== A Short History of a Long Travel from Babylon to Bethel

An Allegory

by Stephen Crisp

In the days of my youth, when I lived at home in my father's house,
I heard many people talk of the house of God;
and that whosoever did attain to get into it did enjoy all manner of happiness,
both in this world and that which is to come.
And a great desire kindled in me, if it were possible, to get into the house;
yet I knew not where it was, neither did they who talked of it;
but they had heard the report, and they reported what they had heard.
There were also some books, that had been written by men who had been in that house;
which books did declare much of the joy and felicity they had in the house.
These books I got, and read them over and over;
which did much strengthen my belief in the truth of the reports:
yet by no means could I tell which was the right way.
But so ardent were my desires,
that I thought myself willing to forsake my father's house, my country and all,
and travel anywhere, wherever my legs would carry me, so that I might find this house.

And upon a time, as I was disclosing my mind to a friend upon this subject,
he readily told me,
there were men appointed in every place to guide those who were willing to go there,
and that this was their business, and they had nothing else to do.
When I heard this I was comforted, and desired him, if he loved me,
to make me acquainted with one of those men.
He told me he would; which he did.
When I came to the man,
I let him know of the fervent desire I had to get to the house of God,
of which I had heard such excellent things;
and that I understood he was one appointed to guide any there who were willing to go,
and to persuade people to go, who were not willing.
He very readily answered, and told me,
it was indeed his business to guide all there who were willing to go;
and if I would comply with his terms, and follow him, he would lead me there.
I asked him what his terms were.
He said the way was long, and would lead him from home, and so I must bear his charges,
and pay something besides, to all of which I agreed.

So we set forward on our journey, early in the morning;
but before we had gone one whole day's journey, I saw my guide sometimes stand still,
and look about him, and sometimes he would pull a little book out of his pocket,
and read a little to himself;
which made me begin to believe he knew the way no better than I. However, I said nothing;
but went on following him several days journey after this manner;
and the farther we went, the more my guide was at a loss.
Sometimes he went a little on, and then would look about him, and turn another way,
and sometimes continue again for a while, and then turn again.
So my suspicions grew very strong, and I began to be in great anxiety of spirit,
but said little to him about it.

But one day, as we were traveling along,
we met a man that took notice of my sad countenance and tired condition.
And he spoke very kindly to me; "`Young man,`" said he, "`where are you going?`"
And when I began to tell him something of my travel,
he desired me to sit down upon the grass, in a shady place,
and discourse a little about my journey: and so we did,
and I told him how things had gone with me to that very hour.
While I was telling him my story, my guide fell asleep; at which I was not sorry,
for thereby I had the more freedom to discourse with the man;
and when I had told him all, he pitied me,
and told me (according his certain knowledge) that this
guide of mine had never been to the house,
neither did he know the way to it, but had only acquired some signs of the way,
which he had received, as I or any other may do; and, if I followed him all my days,
I should never be any nearer to it, and should find at last, I had spent my time,
money and labour to no purpose.

This discourse did so astonish me, that I was at my wits end,
and did not know what course to take.
The man seeing what an agony I was in, began to comfort me,
and told me that the house I sought was much nearer than I was aware of;
and if I would forsake my guide,
and follow him he would soon bring me in sight of the house.
"`And,`" said he, "`I am one that belongs to that house, and have done so several years.
And whereas,`" said he, "`you are to bear this man's charges, and give him money besides,
I will assure you, it is not the manner of the guides that belong to this house of God,
to take money for guiding people there.
I myself have been guide to many a one in my time,
but never took one penny of them for it.`"

By this time, as you must assume, oh how my drooping spirits were comforted;
a new hope sprang up, and a resolution to forsake my wandering guide,
and to follow this new one.

Upon which I awakened my guide, and told him my mind.
I paid him what I had agreed for,
and advised him never to serve any poor soul as he had done me: for I see, said I,
you know not the way, except as you have learned about it in some book.
But if book-learning would have served to find this famous house, I needed not you,
nor anybody else to guide me to it;
for though there are very few who have written experientially of it,
yet I have read them all diligently.
But now I have met a man that I judge has more experience of the way than you have,
and I am resolved to go with him; and if you will honestly confess your ignorance,
and go along with us, then come and be welcome;
one guide will serve two travelers in the way as well as one.
But I could not persuade him; so I left him to take his own way as he pleased.

I now set forward with my new guide pretty cheerful;
and he entertained me with a good deal of discourse along the way.
As he went on in a pretty smooth path, and without stopping, he told me,
in a short time we should come in sight of the house; which made my travel easier.
He also told me something of the rules and orders of the house,
at which I was not at all discouraged; for I considered God was a God or order,
and I doubted not but there were good orders in his house,
to which I was willing to submit.
And as we were thus traveling along, he suddenly spoke to me, saying.
"`Yonder is the house.`"
At this I was exceedingly glad; for now I thought I had not spent my labour in vain.
The nearer we drew to it, the more my joy increased; and when I came in view of it,
I pleased myself greatly with looking at it,
and viewing the towers and turrets that were upon it,
and the excellent carvings and paintings with which it was adorned; indeed,
there was as much art in setting it forth as could be imagined.
Oh! thought I, if there is so much glory without, surely there is even more within,
which I shall shortly be a partaker of.

As I was thus contemplating my happiness, and had come within a bow-shot of the house,
we were to go down into a valley; which we did: and in the bottom of the valley,
glided along a small river.
I looked about to see a bridge, but could see none; at which I wondered;
but on we went till we came to the river side;
then I asked my guide where the bridge was.
Truly, he told me, there was none, but we must go through it,
and so must all that go into that house.

I was a little troubled within myself; but he told me he had been through it;
and there was no danger at all.
With that I began to think within myself, have I taken all these pains,
and shall I give up for so small a matter as this?
What would I have gone through when still in my father's house,
to attain to the knowledge of the house of God, and a possession therein.
Not water, nor even fire would have stopped me then,
if I had so sure a prospect of it as I now have.

I told my guide if he pleased to go before me, I would follow him: so in he went,
and I after him; but when I came at the middle,
there it was so deep that the water went over my head.
Nevertheless, I took care to keep my feet to the ground,
and so got well on the other side; and my guide and I went up together very pleasantly.
When we came to the top of the hill, there was a wide plain,
and in the middle thereof stood the house.
So we went quickly and drew near to it;
and there I saw a very magnificent porch at the west end of the house,
and at the door stood a strong tall gatekeeper, to whom my guide spoke,
and said to him accordingly:
-- "`This young man has long had a desire to be entertained in the house of God;
thereupon I have conducted him here.`"
The gatekeeper asked him which way I had come there; and he replied,
he came through the river: and I do not remember he asked me any more questions,
but bid me welcome, and led me into the house, my guide going in with me,
through many turnings and windings into a great hall.

My eyes went to and fro as I went about the house; and in the great hall,
there I saw many people, who bade me welcome, but none knew the anguish of my soul;
for I began to question whether I was not again deceived:
for I found the house foul and dirty, in almost every part,
and so filled with spiders and cobwebs,
that I thought to myself it had never been swept clean since the day it was built.
And there were some things I met with that displeased me yet worse, as you shall hear;
nevertheless, a good bed was provided for me to rest upon if I could;
and having little appetite, after I saw how it was made ready, went to bed,
and disposed myself to sleep as I could.
But, alas! sleep departed from me, and my spirits were grievously vexed,
and the cogitations of my mind were many and grievous.
Sometimes I thought of the paintings without,
and how that did not suit the dirtiness that was within, and, if I was deceived,
what course I should take.

After long and tedious thinking, I pleased myself with this thought:
it may be better tomorrow.
So I fell into a slumber a short while, but in the morning before I arose,
I heard two or three contending about some accounts,
in which one charged another with fraud; and the other, instead of vindicating himself,
fell to reviling and insulting, with something of the like kind.
They grew so heated in words, that one threatened to turn the other out of doors,
and drive him back through the river,
and never allow him to come into the house any more.

My heart was ready to burst with sorrow;
and in the anguish of my spirit I arose and went to them.
I told them, I little thought to have found such doings, or heard such language,
in the house of God.
I fear, said I, I am deceived; and have been brought in among you by a fair show,
but I see not the glory, peace, and tranquillity I expected.
So I walked away to another part of the house where I heard a great noise and hard words.
As I drew near, I understood the dispute was about choosing an officer;
and two were striving for it, and each of them had gained a party of followers,
and each party grew hot against the other.
As soon as I could be heard, I spoke to them and told them,
such kind of doings as this did more resemble a place in the world called Billingsgate,^
footnote:[From the time of the Roman occupation until the early 1980s,
Billingsgate was a fish market in London, England,
notorious for the crude and abusive language that resounded through its stalls.]
than the house of God.
I went on a little farther;
and there I heard some women scolding and insisting about fashions in their clothes,
and others about getting their children's playthings from each other.
All this, and much more than I shall mention, greatly increased my sorrow.

I now began to long to speak with my guide that brought me there;
and with diligent search at last I found him, and began with him in this manner:
where have you brought me?
And where are the rules and order you told me were in the house of God?
I have often read of the beauty, order, peace, and purity of the house of God,
but here I find nothing but the contrary.
I fear you have brought me to the wrong house, and have deceived me.
So I rehearsed to him what I had met with;
to which he replied that I must expect men to have their human frailties,
and that men were but men.
He would have persuaded me to be satisfied, and to make a further trial of the place.
And as for the rules and order he spoke of,
they were mostly concerned with foods and drinks,
and about rules for electing officers to rule the house of God; as I would see in time,
if I stayed.
And as to the dirtiness of the house,
he confessed that those to whom the care was committed to keep the house clean,
had not been as diligent as they ought to have been; but he hoped, upon admonition,
they would be more careful.

To all of which I returned this answer: What!
Do you talk of human frailties in the house of God?
That complaint is at large in the world,
but how is it fitting for the house of God into which I have heard none can come,
but such as are redeemed from the earth, and are washed from their pollutions?
For God has said, all the vessels in My house shall be holy;
and they that dwell in the house of God must have pure hearts and clean hands.
And much more I told him of what I had heard and read concerning the house of God.
I also told him plainly, I had let in such a belief of the peace, purity, glory,
and comeliness of the house of God, that I was persuaded that this was none of it;
and where to find it, I knew not; but if I never found it while I lived,
still I would never give up seeking, for my desires were ever after it,
and I thought nothing would satisfy me short of the enjoyment of it.
But as for your house here, said I, I have no satisfaction in it;
it is not the place I seek for, so I must leave you.
His answer to me was, he was sorry I could not be satisfied there as well as he;
but if I could not, he would lay no restraint upon me: for his part,
he had directed me as far as he knew, and could do no more for me.

After our discourse was ended, I got up, and went out, but knew not where to go.
Several in the house threw things after me in a spiteful manner, but none hurt me.
So I wandered sometimes north and sometimes south; and every way that came in my mind.
But wherever I went, the anguish of my soul went along with me;
which was more than any tongue can utter, or pen can declare, or anyone can believe,
except this relation should meet with some one that has experienced the same travail;
which, if it does they will understand.
But so it was, I had no comfort night nor day, but still kept going on,
whether right or wrong I knew not, nor dared I ask anybody,
for fear of being deceived as before.

Thus I got into a vast howling wilderness, where there seemed to be no way,
only now and then I found some men and women's footprints,
which was some comfort to me in my sorrow;
but whether they got out without being devoured by wild beasts, or where I should go,
I knew not.
But in this woeful state I travelled from day to day,
wondering within myself what I had best to do--
whether utterly to despair in that condition,
or whether I had best seek some other town or city, to see if I could get another guide.
The first option I saw to be desperate, but I also despaired of the last,
having been so deceived before;
so that all these consultations did but increase the bitterness of my soul.

One day, as I was traveling in the afternoon, a terrible storm arose,
with hail and thunder, and great wind, which lasted till night, and in the night also.
And being weary, both of body and mind, I laid me down under a great tree,
and after some time fell asleep.
When I awoke and came to myself, it was still very dark; and, looking about,
I saw a small light near me; and it came into my mind to go to it, and see what it was;
and as I went, the light went before me.

Then it came into my mind, that I had heard of false lights, as the ignis fatuus,^
footnote:[Also called a friar's lantern, or will-o'-the-wisp,
the ignis fatuus is a flickering phosphorescent light seen at night,
chiefly over marshy ground,
and believed to be due to spontaneous combustion of gas from decomposed organic matter.
The name came to be used to refer to any deluding or misleading guide.]
and such like, that would lead people out of their way.
But then I thought again, how shall I be led out of my way, when I know no way of safety?
And while I sat down to let these striving thoughts run their course, I took notice,
and beheld the light as near me as at the first, as if it had waited for me.
At this I was strongly affected, and thought within myself,
maybe some good spirit has come to take pity on me,
and to lead me out of this miserable condition.
And so a resolution arose in my mind that I would get up and follow it,
concluding within myself,
that I could not be brought into a much worse condition than I was now in.
So I arose and followed it; and it went at a gentle, easy pace at first,
and I kept my eye straight to it.
But afterwards,
I found that a great part of the luggage and provisions I had got together,
did but burden me in my journey; so I threw away one thing, and then another,
that I thought I could spare, but I kept a great bundle of clothes still by me,
not knowing whether I should need them.

As I thus went on, and the light before me, it led me out of the wilderness,
along a plain country, without trees or inhabitants;
only it appeared as if some few had gone that way before.
The light kept in that strait path, without any winding or turning,
till I came to the foot of a great mountain; and, going up that mountain,
I found it very hard getting up,
and began to consider my large bundle of clothes and garments.
I then concluded that a great many of these were of no use for a traveller such as I,
who did not know how far I should go,
nor whether I should need them if every I was so happy as to attain what I aimed at;
nor whether the fashions would suit the place I was going to.
So I threw away some, and later some more, till nothing was left but what I wore.

Thus, following my guide, I at last got up to the top of this mountain,
where I saw another yet higher.
I also saw a man that asked me where I was going?
I told him I could not well say, but I would tell him where I desired to go.
He asked, where?
I said, to the house of God.
He told me this was indeed the way; but he thought I should never get there.
I asked him, why?
"`Why,`" said he, "`there are in yonder mountain so many vipers, adders, and serpents,
and such venomous beasts, that they devour many people that are going that way.
For my part,`" he said, "`I also was going,
but was so frightened by those venomous serpents, that I was forced to turn back,
and would recommend the same to you.`"
I answered him, friend, I have for a pretty while taken yonder light to be my guide,
and it has directed me along this way, and I see it does not leave me; look,
do you see it there before me?`"
He answered, "`Yes, I see it.`"
Well, said I, I have heard by travelers, that if a man has a fire or a light,
the venomous beasts cannot hurt him; and I intend to quicken my pace a little,
and keep as close to the light as I can.
Come, go along with me and venture it.
He said it was true, he had heard that fire would preserve from them;
but he thought the light would not.
However, for his part, he would not venture his sweet life amongst those beasts;
if I would I might; he wished me well, and so we parted.

I then made haste, and got pretty near the light, and up the second mountain I went;
and when I came almost to the top of it, I saw many serpent's dens and vipers' holes,
both on the right hand and on the left.
The venomous beasts drew near me, and hissed at me, and I began to be in great fear,
and trembled exceedingly.
But many times, when they were ready to sting me, the light would step in,
or appear between me and them, and then they were frightened,
and ran away into their holes and dens.

Oh! when I perceive this, how did my heart leap for joy within me!
My joy abounded,--my fear of the serpents abated,--my love to my kind
and tender guide increased,--my courage and confidence were renewed,--
and I began to believe I was in the right way to attain my desire.
So on I went, keeping my eye to the light through them all, without harm,
till I came to the top of the mountain.
Then I saw an exceedingly large valley, so that I could not see the farther side of it.
It seemed to be all wasteland, or places of water, and bogs and mire all over the valley,
which began again to dishearten me.
But, thought I, what shall I do?
All has been well till now.
I was strangely delivered from the serpents; and whatever comes of it,
if this light does not leave me, I will follow it, even if it be through fire and water.

So I kept on, and went down the mountain, a gentle easy pace,
and saw many of those cruel creatures by the way, who put out their stingers at me,
but none hurt me.
And I took notice that the nearer I kept to the light, the more they kept from me.
So I got down to the bottom of the mountain, into the large valley,
which was very green and pleasant for a little way; but by and by,
the light went toward a great low ground full of
water that I thought looked very dangerous;
but coming just to the side of the place,
I saw a small narrow path that ran through the middle of it,
just broad enough for a man to walk upon it.
Into that narrow way the light led me, and went before me.
While I kept my eye steady to it, I went on safely;
but if at any time I began to gaze about, my feet slipped into the mire and puddles,
and then I had much difficulty to get onto the path again.
Had not the light kindly and tenderly waited for me,
I would certainly have lost sight of it, and perished in the way;
for sometimes it was so far ahead of me that I could hardly discern it;
and then I would quicken my diligence, and be more careful of my goings,
and keep as close to it as I could; so that sometimes the light shone round about me,
and I walked in the shinings of it with great fulness of spirit.

After a long time walking in this narrow way,
I lifted up my eyes to the farther side of the low and wet valley,
and saw beyond that there was a very high mountain,
and on the top of it there was a great house:
at the sight of which I was greatly comforted,
supposing that this might be the house I had sought for so long.

But right after this I met with another sore exercise:
for there were many who I perceived had been traveling in this narrow way,
but had fallen into the mire; some on the right hand and some on the left.
These lay wallowing full of envy; some reaching for me to pull me in;
others throwing mire and dirt upon me to discourage me: others would speak very fair,
on purpose to draw me into discourse with them,
that while thus spending my precious time,
I might be left so far behind as to lose the sight of my good guide.
But I saw their evil designs, and was aware of them.
So, keeping in my narrow way till I came to the end of the boggy valley,
I then found firm ground under me feet, to my great comfort.

I had gone but a little way, when my guide, the light, went into a narrow lane,
well hedged on both sides; at which I was glad, thinking I could not go wrong,
and need not now take so much care.
But alas!
I quickly found so many by-lanes, and ways,
which lay almost as straight forward as that I went in,
that if it had not been for the light, which went a little before me,
I might certainly many times have gone wrong.
But by carefully keeping to my good guide, I at last got up the mountain,
and saw the house again.
I then spotted a man of that country, a pretty way off, and called to him, friend, ho!
Friend, what is the name of yonder great house?
He told me the name of it was BETHEL.
Then I presently remembered that that was the name by which
the house of God was called in my father's country,
where I had heard the reports of it, and so earnestly set out to find it.

Oh! the joy and consolation that I felt in my soul,
no tongue can express,--to think that now after all my travels, perils,
and disappointments, I had found what I sought for.
So on I went, journeying with joy unspeakable; and as I went,
I viewed the outside of the house: it was very large, and had but one tower;
there was no carved work about it, no painting,
nor any kind of design that could be discerned;
but all the stones were curiously joined together from the top to the bottom.
I also took notice, that all the stones of the building were transparent,
some more and some less; and I saw no windows.
And, drawing nearer to it, I saw it had a large outward court,
with a pretty large gate to go into it,
so that a man might go in with a large burden on his back.
So, coming to it, in I went; and there I saw many people that were very cheerful,
and appeared to live very pleasant lives.
Some of them told me, they had lived there many years, were well contented,
and lacked nothing; for there was a mighty tree that grew in the midst of the court,
and the fruit thereof was good, and the leaves also, and it bore fruit all the year long.
And many were so kind as to invite me to sit down and eat with them; but that I refused;
and they showed me a great cistern which they had hewn out for themselves,
to catch water from the elements;
and they had made themselves convenient lodgings
in the sides of the outer court to lodge in.

But this did not satisfy me; for I saw my beloved guide pass through them all,
and enter in at a narrow door at the farther side.
Whereupon I left them, and made haste towards the door, where I saw my guide had entered.
I attempted to enter in there, but could not, it was so narrow;
which put me in great sorrow of mind, and what to do I knew not.
My thoughts troubled me on every side, and I tried all ways, but in vain.
Oh! thought I, are all my troubles and labors come to this?
Must I be shut out at the last?
What shall I do?
As I was thus perplexed within myself, I thought I heard a voice,
but knew not from where it came, which said, "`Young man, strip off your old garments,
and so you may enter.`"
This occasioned yet more trouble of mind; for I was reluctant to go naked:
but I at least thought it is better to go in naked, than not at all.
So at last I began stripping,
thinking that a few pitiful rags should not hinder me of so great an enjoyment.
And when I was stripped stark naked as the day I was born,
I tried to enter and found no great difficulty.
And just as soon as I had entered,
one met me and cast a garment of pure white linen over me, which reached down to my feet.
He brought me into a narrow room and said, "`Rest here awhile.`"
Then I laid down in so much joy and comfort as is impossible to be expressed.
All things were so pleasant about me, and my resting place was so delightful,
and my heart so fully satisfied, that it overcame me with songs of joy.
But I found it my business to be still and quiet in my happy condition,
that I had come to enjoy.

I had not been long in this room,
before I went out to see the beauty and loveliness of the house.
As I walked through it, I found everything so clean and bright,
that I was ravished in an admirable manner.
I also met with some people that welcomed me to the
house of God with such kindness as refreshed my heart:
and as I came to be acquainted with them, I marked their conduct,
and their discourses were exceedingly comfortable to me.
There was no quarreling, no contention, no proud nor angry words,
but all passed with meekness and reverence, and due respect one for another.
The young men waited for the words of the ancients,
and the virgins carried a reverent respect to the matrons;
and there was a universal concern and unity, so that I marveled greatly.

One day as I was opening my mind to an ancient, I told him I admired much,
and marveled greatly at the universal concord that I had taken notice of,
beyond all I had ever met with in my life.
He told me it must be so, and could not be otherwise, for the guide that led me here,
had been the guide of them all.
And further told me,
there could be no contention except where two spirits strove for mastery;
but it was not so in this house.
His answer was so full and satisfactory to me, that I said no more to him at that time,
but went on viewing, and beholding the order of everything, till my soul was filled,
and I could say my cup did overflow.
So my former labors and disappointments, sorrows and perils, now meant nothing to me,
having found a full reward, a hundred fold.

So, I returned to my rest again, in a larger room than before, singing praises to my God,
and declaring the praises of the house, and of those that dwelt therein.
And awhile after, I was called forth from the room where I was,
and told I was not brought to that place only to take pleasure and delight therein;
but there was work to be done, and I must take my part of it,
and be faithful and diligent in my employment.
To this I answered,
it was enough that I had attained my desires in being admitted into this heavenly place;
but if there was any business that I could do, I was willing to do it,
whatever it may be;
for it would be my greatest joy to do anything to the
advancement of the honor of the house of God,
and those who dwelt therein.
Then he that talked with me,
told me it was my work to teach the children so far as I had come to know,
and had learned, and as far as I should from time to time be further instructed.
I was a little amazed at this, knowing my inabilities:
but having a little pondered that part of the sentence,
that "`I should be from time to time further instructed,`" I took courage in my work,
and made some progress in it, with great fear and reverence;
waiting daily for those instructions that I was to receive,
and which I did receive in an abundant manner.
So the work did prosper in my hand, and the children loved me, and I loved them entirely,
as though they had been my own children:
and many of them grew up to a good understanding,
and observed their places and orders to my great delight.

After I had thus continued a while,
he that talked with me came and told me I must
take the charge of that part of the household,
and give them their food in due season;
and divide everyone's food according to their state and condition,
and not feed strong men with milk, nor babes with strong meat.
And for this purpose he gave me a key that led into the treasury or store-house;
which I came to see and behold was abundantly filled with all sorts of nourishment,
that never could be exhausted or spent while the world endured.
And here I observed that whatever I and others took out
to distribute daily among the household of God,
still the store-house remained full as at the beginning, and so continues to this day,
and forever.

And now, having continued a long time in this heavenly habitation,
it comes into my mind to let my countrymen, and the children of my old father,
whom I left in Babylon, hear of me;
for I suppose they must judge me to be lost or devoured.
But I could be glad if any, yes, all of them,
were here to behold and taste and feel what I do.
And let none of them say that it happened better with me than with many;
for I have understood, since coming into this house,
that the same Light which appeared to me,
does appear to any poor distressed soul in the whole world;
but the reason that so few come here is because they
fear the perils and dangers that are in the way,
more than they love the Light that would lead them through them; and so they turn aside,
and shelter themselves in an old rotten building,
that at one time or other will fall on their heads, and they perish in the ruins.

Now if any have a mind to know my name,
let them know that I had a name in my father's country,
but in this long and tedious journey I have lost it.
But since I came here I have a "`new name,`" but
have no letters or characters to signify it by,
that I can write, or they can read.
Yet if any will come where I am, they shall know my name.
But for further satisfaction, I will say this: I was born in Egypt,
spiritually so-called; and my father went and lived in Babylon,
about the time the true children of Israel were in captivity.
There I became acquainted with some of the stock of the Jews,
about the time they were returning to their own land;
and they told me wonderful things of the glory of the house they had at Jerusalem,
and would have had me go with them.
And I understood that Solomon, with many thousands of carpenters and masons had build it;
upon which I considered within myself,
that if Solomon and the carpenters and masons had built it,
then carpenters and masons might at one time or another pull it down again.
So I went not with them, but sought a city whose builder is God; and now I have found it;
Hallelujah in the Highest; glory, honor, and renown to his worthy Name and power,
throughout all ages and generations.
Amen.