[quote.epigraph, , Ecc. 2:26]
____
For God gives wisdom and knowledge and joy to a man who is good in His sight.
____

== The Life of Stephen Crisp

Oh, all you saints, and all you inhabitants of the earth,
let the name of Jehovah be famous among you, for there is no God like unto Him!
Let His mercies and judgments be remembered and recorded from generation to generation;
for infinite is His goodness, and His lovingkindness unspeakable.
And although no man can fully recount His lovingkindness reached out to him,
yet let all men testify of His goodness,
and declare of His mercies by which He is drawing the sons of men to Himself,
and winning and gathering the scattered to the true rest.
Therefore, David well said,
"`I will remember the years of the right hand of the Most High;
I will remember the works of the Lord: surely I will remember His wonders of old.
I will meditate on all Your works, I will talk of Your doings.`"
(Ps. 77:11-12) Who can feel His goodness and partake of His love,
and not be constrained to testify of Him?

In the sweet remembrance of His manifold, innumerable mercies, I am even overcome.
For my whole life has been as a continued series of mercy and goodness,
and all my days He has been my upholder.
When I knew Him not, He was near unto me; yes, when I rebelled against Him,
He ceased not to be gracious; His covenant stood with His Seed Christ,
and for His sake He spared me.
His long-suffering and patience were extended towards me,
or I would have been cut off in the days of my resisting Him.
But oh, well may I say He is a gracious and merciful God, long-suffering,
patient and full of compassion.
Oh, let His name be proclaimed to the ends of the earth,
and let the ears of the heathen be opened to hear the sound of His praise.

Surely the Lord has had an eye of tender compassion
upon me from the day that He formed me,
and has appointed me to His praise, and to witness forth His goodness.
For as soon as I can remember, and as soon as I was capable of understanding,
He made me understand that there was something in me which did not consent to any evil,
but rather stood in my soul as a witness against all evil.
This manifested that I should not lie, nor steal, nor be stubborn or disobedient,
but should behave myself in meekness and quietness;
and it also set the truth before me as that which was better than falsehood.
This same witness, even in the days of my childhood,
ministered peace and boldness to me when I hearkened to its counsel.
But there was a contrary nature and seed in me that was of this world, and not of God.
This nature, I found, inclined unto evil, and unto the way and manner of this evil world,
pleasing the carnal mind.
And an eye began to open in me that saw what was acceptable with man,
rather than what was well-pleasing to God.

Now as this eye was daily strengthened by various objects and examples of vanity,
a delight sprung up in me for that which was evil,
and my senses became exercised with vanity,
by which the pure Seed became oppressed and grieved from day to day,
and began to cry out against me.
Condemnation began to be stirred up in me,
and fear entered where before there was no fear, and the pure innocency was lost.
And then, when at any time I did or spoke any evil, the divine Light,
or pure Seed in me would manifest it to me, and show me that I ought not to have done it.
I felt condemnation, which I knew not how to escape.
But then the evil spirit (which leads into transgression)
would always stand ready to help in this time of need.
Sometimes it stirred up a subtlety in me to plead a reason for what I had done,
or a provocation, or a good intent, or else to deny, or at least to mitigate,
the evil of my deed, and so to stop the mouth of the witness of God,
and see if I could escape the condemnation of
the witness of God and so procure my own peace.

But alas, this was a miserable help!
For the light would often shine through all these pretenses and silence my reasonings.
It showed me when I was but a child, in a pure understanding that is from God,
that there is no good reason for any evil, let provocations, temptations,
or examples be what they may.
So was I often stripped naked from all my reasoning and coverings;
and then I learned another way to get ease from the judgment.

When I was very young, about seven or eight years old,
whenever judgment overtook me for evil, I would yield that it was true and right,
and therefore concluded I must do something to please God again.
And so I learned to pray, and to weep in secret,
and to make covenant with God for more watchfulness,
and so for a time I felt unburdened from my weight.
Yet this also was accompanied with many doubtings and questionings,
as to whether my evils were indeed blotted out,
especially when I saw that I was quickly overtaken by the same evil spirit,
and led again into the same evil thoughts, words, or actions.
For the witness of God in me cried even then to have my whole mind given up to the Lord,
and that in every thought, word, and deed I should serve Him.
I did not then know that this pure witness was from God,
but this I knew--that I lacked power to answer its requirings in me,
which witnessed against evil.
And so I had sorrow day and night.

When I was about nine or ten years old,
I sought the power of God with great diligence and earnestness,
with strong cries and tears.
If I had possessed the whole world,
I would have given it away to know how to obtain power over my corruptions.
And when I saw the carelessness of other children, and their profaneness,
and that they did not (as far as I could discern) think of God,
nor consider His reproofs,
though they were far more wicked than I in their
speech and actions--"`Oh Lord,`" I thought,
"`What will become of these?...seeing so heavy a hand is upon
me that I can find neither peace nor assurance of Your love!`"

Then the enemy would tempt me to rest and be quiet,
urging that things were better with me than with others.
And indeed, my mind strongly desired to make a peace for myself here.
But the pure witness followed me and left me not alone, pursuing me night and day.
It broke my peace faster than I could make it up, for my mind was in my own works,
and I could see no further than myself.
I heard talk of a Christ and Savior, but I did not truly know Him.

At that time I lent my ear to the discourses and disputes of the times,
which were very many, and through them many ideas were let into my mind.
Sometimes I heard men argue that God sees no sin in His people.
"`Then,`" said I, "`I am surely not one of them,
for He clearly marks all my transgressions.`"
At other times,
I heard men talk of an election and a reprobation of persons before time began.
I considered this diligently and thought, if it were so,
and if I could find signs and marks of being an elect soul, it might bring me to peace,
and I would not be so tossed as I had been.

I grew to be a very diligent hearer and regarder
of the best ministers (as they were reputed),
and went with as much diligence and cheerfulness to reading and
hearing sermons as other children went to their play and sports.
And when I heard anyone speak about that point of election,
and how a man might know if he were elect--for (in their dark
wisdom) they would often lay down signs of a true believer and
an elect soul--then I would try myself by their measure,
and weigh myself in their balance.
In doing so, I would sometimes gather a little peace for myself,
finding such things in me as they described as signs, such as a desire against sin,
a loathing myself for sin, a love to those that were counted the best people,
a longing to be rid of sin, etc.

But alas, here was still the blind leading my poor blind soul!
This was not the balance of the sanctuary,
and so when I had gotten a little peace and quiet, and desired to hold it, alas,
it was soon shattered and broken again!
For when God`'s pure witness arose in me, by which I was weighed in the true balance,
then I found I was far too light!
And then an anguish would again be kindled in me, and a cry would come forth,
"`Oh where shall I go, and what shall I do, that I may come to a settled state,
before I go from here and am seen no more!`"

In this woeful condition,
the thought of death would bring a dread over both soul and body.
Indeed, trembling and horror were often upon me,
fearing that I was set apart as a vessel of wrath and
so must bear the fiery indignation of God forever.
And oh, that word forever would often seem terrible to me;
but how to prevent this I did not know.

Now I began to perceive more clearly my own insufficiency and lack of power,
for I saw that it was not in my power to keep myself from sin.
I knew that the wages of sin was death,
and so I came to a great crisis--sometimes thinking I had better give up seeking,
and sometimes thinking that if I perish I had better perish seeking.
Here the good got the upper hand for a season, and I became a diligent seeker,
and prayer, and mourner, and would often find the most secret fields and unusual places,
and there pour out my complaints to the Lord.

When I was but about twelve years old,
my general and constant cry was for the power by which I might overcome corruptions.
And though I heard the teachers of those times
daily saying that none could live without sin,
and the doctrine of perfection was held as a dangerous error,
yet that did not abate my cry (though indeed it did often weaken my belief of obtaining,
and so made my prayers almost faithless and without success).
For I knew that without the power of God I must perish, let them say what they would,
and I could not reckon myself saved while I was still
captivated by a corrupt and rebellious nature.
I remembered the words of Christ,
"`He that commits sin is the servant of sin,`" and indeed, I knew I was.

In this iron furnace I toiled and labored, and none knew my sorrows and griefs,
which at times were almost intolerable.
Indeed, I often wished I had never been born,
or that my end might be like the beasts of the field, for I considered them happy,
not having such a bitter combat as I had here,
nor likely to endure what I feared would be my portion hereafter.
I saw my misery clearly, but I saw no way to escape it.

Then I thought I had best not keep my misery to myself,
but disclose it to some who might be able to help me.
But in truth I can say, I found them all to be miserable comforters;
for they counseled me to apply the promises of God by faith,
and to suck comfort out of the Scriptures.
And they spoke to me of the apostle`'s condition
mentioned in the seventh chapter of Romans,
and told me it was this way with him, and yet he was a servant of Jesus Christ.
So they offered me this and other deceitful coverings (with
which they had also covered themselves),
not considering how the apostle called that a wretched and an undelivered state,
as I might well do mine.
But all these things found but little place in me, for my wound remained unhealed.
And He that wounded me and was able to heal me, was near to me, but I knew Him not.

I went groping in that dark and dismal night of darkness,
seeking the living among the dead, as many others did;
but it was so dark that we could not see one another.
As for the priests and professors of those times,
most of them would boast of their experiences and zeal,
and of their assurance of the love of God,
and what comfort they enjoyed by meditation upon the suffering of Christ for their sins, etc.
"`Alas!`" thought I, "`I can think of these things as well as you,
but my wound remains fresh, and I see that I am like one of the crucifiers,
as long as I live in the sin for which He died.`"

My soul longed after some other kind of knowledge of Him,
besides that which could be attained by reading, for I saw that the worst,
as well as the best, could attain such a knowledge.
So I dared not lean upon the priests as much as I had done,
and began to be somewhat more detached in my mind from
them (though I did not yet leave them entirely).
I then began to seek out the meetings of those called Separatists,
to hear their gifted men (so called),
whose doctrine savored more of zeal and fervency than most of the priests did.
These seemed to me not so covetous to make a gain of preaching,
though I could not then see how they coveted greatness and the applause of men.
I was often affected with their preachings,
but still the former bond was upon me (and they yet strengthened it): namely,
the thought that if I were not elected, I could not be saved; and how I might know,
no man could tell me to my satisfaction.
The fear of this would often dash my comfort.

I then began to take notice of the loose walking of such Separatists, yes,
even the teachers among them.
I saw that they were not yet redeemed from foolish jesting, from idle words,
and from anger and passion which sometimes broke out brother against brother,
and so resulted in breaches and schisms, and the rending of their churches,
which they often both built and pulled down with their own hands.
I also saw how inconsistent they were, sometimes letting in one doctrine,
sometimes another, tossed by various winds.
But I heard not a word about how I might obtain power over sin.
Over some sins and some lusts I had power, but over all I did not,
and nothing else would satisfy me.

When I was about seventeen or eighteen years of age, I began to seek yet further,
and hearing of a people that held forth the death of Christ as available to all men,
I went to hear them.
After some time I came to see that there was more light,
and a clearer understanding of the Scriptures among them.
So I began to be conversant with them, and to frequent their meetings,
and I came to be established in the belief that there was a dear Son of hope,
and a way of salvation prepared for all people,
and that none were excluded by an eternal decree (by name or person),
but only because of unbelief and disobedience.

This ministered comfort for a while, and I determined to believe,
and to get faith in Christ, and to reckon myself a believer,
but I found this a hard work, even too hard for me,
though I cried aloud many times to have my unbelief helped.
When I saw sin prevail over me I said, "`Alas,
where is that faith that purifies the heart and gives victory?
Mine is not such!`"
Then the pure witness of God would arise and testify against me for my sin,
and the more my understanding was enlarged, the sharper was my judgment.
Indeed, it grew so sharp,
that I knew not how to endure it as well as I had done in my childhood.
The rough and rebellious nature had now grown strong, and I,
being in the prime and strength of my youth,
and seeing how others spent their time in pleasure and vanity,
a secret lust and desire was kindled in me to partake of their cup.

For a time I took delight in the wits and inventions of men in previous times,
which I found in books.
I was much given to reading,
and so gathered many sayings and sentences of wise philosophers and sages,
and in part obtained the knowledge of many ages gone before me.
These things I thought were like an ornament fitting me for discourse,
and for the company of wise men.
But alas, all this grew up while self stood uncrucified,
and all that I obtained was but sacrificed and
offered up for the obtaining a self-reputation,
which should have been yoked by the cross.
Yet all this served for a while to feed that unwearied, searching,
and seeking soul of mine.
I met with many things that seemed to give life to my soul for a season,
and I began to bless myself that my time was no worse spent.

In this time I found two drawings in me:
one strong drawing and enticement was into the world,
wholly to give myself up to the pleasures, delights, and vanities of it;
the other drawing was unto godliness, watchfulness, and seriousness.
And I (poor man!) knew not what to do with regard to religion.
Indeed I felt a religious inclination in me as I had from a child,
and could have been well content to have taken up some form of Christian profession,
but I was sorely discouraged, not finding any that held forth what I needed,
either in their life or doctrine, namely: power over corruptions,
without which I knew all religion would be in vain,
and would not answer the end for which I should take it up.

So I desisted taking up any particular form of worship,
and kept in the wild field of this world, wandering up and down,
sometimes to one sort of people, sometimes to another.
I took a careful inspection into the lives and doctrines of all sorts, though I confess,
I left my own garden undressed until many troublesome weeds overgrew it.

I began to lose my tenderness of conscience, which I had had,
and began to take pleasure in the company of the wicked.
In many things I came to be like them,
becoming captivated more than ever with laughter and amusement.
I would often sing when I had cause to howl and mourn, and fell to gaming and pastimes,
and presumed upon the mercy of God.
I had a secret belief that God would one day manifest His power,
and bring me out of this state.
I therefore often had a dread upon me of running
as far into wickedness as some others did,
and was kept from many gross evils that my companions ran into.
Herein was the infinite goodness of the Lord manifest, which,
when I came to see with a true eye, it broke my heart.
Yes, my heart and soul praises the Lord for His mercy, who kept me when I knew Him not.
And though the provocations and temptations that attended me were many,
yet I was preserved out of many abominations.
Indeed, I must say and acknowledge (as the Lord said to Abimelech),
it was the Lord that kept me.

This course of life went on for a season, about two or three years,
until a weariness came upon me.
Many times in the very midst of my laughter and lightness,
the hand of the Lord would be heavy upon me,
and His righteous judgment would kindle in me, and put a stop to my course.
Then I would lament in secret,
and sometimes complain to others of my sore captivity and slavery to sin.
And I often would argue, and confer with those who were counted experienced Christians,
how peace and assurance might be attained.
Some would say by reading and applying the promises,
but I had tried this way so often and so long that it took but little with me now,
and I saw I was in another state than that unto which the promises were made.
Others said the only way was to be obedient to
the commands and ordinances of Jesus Christ,
and to be conformable to the primitive saints in walking in church order and communion.
Here, they said, everyone had the strength of many,
and all the church was bound to watch over every member.

I hearkened to these counselors, and was willing to do anything to find the power.
So I took up the ordinance (as they called it) of water baptism,
expecting then to have found more power than before.
My will wrought strongly to bridle and keep down the airy part and sinful nature,
and for a season I strove to maintain myself in a better state than before.
However,
I did not feel the virtue that could truly sanctify and
wash me (for my mind wandered abroad),
and the thing that kept me was not the operation of the pure love of God in my heart,
and His grace prevailing in me, but rather an eye to the reputation of my religion,
and a fear that I might seem to have run and acted all in vain.

These things held but for a season, before the temptation grew too strong for my will,
and the devil entered his own ground and prevailed upon me.
Indeed, he led me captive into sin and evil,
and drew me again into vain company and sports, barren delights and pastimes as before.
Then I clearly saw that I still lacked what I had lacked before,
and had grasped but a shadow and caught nothing but wind.
I saw that my baptism came even short of John`'s,
who did indeed baptize with a baptism of repentance that prepared the way of the Lord,
and made His path straight.
But mine failed to do even this, and so fell even shorter of the baptism of Christ,
who baptizes into a fire that burns up all that
is offensive to God and grieves His Holy Spirit,
and also fills with a Spirit who takes delight in nothing that is corrupt.

This baptism I saw was lacking,
and therefore a dissatisfaction began to grow up further in me, both of myself,
and of my way.
I then testified to the elders (so called) of the church,
that God would shortly overturn all our worships and religions (which stood
in outward and carnal things) and would make known some way above them all,
which would stand forever.
When they inquired what that way should be, I confessed I did not know,
but waited to see what it might be.

About those days many busied themselves in talking and
discoursing about a people called Quakers.
I listened to their discourse with great diligence,
but could hear no good report of them, but only harmful things,
and many false and wicked lies.
But I took notice of this:
that they suffered patiently under many cruel mockings and grievous sufferings,
and I did expect that when the way of God was made manifest,
it would surely be hated and persecuted,
though I thought this would not at all deter or
frighten me from acknowledging and walking in it,
once I knew it to be true.
But inasmuch as I heard they held the possibility of perfection in this life,
this was a thing the wisdom of the old serpent would not join with.
I reasoned strongly against this doctrine in that dark,
fallen wisdom in which many are still fighting for sin today.
These I now know to be no better than the host of Magog,
fighting against the Lamb and His innocent life, saying in their hearts,
"`Rule in heaven if You will, but on earth You shall have no place; no,
not one soul to bear rule and sovereignty over.`"
(I do pity thousands who are fighting the devil`'s battles in this matter,
but having faithfully labored with them in my generation, I leave them now,
who are willful and stubborn opposers.)

In this same fallen wisdom I did reason in various ways
(too many now to name) against the truth,
even while I was in death and in the way of destruction.
But I had not yet seen a messenger of this truth, and longed much to see one,
wishing night and day that our parts might be visited by them,
as I had heard others had been.
At last the Lord sent His faithful servant and messenger of His everlasting gospel,
James Parnell, to our town of Colchester, about the fourth month, 1655.
In the twenty-seventh year of my age,
this young man came in the name and power of the Most High God,
in which he turned many to righteousness, both here and in other counties before,
some of whom remain, and many have fallen asleep.

When I saw this man, I thought to withstand him, for he was but a youth,
and I knew not the power or Spirit that was in him.
I began to ask questions and to seek discourse with him,
but I quickly came to feel that the Spirit of sound judgment was in him,
for the witness of God arose within me, and testified to His judgment,
and signified that I must acknowledge it as being just and true.
On the same day and hour I testified that all our rods
of Christian profession would be devoured by his rod,
(alluding to the rod of Moses and the magicians of Egypt),
which is and shall certainly come to pass.
Later that day I went to a meeting,
and heard him declare the everlasting gospel in the name and authority of the Lord,
which I could not withstand with all my wisdom and knowledge.
Instead, I was constrained to acknowledge and confess to the truth.

[.asterism]
'''

+++[+++Editor`'s Note: James Parnell is said to have been "`young, small of stature,
and poor in appearance,`" but thousands were made to
confess that "`he spoke as one having authority,
and not as the scribes.`"
He was convinced of the Truth when only fourteen years of age,
and became a mighty preacher and promoter of the gospel by sixteen.
Following a debate with a prominent priest,
Parnell was arrested on spurious charges of being an "`idle
and disorderly person,`" and imprisoned at Colchester Castle.
There he was confined to a small hole in the thick castle wall,
twelve feet above the ground.
He died from sickness and ill-treatment after ten
months imprisonment at the young age of nineteen.
The following letter of James Parnell was addressed to Stephen Crisp,
probably a short time after their first encounter and Crisp`'s convincement.

[.embedded-content-document.letter]
--

[.salutation]
Friend,

Stand in,
and keep your mind to that which lets you see your enemies to be of your own house.
Your imagination is an enemy; your wisdom is an enemy;
that which has been precious to you is now your greatest enemy.
Therefore, you must now sacrifice what you have called precious,
and yield it up to death, that the Just One may be raised to life,
and the righteous Seed be brought forth to reign in you and be your Head.
In this way the head of the serpent will be bruised.
In your measure, you will come to understand this,
as you dwell low in the Light which manifests your condition;
for "`whatever makes manifest is Light`" (Eph. 5:13).

Let that eye be kept open which the god of this world blinds in the children of the world.
For by this eye, the children of light can see their enemy, and so the tempter is known,
resisted, and denied.
So with this eye set a constant watch, and let not the fool`'s eye wander abroad,
which draws the wandering mind out after visible objects.
Rather, stand in the warfare, giving no place to the enemy or to his delusions,
but be content to become a fool, that all selfish thoughts may be judged.
Then you will receive wisdom from Him who gives generously and
without reproach to discern and know the enemy`'s schemes.
But know that it is in the cross to your own will and
hasty mind that the gift of God is received.
Therefore it is said "`He that believes will not act hastily`" (Isa. 28:16).

Therefore, be not weary of the yoke of the cross, for in faith it is made easy,
and the impatient nature is crucified, and patience has its perfect work.
So be still in the measure of Light which exercises your mind towards God.
Desire after nothing, but let your thoughts be judged, and let the power of God work,
that He may be seen to be all.
And by this principle alone you must be led and act,
keeping in the cross to the carnal part, and denying self,
both in the particular and in general.
And consider not who is displeased, so long as God is pleased,
for in this you give no just occasion of offense to any.
And though there is enmity in the world,
yet as this leads you to walk towards God in faithfulness,
so it also leads you to walk towards man with a conscience void of offense.
So keep your mind to the Light, and be not hasty to know anything beyond your measure,
for this is how Eve lost her paradise.
Rather, lie down low in the will of God and wait upon His teaching,
that He may be your Head,
and you will find the way of peace and dwell in unity with the faithful.
And though you are hated by the world, yet in God you will have peace and well-being.

[.signed-section-signature]
James Parnell

--

After the death of James Parnell,
Stephen Crisp was called upon to write a short testimony to
the character and ministry of James Parnell,
which he did in a spirit that showed a precious remembrance of
Parnell as the instrument of God by which his long wandering
and weary soul was turned to the Truth.
After speaking of the great work of the Lord in those days, Crisp goes on to say:

[.embedded-content-document.letter]
--

Babes have been His messengers, and children have been His ministers,
who in their innocence have received the revelation of His Holy Spirit,
by whom the deep things of His law and of His glorious
gospel of life and salvation have been revealed.
And among these babes,
who came to receive the knowledge of the mysteries of
the Kingdom of God by the working of His divine power,
was this noble child, James Parnell.
He was a vessel of honor indeed, and was mighty in the power and Spirit of Emanuel,
breaking down and laying desolate many strongholds and towers of defense,
in which the old deceiver had fortified himself with his children.
Much might be spoken of this man,
and a large testimony lives in my heart to his blessed life,
and to the power and wisdom that abounded in him.]

--

[.centered]
Returning to Stephen Crisp`'s Journal

[.asterism]
'''

Seeing that my wisdom and reason were overcome by the truth,
I could no longer contend against it.
So then, here, at the very beginning of my convincement,
the enemy of my soul made an attempt to slay me by enticing me to hold truth
in the same part (the natural mind) with which I had formerly withstood it,
and to defend it with the same wisdom with which I had resisted it.
In this way I remained a stranger to the cross that was to crucify me,
but felt at liberty in the talkative and argumentative spirit,
employing my wits and abilities for the truth.
But although I offered the best that my earth would afford,
I soon felt that my sacrifice was not accepted,
and that something else was still called for.
A cry was in me which called unto judgment,
and the earth that had long covered her slain began to be moved,
though not yet removed out of its place.
Great were the struggles of my thoughts,
and a great desire was kindled in me to comprehend the truth in my own understanding,
as I had done the doctrines and principles of other professions.
But all my labor therein was to no purpose,
for a death was determined by the Lord upon my wisdom.
At last I saw that my labor was in vain; indeed,
my fishing could catch nothing all that night while I worked in the dark,
and did not have the guidance of the light.

In this state I continued a month or two,
but then a swift sword was drawn against that wise and comprehending mind,
and a strong hand gave the stroke.
I was hewn down like a tall cedar that at once comes down to the ground.

Then, oh the woe, misery, and calamity that opened upon me!
Yes, even the gates of hell and destruction stood open,
and I saw myself near falling thereinto.
My hope and faith and all else fled from me,
and there remained no props upon which I could rest.
The tongue that was as a river was now like a dry desert;
the eye that desired to see everything,
was now so blind that I could see nothing certainly,
except for my present undone and miserable state.
Then oh, I cried out in the bitterness of my soul,
"`What has all my Christian profession profited me?
I am poor and blind and naked, who thought I had been rich and well adorned!`"
Oh then I saw the harlot stripped and brought into remembrance before God.
I saw her judgment had come,
and I knew not how to escape the fire of vengeance which then broke forth.
Oh, how wretched were my nights, and how sorrowful were my days!
My delights withered even in wife and children, and in all things,
and the glory of the whole world passed away like a scroll that is burned with fire.
Indeed I saw nothing left in the whole world to give me any comfort.
My sun lost her light, and my moon was darkened, and the stars of my course were fallen.
I saw not how to direct my way,
but became as one forsaken in a howling desert in the darkest night.

When I saw what God had done (for I believed this was His doing), I was ready to cry,
"`I am forsaken forever, for never was there a sorrow like mine!
My wound is incurable, and my sickness none can heal!`"
Alas, my tongue or pen cannot express the sorrows of those days,
in which I sat down in silence, fear, and astonishment,
and was encompassed with sorrow and darkness.
I knew none to whom I could make my complaint.
I heard of joy and salvation,
but could scarcely think that I should ever be a partaker of it,
for I still lacked that living faith which the
apostle said was "`of the operation of God,
who raised up Jesus,`" the true Seed,
which Seed I still felt groaning in me to be delivered from the burden of sin,
and from the oppression of the carnal mind.

After long travail, strong cries, and many bitter tears and groans,
I found a little hope springing in me that the Lord (in
His own time) would bring forth His Seed,
even His elect Seed, the Seed of His covenant, to rule in me.
This was given me at a time when the sense of my own
unworthiness had so overwhelmed me in sorrow and anguish that
I thought myself unworthy of any creaturely comforts.
Then did the hope of the resurrection of the just spring up in me,
and I was taught to wait upon God, and to eat and drink in fear and watchfulness,
showing forth the Lord`'s death till He should come to live and reign in me.
Then I waited as one who had hope that God would be gracious to me.
There was something in me that was eager to know the time, how long I must wait;
but I also found a constant cry in me which called my impatience to death.

On one occasion, being weary of my thoughts in the meeting of God`'s people,
I concluded that none was like me,
and that it was in vain to sit there with such a wandering mind as mine.
For though I labored to stay my mind, I found I could not as I desired.
At length, I decided to arise and leave, and as I was going,
the Lord thundered through me saying, "`That which is weary must die.`"
So I returned to my seat and waited in the belief of God for
the death of that part which was weary of the work of God.
I grew more diligent in seeking that death,
that I might know how to put off the old man with his deeds, words, and imaginations,
his fashions and customs, his friendship and wisdom, and all that pertained to him.
So the cross of Christ was laid upon me, and I bore it.

As I became willing to take up the cross,
I found it to be that thing which I had sought from my childhood--namely,
the power of God; for by it, I was crucified to the world, and it to me,
which nothing else could ever do.
And oh, how glad was my soul when I had found the way to slay my soul`'s enemies!
Oh the secret joy that was then in me!
For in the midst of all my conflicts and combats I had this confidence:
if I only take up the cross, I shall obtain victory,
for it is the power of God through faith unto salvation.
And as I have found it to be so in some things, so I shall find it in all things,
in due time.
Then the reproach of the gospel became joyous to me,
though in those days it was very cruel and grievous to flesh and blood.
Nevertheless, I despised the shame for the joy that was now set before me,
for I had a hope I would in time partake of Christ`'s joy, if I would abide faithful.
It was my great care, night and day,
to keep so low and out of the workings of my own will,
that I might discern the mind of God, and do it,
though it be ever so great a cross to my own.

Yet the enemy of my soul followed me closely and very secretly.
And taking notice how willing I was to obey the Lord,
he strove to get up into the seat of God, and to move as an angel of light,
to betray me and lead me into something that appeared like the service of God.
Yes, many sore conflicts did I meet with before I was able to distinguish
in all things between the workings of the true Spirit and power,
and that which was but the dark spirit transformed.
But in that I had now surely tasted the love and goodness of God, I trusted in Him,
and committed the keeping of my soul unto Him in singleness of heart.
Many and daily were His deliverances which He made known to me,
beyond all recount or remembrance of man.
Praise the Lord forever, oh my soul, for He cared for you in your infancy,
and kept you in the days of your distress!

The more I came to feel and perceive the love of
God and His goodness to flow forth upon me,
the more I was humbled and bowed in my mind to serve Him,
and to serve the least of His people among whom I walked.
As the Word of wisdom began to spring in me, and the knowledge of God grew,
so I became as a counselor to those who were tempted in like manner as I had been.
Yet I was kept so low that I waited to receive counsel daily from God,
and from those that were over me in the Lord, who were in Christ before me,
against whom I never rebelled, nor was stubborn.
And I found that the more I was kept in subjection myself,
the more evil spirits were made subject to me,
and the more I was enabled to help the weak and feeble ones.
So the eyes of many came to be upon me,
as one with whom there was a measure of counsel and understanding.

The church of God in those days increased, and my care for it also daily increased,
and the weight of things relating both to the outward
and inward condition of poor Friends came upon me.
And being called of God and His people to care for the poor,
and to relieve their necessities as I saw occasion,
I did it faithfully for many years with diligence and much tenderness.
I exhorted and reproved any that were slothful, and encouraged those that were diligent,
making distinction according to the wisdom God had given me.

I continued to mind my own state and condition,
seeking the honor that comes from God alone.
A cry was in me to keep on my spiritual armor,
for all my enemies were not yet put under my feet.
So I kept my watch, not knowing where the enemy might again appear,
but after a while I found his appearance once more to be very sharp,
upon the following occasion.

About the year 1659, I often felt the abounding of the love of God in my heart,
and there was a cry in me to stand entirely given up to His will,
not knowing or foreseeing what the Lord was intending to do with me.
But His eye saw further than mine.
His love, tenderness,
and compassion wrought so mightily in me that it
extended to all men on the face of the earth,
so that I was made to cry in spirit, "`Oh that all men knew You and Your goodness!`"
And once, as I was waiting upon the Lord, His Word arose in me,
and commanded me to forsake and part with my dear wife and children, father and mother,
and to go and bear witness to His name in Scotland, to that proud, professing nation.
But when this came to pass, I indeed found that all enemies were not yet slain;
for the striving, struggling, reasoning,
and disputing against the command of God that I then met with cannot be expressed.
Oh, how I then would have pleaded my own inability, and the care of my family,
and my service in our particular meeting, and many more things,
and all that I might have been excused from this
one thing which the Lord had laid upon me,
which I had not thought of, nor looked for!

After many reasonings, and days and weeks by myself,
I thought it best to speak of my concern to some of the
faithful elders and ministers of the everlasting gospel,
secretly hoping that they might discourage me in it.
But, quite to the contrary, they strongly encouraged me,
and laid it upon me to be faithful.
So at last I gave up to the Lord, and acquainted my dear wife of the prospect,
which began a new trial, as the enemy worked strongly in her to stop me.
But I kept in much patience and quietness,
and went and visited Friends`' meetings in Essex and part of Suffolk, chiefly to see them,
and to take my leave of them.
In some meetings the Lord would open my mouth in
a few words to the refreshing of Friends,
but I rather chose silence, whenever I might do so.

The winter drew nigh, and something in me would have deferred my journey till next summer.
But the Lord showed me it must not be my time, but His time.
Then I would have gone by sea, but the Lord withstood me,
and showed me it must not be my way, but His way;
and if I would be obedient He would be with me and prosper my journey,
otherwise His hand would be against me.
So I gave up all, and with cheerfulness at last I obeyed.
Near about the end of the seventh month I went forth,
and visited the churches of Christ along the way.

As I went along in Lincolnshire and Yorkshire,
I quickly perceived that the Lord was with me more than at other times,
and my journey became joyful.
And though I was but weak, poor, and low,
yet God gave me acceptance among the elders of His people,
and in every place my testimony was owned,
and various people were convinced of the everlasting truth.
Then I marveled and said, "`Lord, the glory alone belongs to You,
for You have wrought wonders for Your name`'s sake, and for Your holy Seed`'s sake.`"

I arrived in Scotland in the ninth month that year,
and traveled to and fro that winter on foot with much cheerfulness.
Many straits and difficulties attended me, which I forbear to mention,
it being the time of the movement of the English and Scottish armies,
upon which came the revolution of government,
and the bringing back of King Charles II into England.
About the eleventh or twelfth month I returned to England and
traveled into the west to Westmoreland (part of Lancashire),
and then southward, and in about five or six months time,
I was brought home to my wife and children by the good hand of God.
In all my journey I was sweetly accompanied with the presence of the Lord,
and His power often filled my earthen vessel and made my cup to overflow.
Praises forever be to His name!

In all my journey I lacked nothing that was good for me;
for as it was my care in singleness to serve the Lord, so His tender care was over me,
and He supplied me with whatever was needful in my journey.
Nevertheless, all along a secret hope lived in me that,
when the present journey was accomplished, I would be freed from this sort of service,
and have liberty to return to my calling and family.
Yet it proved quite contrary, for when I had been at home just a few days,
it lay upon me to go up to London to visit the brethren and church of God there.
I went in great fear and dread of God into that city,
and having continued there a few days,
departed northward again at the command of the Lord.
Indeed, I found my way prosperous wherever I went,
and great encouragement I did daily receive from the Lord, who blessed my labor of love.
And besides the peace and joy I felt in myself,
I saw the effect of my labor and the travail of my soul made
manifest by many being turned from darkness to light,
and from the devil`'s power to the power of God.
But still trials attended me and a prison became
my portion near two hundred miles from home.
Great and grievous threatenings were breathed out against me,
and I found that the same spirit which wrought in the persecutors,
both in their cruelty and subtlety, strove to work in me also.

But I cried to the Lord, and He helped me, and my faith failed me not.
I fulfilled my service and my testimony,
and at length was delivered from my prison (along with several
thousand others) by a public proclamation from the king.
I then returned to my own house after about an eight month absence.
My heart was set to serve the Lord who had been so good unto me,
yet the hope of being freed from this kind of service continued long in me,
for I found this work every day more weighty than before.
Many false spirits rose up and transformed themselves into the likeness of truth,
yet they were enemies to the life of truth, which are the worst enemies of all.
I saw that Zion`'s enemy, being unable to prevail in any other way,
was now trying a false pretense of holiness and obedience,
seeking to deceive and beguile the simple.
But I cried to God to give me an understanding and discerning heart to
comprehend the snare of the enemy so that I might be a help to the weak,
and He did so.

As I saw the foundation struck at by the enemy,
I grew zealous for the Lord and His house,
and testified freely against the secret deceits of the enemy.
But this became the occasion for even more exercise and sorrow,
for many who could not see the depths of the workings of Satan judged
my zeal and fervency against that contradicting spirit to be needless.
But in meekness and patience the Lord kept me out of the warring and striving mind,
for I dared not strike those whom I knew to be my fellow servants,
but only those that pretended to be so, and yet served and promoted another interest.
These I often wounded with the weapon God had given me,
and those who came to love the judgment were healed,
but many perished in their rebellion and stubbornness.
Indeed, the Lord arose and blasted the work of the enemy,
and opened the eyes of many that were darkened,
and they came to see the end of what had been the troubler of Israel.
Then peace, unity, and true love were restored in all our borders, and my joy was full,
and my cup did overflow with praises and thankfulness
to God who had regarded His heritage and people,
and had delivered them from the devices of the wicked one.

My soul grew daily more in love with Zion,
and there was nothing in all the world as
desirable to me as the prosperity of the gospel,
and the spreading and publishing of the Lord`'s name and truth in all the earth.
This love constrained me to travel with great diligence from country to country,
to make known what God had done for my soul, and to publish the Day of the Lord.
Yes, this Day of redemption (in which the captivity of spiritual
Israel is brought back to the Lord) did prove glad tidings
unto many who received the report and believed it.
These came to behold the revelation of the holy, powerful arm of God,
to their soul`'s satisfaction.
And in most parts of England where I traveled,
I found the Lord daily adding to the church those who were being saved.
In this my joy truly increased,
and I began to be more freely given up to the work and service of God,
and to the ministry of the gospel.

In about the year 1663, I was moved to cross the seas,
and to visit the seed of God in the Low Countries,^
footnote:[The Low Countries consisted of what is now the Netherlands, Belgium,
Luxembourg, and parts of France and Germany.]
which I did with cheerfulness.
Though I was in an unknown land, and with an unknown speech,
I declared the truth to the refreshing of many,
and to the bringing back of some from error-- sometimes through an interpreter,
and sometimes in my own tongue.
Having accomplished that visit, I returned in peace to England.

After awhile, I was again required of God to go down into the north country,
and I labored in the word and doctrine with great
diligence and fervency along the seacoast,
and so down to Newcastle, and somewhat beyond.
Being led by the Spirit, I came back again a different way,
more eastward through the land,
and found throughout my journey that the plant
of God`'s renown was flourishing and growing.
The meetings were large, and the hearts of Friends were enlarged in love to me,
as mine was to them.

Having returned, a heavy weight came upon me concerning the great city of London,
stronger than ever before.
I went up full of might and power, and as the Lord opened my mouth and ordered me,
I daily warned them of the abominations and wickedness that ran among them like a stream,
and I declared the judgments of God at hand upon them for their great wickedness,
which followed speedily both by war and fire, and many more calamities.^
footnote:[Most notably, a war beginning in 1665 between the English and the Dutch,
which ended in a Dutch victory;
the Plague of London in 1665-1666 (in which
between 100,000 and 200,000 persons were killed);
and the Great Fire of London in 1666 which
destroyed 13,200 houses and 87 parish churches.]
After this, in about 1667, it was required of me again to go into Holland,
together with my dear companion Josiah Coale.
We traveled to and fro, and visited the churches about three months and returned.

I went again into the north of England,
my heart being abundantly drawn out towards the noble seed of God in those parts.
The love and tenderness of heart I felt towards them made all travels, labors,
and perils easy,
because I still saw the tender plants of my heavenly
Father in a thriving and growing condition.
I felt the virtue of life daily springing in me,
which was given me to water the heritage and garden of God.
As soon as I felt clear, I returned,
feeling still more and more the care of the church of God coming upon me.
This constrained me to diligence, and to be as swift as I could be,
that I might be as serviceable as possible in my generation,
and keep myself clear of the blood of all men,
which I found to be no easy or slight work.

After I had safely returned,
I found the presence and power of the Lord still
leading me to and fro from country to country.
I was now obedient, not by constraint as formerly, but of a willing mind,
counting His service freedom, and feeling myself freed from the cares of this life,
having learned to cast all my cares upon Him.
After a year or two of more travel in England,
the Lord laid yet more of the weight and care of the
affairs of His people in the Low Countries upon me,
and I found a drawing towards them.
So in the year 1669, I went over and visited the meetings, obtained various new meetings,
delighting to see to the good order and government of
the affairs relating to Truth and Friends.

[.asterism]
'''

__Stephen Crisp continued a faithful and diligent minister in
the Society of Friends until his death in 1692,
at 64 years of age.
During his 35 years of ministry, he was known by all to be a tireless laborer,
an encouraging father in the church, a prolific writer,
and a great sufferer for the cause of truth.
His journal omits or passes over some of his most painful trials,
as though he desired not to call attention to himself.
But he endured frequent abuse from the enemies of the gospel,
suffered several cruel imprisonments, lost two wives in the course of his pilgrimage,
and all of his children in the plague of 1665.
Through all, Stephen Crisp leaned on the mighty arm of the Lord,
and found His grace to be sufficient in everything.
On his deathbed he was heard to say,
"`I desire the Lord to deliver me out of this troublesome and painful body.
If He will but say the word, it is done.
Yet there is no cloud in my way.
I have a full assurance of my peace with God in Jesus Christ.`"__
