[quote.epigraph, , Eccl. 2:26]
____
For God gives wisdom and knowledge and joy to a man who is good in His sight
____

== A Preface

[.blurb]
=== By way of testimony concerning Stephen Crisp, and his following works.

Although my intimacy with our deceased friend was but of later years,
yet I find something in my mind to write concerning him,
and in commemoration of God`'s blessed power, and word of life that reached him,
and made him through faith and obedience unto the Lord Jesus Christ, what he was;
for that it is which is most worthy of praise, and without it we are nothing,
nor able to do anything that tends to our own peace, or the benefit of others.

It was by this,
the Lord in the morning of this blessed day that he has caused to spring from on high,
visited his soul in this latter age of the world; wherein,
after a night of darkness and time of apostacy, he was graciously pleased,
by that divine and heavenly light, which he,
in the beginning caused to shine out of darkness, to shine into the hearts of many,
and gave unto them the light of the knowledge of his glory, in the face of Christ Jesus,
and made them possessors of this treasure in their earthen vessels,
that were poor and despicable instruments in the eyes of the worldly wise and their own,
yet fitted and raised up by the power of him that raised up our Lord Jesus from the dead,
commissioned and sent forth by the Lord in the evidence
and demonstration of his eternal Spirit,
to publish the glad tidings of peace, to preach the gospel of life and salvation,
and to turn people from darkness to light, from the power of Satan to God;
that they might know remission of sin,
and an inheritance among them that are sanctified through faith in the Lord Jesus Christ,
the true Light that enlightens every man that comes into the world.

This ministry, as it was of God, and these instruments being raised, and sent by him,
he blessed their labours, and made them successful for the good of many.
By the ministry of one of these, though but a stripling, and young in years,
that servant of God, James Parnell, who finished his testimony with his blood,
and left many seals of his ministry in and about that very town of Colchester,
where our dear deceased friend, Stephen Crisp was born, lived, was reached,
and convinced of the blessed truth;
and by the same word that he preached and was an able minister of,
was our worthy friend quickened, and made a serviceable minister of the gospel of Christ,
and freely preached the same about thirty-five years.
He travelled for that end, in many parts of England, Scotland, Holland, Germany,
and the Low countries, endured many hardships, was in several perils,
and suffered imprisonment for his faithful testimony, for the precious truth,
(as by his own journal of his life may more largely
appear,) and through his exercise in the same,
became capable to counsel and advise those that were under sufferings,
and was ready to help them therein.
He exhorted to, and practised charity, and was mindful to do good and communicate,
a sacrifice well pleasing unto God;
and also to assist many in their temporal affairs and settlement thereof;
often pressing Friends thereto, and to do it timely, that no differences, discontents,
or trouble might arise after their decease.
And was very serviceable in his advice to many widows,
and helpful to fatherless children in various respects;
being endued with a good understanding both as a man and a Christian.

And he that endued him therewith, and gave him wisdom, preserved him in it,
and blessed his labours in the gospel, and made his testimony serviceable to many,
it being delivered in soundness of speech, with good demonstration,
and accompanied with life and power.
The consciences of many were so far reached,
that they have been made to confess to the soundness thereof,
and to the power and truth it came from; and have been brought to be made witnesses,
and partakers thereof, and the life and virtue therein,
through faith and obedience to the same.

He was also a man that was zealous for truth, and the several testimonies it led us into,
against the corrupt world, their ways, worship, vain fashions, and evil customs,
and often exhorted Friends to mind the Lord`'s Spirit, and therein to do his business,
and not in their own; nor to boggle or decline their testimony for truth, in any respect,
either against the men-made ministers, forced maintenance,
or their joining people together in marriage for filthy profit`'s sake;
or contributing to the repair of their worship houses; or against wars and fighting;
and greatly disliked that any indirect way should be complied with by any,
to shift or evade their testimony for the truth, in any respect.

Although, in the latter part of his time, he was through infirmity of body,
unable to travel much, yet was he very diligent in frequenting meetings,
and preaching the gospel therein, and to exhort Friends to brotherly love,
provoking them to good works, and pressing them to diligence, and an exemplary conduct,
and to train up their youth and children in that way, plainness,
and simplicity that became the truth, and the humble disciples of our Lord Jesus Christ.
The Lord incline the hearts of all that have them, so to do,
that none may contribute of that substance God has blessed them with,
and made them stewards of, to gratify anything in their children,
which may be to their hurt,
or tend to impede them from succeeding their honest and tender parents,
in that precious truth, and the plainness, humility, selfdenial,
love and tenderness it has led them into,
that the blessing of God may be continued on our offspring; and from age to age,
and by one generation unto another, the Lord`'s worthy name may he praised,
his truth exalted, and he renowned, who is worthy forever.
Amen.

In this holy truth, to our comfort, and his great joy, am I well satisfied,
did this faithful servant of God finish his testimony and course in this world.
And on the twenty-fourth of the sixth month, 1692,
being under much bodily weakness and pain,
he was visited by his ancient friend and brother, George Whitehead,
who gave this account of the same,
as the substance of some-words spoken by Stephen Crisp,
the twenty-fourth of the sixth month, 1692:

"`I see an end of mortality, yet cannot come at it.
I desire the Lord to deliver me out of this troublesome or painful body.
If he will but say the word, it is done.
Yet there is no cloud in my way.
I have a full assurance of my peace with God in Christ Jesus.
My integrity and uprightness of heart is known to the Lord,
and I have peace and justification in Jesus Christ, who made me so, (that is,
upright to God.) Dear George, I can live and die with you; and my dear love is with you,
and to all the faithful in the church of God.`"

On the twenty-seventh, being the day before his departure, he said,
"`I hope I am gathering, (as his expression was understood,) I hope,
I hope;`" being then scarcely able to speak out his words.
George Whitehead near parting from him asked him, "`Dear Stephen,
would you say anything to Friends?`"
After some pause, Stephen Crisp gave his answer:
"`Remember my dear love in Jesus Christ to all Friends.`"

On the twenty-eighth of the said month, he departed this life,
and died in the Lord at Wansworth in Surrey, about four miles from London,
to which place he was carried for the sake of the air,
from the house of William Crouch in London, in a litter,
to William Crouch`'s house there.
Being very weak, he was accompanied by several Friends on foot with the litter,
lest there should be any need of assistance.

After his decease, his body was brought to Grace-church street meeting house in London,
where on the one-and-thirtieth,
a great number of Friends and others met to accompany his corpse to the ground,
and many living testimonies were borne there, by faithful brethren unto the truth.
And then his body was borne on the shoulders of his friends
and brethren that loved him for truth`'s sake,
unto the burying ground at Bunhill Fields, and there interred.

Several testimonies were also borne there at the grave, to the truth,
for the sake of those that yet remain;
and that all might love and live in that which makes
lovely and living unto God and in his sight;
and persevere in diligence and faithfulness in the Lord`'s work and service,
and keep to that Power,
and under the government of that Spirit which only is sufficient
to enable us to follow the steps of them that followed Christ,
and that we might run our race with cheerfulness, finish our course with joy,
lay down our heads in peace, rest with the Lord forever,
and have a place in that kingdom that will never fade away.

That it may be so with all us that yet remain,
is my sincere desire and earnest supplication unto the Lord;
and that we may always abide in that love,
which is the badge or mark of our discipleship,
in that Spirit which is the bond of our peace,
in that Life by which we have been redeemed,
in that grace and faith by which we are saved,
and be armed with the whole armour of light, and walk therein;
that fellowship with God and one another we may know,
and the cleansing virtue of his blood that died for us we may experience,
to cleanse us from all unrighteousness.
Being so cleansed, may we possess our vessels in sanctification,
and continue in the life of righteousness, and in holy fear wait upon the Lord,
to be filled with that wisdom that is from above,
and clothed with the righteousness of Christ, and covered with zeal as with a cloak,
and endued with a good understanding, and guided by his counsel,
and be received into glory, and have the end of our faith, the salvation of our souls;
is the sincere breathing, and tender supplication of him who wishes the good of all men,
and prays Zion`'s prosperity, and the peace of Jerusalem,
that God would make her an eternal excellency, and the praise of the whole earth.

And now having hinted at the author, commemorated the Lord`'s power,
and commended his Spirit, Grace and Truth, by whom grace and Truth came, I shall,
courteous reader, recommend you thereto,
and earnestly beseech you to apply your heart to it.
Let your mind in the perusal of the following writings,
be uprightly exercised therein towards the Lord,
that you may truly savour from what spirit they came, for what end they were written;
and so come to make a right use of them.
By your daily exercise and waiting upon the Lord therein, and living obedience thereunto,
you may be fitted and enabled to succeed in that life, spirit, and wisdom,
which he was endued with.
Dear Friends, it is our great encouragement that yet remain, to be faithful to the Lord,
diligent in his work and service, zealous for his name,
and our respective testimonies for the sake thereof, because that blessed Power, Spirit,
Life and Wisdom, that raised up, fitted, furnished and endued this,
and many more of our ancient, worthy, and honourable brethren, and made them so,
blessed be his holy name, is still with us, and as sufficient as ever.
The Lord is as willing to fill up the places of them he has taken to himself,
into the mansions of eternal glory,
as he was in tender mercy favourably pleased to furnish them for his work and service,
that it may be carried on to his praise, and the honour of his worthy name,
from age to age, and from one generation to another.

And therefore let us that yet remain, be faithful unto the Lord,
freely given up to follow him,
and to manifest our love and respect unto our deceased friend and his works,
by following that wholesome counsel and Christian advice,
he has by word and writing freely and frequently given us;
that so we may by the same spirit and power,
he enabled to follow and succeed him in his work and service, for the precious Truth.

So with the words of our Lord Jesus, the Way and Truth, I may conclude:
"`If a man love me, he will keep my words, and my Father will love him,
and we will come unto him, and make our abode with him.`"
And in that love I desire always to remain, Courteous reader.

[.signed-section-closing]
Your sincere friend and well-wisher,

[.signed-section-signature]
John Field.

[.signed-section-context-close]
George-Yard, London, the 14th of the Third month, 1694.
