== Chapter I.

[.blurb]
=== A Journal of the Life of Stephen Crisp, Giving an Account of His Convincement, Travels, Labours and Sufferings, In and For the Truth.

Oh! all you saints, and all you inhabitants of the earth,
let the name of Jehovah be famous among you, for there is no God like unto him;
and let his mercies and judgments be remembered and recorded from generation to generation;
for infinite is his goodness, and his lovingkindness unspeakable.
And although no man can fully recount his lovingkindness to him reached out,
yet let all men testify of his goodness,
and declare of his mercies by which he is engaging the sons of men to himself,
and winning and gathering again the scattered to the true rest.
Therefore, well said David,
"`I will remember the years of the right hand of the Most High;
I will remember the works of the Lord: surely I will remember his wonders of old.
I will meditate of all your works, I will talk of your doings.`"
Psal. 77: 10, 11, 12.
Who can feel his goodness, and partake of his love,
but it will constrain a testimony to him?
In the sweet remembrance of his manifold innumerable mercies, I am even overcome.
For my whole life has been as a continued series of mercy and goodness,
and all my days has he been my upholder.
When I knew him not he was nigh unto me; yes when I rebelled against him,
he ceased not to be gracious; his covenant stood with his seed Christ;
and for his sake he spared me.
His long-suffering and patience were extended towards me,
else I had been cut off in the days of my gainsaying.
But oh! well may I say he is a God gracious and merciful, long-suffering,
patient and full of compassion.
Oh! let this, his name be proclaimed to the ends of the earth,
and let the ears of the heathen be opened to hear the sound of his praise.

Surely the Lord has had an eye of tender compassion upon me,
from the day that he formed me, and has appointed me to his praise,
and to witness forth his goodness.
For so soon as I can remember, and so soon as I was capable of understanding,
he made me to understand that which consented not to any evil,
but stood in my soul as a witness against all evil; and manifested that I should not lie,
nor steal, or be stubborn, or be disobedient,
but should behave myself in meekness and quietness, and set truth before me,
as that which was better than falsehood.
This same witness, even in the days of my childhood, ministered peace and boldness to me,
when I hearkened to the counsel of it;
but there was a contrary nature and seed in me that was of this world, and not of God,
which inclined unto evil, and unto the way and manner of this evil world,
as most of all suiting the carnal mind;
and an eye began to open in me that saw what was acceptable with man,
rather than what was well-pleasing to God.

And that eye being daily ministered unto by the various objects, and examples of vanity,
a delight sprung up in that which was evil, and my senses became exercised with vanity,
by which the pure seed became oppressed and grieved from day to day,
and began to cry out against me; and condemnation began to be stirred up in me,
and fear entered, where before, no fear was, and the pure innocency was lost.
And then, having at any time done or spoken any evil, the +++[+++divine]
Light, or pure principle in me, would manifest it to me,
and show me that I ought not so to have done.
I felt condemnation, which how to escape I knew not.
But then the evil spirit that led to transgress,
would always stand ready to help in this need.
Sometimes it stirred up the subtlety in me, to plead a reason for what I had done,
or a provocation, or a good intent, or else to deny, or at least to mitigate,
the evil of my deed, and so to stop the mouth of the witness of God,
and to see if I could escape the condemnation of
the witness of God and procure my own peace.

But alas! this was a miserable help, for the light would often shine through all this,
and quell my reasonings; and showed me, when J was but a child,
that in a pure reason that is from God, there is no reason for any evil,
let provocations, temptations, or examples be what they can, or will.
So was I often stripped naked from all my reasoning and coverings;
and then I learned another way to get ease from the judgment.

When I was very young, about seven or eight years old,
I would use when judgment overtook me for evil, to yield that it was so;
and therefore thought that I must do something to please God again,
and so hereupon I learned to pray, and to weep in secret,
and to covenant with God for more watchfulness,
and so I thought for a season I was as one unburdened from my weight.
Yet this best state was accompanied with many doubtings and questionings,
whether my evils were blotted out, or no:
especially when I saw that I was again overtaken by the evil spirit,
and led into evil thoughts, words or actions.
For the +++[+++divine]
witness cried even then to have my whole mind given up to the Lord, and that in thought,
word and deed, I should serve him, but I knew not that it was from God; but this I knew,
that I lacked power to answer the requirings of that in me,
which witnesses against evil in me, and this I lamented day and night.

When I was about nine or ten years old,
I sought the power of God with great diligence and earnestness,
with strong cries and tears; and if I had had the whole world, I would have given it,
to have known how to obtain power over my corruptions.
And when I saw the carelessness of other children, and their profaneness,
and that they did not, (that I could discern,) think of God, nor were in trouble,
though they were far more wicked than I, in their speech and actions; ah,
Lord I thought I, what will become of these?
Seeing so heavy a hand is upon me, I can find neither peace, nor assurance of your love.

Then the enemy would tempt me to rest, and be quiet,
in that it was better with me than with others,
and my reason wrought strongly to make up a peace to myself herein.
But the pure witness followed me, and left me not, but pursued me night and day,
and broke my peace faster than I could make it up, for my mind was in my own works,
and I could see no further.
I heard talk of a Christ and Saviour, but oh! thought I, that I knew him.

My ear was lent to the discourses and disputations of the times, which were very many;
and one while I let in one thing, and another while another.
Sometimes I heard men dispute that God sees no sin in his people; then I said,
surely I am none of them; for he marks all my transgressions.
At other times, men talked of an election and a reprobation of persons before time.
I considered that diligently, and thought, if that were so,
and I could but get so many signs and marks of an elect soul, as might bring me to quiet,
then I would keep it; and not be so tossed as I had been.
I grew a very diligent hearer and regarder of the best ministers, as they were reputed;
and went with as much diligence and cheerfulness to reading, and to hearing sermons,
as other children went to their play and sportings.

And when I heard anyone treat upon that point of election;
and how a man might know if he were elect,
and would in their dark wisdom lay down signs of a true believer,
and signs of an elect soul, then would I try myself in their measure,
and weigh myself in their balance, and so gather up a little peace to myself,
finding such things in me as they spoke of for signs, as, a desire against sin,
a loathing myself for sin, a love to them that were counted the best people,
a longing to be rid of sin, etc.

But alas! here was yet but the blind leading my poor blind soul.
This was not the balance of the sanctuary;
and when I had gotten a little peace and quietness, and thought to hold it, alas,
it would soon be shattered and broken.
When God`'s pure witness arose in me, that I must be weighed in the true balance,
oh then I found I was much too light: then anguish would again kindle in me,
and a cry was in me; Oh where shall I go?
and what shall I do?
that I may come to a settled state, before I go hence and be seen no more.

In this woeful condition, the thoughts of death would bring a dread over soul and body;
and trembling and horror were often upon me,
fearing that I was set apart for a vessel of wrath,
and must bear the fiery indignation of God forever.
And oh, that word, '`forever,`' would often be terrible to me,
but how to prevent it I knew not.

Now I began to perceive my own insufficiency, and my lack of God`'s power,
and that it was not in my own power to keep myself out of sin,
and the wages of it was death, so that I was in a great strait,
sometimes thinking I had better give over seeking, and sometimes thinking,
if I perish I had better perish seeking.
Here the good got the upper hand for a season, and I became a diligent seeker,
and prayer, and mourner,
and would often find out the most secret fields and unusual places,
there to pour out my complaints to the Lord.

When I was but about twelve years old,
my general and constant cry was after the power by which I might overcome corruptions,
and although I heard the teachers of those times, daily saying,
none could live without sin, and the doctrine of perfection held as a dangerous error,
yet that did not abate my cry; though indeed it did often weaken my belief of obtaining;
and so made my prayer almost faithless, and without success.
But I knew that without the power of God I must perish, let them say what they would,
and I could not reckon myself saved while I was captivated
with a corrupt and rebellious nature,
let them all say what they could.
I remembered the words of Christ, He that commits sin is the servant of sin,
and that I knew was I.

In this iron furnace I toiled and laboured, and none knew my sorrows and griefs,
which at times were almost intolerable, so that I wished I had never been born,
or that my end might be like the beasts of the field, for I counted them happy,
for they had no such bitter combat here as I had, nor should endure that hereafter,
that I feared I must endure after all, for I did see my misery,
but I saw no way to escape.

Then I thought I had best not keep my misery so close,
but disclose it to some that may be might help me.
But well might I say, miserable comforters I found them all to be;
for they would bid me apply the promises by faith,
and suck comfort out of the scriptures; and tell of the apostle`'s state,
mentioned in the 7th of the Romans, and tell me it was so with him,
and yet he was a servant of Jesus Christ,
and such like deceitful daubings as they had daubed themselves with,
in like manner dealt they with me;
not considering how the apostle called that a wretched and an undelivered state,
as I might well do mine.
But all these things took but little place in me; my wound remained unhealed,
and he that wounded me and was able to have healed me, was nigh me, and I knew him not.

I went groping in that dark and dismal night of darkness,
seeking the living among the dead, as many more did,
but it was so dark that we that did so could not see one another.
As for the priests and professors of those times,
the most of them would boast of experiences, and of zeal,
and of assurances of the love of God,
and what comfort they enjoyed by thinking or meditating
on the suffering of Christ for their sins, etc.
Alas! thought I, I could think of these things as well you,
but my wound still remains fresh, and I see that I am as one of the crucifiers,
while I live in sin, for which he died.

My soul longed after some other kind of knowledge of him,
than that which was to be attained by reading, for I saw that the worst,
as well as the best, could attain to that.
I dared not lean upon them so much as I had done,
but then I began to be somewhat more loosened in my mind from the priests,
(though I left them not wholly,) but now began to
find out the meetings of those then called Separatists,
and to hear their gifted men so called, whose doctrine, I took notice,
savoured more of zeal and fervency, than most of the priests did,
neither did I see them so covetous to make a gain of preaching,
not yet being come to see how they coveted greatness and applause of men.

I was often affected with their preachings, but still the former bond was upon me,
and they yet strengthened it: namely, that if I were not elected, I could not be saved,
and how I might know, no man could tell me to my satisfaction.
The fear of this would often dash my comfort,
and then I began to take notice of the loose walking of such Separatists, yes,
even of the teachers among them,
how that they were not yet redeemed from foolish jesting, from idle words,
from anger and passion, and sometimes it broke out brother against brother,
and so ran out to parties, and to breaches and schisms, and rending their churches,
which they often both built and pulled down with their own hands.
I also saw how unconstant they were, sometimes letting in one doctrine,
sometimes another, tossed with winds;
but not a word could I hear how I might obtain power over sin.
Over some sins and some lusts I had, but over all I had not;
and nothing else would satisfy me.

I began when I was about seventeen or eighteen years of age, to seek yet further,
and hearing of a people that held forth the death of Christ for all men,
I went to hear them, and after some time I came to see that there was more light,
and a clearer understanding of the Scriptures among them, than among the former.
So I began to be conversant with them, and frequent in their meetings,
and came to be established in that belief, that there was a dear Son of hope,
and way or means of salvation prepared for all people,
and none positively by any eternal decree excluded, as by name or person,
but as unbelievers and disobedient.

This ministered comfort a while, and I set myself to believe, and to get faith in Christ,
and to reckon myself a believer, and found it a hard work, even too hard for me,
though I cried aloud many times to have my unbelief helped.
When I saw sin prevail over me, alas! said I,
where is that faith that purifies the heart, and gives victory; mine is not such.
Then would the pure witness of God arise and testify against me for my sin,
and the more my understanding was enlarged, the sharper was my judgment.
Now it grew so sharp,
that I knew not how to endure it so well as I had done in my childhood.
The rough and rebellious nature being now grown strong,
and I in the prime and strength of my youth,
and seeing how others spent their time in pleasure and vanity,
a secret lust and desire kindled in me to partake of their cup.

Yet for a time I was kept in as with a bit;
and rather took delight to take notice of the varieties of wits and inventions,
that had been in foretime, which I found by books, being much given to reading,
and so gathered many sayings and sentences of wise philosophers and sages,
and in part obtained the knowledge of many ages gone before me;
and these things I thought were as an ornament fitting me for discourse,
and for the company of wise men.
And alas! all this while self stood uncrucified,
and all that was gotten was but sacrificed and offered
up for the obtaining a reputation to self,
which should have been kept in the cross.
Yet this served me a while to feed that unwearied searching, seeking soul of mine;
and many things I met with, became as a life unto it for a season,
and I began to bless myself, that my time was no worse spent.

In this time I found two drawings, one strong drawing and enticement was into the world,
wholly to give myself up to the pleasures, delights, and vanities of it:
and another drawing was unto godliness, watchfulness, seriousness, etc.
I, poor man, knew not what to do, as to religion.
I saw many persuasions, and felt a religious inclination in me,
as I had done from a child,
and could have been well content to have taken up some form of religion,
but was sorely discouraged,
because I could see none of them hold forth that which I lacked,
either in their life or doctrine, namely, power over corruptions,
without which I knew religion would be in vain,
and not answer the end for which I should take it up.

So I desisted taking up any form, and kept in the wild field of this world,
and wandered up and down, sometimes to one sort of people, sometimes to another;
taking a sharp inspection into their lives and doctrines, though I confess,
I left my own garden undressed, until many noisome weeds overgrew it.

I began to lose my tenderness of conscience, which I had had,
and began to take pleasure in the company of the wicked,
and in many things to become like them,
and came to be captivated more than ever with mirth and gaiety,
I often would sing when I had cause to howl and mourn, and fell to gaming and pastime,
and presumed upon the mercy of God, and had a secret belief,
that God would one day manifest his power, and bring me out of this state.
I therefore had often a dread upon me, of running so far into wickedness,
as some others did, and was kept from many gross evils that my companions ran into;
and herein was the infinite goodness of the Lord manifest,
which when I came to see with a true eye, it broke my heart; yes,
my heart and soul praises the Lord for his mercy, who kept me when I knew him not.
And though provocations and temptations were many, that did attend me,
yet out of many abominations was I preserved, and I must say and acknowledge,
as the Lord said to Abimelech, it was the Lord that preserved or kept me.

This kind of course of life went on for a season, about two or three years,
until a weariness came upon me thereby.
Many times in the very midst of all my mirth,
the hand of the Lord would be heavy upon me,
and his righteous judgment would kindle in me, and put a stop to my course,
and then would I lament me in secret,
and sometimes complain to others of my sore captivity and slavery to sin,
and often would I be arguing,
and conferring with them that were counted experienced Christians,
how peace and assurance might be attained.
Some would say by reading and applying promises,
but that way I had tried so often and so long, that it took now but little with me,
for I saw I was in another state than that unto which the promises were made.
Others said the only way was to be obedient to the
commands and ordinances of Jesus Christ,
and to be conformable to the primitive saints, in walking in church order and communion,
where every one had the strength of many,
and all the church bound to watch over every member.

To these counsellors I hearkened, and was willing to do anything, to find the power,
and reproach should not keep me back.
So I took up that ordinance, as they called it, of water baptism,
expecting then to have found power more than before.
My will wrought strongly to bridle and keep down that airy part and sinful nature,
and for a season strove to uphold and maintain myself to be in a better state than before,
though the virtue that should sanctify and wash me I did not feel, my mind being abroad,
and the reasons that kept me were not the operation of the pure love of God in my heart,
and his grace prevailing in me, to teach me,
but rather an eye to the reputation of my religion,
and that I might not seem to have run and acted all in vain.

These reasons held but for a season, before the temptation grew too strong for my will,
and the devil entered his own grounds,
and prevailed upon me and led me captive into sin and evil,
and drew me into vain company and vain sports, and delights,
and pastimes again as before.
Then I sufficiently saw I lacked what I had lacked before,
and had grasped but at a shadow, and catched nothing but wind,
and that my baptism was short of John`'s,
who did indeed baptize with a baptism of repentance, and prepared the way of the Lord,
and made his path straight.
But mine did not so much, and therefore was much more short of the baptism of Christ,
in which the fire was to be found, that should burn up what was offensive to God,
and grieved his Holy Spirit, and then fill me with his Spirit,
which takes delight in nothing that is corrupt.

This baptism I saw was lacking, and therefore a dissatisfaction began to grow up in me,
both of myself, and of my way; and I testified unto the elders, so called, of the church,
that God would shortly overturn all our worships and religions,
which stood in outward and carnal things,
and would make known some way a-top of them all, that should stand forever.
When they inquired what that way should be, I confessed I knew not,
but waited to see what it might be.

About those days many exercised themselves in talking
and discoursing of a people called Quakers,
after whom I listened, but though I hearkened with great diligence,
I could hear no good report of them, but much harm,
and many false and wicked lies were cast upon them; only this I took notice of,
that they suffered cruel mockings, and grievous sufferings patiently, I did expect,
that when the way of God was made manifest, it would be hated and persecuted;
yet I thought that should not at all deter or affright me from owning it,
and walking in it if once I knew it.
But forasmuch as I heard they held perfection in this life,
that was a thing the old wisdom of the serpent could not reach or join with,
but I reasoned against it strongly,
in that dark fallen wisdom in which many are still fighting for sin,
which is the devil`'s host, whom I now see to be no better than the host of Magog,
fighting against the Lamb, and his innocent life, saying in their hearts,
rule in heaven if you will, for on earth you shall have no place; no,
not one soul to bear rule and sovereignty over.
I can but pity thousands who are fighting the devil`'s quarrels in this matter,
but having faithfully laboured with them in my generation,
I leave them that are wilful and stubborn opposers,
who will in nowise receive that which is perfect in this life,
to receive the wages of imperfection in the life to come.

But I say, in this same fallen wisdom did I reason various ways, too many now to name,
against the truth, the fame whereof I had heard as the scripture speaks,
while I was in death and in the way of destruction.
But a messenger of this truth I had not seen, but longed much to see one,
wishing night and day, that our parts might be visited by them,
as I had heard others were.
At last the Lord sent his faithful servant and messenger of his everlasting gospel,
James Parnell, to our town of Colchester, about the fourth month, 1655,
and in the twenty-seventh year of my age,
who came in the name and power of the Most High God,
in which he turned many to righteousness, both there and in other countries before,
of whom some remain, and many are fallen asleep.

When I saw this man, being but a youth, and knew not the power or spirit that was in him,
I thought to withstand him, and began to query and seek discourse with him;
but I quickly came to feel +++[+++that]
the spirit of sound judgment was in him, and the witness of God arose in me,
and testified to his judgment, and signified I must own it; it being just and true.
On the same day and hour I testified,
that all our rods of profession would be lost or devoured by his rod,
alluding to that of Moses and the magicians of Egypt,
which is and shall certainly come to pass.
That day I went to a meeting, and heard him declare the everlasting gospel,
in the name and authority of the Lord,
which I could not with all my wisdom and knowledge withstand,
but was constrained to own and confess unto the truth.

Here at the very first of my convincement did the enemy of my soul make trial to slay me,
and that after this manner, that seeing my wisdom and reason were overcome by the truth,
I could not therewith withstand it, therefore I received the truth,
and held it in the same part with which I withstood it,
and defended it with the same wisdom by which I resisted it,
and so was yet a stranger to the cross that was to crucify me;
and was at liberty in the discursive spirit, to lay out my wits and gifts for the truth.
But I soon felt my sacrifice (though I offered the
best my earth would afford,) was not accepted,
but something else was still called for.
A cry was in me which called to judgment, and the earth that had long covered her slain,
began to be moved, but not yet removed out of its place,
and great were the strugglings of my thoughts,
and a great desire kindled in me how I might comprehend the truth in my understanding,
as I had done the doctrines and principles of other religions.
But all my labour therein was to no purpose,
for a death was determined upon that wisdom from the Lord.
So I saw my labour in vain,
my fishing could catch nothing all that night while I wrought in the dark,
and had not the guidance of the light.

In this state I continued a month or two,
but then a swift sword was drawn against that wisdom and comprehending mind,
and a strong hand gave the stroke, and I was hewn down like a tall cedar,
that at once comes down to the ground.

But then, oh the woe, misery and calamity that opened upon me!
Yes, even the gates of hell and destruction stood open,
and I saw myself nigh falling thereinto, my hope and faith, and all fled from me,
I had no prop left me to rest upon.
The tongue that was as a river, was now like a dry desert; the eye that would,
or at least desired to see everything, was now so blind,
that I could see nothing certainly, but my present undone and miserable state.
Oh! then I cried out in the bitterness of my soul, what has all my profession profited me?
I am poor and blind, and naked, who thought I had been rich and well adorned.
Then saw I the well favoured harlot stripped, and brought into remembrance before God;
and her judgment was come, and how to escape the fire of the vengeance which broke forth,
I knew not.
Oh, how doleful were my nights, and sorrowful were my days!
My delights withered even in wife and children, and in all things,
and the glory of the whole world passed away like a scroll that is burnt with fire,
and I saw nothing left in the whole world to give me any comfort.
My sun lost her light, and my moon was darkened, and the stars of my course were fallen,
that I knew not how to direct my way,
but was as one forsaken in a howling desert in the darkest night.

When I saw what God had done, (for I believed it was his doing,) I was ready to cry,
I am forsaken forever, and never was sorrow like mine, my wound is incurable,
and my sickness none can heal.
Alas! my tongue or pen cannot express the sorrows
of those days in which I sat me down in silence,
fear and astonishment, and was encompassed with sorrow and darkness.
I knew none to make my moan unto.
I heard of joy and salvation,
but could scarcely think that ever I should be a partaker of it,
I still lacking that living faith, which the apostle said, was of the operation of God,
who raised up Jesus, the true seed,
which seed I still felt groaning in me to be delivered from the burden of sin,
and from the oppression of the carnal mind.

After long travail, strong cries, and many bitter tears and groans,
I found a little hope springing in me,
that the Lord in his own time would bring forth his seed, even his elect seed,
the seed of his covenant, to rule in me.
This was given me at a time when the sense of my own unworthiness
had so overwhelmed me in sorrow and anguish,
that I thought myself unworthy of any of the creatures;
forasmuch as I was out of the covenant of God,
and hereupon was tempted to deny myself of them.
Then did the hope of the resurrection of the just spring in me,
and I was taught to wait on God, and to eat and drink in fear and watchfulness,
showing forth the Lord`'s death till he should come to be raised to live and reign in me.
Then I waited as one that had hope that God would be gracious to me;
yet something in me would eagerly have known the time how long it should be,
but a faithful cry was in me, which called that to death.

Upon a time being weary of my thoughts in the meeting of God`'s people,
I thought none was like me,
and it was but in vain to sit there with such a wandering mind as mine was,
which though I laboured to stay it, yet could not as I would.
At length, I thought to go forth, and as I was going, the Lord thundered through me,
saying, that which is weary must die.
So I turned to my seat and waited in the belief of God,
for the death of that part which was weary of the work of God,
and grew more diligent in seeking death, that I might be baptized for the dead;
and that I might know how to put off the old man with his deeds and words,
and imaginations, his fashions and customs, his friendship and wisdom,
and all that appertained to him, and the cross of Christ was laid upon me, and I bore it.

As I came willingly to take it up, I found it to be to me,
that thing which I had sought from my childhood, even the power of God; for by it,
I was crucified to the world, and it to me, which nothing else could ever do.
But oh, how glad was my soul when I had found the way to slay my soul`'s enemies.
Oh, the secret joy that was in me in the midst of all
my conflicts and combats I had this confidence,
if I but take up the cross, I shall obtain victory,
for that is the power of God through faith to salvation,
and as I have found it so in some things, so I shall do in all in due time.
Then the reproach of the gospel became joyous to me;
though in those days it was very cruel and grievous to flesh and blood,
yet I despised it, and that for the joy that was now set before me,
of which I had some hope I should in time be made a partaker, if I abode faithful.
It was my great care night and day,
to keep so low and out of the workings of my own will,
that +++[+++ might discern the mind of God, and do it,
though in never so great a cross to my own.

Yet the enemy of my soul followed me close and very secretly,
and taking notice how willing I was to obey the Lord,
he strove to gel up into the seat of God, and to move as an angel of light, to betray me,
and to lead me into something that was like the service of God.
Many sore conflicts did I meet with before I was able in all things
to distinguish between the workings of the true spirit and power,
from that which was but transformed.
But forasmuch as I had now surely tasted of the love and goodness of God,
I trusted in him, and committed the keeping of my soul unto him in singleness of heart.
Manifold and daily were his deliverances made known to me,
beyond all recount or remembrance of man, for which, oh my soul, praise the Lord forever,
who cared for you in your infancy, and kept you in the days of your distress.

The more I came to feel and perceive the love of God,
and his goodness to flow forth upon me,
the more was I humbled and bowed in my mind to serve him,
and to serve the least of his people among whom I walked.
As the word of wisdom began to spring in me, and the knowledge of God grew,
so I became as a counsellor of them that were tempted in like manner as I had been,
yet was kept so low that I waited to receive counsel daily from God,
and from those that were over me in the Lord, and were in Christ before me,
against whom I never rebelled, nor was stubborn.
But the more I was kept in subjection myself,
the more subject were evil spirits made to me,
and the more I was enabled to help the weak and feeble ones;
so the eyes of many came to be upon me, as one with whom counsel and understanding,
in some measure were.

The church of God in those days increased, and my care daily increased,
and the weight of things relating both to the outward
and inward condition of poor Friends came upon me,
and being called of God and his people to take the care of the poor,
and to relieve their necessities as I did see occasion,
I did it faithfully for several years, with diligence and much tenderness,
exhorting and reproving any that were slothful, and encouraging them that were diligent,
putting a difference according to the wisdom given me of God,
and still minding my own state and condition,
and seeking the honour that comes from God only.
A cry was in me to keep on my spiritual armour,
for all enemies were not yet put under my feet, so I kept my watch,
not knowing well where the enemy might appear,
but after a while I found his appearance once more to be very sharp,
and that upon this occasion.

About the year 1659, I often felt the aboundings of the love of God in my heart,
and a cry to stand given up to his will, which I thought I was,
not knowing or foreseeing what the Lord was intending to do with me.
But his eye saw further than mine.
His love and tenderness, and bowels of compassion wrought so in me,
that it extended even to all men on the whole face of the earth,
so that I cried in spirit, oh that all men knew you and your goodness!
And upon a time, as I was waiting upon the Lord, his word arose in me,
and commanded me to forsake and part with my dear wife and children, father and mother,
and to go and bear witness to his name in Scotland, to that high professing nation.
But when that came to pass I found all enemies were not slain indeed; for the strivings,
strugglings, reasonings and disputings against the command of God, that I then met with,
cannot be told or numbered.
Oh! how I would have pleaded my own inability, the care of my family,
my service in that particular meeting, and many more things,
and all that I might have been excused from this one thing which was come upon me,
that I thought not of, or looked not for.

After many reasonings, days and weeks by myself,
I thought it best to speak of it to some of the faithful
elders and ministers of the everlasting gospel;
not knowing but they might discourage me, and something there was that hoped it,
but contrarily they encouraged me, and laid it upon me to be faithful.
Then I gave up, and acquainted my dear wife therewith, which began me a new exercise,
the enemy working in her strongly to stop me.
But in much patience was I kept, and in quietness,
and went and visited Friends`' meetings about Essex, and part of Suffolk,
chiefly to see them, and to take my leave of them.
In some meetings the Lord would open my mouth in a few words to the refreshing of Friends,
but I rather chose silence, when I might so.

The winter drew nigh, and something would have deferred +++[+++my journey]
till next summer.
But the Lord showed me it must not be my time, but his time.
Then I would have gone by sea, but the Lord with-stood me, and showed me,
it must not be my way, but his way; and if I would be obedient he would be with me,
and prosper my journey, otherwise his hand would strike me.
So I gave up all, and with pretty much cheerfulness at last I obeyed,
and about the end of the seventh month went forth, and visited the churches of Christ.

As I went along in Lincolnshire and Yorkshire,
I quickly perceived the Lord was with me more than at other times,
and my journey became joyful, and the more, in that though I was but weak, poor and low,
yet God gave me acceptance among the ciders of his people,
and in every place my testimony was owned,
and several were convinced of the everlasting truth.
Then I marvelled, and said.
Lord, the glory alone belongs to you, for you have wrought wonders for your name`'s sake,
and for your holy seed`'s sake.

I got into Scotland in the ninth month, that year,
and travelled to and fro that winter on foot with cheerfulness.
Many straits and difficulties attended me, which I forbear to mention,
it being the time of the motion of the English and Scottish armies,
upon which came the revolution of government,
and the bringing back King Charles the Second into England.
About the eleventh or twelfth month I returned and travelled into the west to Westmoreland,
part of Lancashire, and so to the southward, and in about five or six months time,
was by the good hand of God brought home to my wife and children, and relations;
in all my journey being sweetly accompanied with the presence of the Lord,
and his power often filled my earthen vessel and made my cup to overflow:
praises forever be to his name, says my soul.

In all my journey I lacked not anything that was good for me,
but as it was my care in singleness to serve the Lord,
so was the tender care of the Lord over me,
and he supplied me with whatever was needful in my journey,
yet all along a secret hope did live in me,
that when the present journey should be accomplished,
I should be freed from this service, and have liberty to return to my calling and family,
but contrarily it proved.
For when I had been at home a few days, it lay upon me to go up to London,
to visit the brethren and church of God there,
I went in great fear and dread of God into that city;
and having continued there a few days,
departed northward again at the commandment of the Lord,
and found my way prosperous wherever I went,
and great encouragement did I daily receive from the Lord, who blessed my labour of love,
that besides the peace and joy I felt in myself,
I say the effect of my labour and travail of my soul in several places,
made manifest by many being turned from darkness to light,
and from serving the devil`'s power unto the power of God.
But still trials attended me and a prison became my portion,
nigh two hundred miles from home,
and great and grievous threatenings were breathed out against me,
and the same spirit which wrought in the persecutors, both in their cruelty and subtlety,
strove to work in me also.

But I cried to the Lord, and he helped me, and my faith failed me not,
but I fulfilled my service and testimony; and at length was delivered,
and several thousands more, by a public proclamation from the king.
I then returned to my own house, after about eight months`' absence,
and my heart was set to serve the Lord, who had been good unto me.
Yet this hope of being freed from this kind of service, lived long in me,
for I found the work every day more weighty than other,
many false spirits rising up and transforming themselves into the likeness of truth,
yet were enemies to the life of truth, which were the worst enemies of all.
I saw that Zion`'s enemy, that could no other way prevail,
was now trying if by a false pretence of holiness and obedience,
he could deceive and beguile the simple.
But I cried to God to give me a discerning heart,
and an understanding to comprehend the snare of the enemy,
and that I might be a help to the weak, and he did so.

I saw the foundation struck at by the enemy,
and I grew zealous for the Lord and his house,
and testified freely against the secret deceits of the enemy; but,
this occasioned me yet more exercise and sorrow too;
some who saw not the depths of the workings of Satan,
judging my zeal and fervency against that contradictory spirit to be needless.
But in meekness and patience, the Lord kept me out of the warring and striving mind,
for I dare not strike them whom I knew to be my fellow servants,
but them that pretended to be so, and yet served and promoted another interest.
Them I often wounded with the weapon God had given,
and they that came to love the judgment, were healed,
but many perished in their rebellion and stubbornness.
The Lord arose and blasted the work of the enemy,
and opened the eyes of many that were darkened,
and they came to see the end of that which had been the troubler of Israel, and peace,
unity and true love were restored in all our borders.
Then was my joy full, and my cup did overflow with praises and thankfulness to God,
who had had regard for his heritage and people,
and had delivered them from the devices of the wicked one.

My soul grew daily in love with Zion,
and there was nothing in all the world so desirable to me as the prosperity of the gospel,
and the spreading and publishing his name and truth through the earth.
This love constrained me to travel with great diligence from country to country,
to make known what God had done for my soul, and to publish the day of the Lord; yes,
the day of redemption in which the captivity of the
spiritual Israel should be brought back,
which did prove glad tidings unto many, who received the report and believed it.
They came to behold the revelation of the holy powerful arm of God,
to their souls satisfaction.
In most parts of England where I travelled, I found a daily adding to the church,
such as were like to be saved; and hereupon my joy increased,
and I began to be more freely given up to the work and service of God,
and to the ministry of the gospel.

About the year 1663, I was moved to cross the seas,
and to visit the seed of God in the Low Countries, which I did with cheerfulness;
and though in an unknown land, and with an unknown speech,
yet by an interpreter sometimes, and sometimes in my own tongue,
I declared the truth to the refreshing of many, and to the bringing back some from error;
and having accomplished, that visit, I returned in peace to England.
After awhile, being required of God, I again went down into the north country,
and labouring in the word and doctrine with great diligence and fervency, along,
or near unto, the sea-coast, and so down to Newcastle, and something beyond.
Being led by the Spirit, I came back again another way more eastward through the land,
and found all the way the plant of God`'s renown flourishing and growing,
meetings enlarged, and the hearts of Friends enlarged in love to me and mine to them.

Being returned, a great weight came upon me concerning the great city of London,
greater than ever before.
I went up full of might and power, and did daily,
as the Lord opened my mouth and ordered me,
warn them of the abominations and wickedness that ran down among them like a stream,
and declared the judgments of God at hand upon them, for their great wickedness,
which followed speedily both by war and fire, and many more calamities.

After this, about 1667, it was required of me again to go into Holland,
and my dear companion, Josiah Coale, went with me; and we travelled to and fro,
and visited the churches about three months and returned.
I went again into the north of England,
my heart being abundantly drawn out towards the noble seed of God in those parts,
and my love and tenderness of heart towards them, made all travel and labour,
and perils easy;
because I still saw the tender plants of my heavenly
Father in a thriving and growing way or condition,
I felt the virtue of life daily springing in me,
which was given me to water the heritage and garden of God with.
So soon as I was clear, I returned,
having more and more still the care of the church of God coming upon me,
which constrained me to diligence, and to be as swift as I might be,
that so I might be as serviceable as possible in my generation,
and might keep myself clear of the blood of all men,
which I found to be no easy or slight work.

Being safely returned, and finding the presence and power of the Lord,
yet leading me to and fro from country to country, unto which I was obedient,
not of constraint now, but of '`a willing; mind; counting his service a freedom,
feeling myself freed from the cares of this life,
having now learned to cast all my care upon him.
After a year or two years travel thus in England,
the Lord laid yet more of the weight and care of the affairs
of his people in the Low Countries upon me,
and I found a drawing towards them; and in the year 1669,
I went over and visited the meetings, obtained several new meetings,
and they set up a men`'s meeting among them,
to see to the good ordering and governing of the affairs relating to Truth and Friends.

This time did it please the Lord to open my understanding abundantly,
that I began to declare in their own tongue the things
that God had committed unto me to minister;
and several received the everlasting gospel, and were brought to feel the power of God,
by which they are saved from the world, and the polluted ways therein.
Travelling in those provinces of Holland, Friesland, and Groningen, etc.,
I was moved to pass into Germany, to which I gave up in the fourth month that same year;
and by the way met with many perils and dangers, by reason of the horrible darkness,
popery, cruelty and superstitions of those lands and dominions through which I travelled.
Sometimes it was as if my life were in my hands, to offer up for my testimony;
but the Lord preserved me, and brought,
me upon the fourteenth day of that month to Krisheim near Worms,
where I found several who had received the everlasting Truth,
and had stood in a testimony for God about ten years,
in great sufferings and tribulations, who received me as a servant of God;
and my testimony was as a dew upon the tender grass unto them.
I had five good meetings among them, and many heard the Truth,
and several were reached and convinced, and Friends established in the faith.

It was also just in an hour of temptation and time of trial among them,
that the Lord had cast me there; for the prince of that land, called the palsgrave,
had imposed a fine upon them for their meetings, namely,
four rix dollars the year for each family, which they, tor conscience sake, not paying,
he sent an order to take the value in goods.
Whereupon his unreasonable executioners came and took away the treble value,
but they suffered the spoiling of their goods with great joy and gladness,
and counted it a happiness that they were counted worthy to suffer for his name`'s sake,
who had called them to the knowledge of his blessed Truth,
and to bear a testimony in that dark desert, to the light of the Lord Jesus.

I went to Heidelburgh to the prince of that land, and had a good opportunity with him,
and laid before him the danger of his proceeding on in persecution.
He heard me with a great deal of friendliness, and discoursed things at large with me,
and in several things promised it should be better, as it did also after come to pass.
Having finished that service in Germany, I returned,
and being come into the Low Country again, I went to Groningen,
where many had believed in the name of Jesus, the light of the world,
whom when I had visited in the power of God, and strengthened in the faith, I left,
and returned through Friesland to Amsterdam, where,
by reason of my now speaking in their own language, meetings grew exceeding great,
and many strangers came flocking in, and a great openness I found in the country.

Being necessitated of the Lord to come for England,
I left them to the Word of the grace which they had received of God,
which was able to keep them; and came over into England in the latter end of the year,
and went towards London, in order to visit the churches in the western parts of England,
whose faces in the outward, I had never seen, though long desired it.
Passing from London, I went through Berkshire and Wiltshire,
having had many precious meetings with the Lord`'s people, I came to Bristol,
where I found a people, among whom my soul was greatly refreshed.
I stayed with them about a week or nine days, and in a true sense of the Eternal Power,
in which the true fellowship always stood, we took leave one of another.

I travelled that winter with my companion in the gospel, Samuel Cater,
through Somersetshire, Devonshire and Cornwall, to the Landsend of England,
visiting the churches in those parts to our mutual comfort.
I returned by Plymouth, visiting the south seacoast even unto Portsmouth,
then coming through Hampshire and Surrey, came to London, and so to Colchester again,
to the gladdening the hearts of God`'s heritage in that place,
many of whom have with me many a time rejoiced and
given thanks to him that lives and reigns forever,
for my preservation through all perils and dangers,
and the multitudes of deliverances of which I was daily made partaker.

Being moved of the Lord, I appointed a meeting at a place called Chelmandiston,
where many had received the truth and testimony of God through me his servant.
There a priest, who two years before betrayed me to the ruler, and got me into prison;
now procured a warrant to have me cast into prison, and I was so in the First month,
1670, in Ipswich jail.
Being committed to the said jail for being at a conventicle,
(so called,) upon the statute of the 14th of king Charles, which says,
"`If a person be convicted of a conventicle,
he shall pay a sum of money not exceeding five pounds, or lie in prison some time,
not exceeding three months;`" and the court judge, R. Rainsford in his haste and passion,
not regarding the law, but his own will,
committed me to lie in jail until I would pay five pounds;
and afterward being convinced of his error,
he wrote an order for my release at three months end.

I being released, was drawn forth in the love of God,
again to cross the seas about the fifth month, 1670,
and went to Holland to visit the remnant there that had believed,
and to strengthen their faith,
and for some weeks preached the gospel in several cities unto the inhabitants and strangers,
who came in great numbers ofttimes to meetings,
hearing there was one that spoke in their own language.
Many were reached, and some overcome by the power of Truth;
and the hand of the Lord was with me in a blessed manner,
to the refreshing my soul and filling my vessel,
and the overflowings of my cup made many glad.

Then about the seventh month, it arose in me to travel eastward,
and to visit those dismal dark countries in the lower parts of Germany,
and the borders of Denmark and Sweden, where the Lutheran religion bears sway,
and darkness and wickedness in the strength of it therewith.
Oh! the weight and burden I felt many times,
as I travelled through their towns and cities, where it might well be said,
none did good, none considered their ways,
and none thought upon the name of the Lord as they ought to do;
but all manner of wickedness abounded.
I and my companion, Peter Hendricks, were as signs and wonders,
because our manner and conduct,
our words and discourses carried nothing but judgment to them,
and sometimes we gave them books and papers of Friends, and left with them.
Though the rage of many kindled against us, yet the Lord made way for us,
and we had a safe and prosperous voyage, and came to Hamburg,
and had a meeting upon a firstday with those there that were convinced.

Then we went down into the dukedom of Holstein, belonging to the kingdom of Denmark;
and having travelled two days journey, about seventy English miles from Hamburg,
we came to Frederickstadt,
where we found the brethren met together to wait upon the Lord,
upon the fourth-day of the week, who received us joyfully.
We sat down and were refreshed in the fellowship of that
blessed gospel which is ordained for a blessing to all nations,
tongues, and kindreds, who believe and obey it.
After that we gave forth a meeting publicly in the city, to be on the sixth-day,
unto which many of the city came, and particularly,
the chief magistrate and the messenger or sergeant of the city,
and the power of God was much manifest among us,
and much brokenness there was among the people,
and they received the doctrine of Truth with much love and tenderness.

On the first-day of the week, in the morning,
we had a meeting again with the brethren and such as were convinced,
and a great openness was among us from the Lord;
and in the afternoon we had another public meeting, at which were about a hundred people,
and every one`'s mouth stopped; and though liberty was given for objection,
yet none was made.

These things troubled the minds of some professors and teachers,
who had enmity in their hearts against the Truth,
insomuch that two of them came towards evening and desired a dispute with me,
which being granted, about forty or fifty persons came in to hear.
For an hour or two, we spoke together, and the power of God was over them,
and they were divided between themselves, which when the most moderate saw, he went away,
and the other, one Eppinghooft, stayed till he made his folly manifest,
to the most that were in the room, in particulars too large here to relate.
So Truth stood over them, and the city was in a tender, cool and loving frame,
and many were added to the church, and to the faith which saves.
The city has remained in such a frame ever since,
and has been visited by several brethren, as Thomas Green and William Penn,
who have had good meetings among them to their mutual refreshment.

On the second-day of the week, we met together early in the morning,
and committed each other to God, with prayer and supplication;
and they accompanied us to the Jider, which runs by the city,
and there we parted in that love which never changes,
and set our faces again towards Hamburg, where we came safely the next day.
After we had visited Friends there, we took boat and came over the Elbe,
and by wagon came to Bremen, where we left several books.
We passed back to Oldenburgh, and so to Embden, where being upon a first-day of the week,
it lay upon me to go to an assembly of the ministers,
(a kind of baptists,) where after one Hert Jansen had preached,
and the prayer time was over, (for they speak no words in prayer,
but all kneel down and are silent,
every one praying in his own mind as seems good to him,) I say, after that,
I stood forth and spoke in the Dutch tongue about half an hour,
exhorting them to come to God`'s witness, that they might feel judgment set up in them,
to cleanse them, and to prepare them for the Lord, etc.

After this the preacher stood up again and vindicated
and maintained by scripture what I had said,
exhorting them to receive my exhortation.
The same evening several people came together at the house of one Remeikie, a poor maid,
who had neither hands nor feet, a devout woman who sought after the way of God,
and received us gladly to her house.
I was moved to declare the truth of God among them;
and after that we had some words by way of dispute and parted lovingly.

The next day several of them came again to us and kept us company;
and about mid-day we parted very friendly,
and I with my companion took shipping for Delfe-Siele, and so came to Groningen,
and had a meeting with Friends to our mutual refreshment.
From there we came to Lea Warden,
where the Friesland lords had a law to put Quakers in the Bridewell for five years,
that should dare to come into their province of Friesland,
by which law they had taken three Friends of Amsterdam, and put them in prison,
and made an order that no Quakers should go in to visit them.
When I understood this, the zeal and love of God sprung in my heart,
and set me over them and their wicked law,
and I took a pen and wrote to their lord president,
and told them they had done worse than heathens;
and seeing they had made a law to imprison all Quakers, there was I and two more with me,
who were come to visit the prisoners, and desired liberty so to do:
for we feared God more than them and their law,
and were come to fulfill our Christian duty to our brethren,
whom they had so unjustly cast into prison.
The president carried the letter to the council, but the Lord limited them,
and they let it pass by and did not lay hands on us.
We appointed a meeting in the city, and having tarried there several days,
we came to Workum, and took shipping for Amsterdam,
and came there on the first-day morning, about the beginning of the ninth month.

Being come again to Friends in Holland,
we had many precious meetings together in several cities, Alkmaer, Haerlem, Rotterdam, etc.
A young man having heard in Switzerland where he lived,
that he had a brother in Holland turned Quaker; in his zeal came down,
thinking to turn him, but the Truth prevailed u]!on him,
the first and second days he heard it declared, so that he owned it,
and became obedient to the cross, the first week he was there,
to the great comfort of Friends, and most of all, of his brother.

I having travelled through the meetings and visited Friends;
in the tenth month I committed them to the Lord, and to the Word of his grace,
and returned again to England, and went to and fro visiting the churches in London,
and in various parts of the nation for three or four months.
At which time, I understood that several exalted spirits had risen up,
among them that had believed in Friesland,
who began to set forth strange doctrine among Friends,
and sought to unsettle the minds of them that had newly received the faith among them,
and had begun to seduce them from their meetings, and to wait upon,
and to mind strange notions and imaginations,
which has been the ruin of many in former ages, who were not grown to a discerning.

So the zeal of God moved in me against that spirit,
and the love to the tender seed drew me again over the seas,
which was of great service to Friends and the Truth.
I laboured greatly to inform the minds of Friends, of the depths of that ranting spirit,
and where it would lead and where it would centre;
I having had long experience of it here in England.
The +++[+++Lord`'s]
power arose among Friends, and they began to note such as were disorderly and unruly,
and to call them to an account, and took great labour and pains with them,
to regain and recover them out of the snare of the devil,
making many journies and visits to them, which proved not ineffectual,
several being helped and brought back.
Howbeit, some were hardened and waxed worse and worse,
and turned against the power of God into enmity and opposition against Friends;
so that a necessity was upon Friends to clear themselves and the Truth,
of them and their evil works; and the more,
because we saw that the mind in which they were so vainly puffed up, was fleshly,
as afterward appeared.
So Friends called them to their general men`'s meeting, but they refused to come;
then Friends journeyed to them time after time, to warn them,
and to exhort them to turn again to the Truth which they were fallen from;
but when no counsel would take place with several of them,
Friends put out a paper against them for the clearing the Truth.

After these things I came to England again in the fourth month, 1671,
and travelled through several counties, being much rejoiced to see the peace,
unity and courage,
that were among the people of God after the sore persecution that had been among them.
Passing up to London, and back again to Colchester,
where having a sore sickness nigh unto death in appearance,
it came upon me to go into the north country to visit
the churches in Yorkshire and Bishopric,
etc. where I had not been for three or four years,
by reason of my being much beyond the seas.
The love of the Lord abounded in my heart unto those dear Friends northward;
and I was pressed in spirit till I had cleared myself
of all things that lay upon me in my own country.
And upon the Hist of the eighth month, I took my journey forward,
and going through the Isle of Ely, found dear Samuel Cater,
who was pressed in spirit to visit Friends in Scotland,
and so became my companion as far as Newcastle.

Through several places we travelled, to the refreshment of ourselves, and many more;
and the Lord delivered us out of the hands of the ungodly informers,
who were then very brief throughout the nation,
upon the account of the new act which was made to fine us, for speaking in meetings,
twenty pounds the first time, and forty pounds each time after.
This law made them greedy in all parts, but in all places they were,
through the wisdom and power of God frustrated, and though the winter was very sharp,
and my body now through much affliction very weak,
yet was I marvellously supported through that journey;
and having parted with my honest companion at Newcastle,
I turned westward and came southward another way than I went; and so to London again,
where having visited Friends, I returned to my outward habitation again at Colchester,
to the joy of my poor wife and Friends,
who had longings for my return as I had again to see their faces,
which desires the Lord to our comfort answered, about the twelfth month, 1671.

Having continued visiting Friends to and fro, the forepart of the year;
about midsummer I took shipping for the Low Countries again, to visit the flock of God,
where I laboured and travelled about three months in Holland and Friesland,
in the time of that great consternation and confusion that was upon them,
by reason of the great and sudden progress the king of France made upon the United Provinces.
Howbeit, the foundations of their pomp,
power and glory were then shaken and ready to be overturned.
Yet I saw the foundation of Satan`'s kingdom stand very fast among them,
and the people instead of turning to the Lord by unfeigned repentance,
grew worse and worse, and debauched themselves more than ordinary by drinking,
gaming and sporting, and the burden thereof came upon me,
and I was made to cry out against them in the power of the Most High,
and warn them to repent, and put away every man the evil of his doings.
I wrote down the counsel of the Lord as it was manifest in me,
showing them the cause of their misery, and where the remedy must be.
I caused it to be printed and made public to those countries,
and many copies were given to the chief rulers and commanders;
so I cleared my conscience in the sight of God concerning those nations for that time,
and left them, returning for England about the eighth month, 1672.

Having been some time at my own home, and visited Friends in several countries,
I went to London, and parts adjacent, preaching the everlasting gospel,
and witnessing the grace of God, in Jesus Christ,
which shined forth to gather the elect seed out of the house of bondage and darkness.
And the Lord was with me daily to the rejoicing of thousands,
and to my daily encouragement; for by his mighty power were many strong oaks bowed,
and many subtle foxes prevented of their prey,
and many wandering sheep brought home who had long desired to find the fold of rest,
whose souls will ever live with my soul in his covenant to praise him world without end.

Having spent about six months in this manner, I found it upon me from the Lord again,
to pass over the sea,
and to visit various places where Truth had been little or not at all sounded;
and in particular, that hard-hearted city of Embden in East Friesland.
Here one John William Hasbert, a doctor of medicine, received me with great cheerfulness;
and I had a meeting in his house upon the first-day of the week,
about the latter end of the first month, 1673,
where many people of various persuasions did hear
the Truth declared in great plainness and simplicity.
After some time,
those that were convinced were drawn in love to God to assemble together,
to worship God in spirit and in truth,
and in the silence of that fleshly wisdom that can speak when it wishes,
and say what it wishes.
At the first, there sat down about ten persons in Hasbert`'s house to wait upon the Lord,
and when this was noised about the city,
the wicked one stirred up the priests and rulers against them,
and they stirred up the rude and ignorant people to assault them, mock,
reproach and revile them, and the rulers fell quickly to fining, imprisoning,
threatening and banishing those weak and tender plants in almost an unheard of manner.
+++[+++After]
banishing some, sixteen or twenty times, spoiling all they had, save their clothes,
at last they fell upon them also; taking away their coats, hats, breeches, gloves,
aprons, etc.,
and driving them through the streets almost naked
aboard the ships that were to carry them away.
All this and much more by the mighty power of the Lord, did these innocent,
harmless lambs bear with great patience and quietness,
and were not dismayed at all at these cruelties;
for the Lord had regard to his name and to their innocent cry, and supported them,
and does support them, and they have found it true,
that they that wait upon the Lord have renewed their strength:
blessed be the Lord forever.

Returning from Holland into Friesland, I continued about three or four months,
and published the glad tidings of salvation in their
own tongue to all that had an ear to hear.
About the same time were several great pillars both as to state and religion shaken,
and several of those who had been in great places in government, were convinced,
and their understandings were opened concerning the way of Truth,
and began to struggle and contend for it in that wisdom that was from beneath;
whom I faithfully warned and counselled in the love of God,
not to seek to comprehend the Truth, but to wait in lowliness to be comprehended by it,
and gathered into the precious life thereof.
But oh! the cross, the offence of the cross, they could not bear with,
but sought various ways to satisfy themselves with
owning the doctrine and words of Truth,
and loving Friends who walked therein; but came not down to the simplicity of the gospel,
excepting one of them, nor to be separated from the world,
nor from those things in which the world`'s fellowship stands,
though they were brought to confess the way of Truth,
and to cry out of the load that lay upon the soul.
Howbeit the sound of their convincement did tend to the advantage of the gospel,
and many came to meetings, and they of the most honourable;
and some were convinced of various ranks, qualities and persuasions,
especially in Rotterdam, where meetings then grew very large,
and Truth came to have a good esteem in the hearts
of many who had hated it and us without a cause.

After I had spent three or four months in those parts, and found myself clear,
I returned for England against the general meeting in the fourth month,
and travelled with great diligence through several counties,
and went again to Bristol and visited the churches in many
parts of England to my and their great refreshment.

The Lord was with me, and gave me utterance and wisdom as I stood in need,
for he kept me poor in spirit and low in mind,
and I knew that my dependence was upon him alone,
who knew well how to order both me and my service;
and he gave me judgment to rebuke gainsayers,
and to stop the mouths of them that opposed themselves.

So I continued till about the fourth month, 1675,
at which time I understood the former openness did continue in the Low Countries;
and I was drawn in the love of God again to go over there to visit them,
and to behold their order, which I did to my great comfort,
and found the noble plant flourishing,
and a living testimony opened and raised up in many of them that had believed;
and they spoke of the goodness of God in their congregations,
warning all men that they might turn to the Lord by unfeigned repentance,
and wait to see his salvation.

Hearing of the great sufferings of Friends at Embden, I went there to visit them,
and hearing of a law they had published,
of twenty-five pounds tine for every one that should
harbour a Friend in his or their house;
I desired to see it, and took it and wrote a book to the hard-hearted rulers and priests,
and answered their wicked mandate with sharp and sound judgment,
and caused it to be delivered among them.
The power came over them, and they laid not hands on me, nor did me any harm,
though I was publicly in their city two days, and known by many of them;
after which their fury abated, and Friends began to have some more freedom than formerly.

About the eighth month, 1676, having travelled through the provinces,
and visited many places and cities, I returned in the will of God to my own home;
finding my body much decayed and disabled from travel and labour more than formerly;
yet satisfied in the will of God who laid no more upon me,
than he gave me ability to perform; and as he has always been abundant in goodness to me,
so he is to this day, blessed be his name forever.
This I can say, my delight is to do his will,
and my joy is that he has counted me worthy to bear his holy name
and testimony among the sons and daughters of men.
Oh! that all men would fear the Lord, and walk in the way of his righteousness,
that they might come to have the evidence and testimony of his goodness in themselves!

I passed that winter in visiting the churches in Essex and Suffolk,
and sometimes at London,
where it pleased the Lord to appear with me for his name and tender seed`'s sake,
to the convincement of several, and strengthening of many; glory be to him alone forever.
The winter being over I felt drawings to pass again over sea,
finding a particular care and charge laid upon me concerning those parts,
in which the Lord had given me great encouragement, and I saw I had not laboured in vain;
praises be to his name.

About the first month, 1677, I took shipping for Holland,
where I found Friends very well, and in good order;
and their men and women`'s meetings were become a delight to them,
as having not only enjoyed the Lord`'s presence in them,
but had also seen the great benefit that had come thereby,
and the ease they had of the weights that had formerly lain upon them.
Having several times visited their meetings in Holland, I went over into Friesland,
to Harlingen, where many Friends of that country met me upon a first-day;
and we had two precious and large meetings, and many professors came to hear,
who had nothing to say against the testimony of Truth.
Having seen Friends there, and finding myself unable for long journies,
I returned for Holland,
and having stayed there with great joy and comfort in seeing Truth`'s prosperity,
about the latter end of the third month I came back for England, and passed for London,
where I was most of that summer and in the parts adjacent.

Then the Lord put it into my heart again to visit the meetings round about Colchester,
where I lived, which with much pain and trouble of body, though with much joy in spirit,
I accomplished, and found Friends in most places well.
Where I found the subtle,
crafty serpent seeking to scatter and to divide God`'s heritage;
I reproved it with great plainness and confidence in the Lord,
who had showed me the mystery of that iniquity;
and how the enemy of Truth sought to cover himself with Truth`'s words,
and under pretence of leaving all to the power,
would usher in a spirit of liberty to lay waste the blessed testimony of God,
and scatter his people out of the good order into which the gospel, the power of God,
had brought them.

In the service of my God, after this manner,
I continued at and about home most of that winter,
waiting upon the Lord to be led and guided in my
service and testimony according to his will;
for I found that though through long experience,
my senses were exercised in the service of God and the churches;
yet I had nothing to trust to, as a guide or leader,
how and after what manner to minister in the church of Christ,
but the same that led me in the beginning,
even the immediate operation of the power that brings forth
in the will of God all things suitable to their season,
that the glory might be to the power, and the praises to him that gives it,
forever and forever more.

The winter being over, the Lord renewed my strength,
and having further service for me to do, gave ability.
About the first month, 1678,
I found some powerful drawings in the love of God to go down once more into Yorkshire,
where I had had much service for the Lord,
but had not been there for about six or seven years.
So I went to Hull, and visited the churches about Holderness and Hull, and Beverly,
Malton, and York;
in all which places I saw the glory of the temple of my God shine forth in great splendour,
notwithstanding all the rage of the adversary.
I had a precious service in every place, and the hearts of many were opened,
and the souls of many dear Friends were truly refreshed,
and the bread of life was plentiful among us to our
mutual joy and rejoicing in this journey.
My soul was greatly comforted to see so many of the ancients,
and honourable men and women abiding in their places,
and growing up in the house of God as fellow-helpers in the gospel with us.
After about seven weeks tarrying in those parts, I committed them to the grace of God,
and returned for London to the yearly meeting, where having tarried a week or two,
I returned and set things in order in my own house.

After this I again crossed the seas,
and went to labour in his little vineyard there to my great refreshment;
and going over about the fourth month, 1678,
continued there till about September the same year,
in which time the Lord laid it upon me to go up southward
to several cities upon the Rhine,
where several had received a notion of the Truth in a talkative mind,
but were not come to a sense of the cross and dying of Christ Jesus,
nor to a separation from the foolish and vain customs
and salutations that are in the world.
I spoke with several of this sort of people at Cleeves and Wesell.
At the latter place I had a meeting upon a firstday about the harvest time there,
where several heard Truth declared in the plainness and simplicity of the gospel,
and a love was begotten in them.
But oh! the cross,
the cross! that was and is very hard to that mind that would gladly inherit both kingdoms!
Great struggling there was by several of them to argue themselves into a liberty,
to abide in the customs of the world,
and to walk in and obey the light of the Lord Jesus also.
But in vain was all that labour, and ever will be,
for the disciple must be as his master; and he sought not nor received honour of men.
Having answered the witness of God in them,
I was not studious how to feed their curious inquiring
minds concerning things beyond their states and conditions,
but parted with them in the love of God and true breathings to the Lord,
for the bringing forth in the Lord`'s due time what he had begotten;
and so committed them to the grace of God, and returned into Holland,
where it pleased the Lord to visit me with sickness for several weeks.

Finding myself clear of all those parts for the present,
I caused a boat to be prepared and brought to the door of my lodging,
and I lay down in it, being very weak, and so was conveyed to Rotterdam,
where my strength was so much renewed, that I went into their meeting on the first-day,
and for about half an hour declared the Truth of the gospel among them,
exhorting to a steadfast abiding therein unto the end.
Shortly after, I got into the packet boat for England, and so to my own house,
still remaining very weak, and freely given up in the will of God,
that if my service were ended,
I might lay down my head in the will of God in my
own habitation after all my trials and travels.

But the Lord was pleased to restore me,
so that I was able to ride and visit the meetings about home,
and also got twice to London in that winter;
where my joy was to behold the brethren that live in the unity
of that power that shall bruise Satan and his work under foot,
and lay waste his kingdom.
So having visited some of the assemblies of the Lord`'s
people in Hertfordshire and other places,
and cleared myself of what lay upon me in the city,
I returned to my place in the will of God, remaining as a servant waiting to be ordered,
and as a child waiting to be fed of him who is the Father and fountain of all my mercies,
blessings and deliverances, to whom be the glory forevermore.

The next summer finding no necessity lying upon me as formerly, I went not over sea,
but after the general meeting was over,
it lay upon me to visit Friends again at Bristol and thereabouts,
being at that time under a deep sense of some great
exercise that the church of God was in,
by reason of some who under a pretence of exalting the power,
sought to make void the wholesome order and government
which the pure power had led us into,
crying down formality and men`'s orders, etc.
When I came there, I found that this licentious spirit had hurt many,
and grieved many more; and a weight came upon me.
I laboured in the power of the gift that the Father had bestowed upon me,
in meekness and patience, dealing with every one in sincerity,
labouring to show them that were concerned, where the tendency of that work would reach,
even to the throwing down of the hedge that God had built about his heritage,
and laying waste the work of the power under pretence of crying up the power itself;
and by crying down men`'s orders, would draw from the gospel order,
and from the blessed fellowship that was in it.
And it pleased the Lord to give me an open door among them, and many were tender,
and became more watchful; though others in the mean while,
made but an ill use of all the tender dealings in the love of God,
and sought thereby to strengthen themselves.

Alter about twenty days I returned, and came to London; and towards winter,
I returned homeward, where I continued in the peace of God,
having my blessed reward with me,
which no reflections of the adversary could take from me,
and was exercised according to my ability,
in visiting the assemblies of the Lord`'s people in Essex and Suffolk,
where it lay upon me;
and in helping and assisting the Lord`'s people according to my ability,
both in their spiritual and temporal concerns,
as the Lord God of my life gave me an understanding.
For I gave up the ordering of my spirit unto him,
and he opened me in many things relating to the affairs of this world,
that I might be as a staff to the weak in those things,
and might stand by the widow and fatherless, and plead the right of the poor.
In all which I sought neither honour nor profit, but did all things freely,
as I received of God, and he whom I served was my reward, so that I lacked nothing.
Therefore, who would not praise the Lord, and who would not trust in his name?

When the winter was over, I went again to London,
and into Hertfordshire and places that way, visiting the flock of God,
and stayed till our general meeting was over,
and then found drawings to visit the little remnant beyond the seas,
in Holland and Friesland, and continued among them, and in those parts,
about three months.
In which time it came upon me in the great love of God,
to visit a little innocent remnant that had believed in the Lord Jesus Christ,
and professed his name in Crevelt, in the land of Meurs,
who for their testimony had suffered many things and grievous,
and been several times banished from house and home,
and made to wander with wife and children to seek
harbour or shelter in strange cities and places.
These I found now returned to their dwellings, and was joyfully received by them,
and much refreshed in them, beholding their faith and courage,
and their steadfastness in the testimony they had to bear for the Lord.

I tarried with them about three days,
and had several precious public meetings in the city,
and sounded the day of the Lord`'s tender visitation in the ears of many of the inhabitants,
who generally behaved themselves with great sobriety and moderation,
neither mocking nor scoffing, nor evilly entreating us;
which is rare to find a people so moderate in those parts,
which is in the borders of the dark Romish religion, and as it were intermixed with it.
But I speak it to their praise, no man evilly intreated me,
and the Lord`'s power was over all, for which we blessed and praised his name.
Having comforted and strengthened them that had believed,
I committed them to the grace of God, and left them,
and returned again to Holland another way, through the Spanish Netherlands;
where I saw great abominations and idolatry, and worshipping and praying to images,
etc. which grieved my soul; and I could not but declare against it in several places,
as the Lord made way.
Being come back to Holland I soon made way for my return home,
and cleared myself of the meetings in Holland, and took shipping for England,
and got home on the 11th of September, 1680.

Soon after it pleased God to visit me with a sharp fever,
which brought me in appearance nigh to the grave; in which his presence was with me,
and supported me, and refreshed my soul many a time,
so that death was not terrible to me;
but I found myself quietly given up in the will of God, whether to live or die,
I was contented.
But after about ten days the fever was abated,
and I perceived that my days would be yet added unto; in which I was well satisfied,
having a constant resolution fixed in my soul, that whether my days be few or many,
to spend them in the service of God and his dear people, who are to me, as my mother,
my brother, and my sister, yes, as my own children,
finding a natural love in my heart to all my Father`'s children,
and a true love to the brotherhood.
And my God has put it far from me to despise the case of the poor,
or to respect the rich in judgment, but according to the gift and understanding given me,
I have walked with a straight foot in the gospel; the honour of all,
with the praise of all which, belongs alone to him that has wrought it, yes,
his own work praises him, and shall praise him who is worthy, both now and forevermore.

After it pleased God to restore me to a measure of health and ability,
I spent the following winter in visiting the meetings about Essex,
and went to Yarmouth and Norwich, where I had not been for many years;
and beheld the work of the Lord arising again in that great city,
and many were made tender by the powerful impression of the Word of God.
Having stayed thereabouts in Norfolk about a month, I returned again in peace,
rejoicing in the prosperity of the Lord`'s work, and came by Ipswich, and so home.
Shortly after it came in my heart, in the workings of the love of God towards his people,
to take a journey once more into Yorkshire,
which proved to the mutual refreshment of me and many more.
Coming to York a few days before their yearly meeting, I went to Scarborough,
whereby many Friends both of Whitby and Burlington, and the country around about,
had opportunity of coming to me, when I, through bodily weakness, could not go to them,
as I had formerly done.
Much service I had for the Lord and his people there, both in some particular cases,
as also in the general and public testimony of the gospel.
Then returning to York, and staying a few days with them at their general yearly meeting,
I went to Hull, and into Holderness, and tarried thereabouts till about harvest time;
and then finding myself clear of those parts, I returned to York,
and from there to London.
Alter some days and weeks stay there, I returned home.

By this time, I was again overtaken with great pains of the stone and other distempers,
which brought my body very low, and little was expected by any, but my departure.
I found myself given up to the will of God, which I knew was best of all;
and if my service in this world was at an end, I was content to leave it;
and if the Lord of the great household had more work for me,
I knew he could and would raise me up, and so he did in his own time.
I grew again able to go abroad, and got to our quarterly meeting in December,
and then after to visit Friends in Harwich and Ipswich, and some other places.
But for the most part of this winter, 168 J, I was about my own dwelling at Colchester,
where I saw my desire in part answered,
concerning several who were brought to the acknowledgement and profession of the Truth,
whom I hope the Lord will build up by his power, and by the operations of his Spirit;
for he alone can give the increase, to whom alone the glory and praise belong.

The next year, 1682, having spent the summer mostly about home and at London,
about harvest it came into my heart, in the dear love of God,
to go visit his church and people again at, and about the city of Norwich,
that I might be a means of strength and refreshment to them,
in the sharp trials and sufferings that I was sensible were
then coming upon them to try their faith and patience.
The same day I came into the city, I went to their meeting;
and there came one called a justice, with constables and the informers,
and a great rabble of wild and ungodly men, who seemed as if they would devour us,
and hauled me with about a dozen Friends, to their judgment-hall,
where the mayor and aldermen met.
Various practices were used to ensnare me, and bring me into bonds;
but the Lord God of my life was with me, as in former days,
and gave me courage and wisdom, by which all their snares were broken.
But not having had opportunity to clear myself yet in public,
I went the first-day was a week following, after I had visited some country meetings,
to their meetings in the city,
where the Lord appeared wonderfully to bind and limit the adversary.
The meetings were very large that day, both before noon and afternoon,
by reason of country Friends coming there, and abundance that were not Friends:
and all was quiet and peaceable,
for which we gave thanks to God, who we knew was the author of it,
and had set his divine power as a hedge about us for his name`'s sake.

I saw in the light of the Lord, that the Friends there were as soldiers,
with their armour on, well prepared for the approaching conflict,
which came forthwith sharp upon them, after I was come from them,
which they have borne and suffered with great faith and courage,
to the glory of the Lord, and the confounding of their adversaries.
The Lord has appeared with them and for them,
both supporting them in their sharp sufferings,
and sometimes giving them some intermissions thereof;
so that they are kept alive to his praise, that has quickened and preserved them.
Having finished what was upon me there, I returned home,
and continued at and about home that winter, and was visited with some weakness of body;
and in the spring,
found drawings upon me once more to visit the flock of God in the Low Countries.
I went first to London to the yearly meeting;
where though the enemy had opened his mouth wide to devour us,
and much persecution was raised against our peaceable assemblies,
and we were often deprived of the benefit of our meeting places,
yet none could deprive us of the Lord`'s power and presence,
which was evidently manifest among us;
and the blessed fellowship of life was felt and witnessed to our great joy and consolation:
for which high praises were offered up to God, through Jesus Christ,
in the humility of our souls.

The yearly meeting of London being over, I went with several brethren of Dantzic,
Amsterdam and Friesland, towards Holland, to be at the yearly meeting there at Amsterdam,
which is three weeks after ours at London.
Taking shipping at Harwich, we arrived safely at Rotterdam, where having visited Friends,
we past together to Amsterdam.
A pretty many Friends from various parts were come together,
and we had a precious and comfortable meeting, in the unity of the Spirit,
and in the bond of peace; which made our hearts glad,
and tended to confirm the weak and feeble ones,
and to the establishing the testimony of Truth in
the hearts of them that had believed in Christ Jesus.
My God gave me understanding to open the mysteries of his kingdom,
according to their capacities, to our mutual joy and refreshment.
So our dear friends, brethren and sisters,
departed to their several habitations and testimonies, to Dantzic, Holsfein, Hamburgh,
and Friesland, etc., encouraged in the work of the Lord,
and strengthened in the inward man.

Soon after Friends were departed,
it pleased God to visit me again with a very sore fit of the stone-cholic,
which brought me very low in the outward man; and it continued so with me several weeks,
with some small intermissions;
so that I was wholly disabled from visiting the meetings at Haerlem, Alkmaer,
and in Friesland, etc.
Continuing weak, and finding myself clear, in the sixth month, 1683,
I set my face again homeward, and the Lord made my way prosperous;
and by the good hand of God I was brought home,
where in a short time I had a greater exercise to be tried with.
It pleased the Lord to call away from me my dear wife, who had been indeed a helpmate,
and a faithful and loving wife to me, about five and thirty years;
and had with a firm faith trusted in God, and had her eye to him in all our sufferings,
trials, and tribulations,
and had seen before her departure how all had wrought for good unto us,
and was satisfied in his will.
In this exercise I found the good hand of God bowing my spirit to his will;
and I murmured not, but praised his holy name that had let her continue so long with me,
and had made her so great a comfort to me in all my afflictions.
Hereby does the Lord work, to the fitting and preparing of my spirit,
to give up all things visible and mortal,
that at last mortality may be swallowed up of life; and that I,
and all his dear people may see this work perfected, is my earnest travel and labour.

After my dear wife`'s departure, I found the Lord still with me,
supporting me in his blessed work he had called me unto,
and my eye was unto him to guide my way.
In the latter end of the year, 1684, I received an opening in the Truth,
that the Lord would give me another wife, to be both a comfort and a careful nurse to me;
but about the same time,
I saw that the Lord had a service for me beyond the seas in the summer coming.
I went first to London, and stayed there the yearly meeting,
and been comforted and refreshed by beholding the
glory of God that from day to day appeared,
and in beholding the love and unity that increased among the brethren.
I then went over to Holland, accompanied with my dear friend,
whom I had seen would be given me as a wife,
and several other Friends both of Holland and England.
The Lord prospered our way, and we came there to their yearly meeting,
where we found the enemy had been trying his old stratagems,
to lay stumbling blocks in the way of the weak, and had caused some to stumble and fall;
and a spirit of enmity was gotten up very high,
and pretended their matter should be heard at the yearly meeting.
And so it was, and the love of God wrought wonderfully for their restoration,
which after several days labour, was so far effected,
that they with joy and thanksgiving came back,
and laid by all their weapons of war and contention,
and were again brought to a tenderness towards God and his people,
to our mutual joy and rejoicing.
While I was in Holland, visiting the meetings there,
I heard there was a door opened for the Truth, in a little city in Friesland,
called Mackum, which I had long desired.
I went there, and preached the everlasting gospel among them;
where I was received with great kindness, and the witness of God was reached in several,
and a love raised to the Truth, which in the Lord`'s time will bring forth good fruit.

Then returning into Holland, and having cleared ourselves of what lay upon us there,
in the sixth month, 1685, we returned for England;
and in sometime after signified to our Friends and brethren what was in our hearts,
in relation to marriage, which was approved unanimously among them.
In the Lord`'s due time, which was upon the first of October, 1685,
we took each other in marriage, and found the Lord with us in it, blessing his own work,
and has indeed manifested it, that we are of God`'s joining;
and he has made us a blessing in his hand one to another, and true yoke-fellows,
both in respect of our own affairs, and in the affairs of his church and people.
For all which, I find my soul engaged to speak good of his name, to bless him,
and praise him, and to say with his servants of old, his mercies endure forever.

Indeed she was a woman beyond many,
excelling in the virtues of the Holy Spirit with which she was baptized,
as she showed forth, both in life and doctrine,
which made her to be a sweet savour throughout the churches of Christ,
and was a pattern of patience and holiness,
discharging her place as a tender and watchful mother to her children,
and as a careful and loving wife to me.
But alas, as the greatest enjoyments of temporal blessings have their end,
so it happened unto me,
for it proved the pleasure of the Lord to try me whether I could part with,
as well as receive, this great mercy.
In the beginning of the year, 1687, she fell into bodily weakness,
and continued so two or three months, and upon the 9th of the third month,
she slept with the faithful in the Lord, in a perfect resignation to his will,
making a blessed end, to my great joy and consolation.
Although it was hard to flesh and blood to part with so precious a companion,
and to be left alone in my old age, accompanied with many infirmities of body,
yet feeling fellowship with her in the joy into which she entered,
gives me great satisfaction; knowing right well her portion is with the righteous,
and her eternal inheritance is among the just, where sorrow,
snares and temptations cannot come.

After she was buried, I went up to London, and conversed among the brethren three months,
where the Lord was pleased to bless my service unto many,
and then returned to Colchester, where I continued great part of the winter following.
In the year 1688, I went up again to London, and visited meetings thereabouts,
as I found it upon me, and also some meetings at my return in Essex and Suffolk.
About the eighth month, I went again to London,
and was there in the great revolution of government; and sometimes as I was able of body,
laboured with other Friends, with the parliament that then sat in the year 1689,
to get those penal laws by which Friends and other`'s had suffered, to be suspended;
and by the good hand of God, an act was passed to that purpose,
which has proved greatly to the ease of tender consciences.

After the yearly meeting of Friends in 1689 was over, I returned again to my habitation,
and continued there the whole winter,
not being able of body to travel by coach as I had done,
many infirmities growing upon me, yet found daily renewing of strength in the inward man,
and the word of the Lord lived in my heart, to the refreshing my soul,
and the souls of many tender babes that lived and grew by the milk of it;
and in this is my fellowship with the living, and my labour, travail and prayer,
that all may be kept in the feeling of it, for this living word abides forever.

[.small-break]
'''

+++[+++After this he spent his time mostly in Colchester and London, in the service of Truth,
and finished his life the 28th day of the sixth month, 1692.]
