== The Testimony of the men`'s meeting at Colchester, concerning Stephen Crisp.

It is sufficient for the righteous, that they know the Lord, and are known of him,
and that their life is hid with God in Christ: such care not for popularity.
Yet forasmuch as the noble acts of the righteous, by which they obtain a good report,
are such as have been pleasing to God, and the names of such shall be had in remembrance;
we find a constraint upon our spirits,
to give this short testimony of the faithfulness of our ancient friend and brother,
Stephen Crisp, late of Colchester,
and unto that blessed gift which the Lord endued him with, beyond many in our day;
and of his sincere labours and travels, who lived with us for many years,
who was a man zealous for the Lord, his name, and truth;
faithful and diligent in his work,
and able to give counsel and advice to many states and conditions,
and which he often did with a free and ready mind.

Some of us that have known him from the beginning,
can remember how the Lord was pleased to visit him in the days of his youth,
and beget desires in him after himself, and after the knowledge of the way of life;
which did work upon him,
so as to put him upon seeking and getting acquaintance
with the best and most upright-hearted of those days,
and was for a time a teacher among a separate people.
In which way and state he continued, until it pleased the Lord,
(for a distressed seed`'s sake,) to send his servant James Parnell, to this town,
in the year 1655, who by the word of the Lord committed to him,
which clave rocks asunder, among many others, reached unto this our friend;
he with many more in these parts, being ready to cry out, What shall we do to be saved?
By his ministry under God, he was convinced of the everlasting truth,
and forthwith made profession of it; and a great change was soon wrought in him,
his understanding opened, and heart wounded before the Lord,
in the feeling of that lively word in his soul,
which is a discerner of the thoughts and intents of the heart.
Then his former building came to be laid low,
and he saw himself to have but a talk and notion of heavenly things;
and that though he had thought himself rich, he was but poor and naked,
and that to a day of stripping he must come, and to deny himself.
And so he did, and sat down in silence under the cross to his own will,
and waited for counsel and instruction to be ministered to him by the Lord.
After some time he had such openness in his mind,
as to impart now and then a word of exhortation to them that needed it,
and visiting some neighbour meetings, was enlarged to speak a few words among them,
and then returned home to his family, and outward calling.
Thus continuing until the Lord further enlarged his gift,
he came to know a further growth and increase in the truth, and in his testimony for it.
Then he found drawings in his spirit into the north of England,
and afterwards into many other parts of it; and into Scotland and Holland,
and some parts of Germany, where he travelled, and was serviceable among them, the more,
in that he had obtained an understanding in the Dutch language, in a very short time,
of whose service there, in the many visits that he gave them,
we leave to our dear friends in those parts, to give account.

He had a large understanding given him, not only in spiritual,
but also in temporal things,
by which he was very serviceable to many widows and fatherless, and others,
(as many can testify,) being very ready and free to assist them;
and as he had freely received, did freely give;
and was therein not only serviceable to Friends, but also to others of his neighbours.

He was zealously and conscientiously affected for
the peace and prosperity of Friends in every place;
and for that cause diligently laboured among them;
and when he was not able to ride or travel much by reason of his distempers,
as in former days, he continued chiefly in this town of Colchester,
and in the city of London, in the Lord`'s work and service,
as long as strength and ability of body lasted.

He was of a constant, firm, bold mind and spirit,
against all those that secretly or openly sought occasion to make
rents and divisions among us in the churches of Christ,
and laboured diligently to preserve the simple-hearted from
being betrayed by their snares and cunning insinuations,
exhorting them, as did the apostle, to mark those that cause divisions,
and to avoid them, and to keep in the unity of the spirit,
and in the sense of the grace received, that all might grow up in it,
into a further discerning of the mysterious workings of the enemy that goes round about,
and tries every way, to see whom he may devour.

He had a gift of utterance beyond many, sound in judgment and doctrine,
and very convincing to the understandings of many that heard him; for which cause,
his testimony was affecting to many that were not of us,
who would come to hear him when he was with us.
He would often call to people to come and try the sufficiency of the grace of God,
a measure of which was committed to them, and whether it was not able to save from sin,
yes, to the utmost, all such as received and obeyed it.
He divided the word aright, and turned many from darkness to light;
many mourners have been comforted by him,
and many tender-hearted helped through their inward exercises and conflicts of spirit,
and has been a strength to them in their spiritual warfare.
His testimony was as a sharp two-edged sword, to the rebellious, obdurate,
and hard-hearted, to the piercing through them many a time;
and his very outward countenance has sometimes struck to the heart,
as some have since confessed.
Some that have gotten into a spirit of enmity,
have been made through the power that did accompany him,
to come and acknowledge the hurt which that spirit had done them;
and that the Lord was with him.

At taking his last farewell, when he was about to leave us,
he was for several meetings before his departure, mightily opened in his spirit,
in our public meetings, desiring to be clear of the blood of all,
as he several times of late said he was, labouring to speak to the states of all,
and also to Friends`' services to which they were called in their day,
to keep truth`'s testimony clear from all unrighteous actions that might
be committed by those that lived not in that they made profession of,
and to set judgment a-top of them, saying,
if we ceased to separate between the precious and the vile, the vile would overrun us,
and we should become like other people.
Also he took notice of, and rejoiced in the love and unity that had been,
and was among us, exhorting and counselling us to be and continue in the same mind,
keeping the unity of the spirit, in the bond of peace.

He was beloved of his friends, his townsmen and neighbours,
and left or had not many enemies,
at least not more than apostates and false professors of the truth,
who forsaking and turning their backs on God,
no wonder such are envious and opposers of his servants.

He was very tender and helpful to many,
who have been of late called forth into a public testimony,
and into the same work wherein he was himself employed
by his great Lord and Master Christ Jesus,
being very tender and ready to help forward that which he
found to come from the motion of the Seed of life in any,
and would speak a word in season to such.
And his last testimony in our yearly meeting on that account, is worthy of remembrance.

In his last being among us, he was very weighty in his visits in our private families,
often dropping some weighty discourse among us for our edification, furtherance,
and growth in the truth.

For all which works sake, he was much esteemed, and was worthy of double honour;
and we doubt not but is clothed with a large share of honour,
glory and immortality with our God,
which is the portion of all those that faithfully serve and honour the Lord in their day,
as he did.

Signed in behalf of our men`'s meeting at Colchester, the 17th of the eighth month, 1692,

Arthur Gotten, Thomas Wear, Thomas Bales, Daniel Vande Wall, Solomon Fromantell,
Anthony Whaypool, John Furly, Henry Pomfret, Samuel Cooper, John Perry, Richard Waller.

[.asterism]
'''

From the second-day morning meeting, the 4th of the Fourth month, 1694.

Being not willing to multiply many particular testimonies concerning
our dear deceased friend and brother Stephen Crisp,
and having unity with the aforegoing accounts, in a living remembrance of that love,
life and power that he was endued with,
and of his labours and services in the gospel of peace, in the church of Christ,
and of his travails and sufferings for the propagation and preaching the same,
we hereunto subscribe our names, and tenderly desire that all may love, live,
and have their minds sincerely exercised towards the Lord,
in that which teaches how to rightly prize, esteem and make use of the Lord`'s mercies,
and the labours, services and writings of the ministers and servants of Christ,
in whose love we remain servants of Christ, and well-wishers to all men,

George Whitehead, John Whitehead, Francis Camfield, William Bingley, John Vaughton,
Samuel Waldenfield, John Eldridge, Fran.
Stamper.
Ambrose Rigge.

[.asterism]
'''

The Testimony of the yearly meeting of Friends, held at Amsterdam, the Fifth month, anno,
1693, concerning our dear friend, and servant of Christ Jesus, Stephen Crisp.

Being acquainted with the intentions of our dear friends and brethren in England,
to commit to posterity, in a collection, the writings of that eminent servant of God,
and faithful minister of the Gospel of Jesus Christ, Stephen Crisp,
whose ministry in and through the power of God, was effectual unto many;
and among the rest, to us also in these eastern countries: Holland Friesland, Embden,
Hamburgh, Frederickstadt, Dantzick, Palatinate, and Crevelt:
and we having been no small sharers with our Friends in England, etc.,
in the blessed benefit of his acceptable service, do give also our testimony,
in this collection concerning him, in a true and faithful account of his services,
labours and travels in these parts,
and to bless the Lord for his continued care over his church and people here.
He sent him first among us,
about the time that it pleased God to take from us our dear and well-beloved Friends,
and his faithful servants, and ministers of the gospel, William Ames, William Caton,
and John Higgins,
who had it chiefly upon them to preach the truth and watch
over the little flock of Christ in these countries,
and to minister unto the believers thereof in these parts,
according to the heavenly gift committed to them.

We say, we have cause to bless the Lord, and esteem his Divine hand of providence,
that about that juncture of time,
the Lord should move upon the spirit of this our dear friend
Stephen Crisp in the powerful drawings of his love,
to turn his face towards us.
In the movings of that love and life in which he then began to recommend himself to us,
and in which he still lives among us,
he was made willing to put his shoulders under the
burdens that he was to bear in these parts,
on the truth`'s account; and that in such a degree,
that he made it not only his work to come and visit us sometimes,
and thereby give us opportunities to be refreshed and comforted in his company,
in our meetings and private discourses,
as we have also been with many others of our dear and beloved Friends from England,
from time to time,
but also he very diligently took notice of all the occurrences in which truth was concerned.

He was not weary of labouring in the spirit of wisdom and understanding,
which God was pleased to endue him with in a large measure, both in words and writings,
in the spreading of the truth, in doctrine, and stopping the mouths of gainsayers,
and turning back the calumnies and falsehoods which were often cast upon the truth,
and return it upon the heads of its enemies and opposers; and also in counsel,
information, admonition, exhortation and advice, both in public and private,
preaching the truth very acceptably in the Low Dutch language,
and assisting various ways many that needed it,
in the ordering of their concerns belonging to this world,
for which also the Lord had greatly furnished him with a capacity beyond many others.
When from time to time, his service for God`'s truth called him from hence,
he left us always that comfort, that he did not draw his heart from us,
which was very fatherly towards us, but held a constant eye upon us,
and truth`'s and our concerns here, and was always ready,
as much as that outward distance, and his service in England would permit him,
to assist us, as when he was present among us.

When he came to Holland, he also generally went to Friesland,
where he visited some there that were in a measure convinced;
and others that were willing to hear his testimony for the truth,
even before there was a meeting settled in that province, with dear Josiah Coale,
in the year 1667.
Afterward also he went to Groningen, Embden, Hamburgh, and B`'rederickstadt.
At Leuwarden he visited some Friends that were but a little
before imprisoned there for coming into Friesland,
contrary to the edict there published, forbidding any Quakers coming there.
Against which persecution he wrote his two books,
the First and Second Part of the Outcry against the Persecution in Friesland.

In other places thereabout, he preached the gospel,
to the strengthening and comforting God`'s heritage in those parts,
being in the year 1670.
In the year 1667, he visited the small company of Friends,
then living at a place called Creisheim, in the Palatinate.
He also went to Heidelberg, the residence of the prince elector Charles Louis,
to acquaint him with the unrighteous dealings of the magistrates of Creisheim,
in taking from Friends, three or four times the value of goods for an imposition,
which Friends for conscience sake could not pay; and was friendly received,
and discoursed by the prince; whereby Friends were somewhat eased in their sufferings.
Another time he made a journey into the county of Meurs, to the town of Crevelt,
where a meeting was set up.
Also he visited some well-affected people at Weesel and Cleef; and Anno 1685,
he gave us his last visit here in Holland.

Though his heart was with us to the end of his days,
yet his bodily weakness and infirmities growing upon
and disabling him from performing such travels,
prevented him from manifesting such endeared love
to us in such manner as he used to do before.
So at last, he having finished his service, and done his work,
for which the Lord had raised him up, and assisted him, with his power,
presence and wisdom, to perform,
he is entered into the rest of the righteous and faithful followers of the Lamb,
having passed through many exercises both inward and outward, which to mention,
we shall leave to others, who were more fully acquainted with them.
We dare not repine for the loss of his outward company,
but rest satisfied in the will of God, giving thanks to him,
who has blessed us in the enjoyment of his service of love,
being still partakers of the blessed effects thereof;
and hope the Lord of heaven and earth, will be pleased to raise up many others,
to stand up in the places of such faithful labourers in his vineyard.

Signed in behalf of, and by order of the Quarterly Meeting abovesaid, by John Claus.
