== To the Reader

Though the writer of these sermons does out of modesty decline to print his name,
yet he does assure the reader, that he has not in the least altered or imposed upon,
the preacher`'s sense, either in the taking or transcribing of them.
And he does further declare, that he neither is, nor ever was,
one of the people called Quakers, but always of another persuasion.
Yet being willing, according to the apostle`'s rule,
to "`try all things,`" he has sometimes been present at their meetings;
and having the art of short-writing,
he has taken many of their sermons and prayers from the mouths of several of their preachers;
and among others, those of Stephen Crisp, deceased; which, upon review, appeared to him,
as well as to eminent persons of another sect, to contain so many gospel truths,
delivered with such plainness, zeal and demonstration,
and generally agreeable to the known doctrines of Christianity,
that it is hoped the publishing of them may be useful to the world.
And, that the design and intent of them may be the more readily comprehended,
there is a title given to every sermon,
agreeable to the subject-matter chiefly treated of therein.

[.signed-section-context-close]
London, March, 1694.
