== Sermon II. Heart Preparation for Receiving the Gospel.

Preached at Devonshire-House, Feb.
12, 1687.

It is in my heart at this time,
to desire that everyone`'s heart were prepared to
be made a partaker of the blessings of the gospel;
for there is a certain preparation that everyone must witness in themselves,
before they are capable of receiving divine blessings; for in all ages of the world,
the blessings of the Lord have been manifold,
and his arm has been always stretched out in all ages, to the sons and daughters of men,
that are sensible of the love he has unto them;
and where these tenders of the love of God have met with prepared hearts,
they have received it to their eternal welfare:
But this has been the lamentation that has been taken up upon the greatest part of mankind,
that they have not been prepared to receive the love of God;
their hearts and minds have been so filled with the love of visible things,
and carnal objects, that they have not been truly sensible of the riches of the grace,
mercy, and love of God unto them.

Now, it was said of old by the prophet, that the preparation of the heart is of the Lord;
and there is something that belongs to us on our part,
that we may attain this preparation,
that we may be brought into this spiritual frame of mind; and that is,
by returning to the Lord, for people to think upon his name,
and have regard to his appearance: And although this is not the work of nature,
for by nature the minds of people are abroad,
and they are crying out as the Psalmist speaks, "`Who will show us any good?`"
Yet to help that defect, the Lord has been pleased to send forth his grace and his truth,
and to call unto the sons and daughters of men, that they might seek after him,
that they might "`seek the Lord while he is to be
found;`" and they that hearken to his voice,
they will readily confess, that there is nothing does so well satisfy an immortal soul,
as to be gathered into fellowship with its Maker; and that one time or other,
it is the desire of all men and women, that they might attain peace with the Lord;
and they know there is no peace to the wicked;
they know wickedness will remain until it is abolished and destroyed;
and they know it is not in their power to destroy it;
and therefore of necessity there must be a waiting upon the Lord, who is Almighty,
that he may reveal his power in our weakness.

And they that are thus prepared in their minds, meet religiously together,
with expectation from God; that he, according to his promise, will appear,
and reveal his arm, and do in them, and for them,
that which they cannot do for themselves;
this is a fit occasion for people to meet together,
and to have their expectation from God, and say, Lord, you know my weakness,
and you know the enemies I have to deal with; you know I am not able to overcome them:
Therefore we are now met together, in the presence of the Lord,
to wait to receive at his hands, that power, that life, that virtue,
by which we may be made more than conquerors.
Such a religious meeting thus gathered together, has a promise;
"`I will be in the midst of them,`" says the Lord; and therefore, having a promise,
we may reasonably expect that we shall be made partakers of the living virtue and power,
by which we may do that, which of ourselves we cannot do.

And, friends, it is my soul`'s desire, that you were all thus qualified,
that everyone had an evidence in himself of this right preparedness;
for where the eye is abroad upon any visible thing,
that it seeks satisfaction in anything below the Lord himself,
it will wear away and wax old.
All those objects that people fix their mind upon, they will wax old;
but they whose desires, and the breathings of whose souls are,
that they may grow into acquaintance with their Maker, this will never wax old.
When people`'s minds are fixed, as the people of the Lord of old were,
when they made a comparison between the state of their minds, and the minds of others,
and signified it in these words, "`they are saying; they are crying (that is,
they that are of the world) who will show us any good?`"
But for our parts, our cry is, "`Lord lift up the light of your countenance upon us,
and we will be more glad of that, than they can be with all the increase of corn,
and wine, and oil.`"

Now they that feel in themselves that the reason of their
meeting together is to enjoy the light of God`'s countenance,
and to partake of the blessings of God, they have their expectation from God,
their minds are retired into God; knowing right well,
that if the tongues of men and angels are moved to declare
the heavenly and divine mysteries of the kingdom of God,
they cannot be edified or benefited by them without
the divine help and assistance of God`'s Spirit;
for there is a seal upon them, and none can open that seal,
but the Lion of the tribe of Judah; he only is found worthy to unseal the mystery,
and unseal the divine blessings that are with the Lord:
So that people must come to that retiredness of spirit, to that resignation of soul,
to be as a little child waiting upon the Lord, crying out unto the Lord,
that he will prepare them, that he will make them hungry, and then feed them,
that he will raise a thirst in them,
and then satisfy them with those divine springs of life,
which through the Lord Jesus Christ are opened to everyone that believes.
So far as your minds are stayed and settled in waiting for the Lord,
so far you will feel in yourselves an openness and readiness, that if the Lord speaks,
you are ready to hear him, ready to submit to his word, ready to obey him;
there will be such an openness in the mind, not to the words of any man,
but unto the word of God, to receive that; for where the words of men are received,
though never so excellent, they convert not the soul, but "`the word of the Lord is pure,
converting the soul.`"
And this word is that which is able to quicken those that are dead in sins and trespasses,
and bring them to be made partakers of life.
For it is not an increase of knowledge that will do the turn,
but it is the increase of life and virtue, the increase of godliness,
and submitting our wills unto him that made us: It is this that will do our turn,
this will bring peace to the soul, and bring us into the favour of God,
through our Lord Jesus Christ.
Now, that you may all feel that which prepares the heart for this resignation,
and quietness, and subjection, you must wait upon the Lord,
that you may be made partakers of the blessings of his everlasting gospel,
and of his divine presence: This is that which is most profitable, most advantageous:
And then the Lord will open to you the windows of Heaven,
and rain down these blessings upon you, whereby you will be comforted and refreshed,
far beyond all the works that we can do;
for it is an inward work that must be done upon the soul,
to convert people that have been alienated and estranged from God,
and bring them to a reconciled state, through the Lord Jesus Christ,
whereby they may partake of the divine virtues,
which sanctify and justify the soul in the sight of God.

=== His Prayer After Sermon

Most glorious and powerful Father! your arm of power is made bare in this our day,
to bring salvation to the poor.

O Lord! you have lifted up the light of your countenance upon a
people that have waited for your glory and your salvation;
a little remnant whom the good of this world could not satisfy;
but O Lord! in an acceptable time, you have brought your salvation near;
and the light and brightness of the everlasting gospel,
you have commanded to shine into the hearts and souls
of the mourners and bowed-down ones,
who are seeking the living God, not among the outward forms and ways of men.

But, O blessed Father of Life! you have now brought us to the day of your power,
and bowed our wills, and made us a willing people therein to serve you,
and to do your will on earth, as it is done in Heaven; and for that end, O Lord,
you have put it into the hearts of your people to wait upon you,
in whom all our fresh springs are,
that from you we may receive the renewing of power from day to day.

In all the hours of our temptations and trials, our eyes, O Lord,
have been to you and to your power; and we acknowledge,
to the glory of your power and goodness, that you have been a God near at hand,
when we have been seeking you, and trusting in you,
so that we are a people sensible of your power and presence with us;
for that eye which you keep open to your children it brings your glory to our view,
and shows it breaking forth over the nations;
and we have great joy and satisfaction in beholding
the progress of your mighty power in our day,
how you have broken down and confounded, and are still breaking down and confounding,
all the dark imaginations and devices of the sons and daughters of men,
that have conspired to hinder the breaking forth of the glory of your Son, Christ Jesus.

O powerful God of Life! arise more and more in the greatness of your power and love,
and make known your counsel, and your will among the inhabitants of the earth;
and bow their minds, O Lord! and their wills,
that none may dare to withstand your appearance, lest they be found fighters against God,
and destroyers of themselves.

O powerful Father! for this end,
make bare your arm unto the rulers and governors of these nations,
that they may know your counsels, and bow to your heavenly will,
and may promote your law of righteousness in their own hearts, and the hearts of others;
that by your power, a blessed reformation may be wrought, and a stop put to iniquity;
that it may not run down in a mighty stream, as it has done in time past;
but that truth and righteousness, and sound judgment may be known in the earth:
That they that hunger and thirst after righteousness,
may have their souls desires satisfied;
and so praise and thanksgivings shall arise from their souls to you.

O powerful Father of Life! preserve and keep your children, whom you have gathered,
and purged, and purified, and to whom you have made known the way of life,
and made them a willing people in the day of your power, to do your will,
and to wait for the coming of that kingdom that you
have promised to establish under Christ Jesus,
the King of kings and Lord of lords; and that it may grow, and increase,
and be spread abroad upon the earth, and let everyone desire to be the subject thereof.

Powerful Father of Life! the arm of your power and invisible strength has been revealed,
that nothing has been able to resist or stand against and prevail,
by which you are planting Zion and building Jerusalem, and establishing it:
By the same power, let your work be carried on,
and let many be brought in to be subject to Christ, for the good of their immortal souls:
As you have multiplied your blessings upon us,
so from day to day you have made us sensible of your love unto us,
owning us to be your children and peculiar people, by your presence in the midst of us,
whenever we meet in your name to wait upon you, that so, Living Father, all yours,
both here and everywhere, may be encouraged to attend upon you,
and to be faithful to your power; that waiting for the opening of your counsels,
and the enlightening their understandings, they may be able to comprehend,
with all saints, the height, and depth, and length,
and breadth of your love in Christ Jesus;
that in the sense of the freeness and greatness thereof,
all your children here and everywhere,
that in an everlasting covenant of grace you have gathered to yourself
may have communion with you and your Son and Spirit;
and may return you the honor, glory, and praise of all your love, and mercy, and grace;
for you alone are worthy, who are God over all, blessed forever and ever.
Amen.

