== Sermon IV. The Standard of Truth.

Preached at Grace-Church-Street, May 29, 1692.

There is a universal standard of truth,
that God has set up over all the sons and daughters of men;
he has given the knowledge of it in, and through Jesus Christ;
he has dealt it out to them,
that they may be capable of joining and adhering to the truth,
and to be delivered from eternal condemnation.
This standard and measuring-rule is revealed and manifested in every man and woman,
by the light that shines in their hearts, by which they are able to discern,
and to give a sound and true judgment, (if they are but willing) upon all their own ways.
A man or woman may know in every word they speak, in every action they do,
whether they speak, and do, according to the truth,
or whether they are justified by the truth, in what they speak and do.

I tell you, my friends, this is no small mercy,
that mankind has obtained at the hand of his Maker,
that he is brought into a capacity of not acting blind-fold, but that he may see his way,
and his own inclinations, and pass judgment upon them, whether they are good or evil?
Whether they will stand justified in the sight of his Maker,
or whether they will be condemned.

I confess, the veil of ignorance, that is come over the sons and daughters of men,
through sin, transgression and rebellion, is very great.
And I may say, as the apostle said,
"`sometime you were darkness:`" And what can darkness see?
what can darkness discover?
The Lord our God, that made us, has not left us in that state of darkness,
blindness and ignorance; but through the riches of his mercy and goodness,
has found out a way, to command that light should shine out of darkness,
into people`'s hearts, for all that the Devil did to darken man,
to alienate and estrange him from his Maker.

The same Almighty Power, that said in the creation, "`let there be light,
and it was so;`" he has shined into our hearts; and the way by which he has done so,
is through the Mediator, through Jesus Christ the Redeemer,
in whom the fulness of the God-Head dwells.
He has received power from his Father, not only to by a light and salvation,
but to impart and communicate of that divine light unto them,
even "`unto everyone that comes into the world;`" that so by means thereof,
they may be delivered from their darkness, and ignorance of the mind of God,
that they were liable to in the fall, and might be restored, through the Mediator,
to a capacity of judging of their own actions, and of their own words, and ways,
and inclinations.

This is the standard which God has pitched in everyone of our bosoms,
for the trial of ourselves, either for our justification, or condemnation,
of every word and action.

Now, to make everyone sensible of the greatness of this blessing, consider,
it is not only given to augment and increase knowledge,
but it is given on purpose to allure and persuade men into a liking of truth,
into a love of truth: The apostle esteemed it a wonderful mercy that came by Christ;
he has sent him to bless us, in turning everyone of us from the evil of his ways:
So that here is a capacity that the sons and daughters of men have, through the Mediator,
of being turned from the evil of their ways and doings,
to that which is well-pleasing to God.

The next work, after God has wrought thus mercifully for the sons and daughters of men,
is, that they would be good to themselves, and merciful to themselves,
and take pity of themselves, by a due improvement of the grace, and mercy,
and kindness of God, that he has bestowed freely upon them;
and in bringing all their deeds to that standard,
all their words and actions to that rule; that so whatever they may be, or however many,
if they do not answer that standard and rule, they may deny, withstand and resist them,
that so they may keep out of condemnation:
For the apostle declares it plainly without scruple,
"`there is no condemnation to them that are in Christ Jesus:`"
If he had said to them that profess Christ Jesus,
there had been a large latitude, especially for those nations; but the words are limited,
and you will find them so; that is,
"`to them that are in Christ Jesus;`" and (as if
he should say) that you may know rightly what I mean;
I mean, "`such as walk not after the flesh, but after the spirit.`"
They that are in Christ, walk after his Spirit; for,
"`they that walk not after the Spirit of Christ,
are none of his;`" but they that are his, walk after the spirit of truth,
and there is no condemnation to them.

It is not only the scriptures that ratify and confirm this doctrine,
but you yourselves are all living witnesses of the truth of this,
that so far as you do act and speak in obedience to the principle of truth,
that God has planted in you, you feel no condemnation upon you:
Such a thing I did at such a time, and I had no condemnation: Why so?
because I did it in obedience,
and subjection to that measure of grace that God set up in me; and such a thing I did,
for which I was condemned: Why so?
because I did it according to the inclinations of my own corrupt mind,
and in contradiction to the truth that opened in me.

My friends, I would have you in point of the doctrine of christianity,
to be the better for what you read and hear: It is possible for me to preach the truth,
and you may believe what I say, and you may read the Holy Scriptures,
and have the belief of what you read;
but if you come to a sensible feeling of the fulfilling of things you hear,
you will give a greater seal to the truth of the doctrine,
than by all you have read and heard; and you will grow wise to salvation,
by trying and experiencing the effect of everything you understand;
and not like the carnal men of this world, that have not faith,
that mind only their worldly profits and pleasures, such are "`earthly,
sensual and devilish;`" but I would judge of actions and words, according to truth,
and according to the effect I find in me.
I did such a thing, and I had peace in the doing of it; I feel no reproach,
no condemnation upon me.
Here is a way for people to grow up in the life of christianity;
to keep to the standard of truth; for whether men will or no, they must do it at last,
and may now, if they please, make a trial of their words and actions.

As for the most part of you, you are got past Pilate: Pilate could make that inquiry;
"`what is truth?`"
says he: And I confess, it is not long ago, it is within the memory of man,
that a more serious and better sort of people were so confounded
with the darkness and ignorance of those times,
that they were ready to cry out, what is truth?
and where is truth?
Their eyes were so blinded,
and things were so jumbled and confused by the disputations that men raised,
that made things so dark people could not see their way:
But "`God who has commanded the light to shine out of darkness,`"
has brought a "`glorious day;`" has dissipated,
and scattered, and driven away a great deal of that fog and mist,
that did overspread men`'s minds.
As many as have sincerely sought the truth in the inward parts,
they have found a divine principle of truth,
that has a self-evidencing quality in itself,
to convince the minds and consciences of the sons and daughters of men,
that it is the truth: And to this the Lord has brought most of you,
to be sensible of something that is truth in itself.
There are many things that are true in the words of them; many true expressions;
but there is truth in itself, the essential truth of God, which, as it is in God,
is everlasting and eternal, and will stand over all error, and falsehood, and deceit:
The truth, as it is in Christ Jesus, is a standard and rule for men to act by;
he has given it to the sons and daughters of men; and as it appears in them,
it is either a Judge to condemn them, or a Saviour to save them from their sins,
and to justify them.

Now, that which concerns us, is to find out the measure of truth, or manifestation,
or principle of truth, which it has pleased God to reveal in ourselves:
And whoever will turn their minds a little while inward,
into the serious search and consideration, how the Lord has dealt with them,
they will find they are not quite destitute of truth.
One that makes it his practice to lie, cheat and cozen,
is not utterly destitute of truth; for there is a principle of truth in him,
that does check and reprove him for his theft, lying and falsehood,
and he lives under condemnation himself.
He cannot draw near to the God of truth upon any occasion,
but his lying and falsehood stand in his way.
Now, if so be, that this liar be made sensible of a principle of truth in him,
and do but bring his words and actions to the truth,
so much of it as he knows will make him leave lying and deceiving,
and to practise truth to escape condemnation; if he will but leave lying and falsehood,
and live in the truth, and speak the truth to his neighbour, he will find another state,
condition and frame in his soul, than there was before: He is now more at peace,
And has a clear and serene way, to come to God by prayer,
and for pouring out his supplication, which he had not before;
for he had barred up his own way by his sin, which lay continually at his door;
"`if you do not do well, sin lies at your door,`" says God to Cain: So, when you do evil,
you cannot but know it; when you are drunk, or swear or tell a lie,
and deceive your neighbour, and carry on the design of sinful profit, you know it,
whether men know it or no, and God that made you know it;
and there your sin lies at the door, and blocks and bars you out,
that you can not offer your prayers to God with that clearness,
as if you had spoken the truth: So that it highly concerns everyone of us,
to be waiting upon God, for the discovery of his truth to us; and then we must embrace,
adhere and join to the truth, as our chiefest good.

But some will say, this adhering and joining to the truth, is a hard lesson:
It is pretty easy to find out a principle of truth, that stands against,
and opposes all manner of evil: Very few, now a-days,
will deny a settled principle of truth in all men, that judges falsehood,
and condemns deceit, and witnesses against it in others, and in themselves:
But this same joining, and adhering to it, that cannot be done,
without a cross to a carnal mind.

Now, if the cross of Christ be not taken up, there is no good Christianity among us;
where this is neglected, it spots and stains the profession of Christianity,
because it is so directly opposite to the doctrine of Christ;
he that will be my disciple, must; it is not, he may if he will; but,
he must take up the cross of Christ, and follow Him.
There were a sort of people, that were never likely to be made Christians,
that would be exempt from taking up a daily cross;
therefore he presses it upon them to deny themselves,
and take up his cross and follow him.
No man is like to live a Christian life, without taking up a daily cross.

This I cannot do, says one; I know how to carry myself among Christians with seriousness,
sobriety and watchfulness, without shaming any profession; but I cannot deny myself,
I cannot contradict my own will:
This is that which keeps a man from leading a Christian life,
when he cannot deny himself, and take up his daily cross.

Now, it is come to this now a-days, when a light is broken forth,
and men have a principle of truth in their own hearts, it comes to this; says one,
I ought to be "`holy in all manner of conduct,`" and to be watchful over my words,
and have my conduct honest and just without deceit: See what a deal I know,
yet I can never live this life, for all I know it so well;
I cannot take up a daily cross,
which is so much against the contrary inclinations working in me;
then the question I put to myself is, shall I take up a cross or no?

Here it comes to the point with every man or woman,
after they come to the knowledge of this standard of truth:
If the world would but come to this rule and standard,
there would be no more cheating nor cozening, no more fraud, deceit nor dissimulation,
nor war and bloodshed; but if men would,
in everything they do answer the principle of truth in themselves,
they would put the question to themselves, shall I take up my daily cross, or no?
Shall I deny myself those pleasures that my conscience does condemn;
and those ungodly gains that I seek after by falsehood, by lying,
prevaricating and departing from the truth?
Shall I do this, that I may be rich and great in the world, or shall I not?

You know what I say, many of you, and have put this question to yourselves,
and some have made a good answer to it: I will take up my daily cross,
by the grace of God; this standard of truth shall be the rule of my words and actions,
to my dying-day.

They that have learned this lesson, and obtained peace with God,
through our Lord Jesus Christ, that have not only made a resolution,
but performed it in act and deed, by the power of Christ`'s cross, they are purified,
and sanctified, and washed from their old conducts,
and have their conversation in Heaven; that is, live after a heavenly manner,
live a godly life here upon earth, when they have come to this resolution,
and also the practice of it.

I would desire, and it is my labour, that you that hear me this day,
who are aware of what I am speaking, namely, the standard of Truth,
the principle of Truth, that unerring Guide,
which is placed in the conscience of every man, and justifies, or condemns,
his actions and words.
You who are come to be aware of this,
that you may all come to this godly resolution in yourselves,
I would have this dispute carried on in everyone`'s bosom.
When the question is stated, I would have you really answer it;
shall I guide my actions and words according to this unerring rule, or no?
I cannot tell what to say, say some, there is danger in it:
What danger can there be to answer that which a man knows to be truth?
I will tell you what danger: The world is perverse, and most men live out of truth,
and the Devil is a cunning adversary, and he would have none live in it:
He "`abode not in the truth;`" and he would not have us live in it,
nor regulate our words and actions by the truth in our own souls:
What if most men in the world pervert the truth?
What if so few walk in the "`narrow way,`" and so few come to life eternal;
is that an argument that I must not come there?
Should it not stir me up to greater diligence,
that by any means I may be of the number of that few that shall obtain salvation,
and not go with a great company in the way that leads to destruction?
If we improve our times, and seasons, and opportunities, and mercies, and blessings,
that are vouchsafed to us, we at last may obtain life eternal.

But some may say, I must sit down in despair, for I cannot come there of myself,
though I do what I can to work out my own salvation.
There is a decree against me; what, though I should pray ever so much,
and spend my nights in grief and sorrow?
If I be decreed to eternal damnation, there is no help for me,
no hope that I should escape.
And if I be decreed to salvation, though I take my liberty to sin,
and be loose and careless, as others,
it cannot hinder me from attaining salvation at last.

For this reason, many have laid aside the spiritual warfare against corruption,
and their spiritual travel,
that they will do nothing in order to their everlasting happiness;
therefore they think they had as good take their pleasure: But, my friends,
the case is not now so with us; let every soul among us praise the Lord for his mercy,
in expelling that thick cloud of darkness, which is vanished and gone: This I know,
and I hope you do all believe, that God does everywhere, and in every nation,
call sinners to repentance, and that he delights not in the death of him that dies,
but rather that they would turn and live; and in order thereunto, he has given his Son,
Jesus Christ, to be a Saviour and a Mediator;
and he has sent forth the Spirit of his Son into our hearts,
to give direction to us in our way: Now our duty is,
to make improvement of those visitations of mercy, that God has bestowed upon us,
in order to our salvation, and not live in "`revelry and drunkenness, lewdness and lust,
strife and envy,`" and following the fashions of the world:
But we must "`work out our own salvation with fear and trembling.`"

But some will say, is not this done already?
Is it not already wrought by our Saviour and Mediator?
Christ has tasted death for every man, and laid down a price for the soul of every man.

But yet there must be a change wrought in us; there must be a translation of our souls,
from one state to another.
This is called in the scripture, regeneration, and being born again;
this is called a being baptized into Christ, and described also by other expressions:
But the matter is, to change your life; for there is a sinful source of wickedness,
that is stirred up by the motions of the powers of darkness, and our own concupiscence;
but God is always ready to bring us under the government of his Holy Spirit,
that will lead us into all truth; and this cannot be done without a Cross.
But the question lies here, shall I take up this Cross or no?
If I do, it will crucify me to the world.
Let me see; how much do I love the world?
A great deal: But do I love the world better than my own soul?
"`What will it profit me, to gain the whole world, and lose my own soul?
Or what shall I give in exchange for my soul?`"
I cannot get to Heaven without denying myself; let me take care of my immortal soul:
I am a poor creature; I will serve the Lord my Maker,
and make it my business to glorify and please him.
He can snatch me away by death when he pleases; therefore will I labour,
that my thoughts, words, actions and conduct,
may answer to that rule that he has set before me, as a standard of truth,
to square and regulate my actions by.
I will not live any longer in vanity, as many do;
I do not know but my breath may be stopped today, before tomorrow; therefore today,
while it is called today, I will hear God`'s voice, and not harden my heart,
but receive that counsel, that is offered to me, for the benefit of my soul.
I am bought with a price, I am none of my own; I will live to him that died for me:
I have more reason to live to Christ, and serve him,
that shed his precious blood for the redemption of my soul, and to be subject to him,
than to be subject to Christ`'s enemy, to the prince of the power of the air,
who rules in the children of disobedience.
I will take up a resolution to serve God, but I can do nothing of myself;
but the grace of God which brings salvation, will teach me to deny ungodliness,
and worldly lusts, and to live righteously, soberly and godly, in this present world.
Take heed of being deceived and beguiled, for there is no way will bring you to Heaven,
but a holy and undefiled way.

Therefore, come and take this, standard of truth in your hands, to guide you in your way,
that you may neither turn to the right hand, nor to the left:
This will show you the way you should walk in,
and be like the cloud and pillar of fire to the Israelites, in their journey to Canaan,
which was a type of Heaven; the cloud they could see by day,
and the pillar of fire by night;
so this standard of truth will direct you in your travel to the heavenly Canaan.
Let this be the rule and measure of your thoughts, words and actions.

If a workman, that is a builder, has a rule to work by; if he goes on,
and never examines his work by his rule, but makes his eye his rule;
if he does not bring his rule to his work every little while,
to see whether his Work be right; if he works on, and never minds his rule,
what sad work will he make.
But a prudent skillful workman will say, I will not trust my eye too much,
but I will look to my rule, my rule will not fail me; if there be bad work,
it will discover it to me, that I may mend it before I go any further.
Thus a discreet workman will often bring his rule to his work,
and use his line and plummet, that he may make it workmanlike.
He will say, if I let my rule alone, and not make use of it, but work as I please,
and trust to my eye, no wonder if I make bad work, and what I build fall down again,
and tumble about my ears.

You to whom God has given the standard of truth,
as a rule and measure to govern your thoughts, words and actions by,
let everything be tried with it, before you die, and leave this world: If you do so,
and make this your daily practice, then ask yourselves,
and you will be able to tell yourselves, and tell me, and say,
I have now obtained more hopes of God`'s favour,
and a greater sense of his love and goodness to me, than ever I had before.
The apostle does exhort us, to "`walk circumspectly, not as fools, but as wise,
redeeming the time.`"
We have spent a great deal of time in vain, let us now be wise, and improve our time,
for our eternal advantage; let us walk circumspectly, that is, look round about us,
consider our ways, and try all our thoughts, words and actions, by the standard of truth.
"`Today (my friends) while it is called today,`" hear the voice of God,
and "`harden not your hearts,`" and receive that heavenly counsel,
that is tendered to you, that you may be "`partakers of the inheritance,
among the saints in light.`"

=== His Prayer After Sermon

Blessed and eternal Father! you have brought forth your glorious name,
and revealed your power and your mighty arm;
and you have caused a remnant to bow and worship at your appearance: You are wonderful;
your majesty is great; they that do behold you, will, with reverence, worship before you.
Your power is gone forth, and has reached the hearts of your people;
you have humbled them, and subjected them to your Divine, Almighty Power,
that they might appear in the earth, to the praise and glory of your great name.

And, O Lord, as you have begun a great work in the earth,
so you have committed this work to your servants and children,
that bear your name among the sons of men,
that they should show forth your righteousness, among the inhabitants of the earth;
and our souls have said many a time, who is sufficient for these things?
All our fitness and sufficiency, our meetness and preparation is from you:
Do reveal your power, and make bare your Almighty arm.
We have found your presence from day to day, and you have upheld them that know your love.

O glorious God of Life! herein we have encouragement
to go on in the work which you have called us to;
hereby we are enabled to worship before you,
and to offer up living praises unto your great name,
for that refreshment and consolation, which you have ministered unto your people.

And, O Living Father! we have never waited on you in vain;
whenever we have met together in your name, we have found your Divine Presence,
and the opening of the treasures of your love, of your wisdom,
and of your favour to your children: So that from day to day, and even at this day,
you remember your people, and you give them fresh occasion to draw near to you,
and receive their daily nourishment and strength, from the operation of your power.

O living God of Life! gather up the hearts of your people more and more,
and draw them into a nearness to yourself, that their understandings may be more and,
more opened to discern your will, and subject themselves to your wisdom,
that every thought that is exalted against your divine power, and living voice,
in their own consciences, may be brought down;
that so all the nations of the earth may bow before you; that so your truth may reign,
and your power may be exalted, and the righteousness which you have revealed,
may shine forth more and more, in the brightness and glory of it,
and enlighten those that are afar off, that they may be brought to seek after God.

And, Living God of Life! let those that are bowed down under the weight of sin,
be supported and raised up; and those that are weary and heavy laden,
let them have rest to their souls.

Powerful God of Life! keep your people in a fresh and living sense of your love,
and of your heavenly virtue, by which you nourish your children,
and satisfy them from day to day; not only when they are met together,
but when they are separated from one another.
Let your people be preserved from the evil of the world, while they are in it,
and let your wisdom and power give them victory over it,
that you may have the glory of all your mercies and blessings, vouchsafed to them.
For you alone are worthy, who are God over all, blessed forever, and ever.
Amen.

