[short="Sermon VI. The Divine Monitor; or, Light From Heaven."]
== Sermon VI. The Divine Monitor; or, Light From Heaven.

Preached at Grace-Church-Street, June 19, 1692.

It is a great privilege to the sons and daughters of men,
that it has pleased God Almighty to open a way,
how they may come to the true knowledge of himself.
And O that there was a heart in everyone of us,
that could rightly prize this privilege as we ought to do! for
in the knowledge of the true God consists our true happiness;
and without this, the mind of no man or woman can be good.
There is nothing seasons the mind and soul of man,
and prepares and fits it for an everlasting well-being,
but the divine knowledge of the living God that made him.
And there is a propensity in the soul of man, even since the fall,
to return again to God,
and to have that acquaintance and communion with the Lord that man had before he fell:
And they that have regard to that inward spark of divine love,
that they find in their own souls towards God,
they will experience that the Lord is merciful and gracious,
and propitious to that which is of himself.

For though the soul is lost, and man is lost through transgression,
and a great alienation has happened between him and his Maker,
yet the mercy of the Lord endures forever;
and his kindness and favour to lost man is such,
that he stretches out his hand all the day long,
and presents and offers to the children of men a friendship and acquaintance,
and a communion again with him.
And though by sin and transgression,
there is a rebellious nature grown up in the sons and daughters of men,
yet the soul of man is not wholly so;
there is something that strives and labours in a contrary way,
and persuades the soul to turn again unto the Lord, and to wait for the knowledge of God;
and whoever hearkens with care and diligence, to that divine Monitor,
that is daily drawing and persuading people to seek after God, they come to understand,
that the Lord is not so angry with mankind, but his love, and mercy, and good will,
reaches towards all the sons and daughters of men;
and the bar that hinders their communion with God, and peace with God,
it is not in the Lord, but it is in themselves;
and therefore the remedy must be wrought in themselves.

This is evident to every eye, that there is something gotten into mankind,
which the Holy God cannot own, and can never have fellowship with; that is,
another contrary spirit has wrought upon the souls of people,
and has seduced and drawn them out to that which is unholy and contrary to God,
and the terms of God`'s covenant to mankind, which is,
that he should forsake that which the contrary spirit has wrought.
"`Let the wicked forsake his ways, and the unrighteous man his thoughts.`"
Why should he forsake his ways?
Because the Lord never led him into those ways.
He that made him, never led him into them; but the devil, the enemy of mankind,
seduced him into those ways; therefore the Creator cries out to him,
"`let the wicked forsake his ways,
and the unrighteous man his thoughts;`" I cannot have union with him,
as long as he walks in his evil ways; I cannot dwell in his mind,
so long as evil thoughts are in it:
So may the Lord complain of the works which the devil has wrought,
that man is carried away from God, by his evil thoughts, and the works of the devil.

Why does not God destroy those works, when he is Almighty, and able to do it?
Very true, God is so; but he has offered to mankind, through the son of his love,
a way and means, how man may come to be purged,
and cleansed from the evil that the devil has wrought in him,
and how he may come to be reconciled to God:
God has not chosen the way of coercion and force,
and to work altogether by irresistible power,
that man shall go to Heaven whether he will or no:
There was no force used for his going to hell and darkness,
but it was the choice of his will: The devil could not have forced him,
and led him away out of covenant with God,
he could not compel him to break the holy command of God; but the devil tempted him,
and he yielded to the temptation, and now man is driven out of the presence of God;
yet God has found out a way for the sons and daughters of men, to turn again to him:
What by force and coercion, and irresistible power?
No, but the scripture says, He has offered life and salvation to all men:
He has freely given the Son of his love, out of his own bosom,
who making himself an offering for sin,
has presented a way and means for man`'s returning again to God.

How does God present Christ to us?
He presents him to the view of everyone`'s mind, to the understanding of every soul;
he offers and presents him for salvation to the ends of the earth.
There is a damnation come in by man`'s being subject to Satan,
but salvation comes in by his being subject to Christ;
as damnation came in by his being defiled, so salvation came in by his being cleansed:
As the devil is the defiler, so Christ is the cleanser,
and man is the object upon which both do work;
and they that have been defiled and corrupted (as we all have) by the unclean Spirit,
can any of us give a reason they should not be cleansed by the holy Spirit?
We have lost our right to Heaven by sin and transgression, in the first Adam;
and can any give a reason, why we should not be restored, and redeemed, by Jesus Christ,
the second Adam?
No reason can be given of our redemption, but that God is free in his love,
and Christ in his offering: He has offered himself a sacrifice for sin:
Every priest has something to offer; this man, the man Christ Jesus, offered himself,
through the eternal Spirit, a sacrifice for sin; and now the sacrifice is offered,
and a door is opened, and a new and living way consecrated through the veil,
that is to say, his flesh.

Now, who can be wise enough to find out a reason, why all men enter not in at this door?
For all men enter in at the other door, which the devil and Adam opened, to run from God;
all could run in at that door.
What is the reason, that all go not in at that door which Christ has opened,
and God has revealed, and which cost Christ so dear to work our way back again,
for mankind to return to God?
If we go about to inquire into the reason, we shall find it very little,
for there is all the reason in the world we should serve God, and seek our own happiness;
there is all the reason in the world we should part with sin and iniquity,
and with the devil`'s work, which he wrought, if we knew but how: Now this, I say,
is a great privilege, that God has afforded to the sons and daughters of men,
that they may know; for here the terms of the gospel and of salvation,
are brought into a narrow compass, to a short sum, there need no catalogue of them;
they that will be ruled by the wicked one, must have their part with him;
and they that will be ruled and governed by the Holy One, shall have their part with him,
"`that where he is, there they may be also.`"

Is this in the power of man`'s will?
No, there lies the mischief in the will of man; for you cannot but know by experience,
if a man may have his own will, he will always run headlong to destruction,
and run in the way of wickedness: And if ever he comes to turn out of that way,
into the way of righteousness, he must do it in a way that is a cross to his own will.
Some have said, because we have spoken of the free grace of God,
in a way that is universal, of his kindness to mankind, through Jesus Christ,
they have said, that we hold free-will, that men might be saved if they would; but alas,
we have tried it, and we have a universal knowledge, that is able to convince us,
and all the world, that it is far enough from our own will.
Man is far enough from being able to save himself, from being saved by his own will:
He can run on to damnation, there is a current goes with his affections,
and with his corrupt desires, they go with the current and stream;
as long as a man goes on in sin, he swims down the stream.

Now many, after they have long gone on in sin, and their evil ways,
they think of returning to God; for they think there is a better way,
a surer and safer way for their souls, than to go on in wickedness: So there is;
if there be so, says the sincere soul, O that I might walk in it: Why do you not?
I am convinced that I see a more excellent way than my way is,
a better walking and conduct than my life is;
but alas! it is too hard for me to walk in it: Why?
what is the matter, what makes it hard?
because of my own will; I cannot walk in it and have my will, I cannot walk in it,
and enjoy my affections and desires, and my interest in the world:
This is no wonder that you tell me; now you are convinced of a better way,
and would walk in it, and you can not walk in it, but you must take up a daily cross;
we might all of us tell that, and read it before;
I pray God you may come to read it within, what a cross it is you are to take up,
and what way it is you are required to walk in; that is the way of God,
the way that leads to Heaven, it is a narrow way;
but the way that the devil would have you to walk in, is a broad way,
there is no rub in it.

O would you but once come to experience how hard
it is to walk in that way that leads to life,
you would find that you cannot do it without self-denial: It comes to this point;
I have read of it before, but now I find it so.
Such a man, or such a woman, will seriously apply themselves to live blameless, harmless,
and inoffensive towards God and men; they will set a bridle,
and a watch before their mouths, that they may not speak a vain word;
they will take care of the frame and temper of their minds,
that they sin not in their thoughts, that they sin not with their lips,
nor with their hands.
This is not as I was accustomed to do; I was used to have my liberty;
now I find myself yoked, I dare not sin against God: Now I find, by experience,
what I heard before, that no man can follow Christ, without denying himself,
and taking up a daily cross.

I would have you experienced in this work; wicked men think it a pleasant life,
to follow the devil`'s work,
and to walk in the "`broad way;`" but the way of self-denial is uneasy,
there is much strife and opposition in that way; If I have a mind to speak a vain word,
I am limited; if I have a desire to wrong my neighbour, and cheat and defraud him,
I am limited, I am not to do it, that belongs to the broad way:
If a man will seek after the Lord, and walk in the way of holiness and righteousness,
the end whereof is peace, he will find it is a narrow way,
wherein he cannot enjoy his own will; such a one must be a David, who said,
"`I behaved myself as a weaned child;`" that is, as one that is afraid to be beaten.

But you will be ready to say, I am a man, and not a child; I am come now to be a man,
a man of parts; I have seen much, and read much, and would you have me become a child?
How great a man was David: If you speak of a man, he was a man of dignity and honour,
a man of valour and experience;
yet when he speaks with respect to the frame of his mind before the Lord, he says,
he behaved himself "`as a weaned child,`" as one that feared to be beaten,
feared to commit an offence; he feared the rod of his God upon him;
he feared something of judgment upon his conscience.
David was an old testament man, but he had regard to that which never waxes old,
which is the same in all times, new and old, Alpha and Omega.
Christ Jesus was his leader, before he was born of the Virgin Mary;
his word was a light to his feet, and a lantern to his paths:
David had acquaintance with God, who did lift up the light of his countenance upon him.

And when Christ himself came to preach upon earth, he says himself,
everyone that comes into the kingdom of God, must become as a little child.
He must become as a little child in simplicity and subjection;
he must be under government; he must become as a little child,
or he must in no way enter the kingdom of Heaven;
they must not think to enter into Christ`'s kingdom because they are men; men of parts,
men of courage, men of understanding, learned doctors,
masters of liberal arts and sciences: These may help to make them men,
but they must be children; all their wits, and parts, and manhood, courage and valour,
will do them no good; for little children, babes and sucklings,
may understand more than they of Divine Mysteries,
and have greater communion and fellowship between God and their souls than they;
so that all who enter into Christ`'s kingdom, must become like little children.

So that here is a way provided by Jesus Christ,
for man to come again into the favour of God, which is by Christ alone,
not by anything that a man can do; Christ must be their leader and their counsellor,
he alone can give them the true knowledge of God.
No man can know the Father but the Son, and he to whom the Son reveals him.
Men can never attain to the saving knowledge of God by study,
and by disputation and reading books, and commentators,
and observators of matters of religion,
Time would fail me to speak of the multitude of books
that have been written about the knowledge of God.
You must come to Christ for divine knowledge; theology, the knowledge of God,
and divine and heavenly things, are from Christ: He shall have this divine knowledge,
be he ever so simple, that comes unto Christ for it; he cannot have it any other way,
for God has ordained this way: Says God, he shall have it of my Son,
who is the Reconciles the Mediator between God and man,
he shall be beholden to Christ for all.
All men`'s own works and labours will not justify and save them,
for God has committed the whole work of salvation to Christ.
One would think it should be no great matter for
men to lay aside their own works and duties,
and submit to Christ; but I tell you it is very hard, and I found it hard myself.

Men think by reading and learning,
and hearing this and the other man`'s notions and opinions,
they may be edified and profited, and come to the true knowledge of God;
but while they are waiting upon God, in the way he has appointed,
they may receive knowledge from Christ,
and be more certain and infallible in what they do know,
than by consulting all the wise men and learned doctors in the world.
For no man knows all at once; and no man knows all things neither:
It is not a thing necessary that man should know all things in relation to God;
for as he is in himself, he is incomprehensible: For no man knows the Father but the Son,
and he to whom the Son shall reveal him; yet that which he knows of God,
he may know it is certain and infallible.

Suppose a man know nothing of God, but that he is the searcher of the heart,
and trier of the reins.
There are many that have tried this, and say they know it,
that yet doubt whether there be a God or no.
But when God comes within them, and convinces them of sin, and searches them,
and brings judgment upon them for what they have done, then they know infallibly,
that God is the searcher of hearts.
This is not a man`'s work, this is the work of God;
if I find God does approach my spirit, I know it is God`'s work;
I have now got some knowledge of God, how came I by it?
Who gave it me?
No one but he that has all knowledge; he that was with the Father from the beginning,
and was glorified with the Father before the world began, he gave me this knowledge;
and now did he give it you?
By his Spirit; for he has sent forth the Spirit of his Son into my heart;
and that Spirit of Christ searches the hearts, and tries the reins.
He tells me this is evil that you have done,
this is that which God that made you has against you; this you must forsake,
and this you must repent of; here I have an infallibility of what I know,
but I cannot get rid of my evil.

Now if I can believe in the power by which my heart is searched,
and trust in him that has begun to deal with me,
then his work is not only to reveal his light to convince me,
but to put forth his power to convert me;
so that by the power of that truth by which my heart is searched, I come to be converted,
and turned from my sin, and break off from it; and when I am broken off from it,
I am sure, and have a certainty that it is so, that I am broken off from such a sin,
and that my heart is turned against it; I am sure that now I hate it, and detest it,
and that God has turned my inclinations another way: I am sure this is God`'s work,
I can witness this infallibly, that something is now done in order to my redemption:
But there is something yet remaining to be done: What then?
I will go step by step, by following my guide,
I shall be sure to be making some progress every day,
to that state to which the Spirit of Christ will lead me:
These persons come to a certainty of knowledge by their own experience.

Some will say, take heed of being deluded and deceived by the Quakers; so say I too:
Take heed of being deluded by anybody; if any go about to persuade you,
to believe that which you know to be a lie, I am sure they are about to delude you;
I would have everyone to have an evidence in themselves of what they believe.

Does a man believe that such a one is a drunkard,
because the scriptures declare judgment against the drunkards?
the scripture says,
"`woe to the drunkards of Ephraim:`" There are judgments
denounced against the drunkards in the old testament;
consider the scripture does not tell such and such by name, that they are drunkards;
but the Spirit of God, by a work and operation upon a man`'s conscience, singles him out,
and charges him with the guilt of drunkenness.

There is a great condemnation pronounced against whoremongers in scripture,
but it does not tell us who they are by name; but their consciences tell them so,
and gives infallible judgment against them, and say, you are the man,
you are a person that God does judge and condemn; whoremongers and adulterers,
God will judge; but that does not concern you, and affect you, except you be one;
I may read this a hundred times in the scripture,
and not have a reflection in my own conscience, except I be guilty:
But when God meets with a guilty person, and judges and condemns him,
there will be an infallibility in what such a one knows.
If a whoremonger is reflected upon by his own conscience,
if his conscience tell him he is the man, if all the world should flatter him,
and say he is not guilty, he would certainly know that they tell him a lie.

So that here is no dependence upon any man`'s judgment,
but upon an invisible judge in a man`'s own heart: Who shall delude and deceive this man,
that has this experiential knowledge?
those persons will not deceive a man, that would turn him from the evil of his ways;
these do not go about to deceive him,
that will tell him he must hearken to that principle
of truth and holiness in his own heart;
they would deceive him that tell him he is converted when he is not, and leave him there:
But when he is really converted and turned from sin to God,
some will tell him he is deluded and deceived;
I pray God everyone of us may be so deceived: Says the apostle, "`we are deceivers,
yet true:`" All that are truly converted, though men cry out they are deceivers,
though they are deceivers, yet true; they are come to the savour of the knowledge of God,
through Christ;
and so shall certainly come to be partakers of the inheritance that is undefiled,
and that fades not away.

Friends, you know that this has been the proposition of all the prophets, and apostles,
from the beginning to this day;
the thing that they have proposed to the sons and daughters of men,
has been to inquire after the knowledge of the true God:
It has been wonderful to consider,
what the devil has done to present various doctrines that he has found out,
and stirred up others to invent a company of gods,
that other people have adored and worshipped.
It is hard to find any nation that do not worship some God;
it is natural for man to desire to come to some God, he thinks he must come to some God,
and cannot be happy if he come not to God: But the devil has invented many gods,
and set the people a worshipping of idols, the work of men`'s hands,
such gods that are so far from helping their worshippers,
that they cannot help themselves, they cannot wipe off the dust from their own faces;
and if they fall down, they cannot rise again.

But this is not our case, we have but one God preached among us,
and but one Lord Jesus Christ, the Mediator between God and man: Our condition is happy,
in having but one God, in comparison of theirs that have many gods.

If the true God, that you worship, were but trusted in,
you would be the happiest people in the world: If you do but search,
you will find that the devil has in this nation, and in this age,
stirred up people to worship as many gods, as he did in other nations in ancient times,
among the Sidonians, and Amorites, and others.

But you will say, we worship one God, and trust only in one God, and one Christ,
and one Holy Spirit, the only living and true God.

Do not tell me what God a man professes to worship but what God he trusts in,
that gives it the name: Whatever a man trusts in, that he makes his God,
whether it be gold or silver, or the honours and pleasures of this world,
if he trusts in these things, he makes them his God.
Let a man but search and try himself,
and he will find something has got a place in his heart,
that he cannot part with for Christ`'s sake.
He will be ready to say, I cannot part with my house and land, with my wife and children,
and my goods and possessions, because I have a confidence in them,
and believe they will do me good, and be a defence for me;
I trust that in times of peril those things may do me good.
Here is a divine adoration, here is that trust, that confidence,
that all true Christians ought to have in the true God,
and this is placed in these earthly things.
Now, wherever the trust and confidence is placed in transitory and earthly perishing things,
these men trust in transitory gods.

Nothing so shows that a man makes the Lord his God, as when he casts all care on him,
and puts his whole trust in him,
when he makes a profession and acknowledgment of his dominion and greatness,
and of all his other perfections,
that by his wisdom he can procure for them all that is good, and by his power,
keep off from them, and secure them from evil.
When I make the Lord my trust and refuge, and trust him for my God,
I choose him before all the gods of the Heathen,
and trust in him above all things under Heaven,
upon the account of the profundity of his wisdom, and the almightiness of his power:
When a man has this sense upon him,
he will walk before the Lord with resignation of mind,
and be willing to be at God`'s disposal, and he will not only give up himself to God,
but he will hearken to him, and hear his voice when he speaks to him.

"`God, who at sundry times, and in various manners spoke in time past,
unto the fathers by the prophets, has in these last days spoken to us by his Son:`" But,
where is his Son, you will say?
He is in Heaven;
but though he is "`the high and lofty one that inhabits
eternity,`" yet he dwells with meek,
humble and contrite hearts, that tremble at his word.
If I be one of the number of those that tremble at God`'s word,
I have that promise that he will come home to me, and dwell with me.
It is well for you, if the over-ruling power of God has prevailed upon you,
that you can be willing to be at God`'s disposal, and say, Lord,
what would you have me to do?

Therefore, friends, I would advise you all to love your own souls,
that when God desires your hearts, you would give them up to him,
that there he might delight to dwell, and have his habitation.
Hearken to God`'s voice, and have regard to his word,
which is a more sure word than any man`'s in the world.
"`There is a more sure word of prophecy,`" says the apostle,
"`unto which you will do well to take heed.`"
This will check you, and reprove you, when you do evil,
and show you wherein you have transgressed; and will encourage you,
and be a comfort to you, when you do that which is good.
This will make you wise to salvation, and thoroughly furnish you,
and give you understanding for every good work.
This word will tell you, this you must not do, lest you offend God,
and wound your conscience, and grieve the Holy Spirit;
this word will help you so to speak, as to administer grace to the hearers;
such a one as has regard to this word, has a chaplain in his own bosom,
that will direct and teach him how to steer his course, and order his conduct among men,
and how to serve God acceptably.
This High Priest`'s lips will preserve knowledge, even Jesus Christ the righteous,
who speaks to us in his word; we can do nothing but by his direction:
If you come to him to lead you into all truth, he will bring you to the Father,
and reconcile you to him, that so you may obtain his favour and everlasting life.
When one of Christ`'s disciples said, "`show us the Father,
and it suffices us,`" Jesus says unto him, "`he that has seen me, has seen the Father,
and how do you then say, show us the Father?`"
If you subject yourselves to Christ, and to the government of his Spirit,
he will bring you to that life and immortality, that "`fades not away.`"

This has been our labour and travel from time to time, to preach Christ among you,
and not to preach ourselves, and gather a church for ourselves,
but to gather a people unto Christ, who is Lord of Heaven and Earth.
We would preach Christ Jesus the Lord;
we would not have you admire men`'s words and sayings, and charge your memory with them;
but we would have you remember the words and sayings of Christ,
who is the great Mediator, to reconcile man again to God,
that you may know him by his power, working effectually in your hearts;
we labour for nothing else, and we want nothing else.
"`We are ambassadors for Christ, as though God did beseech you by us; we pray you,
in Christ`'s stead, be reconciled to God:`" That you may so live,
that "`whether you eat or drink, or whatever you do,
you may do it all to the glory of God,`" your great Creator,
that has given his Son to die for you, and redeem you from all iniquity,
that you might be a "`peculiar people, zealous of good works.`"

Let God have all the honour and glory, for all his mercies and blessings;
let us render unto him hearty praises, and thanksgiving, for his wonderful love,
and acknowledge that it is a great privilege that we may obtain by Jesus Christ,
even to be brought again to have the knowledge of the living God,
which we lost by our transgression.

=== His Prayer After Sermon

Glorious are you in your appearance, O Lord! and very wonderful is your power,
and your ways past finding out: And in this your glorious day,
you are opening a way for the sons and daughters of men, to turn to you.

And, O Lord! those whose eyes you have opened, rejoice and are glad,
because they have seen the way of your salvation; and the breathings of their souls are,
that their feet may be kept therein,
and that they may make strait steps in their way to your kingdom.

O Lord! we are sensible that our strength, and our power, and our ability is only in you;
and therefore are the souls of your children bowed and subjected to you,
waiting for the renewing of your power,
that as our temptations are renewed from day to day,
you would make known your power in us,
that we may feel the stretching forth of your hand to save your little ones,
out of the hands of the destroyer.

And so, powerful God of Life! break forth more and more in your glory,
and make known your power in expelling the clouds of darkness and ignorance,
and bring the minds and understandings of your people to know you more and more,
till they come to the blessed inheritance, among the saints in light.

Holy and powerful Father! break in upon your people by your Almighty Power,
and scatter the dark clouds of temptation,
and cause the light of life to shine upon them;
you that have commanded the light to shine out of darkness,
do shine into the hearts of the sons and daughters of men; open their hearts,
that they may receive the truth, and make tender their hard hearts,
that they may live to you that made them,
and give it comfortable account to you of their thoughts, words, and actions,
and let them turn to the Lord before it be too late to repent of them.

Powerful God of Life! your mercy and lovingkindness does abound,
to a little remnant that do believe in Christ, and do trust in your name;
you have been with them in their fiery trials and tribulations,
and to this day you have been the glory of our assemblies, and the joy of our meetings.
We are sensible of your holy power working in our souls,
and of your renewing your love upon us: All that desire a full sense thereof,
that are seeking and crying after you for it,
O let them be brought to a due sense of you the living God!
O arise for the help and the comfort of the sorrowful, the sighing and the needy soul:
Pour forth the treasures of your love upon them that follow hard after you,
and breathe for deliverance; that so,
powerful God of Life! praises may arise to you for all your mercies,
and abundant blessings, for your goodness and lovingkindness,
bestowed upon us from time to time.

Most powerful God of Life and Light! let the eye of your
favour be turned upon this land of our nativity;
spare the inhabitants of this city and nation, that they may seek after you;
let them know the weight of your hand upon them,
to bow them down to humility and brokenness of heart;
give them repentance for their sins.

Living God of Life! display your power to all, from the highest to the lowest among us,
and advance the kingdom of our Lord Jesus Christ,
to whom you have given a name above every name;
and let his kingdom and glory be exalted over all, and shine in the midst of us.

Blessed Father of Life! give wisdom to our counsellors, that they may counsel for you;
make known your will, and send help from Heaven to all that stand in need thereof,
and that wait upon you for it; give them your Holy Spirit,
that they may be guided in your way.
Let your Son Jesus Christ have the steering and governing of all things,
and let glory be rendered to your great and worthy name,
and keep us in the love of God and in union with one another;
let the stroke of your power remain upon the hearts
of all whom you have touched at this time;
let them be bowed down always in your holy worship, and remain in a belief of your truth,
and cease to do evil, and learn to do well, and walk acceptably before you,
that so transgression may be finished, and sin and iniquity may be put an end to;
and that truth and righteousness may be set up, and shine among us,
and that our souls may rejoice in you, that we may magnify and praise your power,
and glorify your name; for you are worthy of all honour, praise and glory,
and humble thanksgiving, for the manifestation of your love and power.
All which we desire to offer you through Jesus Christ, who are God over all,
blessed forever and ever.
Amen.
