== Sermon VII. The Inward Preacher; or, The Office of Conscience.

Preached at Grace-Church-Street, June 21, 1692.

My Friends,

Many have been sent among you,
that from living experience have declared their testimony for the truth,
that you might all be brought to wait for the testimony of truth in yourselves.
This is that which will stand you in stead,
to know the testimony of truth in your own hearts to be for you;
therefore you are to wait, especially at such times as these,
to hear the voice of truth in your own souls: For whatever the preacher preaches,
if the truth in your own heart does not speak peace, it is not well with you.
Whatever testimonies are born of the truth itself;
it is the truth that must bear testimony of you, that unerring word,
that gives to everyone an infallible evidence of their peace with God,
or against that which hinders them.

You know our labour has been to persuade all people to hearken to the truth in themselves,
and to make it their business, and travel, and endeavour,
that they might have unity with the truth in their own hearts,
that their consciences may not condemn them.

For such as you, in whom God has raised his witness,
and has exalted the truth for a judge, you are not ignorant,
nor covered over with darkness, as many others are; you do not remain in doubt,
but you know the truth, and have an answer of peace in well-doing,
and a condemnation in evil-doing; not administered to you only by preachers without,
but by the evidence and demonstration of the Spirit of God in your own hearts.
This is that standing mystery which God has raised, which can never be put down again,
but as each one may put it down in themselves.

I grant that men may put it down: You have read, and had it plainly witnessed to you,
even killing the just, and crucifying the Lord of Glory; and of spiritual Sodom,
and Egypt.
These things you have read of, and you that are turned to the light,
know the meaning of those sayings, by woeful experience;
for whenever you have turned aside, from a due subjection to the grace of God,
by which we are convinced, then there has been a piercing,
and crucifying of the Son of God afresh, and vexing and grieving the Holy Spirit,
by which you should be sealed to the day of redemption:
Then there has been anguish and tribulation upon your souls; and if this be minded,
it will plant a fear upon your minds, and make you afraid to do the like again;
but where this tribulation and anguish is neglected and put off,
there a custom of sin takes away the sense of sin.
You know many have had more judgment at some time upon them for a vain word,
or a vain thought,
than afterwards they have come to have for the most abominable wicked action.
How came this to pass?
Was sin ever the better?
Or has it changed its nature?
No; but they are further off from the sense of the evil of it.
This is the word of truth, to which you must stand or fall; this is the stone,
that whoever falls upon it, shall be broken and tendered;
but if they stay till the weight of truth fall upon them, it will grind them to powder.

They will have a life of liberty, let the truth say what it will: I will have my liberty,
and use my tongue as I wish, I will be careless and proud, and envious and malicious,
though I know these things be wrong,
and the witness in my conscience testifies that these things are wicked,
and contrary to the will of God, yet I will have them: Whoever comes to this mind,
the stone is near falling upon them, and they will be ground to powder;
they are like barren earth, which bears thorns and briers, and is rejected,
"`and is near unto cursing, whose end is to be burned.`"

Therefore, friends, I entreat you to hearken to the word of the Lord, it is a holy word,
and an old word; many have professed it: There are many preachers that will cry,
hearken to the word of the Lord in such a chapter, and such a verse.
My testimony this day is, hearken to the word of the Lord: But where shall we find it,
some will say?
I tell you, it is written with the finger of God in your own consciences;
and it is either for you, or against you.
Let your profession among men be what it will,
this Minister of the Covenant has no respect of persons, or regard to profession;
he will not excuse this or that man,
because he makes a greater profession of his name than others;
this rather is his judgment,
and his condemnation shall be more swift and sharp
upon him that makes a profession of Christ`'s name.
"`If judgment begin at the house of God,
what will the end of them be that obey not the gospel of God.`"
Those that take upon them a strict profession, they do greater dishonour to God,
than those that cry out there is no reforming; there can be no living without sin:
These profess what they do, and they do as they profess.
But when people come to profess holiness and righteousness,
and profess a power also by which righteousness is obtained,
but live not strictly according to their profession;
these are they that cause the name of God to be blasphemed among the Heathen,
more than they that say there can be no living without sin.

Now this witness of God has no respect to profession,
but has respect to the state and frame of the mind of a man or woman,
that they serve God with, whether it be with sincerity and uprightness of mind,
and with breathing desires, that they may know the good and acceptable will of God,
and what is well-pleasing in his sight;
and that they might perform that which is according to his heavenly will.
Where this sincerity is, where this cry of the soul is, the Lord has regard to it;
but where people`'s religion is only to bear up a profession,
and hold up an external fellowship and communion one with another;
when this sincerity is lacking, the Lord abhors their worship,
it is an abomination to God, and no benefit or advantage to themselves:
It is not for the glory of God, that they make a profession,
but for some design to themselves, and so they become abominable.

This was the state of Israel of old, and it is the state of a great many now,
that think they do great matters, if they conform so far to the truth,
as that outwardly they may not be charged with a lie,
and that they are of such a society.
It is well if some would come so far as to maintain their society with God`'s people,
and their external profession;
but if they have not regard to the truth in their own consciences,
what is their profession worth?
What will all your unity with them signify?
If there be a breach between God and your own soul, who can heal that breach?
What will the profession signify and amount to at last?
But, "`go you cursed into everlasting fire, prepared for the devil and his angels.`"
And all the reason to be rendered for it, is this; "`depart from me,
you workers of iniquity:`" He did not say in that sentence, you are liars,
you never prophesied in my name, and I never preached in your streets;
but allowing what they said to be truth, that they had made a profession,
and held communion with other Christians, allowing these things,
yet notwithstanding it is, "`go you cursed;`" and the reason of the sentence is,
"`you workers of iniquity.`"

Let the dread of the God of Heaven rest upon you.
My friends, it is another thing to make a profession of the Lord God of Heaven and earth,
than most are aware of; "`let everyone that names the name of Christ,
depart from iniquity.`"
What is iniquity?
It is all things that men or women do to gratify
their own wills contrary to the will of God;
that is iniquity: Where had all men liberty?
Where had Adam and his sons their liberty to fulfill their own wills,
and to contradict the will of God?
Yet nothing is more common in nations, countries and families,
than for people to assume a liberty to perform and fulfill their own wills,
and to bring about their own interest, designs and contrivances,
though at the same time they are convinced that it is contrary to the will of God.
Where this liberty is taken, there iniquity is wrought; that is iniquity that is unjust,
that which is committed against him upon whom we have all
our dependence every moment for life and breath,
for food and raiment, and everything we enjoy;
we have a dependence upon that God that made us,
yet vain men and women assume a liberty of gratifying their own wills,
and setting up for the flesh.

You may remember that passage of the good apostle,
when he saw some libertine professors of Christianity, grow loose and careless;
they thought it was well they did acknowledge God in their meetings and worship,
but as to the affairs of the world,
they had forgotten that God was concerned in those things;
the apostle takes notice of such libertine looseness, "`Go to now, you that say,
today or tomorrow we will go into such a city, and continue there a year,
and buy and sell and get gain; whereas you know not what shall be on the morrow:
For what is your life?
It is even a vapour, that appears for a little while, and then vanishes away:
For that you ought to say, if the Lord will, we shall live and do this or that.`"
You ought to live in subjection to him that made you,
you ought to have regard to God`'s honour in whatever you do: "`Whether you eat or drink,
or whatever you do, do all to the glory of God.`"
Is not this scripture?
Is not this found among the apostle`'s writings?
Do not we hold the name of Christians which was given to them at Antioch?
Yes, we are called Christians, and these writings of the apostle are holy writings,
and what then is the matter that we take so little notice of them?
That men do not apply these wholesome exhortations to the particularities of their conduct,
but that they go from country to country, and from one place to another,
and do what they please,
without having any regard to give their subjection to the great God:
This looseness has brought into the minds of some, such a liberty,
that they live without God in the world; when they go sometimes to religious meetings,
and when they hear the name of God mentioned,
it may be there is a little awe upon their minds,
and they have some regard to that God that gave them breath and being, for the present:
But if there be not religion, if there be not a tie (religion signifies a tie,
a being bound to God) if men be not bound and tied to God,
by that which is made known to them,
everyone will desire that which is good in their own eyes.

Therefore it is necessary for you, my friends, above all people,
you that are come to a measure of the ministration of the Spirit,
to know and to mind what it does speak.
Such a thing I did this morning, and I am reproved for it; such a thing I did well,
and I am justified and warranted in the doing of it:
Thus it is when a thing is well or ill done.
Sometimes some men act two or three days together,
and never bring their actions to the rule; that is,
like a man that is building and never minds his rule, so what he builds up,
tumbles down again upon his head.
You know there is something in you that has a speaking voice, an infallible voice,
and gives judgment on your actions, and passes a sentence,
either of justification or condemnation upon you.
If you would live so as to answer God in what you do, you need not fear answering men.
I do not fear answering men in all I do or speak; if I do but answer my own conscience,
I fear no man, though he be of another persuasion and judgment opposite to me;
if I keep peace in my own conscience,
I shall answer the principle of truth in my adversaries consciences, though they hate me,
and despise me, and seek occasion against me;
if my actions answer the truth of God in my own heart,
they will answer the truth in any man`'s heart: This makes a man as bold as a lion.

When the people of God obtain a reputation, to be true and just, and holy and righteous,
all men will expect holiness and righteousness at their hands.
What if I profess to be one of these people?
If I have not the truth in my own heart,
though I put on this reputation as a cloak to hide my insincerity,
the lack of that truth takes away my courage.
It is truth that has a power in all men in the world,
and it is the power of holiness and righteousness that makes wicked men afraid;
and therefore the apostle argues upon that subject, the magistrate is clothed with power.
What power has he?
The power of justice, and the power of the sword.
What sword has he?
A sword of justice; and he is a terror to evil-doers, but a praise to them that do well.
It is true, if I have done evil, if I meet with a man that is but my equal; if in buying,
and selling, and commerce, I have wronged him, and deceived him,
though he knows not of it, yet I am afraid of him,
I am fearful that he will discover me and find me out: But if I speak the truth,
and do that which is honest in the sight of all men, I shall not fear any man:
There is no nation under Heaven,
but there is a principle of truth to be found among them in the hearts of men.
If I act according to the principle of truth in my own heart,
there is the same principle of truth in all men.
If I walk up to the principle of truth in myself,
I shall likewise walk up to the principle of truth in all men`'s hearts;
if my own heart does not condemn me, all the world cannot condemn me.

If professors were resolved to answer the principles of truth in their own hearts,
and go thorough-stitch in their profession, they might live courageously:
Truth will crown them with victory.
But if they do not live according to the rule and standard of truth,
they are like salt that has lost its savour, which is trodden under the feet of men.
But where all are one in truth, they are gathered into the truth,
and they will live according to it, so far as they are convinced of it.
If you would give them a world,
they will not give away a hair`'s breadth of the truth which they have professed.
When truth thus comes to have dominion, then truth shall overspread the earth,
and the kingdoms of the world shall become the kingdoms of the Lord, and of his Christ,
and righteousness shall rule, and the sceptre of it be swayed over the nations,
and they that rebel against it, shall be broken by it, and they that are found in it,
shall have dominion, and they shall condemn hypocrites and dissemblers.
Now if you would grow up in this dominion, you have an opportunity for it,
because the truth is revealed in your own hearts.

They who undertake to walk in the truth,
merely from what they hear the ministers of truth preach,
laying up in their minds a company of doctrines, notions and tenets,
they will stumble and fall; but they that will hearken to the truth in their own hearts,
and regard the voice of it in all their ways and undertakings;
these have a minister at home with them, they have a chaplain in their own houses;
if there be anything they know not, and if they know not what to do,
they ask the minister of the sanctuary; others will ask their ministers,
but your minister is at home with you:
Where has God appointed any man to rule over your conscience?
No, God has appointed Christ only to rule and govern your conscience,
to be the author of faith, and the finisher of it too:
You that are come to the dispensation of the Spirit of Christ,
keep to the testimony in your own hearts;
then you have fellowship with one another in the truth;
and you have cause to bless God for it,
that God has so opened the hearts of one toward another, that the suffering of one,
is the suffering of all; and the consolation of one, the comfort and rejoicing of all:
But alas! who is in this fellowship?
Only those that are in fellowship with the truth, in their own hearts, and really so:
If a man shall break fellowship with truth in his own heart,
he will make no bones of breaking fellowship with his brethren:
As soon as men break fellowship with truth, they are unruly, heady, troublesome,
and make no matter of splitting and tearing, and rending of fellowship with others.
How comes it to pass that you have done this?
You did not thus while you feared sinning against the witness of God in your own heart.
But when men have once made light of the great minister of the gospel in their own hearts,
it is an easy matter to make light of the rest; if, as Christ says,
they have done so to the green tree, no wonder that they do so to the dry tree:
If they despise me (says Christ) do you think they will love you?

It is most evident in a great many at this day, they dispute against truth,
they have taken a liberty to speak contrary to the truth in their own hearts,
and then they cry down the ministers of it:
Do you think they do so that keep their first tenderness?
When they were convinced, the power of the Lord rested upon them;
when the power of the Lord first wrought upon you, and brought you to yes and no,
and to plain simple language and habit, this was with joy and delight for Christ`'s sake.
They that keep up this tenderness and simplicity of mind, there is no scattering,
nor rending, or tearing among them,
they "`keep the unity of the Spirit in the bond of
peace,`" and they are kept together in one.

Friends, you have an opportunity in your hands, see that you make use of it;
you may bear up, and not be deceived by men, or devils,
if you keep faithful to the principle of truth in your own hearts.
Let whatever reproach and persecution come, here is a standard, a foundation and a rule,
for you to be governed by, every hour of the day; search your hearts,
and try your consciences by it.
As you do this, and keep to the rule of the new creature, of the regeneration,
being changed from a carnal birth to an incorruptible birth.
If you be born of the incorruptible seed, the devil cannot corrupt you,
evil passions cannot corrupt you;
if you keep up that foundation that is incorruptible in itself,
then nothing will corrupt you, nor your ways and manners:
If you will live according to the simplicity of the gospel, you will serve God,
and be examples to others in the life of holiness and righteousness,
and hereby God shall be glorified.
This is that which will shine forth to the whole nation, and give a good report to truth:
But if any that profess the truth, be found false to their profession,
and be found unholy, and deceive and over-reach their neighbour, they lose by it,
and the devil rejoices at it.

Thus we know the life of righteousness is brought forth through the Spirit of truth,
and out-shines all, and will reach God`'s witness in them that are afar off,
and bring them near; and happy and blessed are they that are found in this divine work,
conforming their lives and conducts according to the new creature, peace be upon them,
and upon the whole Israel of God.
There is a minister that abides with you, that goes home with you,
it is his testimony that you must stand or fall by:
If anyone should be a false professor, and be cried up, it he be not sincere,
he has not peace; though he flutter awhile, and make a show,
the worm of guilt gnaws and torments him; such as these have not peace with God,
nor fellowship with the church: Though they seem to be alive, yet they are dead;
as it was with the churches in Asia, they had a name to live, yet they were dead;
though they have an empty name, such a one is a living man or woman,
they are esteemed friends to the church; but though they are commended and cried up,
and have a name to live, yet they are dead;
"`there is a few names in Sardis which have not defiled their garments,
they shall walk with me in white,`" says Christ, "`for they are worthy.`"
"`I know your works, that you have a name that you are alive, but you are dead.`"
See what Christ, the bright Morning-Star, could do: He could look into a meeting,
and see whether few or many had only a name to live, or were really alive;
if they were dead as to sincerity and truth, though they had been among the church,
they would help to break it down, but not to build it up.

You that have this divine life still stirring in you,
and feel the operation that first quickened you to God,
prize this principle of the divine life above all: What is there can rob you of it?
Value not the friendship of the world: Alas! what can it amount to?
Count it as dung in comparison of Christ Jesus; look upon all things with a sound eye:
Peace with God is of that concernment, that you cannot be happy here or hereafter,
without it; the friendship of the world I can be without,
and the customs and fashions of the world I can be without, I can spare these things;
but the favour of God I cannot be without,
and growth in grace and the knowledge of our Lord and Saviour Jesus Christ,
and a sincere profession of the gospel; I cannot be without these things.

My friends, though you do not make a show and flutter in the world, as some others do,
yet your glory is within; they that are living members of this divine body, the glory,
and beauty and brightness of such, appears in the sight of God.
If you grow in grace, you will be a comfort to one another; and as the apostle speaks,
"`you are our epistle written in our hearts, known and read of all men.`"
The Lord preserve and keep you simple, keep you in all sincerity,
in that truth that has wrought in your own hearts,
that you may have acquaintance with your teacher, that he may not be driven into corners;
for you may do it, and stop his mouth, and silence him too.
If you let your perverse will rule, you may slay the just;
but there will come a day of his rising, then down you go.
Whatever men may get by it at present, when truth rises,
when the Just One that was slain has a resurrection in them,
then most certain down they go.
While you have an opportunity in your hands, and an interest in the covenant of life,
walk with God according to the counsel and dictates of his Holy Spirit,
that you may be brought to a heavenly fellowship,
and to partake of the good things that God has prepared for his children.

My friends, pray prize your seasons, let no day slip, for fear you miss a day at last;
wait upon the Lord, and let his fear and a holy awe be always upon your hearts:
Then peace will be upon you, and there will be acceptance of all that you do.
"`Mark the perfect man, and behold the upright,
for the end of that man is peace;`" when he can reflect upon his past life, and say,
I have walked before the Lord with a perfect heart,
and done that which is good and well pleasing in his sight,
and have not turned aside to the right hand or to the left,
but the Standard of Truth has been the guide of all my spiritual and temporal actions.
If truth has been your guide here, then truth shall be your portion hereafter.
If truth guide you in your way, then you shall rejoice with the saints,
and receive an inheritance with the people of God,
and enjoy that glory and felicity which God has prepared for them that love him.

=== His Prayer After Sermon

Everlasting, glorious, eternal God of Life! whose kingdom rules over all;
your kingdom is an everlasting kingdom; a glorious, blessed day has dawned,
wherein you are making yourself known to the sons and daughters of men;
and you have opened an eye in a remnant (which the God of
this world had blinded) to see the glory of this day.
For though we have lived without God in the world, yet you are near to us,
and you have called us to repentance, and inspired our souls with a desire to you,
and to the remembrance of your name:
Praise and everlasting thanksgivings belong unto you,
who are the author of our salvation;
who have reached out your hand and laid hold upon us,
and sought us out when we sought you not,
and have made known your power and love for our redemption and salvation;
and you will make it known more and more to every upright, sincere mind.

O powerful Father of Life! how has your power and goodness
been revealed on our behalf for your own name`'s sake?
You have stood by us in all our trials and exercises,
and we have found you a God near at hand,
and you have brought a remnant to desire nothing so much as the enjoyment of your presence;
you have brought them to be sensible, that without you they can do nothing; therefore,
in all our assemblies and meetings, we desire to be acquainted with your power,
to hear your word which speaks life to our souls, by which we may live.

And dear and powerful Father! the continuation of your goodness among us,
does greatly engage the hearts of your children,
to offer up praises and thanksgivings to you.
You have inclined the minds and hearts of your people to wait upon you,
and have opened their understandings to receive your heavenly truth,
and those rich and heavenly treasures which you offer them,
and have provided a cup of salvation to refresh the poor and needy soul.

O Living God of Life! reach forth your hand,
to support and save those that are breathing after you,
that are sensible of the need of your presence,
and are frequenting the assemblies of your people,
with a hope and desire that they may enjoy a blessing from you.

Living God of Life! touch their hearts with the finger of your power,
let them know that you are ready to open the treasure of your love, and life unto them,
through the Lord Jesus Christ, that their souls may be comforted,
and they may offer up sacrifices of thanksgiving.
And let all your children everywhere, render to your name, through Jesus Christ,
blessing, and honour, and praise; who are God over all, blessed forever and ever.
Amen.

