== Sermon IX. Truth`'s Testimony Against the Power of Sin and Satan.

Preached at Grace-Church-Street, June 3, 1688.

My Friends,

God has made you witnesses of the great work of this day;
the Lord I say has given you eyes to see, and ears to hear,
and hearts to understand the great work of the day; he has called you forth,
that you may be faithful witnesses everyone in your measure
of that which he has brought to pass in your sight,
for he has revealed his power, the eternal power by which the world was made,
he has revealed and manifested that power for the raising up of life,
for the subjecting and bringing under death, and the power of it;
for a great while a testimony that has been born in the nation has been unto death;
he that has the power of death, that is, the devil,
he has had a great many to sound out his power, to declare the continuance of it,
that death must reign, and darkness must continue,
and that the kingdom of the man of sin will never be brought down.

But now in our day, glory to God on high, here is another sound come forth,
the Lord Jehovah has uttered his voice, and who can but prophecy!
The word of prophecy is given of God, and many are raised up to publish it,
and to sound forth the name of the Lord in the extirpation, the ruin and destruction,
that is and shall be brought upon the kingdom of iniquity,
upon the kingdom of the man of sin, and to prophecy and declare in the name of the Lord,
that righteousness shall run down like a stream; this is the gospel,
the glad tidings that we receive from God, and minister unto you, that you might believe,
and that believing you might come to wait upon the Lord,
and behold the accomplishment of it.

For, my friends, herein has consisted all the labour, travel and exercise,
of the servants of the Lord; and for this cause have we suffered many things,
and gone through many trials, because we have steadfastly believed,
and therefore have we spoken it; that the Lord will, by his Almighty power, lay waste,
destroy and bring to an end, that power, that the wicked one, the devil,
has had upon the minds and spirits of the sons and daughters of men,
and that he will set up and establish, in the very same soul, a law of righteousness,
and a law of truth, and will cause the beauty of holiness to shine forth through them,
where iniquity has lodged, where the wicked one has ruled.

Now you that have believed this testimony, you have received it,
as glad tidings unto you, for you are weary of that old service,
you are oppressed under the power of that strange prince.
There was a kind of spirit and power that had ruled over you,
that neither gave you life nor breath, nor had done any good thing,
and yet you were subject; and many there were, who through the grace of God,
came to see that a state and condition of sin and iniquity was not a happy state;
and by a secret kindling of the spark of God`'s love in your souls before you knew him,
there was a cry raised to be delivered, if it be possible.
If there be any deliverance, O why may not I be delivered!
If there be any redemption, why may not I be redeemed!
If there be a power that can set me free from the service of this wicked one,
why may not I be set free?

Ah, friends! remember the days and nights in which these living cries run through you,
then you were poor indeed; then you were humble and broken,
and the Lord beheld you in those days, he saw your state and condition,
he saw how helpless you were, and did not he arise to help you?
Did not a power spring forth in the day of your humility, in the day of tenderness,
by which you became able to make war against the lusts of your own hearts,
and did not you overcome and prevail in your war?
Did not you make a progress by the power and by the
grace that first raised desires in you?
And as you made this progress and gained ground, as I may say, of your own corruptions,
your faith came to be strengthened,
and you were confirmed in the belief and in the obedience of the truth;
and the more you trusted and relied upon him, the more did he manifest his power in you;
he made known his ability and his strength in your weakness,
so that you did become "`living witnesses,`" everyone in your measure,
that there was such a power; and that that power was able not only to save from a little,
or from a few, but was able to save to the uttermost,
to save out of all that was polluted and defiled,
and to cleanse and purify the conscience from all dead works,
and to enable you to serve the living God.

Now the Lord having thus established you, and confirmed you by his power,
that you were found in the faith, and firm in the believing of the truth, my friends,
all the labour, and travel and doctrine, and exercise of the preachers of the gospel,
to those who were converted and confirmed, became very acceptable.
So we preach, and so you believed; here was a unity in our faith,
here grew up a fellowship, a communion in the faith,
and the Lord became glorified in the assemblies not only of those that preached,
but of those that heard, because each one had a place in the body,
and each one had a savour of the word of life by which the body was nourished.

Now, my friends,
that which lies particularly upon me to leave with you for my testimony (and I pray
God that it may be placed in the hearts of all you that have believed) is,
that you may all wait upon the Lord,
to see all that brought to pass which you have believed:
For I take notice by the eye that God has opened in me,
by which he has made me to take care of his flock,
and sometimes put his word in my mouth, that I may speak a word in due season: I say,
by this eye, I take notice of many that have received this precious faith,
and thereby have believed the great and high state; their faith reached so far,
they knew that power to be able to bring them into a perfect dominion over their lusts,
and passions, and corruptions, and over the spirit of the world, over pride, over anger,
over all things that are opposite to the divine life;
their faith is as sound as we can preach it in respect of the extent of it,
but their faith has not reached thus far in its operation upon their hearts;
they have not had the power going on, to accomplish and fulfill that which remains.

Are there not some here and there that are settled in the belief of the truth,
but are got into an ease from the labour of the truth?
But if I be sound in the faith, my understanding is opened;
I do not only believe this matter, but have inward evidence and demonstration,
that I am certain, past all doubt and question of it,
that the Lord reveals his power in them that believe, that purifies them,
and makes them every whit clean;
and here I have a fellowship and communion with them that preach, and them that believe.

But, my friends, all this will not give you communion with God;
though there is communion with the church of God, with respect to men,
who are come into one faith and doctrine, yet for fellowship with God,
it stands in a life beyond all doctrines, and beyond all words and expressions;
therefore your business and mine, and everyone`'s,
is what we undertook when our faces were first turned to God,
that we may be followers of Christ in the regeneration.
For many may be firm in point of doctrine, and yet may not follow Christ Jesus:
Many hold the truth, but do not hold it in righteousness, but unrighteousness.

Now, my friends, have a care, your religion and your souls eternal welfare are concerned.
This doctrine I leave you in charge in the name of the Lord God:
Flatter not yourselves any one of you, because of the soundness of your belief,
but look for soundness of heart, and for a right spirit to be created in you,
a spirit that can no way endure anything that the
light of Christ has made manifest to be evil;
if it be truth you own, then exercise faith upon it,
and whatever sin or temptation assaults you, say,
I shall overcome in the name of the Lord Jehovah; I shall bring you under,
be whatever lust, passion, or corruption you will, in the name of the Lord,
I shall overcome you, and bring you under.

Travel on in the faith committed to you, and you will be more than conquerors;
you will not only grow into external fellowship with
the people of God in the sight of men,
but into fellowship with the church of the first-born, whose names are written in Heaven;
and your communion will not be in words and doctrines, and principles of faith;
but your communion will be with God the Father, and his Son Jesus Christ;
and so in all your meetings together, the joy of the Lord will be your strength,
and the joy of his great salvation your covering,
and he will manifest his gracious presence with you;
and that power which has kept you to this day from your childhood,
and preserved you in all your battles and conflicts with the world,
and strengthened and encouraged you when you went
sometimes sorrowing and mourning night and day,
and fearing lest you should not overcome your adversaries;
that power that has kept you hitherto,
will do greater things for you than you have yet been witnesses of.

Therefore, dear friends, this I would leave with you,
there is nothing will keep you and me in that little
time that remains to us here to spend on earth,
but that which will keep us in the exercise of faith towards God,
and his Son Jesus Christ,
who is "`able to save us to the uttermost:`" Let us wait
to see the power of God for sanctification and holiness;
that will reach as far as saving us from our sins.

This has been the greatest reproach that ever our adversaries have thrown upon us,
that there are some among us that talk of believing in the power of God,
and talk of an ability to overcome their sins, and living a holy life,
and living without sin, while they themselves live in it.
This is the greatest reproach that ever our adversaries have thrown upon us:
Whoever have been the cause of this reproach, God will require it of them,
for the Lord is jealous of his name and glory;
and he will have the praise and honour that is due to his great name,
for working in us "`both to will and to do of his good pleasure,`" says the apostle;
though I know nothing of myself, yet am I not hereby justified.
When you come to that, that you cannot charge yourselves,
then the Lord will not charge you;
but take heed that therein you place not your justification,
hereby you are not justified.

Therefore have an eye to Jesus, "`the author and finisher of our faith.`"
He begins the work of faith, and he will carry it on until he be the finisher of it,
and the justifier of it; he is the Mediator of the New Covenant,
that alone justifies the children of God.
Depend not upon your own holiness and righteousness for justification;
keep your eyes to Jesus the author of your faith, who will be also the finisher of it;
keep your hearts with all diligence, and walk humbly with God,
watching lest your adversary that you have overcome, prevail against you.
By going from the power, there is no safety for the flock,
but only while they keep in the shepherd`'s fold;
be faithful and keep yourselves in the love of God, and he will be present with you,
and keep you to be his witnesses to the end of your days,
and will raise up another generation to be witnesses to his power,
when he has taken you to himself.

To that mighty power of God I commit you,
for preserving you in humility of mind and soul; and my prayer for you shall be,
that you may go on, and make a progress in the good ways of the Lord,
until his work be finished in you.

=== His Prayer After Sermon

Holy and powerful God of Life! who are the Creator of us all; in whom we live, and move,
and have our being; you have made us all for the purpose of your praise and glory,
that we might serve you in the land of the living, among the sons and daughters of men;
and not only so, but you have given us your Holy Spirit, as you did to the people of old.

O living God of Life! you have ordained a remnant to give up themselves to be led by it;
you regard them, and are with them, and they enjoy from time to time your holy presence,
which makes glad their souls; and they have fellowship and communion with you,
and your Son, through your Spirit,
by which they are quickened to offer up pure and living praises upon your altar.

O living God of Love and Life! you have shed abroad your love upon their hearts,
by which they are enabled to pray for enemies, that they may come to enjoy salvation,
and the pleasures which are at your right hand,
which are infinitely better than all the pleasures of this vain world.

Holy and powerful Father! have respect to all our souls,
and touch all our hearts with a sense of your divine love,
that we may feel the cords of your love drawing our souls nearer to yourself,
and assuring us that you have a gracious purpose to save us.

O powerful God of Life! show forth your power,
that our hearts may be touched and quickened thereby, to come to fear you,
and reverence your name, and be acquainted with your operation in our own hearts,
that they may be humbled and broken before you,
and bow down and worship in sincerity and uprightness:
That so holy God of Life! if it be your pleasure,
none may depart out of this assembly without some sense of your love,
and feeling of the powerful drawings of your grace,
and without being raised up to purity of heart,
and convinced of the evil of everything that is contrary to you,
and serve you in holiness and righteousness, and pursue it with all their hearts,
and minds, and soul, and strength, that you may have mercy upon them,
and pardon their iniquity, and love them freely,
for so you have ordained in your Son Jesus Christ,
that we may receive remission of sins through the belief of your everlasting truth.

And holy, powerful,
God of Life! that all your people may partake of holiness and sobriety,
to the praise of your name,
and that they may all come to obtain a victory over all
those spiritual enemies that war against their souls,
that your holy work of redemption and regeneration may be carried on,
to the praise of your grace, and the exaltation of your holy name, to whom praise,
honour, and wisdom belong, and pure and humble thanksgivings; and unto you,
the living God of Life, we desire to offer up our praises and adorations,
for you alone are worthy; who are God over all, blessed forever and ever.
Amen.

