[short="Bearing the Cross of Christ."]
== Sermon X. Bearing the Cross of Christ, the True Mark of a Christian.

[.signed-section-context-open]
Preached at Devonshire-House, October 12, 1690.

He that knows the day of the Lord, and the stretching forth of his arm,
is quickened to feel the power that is in Christ Jesus, the Head of the Church;
that so he may be enabled, through his power, to bring forth fruit unto God.
The eye of the Lord is upon you all, and he expects at the hand of everyone,
that they bring forth fruit unto God,
that according to the aboundings of his mercy towards you,
and of his patience and long-suffering concerning you,
there might at last be an answer in the soul of everyone,
unto the mercy and goodness of God.
They that do not know and experience this,
that the long-suffering and patience of God leads unto repentance,
they know no part of Christianity; let them make their profession ever so high,
and proclaim their notions ever so loud,
they that know not the work of repentance in their hearts, as yet,
need to learn the first principle of the Christian religion.
You know it has been the custom of people to learn their children principles,
and they that have learned their principles, they go for Christians,
whether they repent or no; though they go on in sin and iniquity all their days,
yet they go under the reputation of Christians;
and it is high time to examine and find out (if you can) a reason for this,
that a man shall be accounted a Christian upon any other terms now in this age,
than the Lord Christ did preach and publish in the days of his flesh;
for he did absolutely deny that any man could be his disciple,
without taking up a daily cross, and without self-denial:
Now how should a man at this day be a Christian, or a disciple of Christ,
without taking up a daily cross, and without self-denial?

It may be some will tell you, that they are baptized into the Christian faith,
and have been taught, and have made a profession of Christian principles,
and associated themselves among those that make profession of Christ;
but here is not a word of a daily cross in all this, nor of self-denial;
so that they would have you to understand in this,
that the terms of Christianity are changed,
and that men may be Christians without the terms of Christ, or at least reputed so.

And this has been occasioned by the great apostasy that
has been brought into the church by a long night of darkness,
and the revealing of Antichrist.
Antichrist has been discovered and revealed, and has set up, in despite of Christianity,
a false Christianity; and there came in the terms of a man`'s being accepted,
and being reputed a Christian upon Antichrist`'s terms:
And if you will conform to do thus, and say so,
you shall be admitted into the Christian Society.
Now all these terms of Antichrist,
have been such things as an unregenerate man could conform to and comply with.

And the opening of this door,
has let into the church abundance of hypocrites and evil-doers,
who were in too unregenerate a state to conform to those things that were required;
for in the public society of Christians, it was not said, you must be regenerate,
and take up a daily cross, and deny yourselves, and walk as becomes saints,
and so behave yourselves that God may be glorified,
and the profession of Christianity honoured by you.
Those were the terms of old; but there are other terms of being Christians,
which are of a later date.

Now this apostasy has prevailed and spread over whole nations and countries, not a few,
so that whole kingdoms have become Christians upon these latter terms,
and God is greatly dishonoured among us, and Christ the Holy One most horribly profaned.
It is not so common among Heathens and infidels,
to find people wronging and deceiving one another,
and killing and destroying one another;
and yet it is the practice of many that are called Christians:
These are the fruits and effects of those latter times of Christianity.
Now seeing it is thus, which no mortal man can deny, I have this question to ask,
and I desire that you would seriously weigh it in your hearts and souls,
both while you are together, and when you are separate one from another,
whether it is not high time for all of us to return again to the first terms of Christianity,
and to reckon no man a Christian, let him profess what he will,
saving such a one as does know and witness, that the long-suffering, and patience,
and goodness of God, does lead him to repentance;
and saving such a one as has so much faith towards God,
that for love to God he will deny himself, and take up his cross,
and be a follower of Jesus in that way and life he lived in.

It is high time for all of us to return again to the terms of Christianity,
that were set up by a higher authority than ever Antichrist had,
and before Antichrist was revealed;
for though it is true that Antichrist has obtained power on earth,
to establish his sort of Christianity, that is, without the cross,
and a sort of religion whereby they indulge themselves
in whatever pleases their carnal hearts,
and corrupt minds; yet Antichrist has not all power, he is not Almighty;
I hope neither Antichrist, nor the beast, nor the dragon, nor the false prophet,
nor the harlot, have all power on earth, though they have a great deal,
and by that power they have established laws, decrees, canons,
and innumerable things about religion; and some cry, this is the way you must walk in;
others cry, the way to Heaven lies here, and here you must travel if you will come there:
Some cry, this is truth; others say, it is error: So that the world is divided;
Antichrist`'s government in the world is divided;
and when the house is "`divided against itself,`"
there is hopes that it will fall at last.

But there is one, to whom all power in Heaven and Earth is given and committed;
and his Christians are not divided among themselves, but they are of one heart,
and of one mind; and he that has all power in Heaven and Earth committed to him,
can crush and bruise that power that others have.
Herod had some, and Pilate had some but says Christ, your power is limited,
"`this is your hour,
and the power of darkness;`" and "`you could have no power,`" says Christ to Pilate,
"`were it not given you from above;`" here is power given to the dragon,
to the false prophet and the beast, to speak great things;
but this power of Antichrist is going away;
Christ Jesus was sent into the world in his day, to bring people back again to God,
and to primitive Christianity and obedience, and to the terms of society and communion,
and to a fellowship in Christ Jesus through the Holy Spirit.

Now if we had set up a way of religion, as others have done,
which is contained in some canons, articles, doctrines,
and such and such commandments of men; and if men will confess these articles,
and observe these canons, they shall be of our society;
then we should have done like the rest of the fallen Christians;
but we have declared from the beginning, that professing our doctrine,
and the principles of religion, does not give any man fellowship and communion with us;
but our communion is in the self-denying life, and a daily cross,
in opposition to sensual lust, vanity, pride and bitterness of spirit, corruption,
enmity and wrath;
this has brought us to a holy fellowship and communion in the Holy Spirit,
and to a unity from one head, which is Jesus Christ;
so that there is not this man`'s church,
and the other man`'s church among the people of God.

Do you read in the primitive times, that Paul had his church, and Peter his church,
and James his church, and Jude his church?
Indeed they had their meetings as we have now,
in many cities and countries among the Jews and Gentiles;
but these holy apostles that were the first publishers of the everlasting gospel,
after their great Lord and Master, Jesus Christ,
they never did appropriate any church to themselves, that was not their business;
but our work and business, says the apostle, is to gather you to Christ,
and "`present you as a chaste virgin to Christ;`" our work is,
to turn you from darkness to light, that you may walk in it, and be the children of it;
our work is, to build you up as a spiritual house,
to be presented to Christ the Mediator.

This is primitive Christianity that has its foundation in holiness and righteousness,
sincerity and truth, not in words, and terms, and articles, and canons, and decrees,
and other observances; this is not the foundation of true Christianity,
nor will it ever be, the devil`'s kingdom must be destroyed, it is shaking,
for he in whom we believe, has power from his Father to break the devil`'s head,
Antichrist and the dragon`'s head.
Christ Jesus is signified by several names, the second Adam, Lord from Heaven, the Way,
the Truth, and the Life, but he is the same Christ;
so Antichrist is expressed by several terms and names,
but he is the same power of darkness, he has made the nations drunk,
to stagger and destroy, and devour one another.

This has been done in the fallen state of Christians,
and the design which the Lord Christ has in sending
his ministers and workmen to labour among you,
is to restore men to the first Christianity, and to bring men to God;
that religion is not made up of doctrines, articles, canons and decrees of men,
but it has the word of God for its foundation; "`he that has an ear to hear,
let him hear:`" There is some spirit, and power, and visible work in a true Christian,
which the false Christian never had.
The false Christians have taken the name and profession of Christ,
and their fruits have been dishonourable to him;
they might as well make profession of Antichrist and Satan,
they have a form of godliness, they have some of the word, but they deny the power.
What is their religion and outward profession, when they lack the internal life,
and the motions of the Holy Spirit; if they bring forth the cursed fruits of the flesh,
enmity, wrath, lust and corruption,
which belong to the fallen nature and unregenerate state?

The apostle takes notice of this deceit and hypocrisy in religion,
which was growing up before he died; men "`having a form of godliness,
and denying the power thereof, from such turn away.`"
If there be any brethren that walk disorderly, have no company or fellowship with them,
if you would have the holy name of Jesus free from scandal.

This has been the design of all the faithful ministers of Christ,
to keep their holy profession of the name of Christ free from reproach;
that the holiness of God`'s ways might be seen in
the holy lives of the professors of them.
Till men come to know this, and take up their daily cross, and exercise self-denial,
their Christianity is good for nothing; I would not have you trust in it;
neither in articles, tenets, or observations;
but see how with your lives you answer your profession: Christ was "`holy, harmless,
undefiled, separate from sinners.`"
And why should not Christians be so too?
How can Christians be followers of Christ, and not separate from sinners?
Christ was so.
He went one way, and sinners went another; they followed their sins and lusts,
but he followed the work his heavenly father sent him.
If you are a follower of Christ, you are worthy of the name of a Christian.
Do drunkards and swearers follow Christ?
Do the careless and proud follow him?
Do the unclean and hypocrites follow him?
you know they do not why do you call them Christians?
This is a reproach and shame to the holy name of Jesus, and to true Christianity,
that any of these folks should be called Christians, but such as are followers of Christ,
who are "`holy, harmless and undefiled, and separate from sinners.`"

This seems a strange kind of doctrine, yet if it had been preached in the primitive time,
there were people that would have received it as apostolical doctrine,
that a man should crucify the flesh with the affections and lusts: For says the apostle,
"`mortify your members which are on earth; if through the spirit,
you do mortify the deeds of the body, you shall live; but if you live after the flesh,
you shall die.
And to be carnally minded is death, but to be spiritually minded is life and peace.`"
This was sound doctrine then.

Now come and tell a man he shall certainly perish
and come to damnation for all his profession,
if he does not mortify the deeds of the flesh; if he lives in sin and dies in it,
he is like to perish: How many have been hauled to jails and dungeons,
only for preaching this doctrine, and when we were first sent to preach,
we dared not do otherwise?
And God did not send us to preach till he had washed us, and sanctified us,
and fitted us for the work of the ministry.
Now when we saw in the holy scriptures, that God did work upon others by his Spirit,
before he sent them to preach the gospel,
was not here sufficient authority given to preach the downfall of sin,
and destruction of it?
One would think that such a one, thus called and sent of God,
had as good authority to preach the everlasting gospel,
as the laws enacted by all the princes of the world could give him;
a man sure that has an authority for preaching the gospel,
would not need to wait for orders and approbation; he would not stay for an induction.
The apostle Paul took it for a commission that was creditable,
when he tells you of his mission, it was "`not by man,
but by the will of God,`" that he was called to preach the gospel.
If we should say we were made preachers, if you ask by whom,
not any man in the world can tell you; but we were made preachers many years ago:
Not by man, or by the authority of man, but by the will of God.
What was your commission?
to turn men from darkness (that darkness we had formerly
lived in) "`to turn them from darkness unto light,
and from the power of Satan unto God`". The apostle
sums up his commission in a few words;
the Lord told me I must turn men from darkness to light.
This is our commission that we have received from God in this age,
to turn men from darkness.

But some will say,
that we have not human learning and qualifications for the work of the ministry:
To this I answer, if I heard a man swear or tell a lie,
I could tell him that this was not of God, I have learning enough to know,
and tell men that, and say, whoring, drunkenness, and swearing, and lying,
were works of the flesh, and fruits of the devil`'s power;
I would have you turn from these works to the power of God.
What is that power of God?
I will tell you, it is a manifestation of grace in your hearts,
that will draw you away from the love of all these things; the grace of God,
is the power of God to salvation to them that believe: "`To as many as received Christ,
to them he gave power to become the sons of God; to such as believed in his name.`"
Such Christians will show forth the power and life of religion in their conducts:
So that here is a sufficient authority, not a lack of authority.

I have been sometimes examined by what authority do you preach?
By the highest authority in Heaven and earth, by the authority of God that came by Christ,
the Redeemer.
What do you preach?
Truth in the inward parts, grace and truth, and against all filthiness of flesh and spirit.

As long as Antichrist has a rule, you must not preach down sin without authority;
you must have power, you must be ordained,
and have an induction before you undertake to preach the gospel,
and preach down sin and wickedness: The devil has got such power and rule,
that some tell us, that no man can live without sin;
if it please God here and there to raise a man and
bring him to a holy and righteous life,
this man needs a patent, a commission, an induction,
an ordinance to preach and cry down sin in other folks;
what commission had the Psalmist when he said, "`Come, all you that fear the Lord,
and I will tell you what he has done for my soul.`"

Is it not high time for people that have evidences of the
love of God shed abroad upon their hearts by the Holy Spirit,
to bear their testimony against sin and wickedness?
Is it not high time for everyone`'s mouth to be open,
to testify against such a horrible mist of darkness that is over men;
to testify against hypocrisy, uncleanness, and unrighteousness?

It was the great design of the primitive preachers of the gospel,
to cry down that which some ministers cry up,
so that Christianity is not like what it was,
for then they told them that there was no happiness
but by breaking off from sin by repentance.
No possibility of salvation without confessing and forsaking sin,
and trusting in the mercy of God through Christ for the pardon of it.
Tell them of the mercy of God, and the blood of Christ,
they will tell you that they cannot be cleansed from all sin,
they cannot live without sin.
How comes it to pass that there are ministers that
preach an impossibility of living without sin,
when we assured in the holy scriptures,
that "`without holiness no man shall ever see the Lord?`"
And that "`there shall by no means enter into the kingdom of God, anything that defiles,
or causes an abomination, or a lie?`" Rev. 21:27.
How comes this,
that ministers preach an impossibility of living without sin?
Will any of you, says he, be so presumptuous as to say a man may live without sin?
I will prove it from good authority, both from scripture and the fathers,
that no man in the world can do it.

If any set themselves to it in their own strength, the devil will make fools of them;
some indeed have gone about it in their own power and will,
and have cloistered themselves up in monasteries,
and shut themselves up between two walls, that they might be separated from all society,
and live without sin; they would do it in their own power,
and the devil is stronger than they.

Let me tell you, men of the greatest wisdom, courage and strength,
of the most excellent natural parts that any man can have,
are not able to grapple with their enemy the devil by their own power;
there are seeds of sin, and lust, and concupiscence sown in all their hearts;
so far this is right and sound doctrine,
that no man can do anything in his own power and strength.
But here is the mistake; a man has been a long time wrestling with his sins and lusts,
to get the victory over them;
but by woeful experience he finds his weakness and insufficiency;
he is sunk in his harness, and so has given over the battle, saying,
I shall never overcome the devil and his temptations,
my sins and lusts are too hard for me,
I despair of ever overcoming them in my own strength, by all that I can do;
that is true enough, but must you perish because you can never overcome your corruptions?
If ever I be saved, it must be the free grace of God, that must save me.
How can you come to lay hold of the free grace of God?
I am told I must lay hold on Christ by faith, who is the Mediator between God and man,
and is my only Redeemer; there is no salvation in any other: This is very well;
now you are a believer, what do you expect, what do you hope that Christ will give you?
He will not give me power over my corruptions, so as to live without sin,
that is more than I hope for; but I expect that Christ will reveal his power in me,
and give me so much strength and power against my lusts and corruptions,
that they may not have dominion over me:
Now if you tell me that you hope for strength and power from Christ against sin,
Satan and corruption, do you now tell me that it is still impossible?
It was impossible before indeed to live without sin,
when you did trust in your own strength; but now,
when you come to have grace and assistance from the Lord Jesus Christ, the Son of God,
and Saviour of the world, that gives you ability to withstand temptation,
and overcome your corruptions, and the lusts of your own heart,
is it impossible still to live without sin?
Then you may say, the devil`'s slave I am and must be;
for there is no other power in Heaven or earth for you to lay hold of, if your own power,
nor Christ`'s power neither can do; then you do say, that the devil is Almighty.
Thus they tell us, when Christ has revealed his power, it is impossible still.

If I should call this antichristian doctrine, I could make it out.
Blessed be God,
I do believe that Christ is able to preserve me from the devil`'s temptations,
and all his instruments, if I believe; though I could not do it in my own power,
yet by Christ`'s power I may be preserved an hour without sin: If so, then a day,
and if one day, then a thousand days, if I live so long;
Christ has promised that he will bruise Satan, and tread him under feet,
and destroy his works, and judge you whether sin be not the devil`'s work;
shall I despond, or despair to have the devil`'s work destroyed in me?

Here is ground for you all to believe,
he that has faith may lay hold of this power which is offered of God;
therefore lay hold of it, else your religion will be good for nothing.
This is the enjoyment of a true believer,
that he receives power from Christ to deny himself;
therefore all their pretended Christianity and professions at the day of judgment,
will melt away like snow.
These canons, articles, forms, liturgies,
these will melt away when the day of the Lord comes to burn upon them;
none but they that feel the redeeming virtues of the blood of Christ,
that have their souls filled with the love of God;
and they that will part with whatever they love in the world, for Christ`'s sake,
shall be accepted.

I am not for setting up this and the other sect or opinion;
if it be among those of my own profession, if they profess holiness,
and bring forth unrighteousness, it is all one; I shall not value their profession.
There are many in this city and nation,
that have sheltered themselves under the profession of truth, and talk of perfection,
and have brought their lusts and imperfections with them:
Here Antichrist is trying another game to bring them
under a profession that will serve his turn;
the devil will allow men profession,
if they will live according to their own hearts`' lusts,
so that they may save his head from the blow that God`'s power will bring upon it,
so that they may dishonor the holy name and religion they make profession of;
thus says the apostle, "`I have told you often,
and now tell you weeping;`" they were Christians, so called, to whom he spoke,
but "`they were enemies to the cross of Christ,`" not to the profession of Christ;
he did not say they were strangers to the cross of Christ, but enemies to it;
they let it fall, they kept the name, word and doctrine up, but they let the cross fall;
how much were these Christians worth?
surely but a little.

Indeed, Antichrist has been so silly, that because the words are so put upon the cross,
no being disciples of Christ without the cross,
and the words of scripture are so put upon it; thus thinks Antichrist,
I shall never persuade the people to be at ease, unless I give them a cross;
therefore he sets them a making crosses.
They must be baptized with the cross; they say we deny not the cross of Christ,
we hang it about our necks, we set it up in our meetings and academies, and many princes,
and wise men, and learned men, have been so bewitched and drunk with delusions,
that they have called this the Christ which they have made with their own hands;
they have made Christs, and prayed to them;
and all their religion has been putting together crosses, crucifixes,
forms and liturgies, which they have made with their own hands.

Here is Christianity in an empty profession, but where is the soul of it?
I would inquire for the life of it,
I would see Christianity living in love to God above all,
and loving our neighbours as ourselves.
When this Christianity comes, there will be no killing one another,
nor persecuting one another, nor fulfilling the lusts of the flesh,
nor pleading for it neither.

Blessed be God, that our eyes have seen the witnesses raised,
and life from Heaven come into them; and now religion begins to have a life and soul,
and shows itself in a little remnant:
There is a people raised by God that feel life in their worship, in their families,
in their conducts, and in their behaviour towards relations,
they do what they do as to God.
Many lads and lasses, men-servants and women-servants, they do their work and service,
not only to please their master and mistress, but to please God.
The life they live is by the faith of the Son of God;
they live as becomes the members of his body.
Husbands love their wives, not simply because they are their wives,
as the men of the world do, but they do it upon the account of inward religion,
and of the divine fellowship and communion they have in Christ Jesus.
Husbands should love their wives as Christ loved his church,
and laid down his life for it; so a man should love his wife, and be tender over her,
and minister to her.

The life of Christianity has taught us to behave ourselves so as God may have glory,
and Christianity be restored to its ancient lustre
and beauty that it had in former times.

But some will say, do as well as you can, men will never love you;
if you have the soul of Christianity, you shall be reviled and scandalized.
Men will make works against you, and strew papers against you,
and set the magistrates against you; live as well as you can,
they will follow you and disturb you.

This is more than you know.
If a man once comes to feel the life of Christianity working in him,
and the power of it keeping him from doing evil, and wishing evil to his enemies,
and disposing his mind to a frame of praying for them, inclining him to pity them;
if a man comes to this state, he is at peace in himself, and enjoys tranquillity of mind;
he looks up to the Mediator, Christ Jesus, and feels an answer of peace in his own soul,
and is come to rest in himself.

Now concerning persecution, hatred and enmity,
between the woman`'s seed and the serpentine seed, and how long it will last.
God whom we serve, did say to the devil in Paradise,
"`I will put enmity between you and the woman, and between your seed and her seed;
it shall bruise your head, and you shall bruise his heel.`"
So that it is not to be expected,
that the seed of the serpent (those that are born of that
seed) can love those that are born of the woman`'s seed.
It is possible, that those that are born of the seed of the serpent,
should be translated and brought out of that corrupt state;
but it is impossible that those that are born of the flesh,
should love those that are born of the spirit,
while they continue in their unregenerate state, but persecute them.
It is like a natural instinct, as for water to run downward, and fire to fly upward.
Were not all men and women born children of wrath,
and naturally enemies in their minds to Christ Jesus?
And did he not die and suffer for them all?
So that the very nature of the thing is the very reason why Christ
died to redeem those that were his enemies to be his friends.

Suppose I, or any other to be a member of Christ, and men do persecute me, and revile me,
and hate me, should I not love them, and do good unto them,
when I see one infinitely better than either you or I, do it for us?
when we were enemies, Christ has sent his Spirit into our hearts,
that we might become friends of him, and of him that sent him:
This is the effect of the righteousness of Christ, and of his innocence,
that enemies may become friends; thus have many been brought to a friendship of truth,
that were enemies to it;
if we could not suffer for the testimony we have received of God, what were it worth?
But seeing God has not only given us to believe, but to suffer for his name,
many have been turned by this means from darkness to light, and many more will;
the light breaks forth quickly, notwithstanding there has been so much ado to stop it.

It has been the design of many learned men of this nation,
how shall we stop these men`'s mouths that preach
the doctrine of truth in the inward parts,
the light within, and Christ within them?
I will not repeat the many laws that have been made
against them that will not preach lies,
but the power of Christ and his truth; now what will you do?
You cannot lay hand on them as you used to do; no,
but we will reproach them with the tongue, we will render them odious to the government,
as persons that will overturn church and state, and that preach false doctrine;
and when all is done, and they have said their worst,
people will still believe that sin and wickedness is hateful to God,
that God takes no delight in sin, and that the devil will lead us to sin;
he that keeps most from sin, keeps most out of the devil`'s clutches;
and he that lives most holy, is most like to God.

These things we will preach, and we will go on in this testimony,
that the best way that man can take, is to break off their sin by repentance,
and turn to God, their Maker, with their whole hearts, and they will look to their ways,
and search, and try and examine their hearts, and if they see evil, to keep out of it;
this is such a thing, as there is no withstanding of it, it will go through this nation,
and all the nations of the earth.

What if a company of people should combine together, and say,
we will not have the sun to shine upon the city of London; what course must we take?
When the sun is down, we will build a bank or high wall to intercept its light;
but notwithstanding all their endeavours, when the sun rises,
it will get over their high banks and wall; so all their designs,
and all the contrivances against the light of the gospel,
and against Christ the Son of righteousness, and against the Spirit of Christ,
the light will ascend and get over the heads of them all, and it will confound them,
and break through all opposition.

I exhort you all, my friends, that laying aside all doctrines, and tenets,
and contrivances among Christians, as come to this simple thesis and position;
it is no matter what I profess of religion, if my life is not answerable to it,
if there be not a love to God, and my neighbour, and to my own soul;
there is no life nor power in my profession of religion.
I will rest satisfied in the measure of knowledge that God has given me;
I must not do to my neighbour what I would not have my neighbour do to me;
I must be upright and sincere towards God; God will not accept of any worship from me,
when I am unclean in body and in mind too; we must see that we be purified,
for God will not accept of an offering from an unclean heart;
you cannot bring a clean thing out of an unclean, says our Lord Jesus Christ,
the great preacher of truth and righteousness; I must first make the tree good,
before the fruit will be so; you and I are these trees;
till we have something good in ourselves, we cannot bring forth good fruit.

Therefore you must have respect to the principle of sanctification in your own hearts,
and turn to what you may feel an experience of in yourselves,
some principle of grace and light in your hearts,
that can distinguish between good thoughts and evil thoughts.
Is this good for me to do?
I will go on in it with faith and courage; but if it be evil, I will not touch it,
though there be profit and pleasure to allure and draw me to it; I will not touch it,
though I might gain the world by it.

Here is Christianity with life and soul in it;
we have been scandalized as if we preached up error for justification:
We say there is no justification without sanctification; so you that know the power,
live in it; and you that desire to know, turn your minds to the light and grace of God,
and you will feel the power that will oppose sin in its motion,
and it will never trouble you in its act and workings.
If I would not do ill to my neighbour, and I judge such a motion when it is suggested,
it will never trouble my conscience, because when the devil moved me to it,
I rejected it, I would not follow him.
It is no sin to be tempted; for our Saviour, that was perfectly holy,
and free from all sin, was yet tempted; he had motions in his mind,
but he withstood them, and resisted the devil in all his temptations;
Christ was tempted that he might be able to succour us when we are tempted;
and he will do it for all those that wait for him.

Therefore, friends, trust in the name of the Lord,
and you shall feel the stirrings of that power,
that "`has called you out of darkness into the marvellous
light`" of the sun of righteousness wherein you live,
and which will shine to his immortal glory and praise,
and the everlasting comfort of your immortal souls.
