== Sermon XI. The Spirit of Christ the Only True Guide.

Preached at Grace-Church-Street, October 10, 1690.

You that are met together in the name of the Lord, and have your expectation from God,
and are really waiting to receive a blessing from his bountiful hand;
you are they to whom the Lord will communicate the good things of his kingdom,
and instruct you in the divine knowledge which the wisdom of this world cannot find out;
you shall have your portion in the blessings prepared for you,
and laid up in Christ for you,
to be handed forth to you from day to day for your support.
And hereby you have been preserved and kept alive unto this day.
You have received your nourishment, and divine and spiritual refreshment,
always in the presence of God;
when you have been out of his presence you have met with troubles,
and darkness has gendered upon your minds, and veiled and clouded your understandings,
that you have been sometimes in danger to lose your way,
until you have returned again unto the great shepherd overseer of your souls,
by whom you have had access to God.
You that have had these experiences,
O let your hearts and souls be engaged to continue together in one heart and one mind,
serving the Lord and waiting upon him for something that may do you good;
that may strengthen and confirm you in the blessed truth.

For there are a great many that are convinced, that do yet lack establishment:
There are a great many that know the truth, yet cannot be brought to abide in it,
but are sometimes drawn out of it, and then they meet with trouble in their minds,
and distress and anguish lay hold upon them,
and they do not enjoy that tranquillity and peace,
and that inward joy which they believe others do enjoy at the same time;
and which they might have enjoyed if they had abode steadfast in the truth.
Now what is it that will establish such a one,
but their waiting upon God to receive power from him to resist the temptations,
and the manifold wiles and snares of their soul`'s enemy,
whereby they are daily in danger to be drawn away from God; drawn out of the way?

You know, friends, how the Lord brought us into this exercise of waiting upon him,
by making us sensible that there was none could help us but him.
Teachers we have always had, and men that have spoken of God, spoken of his power,
and spoken of his wisdom; but how to dwell in that power, and stand established in it,
so as at all times to resist the power of the wicked one, is what no man can help us to;
and upon this account it was, that the Lord`'s people were eager to cleave close to him,
and by faith to have their dependence upon him; and cry in their souls, Lord,
unless you establish me, I shall never be established.

The confirming power that stays and settles their minds upon the Lord, it comes from him,
it is handed to us through the Lord Jesus Christ, whom we have believed in;
they that kept their faith in him have had longings and breathings of soul,
that they might receive some divine blessings by him, and through him.
So that they that meet together in this mind, they find a settlement in the truth,
as it is manifested and revealed in them,
and goes down into the deep where unity is known, where they are of one mind,
and the soul is made capable of putting forth strong cries to God,
and living breathings and prayers to God, that he will teach them how they shall profit,
how they shall grow, how they shall serve him, and honour him in their day;
that he will reveal his power in them,
to expel any darkness or veil that has been gathered upon their minds,
that does hinder them from beholding so much glory and excellency in the truth,
and in the ways of God, as some they have beheld.
And so these are travellers that are travelling with the Lord in faith,
to receive a blessing at his hands.
Their minds are not left to this, or that, or the other man,
or to mere words or visible things;
but they feel the word of truth answering the truth in themselves;
and they receive a comfort and benefit, because they find a blessing to arise in them.
These words reach my soul; these administer help to me, and I am comforted in them,
because I find those works working in me, or wrought in me.

For, alas! my friends, many of you know, that there are some who hear the word,
and the declarations in the word are but sounds unto those who
have no experience of the work that is signified by the word;
many such people do hear the lovely sound,
and they are affected many times to hear talk of the work of regeneration,
and of the enjoyments of God`'s people,
and how they are borne up in all their trials by an inward and divine power,
and how they are always kept alive to God, and preserved in his living presence;
but this does not bear them up in a time of trial; but if a trial or an affliction comes,
they sink under it, and they are filled with anguish and perplexity;
so that the word barely heard spoken, and not rooted in the mind,
does not minister to the work;
the words spoken do not carry that kind of operation upon
them as to witness an inward work wrought upon them.

But where there is an effectual work and operation in the soul,
it continues in its labour and travel from death to life.
And as those heavenly things, those divine operations of God`'s power are spoken of,
there is an amen in your souls, saying as far as you have travelled,
thus has God dealt with me,
he has indeed by his power carried some beyond my state and condition,
and my faith is hereby strengthened, and my hope is confirmed.
He that has begun a good work so gloriously in my soul, will carry on his own work,
and bring me to higher attainments,
and further experiences that some of his servants bear witness of.

So that now being exercised, the work goes on,
and the pleasure of the Lord prospers in Christians,
that when they meet together in the name of the Lord,
they know for themselves that the Lord is present with them,
they know what the word of the Lord is unto them;
if they hear the word preached to another state and condition,
yet they abide in and keep that which makes manifest to them in their own state:
And this permits not the soul to be carried away with the word,
and sight and vision of a higher state than their faith can witness to;
and they keep low, and humble and tender, and have a care of their own souls;
as the apostle when he was come to glorious and high attainments in the work of the Lord,
yet he would not glory of anything, but what the grace of God wrought in him:
We do not boast of things that are not wrought in us.

It is possible for the creature to gather in, and comprehend the form of things,
that they have not the work of in them;
and a great many have done so to their great damage, and some, it is to be feared,
to their utter ruin.
They have comprehended high things, and the notions of great attainments;
they have heard them declared and spoken of thus,
and so some have in their speculations declared to
others their conceptions about those things,
yet those things were never wrought in them; they could preach of humiliation,
when the root of pride was not removed; they could preach of regeneration,
and the old man not put off, and the new man created in righteousness not put on.
All this kind of preaching has been in the world, and is still too much in the world,
but it has not produced and brought forth any profit and advantage to the soul,
either to preacher or hearer;
for it has not been accompanied with a divine and heavenly blessing;
but the true ministry ordained of God brings forth
a work of holiness and righteousness in the soul.

And therefore everyone that God has thus reached, and has opened your understandings,
and has made you capable of comprehending and understanding divine things,
take heed lest by the subtlety of Satan, and the wiles of your great enemy,
you be at any time lifted up, and exalted in your minds,
in the notion of the things that you have not attained;
not that you should not so understand the things of God that God opens to you,
as they are many times opened to the creature,
before the work of them is in the heart of the creature: And why so?
why are they opened to me?
It is for your encouragement, that if you do hold on,
and be steadfast in waiting upon the Lord, these things God has in store for you.

Now the creature waits, and says, though I have not attained such things as I have seen,
yet the very sight of them encourages me to wait upon the Lord,
that I may experience the witness of them in myself:
There are many that have some taste of great joy, and apprehensions of heavenly things,
which they have not attained, but they know what they are waiting upon God for;
not that they may have a little joy, which passes through them,
but come to have that joy and tranquillity which will accompany them in all their doings,
and their whole conduct.
God has opened many things to you,
and you have seen the way of righteousness which he has cast up for you;
and many have taken strait steps to themselves, till they have attained to say,
"`now my salvation is nearer than when I at first believed.`"
Let such go on and follow that guide by which they have been directed,
and they shall at last attain to a further state,
not only to know that their salvation is now nearer than when they at first believed,
but that they may come through the Divine Spirit of grace that they followed,
and so closely cleaved to, as their blessed guide in their way,
to have an entrance administered to them abundantly into the salvation of God,
whereby they may sit down, in the kingdom of God, with Abraham, Isaac and Jacob,
and have a wall about them, which is the salvation of God.

Here is a great encouragement for sinners, and upright ones,
to "`follow on to know the Lord,`" and then they are sure they shall know him,
for they shall behold his glory, and their souls shall be satisfied,
for nothing else will satisfy them.

People may have great openings, and great discoveries of things,
and may have delight and joy in the opening of things, as it was with the disciples,
when Christ our Lord conversed with them in the flesh; he opened many things to them,
and they had great joy and comfort in those things which he opened to them,
yet there was something lacking to suffice them.
Philip said unto Christ, "`Lord show us the Father,
and it suffices us:`" John 14:8. There was something
further to be discovered and revealed,
so that they could not find their souls to be satisfied and sufficed, till they had it.
Christ gave them such an answer as relates to that ministration that we are now under;
"`he that has seen the Son, has seen the Father.`"
Now they had seen Christ daily, and conversed with him,
and had eat and drank with him in that fleshly and
bodily appearance wherein he conversed with them;
but they had not a sight of the Eternal Son of God in a spiritual manner,
as he was the Son of God, and their Saviour; they had not seen him so.
And he that has seen Christ in a spiritual manner, has seen the Father also.

So it is with us in our day.
We have, in our profession, the teaching of this and that man.
We have conversed with Christ, as it were, to his fleshly appearance.
We have read the history of his birth, and of his life and great miracles,
and of the great love he had to mankind, by which he laid down his life for them.
We have been conversing with Christ as to his fleshly manifestation;
but consider whether there does not, till now, remain an empty place in our souls,
something that is not sufficed and satisfied?

What would you have?
Have you not scripture?
Read you not there of the birth, life, death, resurrection and ascension of Christ?
I would still have something more, for that will not suffice me;
I would have pardon of sin, and my peace with God,
and the light of his countenance lifted up upon me,
and further manifestations of Christ to my soul.
We can never see the glory of God, but in the face of Jesus Christ.
This is the discovery that Christ makes to the soul that believes in him;
this is that which gives satisfaction.

A Christian`'s work is to be conversing with him,
and exercising his mind under the gathering and teaching of him,
that can lead him to the Father.
None but Christ can do that, lead them to the Father, and show them the Father;
and he has in our day revealed himself, and made himself manifest by his spirit,
that spirit, by which we come to know his holy teaching, reproof and instruction,
daily discovered in our souls.
The spirit is our guide; that spirit we are led by, and are to walk in.
Let men go under what form and denomination they will,
"`they that have not the spirit of Christ,
are none of his,`" until they come to be guided by his spirit.

People are not led into sin by the spirit of Christ;
they will tell you these are the devil`'s temptations, and the frailty of our nature,
and the corruption of our hearts, by which we are led into sin;
it is not the spirit of Christ.
It would be a horrid thing for men to say that the spirit of Christ led them into sin;
there are few or none so wicked as to say so.
The business we are to do in the world is, to obey the will of God:
And where the understandings of men are so illuminated,
that they are satisfied in their minds,
that God has been pleased to give them a manifestation of the spirit to profit withal;
all those that have this spirit of Christ, are directed by it to do the will of God,
and to deny their own wills, and the will of others,
that would draw them from their duty that they owe to God in their generation.

It is an excellent state and condition for a man to be guided by the spirit,
and to be brought under the government of Christ, who is "`the way, the truth,
and the life.`"
So that they that come under this government are directed
and pointed out every day to do the will of God.
This you must do, and God will be pleased with you; and this you may not do,
for if you do it, the Lord will be angry with you; it is sin against God.
So that we have a heavenly advantage of being taught of God by his spirit,
to have the divine and heavenly teaching of the spirit of God revealed in us;
if we are at a loss, or make a question, or dispute about a matter,
the spirit will lead us into all truth,
if we give up ourselves to his guidance and teaching.

This has been our desire and labour many years,
not to draw people to observe what we say;
for who can direct another man in all things relating to the service of God?
If we were ever so certain ourselves,
we could not convey certainty and infallibility upon all occasions to another,
if we should speak ever so much, and be ever so conversant with them.
Therefore our work is, that all people, in all things relating to their souls,
might have recourse continually to the infallible teacher and guide, which God,
through Jesus Christ, has made known to them.
If people be ruled by this, they cannot but live in unity, and love one another;
they will not fall into malice, contention, and hatred one against another.
It is impossible for nations to make war, and destroy one another,
if they would be guided by the unerring spirit of Christ;
for how should it contradict itself?
For how can anything agree with the standard of truth, which Christ has set up,
that acts in contradiction to it?
For nothing is truth but what concurs with it; therefore it must needs agree with itself.
If we be directed by the spirit, we shall call that good which is really good;
and that evil which is so.
If there be thousands directed by the spirit of Christ, which leads into all truth,
that which is good to one, is so to all; and that which is evil to one, is so to all.
We must first know what is good, and then receive power to do it.
If we come to be instructed by the unerring spirit,
to know what is the good and acceptable will of God,
we shall receive daily power from him to do the will of God;
we shall all speak the same thing, and be of the same mind, and live in love and unity.
There is no evil willfully done against God, where the spirit of Christ,
the gospel spirit, comes to prevail upon us;
it will bring us to a peaceableness of spirit, to live in love and unity.
And the great work we have in the world,
will be to do the good and acceptable will of God,
both with respect to our solemn worship of God, and our duties towards our neighbours.
Then there will be tranquillity, peace and joy,
and comfort to all the churches of Christ that are under his government.
And it is given to the sons and daughters of men everywhere,
when they come under the yoke of Christ, and take up a daily cross,
and live in self-denial; this will bring peace and concord among them.

Many will come to our meetings, and spend a little time to hear what we say.
We exhort them to give up themselves to the peaceable government of the spirit of Christ,
that will finish transgression, and make an end of sin,
and bring into the soul (where sin reigned) everlasting righteousness.
Where there is a great deal of pride, malice and envy,
the spirit of Christ will root it up;
and all that evil that the enemy has planted in men, he will pluck it up,
and bring in everlasting righteousness, and plant love in the same soul,
and establish and settle it.
Such a one will have more joy, pleasure and delight,
under the government of the spirit of Christ in one day,
than anyone can have that is governed by the evil spirit in a thousand days.

You say the manifestation of the Spirit is given to every man to profit withal;
what profit shall we get?
How does it appear, that the manifestation of the Spirit is given to profit withal?
Because there is that life and grace stirring in the heart that makes it profitable,
and truth does so prevail, that it makes us do those things that are good and profitable,
and to avoid those things that are reprovable.
If you would hearken to the spirit, that is the reprover, that convinces of sin,
you must turn away your mind from that which will lead into those things that are reproveable,
otherwise you will be under condemnation in your own bosom.

When the Spirit of God illuminates men to see sin, the evil of sin,
he will give them power against it; but when they come to receive power against it,
and steadfastness in the ways of God, what will be the effect of that?
If I become righteous, and live a holy life, and my companions be wicked,
they will mock me, and reproach me, what benefit shall I have by being righteous?
I see evidently I shall lose many advantages which I might otherwise reap,
and reach with my own hand.
I must forsake my profits and pleasure, and other delights of this world.

The disciples said to Christ, we have forsaken all, and followed you; what shall we have?
People before they would forsake all would have something in the room of it.
Christ tells them, that he that has forsaken all, father and mother, brother and sister,
and house and land, for his name sake, shall have in this life a hundred fold,
and in the world to come, eternal life.
What is the meaning of that, they shall have in this life a hundred fold?
Christ that is truth itself, that cannot lie, has promised, that they that forsake all,
shall receive a hundred fold: Now people are ready to grasp at it;
they think it is something that will answer the loss of what they part with;
what you receive in this promise,
must not be of the same sort and kind with those things you did part with;
but when you have parted with all for Christ`'s sake, and the gospel,
you shall receive that which you shall acknowledge is a hundred fold better,
and will make you a hundred fold richer and happier,
and it will give you a hundred fold more than all
that you have parted with could give you.

If we part with sin, we part with that which brings bondage and fear of death;
having parted with that, then your fear and bondage is gone,
and you live then the rest of your lifetime at liberty: But this is not all,
you live in the enjoyment of the favour of God, you shall have the sense of his love,
and the comfort of his Holy Spirit, and you shall live in peace and righteousness,
and treasure up to yourselves glory, honour, immortality, and eternal life;
whereas before you did treasure up only wrath against the day of wrath,
and the revelation of the righteous judgment of God; you shall receive a hundred fold,
that which is a hundred fold better.
Those that part with the things that are reprovable,
and do what Christ in his day performed, the good and acceptable will of God,
the enjoyments that he has in Christ, and the comfort, peace and tranquillity he enjoys,
is a hundred fold better and more delightful than all the pleasures of sin,
and the pleasures and delights of shows, and sights and plays, and comedies,
which vain men entertain themselves with in their carnal state.
A carnal man cannot understand and discern the things of God,
and the pleasures that are to be had in his holy ways;
he only looks at the things that are seen, which are temporal,
and not at the things that are not seen, which are eternal.

But, my friends, those things which are unseen, are not so unseen,
but that when a man has an eye opened within him of the same nature with those things,
he can see them: Blessed be God that we have an eye opened to see spiritual things,
to see the heavenly treasure, and enjoy it in these earthen vessels.

For all that have an ear to hear,
it would be a profitable change to part with all that is evil in the sight of God,
and put themselves under the yoke of Christ,
and receive a principle of grace which he will communicate to them,
that they may do the good and acceptable will of God, and so may enjoy a hundred fold,
and have comfort, peace, and joy before they go from here, and are no more seen.

You to whom God has so graciously and mercifully appeared, that have an understanding,
and a taste and feeling of those things which are divine and spiritual,
and which "`pertain to life and godliness;`" of all the people in the world,
you are an engaged people to serve the Lord; great obligations lie upon you,
that you should abide and continue in that which God has revealed and discovered to you;
I mean grace: For you will never grow,
till you be under the government of the grace of God,
that grace that appeared to you before you came to the knowledge of God and his ways,
that has been with you in your travel from death to life, and from darkness to light.
Prize it as a heavenly jewel,
as that which contains in itself all those things that your soul stands in need of.
If you have any strength to resist temptation,
it is from the grace of God that you receive power to withstand temptations;
if you have any living openings in your hearts,
it comes to you from that grace that is in Christ.
When this, and that, and the other prophecy of the prophets of old is opened to you,
prophesying and foretelling that state and condition which you are travelling towards,
how the Lord will subdue your enemies under you,
you are encouraged hereby to go on cheerfully in your way,
to that rest which you are travelling to.

There are many of those that believe the truth, who are not come to establishment;
and they will find the reason and cause in themselves.
Do but ask and inquire how it comes to pass, that such and such are established,
and not subject to fear, and horror, and perplexity, as I am?
a little thing will turn me over, and shake and unsettle my mind;
this has been the cause,
a lack of keeping close to the grace of God in your conduct in the world.
When you, and your children,
and servants are governed by the grace of God in all you undertake,
then the devil will endeavour to bring you into darkness,
and bring discomposure upon your spirits; for the purpose of Christ Jesus, our Saviour,
is to settle you; and the purpose of the destroyer is, to discompose and unsettle you,
and to marry you to this and the other changing thing;
if he can fix your hearts upon this and that object,
then there is instability upon the soul; take away that thing,
and it brings disturbance upon you.
If you have any object that your mind is set upon,
you will be much disturbed at the parting with it; but whose fault is that?
The truth manifested unto you from the beginning of your conversion,
did engage you to separate yourself from all visible, sensible things,
that God might have your heart and chief love.
If he had been your God, nothing could disquiet you, when separated from you.
If you will have other gods besides him, you will lose your gods;
and when they are taken from you, you will be like Micah, and say,
"`you have taken away my gods, and what have I more?`" Judg. 8:24.
The reason of your discomposure, and anguish, and sorrow, was this;
when you had some other gods besides the Lord,
and your hearts did cleave to some temporary thing,
and the trial came that you had to part with it, you could not bear it.

If you would live a serene life, a life of tranquillity,
set your minds upon nothing but upon the Lord, let him be the object of your souls love;
live in the light of his countenance, and you may always rejoice: Consider,
as for temporals, you hold them of the Lord; God gives you this husband, that wife,
that child, that estate, God has entrusted you with it?
but not so, but he that has it must part with it, and be bereaved of it when God pleases.
Now, if you give up your hearts to God, here will be your establishment and settlement,
and you will have an abundant entrance into the everlasting
kingdom of our Lord and Saviour Jesus Christ.
And would we seek to know and feel wherein the communion of the saints stands;
does it not stand in partaking together of the bread of life,
which our father gives us from Heaven?
The father spreads a table for us in the sight of our enemies, and we are satisfied.
They that come to partake of this table of the Lord, find strength and refreshment;
so do I, and also my brethren and sisters that sit at the same table.
We are daily confirmed and strengthened by what we receive from God, and enjoy there;
here is our heavenly fellowship and society; and where there is this root of love,
love cannot be lacking in the branches: There must be a departing from the bread of life,
before there can be any jarring and contention among the members of the same body,
for we receive life from the same head, "`from which all the body, by joints and bands,
having nourishment ministered, are knit together, and increase with the increase of God,
and are built upon the foundation of the apostles and prophets,
Jesus Christ himself being the chief Corner-Stone,
in whom all the building fitly framed together, grows unto a Holy Temple in the Lord.`"

Now that you may be all preserved in Christ, this is the end of our labour,
that so everyone that has begun in the spirit, may go on in the spirit,
and never look for perfection in the flesh: That you that have begun in humility,
tenderness, and brokenness of heart, may in that meet together at times and seasons,
and have daily the presence of God among you, and have the bread of life,
which will nourish you to life everlasting, and that you may show forth to the world,
the glory, brightness, and excellency of that holy life,
which in Christ Jesus is manifested to you.

