[short="Pure and Spiritual Worship."]
== Sermon XII. Pure and Spiritual Worship.

[.signed-section-context-open]
Preached at Devonshire-House, November 12, 1690.

The worship of God, of the Great God, is pure; he is a holy God,
"`of purer eyes than to behold iniquity;`" and all they who will worship God,
whose souls are breathing to have a return of a testimony in his sight,
must offer up pure worship, and it must come from that which is pure: For that purpose,
the greatness of the love of God is made manifest in Christ Jesus;
and there is a diffusing of his grace and virtue
in the hearts of the sons and daughters of men,
whereby he has laid a foundation for his own worship; because his worship must be pure.
Therefore he has freely given unto us, through his son,
the knowledge of that pure principle of life and grace, from which, and out of which,
all true worship does spring, and all true honour to God arises;
and real obedience to his holy will springs forth out of that which is from himself.

And therefore all that will be worshippers of God aright,
must first know and be sensible wherein the ability and capacity stands,
that may enable them to do so great and so good a work.
Some have conceived it to stand in their own will,
and according to the working of their own will, they have framed worships, religions,
and observations, thinking thereby to please God:
But you know the apostle in a few short words, lays down a positive Christian doctrine,
"`without faith it is impossible to please God.`"

Now this does declare and signify,
that there must be something upon which this faith must work,
that must be the object and foundation of it: Faith as it works in the creature,
works upon something;
it lays hold on something in which there is a capacity of pleasing God.
Now if we are all "`by nature children of wrath,`"
and that no one of himself can please God,
then there must be something that is supernatural,
that must be the object of that faith by which men alone can please God;
and this must be made manifest to the creature for its help,
to be its director and supporter in that work that is too mighty for himself,
too great a work for a man or woman, too deep, too profound for any man`'s abilities,
power, wisdom, and acquirements, that he can attain to in this world,
to worship God aright.
To worship God, that is to perform a pure worship to a pure God;
who can bring a clean thing out of an unclean?
Now if we are all obliged to bring a clean worship,
a pure worship to a pure and holy God, who has created us and all things,
where shall we have it?
Not out of an unclean heart, not out of a defiled mind;
there is no bringing it forth from there,
for that is the state and condition that men are fallen into by sin,
in which their minds and consciences are defiled, their hearts are polluted,
and their affections depraved and set upon wrong objects;
and in this state none can serve God aright:
That which is pure and holy must be first made known, revealed, discovered, and believed,
before people can perform a right worship to God.

And therefore in vain is it, to go and drive people to this and that worship,
and force people to this and that service and conformity,
upon the account of the worship of God.
This is vain worship; when they have done all, it is not acceptable to God;
the poor creature has no return from the Lord, for God accepts no service or worship,
but only through his Son.
And if so be, men cannot pray and preach in the spirit of his son,
and cannot present their complaints and supplication to God,
but by the assistance and help of his blessed Spirit,
there is no reason in religion why people should expect
a return and answer from God of the prayers they make.
For it is the general doctrine of Christendom,
that Christ Jesus is appointed of God for a Mediator between God and man,
and all the acceptance we have, or desire to have, must be through him:
And therefore if we pray without him, and perform this and the other duty without him,
it is contrary to the doctrine of Christianity,
to think that ever we should have acceptance in God`'s sight.

Therefore there is a necessity for every man and woman that desires to be religious,
that has a religious mind, and is willing to worship God, and serve God aright,
there is a necessity that they come to the knowledge of Christ,
who tells us that he is "`the way to the Father.`"
They that go any other way, go a wrong way; but they that go unto God by Christ,
they do receive from him power to draw near to God;
and through him they receive from God all those blessings
that their souls stand in need of.

So here would be an end of all religions the world is full of;
of all the several worships that men have made.
They have invented and found out several ways for people to worship and serve God.
This and the other ceremony;
this and the other observation and method of preaching and praying.
If all this be without the assistance and divine help of the Mediator,
through whom alone we can justly expect acceptance at God`'s hands,
it is all good for nothing.
Therefore the first lesson of a Christian in point of worship, is,
that he come to the knowledge of Christ, by whom, and through whom,
he may expect favour with God.

Now some people say, we are already come to the knowledge of Christ;
we have read the relation in the gospel of his conception, birth, life and death,
resurrection and ascension.
Now where this belief does give a man this kind of Christian knowledge,
it does open a door and way for him into the presence of God.
This is a question that ought seriously to be considered; for if we err in this question,
we err in all: This is like stumbling at the threshold, and never coming into the house.
If we mistake in laying hold of Christ, we mistake in our worship,
and in all matters that relate to life and salvation.

For if we must have another sort of knowledge of Christ,
than we can have from the reports of others;
if I must have Christ revealed in me before I can have the hope of glory;
if I must have the spirit of Christ in me,
to help me to put up my requests and supplications,
before he can present them to the Father,
then all literal knowledge and faith cannot stand men in any stead;
this is evident by the testimony of all the writers of the New Testament.
Christ and his apostles did concurrently signify, that the hope of a Christian,
the power and strength of a Christian, all lies in this,
that they had known the revelation of Christ,
and the powerful operation of the spirit working in them;
this was that which was well pleasing to God.
Many scriptures might be spoken of, but you know the scriptures, and can read them,
and see in them the concurrent testimony of all holy men to this day,
that the knowledge they had of Christ was a divine knowledge, a spiritual knowledge;
it was a knowing him after the spirit; it was a revelation of Christ in them,
that separated and distinguished them from reprobates;
even the knowledge of God through Jesus Christ their Lord.
Why should not we come to this knowledge as well as they?
The Lord is the same, and his power is the same, and his "`arm is not shortened.`"
We may see as much need of divine assistance, and divine love, as ever men did;
we can perform no duty, either of prayer or preaching, without divine assistance;
not so much as a sigh or groan, that may have acceptance with God,
without the help of his Spirit.
"`The Spirit helps our infirmities, for we know not what we should pray for as we ought,
but the Spirit itself makes intercession for us with groanings which cannot be
uttered:`" Rom. 8:26. If we go about the duty of prayer without divine assistance,
we see what sad work we make of it; if we pray not in the spirit,
and with the understanding, how can we receive the thing we pray for?
But if we "`pray in the spirit,
and with the understanding also,`" then the "`spirit helps our infirmities;`"
the spirit that came from God brings us the things we stand in need of.

So that a Christian has a foundation for his worship and Christian performance;
what is that foundation?
Nothing that is corrupt, if it be, it is good for nothing;
for nothing that is corrupted and that defiles, can be acceptable and pleasing to God;
we are all polluted and defiled by nature; how can carnal men worship a Spiritual God?
Carnal men that are in death and darkness, cannot worship that God that is light,
and dwells in light, that is inaccessible,
that is "`of purer eyes than to behold iniquity.`"
Carnal men lack a foundation for their worship,
and will until they come to that foundation that God has laid.

Now, that I may speak intelligibly what the Lord has laid upon my heart,
I would say thus:
There is a universal benefit and privilege distributed and given freely of God,
unto the sons and daughters of men, in their natural state, through his Son,
Jesus Christ, in that he has caused his light to shine,
and his grace to be extended to every man; "`for the grace of God,
which brings salvation (for it is not by works) has
appeared unto all men,`" and brings light,
by which every man may see how to worship God; God has enlightened every man,
and this light comes by Christ the Mediator;
this Mediator is the way that men must walk in, if they will come back again to God;
for men are run out and departed from God; if men will draw near to God,
and take some foot-steps towards the kingdom of God, from the kingdom of sin and Satan,
they must mind the way, the way must be their director,
they must not go which way they wish.

This is that which was prophesied of Christ; says God,
by the prophet Isaiah I will give him for a leader.
I would readily return to God, and go out of the kingdom of sin and Satan,
to the kingdom of God: God has given Christ to lead me;
if I knew what way he would lead me in, I would go that way.
As soon as a man takes hold of Christ, his grace, and spirit, and life,
he will be ready to say, I am corrupt; my senses are corrupt, my mind is depraved,
my conscience defiled and polluted;
but I have found out something that God has bestowed upon me, that is essential,
holy and pure, that did never consent to my corruption,
but is a witness for God against it: Here now a Christian lays hold on Christ,
the leader; which way will he lead me?
If you lay hold of this guide, he will lead you out of evil,
he will teach you to cease to do evil, and speak evil:
This light will lead you to nothing that will dishonour God, or defile your own soul:
But this is not all, we must not only cease to do evil, but we must be doing something;
there must be a breaking off from pride, foolish jesting, evil communication;
but this is not all that he will lead me to; let us learn that lesson,
"`cease to do evil.`"
This doctrine was preached before Christianity was preached, as it is now preached;
the prophets of old preached this doctrine to the Jews that were under an outward administration,
"`cease to do evil, and learn to do well,`" then I will plead with you,
and discourse with you, says the Lord: "`Come now, let us reason together, says the Lord,
though your sins be as scarlet, they shall be as white as snow;
though they be red like crimson, they shall be as wool.`"

This is the first lesson that a true Christian learns in his turning to God,
in his change and translation, to cease from that which is evil:
Here is a cessation of rebellion, and here is some hopes of being reconciled to God;
a man has been a rebel against his Maker,
but he has now received help to resist those temptations that prevail over him:
But there is no worshipping yet,
there is a forward mind in men to do something that is pleasing to God;
but there are some that are not troubled at all for their evil ways,
and dread not God`'s anger, but make a mock at sin, that draw others to it,
and make themselves merry in it:
And there is a sort so far touched with a divine sense of God`'s love to them,
that they have also a sense of his anger and indignation, because of their sin;
and they would eagerly be out of his anger; and who can blame them?
When a man feels the anger of God burning like a fire in his bosom,
who can blame that man if he desire peace with God?
If he be under a sense of the displeasure and indignation of the Almighty,
he must not haste too soon out of that condition he is brought into;
for this is God`'s purpose, and this is the fruit of all his troubles and afflictions,
to take away sin: God has no other end or design in the affliction that is upon him,
than to take away sin;
when God has brought a people into a distressed and dejected state for their sin,
the fruit that God expects, is the taking away of their sin,
and he will hide pride from them, and humble them before him;
if this be the purpose of God, that he intends to purge and purify his people;
then says the poor creature, if God designs to purify me from sin,
then I will pray to God to support me, and bear me up under his indignation:
That is the cry of the soul that he may not be brought
too soon from under the judgment of God,
but may be supported and hid in the hollow of God`'s hand,
until the time of remission and refreshing comes,
that he may behold the light of God`'s countenance.

Here is encouragement for everyone that is acquainted
with this divine principle of grace,
that will be led by it, and follow it so far as to be led out of evil;
then they will be fitted to do something in the work of God;
every sigh and groan that you have the assistance of the spirit of God to help you in,
is a part of worship: All your brokenness of heart is part of worship;
hereby you acknowledge the great God, that he is able to help you on in your way,
and to pardon your iniquity, and blot out your transgression,
and give you all those heavenly blessings that your soul does stand in need of.
Then your soul will bow down to God in acts of holy worship, and say,
with a humble confidence and expectation, God will do all those things in me, and for me,
that will promote my salvation.
It is nothing in religion for people to go from praying and preaching to sinning;
but God must have a holy sacrifice, and that must come out of a pure heart.
Now when a man is brought by the help of God,
and by the divine assistance of the Mediator,
Jesus Christ, to break off from his sin, then he stands fair to become a child of God,
and to be a servant of God, and to do something for God in his generation,
and to offer to God praise and thanksgiving,
and to perform all other duties that God shall lead him into.

But some will say, what, must not we do anything?
I have deeply weighed that question, what a poor man or woman must do,
that is come out of bondage.
There is a propensity in people to be doing, they would readily do something,
they would be doing; they say, what shall I do?
If I do something that pleases not God, I had better let it alone;
and I can do nothing acceptable to God without divine assistance:
Such a one that sees his own impotency and inability, will cast his care upon God,
and will say, the Lord is able to lead me and guide me: I am ready to do your will,
O God!
Make it clear to me that this is your will, and that this is that which you require;
I am ready to do it, though it be a cross to my own will:
He is ready to go on in God`'s way, in the way of Christianity;
such a one that has the true knowledge of Christ, if he speaks,
the Spirit of Christ speaks in him; if he prays,
it is through the assistance of the Spirit of Christ,
through whom God alone is appeased and reconciled,
and through whom they may receive a blessing from God`'s hands:
But for men to run on in their own wills, and to do a thing because they will do it,
they had better sit still; this doing in their own wills,
has filled the world with a sort of Christians that lack acceptance with God,
which is to be had alone through the Lord Jesus Christ;
and the lack of the guidance of God`'s Holy Spirit,
is the misery and downfall of Christianity in our days.

Therefore it is our work and business to build upon that foundation which God has laid;
no worship is pleasing to God,
but that which arises from that spring that is pure and holy:
If I cannot find that which will keep me from all pollution and defilement,
if I cannot find that, I must stay till I can;
to begin a worship and a religion without I know that it is acceptable to God,
is but lost labour, and time spent in vain.

Therefore, friends, let everyone that desires to be religious, turn their mind inward,
wait for the gift of God, which is essentially pure, that never did consent to evil,
that never mixed with the corruption of nature, but bears witness to the light,
that will guide you and lead you, and conduct you first out of sin;
then it will lead you into that worship and religion,
and the performance of those things that are pleasing to God.
They that are come thus to worship, they do not only know what the Lord requires of them,
and when he requires it of them, but they are given up into the hands of God; they pray,
preach, exhort, and live according to the will of God.

It is hard for people in a carnal state to believe this; but you that are believers,
that are come to know the gift of God in yourselves,
and the necessity of being ruled by him, you will believe us,
for none else will believe us; let us preach to as many people and nations as we will,
none will receive us as true ministers,
but those that have the truth in their own hearts;
if there be any that despises the grace of God in his own heart,
he hates that which chides and reproves him; if there be such a man,
he will hate me because I am a minister and a witness of the grace of God,
and of that truth in the inward parts,
which is the ground and foundation that man has of acceptance with God.
A wicked, carnal wretch will say, I hate such a one, I hate the light,
that which checks me, and witnesses against me;
you are such a one as bear witness against me, therefore I hate you: It is very true,
it cannot be otherwise.
Now our desire and labour is, that men may come to the love of the truth in themselves.

You know there are a great many other ministers,
whose labour is to persuade people to believe what they say; to lay down a doctrine,
and prove it by scripture and reason,
and set it home upon their minds by such testimony as the scripture affords,
and hereupon they prevail on the minds and judgments of people,
to believe what they lay down.

It is easy to lay down a position, and prove it,
and convince people that it must be according to scripture;
but when a person is convinced of a principle of truth, he is not regenerated thereby,
and come to God; therefore, though he cannot deny the doctrine of truth in words,
yet he can deny it in works, and does not rightly come to love it.
If people would believe what we say,
and observe what argument we bring to prove a position,
they may be convinced of the doctrine of truth, and come to a profession of it,
and yet be strangers to it, till they come to love it in themselves:
If it were not for this, we would leave preaching,
if God had not given a measure and manifestation
of the spirit to every man to profit withal.
You have it in yourselves, we are but as monitors to you, to put you in mind of it;
you have so much business in the world,
that you have not had leisure to take notice of it.

A man may have a rich jewel, and be poor notwithstanding,
till he come to know the value of it.

A man has a rich and precious jewel; a pearl bestowed upon him,
that would make him rich in faith and love to God,
and qualify him for the kingdom of God, and make him an heir of it; but he knows not,
nor understands the value of it, and esteems it not;
therefore God has raised up ministers to put you in mind of it,
that you may be happy forever, and live in blessedness to all eternity;
"`whoever has an ear to hear, let him hear;`" and when they hear what we say,
let them take the benefit of it to their own souls.
We bring not truth to you, but God has bestowed it upon you; you will be rich indeed,
if you do as a man that bought a field where the precious pearl was,
and dug till he found it.
Come to the foundation upon which you should build all your hopes of happiness,
and depend not upon your own works, or religious performances, for acceptance with God;
for there is no acceptance with God, but only through Christ,
we are only accepted of God through him.
Those that will become Christians indeed,
and worship God as he has ordained and appointed himself to be worshipped,
they must come to the principle of light and grace in their own hearts,
which they have in, and through Christ, and they will find acceptance with God.
