[short="Sermon XVI. The Dawning of the Day of Grace and Salvation."]
== Sermon XVI. The Dawning of the Day of Grace and Salvation.

Preached at Grace-Church-Street, August 2, 1691.

My Friends,

You cannot but know and be sensible, that a gospel-day, a day of grace and salvation,
has dawned upon you, and that the light of it has broken through many clouds of darkness,
which sometimes you could not see through.
This is an inestimable and unspeakable mercy of God unto us,
that the light of the gospel of salvation shines upon a people,
that without it must be miserable.

There has been a very dark and cloudy day upon our fore-fathers, and also upon us,
in the days of our ignorance.
We are apt to wander here and there,
and to be turned aside with the wind of men`'s doctrine, that we could not find a rest,
a home or a settlement for our souls, in order to eternal life.
And there are many that have cried unto God, that he would please to reveal his way,
and to make it known unto them; and they have been apt to covenant with the Lord,
that if once they come to a certainty, they would walk in it.
Unto such as these the Lord has bowed his ear, and has answered them;
and in his answering the cry of the soul, he has brought salvation near,
and has revealed the power by which he would bring it to pass,
in every particular soul that receives the gospel of his Son.

But now friends,
you that are sensible of this blessed and glorious visitation of his gospel-day,
in which salvation is brought near,
it is needful for everyone to examine their own hearts,
whether they have really received the gospel;
whether they have received and embraced the great bounty,
and unspeakable blessings of the gospel, with which the Lord God of life has visited us,
or whether they have rejected it.
For though it is our happiness to know the visitation of life,
yet it does not follow that everyone that is visited will be made an heir of it;
for there are many that fall short through their unbelief.
There are many that have received the gospel, who do disobey the gospel of Christ,
and so have not eternal life by it.

When people come to this serious examination of themselves herein,
then the light and grace, that comes from Christ unto everyone of us,
both to him that rejects it, as well as to him that receives it,
that will make known to them their state and condition,
with respect to the gospel of Christ.
For there are a great many,
that by an alienation of their minds from the light of Christ Jesus,
are apt to be mistaken in their state, and to make a better judgment of themselves,
and of their state inwardly,
than really it will amount to in the day that the Lord searches and tries them.
But they that make a judgment of themselves,
by the openings and discoveries that they have through the light of Christ Jesus (for
so we are to do in this weighty matter) they make a judgment of their state and condition,
according to the evidence that the Spirit of God bears to their spirits;
and this I hope you will all say is a most certain way.
For if we go to compare ourselves one with another, and say, I am better than you,
and that man is better than I, here we are liable and subject to a great many errors,
where there ought to be none.
But if we come to measure and determine our present state and condition,
by the evidence of the Spirit of God, bearing witness with our spirits,
here we have a foundation to place an infallible and certain judgment upon.
And they that are obedient to the gospel of Christ,
are capable of giving a sound judgment of their state, because they are made partakers,
through Christ, of that grace, and light, and truth, which they should be obedient to;
and they are brought into a kind of knowledge and understanding of their duty,
whether they do it or no.
And this knowledge, and this understanding that God has given them,
makes them capable to pass a right judgment upon their own state.
They will not call it a good state, if it be an evil state;
and they will not call it an evil state, if it be a good one.
They know it is good by the principle of truth in their judgment.

Therefore since there are so many uncertainties in the world,
and that men are so apt to take hold of an uncertain way of judging and determining,
even in matters relating to their souls:
There is a greater aptness in people to take hold of uncertainties,
in judging about the matters of their souls,
than in those things that relates to their bodies.
Seeing people are so liable to it, it can do none of us harm to exhort one another,
and move and stir up one another, to make a calculation of our states,
by something that will not deceive.
There are abundance deceived in this country, as well as other countries;
we shall not need to go into foreign parts to find people deceived and deluded.
It will not be amiss to say, the drunkard, the swearer, the liar, the oppressor,
the proud, and the malicious, are deceived: If they were not so,
they would never be overcome by the wicked one; the author of all evil,
he has deceived them, in that they should think to go on in these things,
and cry "`peace, peace,`" to one another, and in their own souls:
This is a great delusion; and the devil is the great deluder that they are deluded by:
And it would be worth the while to find out that
which would make a man think himself in a happy state,
and hope to enjoy eternal life, with God and Christ;
and when he goes on in sin and iniquity,
it would be worth the while to find out the delusion.

There is nothing so proper to turn everyone to the grace of God,
as to search their own hearts, and try their ways.
This is that which will discover their thoughts, and make them known to themselves:
This is God`'s grace and gift to men while they are yet sinners and disobedient;
he does not withhold his grace, but gives his grace, and light and truth,
even to the rebellious: He gives gifts to men, even to the rebellious,
that he might have a place and dwelling among them,
that they might know there is a God that searches the heart, and tries the reins,
and judges all unrighteousness.
If God has given you so much grace, that he might have a dwelling in your heart,
should not that restrain you from sin, that the devil, by his temptations,
might not defile you, and unfit you for the kingdom of God?
When the Lord comes to search the heart, it is in order to the purging of it,
and the taking away of iniquity and sin, that would unfit you for his kingdom.
This is a better way, and more excellent than living to the flesh,
and fulfilling the lusts thereof.
Let people live ever so much to their own corrupt wills, in pride, carelessness,
looseness, and the vanity of their minds,
they will not find so much true satisfaction and delight, as in living a holy life,
living in the fear of God, and avoiding sin,
and keeping themselves from the temptations and snares of the devil.

This is a more excellent way;
and it is our work and business to declare to people this more excellent way, which all,
one time or other, will confess.
This is irksome, some will say; this will abate my pleasure and delights in the world,
and spoil my secular interest.
If it were not for this reason, they would grant it were better to live a holy life,
and to live in the fear of God, than live in the service of the devil;
and their carnal interest lies in the way, and weighs down the scale,
but it is because you join with it, otherwise the devil, and all the powers of hell,
could not weigh it down.
If people would consider these things seriously, they would say,
it is better to serve God, that made them, and gave them life, and breath, and being,
than him that would destroy them;
and then when they meet with the pleasures and delights of the world,
that the devil lays before them,
they would never weigh down the scale against a Divine Reason:
If you will give your heart to it, and seriously consider it,
it will weigh down the scale against all temptations to live in sin,
and pleasure, and mirth.
If you will but join with this Divine Reason,
that tells you these carnal pleasures and enjoyments are not necessary for your soul,
but it is necessary to live a holy, heavenly life,
and to serve the Lord that gave you life, and breath, and all things;
that has vouchsafed you manifold preservations.
If you will but join with the Divine Reason,
and hearken to that which opens the truth in your own heart, all the devil can do,
cannot make you serve him; for the devil has no coercion,
no power to force you to commit sin;
he cannot make a man work wickedness against his will; he must cloud the understanding,
and work upon the will, and allure and entice the affections by earthly things.
So you can not be forced by the devil against your will, to yield to his temptations,
to commit any sin; but you must say, I will do it.

I confess, when the understanding is bribed,
and the will allured and seduced by the devil`'s temptations,
there is no withstanding them.
But on the other hand, if men would give up themselves to the power of God,
they would have Divine Assistance; and joining with that power,
they would be "`more than conquerors.`"
Therefore we cannot but be encouraged to keep in the way of the Lord,
and have acquaintance with the power of God, which will preserve you,
and give you victory over all the temptations and assaults of the devil;
and without this power you cannot overcome; but if you have the assistance of this power,
nothing will be too hard for you.
When you are in straits, and in a helpless condition, you sometimes are ready to cry out,
I shall not overcome my spiritual enemies;
I shall never get victory over sin and the world, the flesh and the devil;
and I shall never be able to withstand his temptations,
but they will prevail over me all my days.
No wonder you make this conclusion,
when you have parted with your trust and dependence
on that power that is able to overcome the devil,
and baffle him in your thoughts, words and deeds.

You may be ready to say, alas! of myself I can do nothing;
I am not able of myself so much as to think a good thought; yet by Divine Assistance,
I do many times think good thoughts.
In me, that is, in my flesh, there dwells nothing that is good.
Not in my flesh abstractly; separate from the power of God,
and the Divine Assistance vouchsafed unto me.
In my flesh dwells nothing that is good.
But if you take me as one that has faith in Christ the Mediator,
this faith embraces the tender of the love of God in the Redeemer.
And when I have this faith, there dwells a good thing in me;
and from this good thing that dwells in me,
there flows forth good words and good actions;
then you come to be acquainted with a power greater than your own;
and if you trust in it, you will be able to withstand temptations.
When you are tempted to any sin, you will not only be able to withstand the temptation,
but to overcome it too, and to be more than conquerors in your spiritual warfare.
This relying upon, and trusting in the power of God, is that which we call faith;
and this faith is the operation of God.

To speak in plain words, God will operate upon your mind, and make you know,
that this is his power, light, truth and grace, by which he would save you.
And after God has wrought and opened unto you in this manner,
it is your duty then to believe in it, to put your trust and confidence in it,
to be delivered.
But though faith be offered unto me, yet it is not forced upon me;
God has offered faith to all men, but he does not force it upon any.
All have an opportunity offered to them; if they will but join with it,
they may have says wrought in them, and be fitted and prepared for the kingdom of God.

There are many that are convinced of the truth of the doctrine that we preach to them,
but they do not get into the power of the truth;
they will hear us preach of the power of truth, and will hear what this man says,
and what the other man says; and this will serve their turn,
that they may talk of religion, and make a profession:
But they do not seek after that power that should
enable them to work out their own salvation.
These persons grow in knowledge, but they do not grow in grace;
they will embrace truth as far as doctrine and words will go; they have professed it,
and they have suffered reproach for it,
and yet they have not received the truth in the love of it;
they cannot reach to the power of it;
they glory in their knowledge and in their understanding,
but they come not to that which sanctifies them; they are not able to resist the devil,
and to stand against his temptations; when a temptation comes, they join with it,
but they cannot withstand it: They come to the knowledge of truth in words,
but they come not to the knowledge of the power of it in their hearts and minds,
so as to make them prepared vessels for God`'s honour;
God is more dishonoured by them than by those that never professed his name:
They fall into the temptation of the devil,
and never discern the operation of God`'s power in their own hearts.

Secondly, There is another error as great as this;
there are a great many that when the Lord`'s power has wrought in their hearts,
and they have truth opened to them in the power of it, yet they have not believed in it,
they have not had faith wrought in their hearts, they have not trusted in it,
nor relied upon the power; so they are weak and feeble, they have little faith,
which is next to none at all.
If they have ever so much knowledge, how easy can the devil tempt them to sin,
if they have no faith; "`this is the victory,`" says the apostle,
"`that overcomes the world, even your faith.`"
This is not my victory, that I see the subtlety and wiles of Satan, and know much;
but that which is my victory is my faith: My trust is in the power of God,
and my reliance upon him who is God, mightier than all the strength of men and devils;
that God who knows my heart.
If I be faithful to him, and rely upon him by faith, I shall resist the devil,
and withstanding his temptations, obtain victory over them.

This power you may have by the gospel;
but then you must be true to the power of it in yourselves;
for I do distinguish between the gospel, as it is a doctrine and word preached,
and an invisible, divine power working upon men by the preaching of the gospel;
you will all hear the gospel preached, though you be ever so proud and high-minded,
and you will say it is true;
but you can never come to the saving knowledge of the gospel itself,
till you find it working inwardly upon yourselves.

We do not pretend to any power of opening men`'s hearts,
as God opened the heart of Lydia;
but when people come to wait upon God with a serious and religious mind,
you will find the power of the word working effectually upon you,
and so the gospel will become the power of God to your salvation.
This is, and shall be my prayer, for all religious assemblies,
that the Lord will be pleased to teach them, by his invisible word,
and beget living desires in them towards himself,
and bring them to an esteem of holiness and righteousness,
that they may adorn the gospel of Christ, by living gospel-lives; for lack of this,
what dishonour have men brought to God, and what reproach upon the gospel.
O! that people would come to hear the word preached, with desire to profit by it,
and say, Lord, do me some good this day,
give me a powerful refreshing visitation at this time;
give me some living experience of your Almighty Power working upon my heart,
that I may not be led by this man`'s word, or that man`'s opinion; for if they mistake,
I shall be mistaken: But if I build my faith upon what God in his word reveals to me,
I shall infallibly know what I am to believe and practise,
and I shall receive from God some good thing,
and I shall know "`what is the good and acceptable will of God;`" I shall find
that there is power in the gospel for building me up in the most holy faith,
and that it is mighty, through God,
for the pulling down of the strongholds of sin and Satan,
and I shall see the salvation of God brought near to me.

When the gospel becomes the power of God,
and works upon the hearts of men by the operation of the Divine Power,
they may distinguish between that faith that is built upon the declarations of men,
and that which is wrought by the revelation and discovery
of the mind of God in their souls;
this is that which we may bottom upon,
and have an anchor sure and steadfast in our own souls; when I depend upon Christ,
"`the rock of ages,`" both of this age, and all other ages,
my faith must be placed upon him; and when I hear the word of a man,
I must have an eye to God, that he will reveal his power in my heart;
this will make me believe in the Lord Jesus Christ,
and receive that ingrafted word which is able to save my soul:
I shall not only hear the word, but live in obedience to it.
What signifies it to make a profession that I have the light within,
if I do not give obedience to it?
For without that, it is all hypocrisy; all pretence to holiness, or righteousness,
all mortification, is but hypocrisy,
any further than we find the power of truth making
an impression upon our hearts and minds,
bringing us to the obedience of faith.

Let them therefore that profess righteousness, live righteously,
and they that hear the gospel, live in obedience to it;
and those that profess to be Christians, let them live like Christians indeed:
When everyone comes to know within himself, so far as the gospel has shined upon him,
that they have received the truth in the love of it,
and love the truth as it is in Jesus, and are obedient to the gospel,
they shall know the salvation of it.
There is a discovery of God`'s power in the gospel, and there is a believing of it,
and trusting in it; this is that which belongs to a Christian,
this is the beginning and the first step to a Christian life; we must believe in Christ;
"`for without faith it is impossible to please God.`"
He that believes, should be careful to walk in the truth that he has received,
and then he shall have a testimony of the power and virtue of it in his own soul.
This virtue and power, if he joins with it, has the government of his heart and life,
and gives him victory over the world, and the temptations of Satan.

You know in the primitive times there were believers that not only held the faith,
but loved by faith; and by that faith they got victory over all the allurements,
and pleasures and vanities of the world.
"`I have fought a good fight,`" says the apostle, 2 Tim. 4:7-8,
"`I have finished my course, I have kept the faith,
henceforth is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, shall give me at that day, and not to me only,
but unto all them also that love its appearing.`"
I have got the victory and there remains an eternal weight of glory for me.

My friends, this is our ambition, and all our labour among you,
that you may be built up in the most holy faith; that you may be brought home to Christ,
in all your meetings and gatherings together:
You should desire to be enriched with faith,
and to have your own store-house filled with all the fruits of the Spirit,
and not only seek for the knowledge of the truth,
but be subject and obedient to what you know,
otherwise by your religion you will but hurt yourselves.
And the apostle Peter, 2 Peter 1:12, speaks of knowing the truth,
and of being established in it,
and of some that "`after they had escaped the pollutions of the world,
through the knowledge of our Lord and Saviour, Jesus Christ,
they are again entangled therein, and overcome,
and the latter end with them is worse than the beginning;
for it had been better for them not to have known the way of righteousness,
than after they have known it, to turn from the holy commandment delivered unto them.`"
There is a power goes along with the preaching of the gospel,
that will enable you to do what you know; the gospel is a powerful doctrine,
whether you know it or not, or whether you submit to it or not,
yet pray remember that God`'s people are a willing people in the day of his power,
they are a certain sort of people that are devoted to God,
and submit all their worldly honours, interests, profits and pleasures,
to the pleasure of God, and desire no other pleasure or happiness,
but to enjoy his presence and favour; they are satisfied with this,
and they are a happy people, being made a willing people in the day of God`'s power;
they are willing to deny themselves, to take up a daily cross and follow Christ,
and have salvation upon his terms.

There are a great many professors that have notions, and out-side appearances,
but they lack that virtue, and life, and power, that should settle them in religion,
and a love of the truth.
The Lord that knows our hearts,
knows that our labour and travel among you has been designed for your good,
and that our hearts desire is, that you "`may be saved in the day of the Lord Jesus.`"
We would have people consider, and attend and hear what God speaks,
and what he has taught you by the ministers of the gospel: We have all ears to hear,
let us thank God for that;
blessed be God that there is a power and an ability of hearing with an outward ear;
but there are many that will not so much as give the hearing
to what might be spoken to them from the Lord:
"`He that has ears to hear,
let him hear what the Spirit says to the churches;`" and what he says to his own soul;
hear what the Spirit says of your own state and condition; if it be good,
bless God for it; are you in so good a condition, that you have no trouble,
no distress to lament, no needs to supply, blessed are you that have none;
but if you find that you have done amiss,
and if the Lord should call you this night to give up your account,
the Lord has a great deal against you, I am sure;
and I tell you it is your duty to turn to the Lord with unfeigned repentance,
that through Christ Jesus, you may receive pardon and remission of all your sins,
and hear what the Spirit says to yourselves, and in yourselves.

Pray come and make it your work and business the rest of the time you have to live,
to work out your salvation with fear and trembling, that when Christ comes, you may say,
"`come Lord Jesus,`" come quickly, purify me and sanctify me,
and prepare me to be presented to the Father "`without spot,
and blameless;`" the day is coming that this will be the desire of everyone of you.

And it is the earnest breathing and desire of my soul,
that everyone of you may have an eye unto the Lord, and he will look down from Heaven,
and have regard to the cry and the sighing of the needy soul.
God will arise, and find out the people that breathe after him,
and that desire to be reconciled to him, through the Mediator Jesus Christ;
the Lord loves to find out such a people,
and I am glad to preach to such a people the glad tidings of the gospel,
and to teach as God has taught me; good and upright is the Lord,
therefore will he teach and guide you in the way which you should go.
Walk humbly with God; he will resist the proud, but he will give grace unto the humble.
Walk uprightly before the Lord in this gospel-day that shines upon you;
love the appearance of God, and prize it, though it has not been so glorious to you,
as to some others, yet despise not the day of small things:
live in subjection to that grace that the Lord has given you,
and the Lord will give you more grace, and pour out his Spirit,
and multiply his blessings upon you;
the Lord has "`begun a good work in you,`" and he will "`carry it on to the day of Christ,`"
and will vouchsafe to bring the glorious day of his visitation upon you.

To the Lord I leave you, to his favour and protection I commit you;
remember that there is no salvation but by Jesus Christ, and none to be had by Christ,
till you come to believe in him; to him that searches the heart, and tries the reins,
that pardons iniquity, transgression and sin, for the sake of Christ Jesus, the Mediator,
to him I do commit you, not doubting but that he that has begun a good work in you,
will at last complete and finish it to his own praise and your salvation.
