== Sermon XVIII. True Christianity.

[.signed-section-context-open]
Preached at Grace-Church-Street, April 10, 1692.

The institution of the Christian religion was for this purpose,
that holiness and righteousness might be brought forth in the earth; that God,
through his Son Jesus Christ, might take delight in the sons and daughters of men,
that they might be reconciled to him; for that which the law could not do,
by reason of its weakness, God has had a purpose to do by his Son,
and to him he gave all power in Heaven and Earth,
that thereby he might be enabled to perform the great work of God,
in establishing righteousness, and in bringing forth a holy people, to serve a holy God.
This is the great blessing that is come to us, and to all mankind,
through our blessed Lord and Saviour, Jesus Christ,
that came to turn everyone from the evil of their ways.
That is the way and method by which our Lord Jesus accomplished the end of his coming,
and the will of his Heavenly Father; Moses and all his washings, offerings,
and sacrifices, could not make clean and purge the conscience;
and by all his offerings and sacrifices, he could not reconcile us to God: But Jesus,
by his once offering himself did forever perfect them that are sanctified;
and by one offering, reconciled us to the Father,
and so brings forth a holy generation unto God,
through regeneration and the sanctification of the Spirit.

And seeing the Lord has been pleased in the riches
of his grace to open this new and living way,
for man`'s returning again into unity and fellowship with his Maker, the question,
my friends, that I would put to you on the behalf of God, is, for all of you to consider,
whether it is not best for everyone of us to lay hold of salvation,
to lay hold of that blessing with which the Lord has blessed us,
that so the principal institution of Christianity might not only be named and spoken of,
but might come to be enjoyed and witnessed in everyone of our own souls;
and that all might wait with expectation on the Lord Jesus Christ,
for fulfilling of this great work in themselves.

There is a general notion among people, that Heaven is a holy place,
and that nothing that is unclean can enter into it, to have a habitation there,
when time in this world shall be no more with us; and that time which we have given us,
I am sure is given us of God,
as an opportunity of fitting and preparing us for his dwelling-place;
and every day and hour of it ought to be employed in that great work,
that so we might draw nearer and nearer to that state and condition
that suits and befits that holy dwelling where saints and angels,
forevermore, praise the great and glorious God: So that I am persuaded you believe,
that you and all of us,
are to be accountable to God for all the time he has bestowed upon us,
whether we use it to the purposes for which he has given it,
or whether we misspend our time upon those things that are not profitable to us;
and upon these considerations,
we had need all of us to take heed to our present state that we are come to,
and are arrived at in the present time; as for the future time,
that we all know we are not sure of; and the future state that we may hope to come to,
there is no certainty of it, unless there be an improvement of the present time,
and the opportunities of our present state:
Therefore everyone should apply their hearts unto the seeking of wisdom and understanding,
and unto God, that he may give us to understand our state,
and our present fitness or unfitness for the kingdom of glory and happiness,
and of that holy dwelling we hope to enjoy forever.

If I will but turn my mind inward,
to the serious consideration of my present state and condition,
I can tell whether I am fit or unfit to approach God`'s presence;
and if I find I am unfit, I must have recourse to the divine working of that great power,
which God has ordained and appointed for this purpose;
I must come to him to work all my works in me, and for me,
according to his good pleasure; and that he will never do,
unless it be by crossing me in my carnal pleasures and corrupt inclinations;
for that which pleases man, does not please God:
And God will not revoke the holy scriptures, that tell us,
"`that they which live in pleasure,
are dead while they live;`" they that are indulgent to their own affections,
and their own delights, and their own humours,
they are not at all ready to please and glorify God; they are not fitted for it,
therefore he never sanctifies, nor brings any into a true Christian state,
but through a daily cross;
so that if I am not already fitted and prepared to do that which is pleasing to God,
I may be fitted by taking up a daily cross, to glorify God here, and enjoy him forever.

What those things are that you are to do, I need not tell you, nor what you have done.
I judge no man: There is one that judges, he will tell you if you ask him,
what your state and condition is; he will tell the drunkard, if he ask him,
whether he is fit for Heaven;
and also the proud and haughty persons whether they are fit for Heaven:
Let such as are guilty of these or any other sins,
inquire of the oracle in their own bosoms, am not I fit for Heaven,
notwithstanding all this?
He will tell you no, there is no unclean thing shall enter there, nothing that defiles,
nothing that hurts or oppresses; the proud, peevish, malicious person,
that is hurtful to others, that hurts his neighbour, is shut out.
"`There shall by no means enter into Heaven anything that
defiles,`" Rev. 21:27. "`For outside are dogs,
and sorcerers, and whoremongers, and murderers, and idolaters,
and whoever loves and makes a lie,`" Rev. 22:15.
None shall enter into the holy city of God,
but those that are purified and purged from all iniquity:
Therefore God has sent his son Jesus, seeing none else could do it:
Moses and the Prophets could not do it, therefore he sent Jesus to bless us,
in turning everyone of us from our iniquities, and from our evil ways;
one man has this evil way, another that evil way: It is all one to him;
his work is to turn everyone of us from our evil ways.

But why then (you may say) are so few turned from their evil ways throughout Christendom,
where Christ is believed in, professed, read and heard;
that yet so few are converted and turned?
for we see great numbers of liars, swearers, drunkards, and unclean persons among us,
where Christ is cried up at a mighty rate,
and yet people are not turned from the evil of their ways;
there is something sure that is the reason of it.

I would have all of you consider what the reason of it is,
that those that profess to be Christians, are not turned from the evil of their ways;
for Christ has all power in Heaven and Earth committed to him, and he is able to do it,
and he was sent from God on purpose to do it; but this is a certain truth,
it is not done; and what is the reason of it?
"`He came to his own, and his own received him not;`" what is the reason?
He has caused his grace to appear to every man in the world,
and yet they are not taught by it.
Here is an object of faith for all, and God has offered faith to all men,
since he has raised up Jesus from the dead, yet men have it not:
What is the reason that this nation, as well as other nations,
have been puzzled about it, to find out things that are so plain in scripture,
in relation to the love of God to mankind, and in relation to Christ Jesus the Saviour,
and so little of this work is wrought among us?

Some say there is never a man in the world turned from the evil of their ways;
they live in sin, and they are under a fixed necessity of continuing in it,
and lying under it all the days of their lives, for all this belief of the love of God,
and the power of Christ, and the profession of it:
Some say there is never a Christian in the world can live one day without sin,
but will defile himself with one thing or another; that the devil will prevail over men,
and sin mix itself with our prayers and alms, and all our holy duties;
so that there is nothing clean; nothing pure that We can perform to God.
There are others that are not so rash in their judgment, and not so inconsiderate,
but they will believe some men and women may come
to a power and ability to withstand Satan,
and resist him in his temptations;
and that there are those that have been turned from the evil of their ways,
but they are not; What is the matter?
You have spent time about this,
what is the reason you are not turned from the evil of your ways?
The devil has told the people in former days, that the reason why men live in sin, is,
because God has appointed it so to be:
And that has stopped the mouth of many a plain-hearted tender Christian;
they have cried unto God under the weight of their sin,
and they see no deliverance after all their prayers and tears,
because they have been told they cannot do it,
and that God has appointed it should be so, and required them to do what they cannot do;
and with some the custom of sin has taken away the sense of sin,
and they go on to perdition in their security.

I hope, my friends, that God has opened your eyes,
and that you have better thoughts of God,
than that he has set you a work and a labour to do, and by his eternal power and decree,
has ordained that you should never do it, but damn you after all.
Consider, there are men and women in bondage and captivity,
and God has sent his Son into the world to redeem them from all iniquity,
and turn them from their evil ways; we are not turned, what is the reason of it?
I beseech you in the love of God, be serious in this matter; serious you must be,
one time or other; when you come to the tribunal of God, there must be a reason given,
or if not, you must be speechless; therefore find it out here.
What is the reason that I am not turned from my evil ways,
since God has sent his Son Jesus to do it, and given him power to do it;
why then is it not done?

Some persons upon inquiry, and after their search, have brought forth this reason:
They have alleged the great power the devil has: The devil is so strong,
and has such a power to darken their minds, and enchant their affections;
he injects and brings things into their minds before they are aware of it.
I confess this, and I will say a little to it,
I will confess as much as the argument will bear, that the devil has great power,
and a way of injecting things into the spirits and affections of people:
He is God`'s enemy and ours too, and he lies in wait,
and will do as much as he can against us, that no one shall get to Heaven;
if we come there, it shall be against his will:
I have heard some magnify the devil`'s power to such a degree,
that he has such power over a man or woman,
that he is able to keep them in sin all their life,
though God has put forth the exceeding greatness of his power for their redemption:
This is hard to believe, that the devil is stronger than Christ Jesus: Well,
as great as his power is, we are in a capacity of knowing a greater power;
the apostle did comfort the Christians,
notwithstanding all the power the devil used with them to defile them,
and keep them from inheriting the kingdom of God, 1 John 1:4. "`You are of God,
little children, and have overcome, because greater is he that is in you,
than he that is in the world.`"
I would have you believe this; I do believe it heartily,
the devil only "`rules in the hearts of the children of
disobedience;`" and he that has the Holy Spirit in him,
has one greater than he that is in the world: If you believe this,
then the question is thus far answered, that we have a Saviour, a Deliverer,
that is more able to redeem us, than the devil is to keep us in bondage:
I hope we are pretty well, now we know we have a keeper:
We are assaulted with the devil`'s temptations, and they are powerful; how powerful?
He has so much power,
as he finds in us an inclination to yield and join with his temptations:
If he comes with a temptation to a man or woman that
has no inclination to that thing he tempts them to;
if they hate that thing, then there is an end of it: The devil`'s power lies in this,
when he brings a temptation that I have an inclination to, then he has a party within me;
if that be rooted out, what signifies his power, let him bring ever so many temptations?

There are many of you that understand what I say;
if a temptation comes to a man to commit an act of uncleanness, if he be a chaste man,
there is no inclination in him to yield to it, or join to it, he hates it,
it is an abomination in itself, and grievous and provoking to God, if he does it;
a man abhors it, then what powerful temptation is it?
If it light upon a man of an unclean mind, that is defiled in his heart,
he has not only the devil, but his own lust and corrupt inclination to contend with;
but if a man believes in Christ, he relies upon him, and he will say, Lord,
you see I am under temptation; here is a great and powerful temptation,
I can never withstand it, but I trust in your name and power,
do arise and deliver me from it: Thus when God does arise, his enemies will be scattered;
though the devil`'s power be great, yet there is a deliverer that is stronger than he:
The reason of mens being overcome, does not lie in the greatness of the devil`'s power,
but in the frailty of our nature.

Some will say, that our natures are so frail, weak and depraved,
that we can do nothing as we ought to do; this is given for another reason,
and there is truth in it, but that truth is but a delusion;
they would excuse themselves when they have yielded to a temptation, I am weak and frail,
I cannot resist the devil; though the devil is not stronger than Christ,
yet he is stronger than I, he works with all his might, power,
and subtlety to deceive me, and ensnare me, and overcome me; I am a poor, frail creature,
therefore I must yield to him: This is a carnal reason;
as though I were to grapple with the devil in my own strength, and to deliver my soul,
as if God has lest me to myself: If you say, Lord,
you have set me to grapple with the devil, and to withstand his temptations,
Lord I am not able to do it myself; God will answer you,
I have laid help upon one that is mighty, that is able to save to the uttermost,
all that come unto me by him;
so that you are not to overcome the devil by your own power and ability:
If any man reason thus, his reason is out of doors; for we are saved by Christ,
therefore I cannot plead my own frailty,
seeing God has provided a rock for my defence that is stronger and higher than I,
that I may trust and rely upon.

So that you see the frailties of our nature is not a sufficient reason,
we must seek further for it yet; and when we come to search narrowly,
and to the bottom of our hearts, I will tell you here it rests;
it has its centre in the perverseness of the will that is in man,
that is contrary to the will of God; it is the opposition of our will to the will of God;
we may talk what we will of salvation and Christianity, that we have a mind to be saved,
and go unto God when we die, and to enjoy the happiness of Heaven to eternity:
We may talk thus; but as long as the perverseness of the will continues,
I am the cause of my own ruin; if I grow in a profession, this perverse will,
will grow up with me under that profession, and under any profession;
change your judgment and opinion as often as you wish, this will go along with you;
the reason and the bottom of things will come to this, none can overcome the devil,
nor be a disciple of Christ, without a daily cross.
When people come to this, to see a necessity of taking up the cross of Christ,
and denying themselves; when it comes to this, there are such shifts and evasions,
and arts that men have to cover themselves, to make themselves and others believe,
that such and such a thing is consistent with the will of God, and that they may do it,
and save their own souls; but they boast of their own deceit,
and are glad that they can make a shift to deceive their own souls;
so that there is no hopes of their ever being purged and cleansed,
and of having any holy work brought forth by them;
but when a man comes to be sensible of his spiritual condition,
and is sincere and honest, he will be ready to say unto God,
if I be deceived in anything, open my eyes.
Lord, if I indulge myself in anything that has a contrariety to your holy will, Lord,
I beseech you discover it to me; such a man will lay aside his own will,
if it be contrary to God`'s will:
Now here is one that is a very fit object for Christ to work upon;
he will not be long before he be savingly convinced.
When a man comes to the word, he is convinced of such an evil in his conscience,
where nobody but God and himself were privy to it, or had any knowledge of it.
It is discovered that he lives in such a practice as is contrary to the mind of God.
God has convinced you, that you love it, and live in it,
and if you will but break off that evil practice,
that he has sent his Son Jesus Christ to turn you from every evil way,
and to redeem you from all iniquity.

This truth has a savour in it; and if you are sincere and upright,
there is nothing for you to say or do,
but to set yourself against everything that is contrary to the mind of God,
and you will have light from Heaven sent to guide you and direct you in your way there;
if you will but receive that grace that is freely
given of God unto you through Jesus Christ,
he will certainly purge you and cleanse you from your sin,
and turn you from every evil way,
notwithstanding the perverseness of your own will and the power of Satan;
and he will work in your heart by his grace,
till it has brought you off from your iniquity, and wrought iniquity out of you,
and so bring forth a holy work to God.

"`Without faith it is impossible to please God:`" We cannot please God without faith,
nor with it neither, unless it be the gift of God.
There is a great deal of faith in this nation, and in this city;
but do you believe all their ways are pleasing to God?
We must distinguish of faith here; the apostle would give a description of saving faith,
he tells you, that it is the operation of God; if I have not that operation,
and a regard to it, how can I have that working?
But since it is the dispensation of the gospel of Christ, and design of Christ,
to turn people to the operation of God in their own hearts,
we would have them believe it.

If there be a drunkard or a profane person, if God work faith in his heart,
he will be convinced and say, what a stroke has the Lord given upon my conscience,
and he will see it is the Lord`'s work: Then believe, whoever you are,
and lay hold of this, for this is the operation of God upon a believing soul,
the stroke of God`'s hand and the power of God, and then you have the work of faith,
by which faith you are enabled to keep yourself from that thing that God smote you for,
and before he gives you over,
the same hour you will find the same hand smiting you for another sin;
this will be like fire in your bones, kindling up your zeal and hatred against your sin,
and will kindle in you a high fire of love to God,
that has not let you lie in your misery, but minded your condition,
and had compassion on you: This love God will shed abroad,
which will run over your heart, he has shed abroad his love, says the apostle, Rom. 5,
upon our hearts by the Holy Spirit, to constrain us to yield obedience;
when you fall into the way of says, which is the operation of God,
the devil comes and knocks and bounces on this side and that,
but God will not fail to give you power to withstand temptation.

The Lord Jesus Christ works in people`'s hearts,
to turn them from the evil of their ways,
that so he may bring forth holiness and righteousness,
and redeem a people from under the bondage of sin,
and fit them for the kingdom of his Father, and to use the apostle`'s words,
present them before the throne of God, without spot and blameless; he will purify them,
and sprinkle them from an evil conscience; their bodies being washed with pure water,
he will sanctify the creature; his word is near them, and in their hearts,
he begins a work in many, and will carry it on in one, and in another.

Here lies the chief work, it is the good hand of God must work all our works in us,
and for us, according to the good pleasure of his will:
Work in you a willingness to bear the cross of Christ, and to deny yourselves;
he will operate for you for this purpose, therefore you must commit yourselves to him.

It is not our preaching which will convert men to God,
but it is the work of God that is pure, which converts the soul to God,
and that cleanses, fits and prepares it for the kingdom of Heaven, Ps. 19:7.
We must come to the word of God, that will convince us, reprove us,
strengthen, encourage and illuminate us,
and do in us and for us all that we stand in need of:
To him be all the praise that works all in you,
and prepares you to be a peculiar people to himself.
The word of his grace I commit to you all, take heed of doing anything contrary to it;
if you do, that which would be your comfort, will be your condemnation.

=== His Prayer After Sermon

Blessed God, and Father of Life! you are glorious in holiness, infinite in power,
the eternal God; your dominion is an everlasting dominion, your kingdom is without end.

O Lord! we bless and praise your glorious name,
that you have made known yourself among the sons and daughters of men;
you have revealed to us in your word the manner of your kingdom among us,
in setting up righteousness and truth, and throwing down iniquity.

Powerful God of Life! subject the minds and hearts
of all your people to your divine power and pleasure,
and let the dread of yourself rest upon our spirits,
that everyone of us may fear to sin against you, and to do despite to your Spirit,
the Spirit of your grace, that we may everyone of us turn from our iniquities,
the evil of our hearts and ways, that we may praise you in the land of the living,
and may become faithful witnesses of that salvation which you have wrought for us,
and for all them that believe.

Powerful God of Life! the souls of your people which you have gathered out of the world,
do praise and magnify your name for what they have seen, and for what you have wrought;
you have wonderfully appeared in your love, and brought salvation near,
and gathered many into it, it is become a wall and a bulwark to them,
that they are defended from the evil one, and from the evils of the world.

O dearest God of Life! raise up poor and needy souls out of the dust,
that they may serve you, and obey you, and do your will,
and show forth your power and strength in their weakness and infirmity,
that they may trust in you, and rely upon you in the time of their distress.

Blessed Father of Life and Power! give grace to the humble and meek,
and teach them in your way.
We have had experience, O Lord! of your fulfilling your promises;
you are still fulfilling of them to all that truly wait upon you;
you have begun a good work, carry it on to the praise and exaltation of your great name.

Blessed Father! reveal your power more and more in the nations round about,
that they that long after the life of the Living God, may come and find you,
and behold your divine appearance, through the Son of your Love, in their own spirits,
that so they may receive your word, and your word may quicken them,
that they may stand up from the dead, and live; for it is the living, the living,
O Lord! that praise you, that honour your name, that offer praise, and glorify you.

O blessed Father of Life! carry on your great work with power throughout all the earth;
gather a remnant of your seed that are scattered,
and bring them home into the kingdom of your dear Son, that we may praise you together,
and rejoice in your name.

Dear Father! you have saved this nation, the land of our nativity, to this day,
by a wonderful power, by your powerful arm;
our souls are deeply sensible of the stretching forth of
your Almighty Hand in our preservation at this day;
so Living Father! if it be your heavenly pleasure, lengthen forth our tranquillity,
and the enjoyments of your mercy and goodness to the inhabitants thereof,
that they may learn to fear you, and turn to you with their whole hearts, and break off,
by true repentance, from all those sins that grieve your Holy Spirit; that so,
Living Father of Life! they may come to walk in love
and in union with your heavenly power,
and have concord one with another,
and show forth the power of your grace manifested to them,
and magnify your love and power,
and give you honour and renown for that great salvation that you have wrought for them;
that so your great name may be exalted,
and your will may be done on earth as it is in Heaven;
that the souls of your people may be refreshed with your love,
and the joys of your presence, and the revelation of your heavenly power; for this,
we offer up to you living praises, and Christian thanksgivings,
in and through the Lord Jesus Christ; for you are worthy of all praise, and glory,
and dominion, forever, and ever.
Amen.
