== Sermon XXIII. Christ the Way, the Truth, and the Life.

Preached at Grace-Church-Street, April 18, 1687.

I fear the high places are not taken away; it has been so in all ages,
and it is manifestly so in this day;
where the heart is not rightly prepared for the Lord,
there the high places are not taken away:
For all the high places in the time of Israel`'s idolatry,
they were ever set up when they departed from the Lord,
and all the high places now they are up in a time of ignorance of God;
when people have forgotten the Lord, then they exalt themselves, then pride,
and arrogance, and every evil way prevails upon us;
but when men come to seek the Lord with uprightness,
that brings down their high conceits, that brings everyone into humility;
for everyone comes to be convinced in themselves that none can find the Lord,
but as they are brought to be humble; yes, indeed, none seek after him aright but such,
none have the promise of finding him but the humble.

Therefore it is the duty of everyone that is a real inquirer and seeker after God,
to know the right preparation of mind, to know themselves in such a frame of spirit,
that they may seek in hope,
that they may have a right and just expectation of
finding him whom they are seeking after;
for this has been the reason that a great many have been frustrated in their endeavours,
and in their purposes of seeking after the Lord,
they have not been rightly prepared for him to manifest himself unto them,
they have not known the preparation of his sanctuary;
there was a peculiar preparation that was requisite
to those that drew near unto the sanctuary of God,
they were hallowed, that is, made holy, before they drew near to the holy place;
but alas! this has been greatly neglected in our days,
unholy people with unholy minds have been seeking after the Holy God,
they have been inquiring after a holy way, and were not prepared to walk in it,
there was nothing raised in their minds, that was fit to walk in that way.

For so long as men or women stand in unity with their lusts and concupiscence,
with the spirit of this world, and the way of it,
they are not capable of receiving that which should lead them into the way of holiness;
no, if it appears to them, they cannot receive it,
for it is with them as with other guests, there be other lovers already let in,
which employ the powers and faculties of their souls, so that if the most beloved of all,
the most excellent, if the "`chiefest of ten thousand`" do appear,
they cannot see a comeliness in him.
The prophet speaking of this state and condition of men,
did prophesy concerning our Lord Jesus Christ,
"`when we shall see him there is no comeliness in him why we should
desire him,`" and so it has happened to a great many now-a-days,
though the truth has appeared to them,
yet they have not looked upon it as a pleasant way, as a way desirable,
but a way to be shunned if possible.
What shifts have a great many people made to keep themselves, if possible,
out of the way of truth, arguing for this and that,
and disputing for one way and another that was out of truth`'s way,
out of the way of holiness.
What was the meaning of all their arguments, but to tell us they might be happy,
they might be saved, though they did not come into truth`'s way,
and walk in truth`'s way?
And though they did abide in those things,
that were contrary to the testimony of truth in their own hearts,
yet it might go well with them.

This is the strength of the arguments of all sorts, of all persuasions in the world,
that have been arguing themselves out of the truth,
and would argue us out of the truth too,
and would take the liberty to do those things which are not agreeable therewith;
but now the reason of this is because the preparation is lacking,
they are those that have no need of truth, and that have no need of God,
and of a Saviour; but think they can make shift without them;
he is not become the chiefest to them, they can abide in the high places,
they can "`call upon the name of the Lord,`" and they can worship in the groves,
and in the high places both together,
like those nations that were brought to inhabit the kingdom
of Israel when the ten tribes were carried away,
they sent for priests to teach them,
they sent back to the king of Assyria to send them some priests,
to teach them to worship the God of their country,
and when the priest came to teach them, he taught them the ceremonies of the law,
and the various observations that the Jews used to practise in that country,
and so they grew into a formality of serving the God of Israel,
they called upon the name of the Lord, and every nation worshipped their own gods.

How is this nation, and the nations of Europe,
now inhabited with such a people that are called by the name of the Lord,
but everyone worshipping their own gods; one makes gold and silver his God,
another makes his pleasure his God, another his honour, another this, that,
and the other lust, and they bow down to them, that is,
they yield themselves to their lusts, concupiscence and corruptions,
that they stand in unity with, but they call upon the name of the Lord too;
they do apply themselves to some kind of form of worship,
which they say is unto the immortal and invisible God;
but alas! they come not to the knowledge of God by this.
All that the priests could do that the king of Assyria sent back,
could not bring the Samaritans to the knowledge of the God of Israel,
they only brought them to a report of such a God, that had set up such a law:
They had the report of it, and for fear that the lions should tear them in pieces,
they would enter into that form, but they worshipped their own gods still.

So it is now, people do not come to the knowledge of the true God, the living God,
by entering into any form of religion; for instance, prayer,
hearing of any ordinance or church-fellowship, these give not men the knowledge of God,
there is but one way to come to that, but one only.
Men have found a great many,
it is past your skill and mine to reckon up the many ways
that men have found out upon the face of the earth,
how they might come to the knowledge of God, and to peace and reconciliation with him;
but they have only played the fool, and spent their time in vain,
especially they that own the scriptures of truth to be a
true and faithful record of the mind and will of God,
they play the fool abominably;
for the scripture that they give so much reputation to in
their profession does testify the way is but one,
and there is no other way for people to be reconciled to God, than by coming into Christ;
to be found in him, to be regenerated and born into his nature,
and have his qualities put upon them, that as he was pure, they may be pure;
that he that sanctifies, and they who are sanctified by him, may become both one,
and so be reconciled to the Father through him.
This you know is the common profession of Christendom, or at least of our nation.
And in other nations, the common profession is, there is no Mediator but one,
no Reconciler but one.
Indeed some others hold there may be other Mediators,
and that there are others that may contribute to them by their mediation,
and by their prayers and merits, but the generality of the nations are otherwise.

Now for people to fall out, and say, my way is best, and your way is not best,
and to fall into contests about many ways,
when the scripture concludes there is but one way, is not well;
we had better all agree about this doctrine,
that there is no possibility of reconciliation with God,
since we are fallen out with him, and since sin has made a separation,
there is no way of being reconciled again to God,
but by and through our Lord Jesus Christ; nor by him neither,
unless we receive of his Spirit to quicken us; nothing can quicken us, enliven us,
or recommend us to God, but the Spirit of Christ operating and working in our hearts,
that he may prepare us for the Father`'s kingdom.

If people would agree upon this, there would be an end of all labour, and toil,
and jangling about the right way, for the consequence and conclusion would be this:
That the man who does not know himself the sanctifying
power of the Spirit of Christ Jesus,
he is out of the way to reconciliation with God,
let his form and profession be what it will: If therefore he be reconciled to God,
it must be by and through the Mediator,
and he will never recommend him to the Father till he has
made him a temple to let in the Spirit of Christ,
to work in his heart, to fit him for the kingdom of God:
And men have no other way to come to it;
for though they be zealous in every prayer and form,
it signifies nothing to any great purpose, their hope will be frustrated;
there is no other way, says Christ, of coming to the Father, but by me; "`I am the way,
the truth and the life`" If I am out of the truth, I am out of the way;
and if I am out of the way, then I cannot come to the end of the way.
This is plain reasoning among men: If I tell a lie, that is out of the truth:
If I have vain communication, or deceive or wrong my neighbour, that is out of the truth;
if I am in that which is manifested in my conscience to be contrary to the truth,
I am out of the way; though I be strict in that way, as to profession,
yet I am out of the way to God, I am out of the truth;
there is no way to God but by Christ, who is the way, the truth and the life;
whoever is out of him, is out of the way; which made the apostle say, that his labour,
endeavour and desire was, that he might be found in Christ,
not having his own righteousness, but having on the righteousness of Christ Jesus.

Many men think to recommend themselves to God by their righteous,
just and honest dealings, and doing wrong to nobody.
This is good in itself, but does not recommend us to God,
unless it be done by the righteous and holy Spirit of Christ Jesus,
unless it be of his working; he must have the working of righteousness and truth in us;
he must plant it, and it must grow by his working, if it be acceptable to the Father;
"`for without me,`" says Christ, "`you can do nothing.`"
A man out of Christ, a stranger to his Spirit, may do something,
but nothing available to the well-being of his soul,
'`till he have reconciliation by Christ Jesus: If he be reconciled to God,
this Mediator must be the Reconciler,
and he must fit and prepare him for reconciliation with the Father.

All the divisions, sorts and sects of religion, must all come to an end;
if this measuring line be laid to them, they all appear too short;
and there is nothing will do a man good,
but that religion that obliges and ties him to the good pleasure of God,
through the Spirit of the Mediator, which he feels working in him,
by which he is raised from death to some degree of life:
When he is sensible what a burden sin is to his life, that godly life which he has,
he is burdened with every sin, and oppressed with every vain thought,
and every vain word, if he be not in some measure quickened,
he is not sensible of this burden; but being quickened,
he is sensible of the burden that lies upon his life, by reason of his sin; and then,
being under the weight of his sin, he calls to God for his assistance;
he cries to God to help him; he now knows that he has striven and laboured in vain.
O God of all grace, if you vouchsafe not help to my soul,
if you do not interpose by the assistance of your grace, I cannot overcome this sin.
There is a continual cry to God for divine assistance,
and as they cry to God for assistance, he ministers assistance to them,
by which they are able to overcome the enemy of their souls,
and all temptations when they come: And when a man finds such divine assistance,
his faith is strengthened and confirmed, and so he fights the good fight of faith,
and at last gets the victory; victory over his sin, and his own lusts, and concupiscence,
and victory over the assaults and temptations of the adversary, and at last he comes,
through the grace of God, to deny all ungodliness and worldly lusts,
and to "`live righteously, soberly and godly in this present world.`"

Now when people do thus, it is by the grace of God.
This life of righteousness, sobriety and godliness,
is not the effect of their labour and exercise, and of their endeavours herein,
but it is the effect of the holy Spirit that has been the teacher.
When you see a man has become a good scholar, eminent in all sorts of learning,
you will conclude he did not attain to all this of himself,
he did not learn this and the other language,
this and the other art and science of himself; no,
he had some judicious and able master and teacher,
who communicated of his learning and knowledge to his disciple and scholar:
This is the efficient cause of his improvement.
Now if a man, by the grace and the Spirit of God, and the teachings of it, live a holy,
godly life, this is the effect of something; he did not always live such a life,
how comes he to live such a life now?
Is it by his own industry, labour and exercise?
No, it is by being exercised, taught and led by the Spirit of God;
so that it is the effect of the grace of God that he should live such a holy life,
this is the meritorious cause of it, as he is a creature,
and by this only acceptable to God in Christ the Mediator.

Thus a man comes to be justified and accepted, not because he is a godly man,
but is made so by the Spirit of God: "`You are not under the law,`" says the apostle,
"`but under grace:`" You are under the teachings of it, under the directions of it:
Grace can reprove people; for that grace and that truth that comes by Christ,
and manifests itself as a light in the hearts of transgressors, reproves their sin,
and calls them out of it; it reproves them for it, and exhorts them to leave it,
both at one time; so that we must acknowledge all our righteousness,
holiness and obedience to be of God, and all that we do in order thereunto,
as it is done by the teaching,
by the influence and operation of the grace of God given us in Christ Jesus;
it is the effect of him who is our Mediator, he works it in us, and for us,
of his good pleasure.

If we be justified, we are not justified for a righteous, holy life,
and for our obedience; but we are justified through Christ,
who works a godly life in them that believe,
so that a man is not justified by any other way or means;
and all other ways a man takes of being reconciled to God, are vain and fruitless,
and have been spoken against by all that were moved by the Holy Spirit in the New Testament.
Says the prophet, with what shall I come before the Lord?
I am fallen under death and sin, and in a separation from God,
I would readily be reconciled to him; what shall I do to be reconciled to God?
He goes about to reckon without Christ, and without faith and holiness.
Shall I take a thousand rams, and ten thousand rivers of oil?
Shall I come nearer still?
Shall I make an offering of the fruit of my body, for the sin of my soul?
Shall I offer my first-born to God,
that I may not be rejected and brought to a separation from him?
Thus men when they come to be sensible,
do feel in themselves that all this is to no purpose: The answer comes, you may live,
but all your contrivances about making an offering are vain:
He has showed you O man! what to do.
It is not your finding this way and that way, namely, your rams, and your oil,
and your first-born;
it is no way of your devising and imagining that can reconcile you to me,
I have showed you, O man, what is good.
What is this that is showed?
It is comprised in a short compass, it is "`to love mercy, to do justice,
and to walk humbly with your God.`"
Will this serve without offering rams and oil, and offering my first born?
This will do if you can but "`love mercy`" when it is shown you; that is, embrace mercy,
and love it.
He has showed mercy to all men; then love it and receive it;
"`do justly,`" leave everything that is unrighteous,
and do that which is just in the sight of God,
but do not boast of your justice and righteousness,
but "`walk humbly with your God;`" here is the whole duty of man.
Here is no dependence on dead works, or my own exertions, in order to my justification.

Indeed the consideration of these kind of lessons do corrupt some men,
and put them upon doing this or that, and upon forbearing this or that,
and has brought many to confession and great abstinence, and put them upon great doings,
thinking this would answer the justice of God; I have loved mercy,
and given all I had to the poor.
If I do justly, and abstain from this and the other liberty, if I walk humbly, that is,
if I humble myself by this and the other manner of penance and contrition,
then I do what God requires, and then I have pleased God.

Now all that have gone this way to work, to do justly, and love mercy,
and to make themselves humble, and humbled themselves in such a low manner,
they have missed the mark.
"`He has showed you,
O man! what is good;`" that it is impossible for fallen man to answer this himself;
he may be convinced of his duty to do justice,
but by his own power and strength he cannot do it;
there are so many temptations from without, and so many from within,
such a propensity in nature,
that will prevail against all the bonds of charity that he can make.

Therefore is help laid upon one that is mighty;
without the grace of God that comes by Christ Jesus, a man can never do right,
though convinced: Though the Lord has showed him what is good,
he shows us that we are unable of ourselves; he has taken care to send his Son:
God has so loved the world, that he has sent his Son into the world,
that he might help those that have need of help,
that everyone that is in distress might have an eye to Christ,
the author and finisher of their faith;
when men have a reference to their faith in Christ, this makes their duty acceptable;
I cannot do it except the Lord strengthen me;
therefore I will have respect to the Mediator, Christ Jesus,
who was sent for a light into the world.
God sends forth his grace for everyone to lay hold on, who generally believe,
that though they are unable to do what God requires, yet he will enable them to do it;
"`for as many as received him,
to them he gave power to become the Sons of God,`"
though they were the devil`'s children before;
he is the same yesterday, today, and forever.
He abides always the same in his grace to men, he is in his operation to them the same;
he offers grace to them that are in a frame of mind to receive it;
they may know that his power will give them ability,
and that whatever they do of themselves will prove fruitless,
because it is not done in Christ`'s name and power, and so not acceptable to God.

The greatest thing that we are to be concerned about, if we will be religious,
and concern ourselves about divine matters,
about the kingdom of God and the world to come, is,
to see what frame of mind we are in at present, whether the high places are taken away,
whether we are not exalted in our own conceits of knowledge and wisdom,
and reckon not to be beholden to him for his grace.
If we be highly conceited, and think we can stand upon our own legs,
the high places are not taken away:
Men are not in this state prepared to seek the God of their fathers; therefore,
let everyone turn to God, and see how it is with you;
see whether there be a mind brought low enough to be subject to Christ,
and to the gracious teachings of his Spirit.

A man may say, I can make a sermon, I can make a prayer and exhortation,
and I can make a book, and send it abroad,
I can do all this by my own parts and abilities; so you may,
and may make it all full of good words, but you can never make it acceptable to God;
for "`without me,`" says Christ, "`you can do nothing.`"
You must have the assistance of the Spirit of Christ,
else you can not make a good prayer, nor a good book, nor anything good;
God esteems the very plowing of the wicked to be an abomination to him.
Where the mind is not exercised by the Spirit of God,
if he should pray from morning to night, and spend all his days in penance,
it will do him no good.
"`If I,`" says David, "`regard iniquity;`" you may think I am a man in favour with God,
a man after God`'s own heart; yet if I regard iniquity in my heart,
the Lord will not hear my prayer.
What signifies prayers and sermons, made of good words,
if they come not from a heart separate from iniquity?
If it be not so, it will do no good at all, in point of acceptance with God.

O let the fear of the Lord enter upon every heart!
wait all to feel the Divine Power of the Lord,
that brings down every high thought,
that so you may look to the preparation of your hearts, that is a right preparation;
when the people are so low, so broken and so tender,
that they are nothing in their own eyes, but what the Lord will make them to be;
then they are as clay in the hands of the potter, they are fashioned by his hands,
and made the workmanship of God in Christ Jesus,
the "`one Mediator between God and man.`"
They must bear the likeness of Christ Jesus, bear his Heavenly image,
they must have his qualities, and have the same mind in them that was in him:
"`I do always that which pleases my Father,`" says the Lord Jesus Christ.
Indeed he has the doing of things in the hearts of men, and God is pleased with him,
and where men have the doing of them themselves,
they are thrown back as dung in their faces; where any rightly desire justification,
where men have a right preparation of heart, so to seek the God of their fathers,
as to find him and be accepted of him, it is through Jesus Christ,
in whom he is well pleased.

In all your assemblies, prayers, exercises and meditations,
you must be separated and drawn off from your former lovers,
and you must be joined to him that God has sent to be a leader and a guide unto you,
then you will find daily his assistance; and as you have assistance from him,
you will find acceptance with God, and he will show you the Father, and that,
and nothing else, will satisfy the soul hungering and thirsting after God.
"`Show us the Father, and it suffices us.`"
So when Christ, the Mediator, comes to have wrought so far as the purifying of the soul,
and the sanctifying thereof, and thereby fitted it for his glory,
such holy souls shall behold his glory; "`for the Lord will give grace and glory,
and no good thing will he withhold from them that walk uprightly.`"

That you may be brought to this state, and kept and preserved in it;
that the Heavens may rain down fatness upon you,
and that you may feel the living virtues that flow from Christ to every member,
is the labour and travel of the servants of God, for their own souls,
and the souls of others that are in unity and fellowship with the Holy Spirit.
