== Sermon XXIV. Captive Sinners Set Free by Jesus Christ.

Preached at Devonshire-House, April 29, 1688.

There is nothing will make people live to God, but that which they receive from God.
For as all men are by nature in a state of death,
so there must be something beyond nature to make them alive again;
and this is what everyone ought to wait upon God for,
that you may feel something that is supernatural,
and that you may be acquainted with God`'s gift; the gift of God, says the scripture,
is eternal life.
Many find a life in this world, that is not the gift of God.
The life that people have in sin, it is not the gift of God;
the delights and pleasures of this world are become a life unto them.
The world is that to which everyone must die; they that are not dead to that,
they all live to themselves, they do not live to God, for none can live to God,
but by the life that comes from him.
That which people receive of man, gathers them unto man; that which they receive of God,
carries them to God.

So men have made gatherings, and have communicated of what they have to one another,
and by virtue thereof, have made them a people: Many men have gathered many people,
many churches, and they live to them that gathered them; they do not live to God,
for lack of receiving something from God,
but all they that come to receive the gift of God, they die to the world,
and they come to live such a life as the world does not love, does not care for,
and has no pleasure in: If you were of the world, says Christ, the world would love you;
but because you are not of the world, they hate you.
How should this be understood, were not they some of the men of that generation?
How does he mean they were not of the world?
Why, I have taken you out of it, says he; and yet they were there still,
and they were named by certain names, the sons of such and such men; yet for all that,
they were not of the world; and that which differed in them was,
being made partakers of that life which the world knew not.

And so there will be an enmity in the world against the life of holiness;
they will hate anybody that lives in it; and as it was then, so it is at this day,
they that are of the world, they hear and receive those things that are of the world,
from the men of this world; but they that are of God, they hear them that are of God,
and they receive the things of God,
and their greatest comfort and joy that they have
is in their communion with God in Christ Jesus,
through whom, as through a conduit, the blessings of the father are ministered to them,
and through whom, as from the fountain of life, their life is renewed from day to day.

But these things are hid from the world, from the wise and prudent of it;
they cannot dig into the depth, nor ascend to this height;
they cannot comprehend the length and the breadth of the things of God,
which are in Christ Jesus; they may reach unto something of the love of God,
that is in the creation; they can tell when the sun shines upon them,
and when the rain falls upon their fields;
and when it falls in due season they call it a blessing;
and while the covenant with winter and summer remains, they look upon it as comfortable,
and perhaps sometimes will bestow a saying, "`I thank God for it.`"
All these things are beneath us, and there is neither love nor hatred known by them all.
I saw the wicked, says one, I beheld his dwelling place,
and he flourished like unto a green bay-tree, and was wicked still,
notwithstanding all this.

But now, they that see where they live, that live to God, they can say,
that their leaf never withers, but they bring forth their fruit in due season;
but he did not so.
But the wicked man that flourished like a green bay-tree, behold I looked,
and he was removed, and his place was no more to be found:
There came a blasting upon all his blessing and his flourishing came to an end;
his riches perished, and his good things passed away from him.
But the man whose delight is in the law of God,
and makes it his pleasure both night and day,
he is like a tree planted by the rivers of water, whose leaf never fades,
and brings forth his fruit in due season.

But this is hid; there is no body in the world but would have something of this life too;
they would be sure of eternal life, but they would not die to the other life,
they would not be crucified to the world, they would not be separated from their lovers;
if they could get into the state of a righteous man, an hour or two before they die,
when they are sure they shall die, it would please them;
but to live that life that is to God, is to die to the world,
and to part with that they have, their comfort, their joy, their peace and honour,
and all their worldly enjoyments in it, before they can come to receive the gift of God,
they think is hard: But they that look after it, and have a mind to find it out,
without parting with the world`'s life, they deceive themselves.

Do not you see how men have deceived themselves in these days?
They have sought after the kingdom of God till they are scattered in their own way;
they are quarrelling about their own way,
as if they never had any scripture to be their rule:
They cry the scripture is their rule; this is the way to eternal life, says one;
and this is the way, says another;
and the one and the other say all these ways are false saving their own;
and all these contenders about the way to eternal life,
they all say the scripture is the rule.

And yet the scriptures speak of the way too, and tell us the way plainly,
the way to rest, peace and life eternal.
If the scriptures had been silent in it,
and had said nothing but of genealogies and histories of armies and wars,
it had been something;
but the scriptures of the Old and New Testament speak of a certain way to eternal life,
and say it is the way of holiness,
a way shall be cast up for the redeemed and the ransomed of the Lord to walk in,
and the wayfaring man, though a fool, shall not mistake in it.
Though he never took a degree at the university, he shall not err in it;
though he be a fool in the account of the world, and never understood Greek or Latin,
yet he shall not err in this way.

The way that leads to the kingdom of God, is called the way of holiness;
but while many have been reading in their books,
they have been contending for a way of unholiness;
no wonder then they have been quarrelling about it, and have all missed it,
and that in the main point of all: Let them make a way, which way they will,
and frame it ever so wisely, according to the best wit they have,
be it a way that has all material qualifications that should make it a way of holiness,
these men may walk in it, but they will never find the way to the kingdom of God,
though they have sought it out: Go to one place and another place,
and ask them what is your way?
Our way, say they, is the right way,
the most sure and certain way that can be found for people to walk in:
But where will it lead me?
It will lead you to the kingdom of God: That is it I would have;
but will it lead me to holiness?
No, never in this world, you must never come to holiness; do the best you can do here,
it is but sin; the best day`'s work you make is but sin;
the best child of God on earth cannot live a day without sin:
Do you hold out that in your way?
Yes; then I have done with that, and must go to another people.

So many have gone many ways to the kingdom of God, and when the upshot is come,
they have found every way a polluted way, a sinful way;
I know this way will never lead me to God; sin first led me from God;
I had been well enough as I was created at first, if I had never sinned against God;
a sinful way will lead me from God.
It is against common sense, and against rationality,
to say we did first go from God by sin, and must go to God again by a sinful way.
Who will believe that such a way will lead men to God`'s kingdom?
and that any way will lead men to God, that will not lead them to holiness?

The Psalmist says,
"`if I regard iniquity in my heart the Lord will
not hear me;`" though a man keeps close to meeting,
and ordinances, and duties, and performances, iniquity it seems remains still;
there is no rooting it out in this world.
This continuing and remaining with a man, makes all his performances, and duties,
and prayers unacceptable to God; they are all turned back again upon him,
and cast as dung upon his face, and true enough too;
so that here is no coming unto God in this way;
the comers thereunto know well enough they are not reconciled to God,
if they are men that are conscientious.

There are a sort of people so stupid and sordid in their judgment,
that if a man tells them they are reconciled to God,
they will believe him though conscience reproves them a hundred times a day.
If the parson of the parish say,
that he has made this child an heir of the kingdom
of God and an inheritor of eternal life;
I know some have believed it forty years after,
and have born themselves up upon this man`'s word all their life:
Do you think there is any danger of me,
that in baptism was made an inheritor of eternal life, and an heir of the kingdom of God?
God has not appointed ordinances in his church for nothing.

I speak not of such sordid hard-hearted people,
that never entered into themselves to know how it was with them,
whether they are converted; but I speak of sober conscientious people,
that do not desire to be cheated in a point of salvation,
though they have been deceived a great while, they may be undeceived:
Then they must take this for certain doctrine,
that nothing can reconcile them to their Maker but that which takes away sin.
God hears not sinners, he will never be reconciled to a man in this world, as a sinner;
but there are many thousands (blessed be God) in this age, as well as in other ages,
that were sinners, and reconciled to God through Christ, and had remission of sin;
but never any man in his sin was reconciled to God, though he did believe the truth,
if he did not come to the sanctification of the spirit,
he could never be reconciled to God.

So that there has been, in all ages,
a way of the working of the Spirit of God in the hearts of them that believe,
to prepare them for the sinless kingdom, for that glorious kingdom,
into which nothing that hurts, defiles or corrupts, can enter.
And because we cannot enter with corruption and defilement,
he has appointed the ministration of his Spirit to work
out that which might hinder the cleansing of us from sin,
that we might have an abundant entrance into his glorious kingdom;
so that while they say there is an impossibility of living without sin,
I had as lies they had said,
there is an impossibility of entering into the kingdom of God;
for never any shall come into the kingdom of God, but those that are without sin;
for there is no purgatory after death.

The Papists have a better conceit than the Protestants in that respect:
The Protestants conceive sin to be expelled at the point of death; and they say,
all the sins of believers, all the guilt of sin, after we are believers, is pardoned,
forgiven and done away, by the death of Christ upon the cross; we will have it,
if we can get it.
If men can imagine a way into the kingdom of God, they will have one.
They believe that a man may sin and contract no guilt;
and that he may sin till his dying day, and then all sin shall pass away,
and he shall enter into God`'s kingdom.
The Papists say none can come to Heaven till they be purged from sin;
and they say God has appointed a place for that purpose,
and persons must go into purgatory, and they must lie there till they are purged,
and purified, and fitted for Heaven.
Now, say the Protestants, truly; there is no such thing,
we find no such thing mentioned in the scripture,
therefore such a thing as this cannot be; for the apostle said,
we have declared to you the whole counsel of God,
and he speaks not a word of purgatory in all the New Testament.
The Protestants have got a way to help themselves, and the Papists, also,
to help themselves, and both lie under danger: As for the Papists,
if their priests mistake, and there be no such place as purgatory,
then they must be brought back to the doctrine of the scripture, which declares,
that as death leaves us, so judgment shall find us; and as we sow so we must reap;
if we sow to the flesh, then of the flesh we shall reap corruption.
Then the Protestants, likewise, if they mistake in saying,
a man may act sin and yet contract no guilt,
then they must be brought back to the doctrine of the scriptures, that tell us,
the soul that sins must die: "`If a righteous man forsake his righteousness,
and does that which is evil, his righteousness shall be remembered no more,
but in the sin that he has committed he shall die.`"

This is sound doctrine:
I had rather trust the doctrine of the prophets and
apostles than the doctrine of all others,
either Protestants or Papists; and had rather depend upon their doctrine for salvation,
that were inspired by the Holy Spirit, than upon those doctrines that say,
there is no inspiration now-a-days.
Some conceive this scripture may be interpreted thus and thus;
and others conceive it means so and so, but we must, say they, submit to better judgment:
I am a fallible man, I submit it to better judgments.
Now when people are concerned for immortality and eternity,
to have such things dished out in such a manner,
what souls are so dull but they would bestir themselves,
and consider and look about them before they go from here,
and how it shall go with them when they are gone?

We are now to work out our own salvation, that is on our part:
None ever have wrought out this salvation, it is wrought out on God`'s part already,
and it is to be made ours; he that is our Saviour, he has suffered for our sins,
and rose again for our justification; he was made to us, of God, wisdom, righteousness,
sanctification, and redemption.
Now wisdom signifies the opening of the counsel of God;
righteousness signifies the subjection of our wills to the will of God;
sanctification signifies obedience to the Spirit of Christ.
Sanctification signifies obedience to something; to what?
what shall we be obedient unto?
what is our rule?
He that is led by the Spirit of Christ, he is his;
but he that is not led by the Spirit of Christ is none of his; so that it is plain,
sanctification signifies obedience to the Spirit of Christ,
and redemption signifies buying again, or setting free from bondage.

We know when our friends are in captivity, as in Turkey, or elsewhere,
we pay down our money for their redemption;
but we will not pay our money if they be kept in their fetters still.
Would not anyone think himself cheated, to pay so much money for their redemption,
and the bargain be made so that he shall be said to be redeemed,
and be called a redeemed captive, but he must wear his fetters still?
How long?
as long as he has a day to live.

This is for bodies; but now I am speaking of souls, Christ must be made to me redemption,
and rescue me from captivity.
Amos 1 prisoner anywhere?
Yes; verily, verily, he that commits sin, says Christ, he is a servant of sin,
he is a slave to sin: If you have sinned, you are a slave, a captive,
that must be redeemed out of captivity; who will pay a price for me?
I am poor, I have nothing, I cannot redeem myself, who will pay a price for me?
There is one come, who has paid a price for me; that is well, that is good news,
then I hope I shall come out of my captivity.
What is his name, is he called a Redeemer?
So then I do expect the benefit of my redemption, and that I shall go out of my captivity.
No, say they, you must abide in sin, as long as you live:
What benefit then have I by my redemption?
I could have been in captivity no longer; if I had not been redeemed,
I must wear my shackles and fetters still, and be subject to my old master and patron,
and when he will have me be drunk, I must be drunk; and when he will have me be unclean,
I must be unclean.

Thus many professed Christians there be (you see it with your eyes)
that will tell you they believe all the articles of the creed,
and they have been baptized into the Christian faith,
and can rehearse all the principles of the Christian religion,
and perform the duty of Christians in going to church, saying their prayers,
and giving alms too it may be; they are such as would be called Christians,
they would be called so, yet they are not redeemed from their vain conducts;
for what makes their shackles and fetters about them?
When their old master bids them be drunk, they will be drunk;
and when he bids them commit whoredom, or lie, or cheat their neighbour, they will do it:
You do believe the devil leads you to this;
you will not say the Spirit of God led you to it.
If one demand, how did you do it?
You say, the devil prevailed upon me: What,
has the devil power over men after they are redeemed?
What sort of redemption is this?
Then comes in the old shift again, we are redeemed from the punishment of our sin,
but not from the act of it.

Now if those that are called ranters had told me this tale, it had been like them;
but when doctors of divinity tell us this tale, it is so unlike divinity,
that it is carnal, sensual and devilish.
To tell believers they are redeemed from the punishment of sin,
but not from the act of sin;
that this is the benefit which we receive from Christ`'s sufferings; that we may sin on,
free cost; that there is no guilt contracted by it; will any man or woman,
that understand they have a soul, venture their immortal souls on this divinity?
I hope not.
They will not venture their soul on this foundation-doctrine:
I hope God will awaken the consciences of people,
that they will not hazard their souls upon such a carnal, devilish foundation;
that if the devil should preach, he could not preach a worse doctrine than this,
to persuade Christians they may live in sin, and sin will not hurt them,
nor impair or break their peace with God, and reconciliation with him.

I will tell you how it has been with me; in my childhood, if I had spoken a vain word,
or a false word, I had contracted such a guilt thereby,
that I was ashamed to draw near to God, to pray to him; I knew he would not hear liars,
I knew there was no way to be accepted without repentance and amendment of life.
I believe others have met with the same dealing from God,
by the secret strokes of conviction that have come upon their hearts,
when they have sinned against God.

So that I am still of the mind, that the persons that depend upon this kind of doctrine,
do at sometimes, especially when sickness comes, and death looks them in the face,
or in times of common contagion or pestilence,
at such a time they have a weight of guilt upon their consciences;
for this doctrine will not support them at death,
but that then they believe they have contracted guilt, or committed sin.

I have wished many times that the Lord would open the eyes
and hearts of the people of this city and of this nation,
to see how miserably they have ventured their souls.
Will merchants in this city ever venture their goods
at such a rate as men commonly venture their souls?
What, will they venture their goods in a ship without a bottom, before she goes to sea?
Now this doctrine has not a foundation;
shall I believe a person that tells me I do not contract guilt,
when I feel it upon my heart; when I commit whoredom and drunkenness,
and cheat my neighbours, shall anyone persuade me that I do not contract guilt?

O friends! we are speaking of great matters; it is about eternity, that we are speaking,
it is about the hazard of eternal happiness; therefore I pray, let everyone be serious,
and consider what I say, for I speak in God`'s name, and on your behalf:
Men are to come to a true search in themselves, what a life it is that they live.
Many support themselves by the doctrines and precepts of men,
and they buoy themselves into conceits of salvation;
let them examine whether it be a life that has its support from the Spirit of God;
this is material for everyone to consider.
There are none can live to God, but by the life they receive from God;
"`the grace of God, which brings salvation, has appeared to all men.`"
Now here is a universal doctrine.

There are a sort of men in this city and nation that tell us,
that saving grace is given only to the elect.
Saving grace is given to all men; but you must construe those words, all the elect,
where they are somewhat injurious, and would cast off the condition of the text,
if they make a distinction in the latter part of the sentence,
for it will not be good sense: "`The grace of God that brings salvation,
has appeared to all the elect, teaching us to deny all ungodliness,`" etc.
Here is us taken out of the all.
The same grace, that is our teacher, appears to be the teacher of others,
though they turn it into lasciviousness.
The grace is the same,
though they make many school-distinctions between common and saving grace.
The apostle explains it, by telling what grace he means; the grace of God,
which brings salvation, appears to all men, and that is by teaching us;
what does it teach?
I pray consider it; it teaches us to "`deny all ungodliness and all worldly lusts,
and to live soberly, righteously and godly in this present world.`"
Where is sin now, if a man be taught by this grace, and the dictates of it.
Can a man live in sin, and yet live righteously, soberly and godly too?
Can a man live in sin, and yet deny all ungodliness at the same time?
Where have men`'s understanding been, that cannot understand their mother tongue,
and consider sense?
Where are men`'s understandings that will say,
I may "`deny all ungodliness and worldly lusts,`"
and yet follow the lusts of my own heart?
You would think I speak nonsense if I should speak thus;
and yet we have been put off with such nonsensical stuff as this.
We must pray to God to send his holy Spirit into our hearts, to enable us to live godly,
righteous and sober lives, and at the same time believe that we shall never do it,
but that it is a business of impossibility.

Now when men come to lay these things together,
and when they consider between God and their own souls, how it is with them,
many are amazed to think they should ever be put off with such incongruous, disagreeing,
and dissonant things, that are not consistent with one another.

But do you think it is possible for any man to live without sin?
Yes, or else I would say it is impossible for any to be reconciled to God;
for God will never be reconciled to sinners, as such;
for his bargain and covenant is made of such kind of articles.
"`Wash yourselves, make yourselves clean,
put away the evil of your doings from before my eyes.
Cease to do evil; learn to do well,`" etc.
"`Then come and let us reason together, says the Lord; though your sins be as scarlet,
they shall be as white as snow; though they be red as crimson,
they shall be as wool,`" Isaiah 1:16-17; still these are the terms,
"`put away the evil of your doings,`" then patience, mercy and long-suffering,
shall be extended to you; "`God will give grace and glory,
and no good thing will he withhold;`" what, from those that say their prayers,
or go to the church or meeting?
No, but "`but no good thing will he withhold from them that
walk uprightly;`" Ps. 84:11. These are the men.

And when the Lord distinguishes by his prophet whom he would have among them,
he speaks of a sort of people that called upon the name of the Lord;
those that feared the Lord, and spoke often one to another; that is,
of the goodness of God; they were a sort of people that trembled at the word of God;
a sort of people that did not do as others did, hunt after pleasures, riches,
and the honours of the world,
but to be acquainted with the inward word that wrought upon their hearts;
in that day that I make up my jewels, they shall be mine, says the Lord.
Whose shall the others be?
You will own these for yours, but whose shall the others be,
that think not upon your name, and tremble not at your word?
There is a place for them too: Tophet is prepared of old, made both wide and large;
the fuel thereof is fire and brimstone, and much wood,
and the breath of the Lord kindles it.
This is for all that are wicked, and that work iniquity.

This is in the Old Testament; then comes the New Testament, in John`'s Revelations;
there is a separation again:
There are a sort of people which are called the true worshippers,
and the angel was commanded to go and measure the temple,
and those that worshipped therein: The outward temple was not measured,
but left for the Gentiles to tread in, and left without the measure;
"`for outside are dogs and sorcerers, and whoremongers, and murderers, and idolaters,
and whoever loves and makes a lie.`"
And then the Lord speaks to his prophets in the Old Testament again;
if you put a difference between the precious and the vile,
then you shall be as my mouth unto them; but if you huddle them altogether,
and sew pillows under elbows, then you shall not be as my mouth.

So that in all ages God aimed at a separation of the state and condition of his people;
and one sort of people were purified, through the sanctification of the Spirit,
and belief of the truth; and another sort were unsanctified and unpurified,
and remained in their sin; and the end of Christ`'s coming into the world,
it was to call people to repentance; he came not to call the righteous,
but sinners to repentance, and to leave off their sin.
To as many as received him, to them he gave power to become the sons of God,
to as many as believed on his name.
Whose sons were the other?
They made as high a rattle of profession as the other: He tells them who is their father,
"`you are of your father the devil;`" and he did orderly prove it, and that was thus;
that they did the devil`'s works, ergo, they were the devil`'s children.
It was Christ himself, the greatest doctor of divinity that ever was in the world,
that spoke these words:
And this is the manner of logic whereby he argues with the Pharisees,
to make them believe that they were the devil`'s children;
they that do the devil`'s works are the devil`'s children; but you do his works,
therefore you are his children; so they sought to kill him,
they could not bear such arguments.

If one should go and search out a people in this city and nation,
and see one man of this religion, another of that religion, and pick them out,
and use this argument with them: There is a man professes high,
he professes a light within; if you look upon his deeds they are dead and dark,
why then he is one of the devil`'s children: If you put me to prove this,
I say he does the devil`'s works, he is an extortioner, a deceiver,
and a drunkard and unclean person, and does the devil`'s works,
and so is none of God`'s children.
And so go to another sort and use this argument, it is safe enough,
you can never fail in this kind of argument which Christ used;
and if people would use it with themselves, and think themselves no better,
then we should have people confess themselves the devil`'s children.

None come to be God`'s children, till they come to acknowledge their lost state,
their deplorable condition; that they are fallen from God,
and through sin and iniquity are got into a nature that is at enmity with God;
then they will cry out,
"`who shall deliver me from this body of death,`" and childship of Satan,
this heirship of wrath?
I am an heir of an inheritance; I am an heir of wrath,
and I would readily part with this inheritance and heirship,
and have an "`inheritance with the saints in light:`" We shall never know this,
till we come to divinity without sophistry, and without tricks and quirks,
and come to Christ`'s reasoning.
He that does the devil`'s work is the devil`'s child;
then they will confess this is of the devil, and the other is of the devil.
This is an evil work; and I see that I have need to be brought into another condition.

When people come to an acknowledgment of the truth, and of their own condemnation,
then they are one step towards redemption and salvation.
No one ever took a step towards their salvation,
till they acknowledged their own condemnation.
"`He that sanctifies, and they that are sanctified,
are all of one;`" and they that are joined to the Lord, are one Spirit.
An evil tree, says Christ, cannot bring forth good fruit.
When Christ spoke this, he spoke it to men and women, and he spoke it of men and women,
and not of trees: And when he said, no man can gather grapes of thorns,
nor figs of thistles, he speaks of a generation of men: As if he had said,
this thorn must be translated and changed into another
nature before it can bring forth grapes;
and this thistle must be changed into another nature before it can bring forth figs.

There must be a change in the nature of man before there
can be a change of the fruit and effect of his doings;
whatever he sows, that he shall also reap; whatever a man does in the body,
he must give an account thereof at the day of judgment; for the books will be opened,
and men judged according to the things written in those books.
If there be a book for you and me, I will warrant you there is a great deal in it;
there is a recorder and a clerk for the book,
which God has opened in every man`'s conscience;
and there is set down every man`'s transgressions and his sins: Says one,
you have written my transgressions as with the point of a diamond;
you have engraved it so deep,
that it seems impossible that it should ever be blotted out again:
Some have had their sins so deeply engraved in their conscience,
that they have thought they would never be blotted out,
they were written as with the pen of a diamond.

When people see and consider that they have ventured their souls upon such slight grounds,
I hope they will be awakened to seek after righteousness;
when they see there is nothing good in them: Where there is anything good,
it is God that has given it to them.
Some will say, if I be perverse, corrupt and wicked, I cannot help it,
therefore I must be beholden to my Maker to help me, else I must never be helped.
Now, because God knows that we are helpless, he has laid help upon one that is mighty,
that is, our Lord Jesus Christ;
and Christ has sent forth his Spirit into the world to convince the world of sin,
and to lead his people into all truth:
And this grace that comes by Jesus Christ has been so universally showed,
and so universally extended to all men,
that I never met with a man yet that had none of it:
But let them be as bad and as dark as they could,
yet the light of Christ shined in that darkness, into the darkest heart,
that ever I met with in all my life: He shows men, that his light shines in darkness,
and the darkness cannot comprehend it.

Therefore the work that God has set us about,
and the service which he requires at the hands of many of us,
is to turn men from their own darkness unto the light of Christ their Saviour,
and from the devil`'s power, that has enslaved them,
to the power of God that can redeem them;
and yet we are far enough from that which they call free will;
it is God`'s will that everyone should be saved: But some will not be saved,
they will keep their own wills and not resign them up to God;
they have a free will to go to destruction.
As for salvation, if they will obtain it, they must part with their own wills,
and they must take a yoke and burden upon them, before they can be saved:
If people can have their wills, they will not take Christ`'s yoke upon them:
He that will be Christ`'s disciple must deny his own will and take up his daily cross;
these are the terms of the gospel.

But you will say, no man, by all the power he has, can redeem himself,
and no man can live without sin.

We will say amen to it: But if men tell us, that when God`'s power comes to help us,
and to redeem us out of sin, that it cannot be effected,
then this doctrine we cannot away with, nor I hope you neither.
Would you approve of it if I should tell you,
that God puts forth his power to do such a thing, but the devil hinders him?
That it is impossible for God to do it, because the devil does not like it?
That it is impossible that anyone should be free from sin,
because the devil has got such a power in them, that God cannot cast him out?

This is lamentable doctrine: Has not this been preached,
this doctrine of impossibility of living without sin?
It does in plain terms say, though God does interpose his power it is impossible,
because the devil has so rooted sin in the nature of man.
Is not man God`'s creature, and cannot he new-make him, and cast sin out of him?
If you say sin is rooted deeply in man, I say so too;
yet not so deeply rooted but Christ Jesus is entered
so deeply into the root of the nature of man,
that he has received power to destroy the devil and his works,
and to recover and redeem man into his primitive nature of righteousness and holiness;
or else it is false, that "`he is able to save, to the uttermost,
all that come unto God by him.`"
We must throw away the bible,
if we say that it is impossible for God to deliver man out of sin.
Is not Christ entered into the root of our nature?
And has he not taken upon him the seed of Abraham, after the flesh?
Has he not entered into the root of all men`'s natures, and tasted death for every man,
that he might quicken everyone that is dead in sins and trespasses?
All these things speak the love of God to mankind, in order to their salvation.

Much might be said to these things,
these clouds of error and darkness that have overspread the nation; yet, this I say,
if one were to speak of it ever so long, it must be by the eye that God gives you,
that you must see it; it is he that opens the hearts of men as he did Lydia`'s:
If there had not been the power of God that reached her heart,
Paul could not have opened it.

When all is said that can be said, the counsel of God which has sounded in your ears,
is recommended to you,
that everyone may retire in quietness and stillness of mind to wait for the feeling
of that quickening power of the Spirit of Christ that is sent into the hearts of men;
that it may open your eyes to see your present state; then you will see a better state,
a further state,
and when you see with your inward eye that your state
is not so good as you would have it to be,
then trust and rely upon the all-sufficient and powerful
operation of God`'s Holy Spirit to mend your state,
and give you power over your corruptions, and to go on from one step to another,
towards the cleansing and sanctification of your souls,
so that you may receive something from God to enable you to live to God;
for all that you receive from men will only make you live to men,
but that which you receive from God, will help you to live to God;
that will purify you and sanctify you, and make you clean through the word:
So through the word you will come to cleanness, purity and holiness:
And when you are come to the way of holiness,
you may believe you have got into the way of God`'s kingdom, and never till then.

It is not enough to make a profession,
but we must live up to the profession of that religion that we make;
it is not holding this tenet and the other tenet, and saying, this minister, I am sure,
preaches the truth; you may be a child of the devil for all that.
I now speak indifferently to all people, without respect to any sort:
They that believe they are walking towards the kingdom of God,
and yet their way is not a holy way, they have cheated themselves,
and deceived their own souls,
and they had need look about them and take heed what they do; the glass is running,
and time is hasting away, and our life may end we know not how soon.
It is good to prize and improve time, while you have it,
and bring your deeds to the light; see what reproofs, instructions,
counsels and openings you have met with from the Lord,
and see how you have answered and been obedient to them,
and so you will come to take a sound and infallible account of your condition;
and if it be not so good as it should be, wait upon the Lord to mend it;
he that made you can mend you, he that made your ears,
must unstop your ears to hear the word of God.

To that power that carries on the works of sanctification and redemption by his word,
to that word I must leave you, and to his spirit I commit you.
This word will be with you, and if you part not with it, it will not part with you;
it will go with you to your houses, and to your shops, and to your beds;
it will lie down with you at night, and rise with you in the morning: To that end,
Christ is a leader and governor, and the captain of our salvation, to lead the van,
and carry you on in the way of salvation; and as many as follow Christ,
and are led by the spirit of God, they are the children of God.
