[short="The Sheep of Christ Hear His Voice."]
== Sermon XXV. The Sheep of Christ Hear His Voice.

[.signed-section-context-open]
Preached at Devonshire-House, May 10, 1688.

[.offset]
"`My sheep (says the true shepherd) hear my voice.`"

The sheep of the true fold hear the voice of Christ, the good shepherd,
and know the voice of strangers too: But, says he, "`the stranger they will not follow.`"
This scripture has been a mark of distinction in all ages,
that has been peculiarly bestowed upon the people of God,
that they have had a discerning knowledge to make
a certain distinction between them that were of God,
and those that were of the world: Now they that are of God hear us, says the apostle.

Now, that you may all find in yourselves this peculiar gift of God,
to be able to understand and discern between the precious and the vile,
that you might know the ministration of life from the ministration of death,
you must all be gathered inwardly into that which you have received of God;
for they that are only exercised with gifts and parts,
and acquirements that appertain to this world,
they have been always subject to delusions,
apt to be led away into a by-path and crooked way, that leads to destruction:
But they that are under the government and direction of the gift of God,
they have been able thereby to make such a distinction of voices, and of sounds,
that they have been preserved from the delusions of the age.

This was the difference of old between the prophets of God and the false prophets,
between the apostles of our Lord Jesus Christ, and the false apostles;
the difference was not so much in their words,
for they had in a great measure the same words; if the true prophets used to say,
"`thus says the Lord,`" the false prophets would say so too;
if the true prophets declared against sin, the false prophets likewise would do so;
for the false prophet stole his word from his neighbour:
But the greater matter by which the people of the Lord were preserved, was,
that hidden and divine wisdom they received of God,
by which they discerned the voice of the spirit from the voice of strangers,
from the voice of them that were of the flesh;
and that was the cause that the Christians in the primitive days did not adhere to,
and follow those false apostles that came to them in their own names,
and held a form of godliness, but denied the power of it.

But they among them in whom their witchcrafts did enter, they went away from the spirit,
and sought to be "`made perfect in the flesh;`" they went to the outward observation,
and to the beggarly rudiments of things that "`perish with the using`",
and from "`the law of the spirit of life in Christ Jesus.`"

And as it has been in those ages of which we have read,
so it comes to pass in this our age,
in which a dispensation of the spirit of truth is
manifested and revealed unto the children of men;
there is a remnant that have received the testimony of eternal life,
and have believed the testimony, and waited on him of whom the testimony is born,
not to have life by the testimony, but to have life in him;
so they receive their life by the ministration of the Spirit of Christ,
and they live to God, and others who have received no life from him,
but have a life in the words, and sounds, and noises and terms,
and distinguishing phrases of things, their life lies there,
they live not to God but to themselves, their glorying is not in the cross of Christ,
but in the words and outside of things; so that everyone had need,
at such a time as this, to approve their hearts unto the Lord;
who knows the inside of people`'s profession, the inside of their religion,
that knows how the heart is concerned towards God,
and what they say and do upon the account of his service,
so that all that are met together might come to receive more and more
of the life and virtue that sanctifies the soul of him that receives it.

For, alas! my friends,
it is not the gathering together of the most excellent words about religion,
and about worship and service, which will approve any man in the sight of God;
that is but the painting of a sepulchre, and covering the rottenness that is in many;
but the Lord sees into the inside of every professor,
and whoever names the name of Christ and departs not from iniquity,
they do but take his name in vain, and contract a guilt upon their own souls;
so that everyone that seems to be religious,
ought to inquire from where their profession springs;
if it springs from a real possession of a measure of that which sanctifies the life,
and shows itself forth, in its working and operation, many times abundantly more,
than it does in word and profession; it manifests itself in holiness and righteousness,
to the honour of God;
it is the aim and design of all such to exalt the name of him whom they profess,
by holiness and righteousness shining forth in their works,
for it will never shine through words alone; many good words may be spoken,
yet God not glorified, but his name may be dishonoured by them;
but whoever comes to feel that which is life in themselves,
they know what will honour God, they feel the birth immortal that is of God,
of his own begetting by the word of truth.

This living birth is that which brings forth living praises; the other is but flesh,
"`that which is born of the flesh is flesh,`" and it glorifies the flesh,
and when the flesh is most of all glorified, most of all exalted,
it is then but "`as the flower of the field,`" it is then cut down and withers;
the sun of righteousness shines with the beams of the everlasting glory of God,
and causes it to wither and come to nothing.

So friends, let your minds be gathered inward, that you may be able in your own selves,
by virtue of the divine gift of God,
to distinguish between the voice of the true shepherd, and the voice of a stranger,
so that your minds may not follow a strange voice,
that you may follow the Lord with your whole heart, with a full purpose of heart;
for there is a real word of prophesy discovered in the inward parts,
which does distinguish between the precious and the vile in everyone`'s particular;
and that which is precious in one, it answers to that which is precious in another;
and that which is vile in one, it answers to that which is vile in another.

For there is an inward and secret mystery of iniquity, as well as a mystery of godliness.
The mystery of godliness is when God is manifested in the flesh;
the mystery of iniquity is, when the wicked one is making himself manifest,
and appears and discovers himself in the flesh,
that he may rise up and glory in the flesh.

Now the eternal truth, which never changes, this is that which gives a discerning,
this has always put a difference between the true and false prophets,
the true and false apostles, and between the true and false ministers;
the difference has not been so much in words as in power,
as the apostle speaks concerning some in his days, that had endeavoured to deceive,
and to draw men aside from the simplicity of the gospel; "`when I come,`" says he,
"`I will know.`"
Now, he does not assert, that he will pay particular attention to their words,
whether they were judicious or no; for he says, I will not know their words,
but their power.
How should he know their power if he were not in the power himself?
Now this divine power, as everyone acquaints himself with it,
it works unto the sanctification of them,
when they have fellowship with the stirrings and
movings of all others that are partakers of it:
This is that which will establish and confirm your
minds in the true faith and simplicity of the truth,
that you turn not aside to the right hand or to the left.
If you have regard to the principle of divine truth that you have received from God,
then you can receive confirmation from anyone that has a measure according to it.
There is a measuring line, and the reed of the sanctuary,
that measures the temple and all that dwell therein,
that measures them with one reed and one measure, and everyone answers to that measure,
according to the stature and degree of growth of the grace of God they arrive to;
and now they are come to a fixed foundation.

Others there are in the world, that have laid their foundation upon this creaturely help,
and the other creaturely help, upon this man, and the other man;
but now true Christians come to have their foundation,
their rooting and building upon Christ Jesus,
upon that word of life that first of all gathered their minds into a desire after holiness,
into a desire after acquaintance with God that made them.

You that are true Christians can remember, how you were begotten,
and that which did beget you; that word of God that is incorruptible, that is immortal,
that was not of a dying quality, that need not be supported by this, and that,
and the other means, but it has its support in itself, it has its nourishment in itself,
and it grows up in itself, and everyone that receives it they grow up in it,
until they come more and more to partake of the life and qualities of it; that as he is,
so they may be in the present world.

But this is never known, but where the word of God has its free passage:
Many have tasted of this word of God, and by tasting of it,
have been acquainted with the power of the world to come;
they knew well enough the power that would bring forth another world, "`a new Heaven,
and a new earth,`" and righteousness in it;
many have felt the power that have never continued to see the working of it,
never continued to see and witness what this power would work;
going aside from the power of the world that was to come,
they have never seen the coming of it, but their foolish hearts have been darkened again,
and their imaginations have grown vain,
and they have conceived to themselves a false liberty to the flesh,
and their wills have been strong, and have prevailed over them;
that though they had tasted of the powers that did belong to the world to come,
they never saw the working and operation of that power to
bring to pass that which by sight and vision they did behold.

Therefore it is needful for everyone of you,
in every state and condition the Lord has brought you into,
to keep yourselves in a deep humility; to know the afflictions,
temptations and trials you are under, and to exercise your minds,
not only on account of what you have got over,
but let everyone know the state and condition in which at present they are labouring;
for when some come to look at what sufferings and difficulties they have got over,
they are apt to be exalted above measure, and lifted up in their minds;
let everyone consider what is their present state and work;
their help lies in that condition.
Some have always a foundation of their faith present with them,
that they may feel the object of their faith where they hope for help,
where they hope for comfort and strength to be present with them.

Now everyone that believes in the word of God, their care is,
that they may know this word of God, that they may hear it, feel it,
and behold the beauty of it under the exercises of it; how it conducts and leads,
how it counsels and advises, that so, in all things they are to pass through,
they may not be as those that have run into it;
as those that do this and that of their own wills,
but may be properly followers of something.

I go into this, or that, or the other thing, not to do my own will; I do not run into it,
but I am led into it; my leader goes before me, the word of God,
that has conducted me and led me: I am a follower of God in all his dispensations,
and in all his leadings and guidings; I am to follow him, for he teaches me his way,
he instructs me in the true way: The best of all his scholars and disciples,
they are to be led and guided into that work and service they are to do,
that they may run into no irregularity or absurdity, for he will lead you into holiness,
righteousness and humility, where all become the servants of God in Christ Jesus,
and servants to one another:
There is a mutual concord and harmony in the work of this spirit,
in the service of this power,
where everyone finds what they are appointed and directed to,
and all the members of the body of Christ know they ought not to be disjointed and rent,
and separated one from another,
but tied together in "`joints and bands,`" to edify one another in the love of God;
so that here is one spirit that has been the guide of this one people in all ages.

Many people have been guided by many guides, and they have been scattered,
divided and separated one from another, and have been under this,
that and the other name; but all God`'s people have been guided by the Spirit of Christ,
that universal Spirit that is one with God.
In the Old Testament times, and the New Testament times,
they were all led by the universal Spirit of Christ, and they were of one heart,
and of one mind, serving the Lord; there was a concord and unity among them;
and if at any time any discord or division happened,
it was because the roaring lion that goes about continually seeking whom he may devour,
had found some or other that he might devour, and draw into his snares and gins;
for there are some that he may, and some that he may not.
Who are they that this roaring lion may destroy?
The devil knows who those are that he may prevail upon;
he knows that those which are in the hands of God are out of his reach:
"`My Father,`" says Christ, "`is greater than all,
and none shall pluck them out of my Father`'s hands;`" yet doubtless
those that are in the Father`'s hands are tempted and tried,
the roaring lion goes about seeking to devour them if he might; a man that he devours,
he swallows up with prejudice, enmity, covetousness and pride,
and he will lead him into any evil thing; he has many gulfs to swallow men up in,
but if he meet with one that is kept in God`'s hands,
he knows such a one is out of his reach, and he is not able to catch him.

If he meet with a man that he can prevail over,
as he did over our father Adam and mother Eve, such as are in their own hands,
that stand upon their wit and parts, and knowledge and eloquence;
those that stand upon these things as their foundation, they are in their own keeping;
these are they whom he may devour and catch, and ensnare in one or other of his gins,
and swallow them up in one of his gulfs and temptations:
But seeing God has opened and manifested these things by his Spirit,
and seeing the secret wiles of Satan are discovered
and made known by the shining of his light,
how ought everyone that is a believer of the truth,
to depend upon God for his protection,
and be careful that he goes not out of his Father`'s hands,
that he never trust himself to his own keeping for his security and preservation,
lest he meet with a temptation that may swallow him and devour him.

I remember our Lord Jesus Christ when he was upon earth,
he put his disciples in mind of what happened long before,
"`remember Lot`'s wife:`" You may take notice of her,
the power of God took hold of her and brought her out of Sodom,
and was leading her to a place of safety,
but she had something of Adam`'s apostasy in her nature, she looked back,
and was turned into a pillar of salt.
Our Saviour was pleased to make use of this passage
that happened some hundreds of years before,
to show how she failed of coming to the place of safety,
though she was led out of Sodom by the hands of one of the angels of God.
O! remember her, she was turned into a pillar of salt,
and this remains instructive to this day.

If we remember where our safety is, and from whose hands we must expect it,
we need not go to look at Lot`'s wife.
We have seen many in our days that have stood fair for redemption,
they have had a power revealed to them, that is able to redeem them,
and save them to the uttermost; but afterward by exalting themselves above this power,
and taking the government of themselves into their own hands,
they have robbed God of his glory, and he has withdrawn himself from them,
and then it was with them as with Saul, when the Lord departed from him,
the evil spirit entered into him.

We have before our eyes from day to day,
those that have known the beginning of the redemption of God`'s power,
and have been in a great measure brought out of Sodom, and out of the way of Egypt,
and they have had opened to them the mystery of the kingdom of God for their encouragement,
but at last they have taken and arrogated those gifts to themselves,
and looking upon themselves as far excelling others,
magnifying their parts as if they were their own, when they were the gifts of God.
Then the Lord has left them, to let them see whether they could stand of themselves,
and they have fallen, and been taken in the gins and snares of the devil, who,
like a roaring lion, is going about continually, seeking whom he may devour.

Now, my friends, it greatly concerns us all to know what refuge we have to fly to,
in a time of trial; we have a time of trial now,
though not a time of external suffering and persecution,
and enduring hardship yet upon us, to try our faith and trust in God;
yet we have no reason to be secure, carless nor remiss in our present duty,
nor to put the evil day far from us,
but to be in the exercise of humility and watchfulness as becomes Christians;
for there is now as much danger and peril in this time of liberty and tranquillity,
as there was before.

If anyone in the time of persecution and suffering has said within himself,
I had better give over and part with the truth, and forsake the ways of the Lord,
and give over my testimony for his name, for I shall be undone and ruined in the world;
this man by his carnal fears has lost his testimony.

So likewise if a man in this time of liberty and freedom of serving the Lord,
and bearing testimony to his name, if he shall not entirely trust in the Lord,
to carry him on in his work and service, and continue his dependence upon him,
and wait for the assistance of the Holy Spirit of God to work in him "`to
will and to do of his good pleasure,`" this man shall lose his testimony,
as well as the other: Therefore,
let everyone of you keep up a dependence upon God`'s Holy Spirit
for carrying on the work which he has begun in your souls;
consider what work it is that Christ is now at in everyone of you;
I know what his work was when I was first convinced,
he was burning up and hewing down everything that hindered
his carrying on the work of sanctification and redemption,
and firmness and stability in the covenant of life and peace.

And now our meeting together ought to be in the name of Christ;
I hope it is so with most of you:
I hope it is not to see and hear what this or that man says,
but to know within yourselves what part of the work
of redemption the Lord Jesus Christ is carrying on,
that you may join with him, and be a willing people in the day of his power,
and say as Paul, "`Lord, what will you have me do?`"
If you will have me part with my all, Lord here it is, I offer it up;
and if you will have any service done, Lord here I am, speak, for your servant hears;
let there be in everyone of you an attentiveness, and a humble waiting upon the Lord,
and say as the Psalmist, "`behold,
as the eyes of servants look unto the hands of their masters,
and as the eyes of a maiden unto the hands of her mistress,
so our eyes wait upon the Lord our God until he have mercy upon us.`"

Whenever a Christian has his dependence upon God`'s wisdom and power,
such a one shall never lack wisdom,
the Lord will give him wisdom to preserve him against all the wiles of Satan;
and he shall never lack power,
for the Lord will enable him to fulfill and perform what he requires of him;
he shall be replenished with judgment and understanding, ability and power,
to direct him into the good ways of God, and to enable him to walk in them.

It is the earnest desire of my soul,
that everyone of you may be exercised in those things which are profitable for you,
and which may be comfortable to your friends and brethren;
that you may all grow up into a stability and steadfastness in the good ways of the Lord,
that you may not be shaken and tossed with every storm and tempest;
that when there comes a time for the trial of your patience, and fortitude and courage,
you may not be tossed to and fro like children, but be steadfast and unmovable,
always abounding in the work of the Lord,
that so living in all holy obedience and patience, and continuing in well-doing,
you may have a constant supply of strength and power
from God ministered unto you by his Holy Spirit.
