[short="Salvation from Sin by Jesus Christ."]
== Sermon XXVIII. Salvation from Sin by Jesus Christ.

[.signed-section-context-open]
Preached at Devonshire-House, August 9, 1691.

It is a general doctrine in the world,
that no man by any means can ever be set free from sin in this life:
This is universally received among almost all Christians, in all churches;
and though they differ ever so much in other things, yet they agree in this;
so that this doctrine has got a sway in the world,
and it is accounted a great delusion and a heresy,
and a grand error for any to question the truth of it.

Now while a man is of that belief, that there is an impossibility of living without sin,
and of breaking down the kingdom of Satan in any one soul in the world,
how can men hope or believe that righteousness should prevail in the heart of one man?
There is neither king nor beggar, nor bishop nor a gospel minister,
but the devil must have a rule and government in him, so long as he lives in the world.
As long as this is believed, it is not possible that the other belief should take place;
it is madness to think that I must be under the rule and government
of Satan if I am under the government of the Son of God.
And it is still greater madness to say,
that Christ and the devil are both my governors and rulers:
It is prodigious folly and madness to speak after this manner.

This belief prevails over all men; over the wise, and mighty, and noble, and learned,
that they can never be freed from the power of sin in this world,
but that the devil will lead them into sin every day; let men be ever so sober,
ever so abstemious in their lives; let them spend ever so many hours in prayer every day;
let them come to meetings and hear sermons, and write them, and repeat them,
and do what they will, here is a bar of unbelief that lies in the way,
that makes men "`depart from the living God,`" and his power,
and lose the benefit they shall receive from Christ:
And therefore they go to obtain it another way, that is,
to have the righteousness of Christ imputed to them,
and they shall be pure and holy in the sight of God,
when they are polluted in their own eyes; and when they see their daily failings,
infirmities and corruptions, yet God may not see them; but that he sees them holy,
just and righteous in his Son.

What strange kind of doctrine is this?
I must presume that God will see me in his Son, Jesus Christ, when I never was in Christ:
How can this be?
"`He that is in Christ, is a new creature; old things are done away,
and all things are become new:`" But if there be old things remaining still,
and I am not become new, shall I presume that I am in Christ,
and that God will see me in his Son?
When people come to use the understanding that God has given them,
they will look upon themselves as barred out by their unbelief,
that the nations have drunk in;
and it is as sweet to them as the honey and the honey-comb.

But, blessed be God, many have vomited it up already;
If they would have placed this doctrine upon man`'s natural ability,
I would have said Amen to it.
I know there is none of us all have a natural ability
and power to deliver his own soul from sin and Satan;
but when they come to place it upon God, that though the Lord make bare his arm,
and reveal his power; though they come to have the grace of God,
that still they could not be delivered from sin, this has blasphemy at the bottom of it.
The other reflected upon man`'s power; this reflects upon the power of God Almighty:
That the devil has got such a power over us, that God has not power over us,
nor can have power and dominion over us,
so that of a whole nation he cannot have one man to serve him.

Much might be said in answer to this: When men are once willing to serve God,
they will be willing to leave the service of the devil.
There is no way to answer that good wish,
but by waiting upon God for the revealing of his power:
I pray God that when you come to a meeting, you may say, Lord,
let your power go forth upon my heart; let your arm be made bare,
and deliver me from the power and dominion of sin.
Some will say they feel God`'s power in a meeting;
I feel the power of God working upon my heart,
in order to the taking away sin and transgression, and giving me victory over it,
through the Lord Jesus Christ.
If they feel this power of God upon them,
it is their duty to believe it and depend upon it: If I believe it,
I must wait for the dictates of it,
and believe that I shall be able to do "`all things through Christ
that strengthens me:`" Then faith will come forth into works,
and appear to be a living faith.

You may remember what the apostle James says, "`as the body without the Spirit is dead,
so faith without works is dead also.`"
As soon as a man comes to join with the mighty power of God,
he will be able to withstand temptation: If he comes into evil company,
he will deny them and not comply with them;
he will find then something of a power and ability to serve God;
though he is not come to perfection, yet he is walking in the way of holiness,
and pressing forward "`towards the mark of the high
calling of God in Christ Jesus:`" He will say,
I have got a little nearer than I was towards the place where I would be,
towards that life which I would live and die; then let death come when it pleases God,
it shall be welcome.

This is the wickedness of many in the world,
they will not live such a life as they would be willing to die in.
They cannot come at it unless it be given them to believe, for it is the gift of God;
they must come to their governor and leader, which goes before, to the gift of God,
which is eternal life; then let death come when it will,
if I have the gift of eternal life.

It is a miserable thing to think that there are many
that have not laid hold of eternal life:
It is manifested, that we may lay hold of it, there is a hand of faith joining with it.
When a man comes to lay hold of eternal life, this life will purify him and sanctify him,
at least by degrees, till he be wholly sanctified in body, soul and spirit:
This is that which the apostle writes in one of his epistles,
your salvation is nearer than when you at first believed.
When they first believed, their salvation was a pretty way off.
He describes salvation to be the end of their faith and hope.

When a man comes to be delivered from his sins, he shall serve God without fear;
but when a man comes to live by faith, he shall overcome;
he is a good soldier of Jesus Christ, and he must fight valiantly under his banner,
till he gets a victory over all his enemies,
and then his salvation is much nearer than when he at first believed.

I would I could say so of some of you; for I fear your salvation is farther off:
Some go straggling here and there, as sheep not having a shepherd;
this is that which my spirit is exercised with.
You that are travellers towards the kingdom of God,
it is the wonderful grace and mercy of God,
that ever it should come into your minds to seek the kingdom of God,
and the righteousness thereof.
They that have obtained this mercy from God, shall receive and enjoy other mercies,
better mercies;
"`blessed are they that hunger and thirst after righteousness:`" That is one mercy;
but there is another mercy, they shall be filled; they shall be satisfied:
When a man comes to this, he must take up a daily cross, and exercise self-denial;
but if he follow Christ, he shall be satisfied;
he shall then have nothing but peace and joy;
he shall then sing praises and glory to God in the highest, and to the Lamb forever.

There is none can understand the glory that is laid up for
those that take up their cross and follow Christ,
and love his appearing.
This is the greatest blessing that God does give unto his people,
he has sent his Son Jesus to bless us, and turn us from our iniquities.
This is a blessing indeed.
Take heed that you do not admit of any new terms:
Do not think to bring God Almighty to new articles,
the terms are declared and concluded on already: If you will obtain the blessing,
you must be turned everyone of you from your iniquities: The terms are already made,
the law of God must be written in the heart and inward thoughts,
and you must close with that power that will write the law in your hearts,
and by travelling towards the kingdom of God,
you will see the coming of that kingdom in you.

It was the joy of my soul, that I saw the kingdom of Christ would be set up in my heart,
before it was set up there; then I saw the Lord`'s wonderful work,
and there was a great alteration in me,
when the Lord was pleased to wean me from the world`'s breast, and take off my heart,
and wean it from worldly lusts, from the world`'s joys, and pleasures, and fashions,
and the world`'s honour and reputation:
I say the Lord was pleased to wean me from these things,
and brought me to a holy resignation, to give up my heart to him: If I have joy,
it must be from the Holy Spirit; if I have pleasure it must be in the presence of God,
who in the multitude of my thoughts within me made his comforts delight my soul;
and if he bring not comfort to you, you will never have it;
you cannot expect it till you do believe; and when you have faith,
you can feel the kingdom of God within you: There must be the new birth,
the work of regeneration,
for "`except a man be born again he cannot see the kingdom
of God;`" there must be a translation from death to life,
there must be a turning out of the old bottom and a fixing upon a new bottom,
upon Christ Jesus the rock of ages;
there must be a subjection to his holy power and government,
else you cannot see the kingdom of God.

Many have gone on in a profession many years, and never saw the beauty of it;
and every little trifle in the world has diverted them, and drawn them away.
This and the other pleasure has drawn away their hearts,
they have seen the glory of the world, which has captivated them:
But those that make a profession of the truth,
and have seen the beauty and glory of the kingdom of Christ, they should,
be shy of returning to the world again, for the apostle says,
"`it happened to them according to the true proverb,
the dog is turned to his own vomit again,
and the sow that was washed to her wallowing in the mire;`" "`it
had been better for them never to have known the way of righteousness,
than after they have known it,
to turn from the holy commandment delivered to them:`" They made a profession,
and were members of a visible church, and had a name to live,
but they were inwardly dead, the sight of the kingdom of God is not given to such,
but unto babes, that have a divine birth, and that desire the sincere milk of the word,
that they may grow thereby.
God has hid these things from the wise and prudent, and revealed them unto babes.

I speak to those who are here this day, that would receive some kindness from God,
and that desire the knowledge of his ways,
and that the mysteries of his kingdom may be revealed to you,
let your minds be retired and you shall find the great things
belonging to your peace made known to you.
We have spoken much of this, but I would not have you know it only by our sayings,
I would have you go into yourselves,
to see whether God has not bestowed this grace and blessing upon you:
If God has given you grace, do not turn it into looseness; do not abuse the grace of God.
What is it that you do when the grace of God has convinced you,
that such and such a thing is sin, and if you do it, it will turn to your ruin?
Dare you venture to commit sin after you are convinced of it?
O take heed of doing despite to the spirit of grace, and of grieving the Holy Spirit,
whereby you are sealed to the day of redemption.

I wish that the weight of this consideration might lie upon you,
and that a holy dread and awe of God might be wrought in your hearts,
that you might be kept from sinning against God.
You know there is a general outcry against presumptuous sinning, sinning against light:
Why should not we all cry out against it?
It is a most dreadful thing for any man to sin against his knowledge and conviction;
if any of us have been guilty of sinning against light, let such a one say,
I have done iniquity, I will do so no more, but enter into covenant with the Lord,
and say, O Lord, so far as you have revealed your will unto me, I will obey it;
I will delight to do your will, O God, though I cross my own will.
Whatever I cross I will not cross God`'s Holy Spirit,
by which I may be sealed to the day of redemption;
I will never do this though I hazard my chief interest in the world:
This is the temper of a true Christian, and I pray God make you all of this mind.

And now my friends, you that desire to see this great work wrought in yourselves,
commit the whole work to God, and trouble not yourselves about it.
I am sure God will carry on his own work, and bring down the devil`'s kingdom,
and rebuke that unclean spirit that is gone forth over the whole nation,
and pour out abundantly of his Holy Spirit to carry on a glorious reformation.
This I believe God will certainly do, from what he has wrought in my own soul.
I know not what instruments are to be employed in the work, I leave that to the Lord;
but the kingdom of Christ shall be advanced, and it shall be outwardly,
and a broom of destruction shall sweep away all his enemies from the earth,
and the wrath of God shall burn against them;
but there is an obduration which has been upon the nations of the world,
and something has stood in the way in all generations.

But, however, I am sure we all may well say, that Christ is the Saviour of all men,
but especially of them that believe.
He has saved this city and nation from the plagues and vengeance that hang over us.
Many years the Lord has spared us, and waited to be gracious for a long time,
to see if we will at last turn to him.
How long the Mediator will intercede on our behalf, we cannot tell;
there is a time when the long-suffering of God will come to an end,
God has brought a scourge upon the nations round about us,
and the flames of his wrath has kindled upon them, and destruction has overtaken them;
how soon it may be our lot, we know not; all our money, our silver and gold,
and valour and courage, will not be able to ward it off, if the Lord but blow upon us.
It is even at the door; there is but one way to save us, and that is turning to the Lord,
and crying to the Lord for the continuance of his mercies and long-suffering,
and patience towards us.
In this cry to the Lord, let us all unite, that are lovers of the nation,
and let us join our earnest supplications in this work,
seeing the Lord has made us the monuments of his mercy and preserving goodness.

We have been continually surrounded with war and blood, and flames and destruction;
and the cry of the orphans has been heard from other nations.
And while they have been consumed with flames, and deluged in streams of blood,
we have sat under our own vines and fig-trees; but judgments hang over the nation,
and whether they will fall or not, the Lord knows:
But what shall we do for the good of our nation, and cities and families,
but labour everyone, in the fear of God, to reform our lives,
and to take heed that we sin not against the light, left we die,
and perish in the middle of those terrible judgments that hang over us.

Let us turn from our evil ways, and depart from all iniquity,
that the kingdom of Christ may be set up in ourselves.
It is the righteous in the nation that the Lord looks at,
and for their sakes he will spare a nation.
If there be a people among us that walk in humility,
and lament and mourn for the abominations committed in the midst of us,
God will have regard to them,
and he will hear the cries and the supplications of a praying people.

Friends, you that cannot make use of sword and spear for the saving of a nation,
you may do good by your prayers, and turning to the Lord with an unfeigned heart,
and let your sincerity appear before him.
If I would take a common prayer-book in my hands, and pray ever so devoutly and solemnly,
if I be not sincere, what will that do?
Or, if I pray without a book, or if I pray without a form,
or reject the form that others have made for me, what will this avail?
But the cry of the poor, and the sighing of the needy,
and the effectual fervent prayer of the righteous,
has availed much for the saving of this nation many years.

Therefore, I exhort you all, as you love the nation, and as you love yourselves,
and your families and relations, sin not against the Lord;
for he is now setting up righteousness, equity, and justice,
and it shall prevail in the nation.
God has been pleased to gather in many, that have been enemies,
that are now turned from sin to God, and led by the truth: And it is their greatest joy,
that now they are no longer servants of sin, but are now become the servants of God.

Now truth will prevail, and righteousness go forth as the morning sun,
and we hope the Lord will show mercy to us for the glory of his own name,
though we are an unworthy people: It will be matter of joy and gladness to us,
if the kingdom of God be come; then we may say our prayer is answered.
We have often prayed, "`your kingdom come,
and your will be done in earth as it is in Heaven.`"
If the will of God be done, then I can do my own will no longer,
then I can be led away by Satan no longer; the devil will have little power,
if I do God`'s will on earth, as it is done in Heaven;
then praises will arise in the hearts of everyone that delights to do the will of God,
and God will carry on his work for the glory of his own name,
and for the redemption of his people,
that Christ may be preached for salvation to the ends of the earth.
