[short="Christ the Way to Eternal Life."]
== Sermon XXX. Christ the Way to Eternal Life.

[.signed-section-context-open]
Preached at Grace-Church-Street, May 6, 1688.

The desire of all nations is come; that which all people desire in their own way,
is come in God`'s way; for all nations and all people on the earth desire eternal life;
they would all be happy in the other world, and in order thereunto,
they have fitted themselves with various ways and methods,
in which they have proposed to themselves the enjoyment of eternal life;
but by reason of the darkness that is in them, they have erred in their ways,
they have been scattered, they have been driven and tossed here and there,
and can never agree about the way that leads to eternal life.

This comes by reason of the great darkness that is
over the sons and daughters of men in general,
in which they have lost their way, and are endeavouring to find it again:
But the subtle adversary led them out of the way,
and as long as he leads and they follow, they will never find the right way:
The great calamity that is come upon the world in this respect,
is very greatly to be lamented; for when the eye of the mind is opened,
to behold the universal state of mankind,
and to see how they are scattered here and there, and often left in confusion,
by the craft and delusion of the wicked one,
and that none of the ways that they have found,
are like to bring them to the proposed end, because they are defiled, because they are,
unholy; this has bowed down the spirit of the Lord`'s servants many times,
and a great cry has arisen in the hearts of those that have
seen the fruition and enjoyment of life eternal;
O,
that the sons of men might hear! and O that they might consider
their ways before they come to their latter end! for mark friends,
this you may take for a certain doctrine, and a sure rule in judgment,
concerning all the ways that the sons and daughters of men walk in; if they be unholy,
they will be unprofitable; the way of the Lord was, and is,
and ever will be the way of holiness, and the people that walk therein, they were,
and are, and they will always be a holy people;
now the sons and daughters of men have not gone to measure their way by this rule,
but the greatest endeavours that ever have been in the world,
from the beginning (the greatest endeavours that men did undertake) were to see how
near they could approve their doctrine and practice with the scriptures of truth,
and that has been the bone of contention,
that they have stumbled about from one generation to another, one crying my way is right;
and here they have been contending, disputing,
and jangling and debating one with another, and could never agree,
and could never come to that understanding, which is given by the Holy Spirit,
that moved holy men to write the Holy Scriptures of truth; if they had,
it is manifest they would have agreed, for this one spirit must agree with itself,
and will give judgment according to its own righteous judgment:
Men being alienated from the life of God, by evil works, and by the suggestions of Satan,
they have not known the way of peace,
and have not come to that which is the desire of all nations,
as now in the fulness of time, the Lord God eternal,
who created the Heavens and the Earth, the sea and the fountains of water,
he has looked down and beheld the miserable calamitous
state of the sons and daughters of men,
and he has seen how they have been scattered and driven to and fro by idle shepherds,
and how everyone has indulged himself in his own way, though unholy and impure;
and it is because of the darkness of the night of ignorance that has been over the people;
and therefore in his infinite love and mercy, he is risen,
and has brought forth his light and his truth, that the nations might be enlightened,
that they might come and see with a divine eye that the truth is but one,
and the way but one, and all that do really desire to be inheritors of eternal life,
must come to walk in that way.
So that people are never brought back again out of that
way wherein they have been scattered and driven about,
till they come to see the way they practise to bring forth iniquity;
they see there is no light to be had in them, they see the anger of God kindled,
and the indignation of God poured out by reason of sin and unholiness.

Now when they come to be convinced by the light of Christ Jesus of their disobedience,
then they come to feel and find a principle,
a seed and root that gives them a law which they should obey,
and hear the right law-giver, and have respect unto him:
Here is the revelation of Christ Jesus by his Spirit,
and this extends itself in its operation and working to the sons of men,
to them that are afar off, as well as to those that are near;
therefore our continual exhortation, from time to time,
according as the spirit has given us utterance,
is not so much to make profession of this and the other doctrine of Christianity,
as to persuade all men everywhere, that they believe in the light,
and hearken to the voice of the light in their own consciences,
that they hearken to that which is purely of God in themselves, as we know,
whoever comes to love the light of Christ Jesus, with which they are enlightened,
it would discover doctrine to them, and make known faith and practice too;
it will lead them in the way everlasting,
it will open their understanding far above all preaching
this and the other doctrine and tenet.

What signifies it to show colours to the blind, or to speak words to the dead;
till men come to have their senses opened,
that they may discern things belonging to the spirit of truth,
the carnal man cannot understand the things of the gospel of Christ,
the carnal man is not subject to the law of God, neither indeed can be;
there must be something done in the soul, to bring it out of its carnality,
and bring it to something that is spiritual,
before it is capable of understanding the things of the spirit:
Therefore when our minds can witness what we came here for,
when we meet to serve and worship God, we shall have a hope to receive some illumination,
some refreshment, some comfort, or some knowledge of things divine;
it is in vain to attend religious doctrines with an irreligious mind.
It is my judgment of charity, that everyone that comes here,
has some expectation of illumination in their understandings, some gift,
or some instruction; this they may receive from the God of Heaven,
by the ministry of those who must be the mouth of God, to speak to them in his name:
When people are thus prepared, and their minds fixed to hear the truth;
if they do not find it in themselves,
if they come not to a sense of the word of life in their own hearts,
their hearing cannot give them life.
We are commending ourselves to every man`'s conscience; let your minds be turned inward,
search and consider,
is there a light that enlightens every man that comes into the world?
Is there a desire of eternal life manifested in me?
Is there that in me that puts me upon obedience to God, to mend my life and conduct,
that I might be recommended to God?
Is there something in me that checks me when I speak amiss, and do amiss?
I do appeal to the witness of God in you; if that be so,
then believe me for the word`'s sake, the testimony of God in your hearts.

Let us next consider, whether we had best agree on this conclusion,
that God has enlightened us, and whether we had not best obey that light;
this is the best way, let us put the question, and wait for an answer from ourselves.
There is much indeed to be said on the other side:
If I should hear and obey that by which I am enlightened,
if I should hearken to the reproof of my own conscience,
I should lose a great deal of the pleasure and of the comfort of the world,
I should lose a great deal of the profit which I gain in my trade and calling,
and of the delight and pleasure I have with my neighbour.

This is not to be denied; I would have things put in the balance;
I grant you will lose some pleasure, and ungodly gain, and the friendship of the world;
but pray consider, and let us go through the account:
If you obey this light of Christ Jesus,
this is God`'s way of drawing you nearer to himself,
to make you an heir of his eternal kingdom; whereas by your indulging your carnal parts,
you will lose your immortal soul; if you should gain the whole world,
and lose your own soul, what will it profit you?
You should consider, why I am enlightened; how comes it to pass that my nature is evil,
and I am fallen from my primitive state, from the knowledge of God,
and from the enjoyment of his presence, and communion with him?
How comes God to take notice of me,
and to enlighten me and kindle in me a desire of returning to him?
why should he do this for me?
You will never find a reason in yourself of this extraordinary kindness,
of this singular mercy of God to you; it is because his mercy moved him,
and it was his compassion that stirred him up:
He has sent his Son Jesus Christ into the world,
that men might have light in and through him, and have it abundantly.
The mercy of God is a fountain from where all this flows to us;
if this prevail not upon you, no argument will: What, was it mere mercy, mere grace,
that God was not willing to see me perish, and run headlong to destruction?
He was unwilling to execute his wrath upon me,
therefore he found out a way by which I might return to him.
This made a good man cry out, behold! what manner of love is this,
with which the Father has loved us?
Here is the grace of God; here is the good will of God; here is the way; a way, what way?
A way of coming to God; a way of being again reconciled unto God,
whom we had provoked by our sins; a way of enjoying eternal life again,
after we had lost all pretence to it.

The next question is, who will walk in the way that leads to eternal life?
We would all have eternal life; it is the universal consent of all nations;
all would have eternal life; but the question is,
who will walk in the way that leads to it?
Some of the nations round about, and many in this nation,
they will walk in their own way, and yet they would have eternal life;
but their way must be of the same nature and quality with the life they would have;
if the way they walk in be not of the same nature and quality, it will not lead to it.
Let everyone examine their way; let everyone examine their progress,
and their lives and footsteps in this world; if they sow to the flesh,
they shall of the flesh reap corruption; and if they sow to the spirit,
they shall of the spirit reap life everlasting; a suitable fruit to that life they live,
and the way they walk in.
If we conclude with reason; with pure, found reason,
we must conclude it is better for us all to walk in the way of holiness;
and we shall have more reason to believe that we shall have life eternal,
than in walking in an unholy way,
therefore we should be resolved to walk in the way of holiness;
and if people are brought to this, it is an easy thing to draw them to confession:
You say true, it is better to walk in a holy way than an unholy way;
but alas! we have not power so to do; we are feeble, weak, dark and ignorant;
and we have many lusts, temptations and impediments, lying in our way,
that it is not possible for any to walk in that way; we know the way,
we understand the way well enough; you would have us walk by the sight of Christ,
and the dictates of our own consciences,
then we should never be condemned for anything we do,
but we should stand in an openness of access to God; when a man sins against God,
sin lies at the door; but they that sin not, have an access to God.
Alas, these things cannot be done!
What can a poor creature do that lacks power?

My friends, this excuse must go no further;
let us try and consider in the presence of God this day,
the powerful God that is the assister of his people; let us try how far this will go,
I have no power of myself; all good men grant it to be true,
you have not power to walk in the way of holiness: But let us ask another question;
does God require of you and me to walk in the way of holiness,
and does he deny power to us to walk in it?
We cannot walk in the way of holiness, but by the operation of his power working in us,
unto the extinguishing of the life of sin and corruption,
that has hindered us all this while; God knows we cannot do it ourselves.
Christ tells his disciples, without me you can do nothing, nothing good,
nothing that is right.
This being concluded on, all power comes from God; the next question is, how,
and which way must we receive power from God greater than our own power?
Which is the way of people`'s receiving power from God?
You have read how people came to have power; "`to as many as believed,
to them he gave power to become the sons of God.`"
What signifies this to them that do not believe?
If believing be the way to obtain power, it is nothing to those that do not believe;
there faith is necessary, in the first place, for obtaining of this power:
This is a great mystery, such an odd saying, that the world knows not what to make of it:
Believers, we are all believers;
I believe the truth of the principles of the Christian religion,
and I believe all the articles of the creed:
To talk of believing at this time of the day, we have believed this twenty, or thirty,
or forty years, but the first act of faith is yet to be done after your sense:
It is true, with the greatest part of the nation;
the first act of faith is not yet begun, for their faith is men`'s faith:
We are for the faith that was delivered to the saints; it is the gift of God,
it comes from the operation of God; so that I may conclude,
whoever remains a stranger to the operation of God, he is a stranger to the true faith;
and they who estrange themselves from that which God works,
are strangers to the operation of God.
Therefore, till people`'s minds are turned to Christ, whom God has sent,
who is appointed to be for salvation to the ends of the earth;
till men come to reduce the government both of the soul and body to him,
as the captain of their salvation; till they come to be thus resigned,
they cannot come to the true faith.

Now when God works this resignation in us, a man will reflect upon himself and say,
alas I have been my own keeper too long, I see I have gone off from God,
now I will return to him, and resign up myself to the Lord,
that he may work in me what he pleases to work:
When men come to this resignation of soul, they have faith given them,
they must believe God will never leave them nor forsake them,
but he will magnify his power in their weakness; I will rest my soul upon him,
and cast my care upon him that cares for me; it is not faith barely in words,
and in the articles of the creed, but it is a faith in the Son of God,
to whom all power in Heaven and Earth is given; I may expect a share of it,
he will give me a little, if I come to him for it; and if I be faithful in a little,
he will give me more; the reason why you lack power, is, because you lack faith;
and the reason of your lack of faith, is,
because you lack a resignation to the will of God; you will be your own carvers,
and your own keepers and guides.
When you come to this resignation to the will of God, God will give you power,
and then you will find him the God of all grace;
you are what you are by the grace of God, and by his power,
and by that power you will obey his will: Here is faith that gives glory to God,
to that God that takes an unholy man and makes him holy; how does he this?
By his holy spirit, which is as fire that burns up that which is corruptible;
then the man is well (I speak according to the dictates
of the spirit) when he is reconciled to God by Christ Jesus,
the Mediator between God and man, the Mediator of the new covenant, who makes our peace.
That you may come to the knowledge of the day of the Lord`'s visitation,
is what our souls labour and travail for,
that you may be in the unity of the same spirit after the desire of all nations is come;
he is come to you, that you may all say within yourselves,
salvation this day is come to our houses, and into our hearts.
