[short="Sermon XXXII. Christians Should Often Think on the Name of the Lord."]
== Sermon XXXII. Christians Should Often Think on the Name of the Lord.

[.signed-section-context-open]
Preached at Devonshire-House, July 17, 1692.

The people of God in former ages, did often think upon the name of the Lord:
I would it might be the daily practice of all that
make profession to be the people of God in our days,
to think often upon the name of the Lord.
This you know is an inward exercise, invisible and known to none but God;
he only knows when you are met together, whether you are thinking upon his name,
whether the exercise of your minds is upon his power,
or upon whatever else your minds are engaged.
They whose exercise and desire is, to feel God`'s power,
and to be acquainted with his name, the Lord is near to them, to reveal his mighty power,
and his name to them,
and they are a people that partake of his goodness and of his virtue,
and have an experiential knowledge of the various administrations
of both his judgments and mercies to their own souls,
and so they can proceed from thinking to speaking of the goodness
of God from the experience that they have in themselves,
that the Lord is good to them.

For all that some do in their manner of speaking of God and his goodness,
and crying up the name of the Lord, it is all worth nothing, it is but noise:
But everyone that partakes in his own soul of something of the divine virtue
and goodness that flows from God invisibly to him through Jesus Christ,
he has assurance in himself that he speaks the truth: It is not mere words,
made ready to his hand,
but it is his own knowledge and experience of that
which God has wrought in him by his own Spirit;
there are none that think upon the name of the Lord, and his power,
and the working of it, but they are able to speak of it effectually and truly.

I know it has been, and is the practice among many,
that they are able to speak of God`'s goodness from what they find
in the writings and sayings of some that lived before them,
that did bear an honourable testimony of God`'s goodness in their religion;
and they learn to say it over again in their particular age:
But what has this tale that they have told, wrought?
This report they have made, how God was with the Christians of old,
the primitive Christians and martyrs; they have told a tale of these things,
and what has it effected?
It has either brought forth Christians, or it has not.

The way for people to be grounded and settled in divine knowledge,
is for everyone to speak what they know: And if they know nothing of these things,
to say nothing of them.
And the way for them to come to receive divine knowledge, is, by thinking, by meditating,
by considering of that converse that God has with their own souls;
for there is a way provided for all men to converse with God that made them:
Every man and woman may ask questions of him, and may have answers from him,
if they have patience enough to wait for them; every soul here present,
that with seriousness of mind shall ask of God what their state and condition is,
if they were to die presently, God will tell them, he will answer them;
he will shine unto them by the light of his Son Jesus Christ,
and let them know whether they are in the gall of bitterness,
and in the bonds of their iniquity still, or whether they are redeemed out of it,
and brought into covenant with himself: But will you believe his answer?
I would have no man go about to ask such a question of God unless
he has a mind to believe the answer that God gives him.
To what purpose should men ask, if they ask amiss?
If they ask without faith, they do not believe except the answer please them.

Many, in our days, have put up their petitions and prayers to God,
that he would discover to them the state and condition of their souls:
The Lord has answered them,
and notwithstanding all the profession that they have made of his name,
and of their faith in his Son Jesus Christ, and of the work of redemption,
yet he has often declared you are still unredeemed, you are still in your sin, and lusts,
and concupiscence prevail over you; you are still in bondage.
This is God`'s answer to many; but there is something arises in their minds,
that they are not willing to believe this; I would think better of myself than this:
What if you do think better of yourself?
You are never the better, "`for the word of the Lord stands sure.`"
There is no removing of it; there is no denial of the truth.
If this truth condemn you, all the world cannot justify you;
and this truth by which God condemns the sinner is in the sinner`'s own heart:
What will he do with it?
It is in the sinner`'s conscience; it does not only condemn him by book,
out of this chapter and that verse, out of this author and the other author,
but he is condemned by God`'s true and faithful witness, in his own conscience.
You will not believe it; but if you believe not this,
then you remain in your unbelief of the truth;
and nothing else but believing it can save you;
no counsel else can deliver or redeem you.

So that the best advice and counsel that I can give a people in this case, is this;
that when they come to such a religious meeting as this is,
they would come with a mind prepared and fitted to think upon the Lord;
to think upon his name, and the way by which he brings people to himself;
for no man can be called a child of God, that does not partake of his nature.
If a man be ever so wise, and rich, and great in the world;
if he be a prince or an emperor, without this he is a child of wrath.
Now if these children of wrath meet with something that convinces them;
if they are touched and become a sensible people,
then crowns and diadems are nothing to them.
Such a one will say, if I be a child of wrath,
a captive to sin and my own lusts and concupiscence,
yet for all that I will go to a religious meeting,
where I hope the word of God will be preached;
I hope to meet with something there that will do me good;
and I have a desire that I may be translated out of a natural state,
from being a child of wrath, to be brought into the kingdom of God.
If I have this desire in me, God that made me, wrought it in me;
for by nature we cannot so much as think a good thought.
When men think of being better, and of amending their ways, and doing their souls good,
these are very good thoughts in themselves.
When such thoughts are begotten in any men`'s hearts,
I would have them to ascribe them to the grace of God, and nothing else.
Preachers may do much where these desires are begotten;
but it is not in their power to beget these desires.

Many have come to a meeting with loose, profane and wandering minds;
and though many good things have been spoken to them,
it has not reached so far as to beget good desires,
their hearts have been so alienated from the grace of God in themselves,
which is the great superior worker, to which we are but servants and ministers;
there is none can beget anything, but he in whom all power is.
They that are under the power of darkness, the devil begets in them looseness and vanity,
profaneness and hardness of heart.
Some go away from a meeting without being touched and persuaded,
and they have no good hope of being better:
But where people are really touched in their spirits,
with a desire after something that will do them good,
they must come to the fountain of good, the God that made them,
and they must think upon him; if they cannot see his glory, and hear his voice,
yet they can think upon him.
This is the least duty of a Christian, to think upon the name of the Lord,
when their minds are exercised about divine matters,
about the state and condition of their poor souls.
If I die this night, what will become of me?
This and that sin I have committed;
how shall I be able to answer to God for one of a thousand of all my loose thoughts,
words and actions?
They that come to a consideration of this, and a due sense of their state and condition,
though it is such a state that they do not like; though it is not such as it ought to be,
yet notwithstanding it may be better;
they may be brought out of it into a better condition.

Now this is the duty of all, to wait upon God, the fountain of all good,
that they may receive something from God,
for "`every good and perfect gift comes from above,
from the Father of lights,`" the Father of your light and my light,
that light comes to us from the Father of lights:
If we have any perfect gift bestowed upon us, it is bestowed by God;
therefore you will grant that we are all obliged, from the greatest to the least,
to wait upon him, if we have the least expectation from God, by meeting,
otherwise we had better keep away.

But I am apt to judge that the most here are come with some desire,
that if it please God they may receive benefit by their meeting:
Where shall they have it?
They say, if such a man preaches, then I can edify much by him: This is a great mistake;
for, let who will preach, there is nobody can receive any benefit,
but it must be from the Lord, as the fountain of good;
for the best preachers in the world are but instruments in the hands of God;
if God does not bless his labours, the preacher can do nothing to the souls of people;
he can sound the truth in their ears outwardly, but he can reach no further,
God only speaks to the heart.
If you mind the preacher and not God that made you,
all his preaching will do you no good; it may indeed help you to a notion or speculation,
but that comes not to the inside, that will be no better, the inside lacks mending.

There are great deformities, scars, spots, stains,
wounds and lameness upon the souls of men, by reason of their sins,
lusts and corruptions; and a remedy is needed,
and there is no physician of value but God that made us after his own image.
The devil has brought in deformity, he has made one proud, another cruel,
another careless, another an oppressor, another malicious; this is all the devil`'s work:
And for this end Christ Jesus came into the world,
"`that he might destroy the works of the devil.`"
He came to destroy pride, malice and lust; these are the devil`'s works,
that Christ came to destroy: Why does he not do it?
He will destroy all the devil has wrought in every man that will be subject to him:
Can a surgeon set a bone, if the patient be not subject to his hand?

But this is far beyond all comparison; Christ has received all power in Heaven and Earth,
yet he always looks for a willing people; he sends the day of his power upon a people,
and he works upon their hearts by an invincible power;
he makes them willing to be helped, and healed, and cured, and then he cures them.
I dare say, there is not one here that is willing to be reformed,
and to submit to Christ to be saved and redeemed by him, but he will do it;
he that is willing and obedient, shall eat of the good of the land,
and shall know the good of redemption.
See whether it be come to a state of redemption; here is universal grace offered;
for the light of Christ Jesus enlightens every one of you;
it shows you your lost state and condition: When we see our condition bad,
that it is not as it ought to be, who would not have it better?

What means prayer, that Christian duty?
What shall we pray for?
Must not people be sensible in themselves what they should pray for,
before they come to pray?
And what is it that will make them sensible but the light and grace of God?
They see their own needs when God works faith in their hearts,
and they believe that God can supply those needs.
Why should I go to a beggar, to pray him to give me a hundred pounds?
I believe he cannot do it, therefore I will not pray to him for it:
Now necessity brings people to prayer, but there must be faith in him to whom we pray,
that he is able to supply our needs, and relieve our necessities.
Upon this account the apostle says, "`he that comes to God must believe that he is,
and that he is a rewarder of them that diligently seek him.`"
He must first know that there is a God to come unto, and then that he is a rewarder.

Here is the foundation of all true religion and true worship;
they that go to God and say their prayers, and join with others in saying their prayers,
if they have no sense of God, they had as good hold their tongues,
for their praying is to no purpose: They that pretend to believe in God,
without an experiential power of God working upon their hearts,
their belief is not worth a straw; without their respect to the power of God,
all their belief is nothing; but if they know that God has such an operation upon them,
that no man or woman in the world can discover that to them, that God discovers,
then they know that God is the searcher of hearts and the trier of the reins, Jeremiah 17:10.

Suppose I know that there is a God,
and at the same time I believe that he will never hear me;
that I am a reprobate creature, and that he has cast me off forever,
and that he has sealed condemnation upon me, to all eternity.
What reason has such a one to pray?
This is a desperate condition.
But while we believe there is a God,
and that "`he is a rewarder of them that diligently
seek him,`" it is not in vain to pray;
yet there is something antecedent too to prayer; there is knowledge,
and faith by reason of that knowledge, that God is a rewarder: He that has this,
let him pray in God`'s name.
But what must he pray for?
He must not offer the sacrifice of fools; he must have regard to his lips;
if it be mental prayer, he must pray for that he stands in need of;
it is for something he prays, that God has revealed by his Holy Spirit;
this he stands in need of; it is something that he needs;
it is power to overcome corruption, and power to overcome temptation,
that he stands in need of;
he stands in need of a Mediator to procure for him the pardon of his sins:
These things he stands in need of, then let him pray; he that is afflicted, let him pray.

So that if a man or woman go to prayer, they must pray to God,
in the belief of his goodness and mercy, that he will bestow some blessing upon them,
that may be for the better, that may be for their good.
When they come to a meeting, to worship God, and hear the word spoken outwardly,
they must pray for something that may be for their good;
Lord give me something that may support my soul,
and something that may enable me to withstand temptation.
People should have their minds thus exercised,
and they should think upon the name of the Lord according to their particular necessity;
they should pour out their supplication to the Lord:
This is such worship as God looks for, and such as he is pleased with;
he will deliver those that thus pray to him out of temptations,
so that they shall not prevail over them: One man`'s temptation is of one sort,
and another`'s of another sort; but they are all delivered by the grace of God,
and helped over them, upon their prayer to God;
for they find by experience that he is a God hearing prayers.

Now, when we have prayed, what is the next work?
It is to wait for an answer of our prayer.
I prayed the other day to God for power to withstand such a temptation;
when that temptation comes again I do expect that God will answer my prayer.
Do you do so?
Then I pray you have an eye to the same grace of God that convinced you,
and showed you the temptation; and have your faith exercised upon that grace of God,
and you will find it sufficient for you, I will warrant you:
Let the devil come with a temptation ever so suitable and subtle,
keep your eye upon the grace of God, and it will deliver you.
This was the case of Paul; when a messenger of Satan was sent to buffet him,
he besought the Lord thrice: The temptation did attend him,
and God gave him an answer of his prayer; "`my grace is sufficient for you.`"
As if he had said, let the devil come with ever so much power,
he shall never overcome you.

I speak to those that are well skilled in this kind of work,
and have met with sharp temptations,
and sometimes perhaps they have been overcome by them,
and at other times they have withstood them: What is the difference; why,
one while they are loose and careless,
and did not pray for the assistance of divine grace; another while they kept close to it,
and were delivered.

Therefore when you come to meeting, with a desire to receive benefit from God,
with your expectations Godward, to receive comfort from the hands of the Lord,
let your eye be upon him, and the working of his grace in your own hearts,
and hearken to that voice that is within you, and it will be more effectual than mine.
If you find the work of grace in you to be the same thing that I speak of,
then believe me for the truth`'s-sake;
believe me because you find the same work and testimony within yourselves.
And I am persuaded there is no one here,
but sometime or other have withstood that temptation which they have met with.
Pray tell me how they did it?
Why, the temptation came unto me, and it pleased God to show me the evil of it,
that it was a bad thing if I yielded to it.
How did you resist it?
had not the devil a coercive power over you, to force you to it, whether you would or not?
That God that showed me the evil of it, delivered me from the evil;
I was not judged and condemned in myself, because I found myself delivered from it;
there are none of you, if you would not be lazy and idle,
but you might be delivered every day, and have experience in your own souls,
that when the devil comes and tempts,
the Lord is at hand to deliver you by his grace and power.

So that the only way for people to be preserved from sin and iniquity,
is to have a reverent respect to that grace of God which they have already received.
I would have that vain conceit, that has long reigned in the world,
taken out of your head.
When you see a wicked husband, wife, or child, you say,
if they had grace they would be better; I say they have some degree of grace already;
God has sent forth his grace and truth, to teach men to deny ungodliness,
so that I would not pray that God would give my husband, wife, or child, or friend grace,
but that he would break their hard hearts,
that they may submit to the grace of God that is already bestowed upon them.
I believe there is not a person here that is utterly void of all grace;
but they walk not according to it, they trample upon it:
For everyone being endued with a measure of grace, through Christ,
our duty therefore is to have a reverential regard to the grace of God,
that we have received.

What grace have I received from God, may some say?
I have received so much grace from God (you may truly say)
that I can tell when the devil brings a temptation to me;
when he tempts me to uncleanness, theft, wrath, malice, or to deceive my neighbour,
I have so much grace that I can tell I am tempted in such a respect;
the grace of God shows me this is a temptation of the devil: But the question is,
whether I am subject to the grace of God,
and love his grace better than the profit or pleasure of a temptation?
It comes as a bait, but the devil cannot make me do that which he tempts me to;
it is not in the power of all the devils in hell, or of his servants on earth,
to make me do this evil thing:
The light of my own conscience shows it to be a temptation.
Now I am free and at my choice,
whether I will love the profit and pleasure that comes with
the temptation more than the grace of God:
I believe there is no one that has been tried by a temptation, but they can say so:
I leave it to him that searches and tries all your hearts, and knows your thoughts,
to judge whether you joined with the temptation,
that you might have the profit and pleasure of it, or joined with his grace,
that thereby you might have resisted the temptation:
You that have done the one and the other, tell me which is the best bargain;
when you have joined with the temptation,
that you might have the profit and pleasure that came along with it;
or when you joined with the grace of God,
that showed you the evil and danger of the temptation.
The same God speaks to you that spoke to Cain, "`if you do well,
shall not you be accepted?
and if you do not do well, sin lies at the door.`"
If you have yielded to a temptation,
"`sin lies at the door,`" there is a breach made between God and your soul.

The same man at another time, having smarted so deeply for it,
being judged by his own conscience, when he meets the temptation again, he says,
let the profit or pleasure go where it will,
if I yield to this temptation I cannot go to God but as a criminal to a judge;
let the profit or pleasure be what it will, I will not join with this temptation.
Can the devil force you to comply with this temptation?
No, if you be true to the grace of God in your own heart,
it will make you able to resist the strongest devil in hell.
Christ has purchased for the sons and daughters of
men a power to withstand the devil`'s power,
and all his devices and temptations, and you shall obtain victory,
and have dominion over them.
If you have a mind to grow in this dominion, when the devil comes to tempt you,
resist him, and you shall, through the power of Christ, be enabled to overcome.

If Satan tell you of the profits and pleasures of this world,
remember that "`the world passes away,
and the lust of it,`" but peace with God endures forever:
By the grace of God you will be able to overcome the devil and all his angels.
This power is given to all that believe and obey the gospel:
If you would have benefit by it, you must be exercised in resisting of temptation,
and have regard to the grace of God, and the workings of it in your own hearts;
and then you will be able to say, when a temptation comes, promising profit and pleasure,
"`how can I do this great wickedness, and sin against God?`"
Turn your eye to God`'s favour, which is better than life,
and you will be more than conquerors; you will say the fear of God seized upon my soul,
and the grace of God came to my assistance, and was as a bulwark against temptation.
Here praises will go up to God; here will be occasion for you to speak good of his name.
Remember what David said; my soul, praise the Lord,
that has delivered me from the horrible pit.
Thus David and the saints of old praised God in their day, and why should not we?
They breathed forth living praises and thanksgivings
for the deliverances wrought for them;
and shall not we do it?

Now this cannot be done without thinking upon his name,
the name of that God that made us: Here I live in the world, I live and breathe still,
I have health, and strength, and an estate, how came I by all this?
Did I make myself?
No, there is a God that gave me life, and breath, and being;
he holds forth the hand of mercy to gather me to himself,
and to redeem me from all iniquity, that I might serve him without fear,
in holiness and righteousness, all the days of my life: If I believe this,
I shall rejoice in him, and love and praise him,
and daily wait upon him for the accomplishment of his work.
He desires not the death of sinners: If you believe the Almighty,
it is impossible for him to lie, all things are possible to him except that; he says,
he has "`no pleasure in the death of him that dies:`" What would he have then?
He would have you "`turn and live:`" What means does he use?
What I would have done I would use means to accomplish it.
You would say, what means has he not used?
What is it that God does more wish for than that men would repent, return and live,
and be happy forever?
He has created them, and given them life and breath, and continued his grace to them,
that they might have time to prepare for eternity;
and he has given his good spirit to instruct them, but they have rebelled against him.
He has sent forth his word, the gospel of salvation, which has been preached to them;
and he has waited to be gracious,
and exercised much patience and long-suffering towards them; so that I may say,
what means has he omitted?
He has planted them as "`a vineyard, in a very fruitful hill; and he has fenced it,
and gathered out the stones thereof, and planted it with the choicest vine,
and built a tower in the midst of it, and made a wine-press therein,
and he looked that it should bring forth grapes, and it brought wild grapes.
Judge, I pray you says the Lord, between me and my vineyard:
What could have been done more to my vineyard, that I have not done in it?`"

But notwithstanding all your unfruitfulness, the day of your visitation is continued,
the Lord is willing to show mercy to your souls.
This is all the Lord your God requires of you, that you would think upon his name,
believe in him and trust in him,
and wait upon him for the operations of his grace in the use of his ordinances,
and your attendance upon them, and hearkening to his voice, and obeying it,
and so to hear that your souls may live.

I will affirm, that there is none of you here present, whether you be Quakers or no,
but you may meet with the divine operations of the power of God in your own hearts,
if you will regard it, and when you meet with these operations and regard them not,
I cannot help it; if you will resist the good things of the Spirit of God,
I cannot help it; if you will be of that mind, always to resist the Holy Spirit;
if as your fathers did so do you, then you must all perish, both you and your fathers;
there is no escaping but by being subject to Christ Jesus, and his quickening Spirit;
if there be any divine operations that you meet with in your own hearts,
let me persuade you to submit and have regard to them;
for I know the devil is near at hand;
and when people meet with divine operations in their souls,
that humble them and bring down their pride,
and convince them of the danger of their condition,
he lies in the way and suggests some poisonous thing
that takes off the edge of these operations,
that, they may dislike them: It is true, they meet with the convictions of sin;
but they reckon they have that faith and belief in Christ,
that does in the sight of God obliterate all their sins that can be laid to their charge,
both past and to come.
If I would look, say they, to the divine operation, or anything wrought in me,
it were enough to make me mad; I look wholly to the merits of Christ;
my mind is wholly fixed upon him who is the author of eternal salvation;
his meritorious sufferings and obedience can obliterate and blot out all my sins.

My friends, I tell you,
many a poor soul has split upon this rock by undervaluing
the divine operations of the Spirit upon their hearts;
they make a false and wrong application of the merits of Christ,
which indeed are so great that nobody can overvalue them;
but we must not make a false application of them,
"`for this purpose was the Son of God manifested,
that he might destroy the works of the devil;`" he takes away the guilt of sin,
not that you might live in it still: Whoever believes in Christ,
shall have power over their sins and not be under the dominion and power of sin;
"`sin shall not have dominion over you; for you are not under the law, but under grace.`"
"`But God be thanked, you were the servants of sin;
though you have obeyed from the heart, the form of doctrine which was delivered you:
Being then made free from sin,
you became the servants of righteousness,`" Rom. 6:14,17-18.

But you will say, I am guilty of a great deal of sin already,
what shall become of me for the guilt I have contracted?

"`If we confess and forsake our sins, he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness;`" and "`the blood of
Jesus Christ his Son cleanses us from all sin;`" 1 John 1:9, 1:7.
Here is a true application of Christ, his merits and righteousness;
when there is a confessing of sin to God, and a forsaking of it,
here is an offering and a sacrifice made to God by
our Lord Jesus Christ for the expiation of sin;
he has by his precious blood purchased the pardon of all my sins,
that he might present me to God "`without spot or blemish;`"
here is a true application of the righteousness of Christ;
but how can I apply it to myself while I live in sin?

Here God`'s witness in the conscience of a sinner pleads against the sinner;
when he endeavours to believe that his guilt is taken away, and all his sins, past,
present and to come, are pardoned, while he continues to live in sin,
and sin has yet dominion over him.

Take heed you split not upon this rock; if you be humble Christians,
you will think upon the name of the Lord;
and when you find the operation of God`'s power begetting
good desires in you to hate sin and love righteousness,
you will then believe; you will then pray to the God of all grace;
for the prayer of the faithful is acceptable to him:
"`The effectual fervent prayer of a righteous man avails much,`" James 5:16.

Let your supplication therefore be poured forth unto God,
to endow you with power and wisdom to subdue all your spiritual enemies,
and to conquer your concupiscence,
and the inordinate desires and affections of your own hearts,
that you may take up the cross of Christ and follow him as your great pattern,
and in his name, and by the help and assistance of his Holy Spirit,
you may know how to overcome all temptations.

=== His Prayer After Sermon

Most glorious Lord God! wonderful is your great power over all,
which you have revealed and made manifest in this your blessed day.
Your arm, O you Almighty God! is stretched forth;
you have touched a remnant with a sense of your divine love,
whom you have gathered unto your name; you have revealed your great salvation,
and therewith you have made glad the souls of your children;
you have endeared yourself unto us by the discovery
and manifestation of your abounding love,
who did love us, when we were strangers, and did preserve us when we were enemies,
and brought a glorious day of visitation upon us,
and opened our eyes to behold the light thereof,
so that we were a people engaged to speak good of your name.
You have declared and manifested to the sons and daughters of men your good will,
and your universal grace that you are daily extending to them,
that all may be made partakers of the riches of your house,
and of your great salvation which by the Lord Jesus Christ you have ordained.

And, O you powerful God of Life: since the day that you first gathered us,
you have been with us, you have been our guide,
and our eyes have been towards you for instruction,
you have taught us and led us in the way in which you would have us to walk;
you have led us, O Lord, in the way everlasting with the poor,
the humble and the meek of the earth; and you have placed our feet, O Lord,
near the everlasting mountain, which you have exalted upon the high hills of the earth,
and you have revealed the glory and the splendor of your house, your holy dwelling place,
and have raised breathings in the hearts of your people,
that they may dwell in your courts forever: And now,
Holy Father! you have gathered a remnant,
and brought a peculiar people to trust in your name;
but still we do all that we do by you; you must be our keeper, you must be our preserver,
therefore we wait upon you; we expect all from your hand,
therefore our applications are unto you, that from day to day, and from time to time,
we may find your living presence in the midst of us.

And, O living God of Life! you have given your children large
experience that you are a God near at hand to us,
in all our trials, in all our exercises; as our eyes have been turned to you,
you have preserved us, and revealed your heavenly power, O Lord,
in preserving and delivering your church and people,
that they may bear a testimony in their generation for your great love,
and the great salvation that you have wrought for them and made them partakers of.

Now blessed God of Life! the desires and supplications of your people are unto you,
for the glorifying of your power, and the exalting of your glorious name.

O Lord! let the mighty operation of your power bow down all stout and stubborn ones,
that have rebelled against you, and that have withstood the tenders of your grace,
and the motions and strivings of your Holy Spirit: You are able to bow them,
and to break their stony hearts; you are able to speak effectually to their souls,
and to make them submit themselves to you.

Holy and living Father! let the progress of your word and gospel be great in our day;
let it have a free course and spread itself mightily to those that believe not,
to beget a feed of faith in their souls, that they may believe in your name,
and trust in your power,
and wait to see the great work of redemption wrought
for the salvation of their immortal souls,
before the day of their visitation goes over.

Powerful God of Life! your little remnant which you have redeemed,
keep them by your power, and preserve them in uprightness and cleanness of mind;
preserve them in the places and stations wherein you have appointed them to dwell,
that so in all the trials, and tribulations, and distresses, that may come upon them,
they may be quiet and still, and in patience possess their souls;
and let them have strong consolation in that everlasting
covenant which in your Son you have made with them,
and revealed to them;
and let them not he moved and tossed with the hurries of this world,
with the tumults and disorders that evil men make in it,
and the storms and the tempests that are raised;
but let their hearts and minds be stayed upon you,
that they may know how to behave themselves towards you and one another,
and towards all that are without,
and thereby glorify and magnify your great name by
the beauty of holiness shining in their conducts,
which may reach the consciences of men, that all that see them may say,
these are the plants that the right hand of God has planted,
and see the fruits that are brought forth from that
root of life revealed in Christ Jesus.

Powerful God of Life! carry on your own work in this city and the whole nation,
and in other places among the people which you have
chosen and gathered to yourself out of the world.

Powerful God of Life! remember those that groan in secret, making their moan to you,
that they cannot lay hold of your salvation for their souls:
Prepare them for that consolation that their souls are breathing after:
They are night and day wrestling with you by earnest prayer,
but what will all their wrestling signify,
except your word and the power of your grace assist them,
and teach them to lay hold of your strength, that they may fight the good fight of faith,
that they may get the victory, and rejoice in your salvation, and see the glory of it?
You see how the children of men are working and contriving
various ways for their own salvation;
make them to know that all their own ways and inventions are in vain.

Blessed God of Life! confound the devices of the
ungodly that seek to lay waste your heritage;
and all those that you have gathered by your word, do preserve them,
that they may serve you with sincere and upright minds all the days of their lives;
and offer up daily thanksgivings and living praises to you, the true and living God,
and Jesus Christ whom you have sent, through your eternal Spirit, who alone are worthy,
God over all, blessed forever and ever.
Amen.
