[short="The Great Mediator of the Everlasting Covenant."]
== Sermon I. The Great Mediator of the Everlasting Covenant.

[.signed-section-context-open]
Preached at Grace-Church-Street, April 25, 1688.

[.salutation]
My Friends,

How should we all admire the workings of the Holy Ghost!
You may know from your own experience, that all the operations of the Holy Spirit,
from the beginning, have been in order to the cleansing, and purifying,
and preparing you for the kingdom of God.
This experience is given to a little remnant, to know that the manner of his working,
that the end, aim and design, of all the operations of his power, is for our good,
and in order to our eternal happiness.

Now, this is a great engagement upon the minds of the people of God,
diligently to wait upon him,
that they may be opened more and more into the mystery of life and salvation,
that hath been hid from ages and generations, and is now revealed by his spirit.

And they that are thus exercised with the measure of grace given unto them,
they do grow and increase in holiness and righteousness, by the working thereof;
and they increase in knowledge in the great things of the law,
and the mysteries of the kingdom of grace: By the eye which God hath opened,
they discern, that the working of his power in all ages, has been for the extirpating,
rooting out and destroying of that root of iniquity,
that hath brought forth such a crop of sin and wickedness, which was not of his planting,
nor of his creating.

For, from the beginning of the creation of God, unto this day,
God hath had a singular love and favour to the sons and daughters of men,
as being (as I may say) the masterpiece, or greatest piece of the creation,
most nearly related to himself, created in his own image, in righteousness and holiness;
and in that they now are not so, but marred, and spoiled from bearing the heavenly image,
is not the Lord`'s doing, but hath been wrought by the enemy both to God and man;
yet the Lord continuing his love unto the work of his hands,
hath from age to age revealed and made known his power,
for the restoring and bringing back again lost man, fallen man, sinful man,
to be reconciled unto him; that he may, as was intended,
enjoy and possess the love and favour of his Maker;
but there was no possibility found for his reconciliation with the holy God,
but by making him holy: For as the making him unholy, separated him from his Maker;
so the making of him holy again, would unite him again unto his Maker:
So that there must be a way and means for the reducing of him to his primitive state,
before he could enjoy and obtain his primitive enjoyments; that is,
the love and favour of God: And there hath been a general universal sense,
upon the sons and daughters of men, of this alienation, and estrangedness from God;
and they have put themselves upon divers ways and methods to obtain reconciliation,
and to try if they could restore themselves; and they have found out ways,
and tried and proved the inventions and imaginations of their own minds,
in their fallen wisdom, what they might do to please God, and be reconciled to him.

We are sinners, and we will sacrifice, we will bring a sacrifice for our sins;
and when men have brought a sacrifice, it hath not been accepted,
because there hath not been a Mediator known, that might mediate for them with the Lord;
so that all the sacrifices they have offered, have never been accepted with him,
in order to an atonement and reconciliation.
Now only those that have relation to the Mediator by faith in him, doth he intercede for,
that he might present them again to God;
and this hath been the difference between sacrificer and sacrifice,
from the days of Cain and Abel, unto this day.
Some have had relation to the Mediator in all their services and sacrifices,
and some have had relation only to the thing offered, and the service performed;
but they have not in all ages sped alike:
They whose service and worship was performed to God, with a relation to the Mediator,
they have found acceptance;
and they whose worship and service was performed
only with a relation to the thing offered or done,
that was but their own act, that was but their will-worship,
and that was always turned back again upon them;
for "`there is no name given under Heaven,
by which any can be saved,`" but only the name of Jesus Christ;
that is the Mediator of the new covenant, for the old one was broken:
And when Aaron was set up to be an high-priest to God,
he was appointed to offer sacrifices for the sins of the people,
and he that committed a sin,
was appointed by the law to bring an he-goat of the flock unto the door of the tabernacle,
and to deliver it to the priest,
and he was to make an offering for the sin committed after such and such a manner,
and it was to be an atonement with God for him: So here was seemingly,
a reconciliation by a sacrifice; and some saw no further than the bringing of a goat,
and a ram, and the performance of the priest`'s office, and they counted all was well:
And others saw farther, long before the apostle spake or wrote it,
it was not the blood of bulls or goats, nor the blood of a ram,
that could purge away sin from their consciences.
And after the apostle had opened the mystery of Divinity,
who had a divine and spiritual skill, in unfolding the restoration of mankind,
he declared plainly, that when the offering was made by Aaron for sinners,
even then there remained still a conscience of sin;
"`for it was not possible that the blood of bulls and goats,
should take away sin:`" So that their outward performances, and their outward services,
they did but point out the Mediator; they had a pointing finger, as it were, to the real,
true and everlasting Mediator, Christ Jesus; who is made a Mediator betwixt God and man;
that by and through him, man might be again reconciled to God.

So that now in these gospel-days,
wherein God is opening the mysteries of life and salvation, to the intent and purpose,
that the sons and daughters of men might be restored again
into their primitive enjoyment of the favour of God;
now in these days, it is the duty of all Christians,
and of all that are seeking the welfare of their immortal souls,
to have their eyes and hearts unto Jesus,
as unto one that is able to reconcile them unto God; to him it is committed,
to him wisdom and power is committed, and to him authority is committed,
that he should be an everlasting high-priest; and that all the services,
and all the worship and religious performances that people offer up to God,
should be in his name, that so by him they might be recommended to God:
For none will find acceptance with the Father,
unless in all their performances they have an eye unto him.

So that it comes plainly to pass,
according to that short and confident assertion of the author to the Hebrews,
that "`without faith,
it is impossible to please God:`" But it is possible to offer sacrifices without faith,
and possible for people to perform religious services without faith,
as woeful experience hath taught us in our days,
that many have been exercised in a kind of religious service,
that never in their lives had faith enough to believe the things that they pray for,
and they are without faith.
When people pray to God to send his Holy Spirit into their hearts,
that they may keep his commandments to their lives end, and have not faith to believe it,
and when they pray, "`Thy will be done on earth,
as it is in Heaven,`" it is a religious performance; but if it be not done in faith,
it is but an increasing in sin, and an addition to sin.
Where is the man that is exercised in praying to God,
that believeth that ever such a thing is like to come to pass?
Go where you will in this or the other nation, and inquire of people about their faith;
they believe there is no possibility of extirpating and rooting out of sin,
while they live upon the earth; therefore all their prayers for it are vain,
and their faith a vain faith: And it is high time in such a day as this,
when men are faithless and unbelieving, to preach up the object of faith,
the Lord Jesus Christ.
People are of divers faiths, and of divers beliefs; but we have found by experience,
that they do them no good, they do not bring a thing to pass,
that of necessity must be brought to pass, before they can be reconciled to God;
their faith doth not cleanse the heart,
nor extend so far as to believe that ever they shall be cleansed;
in all the worship and religion that they perform, they come not to this faith,
that they shall be made clean: All that is done is but in sin and uncleanness;
they cannot bring a clean sacrifice out of an unclean vessel:
And our Lord Jesus Christ saith concerning this subject,
"`an evil tree cannot bring forth good fruit;`" but
there must be good fruit brought forth;
how must we do it?
Make the tree good, and the fruit will be good.
When men`'s vain janglings about religion and religious fancies come to an end,
then all this religion will appear to be in vain,
and will not answer the end for which it is performed,
till men believe that it will make the tree good, and cleanse the heart,
and transform men by renewing the spirit of their minds.
So that religion must begin within; and it is not our changing of forms of worship,
from one form to another, and taking up this and the other opinion,
that doth change our hearts.
Sad experience doth teach us,
that men may carry over their old lusts into a new religion;
we can carry over our old inclinations into our new opinions:
For though the form of worship be changed, the heart remaining unchanged,
and the lusts unmortified, their religion is in vain,
let them be of what persuasion they will.

Now the remedy of this great calamity, that hath overspread all sorts of people;
for there is no sort of people,
but there are those among them that are under this great calamity,
of holding the profession of godliness with an ungodly mind,
and the profession of truth with a false and treacherous spirit.

And for the remedying of this,
there is but one way that all men be brought off from having their eye unto their performances,
and to the doctrines and tenets that they hold, and do, as the apostle saith,
fix their eye upon Christ, and look upon Jesus.
This is the first thing that must begin our religion;
for Christ must be the Alpha of our religion, as well as the Omega of it.
If I begin not there, let me begin where I will, I begin wrong;
let me begin at the most serious and sound doctrine,
and at the most apostolical religion;
if Christ and his apostles were here upon the earth; if I walked among them;
if I believed all they said and did, I should begin wrong,
if I did not fix mine eye upon Jesus Christ, that is the taker away of sin,
and is the sanctifier of the soul by his Spirit.
There must be the beginning, and there must be the conclusion; he is the author,
and the finisher of all true faith.
There are authors of other faiths: Men have their different faiths, and creeds,
and articles, and they have exposed and imposed them too; but this is the worst of it,
none of them are right;
let them be exposed and imposed with ever so much force and violence,
none of these will cleanse the heart;
but that faith which is delivered over by Christ Jesus,
that hath the quality of cleansing and purifying; that is the faith when all is done,
that will do the work; that is it that will save and sanctify,
and do the business that all the world is about.
Everyone would have a reconciler with God, and sin rooted out,
and be as God would have them be; this is the public profession of Christendom;
at least they would find out something by which it might be done:
Although many are willing enough to continue in sin and drunkenness, whoredom,
lying and hypocrisy; these are a sort of fools, that make a mock of sin,
and that swim in the stream of pleasure; and what care they,
so long as they make a profession of christianity?

But I am speaking of a people that are struggling under their corruptions;
that would mortify sin, and serve God in holiness and righteousness,
and do God`'s will "`on earth as it is done in Heaven;`" and do it not in form,
but would have power to do it; and they have tried several ways to do it,
and it is not done; and many have been at this work till grey hairs are upon their heads,
and it is not done.
Now God hath given Christ to make reconciliation; now how can we,
that have the love of God extended to us, but extend our good-will to our friends,
and signify to them, that all the travail and pains they are at,
and all the prayers they make,
will do nothing till they have their faith fixed upon Jesus,
that is able to save and deliver them,
and "`save to the uttermost all that come to God by him.`"

But here some will object and say, it is true what you say,
but is it needful to preach such doctrines to us?
for we all believe in Christ, that is, the only Mediator and Saviour.
We know that Christ Jesus is the only Mediator, and that unless he commends us to God,
we cannot be accepted of him.
This is our general doctrine, therefore what need it be urged and pressed upon us,
that are come into the faith already.

Let me search into the matter;
it is of greater importance than to search into a bargain of worldly things.
Men would fain have others open and discover to them wherein they may be cheated,
to prevent their being imposed on in a worldly bargain.
I hope then they will hearken to know how,
and wherein they may be deceived by themselves,
and deceived by others in matters of eternal concernment.
There are no Protestants, but that reject any Mediator but Jesus Christ,
and believe that no Mediator can reconcile them to God, but Christ alone,
and they say he is the object of their faith.
I would ask them this question, whether they believe in Christ at a distance,
or as present, really present with them?
If their faith be historical and at a distance, that they believe in Christ,
as one born of the Virgin Mary, and was crucified and dead before they were born,
and arose again, and ascended into Heaven, and is set at the right hand of God,
if the reason of my belief be, that I have heard of this relation of Christ,
or whether the reason be, because by his Spirit, he hath visited me in this age;
the one is, I believe, because good men have told me so; but the other is, I believe,
because, by this Spirit he hath promised to send, to lead me into all truth,
he hath visited me.
Now let me examine whether I am aware of such a spiritual visitation,
by this quickening Spirit, which is the Lord from Heaven,
and not only the Lord in Heaven.
Whether I am aware of such a quickening power and virtue,
which I have received upon my spirit,
that he is not only at the right hand of God on high in Heaven,
but is now come to knock at the door of my heart, and hath raised in me a life,
as opposite to sin, as his was.
Let me consider if I be aware of a secret touch of his quickening virtue upon my soul,
whereby he hath begotten me into a life opposite to sin; so that if sin remains,
it remains as a burden, and oppression upon me, so that I am a sufferer;
for as much as I am quickened, and made sensible of a better life, of a godly life,
I would fain be at it, and live in it, but iniquity, lust and corruption lie in the way.
He that hath quickened me so far, as to bring me to a sense of the burden of sin,
my faith tells me, he will take the burden off, else my faith will do me no good,
if corruption still prevail upon me, if my faith tells me this,
it will tell the wickedest man in the world as much;
but if my faith tells me I am a sinner,
and my sins consist of this and the other evil thing I do, and am inclined to do,
it tells me again, that he that hath quickened me, and brought me to a sense of sin,
he can take the burden off from me.

Here now is a true faith, that begins in conviction, and ends in true conversion;
this is the word of faith, delivered to the saints, and which we are to preach.
They said of old, that the word of faith, they had to preach,
was that which was nigh in their mouth, that they might receive it, and do it.
I have something nigh that reproves me for sin; if I be obedient to it,
then faith gives me victory over that which is sinful, for which the world reproveth me;
and as I see faith gives me victory over any corruption,
which I have been struggling under,
I am encouraged to fix my faith upon him that hath thus quickened me:
So that this is the difference between faith in Christ at a distance,
and faith that quickeneth me by God`'s Spirit;
that Spirit that hath been so much slighted in our days,
by the highest notionists in our age; they supposed it to be a mere fiction;
some have mocked and derided,
and others have been discouraged to speak of the Spirit of Christ,
and his operation upon the soul; some have declared both in the press and pulpit,
that they have had no experience of the touches of God`'s Spirit upon their souls.
But our experience hath brought us to another degree of knowledge.
We know, and you may know if you please, and that before you sleep,
that there is a way opened, God has made way for his Spirit to reach the spirits of men,
to signify immediately to their spirits without means, herein thou doest wrong,
and herein thou mayest have life, and seek after it.
Now the Spirit that thus worketh, is the Spirit of Christ,
the Spirit that proceeds from the Father and the Son,
that voice in men that tells them they might believe and be saved.
When he comes, saith Christ, "`he will lead you into all truth.`"
How shall the world know this is he?
He shall convince them of sin.
If there be any convincement that ariseth in man of this and the other sin,
it must be from the way the Holy Spirit hath upon their spirits;
he hath a way to speak to men, and everyone that is a lover of his own soul,
is bound to hearken to that voice.

"`In the latter days,`" saith the Lord,
"`when I shall raise a prophet in the midst of you, whosoever will not hear that prophet,
shall it cut off.`"
All commentators agree on this text, that that prophet was no other than Christ Jesus;
it was not John the Baptist, nor Paul, nor Peter;
but Christ that was promised to be raised.
There was such an absolute command went along with that prophecy,
that all should hear him, and it had a threatening at the end of it,
that all that will not hear him, shall be cut off.
Are they not whoremongers, and drunkards, and liars, that will not hear this prophet?
They will not hear him, because they love their sins.
What becomes of them?
They are cut off from the enjoyment of the love and favour of God,
and when they draw nigh to God in prayer, and other religious exercises, it is with them,
as it was with Cain, sin lies at the door.
When they come into a storm at sea, or are arrested with sickness,
and death looks them in the face, they would have peace, but there is distress,
and trouble in the room of it.
What is the matter?
Wast thou not baptised in the Christian faith?
Did not the minister tell thee, that thou art a child of God,
and an inheritor of the kingdom of Heaven?
Alas! my sin lies at my door; O! that I had time to live a better life!
What ails thy life, man?
My life hath been a life of deceit, lust, and vanity, corruption and hypocrisy.
Did not thy teacher teach thee, that a believer hath no guilt upon him,
but that all his sins are pardoned from the day he became a believer?
This doctrine will not hold in a storm, though it will do in fair weather;
when men are swimming in their pleasures, it will serve them;
but when they come to deal with their Maker, no faith will serve them,
but that which purifies the heart,
and that which makes a change from the earthly image to the heavenly.

It were better for you and I, and everyone of us,
to take these things into consideration, while we have health and strength,
and while some sand (as I may so speak) is in our glasses, to consider what is my faith?
What is the object of it?
Have I a dependency upon my duties, and alms, and good deeds?
They will fail me.
But if my dependency be upon Christ as a Saviour, and a Sanctifier,
and my sanctification is carried on gradually,
he that hath begun a good work in me will perfect it.
And if the reason of my going to meetings, and going into my closet,
and bowing myself before the Lord,
is to keep close to him that carries on the work of sanctification,
he will work all my work in me and for me.
I cannot expect to live in the world, but I shall meet with temptations;
the Devil will tempt me, but my Saviour will be nigh me,
as nigh to me as the Devil can be; if I will keep close to him, he will keep close to me.
"`My Father,`" saith Christ, "`is greater than I,
and none is able to pluck you out of your Father`'s hands.`"
I must expect to be tempted;
"`for the adversary the Devil goes about like a roaring lion,
seeking whom he may devour.`"
Alas! saith one, though I have made some progress in the work of sanctification,
yet for all that, he may one day betray me.
Am I grown strong enough to resist his temptations?
and wise enough to foresee all his gins and traps, which he lays to ensnare me?
But I know who can see them, and defeat them.
I have my faith fixed upon one that can bind the strong man, and cast him out.
The life that I now live, is not in my own parts, and by my own understanding and sense:
"`But the life that I now live, in the flesh, I live by the faith of the Son of God.`"
This is that faith that gives me victory.
The apostle had a battle for it; "`I have fought the good fight;
and henceforth is laid up for me a crown of righteousness, and not for me only,
but for all them that love the appearing of our Lord Jesus
Christ;`" and that come to have familiarity with Christ,
with his Spirit and truth, with his grace and word, in their hearts:
Though these are several expressions, they all signify one immortal seed of life,
by which men are united to God: It is a leaven there,
to leaven them into the Divine Nature.

Whenever such a one is tempted, he resists not the tempter in his own power,
but he waits to feel the arisings of that life, and power,
and virtue that was in Christ Jesus, and is in him still: He waits for that power,
that in the name of Christ he may say, "`Get thee behind me Satan.`"
Being fortified by Christ`'s name, and armed with his power,
what is it that a Christian cannot do?
What valiant, noble and wonderful things have they done,
that have been shielded with this faith?
See the eleventh chapter of the epistle to the Hebrews.
All the repetitions of that chapter, from one end to the other;
in all of them the apostle ascribes all the valiantness
and courageousness of those noble acts,
to the power of faith.
They looked to Jesus, before ever the Virgin Mary brought him forth out of her body.
The prophets did earnestly seek to know those things,
which the Spirit of Christ that was in them, did signify unto them,
that there was to be this great Prophet, before ever the Virgin Mary was born:
So that Christ was always the object of a true believer`'s faith.
Though under the law they had an high-priest, and he was placed at the altar,
and they had offerings burnt upon it, yet they had an eye unto Christ,
they had an undervaluing of all that their sacrifices could do for them.
If thou wouldest have had burnt offerings, saith David, I would have given them;
I would not have withheld them from thine altar; thou shouldest have had enough of them.
He was bold to say, in respect of acceptance and reconciliation,
"`burnt offerings and sacrifices thou wouldest not; a body hast thou prepared me;
for it is written in the volume of the book, I come to do thy will, O God.`"
He had an eye unto Jesus that was to come, upon whom help was laid: There was a Redeemer,
that should come from Zion, and a law-giver from Jerusalem.
They had an eye beyond sacrifices, unto Christ.
In all ages the people of God have had the answer of their souls,
which is reconciliation, and the favour of God: They that had this answer,
never had it but by Christ.
No man can be accepted with God,
can ever have the desire of his soul answered in peace and reconciliation with God,
until his faith be placed on Christ Jesus:
Neither can any man have faith in Christ at a distance,
and thereby be reconciled unto God, but must know his Spirit.
I must have an experimental knowledge of his power and wisdom,
and this I cannot have without his Spirit: Let me believe ever so orthodoxly,
except I have the Spirit of Christ, it will do me no good, it will be no advantage to me.

This is the word, that was in my heart as a well-wisher to the souls of all men:
As God hath done good to my soul, so I cannot but wish well to the souls of others;
that as he hath found out a way for my redemption and salvation,
so likewise I wish the same for others that are bond-men and bond-women,
and under the power of their corruption.
God`'s work hath been to destroy the bondage and the oppression,
and to destroy the tyrant that reigns over the souls of people;
God having made them for his glory, and the Devil has stolen them away,
that they do not that which pleaseth God: But God`'s good pleasure is,
that all may be saved, and come to the knowledge of the truth.
And "`God so loved the world, that he gave his only begotten Son,
that whosoever believeth in him, should not perish, but have everlasting life.`"
And he is called, "`the Lamb of God, which takes away the sins of the world.`"
He can take away sin; if my sin does not obstruct my faith and confidence in him,
he will take it away; and if he takes that away, then he makes the tree good.
Nothing hinders us from the enjoyment of God, but sin;
and if Christ will take it away by the blood of his cross, no matter for all the scorn,
contempt, hardship, reproach and persecution of this world; no matter,
for he hath not deceived us, but told us before hand, if we will be followers of him,
and be led by him; we must expect these things; sufferings, reproaches, persecutions,
disdain and envy.
These things come not uncertainly upon us; the world loves its own,
and cannot love them that are not of it; but they that are not of the world,
may be brought to the terms of God, and they may not be any longer in the world.
Christ prayeth not that his disciples may be taken out of the world,
but kept from the evil: So that Christ is a Mediator, and a propitiation for all men;
and he is working by his Spirit for the redemption of all men,
that "`to as many as believe in him, to them he gives power to become the Sons of God.`"

The sum of all this is, that we have an opportunity put into our hands;
we cannot deny it; you must all upon search, confess,
that the grace of God doth often work in your hearts against any corruption,
against any evil: Let not this price be put into your hands in vain,
as into the hands of fools.
If I knew that this and that was a sin, I would leave it; let us be of that mind,
and we shall soon know it; and then say, if I knew such a thing to be a sin,
and could get a thousand pounds by it, I would not do it,
Why should`'st thou love sin for profit or pleasure?
I am sure it is an ill bargain when it is done.
Whatsoever I am convinced is a sin, I will not do it.

Resolve upon this, and then the grace of God will be at work;
we shall soon see that we must leave off sinning.
There is such a thing I must leave; God hath set up a judgment in my mind against it;
though it bring profit and pleasure, away it must go.
Here is a step, a following step, to follow Christ.
He that will deny himself, will follow Christ: My Redeemer shews me this to be an evil,
I will not do it, but follow him, and imitate him.
Here the soul is led step by step, even by Christ, the Captain of our Salvation,
till it is gradually cleansed from sin, and reconciled unto God;
and this can be done by no other means; for prayers and alms will not do it;
all that can be done by us will not do it; none can do it but Christ alone,
that God hath laid help upon,
that you may all wait for the Divine operation of his grace in your hearts.
That is it which we labour and travail for,
as knowing that God hath wrought wonderfully by it,
for the redemption of all those that love him more than they love their pleasures,
more than they love their sins.
It must be concluded, that following of him, and leaving father and mother,
husband and wife, children, brethren, and sisters;
all these things as they stand in competition with him, and the obedience of his Spirit,
must be looked upon as nothing to him: Then above all things, I must not displease him:
He can speak peace, and none can take it away; and if he take it away, none can give it.
If we follow Christ, when this is done, then all is done according to the will of God;
then the blessing descends upon the whole creation;
then every man will speak truth to his neighbour,
and every man will govern his family with discretion; so God is glorified,
and his name comes to be exalted; who is worthy to be beloved, adored,
and exalted above all blessings and praises.
To him be glory, who is God over all, blessed forever and ever.
Amen.

=== His Prayer After Sermon

Most glorious God of life and power, and of everlasting kindness;
a God of long-suffering and patience, else we had not been here at this day.

Lord, we are monuments of thy mercy! thou hast spared us long,
and hast called unto us in a day when we turned away our ear from thee:
Thou hast stretched forth thy hand all the day long,
and thou hast gathered a little remnant of the lost sheep
of the house of Israel to partake of thy pastures of life;
and now all our souls have been greatly refreshed and comforted since
we came to understand and comprehend with the rest of thy saints,
the height, and length, and breadth, and depth of thy love, which in the Son of thy love,
thou hast revealed to us.

And, blessed Father of Life! our souls do breathe and cry unto thee,
on the behalf of strangers, which are aliens from the commonwealth of Israel,
that are yet breathing and inquiring after thee, asking the way to Zion.

O Lord! remember them and hear their cry,
and let their sighing and complaining enter into thine ears; that all they,
in whom thou hast begun to kindle holy desires after thee,
may have them grow into a flame, to burn up all enmity to thee;
that so they may be purified by thy judgments, and receive of thy heavenly grace.
This is the way which thou hast used with thy children;
thou hast commanded them to worship thee in thy dwelling-place;
thou hast taken them into thy house, and fed them with thy finest wheat,
refreshed them with thy lovingkindness, and filled them with thy Holy Spirit.

Dearest God of Love! this is the design and purpose of our meeting together,
that we may enjoy the presence, and feel the operation of thy word,
and have communion with thee, and thy Son Jesus Christ, through thy Holy Spirit;
the way into rest and life is with thee.
Thou canst open, and none can shut.
Lord! open the hearts of this people, to receive of thy goodness,
and receive of thy blessings; that so everyone may be sensible,
that thou art at least knocking at the door of their hearts,
that thou mightest have an entrance, and bow the hearts and wills of all,
to receive what thou givest and hast to offer; to receive the word of life,
by which thou art quickening them, and kindling holy desires after thyself,
that everyone may receive the truth in the love of it:
That so blessed God of Life! thy glorious work of redemption may be carried on,
and we may all feel it carried on in our souls.

Hear thy poor people that are crying unto thee,
the God of gods in Zion! that are sensible of their weakness and feebleness,
and how unable they are to overcome the enemies of their souls: Arise in thy power,
O Lord! and these enemies shall be scattered;
let the souls of thy people be raised from the dust, and delivered from their sin,
that they may rejoice and praise thy name for their deliverance.

Righteous God of life! our eyes are unto thee, to set forth thy glory,
for thou hast made bare thine arm for the salvation of the poor and needy souls,
and thou hast been stretching forth the cords of thy love to gather them that were scattered;
and hast been bringing home to thee,
those that were hurried away in a dark and cloudy day.

Thou hast made us sensible of thy operations;
and hast constrained thy servants to labour in the word and doctrine,
for the gathering of such home; that so they and we may enter into thy holy covenant,
and may sound forth thy praises to the ages and generations to come: That so,
Holy God of Life and Love! thou that hast saved us with a marvellous salvation,
mayest receive for all thy mercies, and blessings to thy children, praises, glory, honor,
and thanksgiving; for thou alone art worthy, who art God over all, blessed forever.
Amen.
