[short="The First and Great Commandment."]
== Sermon III. The First and Great Commandment.

[.signed-section-context-open]
Preached at Devonshire-House, May 27, 1688.

When God gave forth his Law on Mount Sinai, which Israel was to hear and obey,
the first and great commandment was, "`thou shalt have no other gods before me.`"
Here is the sum and substance of all true religion that ever was upon earth to this day.
All the commandments, all the precepts, prophecies,
and all the dealings of God with his people, from that day to this,
have all been contained in this short precept, "`thou shalt have no other gods but me.`"
And as long as Israel stood in obedience to this command,
their blessings were multiplied upon them,
their good things were increased from day to day; the Lord was with them,
as long as they were willing to be his people; he appeared as their God,
and as their defender wrought their deliverances, fought all their battles for them,
gave them dominion and strength, courage and wisdom;
ministered out of his treasury all good things unto them;
for the great care of God Almighty was with all his people, he had regard to them,
and visited them at all times, to keep them from idolatry; I am, saith he, a jealous God,
take notice of me to be so; I am jealous of my name; if thou wilt be mine,
thou shalt have no other gods but me.

And all the precepts about offerings and sacrifices, and making atonement for sinners,
and the divers services and worship, the various offices in the temple and sanctuary,
they were all outward means appointed of God,
to keep this outward church in an inward conformity to the command of God.
This command was written in tablets of stone,
and these tablets were laid up in the ark of God,
and all this appertained to the first covenant,
and typed and figured out the dispensation of the new and
everlasting covenant that God would make with his people,
not like unto the old.
How not like it?
Not like it in the outward shadows, the types and shadows of things,
but he would bring forth the substance of all those _shadows_ and _types,_
and would alter the form and outward appearance of things; for as God is unchangeable,
so is his law unchangeable.

Moses saith, the first and great commandment is, "`Thou shalt have no other gods but me.`"
This was put into the stone tablets.
Christ Jesus saith, the first and great commandment is,
"`Thou shalt love the Lord thy God with all thy soul,
and with all thy mind,`" Matt. 22:27. This is put into the tablets of the heart.
So here is a difference between the first commandment by Moses,
and the first commandment by Christ;
they both acknowledge the first and great command to be
the subjecting of the creature to him that made him,
as his God, that he may only serve him, and that he may love him with his whole heart.
The Jew could prove this by his stone tablets,
and Christ proves this by the fleshly tablets of the heart,
for there he is bound to love the Lord with his whole heart, and to serve him only;
"`him only shalt thou serve.`"

Now, here the Jews`' law is brought over to the Christians,
in the greatest point of religion that ever was preached; shuts out all idolatry,
all superstition, all variety of religions; all is shut out by this commandment,
and the Christian that hath the law written in his heart, according to the new covenant,
he can go as readily to it and read it, as ever the Jew could go to his stone tablet,
and read the law there; you cannot deny,
that if there be a thing written and engraved in my heart,
I can go at readily to it as I can go to any book or tablet,
though I have the keeping of it: But the Jews had not the keeping of it,
for generally it was laid up in the ark of God.

Now, friends, that which lies upon my mind to speak to you at this time,
and that out of the great love that I have to all your precious and immortal souls,
as God hath had _love to mine,_ is,
that you would all consider and weigh in the fear of the Lord,
whose presence is among us, which of you,
and how many of you are come to the obedience of this commandment:
I do not doubt but the most of you can say them _all,_
but a happy people are you if you can do _one:_ I dare pronounce that soul a blessed soul,
that can perform this one commandment, that can or dare stand before his Maker, and say,
"`O Lord!
I love thee with all my heart, with all my soul, and with all my might;
my love is withdrawn from all other things in comparison of thee;
there is nothing in this whole world hath a place in my mind,
but as it is in subjection to the love of thee.`"

Here is the first and great commandment, the unchangeable law,
the law that was good in Moses`' days, and good in Christ`'s days,
and it holds good in our days; and indeed it is such a definitive law,
that the breakers of it can neither be good Jews, nor good Christians.
There is an absolute necessity lies upon us,
of abstracting and drawing away our minds and souls from all other gods,
from all images and other dependencies and trusts
that people are naturally liable to trust to,
and to have their whole confidence set upon the Lord;
but alas! with grief of heart I speak it,
there are but very few that as yet have known the right giving forth of the law,
and there are fewer that are subject to it.
This law was not given forth at first without thunder and lightening,
and a terrible noise, and the mountain smoking (he that hath an ear to hear,
let him hear) insomuch as Moses himself said, he feared greatly,
and he quaked exceedingly, because of the thunder of the Almighty,
and the mountain that smoked and burnt with fire, so that Israel could not draw nigh.

Now I say,
there are but a few that have come to the knowledge of the giving forth of this law,
that have certainly known those thunders,
and that terrible work that the Lord of the whole earth makes,
when he comes to set up his law; for a great many that have come nigh to it,
and might have heard and received the words of the law of God, they have gone backward,
they have done like unto the Jews of old, though they had suffered much,
and gone through much, and had seen the wonders of the Lord;
how he had led them and delivered them; yet when it came to this,
that they must hear the voice of God, they said we cannot bear it; we cannot endure it:
We have devised for ourselves an easier way;
for the voice of thunder and dreadful noises, put them into terror and quaking,
and trembling, and great dread came upon them; but we have found an easier way, say they;
what is that?
Go thou, said they to Moses, and hear thou what the Lord saith,
and come thou and tell us, thou shalt be a Mediator between us; let God speak unto thee,
and do thou speak the same to us, and we will hear thee.

Thus the Jews that were not come beyond the law of God written in tablets of stone,
they would not come to receive it in their hearts, as the Christian must;
so Moses received the law from the mouth of God,
and he was faithful as a servant in the house of God,
and he ministered forth the law of God, his precepts, statutes and judgments,
and testimonies; and he made them a book of laws for all of them to walk by,
from the highest to the lowest; how they should act in criminal matters,
and to do justice between man and man, and what they should do in the worship of God,
and what they should do towards the priest,
whose lips should preserve knowledge for them; and so he brought up a form of religion;
but his work was according to the precepts of God;
and he brought them into the form of national religion, and government,
and national laws.
And so Moses and the priest ruled over them; and the priest offered sacrifice for them,
and made atonement for them, and Moses inquired of the Lord, and asked council for them,
and taught and instructed them; and what became of all this at last?
When this was done, the priest made atonement for sin,
but he could not pluck away the guilt of one sin;
there remained the conscience of sin after he had made his offering;
and Moses taught them the counsels of God, and the commands of God,
but he could not bind their hearts to the obedience of them;
for he declared openly against them,
that they were "`a rebellious and stiff-necked people,`"
notwithstanding they had a law without them.
Indeed,
time would fail me to run through the manifold miscarriages of the church of the Jews,
in respect of their idolatry, in respect of their contempt and rebellion,
both to God and his servant Moses, who was to teach and to guide them: I say,
the time would fail me to mention the manifold miscarriages
that happened among this people,
that had a law and religion without them, and a teacher without them.

Now in the fulness of time it pleased God in sending his Son, Christ Jesus,
to raise up a prophet like unto Moses, in respect of faithfulness,
though higher in respect of dignity;
for Moses was faithful in all his house as a servant,
but this man was faithful as a son in his own house, in the house that he was heir of,
that house wherein he was as King, even a priest, a prophet, and a ruler in.
When the Lord signified by the spirit of prophecy, the coming of the Just One,
he signified to the people that his ministry should not be as that of Aaron;
the people should not have their religion without them,
and their laws and precepts without them, and their priests without them,
and their worship and church without them; but that they should have it all within them.
"`I will write my law in their hearts, I will put it into their inward parts,
then they shall be my people, and I will be their God, and they shall not forsake me.`"
Your fathers brake my old covenant, but I will make a new covenant in the latter days,
a new covenant, not like that your fathers broke; they brake the law without them,
but I will write my law in their hearts; this prophet that is like to Moses,
he shall teach my people, he shall be a leader to them,
and guide them in the way they are to go, and shall be a captain for them,
to lead them to salvation; and it shall come to pass, in the day that I do this,
if there be any that will not hear him, he shall be cut off from among the people.
That is, the judgment that comes upon the contemners of the gospel,
upon them that will not hear Christ Jesus, they shall be cut off from the people;
from what people?
From the people of God;
they shall have no part of the privileges that are enjoyed through Christ;
they shall be cut off from the benefits that others reap by their faith in Christ.

So that now we are to expect the operation and working of a ministry,
that leads a people to an inward religion, a heart religion,
where the heart is fixed entirely upon the true and living God,
as the object of their dependence and trust; and they have no other.
This is a strange word to flesh and blood; what,
no other dependence than on the invisible God?
Flesh and blood, and sensuality, can never come to this;
this is a religion that hath been hid from ages and generations,
and will be hid to all ages that ever shall be in the world, where sensuality prevails.
What, will you have me to have my whole dependence for the comfort of my life here,
and of the life that is to come, the other life,
to have my dependence upon an invisible God, that invisible power that made me,
and created the world?
How is it possible for me to sequester myself,
and draw myself off from all visible objects?
I must trust to this, and trust to that: Flesh and blood can never attain to this,
with all the wit and reason it hath; it can never separate itself from idols;
they are little children; they are children of another birth, born of another seed,
that keep themselves from idols.

Friends, idolatry is a great deal more common, I find, than most are aware of.
Am I commanded to love the Lord with all my heart, and soul, and mind, and might?
What is left when the whole is taken away?
If God hath my whole heart, what have I to bestow upon the world?
What love, what affection, what eagerness, what fervency can I bestow upon the world,
or any object in the world, when my whole heart, and soul, and mind, is gone before,
is gone toward the Lord?

This is the first and great commandment; and the second is like unto it, that is,
"`thou shalt love thy neighbour as thyself.`"
Here it is that the law and the prophets, saith, creeds, prayer, religion and worship,
all that ever was in the world, all are comprehended in this,
"`thou shalt love the Lord thy God with all thy heart, soul and strength,
and thy neighbour as thyself.`"
So what need is there for us to be disputing about religion; about this tenet,
and the other tenet; this text, and the other text?
For my part, I should only desire you to understand this text,
and I should not doubt your going to Heaven.
Here is the sum; here is all at once; here is the quintessence of all religion,
of all types, shadows, figures, ceremonies and priest-hood,
and all that ever was or could be named and practised in the world; all brought to this,
_the heart given up to God;_ our love set upon him.

What, is this sufficient, will some say?
This will make you a good moral man; but what is this to the Christian religion?
You may be led into error, and become a heretic for all this.

How can this be, that I should not be of a sound faith,
but led into error and heresy for all this?
When people let in error, and heresy, and unsoundness of faith, where do they let it in?
Do they not let in the principles of error and heresy into their hearts?
I believe this, and that, and the other error, that it comes into the heart,
and hath a seat in the heart; but how can we let it into the heart,
when the heart is given up to God?
Cannot I keep out error and heresy, if I give up my heart and soul to him?
Cannot I trust him with all?

This kind of talk of error and heresy hath come among
men that have had the keeping of their own souls:
They have taken their own souls into their own hands,
and have ordered their religion themselves, or have had somebody to order it for them;
and a great many of them have met together to make creeds, and catechisms,
and confessions, and orthodox doctrines,
that might certainly be professed and subscribed.
So afterwards some have come and found fault with them;
then they must have a council to try them; then these go off and are laid aside,
and others are given in the room of them; so that these men have set up for themselves.
These would not be under the government and prescription of God,
as children under the government of a father; but they will set up religions themselves,
and say to the rest of the world, if you own anything contrary to our principles,
you are a heretic; and being a heretic, you are to be rooted out and cut off.
Do not you read in the scripture,
that whoever hears not the Prophet that was to come into the world, should be cut off?
What, will not you hear Christ speak in the church?
Will not you hear Christ speak?
The church cannot speak without a head; if you will not hear the church,
you must be cut off.
Then they have fallen to hanging, and burning, and killing, and destroying people,
and nations not a few: And this comes from their making faiths, and creeds,
and ordering religion themselves: All their barbarous and inhuman cruelties,
martyring and dungeoning people, comes from their making faiths themselves;
and of all things nothing is more desperately wicked, and they did not know it.
"`The heart is deceitful above all things, and desperately wicked, who can know it?`"
Men know not how proud and arrogant they themselves are,
and yet they would be ordering the hearts, and minds, and consciences of others;
and out of this hath sprung all superstition and idolatry,
because men would not give up their hearts to God;
"`thou shalt have no other gods but me.`"
This commandment is great in itself; strict in the terms;
"`thou shalt love the Lord thy God with all thy heart, and thy neighbour as thyself.`"
Their neighbours could not see with their eyes; therefore they would be hanging,
and burning, and destroying one another.

But, blessed be God,
who is now bringing forth true Christianity upon its old basis and foundation,
whereon it was placed at first,
for Christianity hath been jostled off from its first foundation;
for instead of loving God with all their hearts,
and loving their neighbours as themselves, they hated them: Now this is the day,
O friends! the weight of it is great;
this I say is the day wherein God is bringing Christianity upon its old foundation.

I would not have you think that I am here judging our fore-fathers,
that are fallen asleep, that, therefore, they are gone to Hell,
because they saw not this day, and lived not to see that benefit of it that we enjoy;
I am far from it: This was the thing that they believed and prayed to God for;
they did not see this day outwardly, but they saw it by faith.
When I was a child, I remember the people of God, when they met three or four together,
they would rejoice in the hopes of what they foresaw;
they gave thanks to God for the blessed days that he would bring forth,
though they could not tell when; they did say, and believe,
that God would scatter the fogs, and mists, and bring forth a happy day,
wherein his people should have the gift of his Spirit:
When they saw the impositions and persecutions of those times,
when they that did not conform, and comply, were cast into prisons, dungeons and jails;
well, it will not always be thus, say they, there is a day coming,
wherein the Lord will set his people free from all the yokes of oppression,
and from the oppressor.

Indeed, my soul did rejoice in hearing the prophetical sayings of those good men,
and I thought I might live to see that day.
Blessed be God that hath preserved my life to this day, and to this hour,
to enjoy what they prayed for: They prayed to God to scatter the mists and fogs,
that they might no longer cloud and darken men`'s minds,
and hinder them from enjoying God`'s teaching.
Blessed be God, that we are now in the enjoyment of the prayers of the faithful,
that left the world before we were in it.
Now the day is come that they prayed for, and inquired after.

How strangely doth the man talk, will some say, concerning the Christian religion;
the Christian religion is all England over; go to any meeting in London, except one,
and they will tell you they are Christians; I would to God they were;
that is the worst I wish them all.
But what should we talk of the Christian religion without the Christian life?
except we find that amongst them, what signifies the name and profession of it?
And the Christian doctrine is wanting in many places too.
There is many in this city, urging this very command,
of loving God with all their hearts, and their neighbours as themselves,
as fervently as I can do, or anybody else; and yet they will tell you in the next breath,
that no man in London, nor in the world, can do this;
no man can possibly love God with all his heart;
never a man can be found that can perform such an act,
as to love his neighbour as himself: Not every neighbour, it may be,
but some one choice associate he may pick out, that he can love,
and bear with his infirmities and affronts, and _love_ him as himself; _love_ thy neighbour,
that is everybody,
that there may be a good-will for all people throughout the whole race of mankind,
"`peace on earth, good-will towards men:`" This is the fruit of the gospel.
Christian words will not make the Christian religion, there must be a Christian life;
but where shall we find that, or seek it?

I know not, I have nothing to do to judge anybody,
but there is one that judgeth who it is that liveth the Christian life, and who doth not?
Who is this?
what one is this?
The Head of the Christian church: Why, is he here?
Yes, the head of the Christian church is here, and he speaks and gives sentence;
if you have an ear you may hear him, and if you will turn your mind inward,
for he is an _inward minister,_ everyone of you, if you will turn your minds inward,
he will tell you whether you live a Christian life, and what _life_ it is you _live:_
If there be a drunkard here, let him ask whether his life be a Christian life;
will a man go away ignorant from this place, and have no answer?
If there be a drunkard here, let him ask inwardly in his own bosom,
Lord is my life a Christian _life?_
I dare affirm, on God`'s behalf, he will have an answer, no,
thy life is not a Christian _life,_ but a shameful, beastly life, a brutish one.

Who told you that the Head of Christians, Christ Jesus, is present?
Christ Jesus, is he present?
How came he here?
He is ascended up into Heaven such a day, say they, how came he here?
Let him be ascended up into Heaven,
yet he is not so ascended into Heaven as not to be here also;
how should he fulfill his promise, if he be circumscribed in Heaven or earth?
How should he make good his promise, if when two or three are met together in his name,
he is not in the midst of them?
Here now are many more than two or three met together in the name of Christ,
and that hope for acceptance with God, through the Mediator, Christ Jesus;
if you think that here are two or three met together in the name of Christ,
it follows that Christ is in the midst of them.

I know not what you may enjoy, some may possibly say,
I do not find any such presence of Christ;
I hear of the presence of Christ in the sacrament,
and I have heard talk of the presence of Christ at a meeting,
but I have been at many a meeting, and I never found such a presence of Christ.

Can you read the scriptures?
Yes, I can read the scriptures as well at you but that cannot give me a sense of it;
I do read the scriptures and believe them;
but what signifies my reading the scriptures concerning the presence of Christ,
if I have not a sense of it?
I have been at many a meeting,
but never had the sense of such a Divine Presence as you talk of,
nor it may be at the sacrament neither: What is the reason thou hast no sense of it?
If thou wilt take my counsel, and turn thy mind inward,
and inquire whether the thing I speak of be true,
whether there be such a voice as I speak of, that will tell thee what thy state is:
If thou wilt be true to thyself, thou mayest know the Divine Presence,
and thou mayest hear Christ speak.

The soul hath eyes, and ears, as well as the body.
What eyes doth the apostle mean when he saith,
"`the God of this world hath blinded the eyes of them that believe not,
lest the light of the glorious gospel of Christ, who is the image of God,
should shine unto them?`"
If the soul hath eyes, and ears, as well as the body, it can hear, and see as the body;
as the bodily eye can see visible things,
so the eye of the soul can see things that are invisible, and heavenly;
you can hear my voice outwardly, and you may hear the voice of Christ inwardly.
I have known some that have been so afraid to hear ill of themselves,
that they would not inquire; some have been so guilty in their own consciences,
that they have been afraid of hearing ill, and would not inquire about themselves:
So it is inwardly;
some have been so conscious that their life and conversation is naught,
that their life is a sinful life, that they dare not put it to the question:
It would certainly have been told them, thy life is not a Christian life;
thou must mend thy life, before ever thou comest to have peace with God:
If this should be thy portion and mine,
that upon search we should find our condition bad, what harm is it?

I would put one question to thee, be serious in considering of it:
We are all children of wrath by nature, none of us differ about that,
and that "`unless we be born again, we cannot enter into the kingdom of God.`"
The question is, whether I am one of those or not?
Suppose upon inquiry it be discovered to me that I am not, that is bad enough;
this is hard, but not so hard as it is true;
this is the thing which I would have you consider:
Am not I in a better case to know that I am in a natural state,
than to go on and perish to eternity?
As long as there is life, there is hope; as long as a man is upon the earth,
and taking care for his soul, and inquiring about the state of his immortal soul,
if his soul is not in a good condition, is it not better for him to know it,
and to seek for a cure?
For there is no greater infirmity and infelicity can be upon man,
than to have some occult and hidden disease, that he cannot be made sensible of;
for this wastes and spoils him, and he cannot be persuaded to look out for a remedy:
So it is inwardly; if a man be ignorant of his condition, and go on to his dying day,
and hour, and does not seek after a remedy, this man perisheth without all peradventure.
When you are in this inquiry, be content to be controlled,
be willing to have the truth spoken, though it be against yourselves.
I might instance in divers things that I have spoken of:
If a man be satisfied that his life is not a Christian life; I say,
if the swearer or liar, if the proud person, or the effeminate,
as soon as they come to be satisfied that their life
is not a Christian life that they now live,
what can this man expect?
What counsel should we give him, and what counsel should he take?
I will go on in the way that I am in: What,
after thou knowest thy life is not a Christian life?
God forbid: Wilt thou go on and perpetrate sin upon sin,
and heap up wrath against the day of wrath; I am a sinner, my life is unchristian,
I make account to live in sin, and die in sin; is this good policy?
Consider another text which our Lord spake, "`if ye die in your sins, whither I go,
ye cannot come.`"

O friends, lay these things to your hearts;
what have I to do but to tell you that the love I have in my soul for you all,
makes me desire in my heart that you might be saved?
This is the will of God, that you might all be saved,
and come to the knowledge of the truth: Blessed are they that know the truth;
the truth as it is in Jesus.
Truth in the inward parts, hath a speaking voice; and if thou hearken to it,
it will tell thee that thy state is naught.
Canst thou believe the truth when he tells thee so, that thy state is naught,
and that thou art like to go to eternal destruction,
unless there be repentance and regeneration to prevent it?
Canst thou believe this doctrine, when it sounds in thy own heart?
If thou canst not believe it, unbelief will be thy ruin.
The spirit of truth is come to convince the world of sin,
because they believe not in Christ: He tells them their condition,
and they will not believe him.
The Spirit of Christ convinceth men of sin, and they believe him not.
The spirit of truth convinceth thee of thy sin, but thou believest him not.
If thou lovest thy pleasure, and thy profit, and thine honour,
then thou lovest not God with all thine heart; and then thou art not a Christian,
but out of covenant with God.
Art thou sensible that thy condition is bad, were it not best to get it mended?
After we are convinced of our own sinful state,
is it not our best course to seek to have it mended?
Who shall mend it?
saith one; I have done all I can to mend my life, and I cannot mend it.

I have concluded so in my younger years; I have fasted, and prayed,
and spent time in hearing, reading, and meditation, and did all in my own power,
and all to mend my state, but I could not mend it; and as I grew up in years,
sin and corruption more prevailed, and there was no help;
and I came so far as to believe there was no help, and that if God did not help me,
I was undone to all eternity.
I many times wished that I had never been born: I went to ministers and meetings,
and to all sorts of separate people, and to all manner of ordinances,
and to all manner of means, to mend this bad heart of mine,
to see if I could get a power that would give me victory over my corruptions;
but my arm was never so long as to reach thereunto; it was far out of my power and reach.

Many have sought to get this power of reforming their hearts and lives;
to attain it by their own hands, by their own endeavours, but they could never do it;
they could never better their condition,
nor bring forth fruit worthy of amendment of life.
I wish that everyone was come to that pass, that they knew not which way to turn them;
that they were come at last to their wits end: They will come to it sooner or later;
the sooner the better.
I have done all I can; I can do no more; I am at my wits end,
and I know not what to think, concerning my eternal state;
I know not what to judge of it; I strive against my lusts and corruptions,
but for all that they prevail against me: Temptations come before me,
but I cannot conquer them.
O I am glad when people come to that pass, that they know not what to do,
but despair of their own arms, of their own strength, and their own wit,
and despair of all other help in the world; I am glad of that.

I am not preaching up despair of God`'s grace and mercy; but let me tell you,
when men despair of their own doings, and of all outward means, and helps,
then they are fit objects for the mercy of God; and not till then: When the Lord looked,
and saw that there was none to save and deliver, then his own arm brought salvation.
God will not save till then; God will not reveal his power,
till men have done with their own power; they will never trust God,
while they think they can do something for themselves.
All the forms of religion of the several people of this nation,
will do them little good without the power.
What is the meaning of that principle, to have such masses, and prayers, and performances?
What is the meaning of it?
Let us search to the bottom.
They say we are sinners; when we pray to God for his blessing,
and for salvation by Christ, there is this at the bottom,
they think these duties and performances will be very helpful to their state;
helpful towards the knowledge of it: To speak plain English, these are their gods.
If I speak of profane and wicked people, I would say their lusts are their gods:
But when I speak of righteous people, that are mere formalists, then I say their duties,
as they call them, are their gods.
When they have done all, they can do nothing for them, and then they have no gods at all;
then they are _godless:_ And if God doth not help them,
then they are undone to all eternity.

When poor creatures are cast out, as it were, into the open field,
to the loathing of their persons, not salted at all, nor swaddled at all,
but lying in the guilt of their blood: "`When I passed by thee, saith the Lord,
and saw thee polluted in thy own blood, I said unto thee, when thou wast in thy blood,
yea, when thou wast in thy blood, I said unto thee, live.
When I passed by thee, and looked upon thee, behold, thy time was a time of love,
and I spread my skirt over thee, and covered thy nakedness; yea, I swore unto thee,
and entered into covenant with thee, saith the Lord God, and thou becamest mine.`"
What, was it a time of love, when I was such an object in mine own eyes,
that I thought I was the most miserable creature in the world;
one that could not make a good prayer, nor dispute for religion, nor perform any duty;
a poor creature cast out into the open field, to the loathing of my person;
lost all that I gained; my name was from among the living;
my days were passed over in sorrow, and I said there is nothing but darkness, and death,
and misery for me: I used all means, and tried all things,
saving only a living trust in God alone, and that flesh and blood cannot do.
Flesh and blood cannot know him, therefore flesh and blood cannot trust in him.
Alas! said I, I cannot trust in the Lord, I cannot cast my soul and all my concerns,
my fame and reputation in the world, I cannot cast all upon the care of the Almighty;
I cannot know him, nor trust in him; how can I do it?
nobody can do it.
They that know my name, saith the Lord, they will put their trust in me:
Never a truer word was spoken; but how they should know God, and trust in him,
I know not.

When thou comest once to this pass, to be at thy wits end,
and not know which way to turn thee, nor to whom to run for help,
or to ask counsel for thy soul`'s welfare, when thou art come to the end of all,
and without hope, then God reveals himself by his Son Jesus Christ;
Christ the Son of God, is known by our coming to him; but none can come unto Christ,
except the Father which hath sent him, draw him: When thou hast done with thy gods,
and thrown away thy idols to the bats and moles, then thou wilt find the Lord;
and thou wilt cry out, O! that God would have mercy upon me,
and lift up the light of his countenance upon me; I am a poor, miserable creature.
There are many that make such a whining and complaining,
that they take a pride in their very complaints, their hypocrisy is so great.
I have known some that have prided themselves in wording their condition,
and expressing their miserable case before the Lord;
but suppose thou canst not speak at all, but feelest thyself miserable,
thou canst not express thy condition; at such a time as this,
God was drawing thy soul to Christ Jesus, the Mediator of it: I have heard of a Mediator,
and that there is balm in Gilead for me; that there is a physician there;
that there is one physician, even Jesus Christ, the Mediator of the new covenant;
thou hast sinned against him, and grieved him, yet he stands with open arms for thee,
ready to receive thee and embrace thee; where stands he?
He stands as the door and knocks; it is a small matter, one would think, to let him in: Rev. 3:20.
"`Behold, I stand at the door and knock; and if any man hear my voice,
and open the door, I will come in to him, and sup with him, and he with me.`"
Here is good news for an hungry soul, if any such be here; Christ the Mediator,
stands at the door and knocks, he will come in and sup with thee, if thou open to him;
then we shall meet with the Lord`'s supper: This is the Lord, I will wait for him;
he will bring his bread with him, the bread of life, and the wine of his kingdom,
and the Lord`'s supper will be celebrated without cavilling and jangling.

Now, because we will not pervert the scripture, I would have you that understand books,
read what commentators of this and former ages say upon this text;
whether they do not deliver in their opinions, that this knocking at the door,
is Christ calling the soul by his grace; and this door is the door of the heart,
and Christ`'s calling the soul by his grace and Spirit, to let him in by faith:
This is their judgment and sense, and their sense is mine;
and I believe the genuine sense of this text,
that Christ would have people think he is near to them,
and would have them open their hearts, and receive him by faith, to be a Saviour to them.

No; that, saith flesh and blood, I cannot bear,
I cannot consent to have him for my Saviour, I will not let him in,
for he is like Micaiah to Ahab,
"`he never spake good concerning me:`" For if I have him for my Saviour,
I must part with my lusts and pleasures; if there be any other Saviour, I will try,
and not meddle with him; he will spoil all our mirth and good society;
he will tell me that every idle word that I shall speak,
I must give an account thereof in the day of judgment: What,
do you think that I can like such a Saviour?
That I can live with such a one as will call me to an account for every word I speak;
and that if I speak one idle word, judgment will come upon me?
No, I will try one and another, rather than accept of him on such terms;
I am one that am joined to such a church, and enjoy such and such ordinances,
and such helps: I am in covenant with God, and under the seals of that covenant;
I am baptized, and do partake of the Lord`'s supper,
which is another seal of the covenant; I hope it will go well with me.
I will go something farther: Another saith, he must have a Mediator;
I will go to the Virgin Mary, and offer something to her, and pray to her: Saith another,
I will go to Saint James, and Saint John, and other Saints to intercede with God for me.
They must have some Mediator:
This is the twisting and twining of the sons and daughters of men, to keep out Christ,
the great Mediator, who came into the world for this purpose,
to destroy the works of the Devil.
Alas!
I have nothing left but my bare life and living in this world;
I have nothing left me but some _little desire I had to please God,_
and that he will never judge and condemn me for; but my false dealing,
and buying and selling with deceit, he will judge this, and condemn me;
and my discoursing of things without me; all my carnal friendship of the world,
and my vain fashions, all this is corrupt and defiled;
these he came on purpose to destroy; he came to destroy both the Devil and his works.
What, can a man live in the world, and never join with the Devil?
never sin at all?
never do anything that the Devil would have him to do?
There is no perfection in this world; no living without sin here;
then I am sure there is no unity with Christ here; and if there be no unity with Christ,
then there is none with God the Father.
What will become of thee now?
What will all the pleaders for that opinion say now?
There is something stands between God and me, and I shall never have peace;
and what is that?
It is sin; I would have my sin taken away, else I had better never been born.
Canst thou remove sin out of thy heart?
I have tried, but I cannot do it;
I have heard of Christ the Mediator of the new covenant, he saith,
he came into the world, and that for this purpose he was manifested,
that he might destroy the works of the Devil.
Now sin in my heart is the Devil`'s work, I will see if he will destroy that for me;
I will trust and rely upon him, and see if his great power can destroy it in me.

Here people come rightly to believe in him that God hath sent, and trust in him,
and he will take them in; and, like a surgeon, he will rip their hearts,
and let out their corruptions, though there hath been ever so much rottenness;
and he will heal them, and purify them, and pardon them,
though they have been ever so wicked, if they come to him;
when thy sins are set in order before thee, then thou criest out,
"`O wretched man that I am! who shall deliver me from this body of death?`"
Is it God that hath thought on me, and waited to be gracious, hath born my sins long?
how wonderful is his patience towards me!
All these things working in the soul, tends to beget a love of God,
and fervent desires after being cleansed and purified from sin,
and earnest prayer to the Lord, to make the holy fire to kindle that would burn it up:
The more the soul trusteth in Christ, the more doth this heavenly fire burn up our lusts,
and then a man feels a great change in his mind: The things, saith he,
that I delighted in, are now grievous to me;
I hope I shall never be found in those things again; my mind is now taken off them;
who took it off?
Didst thou not strive before to take it off?
I did, but I could not do it.
There are many, I believe, in this assembly, before the Lord,
that are my witnesses in this matter, that when they came to Christ the Mediator,
he changed their minds, and he untied the Devil`'s fetters;
they were tied to their sins and lusts, but he hath unloosed them;
they are ashamed of those things that they formerly took pleasure in.
"`What fruit (saith the apostle) had you in those things, whereof you are now ashamed?`"
So I say, what pleasure have you in sporting, and gaming, and drinking,
and company-keeping?
What pleasure have you to think on your wanton discourses?
What pleasure in pride and vanity?
What pleasure in wrath and bitterness of mind?
And what pleasure in malice and envy?
What pleasure have you in these things whereof you are now ashamed?
So far as you are convinced, you are ashamed to think of them;
I am ashamed to think that the Devil at such a time, by such a temptation,
should prevail over me.

I would to God you were all come to this,
to be ashamed that you might remember your past evil ways and actions,
with sorrow and shame: There is a secret joy in this.
Sure it is better to be ashamed, than to continue in impudence.
God hath wrought this change at last; and who shall have the glory of it?
God shall have the glory of it; for his own works will praise him.
What men do, many times they do for their own praise;
but when they are at their wits end, and know not what to do,
they cast themselves upon their Maker, to see if he will have mercy upon them; if not,
they must perish: Then for what he doth, he gets the glory and the praise of it.

There are some here, that are bound to praise God while they have a day to live,
for what he hath done for them.
They could never have loved God with all their hearts;
but they would have continued strangers to God,
and the Devil would have led them captive at his will.
They would not have loved God with all their hearts,
had not God first shed abroad his love upon their hearts,
and constrained them to love him: It is he that hath first loved them,
and wrought in them, both to will and to do, of his own good pleasure.
Whatsoever we are, we are by the grace of God;
this grace is magnified in them that believe and obey the gospel.

My friends, we know there is so much peace and pleasure in the ways of God;
so much soul-satisfaction in walking with God, and loving of him with all our hearts,
I should be glad if everyone of you were of the same mind, and had experience of it.
We labour diligently for this purpose; and we would set before you these two things:

First, how we may come to know our miserable stand by nature.

And what a blessed and happy state they are in, that have been converted and changed;
that have been translated out of the kingdom of darkness,
into the kingdom of God`'s dear Son.

Consider your state by nature is evil;
we hope that many of you believe the report`'s of the gospel,
concerning the goodness of the Lord, his great love in sending his Son into the world,
to seek and to save you that were lost, and that you believe in him.
And we are persuaded, that by the foolishness of preaching God will save some of you,
that you may be his redeemed ones, and trust to no other Saviour:
"`For there is not any other name under Heaven, but the name of Jesus,
by which we can be saved.`"
He only can take away the sins of the world; his spirit searcheth the heart,
and trieth the reins,
which he promised to send into the world when he was about leaving of it.
Now I dare proclaim that Holy Spirit to be the Spirit of the God of Heaven,
that now sees what resolution thou art of, and what thou art now proposing to do;
whether to go on in sin, or to return to God.
This I can speak without blasphemy, it is God`'s Spirit that searcheth the heart,
and knoweth thy thoughts and purposes, and convinceth thee of thy sin:
God hath sent his Son Christ Jesus into the world to enlighten you,
that by his light you may see him; and that by his grace you might receive him;
and that by his grace you might be saved.

To him I commit you all,
and these words that we have spoken in the evidence and demonstration of the spirit,
according as he hath wrought in us.

I must tell you we were never called of God to study sermons for you,
nor to preach things that are made ready to our hands;
but as the _Lord our God_ hath wrought in us,
and as God hath been pleased to make known his mind to us,
and by his Spirit given us utterance, so we speak, and so we preach.
You that are come to believe and receive the things of the Spirit,
you will judge what I say.
"`I speak unto you that are spiritual; judge ye what I say,`" saith the apostle.
So when I speak of divine and heavenly things, you that are spiritual, judge what I say?
And as you come to judge and determine in yourselves that these things are true,
you will feel the power of them in your own spirits,
and we shall all be of the same mind; and as we have _one God,_
we shall serve him in sincerity, and worship him with reverence.
Then his name shall be exalted in the midst of us,
and we shall edify one another in _love,_ and we shall instruct one another,
and call upon one another; come, let us go to the house of the God of Jacob,
he will teach us, and preserve us in his way, and do us good, and keep us from all evil.

Turn your minds inward, and consider that God is a God at hand, ready to help you;
and he requires no more of you than of other people in former times,
to love the Lord with all your hearts,
and to abstract and withdraw your mind from all other
things that do come in competition with him;
and be sure to have no trust or dependence but upon him;
then see what God will do for you: No tongue can express, nor pen write;
"`neither hath it entered into the heart of man to conceive,
the things that God hath prepared for those that love him.`"
That wisdom and knowledge, that joy and peace, and consolation,
that passeth all understanding,
he will reveal and communicate by his spirit to them that love him, and trust in him,
and rely upon him, and receive teaching from him;
he will feed them with food in due season; he will bring the former and the latter rain,
and they shall be as trees planted by the rivers of water,
and bring forth fruit in due season; and their leaf shall not fade or wither.

This hath been London`'s wonder, and England`'s wonder, how it comes to pass,
that such a people`'s leaf hath not withered, nor faded, as many have done:
Our root was by a river; if we had stood in ourselves;
if our dependence and support had been upon doctrines, tenets, and commandments of men,
then our leaf would have been upon the ground as well as others;
but because we have been upon our root, Christ Jesus, that is always green,
both in summer and winter, therefore our leaf hath not withered; to the praise of God,
and to the honour of his name, be it spoken: He hath preserved us,
for we have no power of ourselves, no more than others; but we trust in God,
and have received power from God, to stand as witnesses for him;
we have trusted in the Lord, and he hath stood by us, and delivered us,
when we were compassed about with dangers and distresses;
if we continue to trust in him still,
he will bring us through all our trials and troubles, and he will be with us,
and never leave us nor forsake us; if we take him for our God,
we shall never need any other.

We read that Senacherib, king of Assyria, sent Rabshekah to Jerusalem to Hezekiah,
with a great army, saying, "`what confidence is this wherein thou trustest?
And he spake also to the people, and cried with a loud voice,
hear you the word of the great king of Assyria; let not Hezekiah deceive you,
for he shall not be able to deliver you; neither let Hezekiah make you trust in the Lord,
saying, the Lord will deliver us.
Hezekiah went and prayed to the Lord, saying, O Lord of hosts, God of Israel,
that dwellest between the Cherubims, thou art the God,
the God alone of all the kingdoms of the earth; thou hast made Heaven and earth;
incline thine ear, O Lord, and hear; open thine eyes, O Lord,
and see and hear all the words of Senacherib,
which he hath sent to reproach the living God, etc.
And we read, that after he had presented his supplication before the Lord,
the angel of the Lord went forth and smote in the camp of the Assyrians,
one hundred four score and five thousand; and when they arose early in the morning,
behold, they were all dead corps.`"

Thus you see what came of it at last; and thus it hath been in our day;
they that trust in the Lord, he will deliver them,
and they shall never be ashamed nor confounded; but as for all other gods,
they that trust in them, shall be confounded and covered with shame,
and they and their gods will perish together.

And now, my friends,
I beseech you all to have respect to this great duty
of putting your whole trust in the Lord,
who is the living God, and he will be always present with you,
and work in you both to will and to do of his good pleasure;
he will support and preserve you in all your trials and sufferings,
that you may be vessels of honor, to bear his name in the earth,
and so sound forth his praise to the following generations.

=== His Prayer After Sermon

Most glorious, infinite, Powerful Father! who hast created us,
and given us life and breath, and lengthened out our time to this day,
and hast long waited to be gracious to us,
and art still waiting upon the sons and daughters of men,
holding forth the hand of thy love,
and offering thy grace and tendering salvation unto them,
and hast brought a day of visitation upon the inhabitants of this city and nation.

Glory, praise and thanksgiving be to thee, O Lord! that by thy power,
thou hast inclined the hearts and consciences of the sons and daughters of men,
to submit to thee,
and bow their necks to the blessed and easy yoke of thy Son Jesus Christ,
that they may do thy will on earth, as it is done in Heaven.
They that are travelling, and distressed,
and afflicted in their souls because of their bondage, do thou arise, living Father,
and reveal, and discover thy power to them;
shew them the exceeding greatness of thy power, that they may trust therein, and be safe;
make bare thine arm for their salvation.
Those that are slumbering in their profession, let them be awakened;
and bring to thine heavenly kingdom, those that have passed through thy refining fire,
and whom thou hast cleansed and sanctified.

Powerful Father of Life! carry on thy work among thy people everywhere:
Gather them that are scattered, and bring back to thyself,
those that are wandering and out of the way, and seeking the living among the dead.
Lord, teach them and let them hear a voice behind them,
and guide them to the holy mountain; that they may be brought to the path of life,
and to the place which thou hast provided for thy little flock to meet and feed together,
offering unanimously the sacrifices of praise and thanksgiving,
which thou hast ordained and appointed in thine house.

Blessed and powerful Father! all thy little ones
be pleased to surround with thine Almighty Power;
and wherever they are, let them feel thy preserving hand,
delivering them from the evil of the world:
We pray not that thou shouldest take them out of the world,
but to preserve them from the defilements and pollutions of it:
That holy people may serve thee the holy God, and bear thy holy name upon their hearts;
that so it may be exalted and magnified above all,
and humble thanksgivings and praises may be given unto thee, through Jesus Christ,
for all thy love thou hast manifested, and for thy abounding mercies,
and renewed favours which we have received at thy hands.

To thee, living Father, through Jesus Christ, thy well-beloved Son,
in whom thou art well pleased, be all honour, praise and dominion rendered by us,
and all the people, from henceforth, and forever.
Amen.
