[short="Sermon V. The Great Duty of Remembering Our Creator."]
== Sermon V. The Great Duty of Remembering Our Creator.

Preached at Devonshire-House, April 6, 1692.

There is only one living and true God, Creator of Heaven and earth,
whom we are obliged to serve and worship: I have so much charity as to believe,
there are none among us, but will own and acknowledge this: And my soul wisheth,
that this obligation did always rest upon everyone`'s mind,
that they might remember their Creator, that hath given us all life and breath,
and continued all our blessings to us;
that so everyone might apply their hearts unto that universal duty,
that we are all convinced of.

And they that are thus employed and exercised, they are considering how,
and after what manner, they may quit and discharge their duty,
and perform the obligation that lies upon them,
so that it may be accepted at the hands of God;
I speak now of those that are considerate, not of those that go on in a form of religion,
and matter not, nor regard whether they are accepted of God or no;
but all that are conscientious towards God, they are desirous to serve God,
and worship him, so as they may be acceptable to him,
so to perform duties that they may receive their reward,
and that encouragement that God in all ages hath discovered,
and made manifest to be in his purpose towards them that truly serve him.

When people come to this consideration, how they may serve God aright,
and worship him acceptably, the Lord is nigh unto them, to instruct them, to teach them,
and guide them in that way that is everlasting: And,
blessed be his holy name! a great many in our days,
have met with this divine teaching and instruction; and are taught in this age,
as in former ages, to understand the worship of God that he requires; that is,
in spirit and truth; and do find, that the Father doth seek such worshippers,
and where he finds them, rewards them, and they have an answer of peace in their bosoms,
and they are encouraged to go on in the worship and service of God,
to the end of their days.

And it is a great mercy and benefit;
a great blessing that God hath bestowed upon a remnant, to open their understandings,
to let them see and know the way of being near to God,
that so they may know whom they worship; for you have read, there have been worshippers,
that do worship they know not what: As our Saviour said to the woman of Samaria,
"`you worship you know not what;
we know what we worship:`" So all that are taught of God,
do know which is the first lesson of Christianity, as the apostle saith;
"`he that cometh to God, must first know and believe, that he is;`" that is,
people must first be sensible, that there is a God,
"`and that he is a rewarder of them that diligently
seek him,`" before they can rightly worship him.

Now, for want of this knowledge, the world is scattered,
and people are divided into a great many sorts of worships, and fashions,
and ways of religions, for want of the knowledge of the true worship,
of the true and living God; so that though men are universally convinced,
that there is a God, and that a worship is due to him from everyone of us;
yet people are confounded, scattered,
and divided about the performance of their great duty;
and in the day that the Lord hath visited his people, he hath come to answer this doubt,
and question for them; it hath been the great question of the world,
and is still of many thousands; I know we should worship God,
but I know not the way and manner wherein to find acceptance:
The Lord hath answered that question in abundance; "`they that have ears to hear,
let them hear what the Spirit saith;`" there is a short answer to it in all.

Let people profess what religion they will, there is no acceptance with God,
but through Christ: So that if people come to be of this, and that,
and the other profession, and change their religion ever so often,
and go from one religion to another, if they come not to Christ,
they come not to him in whom they may find acceptance;
in him God is pleased with everyone; but out of him he is pleased with no one.
The great mystery of religion lies in Christ; people must come to God, by faith in him;
"`for without faith, it is impossible to please God.`"
Let people perform ever so much service and duties,
all must pass through the hand of the Mediator,
before ever their performance will reach unto God,
or before peace and comfort will reach to any man`'s soul.
Therefore, it is the wisest way for everyone, that would have acceptance with God,
to come to him, in the name of the great Mediator.
People would be glad to have acceptance with God,
and not to have their services turned back upon them, as Cain`'s was: Now,
everyone that will have acceptance with God, must come this way; there is but one way,
it is not the way that men have invented; some by their works and merits,
some by their made-faiths, and made-beliefs, and by divers articles and principles,
holding this principle, and the other principle; but our Lord and Creator,
he hath sound out one way, in his infinite wisdom, and unspeakable mercy to mankind,
that was forever lost, and could never return to God, by all his sacrifices,
offerings and performances; he was never able to return into unity with his Maker,
if God had not sound out a way; and the way that God hath found out,
is by his beloved Son Christ Jesus: God spared not: He spared not what?
He spared not his only begotten Son: Why, what did he do with him?
He gave him for the life of the world; in him that God gave, there is life.
It pleased the Lord that his Son should have life in him,
as the Father had life in himself; for Christ was with the Father before the world began;
"`in him was life,
and the life was the light of men;`" John 1:4. It was no created life;
that life that is in his Son, is not a created life, but is an eternal life,
and it was given for the life of the world, and that life is the light of men:
"`This is the true light, which lighteth every man that cometh into the world.`"
So that here is the dignity of that life which God hath bestowed upon us;
we are endued with that life, which was with the Father through Jesus Christ,
before the world was.
Let us consider the dignity of that light, that we are lighted with.

The question is, whether we should obey this light, or no:
It is the question of everyone; I am enlightened, saith a man, shall I obey it, or no?
If I obey, I must take up a cross, and part with my beloved lust and corruption.
No doubt of that; we must persuade people to do that,
before we can bring them to Heaven and happiness, and fellowship with God;
it must not be by that way they lost it, but by the contrary way,
by which God will bring men to happiness again.
They lost it by transgression, and sinning against God;
by this way and means men came out of the presence and favour of God;
but what way shall they obtain it again?
Shall it be by committing iniquity, and breaking God`'s law?
No; here is the way that God hath found out, to bring poor man back again to himself,
by the sufferings and obedience of his Son, Jesus Christ:
He hath given to him all power in Heaven and Earth, that all should be subject to him;
here is a dignity which Christ hath obtained.

It comes to the question with us, whether we are enlightened?
now we know we are enlightened; God hath bestowed something upon us,
that wars and fights against sin and iniquity.
How came we by it?
Is it any faculty in nature?
No; nature is corrupted and defiled, because "`the carnal mind is enmity against God;
for it is not subject to the law of God,
neither indeed can be;`" yet there is something in me that answers the pure law of God,
which makes me to hate things that are reprovable; that is, light: How came I by it?
It is not natural;
for then it would run parallel with the natural inclination that is in my soul,
to lead me further and further from God.
These are set in opposition one against another, the flesh and the spirit;
"`the flesh lusteth against the spirit, and the spirit against the flesh.`"
Here is part of an inward war, that you may all be sensible of.
Now, these two warriors, the flesh and the spirit, make war one against another,
and one of them is overcome.
It is true, there is such a principle in me, that strives against sin and corruption:
How came you by it?
If you believe the scriptures, I say, it is the life of the Son of God,
"`that lighteth every man that cometh into the world.`"
Now, many that have rejected and despised the light, I believe they did not think,
at the same time, to mock and make a scorn of the life of Jesus, though it was really so:
But if people come to a true esteem and value of
that light that God hath planted in the soul,
they will give more reverence and respect to it.
It is this that brings those that preach Christ, to preach him in those terms,
and under those denominations, that he is nigh them.

We do not doubt of Christ`'s being born of a virgin, in the land of Canaan,
and that he wrought miracles, and preached many godly sermons, and that he was crucified,
dead and buried, and rose again from the dead, for these things are certainly true:
But we would have him our Saviour in this age, we would have a nearer knowledge of him,
and a sense and feeling of the virtue of that power,
by which he saved them that lived in former ages:
He is not a Christ and a Saviour of one age only, but of all ages to this day; from Adam,
to the last man that shall live upon the earth.
That age and generation that knoweth not Christ, will not be saved by him,
if there be any age wherein he is not known:
"`There is no other name under Heaven by which you can be saved.`"
If you ask where is this Saviour?
"`Say not in thy heart, who shall ascend into Heaven?
that is, to bring down Christ from above; or, who shall descend into the deep,
that is to bring up Christ again from the dead?
The word is nigh thee, even in thy mouth, and in thy heart; that is the word of faith,
which we preach.`"
He is nigh thy soul, he is the Lord of life, and a quickening Spirit,
if I know that quickening Spirit, after this I know the Lord Christ;
when he comes to work in me by his power, changing my heart,
and translating me from death to life, then I know the true Christ: God hath manifested,
in all ages, that it is the duty of people to come to the knowledge of the Son of God;
for he hath sent forth his Spirit to teach us, and to lead us into all truth.

For when Christ was with his disciples, he told them that he would pray the Father,
and he should send the Spirit, the comforter; and when he came,
he would be known by his divine and inward teachings and operations,
guiding and leading them into all truth; that was his work to them:
But what shall other folks do?
He will be made known to others too: When he comes, he shall convince the world of sin:
So that his work to his disciples was to lead them into all truth;
and his work to the world is, to convince the world of sin: Who will deny,
but that there is a Spirit in our age, as well as in other ages,
that will convince men of sin?
Is this the Spirit of God, that convinceth the world of sin,
or is it the spirit of the Quakers only?
When people come to consider really and truly, how they may serve God aright,
they will find there is no serving God aright, unless they come to Christ the Mediator,
that in and by him they may put up supplications to God; and through him,
they may expect at the hand of God, peace and comfort; and there is no other way,
nor ever will be.

The Jews, they had another way, they had an outward way of serving God;
this stood in divers offerings, sacrifices, washings and observations;
this was a way of worship of God`'s own institution to that people; but what came of it?
When the apostle came to grasp it, he said, the comers thereunto, were not made perfect:
What were the transgressors of it then?
They that would sin on, and continue in sin, and not bring a goat, or a ram,
or other oblation; they that did observe it, and came up to the point of the law,
they did bring their offering when they were convinced of their sin: If a man sinned,
he was to bring an he-goat, and to bring it to the door of the tabernacle;
but when he sinned, the conscience of sin, the guilt of sin remained upon him.
"`For it was impossible,`" saith the apostle,
"`that the blood of bulls and goats should take away the sin:
For if the blood of bulls and goats, and the ashes of a heifer sprinkling the unclean,
sanctifieth, to the purifying of the flesh, how much more shall the blood of Christ (who,
through the eternal Spirit,
offered himself without spot to God) purge your consciences from dead works,
to serve the living God.`"

When there is no hope of atonement and reconciliation with God,
by all those offerings under the law,
he tells you of one offering of the Son of God himself, through the eternal Spirit,
by which he became a propitiation;
for this will do if I believe that Christ offered
an holy offering to the Father for my sins,
I believe he offered his body, and that through the eternal Spirit,
that he might be a propitiation for sin, and take away sin,
and have power over sin and death, and conquer death and darkness:
The apostle drives the matter further;
you must come to the inward work of this outward offering, this eternal offering,
that was in due time offered to God; you must come to know the operations of it,
by the sprinkling of the heart from an evil conscience:
So that there was to be an applicatory faith for the offering of that.
The way to a Saviour was not made by man,
no more than the way of salvation by Christ was found out by man;
no more than the application of the benefit is effected by man.

When it pleaseth God to call a people by his grace, he calleth them by his Son;
not by this and the other form: "`No man cometh to me,`" saith Christ,
"`except the Father, which hath sent me, draw him.`"
The first thing that a man or woman comes to be aware of,
is the secret sense and feeling of the Lord`'s Divine Power upon the heart,
to feel Christ Jesus; as soon as they feel this, and embrace it,
this is a token of the love of God.
I hope all this congregation will acknowledge,
that they have sometimes felt his drawings,
and that they have not embraced and closed with them so well as they ought.

When people are aware of these drawings inwardly to holiness and righteousness,
and are sensible that they should, with care and attention, close with them,
for the good of their poor souls;
and that it concerns them to be happy in the other world that is to come,
and therefore resolve to be led by these drawings of the Spirit of God,
these are not weeds that grow in the fields naturally; these are Sparks of Divine Fire,
kindled in the hearts of men by God himself: No man comes unto God,
till God comes to him, and touches him, and gives him sense and motion:
These are the motions and stirrings of God`'s Holy Power,
in the hearts of many that are wicked and abominable;
yet the Lord doth not despise the work of his own hand, but reacheth to such.

When the Lord meets with those that despise not, but highly prize this wonderful grace,
and close with it, and are glad of it, such a one faith,
I feared that the Lord had forgotten me, and had passed by me, and had done with me;
but I see he visits me again, and he hath visited my soul this day,
inclining me to walk more answerably to his love; he hath doubled his power upon me,
and hath kindled a holy fire in my heart, and caused me to seek after him;
he hath touched my heart, and I will pour out my soul in supplication;
seeing he hath touched me, he will take hold of me by his power,
and he will keep me from being any more drawn away:
I will live in the sense of his power and mercy, that keeps me night and day,
that I may increase in it, and grow in grace.
When the Lord meets with such a one,
he will draw him into the way that he hath appointed:
"`None can come unto me,`" saith Christ, "`except the Father, which hath sent me,
draw him.`"
If I am drawn, into what form shall I go now?
and what ordinance shall I take up now?
This is all under feet; this is none of my work; I will come to Christ the Mediator,
and he will take the government and rule of me: It is not my best way to study a form,
and an outside religion; I will wait upon that power that hath thus touched my heart,
that he may by degrees bring me to the obedience of Christ.

But some are ready to say, who, and what is this Christ Jesus that you are speaking of;
that immediate Christ Jesus that is extant and present,
that I am to have to be the object of my faith; that I may believe in him,
and come to an acquaintance with him, that I may partake of the life of Jesus Christ,
and have it communicated to my soul?

We have not a thought, or a word to speak,
that may derogate from the wonderful grace of Christ,
who died in his person on earth for the salvation of our souls: Yet we must know,
that the Lord Jesus Christ may be spiritually present with us,
and take the government of us, and we are to be subject to him: How shall this be?
I am speaking of one that hath felt the Father`'s drawings,
when he draws them to his Son, and draws them to something that is holy and pure:
This God the Father hath begotten: We read in scripture, that God hath begotten Christ,
who is the only begotten of the Father.
It is strange, you will say, to speak of begetting Christ again, God begets Christ again,
that is, spiritually; he being the first born in many brethren, in every true believer,
and there is a travel of soul that Christ may be formed in him.
See what travel of soul the apostle Paul falls into the second time, for the Galatians.
They were a brave people, they worshiped God in Spirit, and believed in Christ Jesus,
and afterwards they came to be seduced by false prophets, and false teachers,
that set them about their works,
and told them they could not be justified and saved without their own works:
These false teachers that came among them, were as bad as Popish priests and friars.
It is not your obedience to Christ, and the Spirit, that will save you,
you must be doing: So these poor people were deluded and bewitched;
and to give you the apostle`'s own words, they were infatuated,
and drawn away from the simplicity of the gospel,
and they thought by the works of the law to obtain salvation:
The apostle writes a letter to them, and tells them that he travailed in birth again,
till Christ was formed in them.
If this was not scripture, it would look like a strange work;
there must be a forming of Christ, a birth there must be, and a begetting:
Who must beget in this and that moment, but the same that begat from the beginning?
the same is the Father, he begets Christ in all that believe and obey the gospel.
He is begetting something in me that is holy, though I be unholy; the Father,
by the operation of his divine hand, begets something in me that is holy.
This I find, though I am not so good as I should be; I have that given me,
that will tell me,
that the more I adhere and join myself in my desires and affections to this good principle,
the more I shall partake of the quality of it; this good principle,
though it be like a "`little grain of mustard-seed,`"
I cannot tell what to compare it to for littleness,
in comparison of the great lump and mass of sin, corruption and filthiness,
that wars against it; yet this will overspread all that is bad, and make me holy,
as that is holy; pure as that is pure, and to have a love for him, from whom it came,
even to Christ and God; it will gather the affections from corruptible things,
and place them upon things above.

This faith tells people that it is "`the substance of things hope for,
and the evidence of things not seen;`" such a one live by faith,
such a one that comes to be joined to that, that is begotten of the father,
he lives "`by the faith of the Son of God,`" and can do nothing of himself,
but through Christ that strengthens him; he says unto God,
I perceive I can do nothing without thee; I cannot pray unto thee, nor serve thee;
of myself I can do nothing acceptably, but through Christ the Mediator;
such a one becomes like a little child, and he must be led; and who must lead him,
but the Spirit of Christ?

You cannot preach, says one to him, unless you be moved by the Spirit:
You cannot pray until you be moved by the Spirit: How should I? No,
without him I can do nothing, I cannot preach, nor pray,
nor do anything acceptable to God the Father, but by Christ;
and he hath revealed him in me.

This is no new doctrine, we see the new and living way;
it was an old way to old Christians, and a new way to the new;
and so a thousand years hence, if the world lasts so long,
men will see that they cannot do anything pleasing to God,
but as they are gathered into Christ; they will see their own righteousness,
works and doings, will avail them nothing at all.
This is all laid at the feet of Jesus,
whom God hath exalted to be a Prince and a Saviour, to be Lord and King.

Now, my friends, we are engaged in this age, abundantly engaged, to offer thanks to God,
through Jesus Christ,
that he hath provided and opened a way for the sending forth the Spirit of his Son:
And that God hath gathered a people, and hath made known to them the way of life,
that they might walk in it; but there is no walking in it, but through a daily cross,
and self-denial.
It is not likely that a man should be brought back
to God the same way that he went out from God;
and the prophets and apostles do allude to this turning to God;
"`when thou turnest aside to the right hand or to the left,
thou shalt hear a voice behind thee, saying, this is the way, walk in it.`"
There is a voice, that calls to people in our days, to look behind them,
for they are out of the way.
This prophecy is fulfilled in our day; we cannot turn away from the good ways of God,
but we may hear a voice behind us, saying, thou art sinning against God,
and breaking the holy law of God, Now, if people return, it must be by the cross:
I will not return to God, saith one; I have pleasure, profit, and honour,
and whatsoever my heart can desire, in this evil way that I am walking in; if I return,
I shall have nothing but shame and reproach; I shall be undone and ruined,
and I shall lose the favour and friendship of my friends and relations;
I cannot return to God, but through a daily cross, and self-denial: What then?
It is likelier to be the right way, by this bearing the cross.
Christ tells us, "`if any will come after me, let him deny himself,
and take up his cross and follow me.`"
This voice of Christ calls me to repent and turn from sin,
and giveth me a strong argument, that it is true;
that it is the same way that will bring me back to God, by the Mediator.
It brings its own evidence with it; we need no argument to prove that it is a right way;
it is a right way, because it is the "`narrow way;`" it is the right gate,
because it is the strait gate.
Everybody can walk in the broad way with ease, without any cross.

When people are come thus far, that they are convinced of their duty,
when they are called to amend their lives and conversations,
to forsake their lives and turn to the Lord, this is the great question,
have I power to do this?
This question hath stumbled a great many,
when they have some beginning thoughts of turning to the Lord;
and at last they have settled themselves in a belief that they cannot do it; it is true,
and nothing truer, that men, convinced of their sins,
have not power to leave their sins of themselves; this is true, but not all the truth;
to men that God convinceth of sin,
he gives them power to be made willing to forsake their sins.
He hath given power to all that are in Christ Jesus,
to believe and become the sons of God;
then they have denied ungodliness and worldly lusts, if they be the sons of God,
and live righteously, soberly and godly, in the world.

But what shall they do that are sensible they have not power to forsake their sin,
till God is pleased to give them power?
Such have nothing to do but to wait upon the Lord, for the giving of this power;
and there is a duty incumbent on them then to answer this power.
The apostle, upon this subject, tells us what people are to do for their own conversion.
He ascribes the power of conversion to Christ Jesus: The prophets and apostles,
they tell us, there is something for man to do, that is, if he hath not power,
he is to be willing to receive it.
The apostle hath a notable expression to this purpose; he puts them in mind,
how they used to do by the devil, when they were the devil`'s servants;
they did obey his commands, and yielded their members servants to unrighteousness:
How did they yield?
They did it heartily, with pleasure and delight.
Thus you did when you did not know the power of God;
but now you are come to the knowledge of the power of God,
"`yield not your members as instruments of unrighteousness unto sin,
but yield yourselves unto God, as those that are alive from the dead,
and your members as instruments of righteousness
unto God:`" Rom. 5:13. Let your minds,
and wills, and affections, be joined to that power which God visited you with;
in love to God, give up your members as servants unto righteousness.

Here is something for man to do in the day of God`'s visitation;
"`thy people shall be willing in the day of thy power;`" when they come to that,
and experience that, this shews that they are the people of God:
But they that are not a willing people, are none of God`'s people, God`'s people are so;
and I pray God make you all so, to be a people willing to be God`'s people,
when he gives you power,
and it will not be long before he gives you power to forsake your sins, to forsake this,
and the other foolish, proud and vain action and fashion;
he hath made Christ Jesus to be Lord and King, and he shall reign over death;
he hath made all things by Christ, and he is become the Saviour of all men,
but especially of them that believe; so that I would have a special salvation,
and thou wouldest have it too: Christ hath made a way,
and opened a door for us to be saved,
that we might have an abundant entrance into his everlasting kingdom:
But I would have a special salvation,
that would invest me with the love of God in my heart, before I die;
it is to be had through Christ, therefore to him will I come, to him must everyone come,
and every knee bow to his name, and everyone must wait for his appearing in the Spirit.
When Christ appears, truth stirs.
Now, if a holy, divine life is in thee, it is he; if a principle of truth stir in thee,
it is he: The same Jesus, only in a smaller manifestation:
He that is faithful in a little, he will make him ruler over much:
This is he that God hath ordained to be the Captain of our Salvation;
this is that which we preach in his name, and testify and declare to all people,
that there is no other salvation, no deliverance from death and hell,
but by and through him; in him there is a reconciliation,
and that "`peace which passeth all understanding`" and power
over all those things which have captivated us,
and made us disobey our great Lord and Maker: Let us wait for the coming of Christ;
he is our Judge, our Law-giver and King, and he will save us:
This was the cry of his people of old,
for the glorious and great salvation he hath given, and the work he hath wrought.
Let the prayers and supplications of all people, that desire salvation,
be put up more and more, that he will visit the earth, and give power from above,
and bring us into that new and living way, which he hath consecrated for us,
through the veil, that is to say, his flesh; to whom be glory, forever and ever.
Amen.

=== His Prayer After Sermon

Most blessed and glorious Father, and Fountain of Life,
and of all living Blessings! whose glorious day dawneth;
by thy power thou hast brought the children of men out of darkness,
that they might walk in the light thereof: Great joy, and strong consolation,
hast then brought unto thine Israel,
unto the people that thou hast gathered by thy arm of power; thou hast made them, O Lord,
to take great delight in thy ways;
for thou hast caused the light of thy countenance to be lifted up upon us,
and thy holy and divine presence hath gone along with us, from time to time,
through all those states and conditions,
and through all those trials and exercises that we have met with,
and that thou hast led us through.

The right hand of thy power, O Lord! hath been with us, and therefore we have not failed;
and thy heavenly blessings have been rained down upon us,
that have made thy heritage to grow and become fruitful, to the honor of thy great name,
and the eternal consolation of our souls.

And, therefore,
O heavenly Father! in the consideration and feeling
of the great things thou hast wrought for us,
and for the continuance of thy love to us,
our souls are always engaged to offer high praises,
and humble thanksgivings to thy great name; and the supplications of our souls,
whom thou hast quickened and brought to life, are daily poured forth upon thine altar,
that as thou hast hitherto helped us,
thy holy and divine presence and power may still accompany us to the end of our days;
and that in all the exercises, and trials, which thou art pleased we should meet withal,
we may find thy presence with us, that thy eternal, heavenly power may surround us,
that so we may be more than conquerors, through Christ, that hath loved us.

And O powerful God of Life! our souls rejoice,
and our hearts are made glad to behold the progress of thy power in our day,
how thou hast brought down the mighty from their seats,
and hast exalted those that are of low degree; how thou hast laid the mountains low,
and exalted the inhabitants of the valleys.

O blessed Father of Life and Power! praises, praises wait for thee in Zion;
and dear Father! by the operation of thy wonderful power, preserve and keep thy children,
whom thou hast gathered into a living sense of thy presence,
that they may bow before thee, and be exercised in a daily, holy,
divine worship unto thee; that so,
powerful God of Life! thou mayest daily pour down thy blessings upon us,
and delight to manifest thyself to be our God;
and let us live as becomes a people that are gathered unto thee.

O Lord God Eternal! carry on thy great work in the earth,
and make known thy power more and more; there are many breathing-ones,
and many that cry to thee daily.
Living Father! it is the operation of thy Spirit that hath raised these breathings,
and kindled these desires in them, and it is thou alone who art able to answer them;
therefore, living God and Father, they are committed to thee; the mourners,
the bowed-down, and those that are laden with sin and iniquity,
and that groan under the pressure and burden of it, let their burdens be taken off,
and the yoke of Christ, that easy yoke, be put on,
and let none of thy commandments be grievous to them,
that they may be made meet to enter into thy kingdom;
let them be brought through the labour and travel of regeneration,
and let none be exalted into the airy vision and sight of things,
but by thy living power, be rising to eternal life in their souls.

And Lord, we pray thee,
fit and prepare all thy people for the work and service
which thou hast been pleased to call them to,
that so thy name may be exalted over all, and thy truth spread more and more;
and let all error and darkness be expelled,
and let the power and influence of thy name be great in the earth,
that all thy scattered people may be brought home, to reside in thy house,
that there may be unity and concord amongst them,
and they may all with one heart and mind, return, and ascribe praises and honour,
and glory to thy holy name, for all thy blessings, mercies and living refreshments,
that we have received at thy hands, for thou alone art worthy, and God over all,
blessed forever and ever.
Amen.
