== Sermon VIII. Saving Faith, the Gift of God Alone.

Preached at Grace-Church-Street, March 8, 1687.

My Friends,

You that are made partakers of that precious faith,
which hath brought you to an expectation of that redemption
and deliverance that comes alone by Christ Jesus,
your minds should be continually exercised in that faith which God hath given you,
for it is a great gift, a blessed gift that he hath given to us to believe.
This never came of ourselves, never was there a true believer in Christ Jesus,
but he received his faith of God, it was the gift of God, it was given to him to believe.
Other sorts of believers there are in the world,
that can communicate their faith one to another;
but they are true believers that have their faith
communicated to them by the Spirit of Jesus Christ,
it is "`given to them that believe;`" and because
it is so excellent and so heavenly a gift,
and hath such large privileges belonging to it,
it is necessary that everyone that receives it, should have a continual exercise in it;
that you may know what it is, and what it doth for you,
and so come to be experienced Christians.
Now all that are partakers of it, they do believe, and know in whom they have believed,
and for what they have believed, even for the saving of their souls.

The true faith, that is the gift of God,
it is not at all short of a complete saving of their souls; they that truly believe,
their faith stands in one that they know is able to save to the utmost;
and so a true believer hath a great comfort in his
faith above all other believers in the world;
for he knows that his faith reaches to a complete redemption,
unto a complete sanctification, unto a complete fitting of him for the kingdom of God.

Now there is no such faith that ever was made by men,
there is no such faith that all the wise and learned men upon the face of the earth,
have either preached or given forth to be received;
for if you come to consider the divers forms of faith that men have ministered,
they will fall short of saving their souls, they fall short of redemption,
they fall short of fitting and preparing them for the kingdom of God,
and so they have not that comfort, that satisfaction,
and that inward refreshment that belongs to the others, or that accrues to their souls,
that have "`the faith of God`'s elect.`"

And herein hath been the privilege of the people of God in all ages,
as well as in our age; their faith hath had a farther extent,
it hath reached farther in order to the good of their souls,
than the faith of all others hath done:
What comfort can a serious Christian take in a faith
that falls short of righteousness and redemption?
Would it not make a man or woman`'s heart ache, to think I am a believer,
but yet I have no faith that reacheth to sanctification, and holy living,
and redemption from sin?
All my faith leaves me a sinner all my days;
to my dying hour there is no mastery to be had, no getting victory over sin,
it will prevail over me as long as I live.

This is not that precious faith that God`'s elect have been made partakers of,
that works effectually in their souls;
this is not that faith that can minister real comfort
to the poor soul that is laden with iniquity,
and weary of sin; the faith that falls short of sanctification, and redemption from sin,
is such a faith as God never gave his people; it came some other way into the world,
and it hath captivated most of the sons and daughters of men,
and they have expelled the true faith (as much as in them lies)
that saving faith that purifies and cleanses men from sin,
and gives them victory over the world, and have got another faith in the room of it;
and they live in their sins, and in their lusts and concupiscence,
and still remain in captivity.

But God was pleased to hear and answer the cry of the souls of
a remnant (for which many of us have cause to magnify the name
of our God) when we had travelled from mountain to hill,
to seek where true comfort might be found,
where one should say to us that we should overcome.
We know there is no eating of the tree of life until we do overcome;
nor entering into God`'s kingdom till we be cleansed.
Some laid an impossibility in our way, which made many a one to mourn.
What, must we never be cleansed?
Must this crooked heart, and perverse will, always remain?
Must I be a sinner and a believer?
A sinner, and call myself a child of God?
How can these things hang together?
These have made many to faint in their minds, and to say as David did in his distress,
"`One day I shall perish by the hand of Saul.`"
One day this corruption will be my ruin; for all my prayers, and hearing,
and other duties and performances, this sin will be my utter ruin at last.

After many have mourned, and been afflicted, by reason of the burden that was upon them,
it hath pleased the Lord to visit a remnant,
and to open their hearts to make known the precious faith,
the "`faith of God`'s elect,`" the "`faith that was once delivered to the saints.`"
Is this the faith that is worthy of an earnest contending for, and preaching for,
and suffering for?
Who was ever so mad,
as to suffer for such a faith as will leave a man under the power of Satan,
and his own lusts?
No wonder that such have a faith that is not worth contending and suffering for.
Who will expose themselves for such a faith that will never do them a kindness?
Now that faith which belongs to a purified soul, to one that is sanctified,
that faith delivered to the saints, it is called a shield;
when once a Christian comes to make use of this faith as a shield,
he will find the power of it.
A shield is that which is worn by persons that are among enemies;
it is for the defence and safeguard of one that is beset with enemies;
and a good Christian is so situated.

There is a sort of blind Christians, friends to the world, their christianity is worldly,
and their faith worldly; but all true Christians are in the midst of their enemies,
inward and outward; and if they had not the shield of faith to defend them,
they would certainly be wounded every day, they would be slain and lose their lives:
The faith that is called a shield,
it is that by which a Christian is to be defended
and saved from harm designed against him every hour;
for the devil goes about like a roaring lion, continually seeking whom he may devour.
The apostle speaks more particularly to believers; the devil, your adversary,
he is an adversary in himself, but more especially your adversary that are believers;
that have believed to the saving of your souls.
You that believe that Christ is sent of God,
endued with power sufficient to break his head,
and power to redeem you out of his service and bondage, the devil will be your adversary:
Let him be so, if I have but my shield.
This is that which if a man use, he will quench all the fiery darts of the devil.

If a man come once to receive the faith, the true faith, faith in the power of God,
this faith will remain victorious over temptation;
but if thou dost not keep thy faith in a continual exercise,
thou dost not deserve the name of a true believer: If a man receive the true faith,
and grow careless in his christian exercise, will not this adversary, the devil,
be about his ears?
Will not he send forth his fiery darts at him; his temptations, and snares, and gins,
to entangle him, though he be a believer,
if he doth not keep in the continual exercise of his faith?
But a true Christian, that feels the power of the grace of God,
and is in the continual exercise of true faith, he is like a watchman or sentinel,
that hath his armour on, and his shield ready,
he knows he is on the borders of his enemies quarters,
and he keeps himself in perpetual watchfulness,
in daily expectation of the devil`'s fiery darts; he keeps his shield in readiness;
I see a temptation lies in such a thing,
but I see the Lord`'s power is able to keep me out of it.
I see there is profit or pleasure in the snare; it is a hook that is baited,
but I see the hook through the bait, blessed be God;
and I have a confidence in his power, and that he is able to keep me from that thing,
for all the baits of profit, pleasure, or the friendship of the world.

A believer keeps in the exercise of his faith,
and considers that his salvation is nearer than when he first believed;
the people that believe, are not presently saved,
the work of salvation is to be wrought after they believe; "`for without faith,
it is impossible to please God,`" "`nevertheless the foundation
of God standeth sure,`" it is founded upon the power of God;
when a man believeth, the work is begun; though some foolish professors tell us,
that the work is done when the act is only in the mind;
they will tell you what day of the month,
and such a day of the year their conversion was wrought; but they know not what they say.
A man may possibly know when it was brought about:
A man may know about the time when God communicated faith to him;
but he must know after he is a believer, then begins the work of salvation,
the believer is to be saved from this or the other enemy;
he is not presently saved from all, there must be a warfare,
a fighting the good fight of faith, before these enemies of his salvation are overcome;
the devil will not give over because I am a believer,
and because Christ promised to break his head;
the seed of the woman shall break the serpent`'s head.
I am now but putting on my armour; the battle is not fought;
I have not yet gone through the peril of the fight; I am now buckling on my armour;
when the fight comes, if I have not my shield and my armour ready,
I may be slain for all this; some have made shipwreck of faith, they have not held it,
nor kept the faith, but given it away: But saith the apostle,
"`I have fought the good fight, I have kept the faith,`" I have gotten the victory.

So people, after they are believers,
they must wait to have their faith strengthened by renewed
manifestations of the same power in which it first stood:
They must wait upon the Lord, and he will renew the strength of their faith,
zeal and courage; and as temptations are renewed, they have new courage,
and new strength and new ability, and all by this divine,
spiritual and Christian exercise; they every day come to see the work they believed,
that which their faith tended to, see the work in some measure wrought,
they see some enemy of their souls brought down and slain,
and they see their souls come up to a little more dominion than they had before;
they see the devil`'s power is weakened more than before,
and that he hath not so much power as he hath had over them.
These things are some encouragement to raise up in a true Christian,
living praises to God; seeing, by believing,
he hath found thus much encouragement by the working of the word,
why should he not wait on the Lord for the accomplishment of this work,
that he may believe to the saving of his soul,
that he may come to receive the end of his hope and faith, the salvation of his soul?
Now, by thus keeping their faith in exercise,
they know that their salvation is nearer now, than when they first believed.
It is not so with everyone, for many that have believed, their salvation is farthest off,
because of their negligence, professing one thing with their mouths,
and doing another thing in their practice;
there are some things which they believe and profess, and yet do the contrary;
that puts their salvation further off, and draws them secretly into desponding,
and into a losing their courage and zeal for God;
the custom of sinning hath at last taken away the sense of sinning.
It is so with a man when he first transgresseth the rule, he is somewhat tender,
and doth it with some regret; but after he is come to a custom of doing it,
he is pretty well at ease,
and so by degrees he goes on towards the state of being past feeling.
At last such sinners come to dying; they were dead once before,
and were quickened through the operation of the Spirit of Christ Jesus;
they were quickened, and if they shall die again, if you die a second time,
pray remember it is a second time; you that are careless and ready to die,
remember it is the second death that you are going to;
and consider that if you die the second death,
you shall have no part of the first resurrection: Better such had never been born at all,
than after they have lived in hope, to lose it again.
This is that which was upon my heart to commend unto you,
that you may partake of this precious faith,
that hath a tendency to the saving of the soul, and fitting you for the kingdom of God.
Hath God given you to believe?
And will you not believe that you shall live without sin?
If you come to obtain this precious faith,
you will believe that you shall come to live without sinning against God,
and have the light of his countenance shining upon you.
He that truly believeth, his faith reacheth to this, and he will say to himself,
I am saved a little from the liberty of my tongue,
and from many sins of an evil practice: God hath redeemed me from my vanity,
pride and passion, and other things that were troublesome,
the Lord hath redeemed me from them; I see the work is going on,
and I am nearer to the kingdom of God than when I first believed;
I have gotten victory over many of my spiritual enemies,
and I hope the Lord will carry me on,
and keep me by his power through faith unto salvation: Hitherto the Lord hath helped me,
I have not fought in vain, I have not been beating the air,
but God hath given me victory over the tempter inwardly and outwardly,
so that he could not prevail, whilst I kept the shield of faith over my head;
but when I have been careless, and not exercised my faith as a shield,
I have been weak as other men.

You are not called to weakness and feebleness, but to the power of God,
that you may be exercised in it, and by it be kept from the evil of the world:
There is a possibility of being kept, if you be faithful to him that hath called you,
that is, Christ Jesus, the Captain of our Salvation, if you follow him step by step,
and do not run headlong all at once;
when you see a great deal of sin and corruption before you,
and seek to master it in your own strength, you will lose the victory:
The same word that sheweth us our sin, sheweth us our own inability to overcome it,
and that we can do nothing without divine assistance;
though we lie long struggling under the weight and burden of sin,
we cannot of ourselves get victory over it, we cannot bring judgment into victory,
God must have the glory of it.
If you keep to Jesus, he will carry on the work; you did believe in him,
for he did work this faith in you, and he will carry on his own work,
and his own work shall praise him.
All others that talk of faith, and make an empty profession, they dishonour God;
they talk of perfection, and living without sin, but never experience it,
and so bring dishonour to God: If you wait to see this work carried on;
if you believe and exercise your faith for the overcoming of your sins,
and "`perfecting holiness in the fear of God,`" you will hereby bring glory to God,
who alone is worthy of all praise; who is God over all, blessed forever more.
Amen.

=== His Prayer After Sermon

Most blessed, holy,
and unchangeable Lord God! thou hast visited us by
thy dear Son and our Saviour Jesus Christ,
to gather us to be a people unto thee, who once were not a people, and once not gathered.

Everlasting Father! thy mercy is great, and thy goodness is great,
and to be greatly prized by us all;
thou hadst compassion on us to help us when we could not help ourselves;
and thou hast laid help upon one that is mighty and able
to save to the uttermost all that come unto thee by him.

Blessed God,
and Father of our Lord Jesus Christ! we give thee thanks
for thy abundant mercy and goodness extended to us.
Lord God Eternal! extend thy mercy more and more;
and visit the children of men in all nations with the knowledge of thy truth.

Blessed Father of Life! we pray and cry to thee, that thy work may go on,
and that it may prosper and increase, and let the day of thy visitation be extended,
and reach forth thy Almighty Arm, that the children of men may be gathered unto thee.

Blessed Father of Life! thou hast shewn mercy to our souls,
and we have seen the goings of God in his sanctuary; thou hast, by an out-stretched arm,
gathered us to be a people to thyself; thou hast appeared for thy people in all ages,
and thou hast saved them out of oppression, and stilled the fury of the enemy.
Thou hast cut Rahab, and wounded the dragon, and made way for thy people Israel,
that they passed through the Red-Sea as on dry land.
Lord, do so for thy people spiritually in our day, and make way for them,
and open the door that thy gospel may spread, and run, and be glorified,
and have a free course among us; and that thy worship may be set up,
and pure incense may be offered up to thee.
O Lord! this is the cry of thy servants, and the voice of their supplications to thee,
that thy Spirit may be poured out abundantly and operate upon them,
that thy word may be profitable and welcome to their souls.

Blessed Father of mercy! thou hast blessed thy children
and people with spiritual blessings in Christ Jesus.
Thou hast given us thy pleasure this day; and blessed be thy name,
thou hast refreshed our souls at this season;
let our praises ascend as a sweet smelling savour, and acceptable service to thee:
And for all thy mercies and renewed favours and blessings to us, and to all thy people,
both here and everywhere, let thanksgiving and living praises be rendered to thee;
for thou alone art worthy of all blessing and praise, who art God over all,
blessed forever.
Amen.
