[short="The Divine Life of Christ Jesus."]
== Sermon XIII. The Divine Life of Christ Jesus.

[.signed-section-context-open]
Preached at Grace-Church-Street, March 16, 1691.

The blessed life of Christ is not of this world;
and it ought to be your care in all your religious assemblies,
that you be gathered into the inward, feeling sense, of this divine life;
that you may feel your fellowship and communion in
that life of Christ that is not of this world.
And may all of you lay hold upon it; for this is the nourishment and the heavenly bread,
with which the children of the kingdom are fed and nourished from day to day;
there are many that feed upon words, that are not the children of the kingdom of God;
but the begotten of God are come to know the virtue of the divine life, Christ Jesus;
their feeding and their nourishment is by every word
that proceedeth out of the mouth of God,
and they grow up to life eternal by that divine and heavenly gift,
that God the Father hath bestowed upon them, through his Son Jesus Christ;
and they enjoy the communion of saints, through this divine Head of the Church,
that communicates of his life and virtue through every member,
by which they are sanctified,
and every day more and more prepared for that living and
eternal inheritance laid up for the children of God.

And when there are a people that are thus gathered into the life of the Lord Jesus Christ,
they are able to draw nigh to God; they feel the power of entrance,
because their sin is removed that did formerly lie at the door;
and the way is opened and consecrated for them to
draw nigh and partake of the table of the Lord,
by which they grow stronger and stronger in his might and power,
and are thereby enabled to perform the whole will of God,
and that divine worship and religious service,
which God requireth at their hands in their day.

For it is very certain, and we have found it by experience,
that the words of our Lord to his disciples of old are true;
"`without me (saith he) ye can do nothing.`"
For though people may meet together, and may pretend and set up a form of worship,
and of religion in their own wills, yet it all amounts to nothing,
with respect to acceptance with the Lord; there is no return in their souls,
no addition of life, nor increase and growth of life;
they are not nearer the kingdom than when they first believed,
but many times further off; by leaning upon a formality,
and not really entering into the work of God, nor travelling out of death into life;
for there must be a path, and a travelling in it;
the soul must have an exercise through the power and life of Jesus,
for the overcoming of death, that did separate from God, and a preparing for life,
that life that unites us to God again: And when people are in earnest in this travel,
they are resigned up to the government, direction and leading of him that is gone before,
that hath made a way for us, and will further our progress towards the kingdom of God.

And, therefore, my friends, you know the way, and know how the power hath reached to you,
and hath opened your understandings that you may
be faithful to that power in your own souls,
and may have the use and true improvement of this, and all other such meetings as this,
for the gathering of your minds out of all visible and changeable objects,
unto that life which God hath revealed, that so in the exercise of it,
you may hold your fellowship with God, and with one another;
here is the bond of perfection, here is that in which God hath created peace and rest,
and joy for his people; so far as everyone is partaker of this innocent life,
and feels himself changed into it, they are gathered into the church,
and they are gathered into fellowship with the head of it,
and are comforted in their membership, in their partaking together.

Though I be but a little one,
yet I partake of the same virtue which the Lord administered to the greatest saints,
while I am a waiting upon him, and of the same divine consolation, and operation,
and power that weaneth more and more from the world, and that which is corruptible,
and raiseth up in me daily more and more fervent
desires after that bread that perisheth not.

Now herein men and women have an evidence of that Christianity in themselves,
the Spirit of God bearing record and witness with their Spirits,
which all the loose professors of Christianity in the world are strangers to,
their evidence in themselves, being against them;
they seek to have evidence without them, and to gather up some kind of marks and tokens,
and sayings, and sentences, from without them,
to make them believe that they are in covenant with God,
and that they are in a state of salvation by Christ; but he that truly believeth,
hath an evidence of his Christianity, and of his reconciliation with God;
and he hath this evidence in himself, a divine,
spiritual testimony that answereth to his own spirit, that witnesseth to him,
that he is one of the children of God.

And my friends, to this you are called, whether you are come to it or no;
it is this you are called to with a heavenly call,
that you might no longer live in the rudiments of the world,
to be seeking and looking here and there, for a ground of peace and of rest;
a ground of hope, but may know and feel the same thing,
the same ground of eternal hope that the saints of old had; what is that?
what reason did they give and render of their hopes of eternal glory?
The apostle tells you plainly the ground or reason of their
hope of being glorified in the world to come,
was Christ in them the hope of glory.
They witnessed that Christ gave his life for the world.
Take the glorious testimony that the apostle did bear in one of his epistles; saith he,
the life was manifested in me; it was not covered up or hidden,
that people could not find it; God was pleased to bring it to light by the gospel;
when a thing is brought to light, you may see it.
This he affirmed in his day, and the same is affirmed in our day.
The life is manifested; what life?
Not the life of this world, but a life not defiled, not polluted,
but the life that is of God, a heavenly life that is holy and pure;
that life is manifested; we have seen it, and we exhort all to lay hold of it,
to lay hold of eternal life: Some had a sight of it, that had not laid hold of it;
they saw it in a vision, and they might say possibly, oh that I could live such a life,
that there were no sin in me, in my words, or thoughts, or actions,
what a gracious life would that be!
They had seen that life, they had tasted of it, but they did not lay hold of it,
but let it go by them: Take heed of that, when you have seen it with open eyes.
"`Blessed are your eyes, for they have seen, and your ears,
for they have heard,`" saith Christ to his disciples: They saw that life that was holy,
harmless and undefiled.
Lay hold on this life, especially when you are thus assembled together,
in a solemn manner in the presence of the Lord, waiting to behold it,
and see it more and more discovered to you,
and labour to have that gathering power that will bring you to it,
that you may know the strength that comes by it to the soul.

There is none of you, but what will meet with temptations in this world,
that will draw you into death and darkness, to things that are carnal, and sensual,
and devilish sometimes.
How shall I stand if I be not centered in that life that was before the world began,
and before the devil was?
If I labour to feel the influence of that divine power, that is able to keep me,
my faith tells me so: I know that power is able to keep me,
if I keep in the exercise of it.
The trust of a true believer is,
that whatsoever temptations and trials they are exercised with,
they know one already come, in whom they have trusted,
who is both able and willing to deliver them.
So by this means he is kept harmless, and innocent,
and blameless in his life and conversation.
Thus you might be kept, if you would regard,
and have respect to the life that is manifested in you.

Whosoever comes to know,
and feel and witness in their souls the discovery and revelation of the life of Jesus,
they know there is in it a certain dominion over that which is contrary to it;
and many of you had experience of the exercise of the power of God in your own hearts,
that hath enabled you to reign over those things, that have formerly ruled over you:
That you can now subdue vain thoughts, and evil desires,
that you can withstand temptations that come from without, and from within.
Now if you could do this, and if ever you have done it,
you did it by that power that God discovered and revealed in you from Jesus Christ:
You had not such hold of this once, before you believed, but by believing,
the word of God sent it unto you; it being fixed by faith in the heart,
that faith which is of the operation of God:
You could then do that which you could not do before,
and forbear that which you were led away by.
These experiences which God hath given you,
should encourage you to hold on in your labour and travail,
and engage you to "`grow in the grace of God,
and in the knowledge of our Lord Jesus Christ.`"
Whatsoever is propounded by men in the profession of religion,
this ought to be our design and end,
in the discovery that is made to us of the life of Christ; that we may grow in it,
and live in it;
(indeed there is great talking of it) but we should labour
to shew forth the resurrection of that life in us.

They that come to be baptized for the dead, are baptized into the death of Christ;
the apostle tells you, "`in that he died, he died unto sin.`"
There are none baptized for the dead, and made partakers of the death of Christ,
but those that died unto sin, as he died.
Though Christ had no sin, yet he died unto sin: What use did he make of this,
that Christ knew no sin, but yet did take our sin upon him?
He died unto sin, that they which did partake of his death,
might be partakers of his resurrection: He liveth again, and after death riseth again.

Those that partake of this death unto sin, are crucified unto this world,
and have taken up Christ`'s cross,
and are dead to all the pleasures and delights of this world,
which are withered away and come to nothing.
What do they live to now?
To righteousness, holiness, chastity, temperance; these are pleasant to them;
these come to live to righteousness, through the power of him that loved them.
This shews the glory and the power of the grace of God.
It is the grace of God that worketh such a change in a man or woman.
They that delight in sin and wickedness, in that which is corrupt and ungodly,
they have no delight in this, no delight in sobriety, chastity, holiness,
and purity of mind.
In whom hath it wrought such a change?
In all that are freely given up to it.
Where anyone is given up to that life, the grace of God hath the praise of it.
This is the exaltation and praise of the power of God; so that others may find by this,
that they may by it come to believe, and by believing, to be saved.

Thus the gospel hath gone forth, from one to many, and from these to many more,
and is increasing more and more; for grace, mercy and peace, are multiplied,
by which the heritage of God, and so every man and woman that partake of this life,
are gathered into fellowship.

So that your end in coming to these meetings, is not so much to hear what this, and that,
and the other friend saith; but what you have in yourselves to witness to:
The divine operations of the power of God in your souls,
bringing down something that is to be brought down,
and raising up something that is to be raised.
Temptation to sin hath more prevalency upon me, than it hath upon this, and that,
and the other man.
I am not come to their degree,
yet it is better with me than it was at my first convincement.
If thou dost say this and deceive others, cry to God,
and pray earnestly that all may be brought down which is contrary to his grace.
If thou sayest and professest this, to strengthen that, which is known,
by the light of Christ, to be against the truth of God,
if at the same time there is a deceitful heart,
how will this appear at the great day of God?
The eye of God is upon thy hypocrisy; he that never slumbers nor sleeps, he beholds thee,
if there be any sin that thou wouldest keep and save alive.
If thou makest a profession, and notwithstanding sayest, this sin I will keep,
the Lord pardon me in this thing; like Naaman, the servant of the king of Assyria,
who said to the prophet, "`thy servant henceforth will neither offer burnt offering,
nor sacrifice to other gods, but unto the Lord.
In this the Lord pardon thy servant,
that when my master goes into the house of Rimmon to worship there,
and he leaneth on my hand, and I bow myself in the house of Rimmon;
when I bow myself in the house of Rimmon, the Lord pardon thy servant in this thing.`"
He knew if he bowed not, the king would take notice of the alteration of his gesture,
therefore he would bow in the house of Rimmon:
That sin he would save alive under a profession: That hypocrisy the Lord did abominate.

Be upright in the sight of God, and be faithful to your own souls; if it be so,
then every sin will be a burden, and you will long to be rid of it; if it be so,
you know whose hand it is that hath brought you so far; if you be really cordial,
and give up yourselves to Jesus, that work which he hath begun in you,
he will finish for you.
He will finish it for you, stand out with him in nothing; give up yourselves to him,
and join not with his enemies; take heed of hearkening to them;
take heed of every sin that will at last be a burden and oppression to your souls.

But if you live this heavenly life of Jesus, you will be set at liberty,
to have dominion over sin, and to stand without guilt before the throne of God.
Friends,
let your hearts be deeply affected with the great
mercies that God hath bestowed upon you,
and for his gift to you of that divine life that is acceptable in his sight.

Many things have been done upon the account of religion,
and we could never be satisfied whether they were acceptable to God;
we could not be satisfied whether we did anything pleasing to God:
We may say of them as the apostle Paul did of the Jewish sacrifices,
there remains a conscience of sin, an accusing conscience, that tells us,
that guilt is not removed, nor the sin taken away,
till the Lord opens this divine mystery to us,
that our justification must be by faith in Jesus;
that nothing could reconcile us to God but the life of Jesus, and the merit of his death.

This life of Jesus was a holy, blameless, harmless, and innocent life,
which "`life he gave for the world;`" which "`life is the
light of men;`" and our souls being turned to this life,
we see the glory and the excellency of it,
and desires are kindled in our hearts after it.
Many have pursued, and laboured, and travelled,
that they might come to the enjoyment of it.
The very discovery of this life ought to be highly prized,
and your souls affected with it; and when you have obtained it, you will say,
O! what a blessed condition am I come into! that
Christ hath manifested his divine power in me,
not only in reconciling me to God, but taking away the conscience of sin;
by that alone the accuser is cast out, and I may now sing to God, songs of deliverance.
Now you taste of the mercies that God hath bestowed upon you;
this will affect your souls with a childlike submission and subjection to him,
that hath begun to save and deliver you,
that so you may resign up yourselves to his will, and forsake the world,
and the things of it.

Now when these come to such a meeting as this, their minds may be retired,
and they may be sensible of the power of truth upon their hearts;
but for want of keeping their subjection to the divine power,
that hath opened their understandings, when they come into the world again,
they are ensnared and entangled, and many times, for want of watchfulness,
through a looseness of mind, and unruliness of tongue, they run into anger and passion,
and this grieves the Holy Spirit of God.
And how should you come to God through the Mediator, when you grieve his Spirit,
and quench the motions of it.

These things have been hurtful to many,
that in their time might have been pillars in the house of God.
Take heed of this, and let the goodness of God dwell upon your minds,
that you may feel and experience the inward administrations of it;
there are many that are much affected with the outward ministry,
and are very desirous to hear the servants of God
declare the things that God hath wrought for them,
and in them, and the wonderful things that God hath opened to them;
yet when you have heard all that man can say about it,
if the divine ministry of the word of God doth not make powerful impressions upon you,
and sanctify and renew your souls, the outward ministry of the word will do you no good.

Now that you may be established in the truth that you have been taught,
this testimony ariseth in me,
to desire everyone to heed and attend to the manifestation
of this life of Jesus in yourselves.
Whatsoever God hath bestowed upon me or another, you may perish for all that,
and I am not the better for what God hath bestowed upon you,
but may perish notwithstanding; but that God hath manifested eternal life to my soul,
let that be everyone`'s centre: This will make you holy and blameless,
and preserve you in every state, and in the hour of temptation,
and in the midst of snares; this will be a bulwark to you;
this will be as the walls of Zion, which is the salvation of the Lord.
That so you may be preserved sensible of the goodness of the Lord: That grace, mercy,
and peace may be multiplied in your bosoms;
this will make you dear and affectionate one to another.

Though there may be an external fellowship among
those that preach and profess the same doctrine,
yet when they come off from that, when once men depart from the power of truth,
they grow stubborn and rebellious;
but when men come to be gathered into the inward
fellowship that stands not in terms and words,
but in the revelation of Christ, and in the participation of his virtue and goodness;
the more you are united in this, the more you are knit one to another,
and become useful and helpful one to another.

The Lord vouchsafe to everyone of you a taste of his goodness,
and you will prefer it above all that the devil has, and his instruments can present;
and if you retire more into this heavenly and divine life of Jesus,
you will feel and enjoy more peace and satisfaction, and true consolation in your souls,
than I, or any man in the world can tell you of.
