== Sermon XIV. The Kingdom of God Within.

Preached at Grace-Church-Street, July 26, 1691.

You have read and heard much concerning the day of the Lord, as a great and notable day;
many of you are now living witnesses that the great and notable day of the Lord is coming,
in which the accomplishment of great and notable things, the mighty works of God,
which have been prophesied of, may be lawfully expected.
It is the work of every Christian to wait upon the Lord in the light of this day,
and to be acquainted with the works of the Lord, both inwardly and outwardly;
for the day of the Lord is a day of power,
and that power of God worketh wonderful things;
and if we are not kept in the light of that day, the Lord may work great things,
and we not know it;
we shall be looked upon as careless and negligent witnesses of the works of the Lord,
as those that do not regard them.
If you would be faithful witnesses, you must have regard to the works of the Lord,
and the operations of his hands.
One that is minded to be a faithful witness,
he will take notice of what is said and done;
you are called to be witnesses of the works of the Lord Jesus Christ, and of his doings;
you must stand where you may hear, and see,
and understand what the Lord is about to do at this time.

In testimony and witness bearing,
the greatest thing we have to expect in this day of the Lord, is,
that God will set up the kingdom of his Son Christ Jesus;
and unto this all the prophets did bear witness in their time,
and now it is our turn to bear witness of it,
by sensible and living experiences of the accomplishment
of those things that they prophesied of,
that the Lord will set up the kingdom of Christ,
and bring down and lay waste the kingdom of Antichrist.
This our Saviour taught his disciples to pray for more than sixteen hundred years ago,
that the kingdom of God might come;
and all the true disciples of Christ ever since have prayed for the coming of this kingdom,
and many of them have seen the coming of it, and rejoiced;
and others have died in the faith of it,
and have been gathered into the kingdom of Heaven.

But, my friends, that which chiefly concerns us at this day,
is to behold the kingdom of Christ, the eternal Son of God, within us,
to go forward and prosper; and the kingdom of Antichrist suppressed and destroyed,
and utterly laid waste; and this is wrought two ways, first, inwardly; second, outwardly.

First, inwardly; there is a great inclination in the minds of people,
to look more at the operation of God`'s power in this great work outwardly,
than to look at it inwardly, but unto that there must be a daily cross taken up,
and it is my business at this time to tell you in the name of the Lord,
that your duty and mine is to turn our minds to the working of the power of God in ourselves,
and to see that other kingdom of the man of sin weakened and brought down within us;
then there is no fear but he will carry on his work outwardly,
and we shall see as much of that work as belongs to our generation;
but the great matter and chief government of you and me,
is to see the kingdom of God set up within us,
which stands in holiness and righteousness:
Our business is to walk till we see the righteousness of this kingdom set up within us,
in our hearts and souls, and to have a real change made.

We all know, and we must confess, that we have been subject to the man of sin,
whatsoever we are now.
We have seen the reign and government, the rage and tyranny of the wicked one,
that hath led us into rebellion and disobedience to the Lord our Maker.
How do we like that government, to be ruled by the devil, and to be led captive,
and to be made to do his will, and to rebel against God that gave us our life,
and breath, and being?
How do we like the government of Satan?
I hope we do none of us like it.
It was so with me; and they that are under the tyrannical government of Satan,
have many cries and wishes in their souls, that they were freed and delivered from it,
and brought under the government and obedience of Christ Jesus;
and that they were able to serve God as they ought to do,
that they might be translated from the kingdom of sin and Satan,
into the kingdom of the blessed and dearly beloved Son of God.

This hath been the cry of some ever since they have known the word;
and I am persuaded it is the cry of many at this day.
I have good news to bring you; not that the day of your redemption draws nigh,
but that it is come; the day of redemption is now come,
and there are a great many blessing and glorifying the name of God that they are redeemed,
and delivered from the bondage of corruption;
and have more joy and delight in the service of God, that made them,
than ever they had in the service of the God of this world.

But may not some say, how shall this great work be wrought?
For it is a great work,
and we verily think that nothing but an Almighty Power can effect it.
For there are many in this assembly have been trying to no purpose,
and done what they could in their own strength, to deliver their own souls from death,
and yet they find themselves in bondage still; nay,
they have called in the help and assistance of those
that they thought to be stronger than themselves,
and all have failed, and they are yet weak and entangled,
and they cannot find themselves at liberty to serve the Lord as they ought to do.

I am of this mind, that nothing but the Almighty Power of God can do it;
and when you have come to my experience, to know this as I have done,
then I hope you will seek after that, and you will see good reason for it;
and you will then come to this profession, if the Lord puts not forth his Almighty Power,
I must then perish, for there is no other power can deliver me.
When you come to know this, what must you do?
Why you must wait for the revelation of that power that will take you
off from all trust and confidence that you have ever had in anything else:
A man that hath nothing to trust to but the Almighty Power, and mercy,
and goodness of God, he puts his whole trust and confidence therein,
or else he knows he must perish.

When a man or woman comes to this pass, that they have nothing to rely upon but the Lord,
then they will meet together to wait upon the Lord:
And this was the first ground or motive of our setting up meetings;
and I would to God that this was the use that everyone
would make of them that come to them,
then they would be justly and properly used,
according to the end of the institution of them at first;
we should use them as poor desolate helpless people that
are broken off from all their own confidence and trust,
and have nothing to rely upon but the mercy and goodness of God;
and if he pleaseth to reveal his power among us, we know that he is able to save us.
And when we have met with the revelation of God`'s power,
and we have met together in simplicity of mind,
the Lord was pleased to communicate his Spirit to us, and open a door for us,
and discover and reveal to us that it was the day of his power:
And when we came to examine ourselves whether we were willing in this day of God`'s
power (for the prophet gives us a note of distinction between the people of God,
and other people;
"`thy people shall be willing in the day of thy power;`" which is as much as to say,
when God discovers and reveals his power to them,
such a people are willing to give themselves over to the government of it;
when we found we were subject to it, we had joy in believing,
before we attained the end of our hope; it was gladness to us we found ourselves willing;
and I am persuaded that everyone of you would be glad to find yourselves
willing to part with that which you cry out against.

What a cry is there of our bondage and corruption,
and of our being led captive by our lusts.
We may hear such a cry from one end of the kingdom to the other:
People cry out of the bondage of corruption, and of their subjection to sin and Satan:
I would they were in earnest;
there is not that earnestness and reality in men and women that God looks for,
and so there comes nothing of it.
There is no redemption, and no deliverance; the Lord doth not hear them,
though they come now-a-days into his presence, to offer up their prayers.
I would have you to be in good earnest, I wish well to you all;
and it would be hard to say that you do not wish well to yourselves.
Here lies your welfare,
that you find yourselves willing to be subject to the power that made you;
you have been subject doubtless to the power that destroyed you;
that power that never gave you life and breath,
and would be instrumental of your destruction:
The power of the God of this world never did men good, but destroyed them, deceived them,
and deprived them of their lives.

Now if there was but a willingness in everyone of us,
freely to give up ourselves to that power that created us, to obey his will,
I am sure there is never a man or woman among us
should long be without the knowledge of it.
If I am but willing to be subject to the law of him that made me,
it will not be long before he discover it to me,
and reveal his power in me in the glory and excellency of it;
that power which is more able to preserve me, than all the power of men on earth,
or all the power of the devils in hell is able to destroy me.
When the Lord shall discover and reveal his power in you,
you will be willing to be subject to it.

But methinks the sound and noise of flesh and blood grows loud here:
I would be subject to God, but I would not have him cross mine interest,
and deprive me of that I love and thirst after;
I would not have him embitter my carnal delights and pleasures,
and undo me as to my reputation in the world.

You may see whence this comes, that you would make a bargain,
and draw a contract with the God of your lives about these things;
this is a nonsensical thing; because of all people in the world,
you are a people that have had a veneration for the holy scriptures,
the scriptures of truth,
and have been acquainted with them as familiarly as with any book in the world,
wherein you find articles drawn, long ago fixed and sealed;
and no new ones are to be drawn.
If anyone will be my disciple, John or Thomas, James or Peter, or whosoever he be,
he must take up his daily cross, and deny himself, and follow me.
Now here is a contract made,
therefore turn aside from all kind of reasoning and consulting with flesh and blood.

If you will become spiritual, and partake of spiritual blessings and benefits,
I would advise you to turn from all kind of reasonings that come from the pit of darkness,
that hath thus far deceived you, and will ruin you forever, if you hearken to them.
For assure yourselves, new gospel-terms no man can make;
and if any come to preach new gospel-terms, count him a deceiver;
for there is no possibility of being a disciple of Christ,
but by taking up a daily cross, and denying ourselves,
and following him as our leader and guide.
To him I must go, and go in no other way, speaking nothing,
and doing nothing but what is holy and pure; he must conduct me in my walking,
guide me in my way, and justify me in it.
This is to be a true disciple of Christ.

As soon as he comes to adhere, and join to the power of God revealed in his soul,
he sees the coming of the kingdom of God; he sees it at a distance;
he saith within himself, and makes this conclusion, I will follow my captain;
I will become subject to the kingdom of Christ.
If I obey this divine principle of the grace of God, and the gospel of Christ,
I shall be his disciple.
I read in his blessed book, "`that as many as are led by the Spirit of God,
are the children of God.`"
I am not to propose new terms, but to accept of the old terms of the gospel of Christ.
I see that the kingdom of God is to be set up,
and the kingdom of the devil to be brought down in me; if I follow this divine principle,
I shall never follow the devil more; if he would have me lie, I shall refuse,
and say I cannot; if he would have me run into vain and corrupt communication,
and foolish jesting, that will be a bridle to me, that I cannot do it.

I speak now to persons that live under the light of the gospel of Christ,
and that are subdued by his grace;
I would speak that which all the logic in the world cannot overthrow;
that which the most cunning logician, with all his wit and quirks,
cannot refute and prove erroneous.
If a man be led by the Spirit of God, he cannot lie; this is a common cure for all men;
if I be led by the Spirit of Truth, and hearken to the principle of truth in my own soul,
this will cure and heal me of the wounds and maladies of my corrupt nature,
and set me at liberty from my old master; I do not like his service.

I hope if any of you like the servitude and bondage of sin and Satan,
you will desire liberty before you die: Why do not you desire it now?
It may be thou thinkest to enjoy a little liberty, and reputation,
and pleasure in sin for many years, for six or seven, nine or ten years,
and then break off from it, and repent and turn to God:
How dost thou know that thou hast ten days to live?
It is of high concernment to every one of us to wait for a discovery of gospel liberty,
and an ability and power in his soul,
to enable him to break off from the servitude and bondage of sin and Satan,
that he hath so long lived under; and to wait upon God with patience,
for the setting his soul at liberty, and setting up the kingdom of Christ within him,
and pulling down the kingdom of Satan, that he may be brought into the kingdom of Christ,
that consists in "`peace and righteousness, and joy in the Holy Ghost.`"
These are the things that follow one another; when righteousness is set up in me,
I shall not be disturbed, I shall have peace; and if I have peace I shall have joy,
and this joy is in the Holy Ghost;
the apostle saith the kingdom of God consists in these things.

Now that everyone might be persuaded that God hath given a measure of his grace to them,
as well as to other folks, let them consider and say within themselves,
God hath not shut me out of the number of his people:
He hath knocked at the door of my heart, to bring me to repentance;
he hath waited upon me so long, surely he hath a mind to save me: Would he call upon me,
had he not intended I should repent and turn to him?

But where is the power?
you will say; knocking at the door of the heart, and checks of conscience,
we understand them; but we understand not where the power is,
to be conformable to the will of God.

People will never understand it while they are in the kingdom of Satan,
and under the power of the prince of darkness; the apostle tells us,
that "`the god of this world hath blinded the minds of them that believe not,
lest the light of the glorious gospel of Christ, who is the image of God,
should shine upon them.`"
If men saw the beauty of the gospel, they would run after it, and embrace it;
therefore the devil blinds their minds,
that they should not see the beauty and amiableness of the gospel,
and like the terms of it:
He hath the rule and government of the children of disobedience.
So long as I live in subjection to that devilish, hellish power,
which leads me forth into sin, I shall be a stranger to God`'s power,
that would enable me to break off from it.

You never read in scripture of any that ever came to be saved by the power of God,
but there was faith mixed with it, that came to join with that power of God.
Our Saviour said to the impotent man,`"thy faith hath made
thee whole;`" thy faith joining with that power of God:
We shall be made "`strong in the Lord,
and in the power of his might,`" and be able to withstand temptations.

As soon as the soul of man joins with the grace of God,
he doth forsake the service of his old master and governor:
Sin shall no longer have dominion over him; though he may meet with the same temptation,
it shall not have the same power over him,
but he will be enabled by the grace of God to withstand it, and overcome it.
If you ask such a man,
how it is that he overcomes that temptation that formerly prevailed over him,
he will tell you, I have now an helper, I am now joined to the grace of God in my soul,
therefore do I withstand temptations, and have power over them.
Thus comes the kingdom of Christ to be set up in the soul,
and this is that which will sit and prepare us for the everlasting kingdom of God.
They that do wait upon God, shall see this work wrought inwardly in them,
they know more by faith than they can see by sense.

I know, and am certain, that the power the devil hath in the world, shall be broken down,
and righteousness shall be exalted, and justice and equity shall prevail in the nations.
I shall not perhaps live to see it, but I may see it by faith;
I have seen enough for my generation, and they that live in the next generation,
shall see it also; for the church of God is the same from one generation to another.
Now unto us it is given to see the things that in former generations were prophesied of,
God having (saith the apostle) "`provided some better thing for us,
that they without us shall not be made perfect.`"

The church of God from one generation to another,
have their measure and degree of service, and bear their proper testimony,
and leave the rest to succeeding generations:
It concerns us in our generation to see a change made inwardly in our souls,
and the kingdom of Christ set up within us,
and the kingdom of Satan brought down in ourselves.
This doth not concern my son or grandson only, but it concerns me,
and when they grow up to mature age, in their time it will concern them:
Therefore that which is most profitable to us, is, that we have such a station,
and stand in such a place in our time, where we may see the work of God carried on.

I have considered, many a time, that there are many brave men and women in this age,
that might have been eminent witnesses of God in this world,
and borne their testimony to his truth, but their faith hath been weak and ineffectual:
They have discovered their unbelieving hearts,
and have joined with the common herd of the world,
because they thought such great things could never be done,
that the kingdom of Satan could never be pulled down and destroyed,
and the kingdom of Christ set up within us, but I would hope better things of you,
things that accompany salvation; and that he that hath begun a good work in you,
will carry it on to perfection, that living praises, and joyful thanksgivings,
may be rendered to him who alone is worthy, who is God over all, blessed forever;
to whom be glory and dominion forever, and ever.
Amen.

