== Sermon XV. The Undefiled Way to Eternal Rest.

[.signed-section-context-open]
Preached at Devonshire-House, July 29, 1691.

[.salutation]
My Friends,

The Lord will be with all his people, that are undefiled in the way,
that are spiritual travellers walking in that undefiled way,
that leads to an undefiled rest.
There are some that by this way are entered into rest,
that rest which God hath prepared for them.
We cannot apply to ourselves that promise that is made to us of entering into rest,
unless we be real and true travellers in the way that leads to it, for if we do,
we deceive our own souls.

Therefore you that have had a sight and vision of the way everlasting,
that leads unto a holy rest, you are an engaged people to make strait steps therein,
and to have it your daily care, and make it your continual business,
to look that your goings and foot-steps are of the same nature
and kind that the rest is that you desire to enter into:
For it is an undefiled rest, that we all are, or ought to be travelling after;
therefore everyone of us must be undefiled in the way,
and every foot-step must be of the same kind and nature,
and separate from all that which defileth it and polluteth it;
that so it may have a tendency to the bringing of the soul nearer to its rest.

This holy rest many travellers have attained by this holy travel,
and many are still in hope to attain it.

But now they that are full of hope of attaining this rest,
their foot-steps and goings are not of the same nature and kind;
they are not holy and pure, they are not undefiled;
These have not their faces truly Zionward,
though the face of their profession may stand that way;
but the Lord looks at the heart of everyone, and he knows which way the heart stands,
they who have their hearts truly turned to the Lord,
they have the mark of holiness in their eye,
and the mark of purity and righteousness in all their undertakings,
because they know there is no attaining to that divine rest,
but by a holy way and travel; therefore their trust and reliance is alone on the Lord,
that is to keep them in all their way;
for if they be ever so clearly convinced that holiness and righteousness is their duty,
and is the way whereby they may attain to the kingdom of God,
though they are ever so fully convinced of it,
yet there lies an impossibility of any walking therein
without the divine assistance of the grace of God;
for though they have been convinced by the appearance of his grace,
and have had a light that openeth to them a sight of these things,
it is not this sight and vision that will enable
them to run the race that is set before them.

For the manifold impurities and hindrances which are in our way,
between our coming out of Egypt`'s land, the bondage of corruption,
and our entering into the kingdom of God,
are too mighty and too great for any man with his knowledge and strength to overcome.
The children of Israel might as well have gone through the Red Sea,
without the help of God, as the Christian traveller can go through the many difficulties,
and the many impediments that he is to meet with in his way,
without the assistance of God`'s Holy Spirit.

My friends, it hath been a labour and travel at this time upon my mind,
that all whom God hath so signally blessed with the knowledge of the truth,
that you may see your way, and most clearly know and understand,
that your way leads to life eternal;
that all and every one of you in your particular meetings,
are to have a dependence upon that which can help you in your way.

For I have seen too many that have had a wrong dependence,
after they were rightly convinced,
and after they have had a true knowledge of their way wherein they should walk;
they have too much trusted to openings and sights which they have received;
they have thought their mountain so sure, and that their feet have been past sliding,
that there hath grown up a state of presumption,
that they have thought they should never turn aside,
and have not had due regard to the renewing of the Divine Power of God in their souls,
that God`'s children always must have.
They have (as I may so say) forgotten what our Lord said,
"`without me ye can do nothing:`" They have passed
a sentence upon that doctrine in their minds,
and they have thought they could do something; that they could withstand temptation;
that they could do some work for God, and service to God,
without the Divine Assistance of that power that did beget them;
and alas! the least they have sustained hath been, that they have run into evil,
and they have defiled their way, and run into temptations,
though it hath pleased the Lord, whose mercy is infinite,
to pull them many times back again out of the snare which they were fallen into,
and to take them again, and to wash them, and cleanse them, and purify them,
and set their feet on a sure place.
This was more than they deserved; but his mercy, and goodness, and tenderness,
is over all his works.

This he hath wrought for many a one; and not only once, but many times;
it is hard venturing; it had been better if such a one had never fallen,
or that their footsteps had never slid from the ways of the Lord,
than after they are fallen, to be renewed again by repentance.
It hath caused sore judgment, and condemnation, and anxiety of spirit;
and they have given their old enemy an advantage to whisper in their ears;
thou hast lost thy ground; thy sins are gone over thy head,
and thou shalt never find repentance.
These are the words of the wicked one, who seeks occasion against us;
and through our carelessness, and not being watchful, we put an advantage into his hands.
Now seeing you know he is vigilant,
and seeks occasion that he may turn you out of your way,
before you attain to the end of it, you ought to be vigilant to keep occasions from him.

But some may say, how may I keep occasions and advantages from the enemy?
I answer, the way hath been often told you, and I dare say most of you have tried it,
and found it to be true,
that so long as you have remained in a watchful state and posture,
and have had your minds exercised by the grace of God,
by which you were convinced of your sin, and by which your duty was manifested to you,
so long you gave the enemy of your souls no occasion;
but the truth preserved you wherein you trusted,
and wherein you hoped and waited for the virtue and power of it.
Did you find want of ability then?
Did the enemy prevail then?
He did not cease to tempt when you was in the most watchful state of a Christian;
the devil did not then cease to tempt you,
but you found in you a power that resisted him, and said, "`get thee behind me, Satan.`"

So long as you are upon your watch;
so far as you keep your mind fixed upon the Divine Power,
so long you are in a sure place; and whosoever turns aside from this,
they suffer great harm and prejudice; and if ever they be restored again,
it is with loss and damage, and sore exercise; and if they be not restored,
they are lost to all eternity:
Then "`it had been better for them not to have known the way of righteousness,
than after they have known it, to turn from the holy commandment delivered to them.`"
And then they said within themselves, this must be the way.

Sirs, these things pertain to your everlasting welfare;
I speak to you as a people that God hath abundantly loved;
and it hath been far beyond anything of desert.
He hath made known his ways to you; the Lord may say, concerning you of this city,
as of old, "`what could I have done more for my vineyard, that I have not done?`"
So he may say concerning you, what could I have done more to make them a grown people,
a holy people, an entire people, that they may bear my name,
and walk before me in holiness and righteousness, all the days of their lives?
What should have been done more for them?

But this is an exercise to us, whom God hath blessed, and set as watchmen,
to behold and see the state of his people,
and to feel and bear the burdens that are to be borne; and this is a great burden,
that after all that God hath done, and that we do in the hands of God,
all that is necessary for the welfare of the people, there are some that turn aside,
and defile their way; and we testify in the name of the Lord,
that whosoever walks in a defiled way, shall never come to an undefiled rest;
therefore that you do not attain to that undefiled rest,
it is because ye have been defiled:
Seeing the holy conversation of the people of God is the
effect of the working of his own power and Spirit.

Here comes the rest, by and through a Mediator, even Jesus Christ the righteous,
who is the Mediator between God and man,
and the leader of all his people in the way of holiness and righteousness,
which he hath made manifest to them that believe and obey the power:
And he hath purchased eternal salvation for all that believe and obey the gospel:
But the transgressors do not obey the gospel;
the Spirit of Christ doth not lead you to transgression;
and the power and light that comes from Christ, doth not lead you to pride, vanity,
envy and bitterness: Wherever these things are led into, there is another spirit,
and that other spirit hath another tendency, it leads into the wrath of God.

And my friends, this is that which my soul desireth at your hands,
and it is for your good and advantage; it is my duty to discharge my conscience,
and to speak plainly as the Lord shall give me utterance,
to warn you that you abide in the truth; for if so be you be not saved,
but will turn aside after your own hearts lusts,
after your pride and the vanity of the world, and the lusts thereof,
you may blame yourselves, and your iniquity will be your ruin.
We that have given up ourselves to God for your sakes, and the churches sake,
we speak these things which we have learned of God,
and we earnestly press you that are convinced,
that you walk in the truth which you have believed:
There is no great need of more knowledge,
and of the vision of heavenly and divine things;
for abundance of you have seen more of the things of God,
than ever you have travelled and come up into.
I would to God, that everyone of you that are convinced,
would come up to the measure of the knowledge you have received.
O! that you would answer the Lord`'s power,
in opening and discovering his mind and will concerning your travel,
and the things that belong to his everlasting peace,
that your foot-steps may be directed thereby.
If you will walk in this undefiled way, you may lay down at night,
and rise in the morning with peace, and in the favour of the Lord,
and have the answer of a good conscience in his sight.

The means that must help and conduct us in this way,
must be that familiar converse that the soul must have with something greater than itself;
the familiar converse that the soul must have with the Divine Power,
with that manifestation of Divine Light and Grace, which, through Jesus Christ,
God hath given unto you.
For if a man prize and esteem the truth ever so much, and suffer ever so much for it,
and love the minister ever so much, if he keep not a familiar converse with the truth,
notwithstanding all his profession of love to the truths of the gospel,
and the preachers of it, he will reproach it: Though he professes and says, I love thee,
I love thee; though he hath suffered much in the way,
yet if he love not the truth in his own heart,
and desire not to feel the excellency and virtue of it,
that man will certainly dishonour the truth, and grieve the Holy Spirit of God.

We warn you to take heed of your way, and to your feet in your Christian walk,
that you may come to have an abundant entrance into the kingdom of God.
Pray to God that the work of regeneration may be wrought upon you,
that you may be born into another seed, and partake of the divine nature: Then,
though the devil assault you, he cannot overcome you;
he will find nothing in you whereby to betray you into his hands,
when that change is wrought, and when God hath made an alteration,
and hath brought you out of the love of the world, and the love of earthly things,
and "`set your affections above, where Christ sits at the right hand of God.`"
Now you can say, here comes a temptation with this instrument, and the other instrument,
and the devil lays things before me that he would have me to do,
but I have no inclination to it, I have no mind to be sucking at the world`'s breasts;
but my mind is set upon this, that I may reach acquaintance with God,
who will be a present help to me, and tread down Satan under my feet.

There is need of your continual care and vigilancy,
and that you watch and pray that you may not enter into temptation.
It is not so easy a thing for a man or woman while
they are in this world to do anything without sin;
but God hath called you to a holy profession; which is,
that you should do all you can do, to do everything you do without sin:
For whether you eat or drink, or whatsoever you do,
you should do all to the glory of God.
This spirit we would have in you,
and we would have all you that have received Christ Jesus, the Lord,
to walk in him as you have received him: Then you shall be kept undefiled in the way,
and delivered from temptation.

To this end you must be still, waiting upon the Lord,
that you may have acquaintance with him from day to day; you are in the world,
but you should not be of the world: The prayer of our Lord Jesus Christ,
to his heavenly Father for his disciples,
was not that he should take them out of the world, but keep them from the evil.

Merchants, tradesmen, and shop-keepers, have always something to do in the world,
but they should pray earnestly that they may be kept from the evil of the world.
There is nothing can be done in the world, but there is evil in it,
which we shall be overcome by, if we do not keep our watch.
In the government of a family,
there are occasions and provocations given to be passionate and furious;
many occasions are given to men and women; but we should not be transported and overcome:
Our profession obliges us, that when a child or a servant gives a provocation,
we are not to behave ourselves unseemly, and unbecoming our holy profession;
for it is not in their power, nor in the devil`'s power either,
to kindle your wrath and anger into a flame: If you are upon your watch,
and wait upon the Lord,
he will give you wisdom and strength to stand against all temptations whatsoever,
and to order your conversation according to the will of God,
and as becomes the gospel of our Lord Jesus Christ.

In merchandize, buying and selling, there are snares, and there is evil we may run into;
but this is our comfort and joy, there is no coercion, we cannot be forced to sin,
the devil can only lay a temptation before me; if thou wilt tell a lie, equivocate,
dissemble, here is an advantage for thee; but the devil with all his subtlety,
power and allurements, cannot say, thou shalt run into this sin,
and be overcome by this temptation; for though of ourselves we can do nothing,
yet in the name and strength of our Lord Jesus Christ, we can do all things;
we can do that which is just, and stand over the temptation, and trample upon it,
and "`not be overcome of evil, but overcome evil with good.`"
When we have bought and sold, we may look back upon what we have done with pure minds,
and clean consciences in the sight of God, and we may come off victors,
and "`more than conquerors (over temptations) through Jesus Christ that hath loved us.`"

The more a Christian keeps himself unspotted, and the more watchful he is in his walking,
he may go on from day to day, and see the snares of the devil, that lies in this vanity,
and this and the other vanity and temptation, and yet escape it.

I would I could say of some of you, that when the devil laid a snare for you,
you did not run into it when you saw it.
I have known some that have had understanding enough,
that they need not be told where the snare of the devil lies; yet so hath it been,
the devil and their own hearts lusts have agreed together,
and they have run into the snare.
This is from the old confederacy that men have had with God`'s enemies;
"`you are my friends,`" saith Christ, "`if you do whatsoever I command you.`"
If you are the friends of Christ, you will be his subjects, and yield obedience to him;
when he shews them a snare they will keep out of it:
This is the proof of a true Christian, that he will be true in a time of trial,
and will trust in that divine power that keeps him out of the snare.

One thing more I would say, that divine fellowship that you have with Christ Jesus,
it consists in holiness of life and conversation,
and the exercise of a good conscience towards God, and towards man.
It is in vain to tell me that you will walk in unity with the truth,
unless you have unity with the truth in your own hearts; you cannot deceive the Lord,
nor long deceive his people either.
Here is the fellowship that you are to live in all your days,
to live in fellowship with the people of God, and communion of saints;
can the saints have communion in anything but holiness?
and holiness is a blessed, sacred thing, it becomes the house of God forever;
they that are saints, are sanctified and made holy; and "`he that sanctifieth,
and they that are sanctified, are all of one; for which cause,
he is not ashamed to call them brethren,`" Heb.
2:11. They that are sanctified are become saints,
they bring forth the fruits of holiness and sanctification,
and they are come into fellowship with God and one other.
"`Every branch in me,`" saith Christ, "`that beareth not fruit, he taketh away;
but every branch that beareth fruit, he purgeth it, that it may bring forth more fruit.`"
That branch which beareth not fruit, is cast into the fire and burned.

There are some that bring forth fruit, but it is fruit to the flesh, and the wicked one,
but I hope you are not of that number:
These separate themselves from the life of the true vine;
these have no fellowship nor true membership with the church of Christ,
while they walk as captives to the devil, and sin; these are of the world,
and not of the church.
If you would have fellowship with the church,
do not think to have it by outward conformity:
Do not think that this will maintain your fellowship with Christ,
without a life of inward holiness and righteousness;
for that day you break with the truth in yourselves,
you break off your fellowship with the church of God, and break your peace with God,
and can no way be restored again to the favour of God, but by an unfeigned repentance;
for the mystery of faith is to be kept in a pure _conscience:_
How is my conscience defiled, if I wrong not this, or the other man or woman?
Some can hold the mystery of faith; so far as it consists in a profession,
they can profess it, and they preach it;
but they have not held the mystery of faith in Christ, so as to receive life, and virtue,
and comfort from him.
You have got the history of words and doctrines;
but as soon as you defile your conscience, by doing evil things,
and depart from the principle of grace, you make shipwreck of faith.

But, my friends, as you have a mind to continue and abide in the faith,
and in this travel and heavenly journey, I would give you this as a certainty,
it may do you good when my head lies low: The way to continue in the church of God,
and communion of saints, and to retain your peace with God,
is to keep a familiar converse with the truth in your own souls,
and it will keep you from falling, and lead and guide you in your way,
in your travel and journey to Heaven.
As the mother, when the child cries after her, but cannot go,
takes it by the hand and leads it, so if you keep close to the truth,
it can lead you through all difficulties, through great business as well as little,
and deliver you from snares and temptations, and when you are assaulted,
it can bring you off clear.
As for communion with God, and communion with the saints and people of God,
it stands in that peace, and purity,
and keeping a holy frame of mind in your heavenly travel, in the undefiled way,
that will at last bring you to the undefiled everlasting
rest that remains to the people of God.
