[short="The Excellency of Peace with God."]
== Sermon XVII. The Excellency of Peace with God.

[.signed-section-context-open]
Preached at Devonshire-House, August 5, 1691.

[.salutation]
My Friends,

It is man`'s great happiness in this world to have acquaintance with God,
with the Lord that made him, from whom he hath life and breath here,
and his eternal welfare hereafter;
this doubtless everyone will acknowledge one time or other,
that peace with God is a great jewel, and the best estate and riches.
It is the great desire of everyone that they may attain to this one time or other;
and there is a great neglect of happiness among the sons and daughters of men,
in not seeking of it, and not labouring to attain it while it is to be had;
Oh! how many trifle away their time about sliding and perishing objects,
and they know at the same instant that they are yet destitute of the favour of God,
and peace with him.
Oh, friends! the very thoughts and consideration of the worth of this jewel,
and of the misery of being without it,
and the uncertainty of our time while it is to be attained,
might put everyone upon a serious,
diligent inquiry after the way and means whereby they might attain it,
that so they might have a resting-place for their souls,
and satisfaction to their inward man, that it shall go well with them,
when time shall be no more.

And they that come to this consideration, and are resolved in their hearts and minds,
that they will labour after this, and set their whole endeavour after it,
they will in the first place seek "`the kingdom of God,
and the righteousness thereof:`" These do need a
daily encouragement in their way to Heaven,
and there is nothing on the Lord`'s part wanting to such souls,
but that they may attain their desire.

But alas! this hath been, and is still the misery of thousands,
they are seeking after peace with God, but they err in the way to it,
they do not seek in that way, nor take hold of those methods,
by and through which God hath promised peace; you shall scarce meet with anybody,
but they would have eternal life and peace with God;
we shall not need to persuade people to wish for,
and to desire to have peace with God when they shall come to die,
and lay down their heads in the dust.
There is not a Balaam, but he desires to die the death of the righteous,
and that his last and way be like his: There is not a Scribe, or a Pharisee,
or any that profess religion, but they are seeking eternal life.
The Lord Jesus did witness concerning them, that they were an envious, proud,
persecuting people, yet that they did seek after eternal life,
and they pitched upon some methods and ways whereby they thought to get and enjoy it;
but all this was error still, they were out of the way of attaining it,
and so are a great many people at this very day;
they are in a state and condition wherein they are never like to enjoy it;
the methods and the ways that they have chosen to themselves, to find eternal life by,
and to obtain peace with God, will never answer the end.

And God hath been pleased to discover to us the many by-ways that people have chosen,
and seek peace with God by; therefore we are willing at all times,
to shew people their error in these great matters of highest concernment to them.
If they did err in their way of seeking to obtain some earthly good,
and missed their end, they know the price of it, it is but a loss of so much,
which if they had taken a right course, they might have attained;
but it is an unspeakable loss, an inestimable loss, if they lose peace with God,
and all the pains and labour they are at to obtain it.

I beseech you, friends, consider these things, they are of great weight,
and you will say so one day or other; for, saith our Saviour,
"`what will it profit a man to gain the whole world, and lose his own soul?
Or what shall a man give in exchange for his soul?`"
O! How sad is it to consider, that a man hath not made provision for his soul,
that he hath not a place of rest for his immortal soul,
and that the arms of the Lord Jesus Christ are not open to receive his soul,
when his body can retain it no longer!
If this be a man`'s state when he comes to die,
it had been better for him that he had never been born: Men may live and gather riches,
and enjoy a plentiful estate; but if they be destitute of the favour of God,
and peace with him, what will they do with these perishing enjoyments?
They cannot possibly satisfy themselves with these transitory, visible things;
but if these persons only mind their bodies, and neglect their souls,
do they not live like the beasts that perish?
The beast seeks after his meat, and when he finds it,
he eats it with delight and pleasure, and in a little while he lies down and dies,
and there is an end; so it is with careless souls,
that have no regard to their future state; but they say, "`let us eat, and drink,
and be merry, for tomorrow we shall die.`"

Oh! that everyone of us did apply our hearts seriously to the consideration
of the weight of these things that concern our eternal state;
if persons did this, then they might come to an inquiry into their own souls,
what method and way is most safe for the attaining of so blessed an end.
For you know there are abundance of people, if you look up and down in the world,
you will see everybody almost hunting up and down in some way of religion or other,
and are engaged in religious performances: What is the matter?
what would you have?
We would have peace with God here,
and everlasting rest hereafter in the kingdom of Heaven; that we would have.
Thus have the nations been scattered and driven up
and down in the pursuit of happiness and satisfaction.

There is a general belief amongst people, that there is a Heaven, and a Hell,
and that they must have their part in one of them;
there are none that desire a portion in the lake that burns with fire and brimstone.
Those profane wretches that cry to God to damn them, they do not mean what they speak,
they would be saved for all that; everyone will cry at last, Lord have mercy upon me,
if he hath but time to say so: Let us cry, Lord have mercy upon me now;
Lord bestow thy savour upon me;
"`Lord lift up the light of thy countenance upon me;`" Lord touch my hard heart,
and soften it and break it, by the power of thy Spirit; "`open mine eyes,
that I may see the wonderful things of thy law; open mine ears,
that I may hear thy voice.
It is good for people to make use of time while they have it;
whosoever calls upon the name of the Lord shall be saved,
and God will pour out his wrath upon those that call not upon his name.
He that calls upon the name of the Lord, shall be saved;
and God gives great encouragement to people to seek after him.

What mean you by seeking after God?
I have gone to church, and said my prayers;
I have gone in the way which my fathers have led me, and directed me,
I hope I shall find mercy at last; I am a believer,
I believe in Jesus Christ that died for my sins, and rose again for my justification;
I hope, through the merits of Jesus Christ, I shall be saved.
What mean you by seeking after the Lord?
Do not we all hear of him, and pray to him every day?

Is there anything more common than this, that people speak to one another generally about?
as for the general knowledge of God, you and I may see to our sorrow,
that a great many Lord, Lord, that are never like to enter into the kingdom of God.
If all that take the name of God in their mouths,
should enter into the kingdom of Heaven, it would be a very foul kingdom:
If all the drunkards and whoremongers of England, and all profane ungodly persons,
that will take the name of God in their mouths, should enter into the kingdom of Heaven,
it would be a very unclean and impure kingdom;
there is nothing enters there that is unclean, that is abominable,
that loveth to make a lie.
So that there must be some more peculiar people that shall
have an abundant entrance into the kingdom of God;
and there must be something that will entitle them to it.
For you may remember our Saviour saith, "`no man knoweth the Father but the Son,
and he to whom the Son shall reveal him.`"
So much as may be known of God by works, you and I may know,
without the revelation of Christ; we need not wait for this knowledge,
we can have it by books; we can have it by Christ`'s revelation.
Nothing would serve some in our Saviour`'s time, but eternal life;
and our Lord Jesus bids them "`search the scriptures,
for in them (saith he) you think to have eternal life,
and they are they which testify of me.`"
Yet for all the profession they made, he tells them, no man hath seen God at any time,
neither seen his shape, nor heard his voice; they were strangers to God,
though they had a general knowledge of God.

So it is at this day; there is a general knowledge of God,
and people hope to obtain peace with God, and eternal life.
Their parents and their tutors have instructed them in the principles of Christianity,
and about the attributes of God;
but all this will not bring a man to a saving knowledge of God,
and reconciliation with him: For a man that is as wicked as the devil can make him,
knows these things, and yet may be a servant of the devil, and do his work;
he is not born again, and become a child, In all his external knowledge.
Now he that desires to come to the true, saving knowledge of God,
our Saviour hath told us, "`that none knows the Father but the Son,
and him to whom the Son will reveal him;`" this is
a sure way to come to the true knowledge of God,
by Jesus Christ; he hath the key that openeth the heart,
and he will bring us to the true knowledge of God the Father.
Christ hath the key of David, "`which openeth, and no man shutteth; and shutteth,
and no man openeth.`"
He can bring us to behold the glory of God in his own face;
without him we are never like to come to the saving knowledge of God.

Poor man is in a lapsed, fallen state, he is fallen into sin,
and is in a state of alienation from God,
and therefore he cannot come to him but by a Mediator;
there is one Mediator between God and man, the man Christ Jesus,
and he must make peace for him, else he will never have it:
How then shall we come to Christ, if he is the only means,
and there is no other by which we may come to the knowledge of God,
as the scripture speaks?
Hearken to it, how may we come to Christ?
I answer, you will never come to him; if he first come not to you,
you will never be able to do it.
It is not coming to Christ, when you say, you do believe that Christ died and rose again,
and ascended up into Heaven, and sits at the right hand of God,
and lives forever to make intercession for his people,
and to read those words and doctrines which he preached up and down at meetings,
and solemn assemblies; but if you believe that he is the eternal Son of God,
and "`the author of eternal salvation to all that obey him,`" you must come to him,
and entirely give up yourselves to his glory and service; without this,
you cannot come to him, nor will he bring you to the Father: Christ is come near to us,
he stands at the door of our hearts, and he stands and knocks:
"`Behold!`" that is a word that calls for attention, for people to take notice of.
"`Behold, I stand at the door and knock;`" what dost thou knock for?
saith Christ, that thou mayest open the door of thy heart; for "`if any man open,
I will come and sup with him, and he with me, and my Father will come to him,
and we will make our abode with him.`"

Now people are loth to be at this pains and trouble,
to open the door of their hearts to Christ,
for they will not believe it is Christ that knocks, and that rebukes and checks them,
when they refused to open to him;
when they find something within that reproves them for their sin,
and doth condemn them that they cannot be at quiet,
they will never believe that this is Christ: How can this be Christ?
they say, He is ascended up to Heaven, and he is at the right hand of God the Father:
Will you make me believe that this is Christ knocking at the door of my heart?
I cannot believe it: But what saith our Saviour, "`unless you believe that I am he,
you shall die in your sins:`" For there is nobody else can help you out of them.

There is a two-fold consideration that we are to have of Christ; one is,
as he was "`made of a woman,
made under the law;`" and another consideration of Christ is,
as he is the eternal Son of God.
Men have very gross thoughts of Christ, to think, that because he is in Heaven,
therefore he cannot be here too: They measure him by themselves;
they know because a man is at London, therefore he cannot be at York at the same time.
Thus these men object, if Christ is in Heaven, how can he be here?
His doctrine and precepts are here, let us make use of them all;
he will come again at the day of judgment; but this is a day of judgment:
Doth not he judge you now?
He is the judge both of quick and dead, and he is the searcher of hearts,
and the trier of the reins; so that thou canst not think an ill thought,
but he will tell thee of it; he is nearer to thee than the wife of thy bosom,
or thy husband that is near to thee: Husband and wife may think an ill thought,
but they cannot tell one another of it; but Christ is one that comes so near thee,
that thou canst not conceive an ill thought against thy neighbour,
but he will tell thee of it.

This is the Lord Christ, as a Spirit, a quickening Spirit,
who is made manifest in the flesh:
He hath given to every man a measure of the Spirit to profit withal:
"`The grace of God which bringeth salvation, hath appeared unto all men.
"`Notwithstanding the distinction of learned men
between common grace and spiritual grace,
this grace "`that brings salvation, hath appeared unto all men.`"
This manifestation of the Spirit and light within, we have from Christ.
These are the ways and methods that the Lord Christ hath taken to approach near to us.
Now your own reason will tell you,
if this be the way and means that Christ takes to approach near to us,
we cannot take another way to approach to him: If Christ hath taken, I say,
this way to approach to us, by the light and manifestation of his own Spirit,
which convinceth us of sin: If this be Christ`'s way of coming to us,
there can be no other way of our coming to him, but by the same method of his grace.
He saith, "`if you have the light, believe in the light.`"
I have the light, I am enlightened, there is something that discovereth my evil thoughts:
Why must I believe in the light?
That you may be children of the light, as our Saviour speaks;
they that are the children of the light shall have it for their inheritance;
and they that are children of darkness, must have darkness for their inheritance:
While we have the light, we must believe in it,
and we shall be made children of the light: God hath sent his Son,
and the Son hath sent his Spirit and his heavenly grace into our hearts,
that we may draw near to him, and be directed how to attain acquaintance with him,
and to do that which pleaseth God, and come to be in union with him,
and do the works of God.
This is that which God requires of us, that we will believe on him whom he hath sent;
that we may embrace the light, and believe in the light, in the Lord Jesus Christ.

Pray what do you mean by believing?
There is something within me checks and reproves me for sin, and calls me off from it,
and bids me turn over a new leaf: Must I hearken to this?
Is this that which you mean by believing?
As to this degree of believing, they that reject it now, shall believe it hereafter;
for all the world at last,
and the damned in hell shall certainly confess that there was grace, and light,
and means afforded to them, and they might have gone farther,
and escaped that misery that they are fallen into.

But there is a more precious faith that I would have you partake of,
a "`faith that worketh by love.`"
Since the Lord hath been so gracious as to extend his mercy and love to me,
I am so taken with the love of God, that I will be obedient to him;
this faith that worketh by love, is the faith of God`'s elect;
that by which we may obtain victory over our passions and lusts,
and over Satan and the snares of the world;
when we are come to close with the grace of God, and to believe in Christ, this is well:
But we must also yield obedience and subjection.
Yet when faith hath brought forth obedience, you cannot be justified by it,
you cannot be saved by your obedience, but Christ alone:
He is the author and finisher of our faith, and a Mediator from first to last.

Now all that come to close with the appearance of Christ in their own heart,
they have laid hold of the method appointed for their coming to him.
It is Christ they must hear; he is come so near to men that they may hear his voice,
and hear him tell us our very thoughts.
Why should not I hear him when he checks me and reproves me for sin?
He comes near and tells me that I have done amiss; Lord, I have done iniquity,
I will do so no more.
Thus Christ converseth with his people, and doth not only check and reprove them,
when they do that which is evil, but persuades them and enables them to do good.
He is a Mediator, he is a middle person, and hath taken flesh upon him,
that he might reconcile them to God, that do believe in him.

Now, when we come to have acquaintance with God, and have chosen him to be our God,
he teaches us to do what is good, and reproves us for what evil we have done.
Who can choose a better guide, to lead him into acquaintance with God,
than Christ that is conversant with us, piercing into our thoughts, and speaking to us?
I may hear him with the inward ear of my heart; when I do evil he checks me for it,
and tells me the thing I should seek is of inestimable value;
and if through my unbelief and carelessness I miss of it,
it had been better for me that I had never been born;
now we are in the way of coming to receive the end of our faith,
the salvation of our souls, let us not "`neglect so great salvation.`"
No man can save himself, nor save the soul of his brother, nor find a ransom,
nor procure an offering for the expiating of his sin;
therefore let everyone that would have his sin expiated and pardoned,
and cannot be satisfied and quieted, till he hath peace with God; let him come to Christ,
the Mediator, and come with faith and truth in the inward parts, and submit to him,
and be willing to be ruled by him, then Christ will save him,
and present him without spot and blemish to his father.

Consider that those that are the people of God, are led by the Spirit of God.
They miss their way to reconciliation with God, that love any other way,
or think to come to God any other way than by Jesus, the Mediator,
their labour will be lost:
Therefore I must exhort and persuade you that are out of the way,
that you would take God`'s method, and come into God`'s way.
The terms, I have told you, are made already; the bargain is not to make now;
I will give so much to be at peace with God,
or I will part with this or the other thing that is dear to me.
No, the agreement is made between God and Christ,
and his covenant is "`ordered in all things,
and sure;`" and his covenant stands sure with none, but those that are in Christ Jesus.
There was a covenant made with Abraham;
"`in thy seed shall all the nations of the earth be blessed.`"
The promise is made to the seed, that is, to those that are in Christ;
the faithful are counted the seed;
now the faithful are those that are obedient to Christ, who is the seed of the promise,
in whom all the families of the earth are blessed.
They must come to Christ the seed, they must not rebel against him;
they must come to him, and believe in him;
be there never so many nations and families in the world, the promise is not to them,
but to as many as the Lord our God shall call.

Here is the way for people to lay hold of, for their coming into acquaintance with God,
which is of so great necessity before they die;
they must come to Christ himself by his Spirit in their own hearts.
We need not go to this and the other learned man,
and inquire of this and the other sort of people;
but we must cry to God for help and direction, and come unto him,
and give up all the powers and faculties of our souls to him, to be governed by him:
God will have servants that will be obedient to him; if ever we come to obtain salvation,
we must have another master, one is your master, even Christ;
I must come under the government of Christ, and he must lead me, and rule me,
if I will be a child of God.

When people come to see there is no effectual way,
but submitting to the grace of God in their own hearts,
and yielding themselves up to the dictates of the Spirit of Christ in their souls;
when they come to this, there are many hazards and difficulties to be encountered with;
there is the appearance of the cross of Christ,
and we must take up this cross if we will follow Christ,
and be obedient in all things unto him.
This is that which will kill all my pleasure, lay waste all my religion,
and destroy my hopes; I must be like a man that built a house without a good foundation;
I must pull it all down again, and I must come to build up again upon a new foundation.

Here many have turned aside, the cross of Christ hath seemed to them so sharp,
and hard and intolerable, that they could not bear it;
they would not be at the charge of such a religion; what,
must I part with all my delights, and my beloved lusts and pleasures,
and all my interests in the world for Christ?
I cannot part with these, these things lie in my way,
I must rather lose my soul than part with what is so grateful to me,
and join with the light of mine own conscience, and the truth in my inward parts; what,
must not I have so much as liberty of thought?
What, must my thoughts be regulated by that which is so cross and repugnant to my mind?
Must I throw out all evil thoughts out of my heart,
and suffer none but good thoughts to remain there?
Who can stand here?
Who can bear such strictness as this?
Rather than endure this, I will choose to lose my soul;
many have lost the truth on this account, and many are in danger to lose their souls.

If there be in you any desire of peace with God,
that you may not go hence before you have attained it,
take hold of the present opportunity; hardness of heart is a desperate plague,
it comes from a long obstinate continuance in sin;
when we have withstood the day of God`'s patience and long-suffering,
and grieved the Holy Spirit of God; then God giveth us up to our own hearts`' lusts,
because we will not hearken to the voice of the charmer, charm he never so wisely;
when we stop our ears, and will not attend to the calls of God; when men will go on,
and nothing can stop them, in the career of their lusts and pleasures,
but they will retain their carnal delight and friendship with the world;
this hardness of heart is a desperate plague; take heed of it,
that it doth not overtake you, and bring ruin and destruction upon you:
Consider the patience and long-suffering of God,
and let his goodness lead you to repentance:
Consider God hath waited to be gracious to you,
he hath exercised much long-suffering and patience towards you;
whereas he might have cut you off long ago,
and given you your portion with the damned in hell;
but he hath hearkened to the Mediator that hath pleaded for you;
he hath extended his patience and long-suffering to the wicked and rebellious also;
and for this reason, the apostle tells us, that Christ is the Saviour of all men,
especially of them that believe.

Now the patience and long-suffering of God hath been lengthened out to all,
and we have not improved it.
Conscience hath been sensible of the inward strokes and rebukes of God for sin,
and of the inward calls of his grace to bring us to repentance;
but we have not regarded these calls, nor hearkened to the voice of God, so as to hear,
that our souls might live; O! let us not put off our repentance any longer; but today,
while it is called today, let us hear his voice, and harden not our hearts,
but be of a tender heart; let our hearts be softened, and tendered under the word of God,
and under the strokes of his judgment.
If ever the Lord bring you under a tender frame,
you will receive the word of God with meekness, and mix it with faith;
then it will work effectually to the amendment of your lives;
it will work faith in those that are unbelievers,
and strengthen the faith of those that believe.
Then we shall have cause to bless the Lord,
and praise and magnify his great name for his patience, long-suffering and mercy,
which at this day he hath lengthened out, and graciously extended to us.
