== Sermon XIX. The Mighty Work of Man`'s Redemption.

Preached at Grace-Church-Street, Feb.
8, 1687.

My Friends,

We are met upon the most weighty affair that can be to everyone of us,
even to wait that we may have a true knowledge of the beginning,
carrying on and perfecting the mighty work of redemption,
that people may know that redemption is wrought in their souls;
for everyone`'s soul hath been lost and captivated,
and led away from the pure presence of God; all have been alienated by reason of sin,
which hath been an universal wall of partition and hath
excluded and shut out unholy souls from the Holy God;
all that have been defiled and polluted, they have been excluded from his dwelling place,
they have been driven out into the world, and the world hath become a world of misery,
and of distraction and confusion to the sons and daughters of men;
there hath been anguish, tribulation and wrath upon all their souls,
and an insensibility hath happened unto many,
that they have not been apprehensive of the great depravation they have lain under,
and they have not been sensible of the glory of that
state and condition which they were to have enjoyed;
and in that state of insensibility they have not sought after the Lord,
but have been captivated and led away by divers lusts and pleasures,
by which they have wounded their own souls more and more.

And in such a state as this it is, that the Lord hath found us; he hath sought us out,
and he hath found us "`cast out into the open field,`" and wallowing, as it were,
in our own blood;
and yet this hath been a "`time of love;`" and he
hath manifested his love to us in this respect,
in that he hath awakened us and brought us to a sense
of our depraved and deplorable condition,
and given unto a remnant to perceive, that there is a more excellent glory,
a more excellent enjoyment to be had, than any this world can afford.

But a great many of those whose eyes are so far opened,
that they can see and discern a more excellent glory, yet they cannot receive it,
for they are not in a capacity for the enjoyment of it; many have the glimmerings,
and some little light of heavenly things, but they themselves are earthly:
Many perceive there is a holy life, but it is not theirs, for their own life is unholy,
and yet they know there is a life that is holy and pure.
Hereupon desires are begotten, by the word of life in the sons and daughters of men,
through the Lord Jesus Christ, the Mediator;
by him desires are begotten in people that they might come to enjoy that life of holiness,
that they might not only see a better state than what they do enjoy,
but that they might come to enjoy it, and have it for theirs.

There is a universal desire in people that they might have eternal life,
and they believe there is an eternal life to be enjoyed; but everyone hath it not,
and the reason is, because they are not fitted and prepared for the enjoyment of it;
for it is a kind of treasure that is never put into an unclean vessel;
there must be a cleansing and purifying,
that so earthen vessels may come to retain and hold this heavenly treasure;
and when it comes to this, that people must be cleansed and purified,
here the world turns out to divers means and methods; some have gone to outward washings,
outward cleansings and observations of this and the other ordinance,
and when all that hath been done, themselves being judges, they were yet unclean;
when they have done all that lies in their power and ability,
towards their washing and cleansing, and towards preparing themselves,
they have found some secret testimony in their own
consciences that their hearts were still unclean,
and that there was defilement still abiding and lodging in the secret of their souls;
and this hath put a great many to a stand, what they should do;
when they have come to the end of all, they know not what to do:
Many have cried secretly, what shall we do to be saved?
For all that we can do, cannot save us.
We have retained this, and the other doctrine, followed this and the other way,
and made many observations; but all this doth not cleanse our soul,
nor purge our consciences from dead works,
this will not bring us to the inheritance of that immortal life that will give us satisfaction.
We hear many speak of satisfaction,
and of "`joy unspeakable and full of glory;`" but
here is a weight and burden still lies upon our souls.

Therefore, my friends, that all such who are brought so far,
as to be under such a burden and oppression, might be informed and come to understand,
where the true rest is, and where that power can be found,
that is able to answer those tender desires that are begotten in them;
for this cause hath the Lord our God communicated
and given the dispensation of the gospel of his son,
unto a remnant whom he hath sanctified,
that they might speak a word in season to the weary soul.
This is not a day to make a mock of sin,
this is not a day to make a covenant with death and hell,
and to resolve to go on in a wicked life, and to continue in it all their days.

But yet there are a sort of people that desire to have a
word spoke in season to them when they are weary.
How many are there in our age and generation, that one may reckon of this number,
that are sinners, and overcome by their lusts and corruptions,
and by the temptation of Satan and his instruments.
But they are weary of it, it is a burden to their souls,
it costs them many a bitter tear, many a sigh,
and many a sad and sorrowful thought in secret,
that they should have a sight of a more excellent glory,
and of a better life than that of their own, and yet know not how to get into it.

My friends, that same divine word of life, by which any of the people of the Lord,
in any age, were ever restored, redeemed and purchased again to the Lord;
that word of life must have been at work in their hearts, and hath been at work in them,
or else thou hadst never been so far opened;
there hath been something that hath unstopped thine ears, that thou mightest hear;
and the reason of thy continuance in thy bonds,
after thy knowing something that might have freed thee, is,
because thou hast not heartily closed with that which hath begun the work, which God,
by his redeeming power, hath effected in the hearts of them that believe in Christ,
and thereby an inclination is raised in people to seek after the Lord.

You know what the apostle saith, it is not of us so much as to think a good thought.
But this all people will grant is a good thought, when a sinner thinks of turning to God,
and leaving his evil ways, if he had power and ability, and cries out,
if I knew how to stand against temptation, I would never sin against the Lord more;
this must be a good thought in thy mind: How came it there?
Who is the author of this thought, you will say?
This ought to be attributed to the love of God in Christ,
that he hath convinced and persuaded us; and that though there is sin and pollution,
yet he hath not so forsaken us, as utterly to cast us off,
he hath sent forth his quickening Spirit, that is, the Lord from Heaven,
that he might stir up and quicken people to consider their condition,
and bring them to a sense of their present state,
that they may come into a better state than they are in at present.

If this may be granted, that the Spirit of God, and the grace of God,
is the author of these desires, then it will be granted at the same time,
that everyone of you ought to be sensible, that such spiritual desires stirring you,
are from the motion and operation of the Spirit of
God that hath raised them in your souls;
and then I hope you will grant, that if you had but joined with that Spirit,
and with the assistance of that Spirit, all things would have been possible thereunto.

So that here is the first thing that I would have
everyone satisfied about in their understandings,
whether they are totally exempted from any such touches and operations of God or no;
for it is said by some ignorantly,
that a great part of mankind have never had any such
divine workings of the Spirit of God upon them,
in order to their conversion;
therefore it is not in vain for you to consider your state and condition; for if you,
or I, or any here, be under such circumstances, that they never had,
nor are ever like to have any such divine operations or touches of the spirit of life,
in order to conversion, then I am sure you and I had better never have been born.

If you will consider with yourselves,
and lay aside the disputes of doctors and learned men,
you may know the things pertaining to yourselves.
Things relating to others, I may let disputes alone about them;
but as for things relating to my salvation, I must have a certain knowledge of them.
It concerns you, my friends, to know within yourselves,
by an infallible evidence of the Spirit of God, whether you have had such divine touches,
workings and operations upon your hearts, as have inclined you to seek the Lord.
I hope I may believe there are none here but have in their hearts an answer;
I have had such touches and operations in me: This is great love from God;
more than any tongue can set forth.
You will be ready to say, I have not deserved this;
I have not so behaved myself towards my Maker as to deserve that he should wait upon me,
and call upon me.
When wilt thou turn, and amend thy life, and hearken to him that made thee?
When wilt thou leave serving God`'s enemy, and serve him that is thy rightful Lord?

So that now this is a great aggravation of our sin to continue in it,
and yet to have a belief that God is still waiting upon us,
and that he hath such a kindness for us,
as now and then to touch our hearts by the inward operation of his spirit and grace,
in order to conversion.

Now when this is agreed, and men settle themselves in the belief of this,
you know what the consequence will be.
When I consider with myself, I that have been under these workings, have been rebellious,
wicked and disobedient to God, yet the Lord is not so angry as utterly to cast me off,
but is still waiting to be gracious, by the operation of his spirit,
to gather me to himself, in order to sanctify me, and heal my backsliding,
to cure my weakness and infirmities, and at the last to save me,
and make me an heir of his eternal kingdom, what is the consequence of this love?
Why, the next resolve must be this; I will either rebel against his grace,
and resist his power, or I will submit to him; which of these is the best way,
the safest way?

Are there not a great many in this age,
that are as sensible of the workings of God`'s grace for their conversion,
as ever you and I were;
that are as sensible that God hath called them to holiness and righteousness,
as any of us can be, and yet they have resisted the grace of God?
They have said in their hearts, we will not submit to this power,
that will make us so holy, and so watchful, and so careful, diligent and obedient,
for this very reason, because it will cross my interest, it will cross my pleasure,
it will hinder my preferment in the world, and my reputation among men;
and for this reason I will not bear this yoke.
I would be glad to hope there are none such here,
that have made such a covenant with death and hell,
and yielded themselves up to the devil, to serve him all their days.

Let us, who are at this time, and at this meeting, under the operation of God`'s grace,
and feel the Lord calling us by his grace, and working upon us by his spirit;
let us enter together into a holy, solemn resolution, that we will obey this good Spirit,
and take him for our leader, and submit, though it should be to a cross:
Thus people will think, they will come to this resolution,
when the work of redemption is begun in their souls,
and when they are convinced of their sin,
and their eyes are opened to see the way of holiness;
and though they never take a resolution to walk in it, yet everyone shall be convinced,
and see there was a better way than their own,
and be convinced by the grace of God one time or other,
that in respect of God`'s working of it, it is beginning;
but in respect of men that should join with the operation of God, it is not beginning,
for he hath no desire to those things which he doth not know,
he still depends upon himself; but when the soul comes to be satisfied,
that it is the visitation of God,
and joins himself to him in a holy resignation of his own will, and saith,
this is the Lord, he is come to work upon me,
he is come to change and alter the frame of my mind: It is the Lord,
let him do what he will; here is a mind brought to submit to the grace of God,
God is able to do that for him which he cannot do for himself.

When people come to the right object of their faith,
and act their faith upon that object, they every day find a progress,
a going forward in the work of grace, according to the work of grace in their souls;
and there is a power that inclines them to believe; it is not for such to cry,
if they had power, they would do more; he that hath the spirit of grace,
the Spirit of Christ, that had all power in Heaven and Earth given to him,
to put it forth on purpose for the bringing back of men and women home to God;
he that hath this object of faith before him,
he will not look for power in his own will and affections to redeem him,
he expects a power to be daily ministered and dispensed to him, as he hath need of it,
through the Lord Jesus Christ, who is present with him,
in all his trials and temptations: He cries,
here is a temptation that will carry me away, O Lord help me,
put forth the arm of thy power and save me, plant thy fear in my heart and deliver me,
their eyes shall see their Saviour, saith the prophet.

Thus when a man comes to be joined to the right object of faith,
and doth exercise and put forth lively acts of faith upon Christ,
his eyes shall see his Saviour; the light that shines into his heart,
discovers to him the temptation, and it also shews him a Redeemer at hand;
his Saviour is nigh him, and he trusteth in him, and relies upon him, and says,
this word of God is in my heart, and I do really believe,
that although the temptation that assaults me be strong, yet it shall not prevail;
whether it be the profits, the pleasures, or the honours of the world.
If I put my trust in this power, I cannot go near the evil; I am a Christian;
I have entered into a covenant in Christianity,
that I will join with nothing but what God approves of:
Now when I have represented to my mind the temptation of the devil,
and that evil which he sets before me, and I know it is contrary to the mind of God,
how can I go into that evil, and break my covenant with God,
after I have entered into covenant with him, to love him, serve him, and obey him?
The power of grace upon such souls, the operation of grace, is so powerful,
that the temptation comes and goes, and they are saved and delivered out of it,
because God helpeth them; but if they comply with the temptation, then tribulation,
wrath and anguish, pursues all such as are rebellious and disobedient to the will of God.

Now this redemption is carried on gradually from day to day;
the truth that thou believest, it operates by degrees; thou art delivered,
first from one evil practice, and then from another evil work:
But there is a great deal more; thou rejoicest and art glad,
that thou art delivered from one sin;
but thou wouldest be more glad to be delivered from them all.
I speak to those that are serious for their immortal souls;
when they see themselves delivered out of one evil, that they were ready to run into,
they would be glad if they were redeemed out of every evil;
that their crossness and peevishness, their frowardness and wantonness were removed:
They should be glad to be delivered from all their sins.

What do you think, say some, that a man, while he liveth here, may come to see all sin,
all evil and corruption brought under, and nothing but holiness,
righteousness and truth remain in him;
and that there shall be nothing but simplicity and innocence?
Do you think that such a thing can be?

Why should not I think so?
You will grant me,
that the power of grace is able to get such power and victory over sin and corruption,
that you may come to hate it as much as ever you have loved it; if you grant me that,
the consequence will follow, he that gave me victory over sin,
can give me power over all sin.
All Christians believe, that God`'s power is infinite; the scripture testifies,
all things to be possible to God, "`with whom we have to do.`"
If all things be possible to God, sure this is possible;
there is nothing so contrary to God as sin;
and God will not suffer the devil always to rule his masterpiece, man.
Mankind is God`'s masterpiece, the most eminent creature in this lower world,
made after God`'s likeness;
and though the devil hath brought men into his own likeness now,
yet nothing can be more contrary to the mind of God,
than that the devil should have the rule of us,
for God would have the government of us himself.

When we consider the infiniteness of God`'s power,
for destroying that which is contrary to him,
who can believe that the devil must ever stand and prevail?
I believe it is inconsistent and disagreeable with the true faith,
for people to be Christians, and yet to believe that Christ, the eternal Son of God,
to whom all power in Heaven and Earth is given,
will suffer sin and the devil to have dominion over them;
there is no other name under Heaven by which I can be saved,
therefore I have put my confidence in him: If the devil must have the rule of me here,
then I cannot be subject to Christ in all things; I may go to meetings,
but can never master the devil and his temptations;
this is as inconsistent with the faith of a Christian, as light with darkness,
and Christ with Belial.
If Christians think themselves true believers,
then let them see how far their faith will reach, whether it be like that faith,
which was once delivered to the saints, for by that faith their hearts were cleansed,
and they became free from sin, Rom. 6:22. "`But now being made free from sin,
and the servants of God,`" saith the apostle, "`you have your fruit unto holiness,
and the end everlasting life;`" you were servants to sin, but now you are free from sin;
so that this faith is but one, and if men have got another, it will do them no good:
Take heed thou art not mistaken about thy faith.

I have heard some learned men say, that a believer is a servant of sin,
and he is ever like to be so; but he is not at the same time free from righteousness,
for he hath the righteousness of Christ imputed to him,
and God looks upon him as righteous in his righteousness;
there cannot be a more anti-apostolical doctrine, I may be a servant of sin,
and yet have the imputation of Christ`'s righteousness; I may be a servant of sin,
say they, yet Christ is righteous, he is the righteousness of God,
and he hath fulfilled the will of God, and hath purchased salvation for me,
and he is the object by which I am made righteous.

Consider this, the imputation of Christ`'s righteousness will never do me good,
till I come to partake of his righteousness,
till his righteousness be made my righteousness, in me and for me.
Christ is made to us of God, wisdom, righteousness, sanctification and redemption;
so that if a sinner, one that was a sinner the other day, come, through faith in Christ,
to have his heart cleansed and purged, and true righteousness planted in him,
where sin was planted, there sin, through the blood of Christ,
is cleansed and purged away.

So that Christ is made righteousness to me,
and not his righteousness barely imputed and reckoned to me; Christ is my wisdom,
I am a fool without him; Christ is made righteousness to me;
for my good deeds and holy living cannot be acceptable to God till they be done in him,
and commended to God by him; the proper work of faith is,
to fix the soul on him that "`worketh all things in us and
for us,`" that "`worketh in us both to will and to do,
according to his good pleasure;`" and it is the good
pleasure of God that we should live in all righteousness.

They that come to receive this faith at first, have to receive it from an inward feeling;
they have the operation of the word of God in them; so the apostle reckons faith,
not because such a man heareth, and such a man believeth what such a man preacheth,
but faith is the operation of God; you may hear me, and a thousand preach,
and you may die unbelievers for all that, except you come to this,
to know the operation of God, and the work of faith in you.
How doth my heart close with this?
How doth my soul join with this?
What virtue and power do I feel in myself?
it may be others that preach, feel the power, but do I feel it?
if not, I come but to a noise and sound:
If people feel not their hearts joining with the word preached,
there comes no advantage to them; you read in scripture,
that the word preached did not profit,
because it was not mixed with faith in them that heard it: This is your case,
you come to meeting, and you love to hear the doctrine of truth preached; I tell you,
and I will speak plainly to you,
unless you come to feel the operation of the word of truth in your hearts,
you may hear the gospel, and the word of life preached to you,
but it will not profit you much.

How is it possible for a man to have a testimony against drunkenness, and yet be drunk?
a testimony against uncleanness, and yet be unclean?
How can a man hear such a testimony and believe it, and yet commit the sin?
He heard it, but did not feel the virtue of it within himself,
and so he did not mortify the sin that he was inclinable to;
but they that come to join with truth,
and with meekness receive "`the ingrafted word,`" they find the power and ability of it,
they find how able it is to save their souls, they find how it worketh,
not only just when they hear it, but it goes along with them, and dwells with them,
and they find the virtue of it overshadowing their souls,
with the dread and terror of the Lord, not with the words that a man speaks;
I do not trust to them, but here is the power and the fear of the Lord,
which will preserve my soul, and keep me in safety;
this is that which will keep my mind fixed upon him, and keep my mind inward,
that I do not gaze about me;
so that everyone may have an infallible testimony of what they have heard and known.

I have known the doctrine of several sects that have been among us,
and the main thing that many have gone from one people to another about, is this,
that they might know what such a man holds forth more than such a one,
and they think the truth is more perspicuous among such a people than other people;
if you examine the matter, it is this, who preached and proved his doctrine best.
Alas! if they did all concur together,
and did preach as certain and infallible doctrine as ever Christ and his apostles preached,
this will all do thee and me no good, unless we know the power.
You know there were thousands that heard Christ preach, as you now hear me,
and there were some so taken with him, that they went away, and said,
"`never man spake like this man.`"
But were they all Christians?
Did they partake of life by him?
No, some of them were ready to stone him.

Now bring this home and consider with yourselves,
whether you are not some of you in the same state; when you hear truth preached,
there is an assent and agreement with it in your minds;
but when a command comes to be obeyed, and a cross to be taken up,
and self-denial to be shewn, or some increase of trade lies in the way,
let truth go where it will, you must follow your interest;
there wants somewhat to fix you in the principle of truth,
which is able to sanctify you and perfect you,
that you may be reconciled to God through Christ.

They that are resigned and given up to truth,
it is possible for them that they may be satisfied;
they have an infallible testimony of the spirit of truth witnessing with their spirits,
that such a thing is bad, and if they might get the whole world to do it, they will not.
What is profit and pleasure to me?
My pleasure is at God`'s right hand, and my profit is to get grace,
and to have an abundant entrance into God`'s everlasting kingdom.
Those that have the true knowledge of Christ, they have profit and advantage,
pleasure and delight enough, which is hid from the world, and ever will be.
They are for profit and pleasure, which they may have with a good conscience.
Those things which God affords them as blessings in this world, they despise them not,
but take them with thanksgiving, and use them for his glory:
But if they cannot have profit or pleasure without
sinning against the Lord and their own consciences,
let those who will, take profit and pleasure.

They that come thus to close with truth, they have an infallible evidence within them;
they do not conceive it is thus and thus, because such a man saith it is so;
but they have an infallible evidence in themselves.
This is the mind of the Lord; God hath signified it by his Spirit,
and sealed it upon my spirit, and I cannot but know it.

What, do you profess infallibility?
Yes, else I would hold my tongue; if I did not know what I assert infallibly,
I would never preach more; truth may be many times concealed.
A man may have wronged and cheated his neighbour, and he not know of it;
this man goes away, and his neighbour doth not reproach him;
but when he comes to lie down in his bed,
he hath a sting and a reproach in his conscience, I know I have done him harm.
Is not this infallible?
Let me consult some learned men, that I may know whether I have told a lie.
I need not go to learned men and logicians, to know whether it was a lie;
I am infallible in this, I know certainly it was not a lie; I have a certain evidence,
and if a thousand men tell me to the contrary, I will not believe them.
If there be infallibility here, is there not then infallibility in the word of truth?
Shall I question it, or doubt it, if I have an infallible testimony of it?

Though men have ever so little proficiency, if they have it upon sure terms,
and lasting foundations,
let a thousand men come with all their logical skill and sophism,
yet they can never remove a man from the witness in himself.
The remnant that God hath brought to this foundation,
they have a certainty and infallibility in their obedience,
that they pay to the will of God,
and in the comfort they have to the obedience of the law of God,
which he hath written in their hearts.
Let what will come, they can never be removed;
for this exceeds all the precepts and doctrines of men;
it is the precept and doctrine of Christ and his apostles.
Let people read them, and endeavour to practise them: But here comes the testimony,
the divine power by which the precept was given forth to them,
and is now given forth again to thee and me, with the same liveliness and power.
Let us perform them as did the primitive Christians.

Here now, comfort comes to flow forth from a settled foundation that shall never be moved.
The winds have come and blown upon religion; let what wind will blow, that can blow,
God hath built his church upon a rock,
and it will remain unmovable against all opposition;
blessed are they that are founded thereupon.
Hath God fixed and established us in our society with one another,
and with our Lord Jesus Christ?
this is the foundation that God hath placed it upon.
We desire that all men may come to the same stability and settlement,
and never more to be tossed with the winds of doctrine, but be built upon Christ Jesus,
"`the Rock of Ages,`" the rock of our ages, the rock of us and our children.
That God will carry us on in this society, is the desire of our souls, for ourselves,
and all our friends and countrymen.
The way for you to be blessed, and to have an advantage for your immortal souls,
by the testimony that hath been raised up, is,
to have regard to the working of the same power,
that you may come to partake of the benefit of those gifts
and graces which God hath bestowed upon his church.

=== His Prayer After Sermon

Most blessed and glorious God and Father of Life! how wonderful
art thou in thy appearances to thy people in the day of thy power,
in which thou hast stretched forth thine arm,
and hast gathered a remnant of those that were scattered,
and art yet gathering and bringing to thyself, those that have been driven away;
and thou hast made known thy power and goodness in
the hearts of the sons and daughters of men,
that they might love thee.
That thou mightest beget love to thyself, thou hast made known thy love to their hearts;
if thou hadst not loved us first, we had never loved thee:
But thou hast been shedding abroad thy love in our hearts by the Holy Ghost,
to constrain us to love thee.
Thy love is manifested to all that are breathing after thee,
and none do breathe after thee, but through the life that thou givest them;
and those that were dead in sins and trespasses, hast thou quickened,
and we would send forth thy praises and thanksgivings for
the great things thou hast done for us in Jesus Christ.
All thy works praise thee, and thy saints bless thee.

Holy Father of Life! increase and multiply those graces
and holy desires which thou hast begun to work in us,
and pluck up every plant that thy right hand hath not planted.
Let spiritual Sodom be burnt up, and all that are corrupt;
let those things that thou hast planted spring up to the praise of thy name,
and the salvation of the souls which thou hast gathered.

O powerful God of Life! let thy blessed presence and living fear be among us,
that all thy children may offer praises,
and the sacrifices of humble thanksgivings upon thy holy altar.

Arise, O Lord! more and more in the greatness of thy power,
and dispel the clouds of darkness that hath been upon the sons and daughters of men,
and raise up in everyone of us more and more holy
desires and breathings after that life that is eternal.
Those that have been scattered, let them be now gathered,
and let those that have been driven away in a cloudy and dark night,
be brought to a glorious and blessed day,
wherein they may enjoy the gospel that brings light to dark souls,
that praises and thanksgivings way be offered up
in thy house for thy holy presence with us,
that we may be fed there, when we are assembled together in thy name,
according to thy promise.
Continue to be in the midst of us,
that living praises and thanksgivings may be offered up to thee, through Jesus Christ;
for thou alone art worthy, who art God over all, blessed forevermore.
Amen.

