== Sermon XX. The Word of God, a Christian`'s Life.

Preached at Grace-Church-Street, March 14, 1687.

It was the doctrine of the great master of the Christian religion, the Lord Jesus Christ,
while he was preaching and publishing,
and making known the way of salvation among the sons and daughters of men;
he then preached and declared, that it was not bread only by which a man lived,
but "`by every word that proceedeth out of the mouth of God.`"
Now the way and means of man`'s preservation in life, in a living state,
the method and course that the God of Heaven doth
open to keep the sons and daughters of men alive,
is by this word:
"`Every word that proceedeth out of the mouth of
God,`" hath a ministration of life in it;
and, therefore, all that are desirous of the enjoyment of the immortal life,
and of the preserving and increasing of it,
they are diligently to wait to be made partakers of this divine ministration.
Outward bread is for outward preservation, but man is made inward as well as outward,
he hath a soul as well as a body.
Now Christ, to signify to us, what the inward man is nourished and fed by, tells us,
that "`man liveth not by bread alone,
but by every word that proceedeth out of the mouth of God.`"

So now in this our day, as well as in former days,
it hath pleased God to give unto a remnant an experimental
knowledge of the truth of this;
that they have been quickened and made alive by the word of God; that is,
they have heard, and felt,
and tasted of the word of life that was with the Father before the world began,
that hath been divinely ministered to them, by the mercy of God, through Jesus Christ;
many that were dead in trespasses and sins, he hath said unto them, live.
He hath given unto many an inward sense of their state, who sometimes had it not;
he hath brought many a one to feel sin to be a burden and an oppressing load,
who sometimes before have taken pleasure and delight in it.
This is a great change that is wrought in a man`'s mind,
that he should come to be laden with that, burdened and oppressed by that,
which was before his pleasure and delight;
yet this great change hath been wrought in many a soul,
by the operation of the word of God, of that inward word, that inward voice,
when the Lord hath taken men in hand himself.

There are many have taken sinners in hand,
and have gone about to convince them and convert them, but they were not able to do it;
but when the Lord hath taken men in hand himself,
when his Creator hath undertaken to deal with him himself, then the man cries out,
"`I am a worm, and no man;`" then he cries out under the sense of the judgment of God,
then he cries out under the indignation of the Lord, which he hath kindled by his sins,
he cries out for mercy, then he prays for remission,
then he wishes that he had never provoked the Lord;
for the word that goes out of the mouth of God,
hath a mighty force and power upon the spirit of a man,
so that he is converted and changed by it; as the prophet said of old,
"`the word of God is pure, converting the soul.`"

Now where any come to an experimental knowledge of the word of the Lord,
of this inward voice, whereby God speaks to the sons and daughters of men,
they have received thereby an infallible feeling of their own state and condition;
this is the first lesson learned by it.
They come to have a certain, infallible knowledge of their own state,
and they are sure that they cannot be deceived;
for it brings an evidence with it in their consciences,
so that whatsoever this word of life signifieth to a man,
he hath the knowledge of the same thing evidencing it in his own conscience,
as the apostle saith, "`if our hearts condemn us, God is greater than our hearts,
and knoweth all things.`"
Now here is a way found out for men to obtain divine knowledge by a divine means;
for the Lord speaks by his Spirit, and if men come to hearken to that voice,
unto that speaking, they perceive readily what it saith unto them:
The Lord tells people as well now as in former ages, what he hath against them;
and this everyone in the closet of their own hearts, come to understand.
We read in the book of Revelations,
what our Lord Jesus Christ appointed John to write to the seven churches in Asia,
that he had few things against some, and many things against others.

Now that which is the design of our meeting when we are assembled together, is,
that we may know what the mind and judgment of God is, concerning ourselves:
How shall we know that, unless we ask him, and come to wait upon him,
and inquire at the oracle of counsel, that God hath appointed in the bosom of every man?
For he signifies his mind unto the children of men,
by that light and grace which Jesus Christ hath planted in them,
he hath enlightened every man that comes into the world, with an undeceiving light,
and he hath ministered of his truth and grace to every man;
though the man be bad and untrue, and in the dark, and there be darkness in him,
yet the light shineth in darkness.
The man may be a false man, yet there is true knowledge in him;
if this man hearken to the voice of truth,
when the God of truth signifies what his mind and judgment is concerning him,
and his present state.

So that there is an opportunity offered, and if a man believe the word of truth,
which is administered to his own mind, he cannot say such a man hath deceived him,
for it is truth itself which is signified to him which he believeth:
For the truth is the object of his faith, and he believeth it of himself;
he believeth that while he remains wicked in his unrenewed state,
he is out of the covenant of God, and in the high road to destruction,
if he doth not get out of it, and return to God, and mind his duty: He believeth this,
and he believeth the truth: It hath been so with many, it hath been so with us all;
this is the first kind of faith and belief that ever we receive;
for when truth signifieth to us our fallen state, our alienated state,
when truth signifies and discovers to us the partition
wall of sin and iniquity which we have builded up,
whereby the glory and favour of God was hid from the soul, we believed this to be true;
we would have been looked upon as heirs of God`'s kingdom,
yet when we are come to hearken to truth,
we find that we are children of the devil and do his works;
shall a man believe this after he hath been forty years a professor of Christianity?
If a man believe truth, there is no danger in believing it,
though it be his own destruction that is threatened.

Now the great thing that I would have ushered into the hearts of men, is,
that they may believe the truth for truth`'s sake.
If men will believe the truth, they must believe many things against themselves,
which they are not willing to believe; but saith Christ, no man can be my scholar,
my disciple, but by denying himself.
I must deny myself, my pretensions to Christianity,
my supposed saintship and title to the kingdom of God;
now if I would be convinced that I am a wicked man, a profane man,
one that doth not live as becomes the gospel, I must believe truth,
the voice of truth being of infallible certainty; it is signified divinely,
by the immortal word that cannot deceive us;
this ought to be the reason why people should believe the testimony of it,
though it be against themselves; they that do so,
presently come to find the effects of it,
for they were in their sins and trespasses before, and so are still;
they were before in a kind of liberty, in a kind of ease and indulgence of themselves,
and still their sin remains in them, and they remain in it;
but they are now under a sense of sorrow, under a weight, under a burden,
under an oppression, which signifies they are alive, and quickened;
for (if you take an outward comparison) they remain not senseless and dead;
now lay what load you will upon a dead man, he will neither groan, nor grumble at it;
but if becomes again to life, he cries take off the burden, the weight and oppression,
that lies heavy upon me.

This is the difference between being "`dead in sins and
trespasses,`" and being brought to life and sense again;
this word of life that comes from the mouth of God,
begets a sense in everyone that receiveth it;
it is of great service and use to all people to be acquainted with it,
that desire to be heirs of life eternal,
that desire to be inheritors of the kingdom of God: But how should they come by it?
They think by this and the other duty, and temporary performance, to obtain it; no,
but if they will have life, they must have it from the God of life that created them,
he must create them again to good works: They can have it but by one way,
all must be brought to it that way; it cannot be by hearing a man preach;
unless the spirit doth cooperate with the word of God,
there is no possibility of being quickened,
and necessity binds me to hearken and have regard to that one means: Now I say to you,
saith Christ, speaking of people`'s way of living to eternity,
"`man liveth not by bread alone,
but by every word that proceedeth out of the mouth
of God;`" now when we come to understand this text,
as spoken by our Lord Jesus Christ,
we did conclude there was a possibility of understanding and hearing
that inward voice and word of truth in our own hearts,
that God did speak to us by his Son, Jesus Christ, who enlightened us.
Hereupon meetings were appointed at first, that the word should minister life in them,
and life to them that attend them;
and to this day our meetings are appointed for this purpose,
that we may have the ministration of life and virtue, from Christ,
the fountain of life and virtue, by whom we were to be quickened and strengthened,
and by whom those that are "`dead in sins and trespasses`" were quickened.

Therefore I would have everyone always to have a reverence to the word of life,
that speaks in themselves; for, if we speak as we are moved by the Spirit of God,
and utter those things by verbal testimony, which God hath made known to us;
if you have not an oracle in your bosoms,
if you do not at the same time perceive an echo of truth in your own souls,
this will do you no good, but be an empty sound which will pass away again;
but the mind that is serious and settled, in waiting upon God with an earnest desire,
that it may receive benefit in going to this and the other meeting; such a one will say,
I pray God bless this opportunity to me, that so I may receive benefit to my soul.
Where people meet in this manner,
they have not only an administration of doctrine from without,
from this and the other instrument,
but they have a ministration of the word of God in themselves, by which a man liveth.

Let us not be led and hurried away with the grand error of the times,
the great error of this age, and of the ages bypast,
that there is no possibility for people to understand and hear this voice of God,
this inward voice.
There are, say they, no immediate teachings now-a-days, no inspirations now-a-days;
they might as well say, that there are no conversions now-a-days.
I will prove it from the holy scriptures, that there is no man in this age, +++[+++who]
is like to be converted to God, or redeemed from his iniquity,
and brought to the knowledge of his Maker,
unless he have it by the inward working of the eternal God:
Not by man`'s preaching and instruction,
nor by reading all the good sermons that ever were preached,
without the cooperation of the holy sanctifying Spirit,
which begets life in them that believe; and if these men say none can be converted,
then we must all go headlong to hell, even they and all.

These Quakers may say what they will, there is no immediate teaching now-a-days,
no man can know the mind of God, nor understand the scriptures;
none can open them to you.

But, blessed be God, this darkness is removed; this veil is gone over and taken away;
the brightness of the glory of the gospel hath expelled this darkness,
and thousands now-a-days do not only hear the minister reprove them,
but they hear a voice within that doth reprove them for iniquity;
and they find and feel a judgment and tribunal within themselves,
and that God hath an immediate way of counselling
and instructing them if they will hearken to him.

You that are under any sense of this,
that are come to such an inward sense of the operation of the word of God,
if you have heard it reprove you, exhort you, judge you and condemn you,
consider that this word proceeded out of the mouth of God,
and not out of the mouth of any man.
You hear the sentence of God upon you in your own consciences: Whence comes it?
This is out of the mouth of God.
Every word that comes out of the mouth of God, administers life, sense and conviction;
and you feel it and receive it, and you may have a more familiar acquaintance with it.
There is not a day or hour that passes over your heads nor mine,
but if we attend to this inward voice, we may know what it speaks to us, by its counsels,
doctrines, reproofs, convictions and illuminations; for the Spirit speaketh expressly,
with an express signification, unto the spirit of man;
and if he be under a temptation to tell a lie,
and he comes to a little pause or question, whether he shall tell it or no;
if he hearken to this inward word he will not pause long about it,
but such a sentence will arise in him, as that in Joseph,
"`how can I do this great wickedness, and sin against God?`"
How can I speak a lie, tell a lie, when in so doing I sin against God?
Here is a sentence of truth, wilt thou receive it or no?
No sayest thou, I will venture to tell a lie;
then shalt thou come into the rank of them that do despite to the Spirit of grace,
and trample underfoot the Son of God,
and count the blood of the covenant an unholy thing.
What sentence such shall have, at the latter end,
you may read at large in the holy scriptures.

Now there is a great necessity that everyone be persuaded to hearken to this voice,
not only at a meeting, but on all occasions they have in the world.
I hope I speak to many serious and religious persons
that are inquiring about their immortal souls,
what may be best for their souls, whether it is better to go on in wickedness,
or leave off; and that resolve and say, I would be glad to leave my sins as well as you,
if I had power, and to live a holy life.
As for the want of power, (that you have not power) I do not wonder at it;
for until you come to an exercise of faith,
in that which hath empowered the people of God, in all ages,
I wonder not that you have not power.
You say I am so weak, that I am overcome before I am aware;
the devil is so subtle and cunning with his temptations,
that I am surprised and snatched into temptations,
and overcome with evil before I am aware: He is like a roaring lion,
going about continually, seeking whom he may devour.
But whom can he devour?
Can he devour those that hearken and submit to the word of God?
If he could, then none could escape him; if the devil could pluck out of God`'s hands,
then nobody would go to Heaven, nor never shall, if he have power.

Where the devil finds any in their own hands,
as suppose a religious person of this and the other religion,
who never experienced anything of this power of God,
but trusteth to his duties and performances, this man is in his own hand;
now such a one the tempter hath power over: He can make him cheat his neighbour,
and lead him into drunkenness and uncleanness sometimes,
and into the greatest abominations;
but if a man come into the exercise of faith and dependence upon God,
and hath left trusting in himself and saith, I see I cannot preserve myself from sin,
I see a necessity of putting my trust in the Lord,
and of waiting upon God`'s power to keep me: If the tempter come to such a one,
he cannot prevail, all the devils in hell cannot stir him one jot;
the devil may tempt him, but he stands in the power of faith; he knows his name,
and saith, "`get thee behind me Satan;`" when the devil comes before him,
and lays a temptation before him, he casts it behind him;
if the devil rise up against him, he can chain him down,
he can say in the name of the Lord, "`get thee behind me Satan.`"

This is the reason why many are tempted, and not overtaken;
why many are tempted to sin and not overcome:
How comes it to pass that we do not do everything that we are tempted to?

There is something that keeps us; the devil is not so bad to tempt,
but we are as bad in our own inclinations to yield to him;
"`the heart is deceitful above all things, and desperately wicked; who can know it?`"
There is more wickedness in it, than can be uttered.
If people be tempted and not overcome, something must preserve them;
if there be something that preserves a man from any evil,
it can preserve him from all evil.

The reason why some people are led into temptation sometimes, and resist it,
is because sometimes the temptation suits not their inclination;
sometimes the reputation lies in the way, sometimes one thing, sometimes another:
But when a thing they are tempted to, suits their profit and pleasure,
then away with the fear of God, and nothing shall hinder them; I will have my pleasure.

But they that understand the keeper of Israel,
and come to know his power lying in their hearts,
these always bring their deeds and temper before him,
and they come to him for a verdict and judgment, and they ask,
doth this tend to the honour or dishonour of God?
Is it good or evil?
The oracle of God in thy heart says do it not, it is evil,
thou wilt kindle the indignation of the Lord against thee;
"`what will it profit thee to gain the whole world and lose thy own soul?
or what wilt thou give in exchange for thy soul?`"
Here is one at hand that can give counsel to all of us, at all times;
this is he that we must advance; our labour and work upon the stage of this world,
among the sons and daughters of men,
is to advance the virtue and great authority of the mighty Counsellor, Christ Jesus;
we do say and affirm, in the name of God,
that the same light by which God "`hath brought us
out of darkness into his marvellous light,
and from the power of the devil into the kingdom of his
dear Son;`" the same power is extended to you,
that you may he sanctified and saved from your sins.

One sect will say, my tenets are so and so, and our ordinances are so and so,
will you come over to us?
You shall be a member of our church.

Our duty is to come over to the grace of God that shines in our hearts;
now we are witnesses for God, that he doth not desire the death of them that die,
but rather that they would turn and live; for his word is gone forth,
and his light shines, and his glory is risen upon the nations,
that they that inhabit the earth may fear him.
"`Fear God, and give glory to his name,
for the hour of his judgment is come:`" Do you know that to be true?
That you may not be deluded,
you shall certainly know that the hour of God`'s judgment is come.

Thus when anyone suffers himself to be led away with the evil one,
when he feels after that a remorse upon his own heart,
he finds a secret judgment and tribunal set up in his own bosom, against whoredom, lying,
drunkenness, fraud and other sins, he knows be hath done amiss;
he is not going to a confessor,
that will take off and remove the guilt from his conscience;
he hath offended the majesty of the great God, and God hath signified it to him,
is not judgment come, and hath not God set it up in his own heart?
If through custom in sin thou losest the sense of his judgment,
it is not because God hath determined to take advantage against thee,
but because thou actest against thyself, and comest to be past feeling;
thou wast once under a sense of these things, and thou wast not past feeling;
if thou at any time told thy parents a lie, thou hadst remorse;
but now thou canst tell a lie, and not feel it, thou art past feeling;
whose fault is this?
The Lord would have brought thee to love the truth, but thou choosest lying;
if thou perish, "`thy blood will be upon thine own head,`" the Lord is clear from it.

They that receive the word of God have life.
"`For man liveth not by bread alone,
but by every word that proceedeth out of the mouth of God.`"
You are sensible of God`'s speaking this word to you:
I exhort you all in the love of God, that you would prize this manner of speaking,
and look upon it as the greatest mercy that ever you enjoyed,
that God hath not given over speaking to you,
and that conscience hath not given over speaking to you,
and that the Spirit of the Lord doth yet strive with you; he will not always strive;
you may be of that sort of fools before you die, that make a mock of sin,
and be as trees "`twice dead, and plucked up by the roots.`"
You that are sensible of this inward voice, prize it above all your mercies;
health and wealth, and all other mercies,
are not worthy to be compared to this voice of God speaking in you: They that prize this,
will never complain for want of power; they will find power in it;
all the power in Heaven and Earth is contained in this truth that shines unto you.
They that come to be exercised in this word, receive power from God,
for God gives it to them; he gives them power by degrees (from being sons of Belial,
sons of the devil) to become sons of God, even to as many as believe in his name.
They that receive this truth, grow tender of a lie, of a vain word;
they find themselves grow tender, feeling and sensible.
Here is a token that the God of life is quickening them;
I am now tender of speaking a lie to my neighbour; I will not do that thing to another,
that I would not have another do to me; when you come to a tender state,
which is far better than a hard-hearted state, you will have an evidence in yourselves,
that "`man liveth not by bread alone,
but by every word that proceeds out of the mouth of God.`"

Blessed are they that God hath brought into acquaintance with his word;
of all nations and people upon the earth, they are a blessed people;
though there are manifold blessings that reach indifferently to all, "`the sun shines,
and the rain falls on the evil and the good,
and on the just and unjust;`" yet this is a blessing that can only make the soul happy,
that an intercourse between it and its Maker is open;
that there is an open intercourse for the Lord to hear a man cry,
and he to receive his word;
all those that God hath brought into covenant with himself by Christ,
he hath made sensible of this intercourse and way of God`'s speaking to his people,
which he spake to them by in former days: Take heed that this way is not stopped up;
you know by what it was opened, and what will stop it up again;
when you were in much trouble and grief, you cried to the Lord, and he delivered you:
But "`if I regard iniquity in my heart,`" said David,
"`the Lord will not hear me:`" You cried to the Lord again, it may be,
and he did not answer you; and the Lord cried to you and you answered him not,
but hearkened to your lusts.

Yet the Lord by his long-suffering and patience hath won upon a remnant,
and hath brought them over to believe and trust in his power,
to remove out of the way that which hindered the intercourse between God and their souls.
What a great stir was there in removing out of the way the pride, corruption, enmity,
looseness, wantonness, and abundance more of evil things,
that made the soul like a wilderness?
What hacking and burning up was there?
God`'s word, like a hammer, and like a fire, did break up and burn up these things;
and the same word of God, like a sword,
did cut down those sins and lusts which prevailed over you before:
By this means God hath opened a way for you, to have access to him,
and for his word to have access to you: When you come to the Lord in this way,
you know you live by this word,
and if you hear the word of the Lord spoken immediately to you,
your joy and consolation increaseth,
and you have sweet communion and fellowship with God and Christ, and with one another,
by this covenant of life.
How came you into it?
It was by removing a great deal of rubbish out of the way.
If you should let this rubbish grow up again,
which kept you from the joy of the Holy Ghost, will it not do it again?
If your pride, corruption, enmity, prejudice, looseness and wantonness,
if these be suffered to grow up in any of you, they will do as they did before,
they will separate you from the Lord and from one another:
As the truth brought you to God and this heavenly fellowship with him,
so if a wrathful mind and wanton spirit get up again, it will separate you from God,
and scatter you from one another, then you will live in the outward life,
and die to the inward one and perish: Remember you were told so.

Every one that goes from this living word,
and suffers anything to arise of the old nature, so much as that riseth,
so much will your way of intercourse with God be stopped; sometimes men cry to God,
but they have a bar in their way; and they come for comfort to the throne of grace,
but they cannot receive those ministrations of joy and peace, which they desire;
their foolish hearts are darkened, and their minds blinded,
and they will go on in darkness,
and be left out of the holy covenant which God hath called his people to.

You that God hath engaged to be his, by the operation of his power,
O live in a holy fear and watchfulness; and know this,
that let your understandings and gifts be what they will,
you have nothing but what is given you; and what God hath given you, he can take away.
Thou hast decked thyself with my flax, and my wool, and with my silver and gold,
and other ornaments, and followed thy lovers, therefore will I take them away from thee,
and strip thee of all thou gloriest in.
Those that forget God, of whom they had these things,
that forget their brokenness of heart, and the subjection of their spirits to God;
if they forget this, let them know, that let their parts be what they will,
they will certainly wither, and their inward life will fail:
You that have regard to your own souls, and do desire heartily, at this time,
to be quickened, and find that the Lord hath removed your deadness,
and quickened and raised you to such a degree and measure of life, that you can say,
I find communion with God,
and fellowship with my friends and brethren in that one eternal life,
I pray God you may continue in it long, and lay down your heads in this blessed,
heavenly life.
Now that you may so do, keep yourselves low and humble, and in the fear of God,
and keep your ears always open to his word,
and live as becomes those that are born again and begotten of God,
and are brought to partake of the divine life.
Let temptations surround you, that life will preserve you;
he that never sinned is with you, to keep you from sin; and he that never deceived any,
will keep you from being deceived.
To his counsel and conduct, and to his divine care and protection, I now commit you.
