[short="Sermon XXI. The Necessity of a Holy Life and Conversation."]
== Sermon XXI. The Necessity of a Holy Life and Conversation.

Preached at St. Martin`'s-Le-Grand, March 26, 1687.

O how happy are they that have bread in their own houses!
and that can draw water out of their own wells!
These have a blessed, glorious dwelling place;
these are the children that their father provides for:
All the divine treasures and the riches of heavenly things are laid up for these;
O that all that have a sight of this blessed state,
were got into it! that their minds might not more wander;
that people might not be scattered in their thoughts, that when they meet together,
they might have their expectations entirely from that God whom they profess to worship.
Lord, thou hast said that thou wilt teach thy people thyself;
here a cry goes up to the Lord, and their expectations through faith pitched upon God;
they never meet in vain, but a well springs up, and the water of life comes to them,
by which they meet with divine refreshments;
for you know the promise that our Lord made to his disciples,
"`he that drinketh of the water that I shall give him, shall never thirst more.`"
Why, will once drinking serve,
because I have tasted of the living water that the Lord Christ gives me; will that serve?
No, but he giveth me a substantial river, that is the reason why I shall thirst no more;
it shall be in me "`a well of living water,
springing up to everlasting life;`" blessed are the witnesses of it;
these are they that are satisfied concerning religion and doctrine;
they are satisfied concerning worship; they are looking after no new things;
when they meet together, they meet in the name of the Lord,
and they have their eyes to him, who is a fountain,
and they discern a brightness and a glory that is unspeakable;
and the glory that is speakable, that appears many times through instruments,
will not satisfy them; there is something beyond that, which must satisfy;
this will never do it; such as these will never be satisfied with hearing and seeing,
till they come to hear and see that which is unutterable, and then they are satisfied:
Christ had preached many sermons in the hearing of his disciples,
and there were a great many said, that there was never any spake like him,
or preached like him; yet one of them that was the nearest to him,
and most acquainted and intimate with him,
after some years meeting and hearing of his sermons, he cries out, "`shew us the Father,
and it sufficeth us.`"

My friends, this comes near to many of your states; many of you have heard long,
and have heard the speakable word of God, that which could be uttered,
that which could be spoken forth, by the demonstration of the Holy Ghost,
by them that have received it of the Father; this you have heard long,
and yet there are many of you, that if you come to a serious search,
you will find a want;
you will still find that you have not that satisfaction that puts you beyond doubt,
beyond fear; there is something that stands in the way,
that hinders your enjoyment of the unspeakable glory of the unspeakable word,
and this will never be removed,
but by your innocent submitting to the work of the power of God in your own hearts,
that so you may not only be believers, but come to be really baptized,
and then all is out of doubt; for our Lord said, he that believeth, and is baptized,
shall be saved; he doth not say he may be saved; but, he shall be saved.

Woeful experience hath told us in our days, that a great many have believed the truth,
and yet they are never like to be saved, they have made shipwreck of their faith;
but if they had been baptized, if they would have endured the baptism,
if they would have been buried with Christ in baptism, they should have been saved,
everyone of them; and now there are a great many that remain in the belief of the truth,
and yet they are not baptized, they are not dead, not buried,
notwithstanding they have received like precious faith with us,
that faith which is of the operation of God,
and that is like precious in its nature to all that do receive it,
and would work the same effect in all too, if it were not obstructed;
but notwithstanding they have received faith towards the saving of their souls,
yet their souls are captives, their souls are subject to lusts, and pleasures,
and vanities, and unto empty and foolish things, and to passions and corruptions,
after they have received faith.

For if you take one that is a believer of truth, that is overtaken with his lust,
and passions, and corruptions, he will commonly own that he believeth the contrary,
he believeth that these things should not be, that it ought to be otherwise:
This is the signification of truth against untruth; if it should be otherwise,
why is it thus then?
Why, he finds a life to spring up in that which is corruptible,
that is always contrary to the life of God, and at enmity with it: What shall I do?
I believe the truth, I know it is an holy thing,
it leads all that submit to it to a holy life, and there is this and that unholy thing,
this and that corrupt thing remains, what shall I do?

It is an evident demonstration that thou wantest the baptism of him in whom thou believest;
thou hast believed in Christ Jesus that cometh after John, and was before him;
and now having believed in him, thou wantest to be baptized by him, and for want of that,
the pollution and corruption that was in thy nature in the time of thy alienation,
prevails still upon thee, contrary to thy faith;
and there is no coming to obtain this baptism,
but by sinking down into that which will slay thee, that which will kill thee:
But there is such a shifting to save ones life,
there are so many twistings and twinings of people to save their lives,
that at last they lose them;
but there are none that could ever find that life that is eternal,
but those that are willing to be given up to the dead, and submit to this baptism,
that is, by the Holy Ghost and by fire: These only do come to life,
they come to the resurrection,
for you never knew any that died this death but they rose again;
it is as impossible for death to hold anyone down that is buried in this baptism,
as it was impossible to hold Christ down, when he was in the grave;
the same power that brought again our Lord Christ from the dead,
the same power it is that quickens us, while we remain in these mortal bodies,
after we have sustained this death and crucifixion.

But who can believe this saying?
For "`this is a hard saying, who can bear it?`"
Is it not enough that I am a believer, which makes me a Friend,
and entitles me to a community among you; and as long as I hold the truth,
and profess the truth, I am looked upon as one of your society?
This is very true;
this doth entitle people unto the outward privileges of the Church of Christ;
but there is another inner court,
that lies under the angel`'s reed (the measuring-reed) that is to be measured;
the temple is measured, and every worshipper in the temple is measured;
there was an outward court, that was for representing the Church of God in general,
from the particular; the outward court was not measured, that the Gentiles might come in;
the unbaptized people, which were never regenerated,
they might come so far as the outward court,
but this did not entitle them to the privileges of the house of God,
nor to any worship or sacrifice that was accepted upon God`'s altar.

It concerns you and me, my friends,
to be serious about matters of this moment and importance, and not spend our days, and,
as it were, speak by rote, under an airy profession, though of truth itself,
without considering what progress you have made, what benefit you have obtained,
and whether you are come not only to the shadow of good things to come,
but to the very substance of the heavenly things;
for the comers to the outward worship could never, with those sacrifices they offered,
be made perfect; the comers thereunto were not made perfect,
as to the things pertaining to the conscience, speaking there of the outward worship,
Heb. 10:1; but coming to the heavenly things, whereof the other was but a shadow,
they made people perfect, as to the conscience, and did bring them to salvation.
The apostle alludes to this baptism,
for he speaks in a figure of the eight persons that were saved in Noah`'s ark;
then he brings down the allegory to christian baptism, not only the baptism of John,
the fore-runner of Christ, that preached of Christ, but to the christian baptism itself;
by the like figure whereof baptism now saveth us, saith the apostle;
"`not the putting away of the filth of the flesh, but the answer of a good conscience.`"
What doth he mean by baptism saving us?
He means,
"`the answer of a good conscience towards God,`"
through the resurrection of Christ from the dead;
so that christian baptism did bring along with it the cleansing
and putting away of all sin out of the conscience,
that might bring them under doubts and scruples; and then there is an arising of Jesus;
the Saviour, in the conscience,
the Mediator that brought them to answer for them in the sight of God;
for if people be conscious of sin, and do leave off their sin,
this doth not yet cleanse the conscience; for there still remains a conscience of sin;
tis not the leaving off our sin that makes our atonement with God,
or that expiates our guilt, or doth away the guilt of the sins that we have committed;
but there must be a forsaking and a leaving off sin by the virtue and power of the spirit,
by which we are enabled, not only to leave off sin,
but are guided and directed to the Mediator, whose blood alone reconcileth us to God,
and cleanseth us from all sin.
If I should never commit a sin while I live,
it is not this simply in itself that will make me have the
answer of a good conscience in the sight of God;
for there remains the guilt of sin contracted in the days of unbelief,
which is a bar and hinderance, that none can approach the Holy God,
but in the atonement and salvation that comes by Jesus Christ;
for all that believe and obey the gospel are accepted in Christ,
and that upon the account of Christ`'s precious blood,
that cleanseth us from all sin and unrighteousness.
Whom doth it cleanse?
Those only that forsake their sins, and by his power are brought to a holy life; they,
by the virtue of his power, and the cleansing of his blood,
come to have their former sins removed from them, as far as the east is from the west.

But what is this to them that remain in their sins?
what is this to them that are not baptized for the dead?
that have not put off the old man, nor put on the new man,
but have only put on the name and profession of Christ, and put on the outside of him,
his garment, but have not put him on,
they are not created again in Christ Jesus unto good works, that they might walk in them?
No wonder there remains a conscience of sin in them,
there is a bar that hinders them from the sight of the glory of God,
and from real and true satisfaction,
concerning their atonement and reconciliation with God,
and this hinders them from the enjoyment of that "`peace
that passeth understanding;`" and it is no wonder,
because they are not come to this baptism that brings
the answer of a good conscience in the sight of God;
they are not risen with Christ; how should they?
for they are not buried with him.
"`Know ye not that so many of us (saith the apostle) as were baptized into Christ,
were baptized into his death; therefore we are buried with him by baptism into death;
that like as Christ was raised from the dead by the glory of the Father,
even so we also should walk in newness of life,`" Rom. 6:3. Here is
a change figured out between them that had partaken of the spiritual baptism,
and were come again to the participation of life in the resurrection of Jesus Christ,
and those that were not baptized.

So it is now with everyone that cometh to believe the truth, and make a profession of it;
there is a way cast up, and there is a door opened for salvation;
but the grand question that everyone ought to inquire about, and put to themselves, is,
what progress they have made in this way?
Whether they are baptized yet or no?
whether they have put off the old man with his deeds,
and put on the new man and the new man`'s deeds, which are righteousness and holiness?
They that find, that though they are believers, they are short of this,
they do also find that their shortness is their hinderance,
their shortness in not coming up to the pattern that hath been shewed them,
is their hinderance, so that they enjoy not the things here spoken of;
the being under this sense, and really sitting under this sense in a meeting,
though there should be no man speaking to them outwardly, yet being come to this faith,
and made partakers of this baptism,
people would find in their own bosoms the hidden word of life ministering to their condition;
they would have enough, there would not be a famine of the word unto them,
nor they should not need to be in expectation of going out to this or the other instrument,
but they would be satisfied when they are met together with the presence of the Lord,
that the Lord is in the midst of them, ministering unto them the word of life,
in his operating and working, speaking in a tongue that everyone can understand,
speaking with a kind of voice and language,
that everyone may understand his own state and condition;
and this is the way that God brought up people from the beginning,
to the knowledge of heavenly things, and opening of the mysteries of salvation;
we had it not of men, but of Jesus our Lord; he was our great minister,
we waited upon him, and trusted in him, and he taught us himself;
he hath ministered to us at our silent and quiet waiting upon him,
those things that were convenient for us; we might well say,
he gave us our food in due season; he hath not only given strong meat unto men,
but hath ministered of the sincere milk of his word unto babes,
that lived in sincerity and self-denial, loving God above all things;
and he taught and conducted us in our way, this way of simplicity,
until our understandings came to be opened,
until our souls came to be prepared to receive the mysteries of his kingdom.

In those days there were some that started up in knowledge,
and that built their nests on high, and took flax and wool, and gold and silver,
and decked themselves with them; but the Lord found them out, and brought them down,
and took the crown from their head, and clothed them with dishonour.
So God doth from age to age; his judgments will begin at his own house:
If you would "`grow in the grace and in the knowledge of our Lord
and Saviour Jesus Christ,`" then grow in humility and self-denial,
and keep a constant watch upon your hearts; examine your hearts,
and "`commune with yourselves upon your beds,
and be still;`" take heed lest you sin against the Lord, and provoke him.
There were some that provoked the Lord of old, and they committed two great evils:
What be they?
They have gone away, and forsaken the fountain of living water; as much as to say,
they have not their dependence upon an invisible power, as they ought to have:
For I am a living fountain, and it is by an invisible power that I am able to counsel,
teach, direct, purify, and open their understandings; but they have forsaken me,
that is one great evil; and the other is, they would not be without somewhat;
they have forsaken the Lord, and they would have somewhat instead of God;
they have digged to themselves "`broken cisterns, that will hold no water.`"
And how many in this age have committed these two great evils!

My friends, examine yourselves;
are there not many that have been guilty of these two great evils?
They do not keep their close dependence, trust and reliance,
upon the invisible power of God, as they profess they ought to do,
but are hurried away from it; some by the love of the world, some by lusts and pleasures,
some by passions, and others by worldly interests, are drawn away from the power,
to do and say that which the power is against:
Is not this a forsaking of the Lord the living fountain?
What do they do then?
Are they not for this and that, and the other man?
for hearing this and the other man`'s word, and digging to themselves broken cisterns?
And have they not their trust and confidence in going to meetings,
in commending this and the other way?
Have they not their trust in their profession outwardly,
when it ministers nothing to their souls, so that they secretly wither for all this?
If you had all the men and angels that were ever sent of God, appointed to preach to you,
they could not minister life to you,
unless there be that faith that stands in the power of God.
The faith that stands in any man`'s words, will not overcome your lusts;
but the faith that stands in the power of God, purifies the heart;
it will not suffer any unclean thing there.
As for preaching, let a man preach against this and the other lust and corruption,
there it will remain for all his preaching, unless men know God`'s power and life,
in which there is righteousness; for words and knowledge, and sight and speculation,
will never give people victory over their sins.

Therefore you know,
everyone who is settled must be settled where the foundation of religion is;
it is not coming to meetings,
and owning this and the other doctrine which is the foundation of our religion;
God hath revealed his power to everyone of us;
God hath not given his Spirit to preachers and prophets only,
for then there would be a famine of the word, as was in Israel,
the priest`'s lips only preserved knowledge.
If you did take away the priest, you did take away their knowledge.
The prophets had the word of God, and they only spake the word of God.
If the prophet was taken away, then the word of God was taken away.
The Lord threatened to send a famine among them; they grieved and vexed,
and killed and destroyed, the priests and prophets; therefore, saith the Lord,
I will send a famine among you, not of bread, but of the word;
and they shall go from city to city, and inquire for the word of the Lord.

Thus it was in the Jewish church; if there was a prophet they would go thirty, forty,
or a hundred miles to him that had the word of the Lord; they shall go from city to city,
to inquire for the word of the Lord: But blessed be God we are come to another day,
for now the word of the Lord is manifested in the hearts of all that believe;
they know the word: I do not say all that believe do preach the word, or ought to preach;
but the word preacheth to them;
they are not as "`broken cisterns that can hold no
water;`" when they find the word and hear it,
they speak it presently; what is ministered to their own condition,
that they tell to other folks;
when people come to the blessing of this dispensation
that God`'s word revealeth in their hearts,
they then know what the signification of it is, they understand the doctrine of it,
the doctrine preacheth holiness to them;
not that they should preach holiness and yet remain unholy;
not that they should preach humility, and yet remain proud: it preacheth holiness,
humility and singleness of heart to a remnant,
that like good scholars and disciples learn the lessons and doctrine of the word of God.

Now when thou hast learned them well, and art come to see the effect of the word,
and dost bring forth the deeds and works which are the fruits of holiness,
"`perfecting holiness in the fear of God,`" and with
humility known and witnessed in Christ Jesus,
and art not only meek in show, but meek and low in heart;
when people come to be meek and lowly, and of a clear conscience,
purged from all dead works to serve the living God;
then if the Lord gives them a word of exhortation, of doctrine or counsel,
it is very welcome, and it hath a savour through the blessing of God,
and they come by it to be built up in their most holy faith,
and this word is brought forth in holiness and righteousness in their lives,
and shews itself in a life of holiness;
then thou wilt shine in thy conversation to all that thou conversest with,
so that they may see thee to be such a man or woman as hast been with Jesus,
and learned of Jesus, and received a word engrafted;
when thou dost receive the word into thy heart, there is the engrafting of it:
If it hath not root there, then, saith Christ, my word doth not abide in you.
If you feel something of this invisible word in your hearts,
it brings you to a resolution to serve God, and to keep yourselves from sin,
and to answer the profession which you make of God;
this is the effect of the word of God, if it doth abide in you.
Doth it abide?
You shall know anon or tomorrow,
so soon as a temptation comes to stir you up to pride or passion, to fraud or deceit,
then you will see whether the word abide: If it abide, you sin not.

This is scripture, a certain fundamental doctrine,
that may be as safely preached as any doctrine: If the word abide in you, you sin not;
what of that?
let the word go, and you will sin, whenever you are tempted to it.
"`I write to you young men, because you have overcome the wicked one, you are strong,
and the word of God abides in you, and you have overcome the wicked one.`"
We shall see as soon as a temptation meets with thee, whether the word abides in thee;
if it abide, thou wilt not sin, but resist the tempter.
Set thy foot upon the temptation, and go over it, and thou wilt have the dominion;
and this will make thee a free man or woman,
and thou wilt "`stand fast in the liberty wherewith Christ hath made thee free.`"
The apostle supposeth them free, and that they have got dominion;
then "`stand fast,`" saith he, "`in the liberty wherewith Christ hath made thee free.`"
It is a liberty not of lust and sin, but a liberty of the soul;
the soul now is not at the devil`'s will and call.

For it is a shame to the doctrine of Christianity, that we profess things,
and yet deny them in practice:
We profess that there is a power in Christ to keep and preserve us out of sin,
and we profess to believe this power is communicated to them that
do believe in the Lord Jesus Christ for their preservation;
that is, he will not withhold it from them:
We profess these things in the face of the whole world;
and yet when the devil calls one man to covetousness,
and another to defraud his neighbour, and another to defile himself,
he is drawn away thereby; what hypocrisy is here to profess this, and act the contrary?
I do not wonder that they that profess they cannot live a day without sin,
that they should fall; but they that profess to believe there is power enough in Christ,
and that it is offered to them, to live in sin and yield to temptation,
this is horrid wickedness.
They that are of an upright, single mind, would die before they would sin,
knowing that God is Almighty, and gracious, and willing to bestow his power, and wisdom,
and grace, upon them that ask it;
they would die rather than sin against God presumptuously: let it cost me my goods,
my estate, my liberty, or my life, "`how can I do this great wickedness,
and sin against God?`"
They love God above all; you never heard them complain that they wanted power,
for the Lord is at their right hand, and they shall not be moved.
They cannot fall; though they are tempted, they will not fall into temptation.
They have power when they see the devil before them, to put him behind them;
the nobility of their extract, of their new birth and regeneration,
puts such a temper and disposition into their souls,
that they scorn to be at the devil`'s command, as if they were his children.

Oh! it is a noble and honourable thing to be a child of God,
a very high dignity to be in such an honourable relation to God,
and to have a right to the heavenly mansions,
to sit down in heavenly places in Christ Jesus.
I would to God you were all ready for it, that you had the wedding garment on,
that you might not be bound hand and foot, and cast into utter darkness.
What is the reason that you do not sit down in this heavenly frame and temper,
and draw the waters of salvation out of your own souls;
could the Lord do anything more than he hath done,
and could his servants do any more than they have done for your help?
Are not their labours demonstrations of it?
We have been as epistles of Christ written in your consciences.
We have been testifying that there is something wanting in too many,
the want of resigning up themselves to the baptism of the cross.
People are willing to be counted friends; but they are friends of God,
that do whatsoever he commandeth them; that is the Christian lesson, not to say,
I will be a friend to you, and a friend to the church, and to such a sort of people;
but I will be a friend of God, and do whatsoever he commandeth me;
whatsoever command God lays upon you, either to take up a cross,
or to deny yourselves and follow him.

Learn this lesson, and you will be disciples indeed, and members of the church too;
not members of a church privileged outwardly only,
but members of a church of the first born,
and you will have your names written in Heaven;
when one comes to have his name written in Heaven, he comes to know his name,
it is a white Stone, not a speckled one; they that have it, they know it,
they are not ignorant of one another`'s names, that are written in this book;
they have a fellowship that nobody can declare;
their communion is in that bread and that cup: This is a cup of blessing indeed,
and this hath blessed us, and will bless us.
God will preserve a people in this fellowship.
You that are at a distance now, you must come nearer to him;
God will choose a people by whom his name shall be magnified;
because the love of God is shed abroad in our hearts, we cannot but desire this for all,
especially for the household of faith; we cannot but desire their perfection,
their growing up in the grace of God, that they might come to be partakers of Heaven.
And in the next place, our love is to all people, everywhere;
we would be glad that all were saved; they that despise us,
when we are speaking of heavenly things, speaking like a child, like a stammering child,
speaking of the glorious excellencies of God, of the lovingkindness of God,
speaking of those things which God hath spoken to our souls,
they that despise these things, we would be glad that they might be saved:
If they were partakers of these things, they would be glad as well as we,
and they would be more really happy in respect of this world,
for the time that they are to live here; they would live a happier life,
even in this world, and they would have everlasting life in the world to come.

The love of Christ constrains men thus to judge,
that everyone that hath received like precious faith,
ought to answer that grace and faith which God hath
ministered to them in a holy life and conversation,
and everyone who is a stranger to this thing, ought to be of an inquiring mind,
and an open heart, to wait for the day when God will visit them with the same grace;
when you give up yourselves to a daily cross, as Christ`'s disciples,
you will not be running after anyone to teach you to know the Lord,
for you will all know the Lord, from the least to the greatest;
I that have been but a little convinced, shall I know the Lord?
Thou shalt know the Lord, thou that art dead in thy sins and trespasses,
thou that hast not known the blood of cleansing,
thou shalt know the Lord to be thy judge, and thy law-giver,
to teach thee how thou must live, walk and act; and is not that a good knowledge?
This is the way they reckoned upon in old time, it is a notable expression,
"`the Lord is our judge;`" there is the beginning, he began there,
judgment began at the house of God; those he brings into his house,
he brings them under the discipline of his house, the Lord is our judge,
he is our king and law-giver, and he will save us;
this same exercise of discipline under judgment brought
to them the faith and experience of his being their law-giver,
and this brought them to a faith of the last sentence, we shall be saved;
and the Lord answers such a people, that he will bring salvation to them,
salvation shall be for walls and bulwarks:
Did the people of this nation but know salvation was brought near to them,
and that it was their bulwark,
there would not be a crying up this and the other rotten thing for a bulwark.

We talk of a bulwark as well as others; we have a bulwark, blessed be the God of Heaven,
made of better stuff than theirs;
for it is the salvation of God which hath kept us from the pollution of sin,
and from a running into all excess and riot that others have run into;
it hath kept us from the evil, it hath kept evils out of us,
and we have found that certainly true, that "`all things work together for good,
to them that love God,`" and fear God; that all the providences of God together,
have all wrought for our good; and this is the bulwark that we have trusted in,
and it hath served hitherto,
and it will serve us and our posterity to the end of the world:
This is a bulwark that will never be stormed,
that will never be thrown down nor laid waste: Though all the powers on earth,
and all the potentates in this world should agree together,
they shall not prevail against it; we have salvation for walls and bulwarks;
if I be within these walls, salvation is round about me;
if I am got into this eternal bulwark, I am safe from the devil and his instruments;
here is a bulwark to be relied upon.

Many wonder we differ with them in some opinions;
we have that confidence in this bulwark, that we desire not another;
God will last and abide forever, so will this bulwark; all the care that I take,
and all the care that you should take, is to keep within these walls: Do not sally out,
if you go out, the devil is watching,
and "`seeking continually whom he may devour;`" he will catch stragglers;
if people will go out for profit, or for pleasure, or interest,
the devil will catch them; how can such people talk of salvation for walls and bulwarks?
the devil hath got them in his snare, and they are caught in drunkenness,
uncleanness and other sins; the reason is, they have gone out of their bulwark,
they have sallied out of their walls, for the devil could never have forced them out.

"`O take heed,`" says the apostle,
"`lest there spring up in any of you an evil heart of unbelief,
in departing from the living God;`" as if he had said, you are Christians now,
you are a people come to a good state in Christ;
but consider you have no strength to stand but in him;
no power to keep yourselves but in him; "`take heed,`" at all times,
"`that there spring not up in you an evil heart of unbelief,
in departing from the living God;`" take heed lest
there spring up in you such a thought as this;
I may take this pleasure, and the other profit;
consider that thou diest and witherest if thou depart from the living God;
take heed of taking liberty above the fear of God:
It is not our talk of salvation for walls and bulwarks, that will do us good,
but our keeping within these walls.

I remember a notable saying of the apostle, which hath a great emphasis in it,
and a great deal of doctrine; he writeth to the church,
after they were become a people of professing Christians,
take heed lest you come to be beguiled by the serpent, as he beguiled Eve;
he did not speak of Jezebel, a wicked woman; but he spoke of Eve, a good woman,
created after the image of God, in righteousness and holiness;
they were come to a life of sanctification,
to a life that was hidden from ages and generations.
You must look to yourselves, and look upon yourselves as in the state of your mother Eve,
a woman brought forth in righteousness and holiness,
that might have stood in that primitive state,
notwithstanding all the subtlety of all the serpents in the world;
but having hearkened to this old serpent, she was beguiled;
there grew up a consultation in her reasoning part; it may be so as he saith, I will try.

So I say to you that are come to a state of sanctification,
and in some measure to know the cleansing power of God,
that you have not believed in it in vain,
but it hath effectually wrought some change and alteration in you,
and is still carrying on the work of your salvation.
Many temptations will attend you, and many snares will be laid in your way;
but God hath preserved you to this day:
I know the devil`'s wiles and temptations are manifold;
they are fitted to everyone`'s inclinations, fitted to every opportunity,
and to every occasion in this world: Men are tried every way by the tempter,
to see which way he may ensnare them;
he tries every way to ensnare and entangle the simple,
that he may turn them to the right hand or to the left,
that their souls may be destroyed and perish.

I cannot speak to you by a more emphatical word,
by a more familiar exhortation than this, take heed you be not beguiled as Eve was:
Many will be tempted as she was, but I would not have you do as she did,
and yield to the temptation: Take heed that you do not defile yourselves,
but keep your garments white; you that have been washed and cleansed,
labour to keep yourselves unspotted from the world; this is pure religion and undefiled,
that which hath enlightened many a nation,
and shall enlighten many of those whose religion is to be undefiled,
and to keep themselves unspotted from the world.
I pray God increase the number of them,
that so the blessed work of sanctification that hath begun in this way,
may be carried on to his praise, and the salvation of our souls,
to the spreading forth of his glory, and the exalting of his name;
that the strangers which are scattered and desolate, may be brought into his holy way,
and walk in it; that we all, in a fellowship together, walking in that holy way,
may through the eternal Spirit, offer praise and thanksgiving to God,
who is worthy to receive glory and honour, power and dominion, forever and ever.
Amen.
