[short="Baptism and the Lord`'s Supper Asserted."]
== Sermon XXII. Baptism and the Lord`'s Supper Asserted.

[.signed-section-context-open]
Preached at Grace-Church-Street, April 15, 1688.

[.offset]
"`If any man hath not the Spirit of Christ, he is none of His.`"

If I should say no more,
there is that in everyone`'s conscience that will make application;
if he that hath not the Spirit of Christ, is none of his, you may say, whose is he then?
If they be none of Christ`'s that have not his Spirit, whose are they?
They are all his whose Spirit rules them,
everyone of us doth belong to him whose Spirit ruleth over us,
unto whose power we are subjected.
You know this distinguisheth people in the world,
one king knoweth his subjects from another king`'s subjects;
they are under the obedience of this, that, and the other king or prince,
his law is over them, they are subject to it;
so here is a decision of all the people in the world, whom they belong to.

We, all of us, I hope, do expect there will be a decision at the day of judgment,
and believe the things we read concerning it, that there will be a decision,
and some will be placed on the right hand, and some on the left;
some will have the sentence of, "`come ye blessed,`" and others the sentence of,
"`go ye cursed;`" but now there is a way of finding out
the decision of the matter before we go out of the world,
before the day of judgment, when there will be no remedy, what then is,
must be and abide so; now there is no need it should continue so; if it be amiss,
it may be mended; if I do not belong to the right prince,
if I be not under the right power and spirit, I may be, for now it is a day of grace,
a day of mercy; I have been a rebel to the right prince,
I may be pardoned and taken into favour;
it is far better for people to know their state now, than to know it then,
because then there will be no remedy.

The apostle, in laying down fundamental, apostolical doctrines,
that were to be believed and taken notice of, and are in our age, so that we may say,
things written of old time, were written for our learning;
he makes this affirmation and position of doctrine,
he that hath not the Spirit of Christ, is none of his, he doth not belong to him;
though he be called a Christian, he is not a Christian,
if he hath not the Spirit of Christ; it is but a name he hath got,
he hath not that which makes him essentially so, for nothing can make a Christian,
but having the Spirit of Christ;
therefore when they would vindicate their being Christians, they prove it thus;
for he (speaking of God) hath sent the Spirit of his Son into our hearts,
and we know the mind of Christ; we know him that is true, or we are in him that is true;
these things, if they were right, if they were true,
were evident demonstrations that they were a sort of men
who depended more upon the Spirit and spiritual teachings,
and spiritual guidance,
than upon all the rules and methods of teaching that were in the world.

I speak of this, friends, because you know as well as I,
how averse this age of ours hath been,
to have anything spoken of spiritual dispensations, or about spiritual teachings;
though a man hath been counted formerly a wise man, a learned man, or a man of parts,
if once he come to smatter out a little about inward teaching, it is enough to spot him,
and make him ridiculed of his acquaintance, as if there were no such thing in the world:
We have a book, called the bible,
it is from one end to the other full of such expressions, of being led by the Spirit;
you have an anointing which "`teacheth you all things:`" The whole tenor
of the New Testament is about spiritual teachings and divine operations,
and of faith being the operation of God;
and the Old Testament hath abundance of expressions by way of prophecy,
that in the New Testament days, if people would look for the law of God,
they must look for it _in their hearts;_ and if they would know God,
they must look to the Mediator, the Lord Jesus Christ:
The New Testament also directs us that way;
Christians should be the most spiritual people in the world, that is the guide, the rule.

But, say they, the scripture is the foundation of faith and manners, belief and practice;
this is too often but dissimulation, and I am afraid it is to be found in some; what,
is the scripture the rule of faith?
and may people believe what they find in scripture?
Yes, but say some, it is best be aware for fear of error.
What is in the scripture is serious, sound and orthodox, and did Quakers, think you,
never find in scripture that people were to wait for the Spirit, and pray in the Spirit,
and serve God in the Spirit, and that all religion that is not in power,
is not available, did they not find it in scripture?
And you that are not Quakers, did you ever read the New Testament?
How came it to pass that ye never found these texts?
But some people read and read the New Testament twenty times over, and mock and deride,
and persecute a man that shall speak of the Spirit`'s teaching.

I have admired at it, how intelligent men,
to whom God hath given a competent understanding, should be so blinded;
they have learned to read English,
and they have read the New Testament over several times, and the Old Testament too,
and they have read those sentences of Christ`'s doctrine,
that do so currently and unanimously speak of divine teachings and spiritual operations,
spiritual worship and spiritual religion,
that must have some motion and stirring of the Holy Ghost to be the original of it,
and that all others are not acceptable to God; doubtless they have read these things,
but I have often desired and do still desire that they would read it again once more,
and try and see what God will do;
he hath oftentimes made use of the holy scripture as a means
to awaken people and to open their understandings,
and let them see the mind of the spirit by which the scripture is written,
and the next time if they can find scripture text and apostolical doctrine,
to teach people to wait upon the Spirit, I hope they will leave scoffing and mocking.

It hath been hitherto looked upon as an invention,
to speak of the teaching of the Spirit, and waiting upon the Spirit,
and being moved by the Spirit.
This apostolical doctrine, prayer and worship,
hath been looked upon as an invention that we have brought in:
To look for the Holy Ghost in that way that was never known to our fathers,
is a fantastical conceit of the Quakers, say they:
To tell people they must be led by the Spirit in divine things, as in prayer and worship,
and the like, that in these things they must wait for the Spirit,
was there ever any man that was counted good for anything that ever preached so,
before they came?
Do we read any such kind of thing in scripture?

O! the blindness that hath happened to this nation!
I have considered, not without admiration, how the devil (he is a Spirit too,
and a wicked one) how he should have power to prevent our acknowledging the belief,
sense and feeling of the Spirit of God now-a-days;
there are thousands in this nation that have formerly believed
that it was as impossible for a man to believe the divine
motions and strugglings of the Spirit of God in this life,
as to raise their fathers and mothers out of their graves;
some of their learned teachers have told us it is a whimsy and fancy,
and that there was no inspiration of the Spirit now-a-days,
but that it was a foolish fancy in us to wait for such a thing, it is needless, say they;
there was an immediate teaching in the apostles days,
and they had the sense of the Spirit of Christ working in them,
to teach them to write letters and epistles to the church,
which letters and epistles were written by the moving of the Holy Ghost,
but we have no need of it now,
the Holy Ghost hath brought order and government into the church,
we have it now in black and white printed in our books, therefore say they,
there is no need of the Spirit,
and people need not be acquainted with the operation of the Spirit now-a-days,
in regard they have it in their books what manner of worship they must perform.

I grant them their due, that they have the direction of the scripture;
I am able to understand that people are to worship God, and pray to him,
and are to meet together and to observe this and
the other doctrinal precepts there laid down;
I confess I can make shift herewith to frame out a form of religion,
and if I do not mistake in the opening and explication of the doctrine,
I could make a right form too, but I am liable to mistake,
another man that understands Greek better than I,
saith that the Greek word ought to be translated so,
and the form ought to differ in such a respect;
some say the only way of government is by bishops, and the word bears it in the original,
and another saith he hath stretched the word, for the word means presbyter;
another saith presbyter signifies no more than choice of church elders and deacons,
and such like, and this is all out of one book, the settlement of bishops, presbyters,
and elders.

Here a number of form-makers all fall out about the meaning of the word;
what remedy can any mortal man provide for this?
We must not be killing and slaying one another about words;
if I be an episcopal man and say the word signifies bishops, I may be a wicked man still;
and if another say it must be presbyter, he may be a wicked man too,
and if another say it should be pastor, elders, and deacons,
he may be a wicked man notwithstanding.

Thus they have rent and torn one another about church government;
what remedy shall we have for this,
that these quarrellings and contentions about terms and words may come to an end?
Could a man prescribe a more certain remedy for all these mistakes than this,
if they had a measure of this Spirit which did work
in the apostles when they wrote down these words,
which the apostles had in writing them,
then I say they could tell you what the Spirit meant,
for the Spirit is the same and not changed, and the words are the same to a small matter,
so that if a man had that, he might end all the controversy;
but where shall we have a man that hath this Spirit to end the controversy?
There is none now-a-days say the Protestants,
and say the Papists there is none but one that hath this infallibility;
and many will not suppose that neither, for some of them say,
that one man is as infallible as another man;
there is a great dispute whether any one man be infallible,
or a great many men together are infallible about doctrine and worship:
This might be cured all at once if we could come to this conclusion.
Papists, Protestants and Quakers, here is an end of all out-side worship,
he that hath not the Spirit of Christ is none of his: If there be not Spirit in it,
it is not Christ`'s religion and worship.

So that they that jangle and bark and bite, are without, among dogs and sorcerers,
that are strangers to the Spirit of Christ;
there is a spirit in them that denies the Spirit of Christ,
there is a Spirit that rules in them that are without the Spirit,
for nobody that I know of, acts things without a spirit, and without being moved.
What, are good and bad all moved by the Spirit, and yet are there no motions?
I have sometimes turned the question upon people,
and asked them if there were no motions of the evil spirit,
hath it no such kind of influence that it can move upon our spirits,
that we can sensibly feel ourselves thrust forth to such an action?
I never met any man that would deny it,
they are so generally favourable to the wicked spirit;
no man will deny but the devil hath a way of moving
and stirring upon the spirit of a man,
and to suggest to him such an evil thing, and as I have sometimes said,
it is so received an opinion,
that when the malefactor comes to be arraigned at the bar for some grievous crime,
they lay the foundation of the indictment,
such a day he was moved and instigated by the devil to do such a thing;
here is a settled motion for the devil, for him to influence people`'s spirits,
but no way for the good Spirit of God to influence men`'s spirits;
here is nothing left us but a bad instigation; but to know inward motions to good things,
it is not to be expected now-a-days.

How should ever the cunning serpent, that would have power over the best of us all,
be said to winnow us?
Christ signified to Peter, a bold and resolute disciple, Satan desires to have thee,
and winnow thee as wheat; if the devil had power over everyone,
to make them his servants and slaves,
what remedy have we but we must all perish and go headlong to hell with him,
unless there be some way of resisting him?
That is true, say people, the devil must be resisted; we find it in the New Testament,
"`resist the devil;`" this is a good exercise; but tell me one thing,
when I go about to resist the devil, must I resist him in my own power?
If I was to say you might do so, you would say I was an erroneous preacher,
and well you might: This is an old free-will doctrine,
that a man may resist the devil by his own power, and escape his snares,
and do the will of God:
This hath been cried down by the doctors of the Church of England,
and by most of all sorts of Christians; and for our parts,
since the Lord hath opened our mouths, we did never speak a word in favour of it,
as if we went about to resist the devil in our own strength; if we did,
the devil would make fools of us:
He that goes about to resist the devil in his own strength,
will be entrapped and ensnared by him, in that men have a propensity to sin,
and by his cunning and subtlety, may be led into a snare before they are aware.

Thus it is agreed on all hands, that our power, as men,
is too weak to resist Satan`'s temptation,
so that you see we must have the assistance of the divine power, or all go to hell;
there is no medium between those two extremes, some extraordinary power must assist me,
or else the devil will have me.
If you will not admit of a supernatural power to come in to help me and you,
we must all go to hell, there is no remedy: I will say my prayers, saith one; do so,
yet in the best of your prayers there will be sin;
and "`if I regard iniquity in my heart,
the Lord will not hear me:`" I will go and hear sermons, say you;
the very man that preacheth will tell you,
that hearing of sermons will do you no good at all,
unless there be motions of the Spirit of God,
so that you will be wrapt from one thing to another, and have diversity of doctrines,
and come to no fixedness; and while you concern yourselves about doctrines,
all the while the devil prevails upon you; as for the tongue, he hath the rule of that,
and as for the hands, he hath the rule of them,
and makes you do those things that by his perpetual suggestions he moves you to;
so that your going to church and saying your prayers signify
nothing to bring you from under the wrath of God,
and from the captivity of the devil:
Hath not the devil those in captivity that go to church, and say their prayers,
and give alms?
These are things that you can do by your own power, the saying of your prayers,
and fasting, and giving of alms, these things thou mayest do,
the devil will not hinder thee,
for he knows that these will not bring thee out of his clutches,
nor out of his chains and fetters.

There is but one way and means by which the devil may be effectually resisted,
that is by taking to our help stronger than he;
I have gone for help to many stronger than I, in my young days,
that I thought to be stronger Christians,
and many of them did afford their help in the work, by counsel, by persuasion,
by exhortation and by doctrine, but all this did not do; and the reason was this,
because the devil was too strong for me, and so he was for them.
As long as you go for help to this and the other place,
until you find one stronger than the devil,
expect no deliverance or help from anything in the world,
but lay aside all confidence in the flesh, in any many man on earth,
or in all the doctors words and best preaching you shall hear,
lay aside your confidence in them, they will never do you any good in this respect,
for they will never break your chains off; many are loaded with them, but some, I hope,
are "`weary and heavy laden,`" and feel the weight of sin,
I pray God increase the number; though it be a state of sorrow,
it is better than the state of fools, that make a mock of sin;
I would have you weary and heavy laden with your sins, and brought into this state,
to see yourselves captivated by the strong power of darkness,
and to see you are unable to deliver yourselves out of it by your own power.

For me to fall into the hands of a tyrant that is stronger than I,
and no man to deliver me, how sad would it be.
If I could find a man stronger than this tyrant, and that would kill him,
I should be his servant, and have a better master: No man can kill this tyrant,
that hath led me captive and made me a slave; if he say, be drunk, I must be drunk;
if he bid me swear, I must swear:
This is the slavery that the devil hath got his servants into, that whatsoever he saith,
that they must do, if he bids them do it: "`O! wretched man that I am,
who shall deliver me?`"
I cannot deliver myself, and no man can deliver me;
I would be acquainted with all Christians, if they could help me;
I would try all religions that are this day in the world, to see if there be help for me:
Many are oppressed with sin, and they go to and fro, to see what help can be given them,
to free them from the bondage that the devil hath them in:
This sort of people are to be pitied, and the souls of all good people will pity them,
for such as these seek the living among the dead;
they seek that to redeem them that cannot redeem them: We have sought, say they,
for power and strength from them that had not enough for themselves,
they were captivated as well as we,
and all this because we came not to him that is stronger than the devil.
You will take the same course, and stay till grey hairs come,
and you go down to the grave with sorrow, unless you come to one stronger than the devil,
and then trust in him, believe in him, and expect deliverance by him.
The reason why people do not expect deliverance is,
because these two things are shut out of their belief.

[.numbered-group]
====

[.numbered]
I+++.+++ They believe not that a sinful life will carry them to destruction.

[.numbered]
II. They think there is not any possibility in this
world to live any other than a sinful life.

====

The devil hath brought men to this pass, that they live as easily in a sinful life,
as a fish in the stream: We are in the way, say they; when we were baptized,
we were initiated into the Christian church, we were baptized with the sign of the cross,
that shews we are soldiers of Christ and bear his badge and banner upon us;
and the man said at that time,
I was made a child of God and an inheritor of the kingdom of Heaven; if this be not true,
then I am cheated and deceived, for I am to believe this to be true;
the church hath affirmed that these things are to be believed;
and to question the veracity of the church, is to question all.

I would question whether thousands find the truth of it.
When thou wert baptized,
there was a kind of covenant and bargain made for
this child of God and heir of eternal life,
that he should forsake the devil and all his works,
and the pomps and vanities of this wicked world, and the sinful lusts of the flesh:
And there is security given that this child shall never serve the devil and sinful lusts,
and never be proud, but serve God and keep his commandments:
Now this security being taken,
then they suppose that this child will certainly be an heir of the kingdom of God.
It is very true, stand to thy church;
if this security that is taken for a child be but effectual,
then there is no doubt of being a child of God,
and an inheritor of the kingdom of Heaven.
But if this security fail, is the church to blame if men`'s hopes to eternal life fail?
Was it not my condition, that thou shouldest forsake the devil and all his works,
and the pomps and vanities of this wicked world, and the sinful lusts of the flesh,
and if thou break the bargain, and thy part of the covenant, and miss of eternal life,
who is to blame?
Look to the security, see that thou forsake the devil and all his works,
and the pomps and vanities of the world.
But thou mayest rather say, I have enjoyed as many of them as I could;
and for the lusts of the flesh, I have enjoyed as much of them as I can; and what,
dost thou believe thyself to be a child of God and an heir of the kingdom of Heaven,
notwithstanding?

If I promise to deliver a man any particular kind of goods,
upon the payment of so much money, if I fail in delivering the goods,
he will not deliver the money; a man must forsake the devil and all his works,
and never lust after the pomps and vanities of this world; that is a child of God,
let us see him grow up, and if he goes on to be faithful in this covenant till he die,
I do not at all question but he will be an heir of eternal life;
but when all this is broken, and the security signifies nothing,
and the man is given up to serve the devil, breaks all God`'s holy laws,
erreth and strayeth from the way of God`'s commandments like a lost sheep,
and grasps at the pomps and vanities of the world, as much as he can,
and thinks he gets no more than comes to his share;
and when he shall indulge the lusts of his flesh, this is a child of the devil;
he is a child of that Spirit that was a liar from the beginning.
Never talk of being a child and an heir of God`'s kingdom, such a man is in fetters,
he is to go along with the devil and his angels,
and there is a kingdom prepared for them, and a kingdom of darkness,
and he must have his portion with them in everlasting misery:
Tophet is prepared of old for all the workers of iniquity.

What for those that are baptized?
Yes, but do not you deny baptism?

No, not I, I would have men and women baptized with a baptism that will do them some good.
Some have seen the vanity and weakness of this kind of baptism,
and called it baby baptism;
and therefore would go and be baptized and plunged in the water over head and ears,
but they came up again with the same heart and mind, and the same polluted soul.
John baptized in Jordan, and all Jerusalem and Judea came to be baptized of him:
There were a sort of baptized persons then that crucified the Lord Jesus Christ,
that never did them harm in his life, but much good.

This baptism had never an apostolical patron,
but there is another baptism that is so infallible a baptism,
that if a man were surely baptized withal, he was sure of Heaven,
he would never need any other assurance of Heaven
than to be baptized with the baptism of Jesus Christ:
The lip of truth speaks of him, "`he that believeth and is baptized,
shall be saved:`" He shall be saved in spite of the devil and all his temptations,
in spite of persecutions and the stumbling-blocks laid before him.
Here is a baptism worth a man`'s while, worth all his labour, if he could obtain it;
"`the that cometh after me,`" saith John the Baptist,
"`he shall baptize you with the Holy Ghost and with
fire;`" here is a baptism belongs to Christians,
an ordinance ordained.
Far be it from us to deny baptism; but we would light of the right,
since there are so many sorts: This baptism is so right and certain,
that it ascertains a man of his salvation,
but it is done by "`the Holy Ghost and with fire:`" If it be by the Holy Ghost,
then it is far enough off from us; for there is no Holy Ghost in our days, say some,
so this baptism is ceased, and inspiration is ceased.
If the Holy Ghost and fire be the matter of baptism, the thing being failed and ceased,
the consequence cannot follow;
thou and I cannot be baptized because there is no working of the Holy Ghost in our days;
say some,
this baptism is "`with the Holy Ghost and with fire;`"
with fire for burning up our corruptions,
and purifying our hearts.
But the Holy Ghost hath done working upon men, say they;
why then there is an end of baptism: A man is hungry, and when his time comes to eat,
he hath no victuals, yet he sits him down as if he did eat;
will this feed and nourish him?
So men now-a-days, they have a baptism wherewith they are baptized;
but baptism with "`the Holy Ghost and with fire,`" is the right baptism,
therefore do not baptize until you find the Holy Ghost, this will be far better;
this is the baptism that they which come to know it, are sure of salvation by it;
for by this baptism,
they are borne up and tinctured in their souls with the Divine Spirit of Christ Jesus,
proceeding from the Father and the Son, till they receive his likeness,
and so die unto sin: "`As many as were baptized, were baptized into Christ`'s death.`"
The apostle openeth it, "`in that he died he died unto sin once,
but in that he liveth he liveth unto God;`" so that they that were baptized,
were baptized into Christ`'s death; and you that are dead unto sin,
how should you live any longer therein?

These that were baptized lived without sin; can that be true,
that no one lived without sin but Christ only?
Yes, saith the apostle, you that were free from sin, are alive to righteousness;
their life stood before in sin, and now that life is taken away by baptism,
and they are alive to Christ, and he that liveth he liveth to God.
He that comes to be partaker of the first resurrection, if he live ten, twenty, forty,
or a hundred years, he liveth to God,
he liveth no more in the pomps and vanities of the world,
and the sinful lusts of the flesh, but he liveth unto God.
This baptism, whoever comes to be baptized with it, shall be saved;
so that we do not deny baptism.

But we hear say, that you deny the Lord`'s supper.
We have never had such a thought, God knows;
there is nothing that our souls long after more;
but people have been making a kind of work of their own, they have lost a reality,
and make shadows, as children do, who when they see things made in the house for service,
they will make the like in sand and clay.
People do not see what a great thing it is to attain to the supper of the Lord;
as things come into an evangelical opening,
we spake then more lively and freshly of things.
"`Behold I stand at the door and knock, if any man open to me,
I will come in and sup with him, and he with me.`"
For the understanding of this text, go and examine,
and search all the commentators you can find, and see what the learned men say of it;
see if they do not apply this to the inward call of the Spirit and grace of Christ,
to let him into our hearts;
and would one think that those that wrote these things
should be against the spiritual dispensation of things?
They say that this knocking at the door of the heart signifies
the call of God`'s Spirit at the door of the heart.
There are two sorts of sinners that God knocketh at the door of their hearts; one is,
a man that is weary of his sin: For his part, he wisheth that he might never sin more.
As soon as he perceives the knock, and is called upon to let in the grace of God,
to help him against temptation, he freely opens his heart to receive it, and saith,
with all my heart I will entertain and welcome the grace of God;
glad I am that God hath had so much patience towards me; and since God offers his grace,
I will embrace this grace of God above all pleasures, and I will take it into my heart;
the grace of Christ is the greatest jewel that I know.
Honest Paul, he took this course, and prayed, Lord take away this tempter;
here is a temptation that troubleth me, and I am not willing to yield,
for all the devil follows me with it; he cried unto the Lord,
and besought him three times, earnestly, to take away the temptation;
and the Lord answers him, "`my grace is sufficient for thee.`"
What matter if the tempter buffet thee, and trouble thee,
hast thou not received my grace into thy heart?
Thou art a believer, and thy trust is in me, and "`my grace is sufficient for thee.`"
Let the tempter do his worst, keep thou to the grace of God,
and thou wilt withstand and overcome the temptation when it comes.

If a man openeth his heart and receiveth Christ when he comes,
then you shall find such an alteration in that man,
that go and try him with the same temptation which prevailed over him the last week,
it will not do so now; though he be as weak as water,
and as prone to corruption and iniquity as before,
yet now having a faith begotten in him, that the grace of God will defend him,
he keeps out of the devil`'s snares.
Now this man trusting in this grace till his sin and iniquity be purged out,
now is the time to spread the table; there is a clean heart,
and the heavenly guest is now come,
and the dainties of the kingdom are brought to him for his nourishment.
Now, saith Christ, I will come in and sup with him, and my Father also will come,
and we will sup with him, and he with us.
This never happens to anybody so long as the table and heart is foul;
for the table must be clean, and the devil and sin thrown out,
and then will the Lord confirm and ratify, and seal the covenant;
so that here is a seal with a witness.
When a man hath this testimony of the love of God,
that God is reconciled to him in Christ, then Christ will come in,
and he will bring his Father, and they will sup with him;
and this is that which will give complete satisfaction to such a soul.

All the tongues of men and angels are too short to speak of these things,
as they are in themselves, but they are all manifested by the Spirit.
All the mysteries of the kingdom of God, are manifested by the Spirit of God;
now to say there is no Spirit to be regarded now-a-days, that is as much as to say,
we must never regard the kingdom of God,
"`for no man can discern the things of God but the
Spirit of God,`" no man can tell what they be;
as "`no man can know the things of a man but the spirit of a man.`"

But I must look to this and the other form, and mark, and methodize them,
for we can know nothing of the things of God themselves.

I hope you are all of another judgment,
and believe that this is a trick and cheat of the wicked one;
people do find the Spirit and will feel it if they will wait upon the motions of it.
I do not only mean when you are here together,
but when you are separated one from another;
when you feel the motions of this good Spirit, embrace them, and make them yours.
This Spirit is a gift that is given;
so may a shilling or a piece of bread be held forth to a poor creature,
but if he receive it not, he may perish for all that; it is not his,
though I have appointed it to be his,
and have separated it from my other substance to be his.
If he receive not what I offer and would give him, he may perish for all that.

Here is grace and truth comes by Jesus Christ, and God hath offered it to all men,
in that he hath raised up Christ from the dead;
"`the grace of God which bringeth salvation,
hath appeared unto all men;`" but all men have not received it,
therefore all men have it not; and they that have not the grace of Christ,
and the Spirit of Christ, are none of his;
but it doth not follow that they never will be none of his.
When they have received the gift by Christ, and say, I will be his sheep or lamb,
they will come into his favour by that gift,
and shall partake of the good things of his Father`'s kingdom;
but till they have received this gift, they are not the better for it,
they have not any benefit by the death of Christ; they have no help, no benefit by it,
except it be the patience and long-suffering of God,
who for Christ`'s sake bears with their weakness, and waits to be gracious,
and for Christ`'s sake offers them favour; but they are not come to the possession of it,
till they open their hearts, and receive the grace of Christ;
then they are convinced of Christ`'s end,
and that there is a possibility of enjoying the Spirit of God,
and of being taught and led by it.

Take this along with you,
that it is your absolute and indispensable duty to
wait from day to day upon the great God of Heaven,
the giver of every good and perfect gift, that you may have that blessed gift,
that you may have the assistance of a greater power than
your own to lead you out of sin into righteousness,
that through Jesus Christ you may be acceptable to God.
