[short="No True Worship Without the Right Knowledge of God."]
== Sermon XXVI. No True Worship Without the Right Knowledge of God.

[.signed-section-context-open]
Preached at Grace-Church-Street, May 24, 1688.

[.salutation]
My Friends,

There is no man +++[+++who]
can truly worship God, till he comes to a measure of certain knowledge of him;
for all the worship in the world where the veil of
ignorance still prevails upon the mind,
is all abominable; there is no acceptance with God:
There must be a knowledge of God before there can be a true worshipping of him;
for they that worship before they know God, they worship they know not what;
they worship a God they have heard of, but do not know;
so everyone that would be a true Worshipper,
must first come to that which giveth a true knowledge,
that raiseth up a certainty in the mind, this is the Lord, we will trust in him;
this is our God, and we will serve him.

And that all people might come to this certainty of knowledge,
therefore it is that God hath sent forth his Spirit,
that the things of God might be communicated by the Spirit of God,
for without the assistance of this Spirit, men seek after the knowledge of God in vain;
if they seek after the knowledge of God, they cannot find it,
and if they seek after the worship of God, and after acceptance with God,
they cannot find it; so that all religion, and religious performances,
that people are exercised in, where the spirit of truth hath not the beginning,
they will all prove fruitless in the end.

There are wise men in the world, who have employed their wisdom to find out the true God;
but God in wisdom hath ordained, that the world by all their wisdom shall not know him;
so there is an end of all their labour: How shall they know him then?
As "`none can know the things of a man, save the spirit of man that is in him,
so none can know the things of God,
but the Spirit of God;`" so that they that resist the guidance,
direction and counsel of the Spirit of God,
are like unto those that would enter into a house or palace,
and remember not the door that leads into it.

People would fain come into the divine knowledge
and into the understanding of divine mysteries,
but they would come by it another way; they would study for it,
they would learn it by arts and sciences, they would attain it by their own industry;
and herein they labour to excel one another.
If there comes a man among them that tells them, friends you are all out of the way,
then they are angry, and instead of inquiring what is the way,
they are angry that their way must be rejected.
Friends, you will never come to the knowledge of God but by the Spirit of God;
then they mock, and then they scoff and scorn the doctrine of the Spirit,
for the teaching of the Spirit hath been the common scorn and derision of our age.

It is so in our day with many;
if they cannot come to the knowledge of God any other way but by the Spirit,
they would deny to make use of that, to be subject to that,
and these put their trust in their own power and industry,
to find out the mystery of the knowledge of God; so they are "`ever learning,
but are never able to come to the knowledge of the truth:`" How should they?
How can a people come to a knowledge of the truth,
without the spirit of truth that reveals it?
Can any come to the knowledge of Christ unless he that sent him reveals him?
Where are people`'s books?
where are their bibles?
where is their rule (they call it so) that all their endeavours for many
ages have proved fruitless in respect to the knowledge of God?

This is but your say so, some may say;
how doth it appear that we have not attained to the true knowledge of God?
and to the true worship, and to the true religion?

I will tell you how it appears; for all, in all ages,
that have attained to the knowledge of God,
they have been made partakers of his divine nature and his divine qualities;
they have brought forth a sort of fruit in their lives and conversations,
that hath been of the same nature, it hath been holy and divine.
They have known the sanctifier, and they have been a sanctified people,
so they have become one with him,
and have shewn forth the beauty of holiness in their lives,
that is a demonstration that may shew the knowledge of God,
for without it they live another life, an unholy one, a corrupt one, a life of self-love,
a life of pride, vanity and enmity, and that they never had from God,
but from another root; a life of iniquity and sin, it came from another seed;
so that they are still without the knowledge of God.

And again, all that have come to the knowledge of God, they have trusted in him;
that people cannot do now-a-days, except here and there a few that do know him;
the generality of the age they cannot trust God;
they must have something else to rely upon, and trust to, for in him they cannot trust.
Now the Lord said by the prophet of old, they that know my name will trust in me;
that is enough if people know God, whom to know is eternal life,
even to "`know thee the only true God,
and Jesus Christ whom thou hast sent:`" This is life eternal;
if people were come to this divine knowledge,
they would never take care or study for any refuge, or set up this, or that,
or the other thing to lean upon.
A rich man he trusteth in his riches, one trusteth to one thing and another to another,
but they would trust in the living God, and he should be their God and their rock,
and they would venture their concerns upon him,
both in this world and that which is to come, if they did but know him.
People may talk as much as they will, but he can never, properly, be said to be my God,
and thy God, till we cast our care upon him, and can venture our concerns upon him,
both in this world and that which is to come; and can say, he is our God,
and our reliance and dependence is upon him.

Now this is the effect and consequence of this knowledge of God;
such as come to partake of it, they shall have no need to be bid to worship him.
You shall have no need to make a law,
that this people shall worship the God that they know;
there needs no law to command the people of God to worship him;
his law is written in their hearts; and they that know him, will worship him.
There was never any man on earth, that had the knowledge of the true and living God,
that needed be put upon worshipping him, that needed a law to oblige him to it;
for the very knowledge that is given of God through Christ,
this brings forth naturally an adoration of the invisible
power which men put their trust in;
it produceth an adoration that is true worship;
it causeth an humble reverence of that power; it brings the soul upon its knees,
as it were; it brings the soul to stoop and bend, and bow upon all occasions to God,
as his God: It raiseth his expectations to receive counsel, and judgment,
and understanding, from him, as the fountain of wisdom;
and hereby people are taught to worship in the right divine knowledge.

But to tell men of the worship of God before they know him;
though you make as many laws as you will to force
them to worship that God they do not know,
yet you can never do them any good, nor make their worship acceptable,
nor make them devout; you can never bring devotion,
nor divine adoration into their hearts, by all the laws that you can make.

But there is a spirit of life that sets the soul
at liberty from its former bondage to sin and Satan;
and when this law comes to be revealed in my heart, what saith this law?
Worship God, give honour and glory to him.
This law saith, submit thyself to him that redeemed thee, thou art his,
thou art no more thine own;
this law being written in the heart obligeth a man to a true worship,
and to "`worship God in spirit and truth,`" for this
man hath done imagining among the Heathen,
that there are gods many, and lords many: He hath done imagining what God is,
and where he is, for he is now come to know him;
he is instructed beyond the best scholar in Athens,
let him be ever so mean and despicable in the world; if it be ever so poor a lad or lass,
they are beyond the best scholar in Athens;
for the best scholar there came only so far as to contradict their fellow scholars:
Some of them were for Mars, and some for Jupiter, some for one God and some for another:
These scholars, by some beam of divine light shining in them,
had come to perceive that the influences that were in Mars, Jupiter and Venus,
and the Sun and Moon, and other planets, they received them from an higher power,
that is, God.
They denied not that these planets had power and influences given to them;
sometimes they are called heavenly bodies; the sky, or canopy of Heaven; and sun,
moon and stars are called heavenly bodies, they have power and influences;
but this was given them,
and that power must be greater than theirs from whom they receive their power,
virtue and influence, even that God who is the maker of all things.
The scholars at Athens understood so much,
as to see there was a God greater than the planets which the nations worshipped;
they thought that God was to have an altar as well as Jupiter and Mars,
and those other gods,
and therefore they built an altar "`to the unknown God,`" whom they ignorantly worshipped.

If thou and I are come to the knowledge of the true God,
then we must know more than these scholars of Athens,
who erected an altar "`to the unknown God:`" When the apostle
came to preach divinity among these scholars of Athens,
who were masters of arts and sciences, he preached to them, saying, that unknown God,
whom ye ignorantly worship, him declare I unto you;
we do not need to declare to you the gods of the nations, for you worship them,
but to declare to you the unknown God whom ye ignorantly worship;
these were the great scholars of Athens that the apostle spake to:
What dost thou declare of God?
"`He is the God that made the world and all things therein,
seeing that he is Lord of Heaven and Earth, and dwelleth not in temples made with hands,
neither is worshipped with men`'s hands, as though he needed anything,
seeing he giveth to all life and breath, and all things,
and hath made of one blood all nations of men to dwell upon the face of the earth,
and hath determined the times before appointed, and the bounds of their habitations,
that they should seek the Lord, if haply they might feel after him, and find him,
though he be not far from everyone of us; for in him we live, move and have our being;
for as certain also of your own poets have said, for we are also his offspring;
for as much then as we are the offspring of God,
we ought not to think that the Godhead is like unto gold, or silver,
or stone graven by art and man`'s device.`"

Here is a way of learning, you need not turn over books anymore;
if I would know the true God, I must know who gave me life and motion,
and who created me, he is not far from me; and how should I find the knowledge of him?
"`feel after him, if haply you may find him; for he is not far from any of us;
in him we live, and move, and have our being;`" we cannot live without him one moment;
he giveth life, essence and power, to all creatures in Heaven and Earth;
we must have him with us, or we cannot live; I die as soon as my life departs from me,
so do you; if my breath and life continue with me,
it is by the power of him that giveth it, in whom I live, and move, and have my being;
still it is in him that first gave it.

Here all the great scholars and philosophers were counselled to feel after him;
so are all people now-a-days: This is our business,
when we go to preach the knowledge of God to them that want it; our commission runs not,
that we must read such a book, such an author, and turn over such a leaf,
and there you shall have a discovery, and a fair demonstration of the attributes of God,
of his wisdom, power, goodness, mercy, omnipotence and omniscience;
our commission runs not that way, but our commission runs thus;
that we turn people from darkness to light; and from the power of Satan to God;
to turn their minds from that which may hinder the knowledge of Christ, from darkness,
blindness and ignorance; God is not far from them; perhaps they might find him,
if they did seek after him.

There are a sort of men now-a-days (such as were in former times) that say unto God,
"`depart from us,
we desire not the knowledge of thy ways;`" such a sort of people are dark,
and blind and ignorant, and are like to continue so, that say to God, depart from us;
God is come to them, but they bid him depart from them:
We are sent to these people that are dark and ignorant,
and have not the true knowledge of God, though they have abundance of notions,
hear-say knowledge, learning and speculation;
our business is to convince them of their ignorance,
and to turn them from darkness to light.

There are a people that have mocked and scoffed at us many years; what, say they,
is there a light within?
Must we go to the light within?
Hath everybody a light within?

Yes, I believe so; and you must believe so too, if you will believe the scriptures.
Christ is the true light, and he hath enlightened every man that cometh into the world.
If he did light them, how did he do it?
I will tell you, say they; he spake a great many gracious words,
and somebody hath writ them down.
What, will this prove the light within?
Because we have got a New Testament, and Christ hath spoken a great many gracious words,
and they are written down and recorded, doth this prove the light within?
No, people might have been in darkness still, for all the books of the New Testament,
and the Old Testament too, and for all the books in the world;
for they would never have conveyed light into the hearts and consciences of men,
if God had not placed it there.

Indeed these books may be instrumental,
and God doth make use of them as a means for the conveying of light and grace,
and working of true conversion; but the holy scriptures cannot do it of themselves,
unless there be a co-acting and cooperation of the Spirit of Christ with them;
without this spirit they cannot convey saving light to us;
how prove you then a light within?
The apostle tells you, if you will believe him, 2 Cor. 4:6: "`God,
who commandeth the light to shine out of darkness, hath shined into our hearts,
to give the light of the knowledge of the glory of God,
in the face of Jesus Christ;`" so that everyone that retireth into himself,
will know quickly, and understand his error, and confess that there is a light within,
and that by this rule, because there is something in the heart,
that makes manifest that which is reprovable; if they do or say a thing reprovable,
that which manifesteth a thing is light; that which manifesteth dark words or works,
is light.

Now when they have found this light within, the next question in controversy is,
whether this will give men sufficient light for the true knowledge of God;
whether this be sufficient to bring a man to life and salvation?

I am of that judgment, that it is sufficient; and I believe it heartily,
and preach it boldly in the name of the Lord, that the light that shines in your hearts,
shines there to give you the true knowledge of God, in the face of the Mediator,
the Lord Jesus Christ.
You cannot believe this, you will say, for you have had this ever since you were a child,
and you know not the least good it hath done you; all our learned men and ministers,
go to what sort you will, they speak very slightly of it;
this light within is nothing but natural conscience, a poor light,
it is but an _ignis fatuus,_ that will mislead us.
But let me tell thee, the reason why it doth thee no more good, is,
because thou hast been loose and wanton, and vain,
and wouldest not receive the reproofs of it; reckon up the time, and call to mind,
when thou didst receive the reproofs of it, then it did thee some good,
and brought thee to remorse, and brought anguish and sorrow, and trouble into thy mind,
and brought thee to a right sense of what evil thou hadst done;
but if thou didst not regard it, no wonder it did thee no good;
its reproofs and counsels were like the seed sown by the high way,
the fowls of the air gathered it up, and it did not grow; that is,
the devil plucked it up,
and then the soul lay as seed that brought forth no fruit to God,
and the devil might have what advantage he would.

I will tell you the reason why so many learned men, men of great abilities,
speak so slightly and meanly of it, because it hath done them no good,
inward nor outward, that they know of:
How should it do you good when it hath done them none?
The reason why it doth them no good, is because they do not believe in it;
and did Christ ever do anybody good that did not believe in him?
He gave men power indeed to become the sons of God,
the greatest good that they are capable of;
but it was to those that believed on his name:
Were all they the sons of God that heard Christ preach?
No, some were the devil`'s sons; our Saviour tells them,
that they were of their father the devil, and they did his works;
they came to meetings and heard Christ preach; he discoursed to them,
but it did them no good, for they did not believe on his name.

And then it appears in the next place, that if this light be taken heed to,
and if men come to be taught by it and receive instructions,
they would then have it all for nothing, they would have it all for God`'s sake;
all the counsels and understanding of divine mysteries, all the openings of God,
and all their knowledge of God would be obtained without charge:
What then would become of the trade of preaching Christ, and the attributes of God;
then their silver-shrine-trade will be spoiled, and then their Diana is gone;
and this light hath done them no good inwardly because of their unbelief;
and it doth them no good outwardly, because it spoils their preaching trade,
because it teacheth men for nothing, but teacheth them, for God`'s sake,
the light of the knowledge of God, that shines in the face of Jesus Christ,
wherein are the openings of the mysteries of the kingdom of God.

So that if any come to know the virtue and the power
that turneth men from darkness to light,
they are come to another state, and turned from the power of Satan to the power of God;
and when the power of God is revealed in them, then they say, this is my God;
now I know the true God; they speak as those that are acquainted with him;
"`this is life eternal to know thee the only true God,
and Jesus Christ whom thou hast sent:`" It is not to know him at a distance,
but as always present: The soul comes to be acquainted with God,
as familiarly as a man is acquainted with his friend, and better too:
A man that is acquainted with his friend, only knows some things pertaining to him;
but those that are acquainted with their Maker they know the whole counsel of God,
so far as belongs to their peace; therefore it was not in vain said of old,
"`acquaint thou thyself with him,
and be at peace:`" Be but acquainted with that inward power that knows thy thoughts,
and then nobody need to preach a sermon to thee of the omnipresence of God;
nobody need make thee a doctrine of it,
and offer reasons and motives for thee to believe it; it is all foolish labour;
I know that God is with me, and near me; I feel him in me, and with me,
at my down-lying and up-rising; when I am in my shop and about my business,
he is with me in all places;
and such a man is also well instructed about the omniscience of God;
God`'s knowing everything; I have learned that since I came to know him,
all the doctors in Europe can tell me no more than I know in that point;
the Lord observeth all my goings, and numbereth all my steps; Lord,
thou makest manifest the thoughts of my heart, thou searchest my heart,
and tryest my reins.
Here is God`'s omniscience and knowing all things.
Here is divinity growing out of the life.

Then the wisdom of God is infinite; so are all God`'s attributes infinite,
incomprehensible and unspeakable, they are all so in him,
but he makes manifest a measure of his wisdom;
he brings a man from being such a fool as he was before, to become a wise man;
he was such a sot and fool as to become drunk and tumble in the dirt;
he could not stand upon his legs, but now he is become wise and sober:
Another was so foolish as to defile himself and wallow in his uncleanness;
now such a man comes to true wisdom, it begins in the fear of God,
"`the fear of the Lord is the beginning of wisdom:`" What doth his wisdom do?
It keeps him out of the dirt; it makes him live, first as a man then as a Christian,
to "`live righteously, soberly and godly,
in this present world:`" It leads him into the knowledge
of the mysteries of the kingdom of God;
"`to know and comprehend with all saints, what is the height, and length, and breadth,
and depth,
and to know the love of Christ which passeth knowledge:`"
This is more than bare sobriety and moderate living;
such are taught to live soberly, righteously and godly, to live by faith,
and to be led into the knowledge of the mystery of the kingdom of God;
to know the Lord Jesus Christ to their justification.
This is the learned and the wise man; he hath got the substance as well as the shadow;
he hath the marrow as well as the bone; he is reconciled to God, through Christ;
he hath remission of sins through Christ Jesus, that died for him and rose again.

When you come to be partakers of this, it will do you good; notions will not do it;
when you come to know God for yourselves, and understand him for yourselves,
to know him as your Saviour and Redeemer,
that hath rescued you from the snares of the wicked one; whoever doth this,
they will worship God; when they have this knowledge of him, they will bow to him,
they will be like those of old that said, "`he is our judge, he is our law-giver,
he is our king,
and he will save us:`" There arose a testimony in the hearts of good people of that age,
that God was their judge that judged them, their law-giver that directed them,
how they should make their way to him; that he was their king, and ought to rule them,
for he must save them.

So when people come to know God for themselves,
to be inwardly acquainted with God for themselves;
when a company of these souls meet together, when they have been at this school,
and learned this lesson of divinity, they then sit down and wait upon the Lord,
that God that searcheth the heart and trieth the reins,
and observeth how they do service for the honour of his name,
and they receive spiritual gifts from him to their edification and comfort,
and they receive judgment from him when they do anything contrary to his mind.

The Lord Jesus Christ is the Minister of the Sanctuary which the Lord hath pitched:
If men have a church, as they call it, they must have John or Thomas for their minister:
We know who is the minister of such a place;
but here is a minister set up in God`'s sanctuary,
this priest`'s lips shall preserve knowledge.
All that come to God`'s church are taught of this priest, he is a high one,
the high priest of our profession, we have not such another;
he is not set up by a carnal commandment;
his induction came not from any priest in this world,
but his induction came from the God of Heaven and Earth;
his Father set him up for a priest; he comes by a Heavenly induction and commission,
he is a priest forever, after the order of Melchisedeck, not after the order of Aaron:
If you come to God`'s church, you may hear this minister.

Some have called a house of stone, or wood, a church, but that will not do now,
therefore there are people that know better than they,
who see churches gathered of living stones; men and women are gathered to these churches.
Now the apostle saith, the church is in God, the Father of our Lord Jesus Christ:
If you will come to church you must come to Jesus Christ, the church is in God,
the Father of our Lord Jesus Christ, the general assembly,
the congregation of his faithful people.
What do you mean by a church?
Ask a learned man, that understands Greek and Hebrew, what is the meaning of the word?
A church, saith he, is the congregation of the faithful,
it is an assembly of the faithful people congregated together.
Where must they meet?
they must meet in the general assembly of the first-born,
whose names are written in Heaven.
The Hebrews were come to that church, though they lived many hundred miles asunder,
in Asia, Cappadocia and Bythinia: You are come to the general assembly of the first-born;
there is a priest, there is the high-priest of our profession, the Lord Jesus Christ,
who is a priest after the order of Melchisedeck, not after the order of Aaron.
How long is this priest like to stay in his priesthood?
Forever; he is a priest forever, "`not after a carnal commandment,
but according to the power of an endless life.`"

The priests that were after Aaron`'s order, they could not continue:
Death snatched one away, then they must have another priest;
but here is one that hath a priesthood higher than the Heavens,
by the power of an endless life: Here is the priest of God`'s church,
and the teacher of God`'s people; so that when God`'s people come to church, that is,
to God the Father, there Christ teacheth them, according to the old prophesy,
I will teach my people myself.

We have laboured to bring people to this teaching,
that they might come to the knowledge of the living God.
Now there needs none to teach them, for they are taught of God; blessed be God,
our labour hath not been in vain, we see the fruit of our labours, and are satisfied.
We have been labouring to bring men to know the Lord; now all shall know the Lord,
from the greatest to the least, and bow before him, and worship him;
they hear that their high priest`'s lips shall preserve knowledge.
If they do amiss, he chastiseth them for it; if they do well,
then he comforteth them by his Spirit: Now our labour is,
that all may be brought to this, and that everyone may know the Lord,
and may fear him and serve him, and worship him in his temple:
Our bodies are a temple for that use, to worship God in;
know you not that your bodies are temples of the Holy Ghost?
you must worship in yourselves, you must go into yourselves,
you must know the exercise of the grace of God in yourselves,
and the workings of the spirit of truth in yourselves,
and that your souls in your bodies may be bowed to the power of the spirit,
and that your worship must be in the spirit; you must pray in the spirit,
and give thanks in the spirit.

Though those that set up worship in the church,
talk of divinity and religion in every part of it,
yet the substance of all the shadows of the law are fulfilled in the gospel;
the substance of all the modes, and rites, and forms of religion,
are fulfilled in the gospel-way: So then let everyone compare and examine their state,
and consider how the case stands between them and their Maker,
what knowledge they have of God, and what trust they have put in him,
that so they may be persuaded and prepared to come within the pale of this church.
But you must first come out of the world,
else you can never come into that church that is in God; if you be in the world,
you must go to the world`'s church, and be the members of the world`'s church;
and you shall have this for your pains, the world will love you;
but if you come out of the world`'s church into God`'s church, the world cannot love you.

Be as good as thou wilt, thou canst never be so good as Christ Jesus,
and they loved him not, because he was not of the world;
"`if you were of this world,`" saith Christ "`the world would love its own;
but since you are not of the world, I have taken you out of it,
therefore the world hates you;`" if they do so to the green-tree,
what will they do to the branches?
are you better than I? saith our Saviour;
"`the servant is not greater than his Lord:`" Those that
are the disciples of Christ must be content to be persecuted,
reviled and hated for his name`'s sake; for thus they treated him who was holy,
and harmless, and undefiled, who gave them a good example, and who did them no hurt,
but did them good; yet the world hated him,
and it is but reasonable to expect that you should
suffer from the world in the same manner,
and bear it at their hands.

If you come to this church that is in God the Father, and Jesus the Mediator,
the church of the first-born that are written in Heaven,
and come out of the world`'s church, then the world will be about your ears;
all the world will set themselves against this church,
against the woman that shall bring forth a birth, that shall rule over the nations:
"`There appeared a great wonder in Heaven, a woman clothed with the sun,
and the moon under her feet, and upon her head a crown of twelve stars,
and she being with child cried, travelling in birth, and pained to be delivered.
And there also appeared another wonder in heaven
(a terrible thing) and behold a great read dragon,
having seven heads and ten horns;
and the dragon stood before the woman that was ready to be delivered,
to devour her child as soon as it was born: And she brought forth a man child,
that was to rule all nations with a rod of iron, and her child was caught up to God,
and to his throne.`"
When the dragon was ready to devour this birth, God took it into his own care,
in spite of the devil and all his instruments,
and he will save the child and preserve the woman;
he that sits in Heaven will laugh at his enemies and defeat them.
There is a place appointed for the woman in the wilderness,
where she is preserved by the Almighty Power; where she is nourished for a time,
and times, and half a time, from the face of the serpent;
but she must come out again after some time,
in spite of the devil and all his instruments, of all his dragons and serpents:
The woman must come out of the wilderness,
and the man-child must come down with great power, to rule the nation.

This hath been accomplished, say some, above fourteen hundred years ago;
and if you will take their word, the church hath been come so long out of the wilderness.
But the church that they speak of, hath it not wanted holiness and righteousness?
Hath it given glory to God on high, with peace on earth and good will to men?
No, their church hath lived in tyranny and barbarous cruelty, and shedding of blood.
They say the church was in the wilderness in Diocletian`'s time,
and when Constantine came to the empire then she came out of the wilderness.

If it had been a holy church, we should have seen the man-child come down from God,
and holiness and righteousness would have run down like a mighty stream,
and truth would have filled the whole earth.
All these things have not yet been fulfilled,
for we have seen the professors of truth fallen in the streets;
they have been persecuted and troubled, and thrown into prisons and dungeons;
but there is a better church somewhere to be found.

I read of the holy church, the lamb`'s wife,
the spouse of Christ that hath been hid somewhere, a great while,
in some corner or other in the wilderness;
but she will come forth again out of the wilderness,
"`leaning upon her well-beloved:`" She doth not come
leaning on this prince and the other potentate:
She comes not out of the wilderness leaning on captains, generals and armies,
but leaning on Christ her well-beloved, the immortal, invisible power of the Son of God;
she trusteth in it.

All the other churches, I have read of, they have leaned upon one prince or potentate,
or one emperor or another, and they have relied on these great men as on their bulwark;
but this church that comes out of the wilderness,
will come leaning only upon her well-beloved, the Lord Jesus Christ,
who is the author and finisher of her faith; she will put her trust in him,
for he will deliver his church from all her enemies:
And though the serpent cast out of his mouth water as a flood, after the woman,
that he might cause her to be carried away of the flood,
yet the Lord will cause the earth to help the woman,
and the earth shall open her mouth and swallow up
the flood which the dragon cast out of his mouth.
Let the dragon do what he can to destroy the woman and her seed,
she knows what her beloved can do,
he will command the earth to open and swallow up the flood,
and she shall go dry through it.

How happy are they that lean upon Christ their well-beloved!
The church of Christ in all ages hath leaned upon him,
and he hath founded his church upon a rock, so that the devil and all his instruments,
and the very gates of hell shall not prevail against her.
The members of this church have Christ Jesus for their teacher,
and they receive counsel and direction from him: He is their priest and teacher,
and he teacheth them by his spirit and his word, which he hath placed in their hearts,
and given them an understanding to know him that is true:
Christ`'s word you must keep to, if you will be true scholars.
This is true divinity;
if you will have the mysteries of the kingdom of God communicated and opened to you,
give heed to his word, and that truth that is in your inward parts:
Attend to that light and that grace that is manifested in your hearts,
and the Lord will shew you more of the power and efficacy thereof;
and "`if you be faithful in a little,
he will make you rulers over much;`" live answerable to
the understanding and knowledge that God hath given you,
and if you be faithful in a little,
he will communicate more and more of his mind and will to you;
and if you be led by the spirit of truth, you will trust in it, and hearken to it,
and understand the language of it in your own hearts;
and if you be a willing people in the day of God`'s power,
God will work all things in you and for you, and work in you "`both to will, and to do,
of his good pleasure.`"
