== Sermon XXVII. God`'s Wonderful Love to Mankind.

[.signed-section-context-open]
Preached at St. Martin`'s-Le-Grand, November 9, 1690.

It is our great concern, while we are in this world, to promote the glory of God,
and to work out our own salvation, to endeavour, as much as in us lies, to be sensible,
and to help one another to be sensible of the love of God to us:
This is the only thing that can give us true comfort,
to have a sense of the love of God to us in Christ Jesus:
There is nothing more certain than that all of us are partakers of the love of God,
which is imparted to us daily, and we live not a day without it; but we may,
if we have not a care, live many days without it,
and without the comfortable sense of it; and that is the reason,
that a great many of the sons and daughters of men, do shew forth in their lives,
so little love to God, because they have so little sense of his love to them;
for the apostle John,
that had attained to a great knowledge and experience in Christianity, plainly declareth,
that the reason of that love that we have to God is,
"`because he first loved us;`" and I do not believe
that any man can have any true love to God,
that is not sensible of the love of God to him.

And as for those temporal blessings that we enjoy in this life, as health and strength,
and our very breath and being, and well-being, that every day and hour are continued,
they are from the love of God to us,
and the lengthening out of our lives and vouchsafing
us opportunities for the good of our souls,
are evident tokens of God`'s love and good-will to us.
Where these things are not considered and regarded, men live like the beasts that perish,
and regard not him that made them, but go on in disobedience to him,
and dishonouring of his great name, and heaping up wrath upon their own souls:
And thus doth every man, while he remains in his natural state and condition;
for there is in every man by nature the seed and
root of all sin and rebellion against God,
which makes him return evil to God for the good he doth to us.

And I believe we are all of us sensible, in some measure,
of the depravity that is fallen upon all mankind, and of that enmity to God,
and that aversion that is in men to the doing the will of God,
and that impotency and inability that is in every man to the reforming of his ways,
and the changing of his heart, and leaving off his corrupt and vicious inclinations,
without the divine help and assistance of the grace and Spirit of God.

Now they that are thus far sensible of their alienation, by nature, from the Lord,
and are also sensible, that the time they have here,
is the only time they have for their preparation
and being fitted for that everlasting kingdom,
which we all would enjoy; how ought this to affect the mind of everyone,
that while they have time, they might prize it and improve it,
and come to an inward sense of the love of God,
that so they might have a love raised in their hearts again to God?
For people will never be obedient unto God, till they love him, nor ever love him,
till they are sensible of his love to them.

Therefore,
that which is the means and way of God`'s making
himself known to the sons and daughters of men,
that means, and that way, everyone ought to embrace;
everyone ought to be acquainted with it, and have the exercise of their minds in it,
that so we might come to the knowledge of God, and might know,
by an experimental and sensible feeling, the kindness of God to us.

And truly friends, they that are minded to spend their time, and exercise themselves,
in the consideration of the mercy and kindness of God,
they have work enough for their whole lifetime,
to consider and contemplate the manifold mercies of God bestowed upon them;
for we have our life and breath from him, whom the whole world obeys, and serves; God,
that made all living creatures, hath created us, and preserved us;
he hath had long-suffering and patience towards us until now,
and he is yet mindful to do us good,
which is evidently manifest by the invitations and promises he hath made us,
and the workings of his Holy Spirit that he hath made us acquainted withal.

For who is there in this assembly,
that God hath not made sensible of the tenders of his grace,
and invitations to repentance and reformation,
that they that live loosely and vainly in the world,
might turn to the Lord with all their hearts, and consider their ways and doings?
God hath waited to be gracious to the sons and daughters of men,
and his mercy and patience hath been beyond all human patience,
beyond the patience that ever you did bestow upon any,
this the Lord hath bestowed upon you; therefore I entreat you, in the love of God,
let this consideration sink deeply into your spirits,
that you may be affected with the kindness of God, and his patience towards you,
and his long-suffering, while you have been sinning against him.

But some will say, how shall I know this?
After what manner may I experience this love of God to me?
How may I be sure that the Lord hath a love for me?

My friends, it is not only temporal kindness that we enjoy from God;
it is not only the lengthening out of our days,
that is an evident token of the love of God to us;
but there is a demonstration and manifestation of it,
that is universally extended to the sons and daughters of men,
in that he hath sown his word in them,
and hath sown his truth and his grace in their hearts, that every man,
though he may be ever so wicked, ever so foolish and vain,
yet he hath many times checks and reproofs in his own heart: I know it,
and I doubt not but you do.

Pray whence comes that principle which doth stop you in a course of sin,
and check and reprove you for sinning against the Lord?
If you attend to it, and consider it, you will find it proceeds from God;
it comes from him, from him comes our life and breath;
then people should be incited to receive the grace of God;
the favour and mercy of God which he hath bestowed upon them,
in order to their salvation.
The scripture tells us, that grace and truth came by Jesus Christ.
If thou hast any good, it came by Jesus Christ; and if thou hast any truth,
it came by Jesus Christ, who is the fountain of truth,
and the fountain of the grace of God;
it is he by whom God hath made himself known to the sons and daughters of men;
it is Christ alone, that God hath ordained to be a Mediator between God and man,
that so he might be the minister of an everlasting covenant,
which we are brought into with God;
so that now people should come to the consideration of the
way and means that God hath ordained for their redemption,
namely, that he hath given Jesus,
that great and unspeakable gift of his love and kindness,
to the sons and daughters of men; here is grace and truth, that came by Jesus Christ:
How is it come?
It is come into my heart.
Though sin, and lusts and corruptions, perhaps, have a place in many,
yet Christ hath a place too--"`he hath made his grave with the wicked,
and was numbered with the transgressors;`" he was
like the seed that lies under the clods,
and is the least of all seeds, yet when it comes out of the ground, it riseth high,
and spreads abroad its branches, and brings forth fruit; this love of God,
this unchangeable holy truth, is in everyone;
why then should not every man be ruled and governed by it?

But some men will say, is truth better than falsehood,
and grace better than lust and corruption?

You may see that, by the light that is discovered in the inward parts:
Let every man turn inward to the grace of God,
turn to that light that shews itself in the creature, and see what it will do for us:
This is the doctrine that the apostle was sent withal;
he was sent with a commission to turn men from darkness to light,
and from the power of Satan to God: Why did he do it?
It was for this end, that men might have remission of sin,
and that they might come to an inheritance among them that
are sanctified by faith in Christ Jesus our Lord;
so that this gospel is the same that it ever was,
though men have divers ways of preaching,
and several methods and ways of declaring the truths of the gospel;
blessed be God the apostolical doctrine is preached again,
and the blessed gospel hath the same power attending it that was in former days,
and may have the same effect; and that this may be the portion of everyone of you,
is the end of our labour.
And we have in our eye but two things.

[.numbered-group]
====

[.numbered]
_First,_ to discharge a good conscience in the sight of God,
who hath given us his word to preach,
and to turn men from darkness to lights and from the power of Satan to God;
that we might keep ourselves free from the blood of all men.

[.numbered]
_Secondly,_ another end is, the desire that God hath placed in our hearts,
that all men everywhere might be saved; this is God`'s will;
if any be damned it is their own will, and the devil`'s will; this is God`'s will,
"`that none should perish,
but that all should come to repentance`" and be eternally saved.
Now in this work of your salvation,
we would have regard to him that sent us to preach the everlasting gospel,
and we would discharge ourselves faithfully,
and be "`made manifest in your consciences,`" that
the benefits of the gospel might come to be yours;
that you might answer the purpose of God, in sending Christ to be the Saviour of mankind;
you must turn from sin to God, and then you will find the blessing that comes by Jesus,
which is to turn everyone from his evil ways.

====

You may read this in a book, and you may also plainly read it in your hearts:
The Lord Jesus Christ hath given you light to distinguish between good and evil;
if you do good, you may make a comfortable reflection upon yourselves,
and this will be your rejoicing, the testimony of your conscience on that account;
but if you do evil, though all men do justify you and commend you,
yet you will be condemned in yourselves;
so that you have that in yourselves which distinguisheth
between things that differ in their nature and kind,
and you have a little enlightening by the knowledge and understanding you have
received concerning the things that are pleasing and displeasing to God;
if after you know this, you will go on in a way displeasing to God,
he will at length be too hard for you,
and plunge you down into the abyss of his wrath to all eternity.

After persons are satisfied and enlightened with the light of Christ,
and come to the experience of things in themselves,
they will love the light and walk in the light;
but there are many in this age that have read the scriptures plentifully,
and yet still go on in a way of sin, they cannot love the light that reproves them;
he that doth evil he hates the light,
and the dawning of the day is as the shadow of death to him,
and it brings nothing but condemnation upon such persons,
so that they do not love the light, though it is evident they have it and enjoy it;
and it shall be their condemnation whether they will or no;
if they do not love the light and embrace it, it will never be to their salvation.

God hath given Christ to be a light to the Gentiles,
and his salvation to the ends of the earth.
He is the light that enlightens every man that comes into the world;
the apostle John tells you the genealogy of the word of God;
"`in the beginning was the word, and the word was with God, and the word was God;
and the same was in the beginning with God; all things were made by him,
and without him was not anything made that was made; in him was life,
and the life was the light of men;`" the life of the eternal word was the light of men;
what men do you mean?
I answer, he is the true light that lighteth every man that cometh into the world.
He extendeth his light to every man,
but it is condemnation to every man so long as he continues to be a sinner against God:
"`This is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil.`"

Now all men are by nature dead in sins and trespasses;
after our first parents fell into sin they were dead to God;
"`in the day that thou eatest thereof thou shalt
die;`" when they had eaten the forbidden fruit,
they did not die as to outward appearance,
but they died as to that communion they had with their Maker;
in this dead state lie all the sons and daughters of Adam; but, as our Saviour speaks,
though they be dead, they shall live again; Christ is the Lord from Heaven,
a quickening Spirit;
this is the object of our faith that hath been extended
and offered to mankind ever since the fall;
there is no name under Heaven, no other power or spirit by which a man can be saved;
this great Mediator, the eternal Son of God,
is the light that lighteth every man that cometh into the world:
Faith in Christ is the same that ever it was,
notwithstanding the many forms of worship among the sons of men;
some of God`'s setting up, and some of men`'s setting up; yet among all these,
the object of faith is the same, and saith the same.

In the 11th chapter of the Hebrews, that little book of martyrs,
the apostle there gives you a catalogue of the mighty things
that have been done by the faith of God`'s people;
he begins with Abel; "`by faith Abel offered a more excellent sacrifice than Cain,
by which he obtained witness that he was righteous, God testifying of his gifts;
and by it, he being dead, yet speaketh;
by faith Enoch was translated that he should not see death, and was not found,
because God translated him, for before his translation, he had this testimony,
that he pleased God;`" and so the apostle there goes to Noah, Abraham, Isaac, Jacob,
Joseph and Moses: "`And what shall I say more, saith he,
for the time would fail me to tell of Gideon, and of Barak, and of Sampson, and Jeptha,
of David, Samuel, and of the prophets, who through faith subdued kingdoms,
wrought righteousness, obtained promises, stopped the mouths of lions,
and quenched the violence of fire, escaped the edge of the sword,
out of weakness were made strong, turned to flight the armies of the aliens.`"
All these great and noble things were done by faith;
it was the aspect their souls had upon Christ the Mediator between God and man;
it was their trust and reliance upon God through Christ the Mediator
that did support and uphold them in all they did and suffered.
This faith is still the same.

There are many faiths in the world beside,
but they will prove but the faith of hypocrites.
Some have a faith, that if they do this and the other work,
they say you may trust your souls upon these good works;
but this is not the faith of Abraham, the father of the faithful.
But some called Christians are gone so far in the doctrine of merits,
that they think they can do enough for their own salvation,
and for their friends and relations too;
that there may be more merit still over and above,
that others may have benefit by the merit of their works of supererogation:
But this is not the faith of Abraham, and other saints,
by which they wrought such wonders in the world.
I would not have men trust at all in their own works for salvation,
but trust in Christ alone, who "`is able to save, to the uttermost,
all that come to God by him.`"

But some will object that we are taught the doctrine of faith in Christ,
and justification by him.

Well, for my part, my tongue shall as soon drop out of my mouth,
as oppose the doctrine of being justified by faith in Christ.
But, let me tell you, this may be misapplied:
If a man believe that he is justified by faith in Christ, and yet knows,
in his own conscience, that he is condemned, he believeth a lie;
he is seduced and deceived.
A man cannot be justified by Christ, when the Spirit of Christ condemneth him:
Such a one, when he comes to lay down his head upon his dying pillow,
all his faith will fly away.
I have met with some instances, lamentable instances,
of those that were called Christians, that have made a profession of religion,
and at last have laid down their heads in sorrow.
If this be your mistake, consider, while you have time, that you may die in peace.

Now the proposition and tender of the love of God to mankind,
hath always carried that limitation with it, that everyone in the world ought to observe;
if a man hope to be saved by Christ, he must be ruled by him:
It is contrary to all manner of reason, that the devil should rule a man,
and Christ be his Saviour:
The whole tenor of the New Testament is against it (pray read it as oft as you please,
for it is a good exercise) you will find the true Christian`'s faith to be this,
that he that hath faith in Christ hath an operation upon him for the cleansing his heart,
and purifying and purging his conscience from dead works,
that he may serve the living God; though he hath been a servant of the devil,
it will make him leave his former servitude,
and bring him under the influence of another law,
the law of the spirit of life in Christ Jesus,
which will make him free from the law of sin and death.
The apostle sets down the several conditions he had passed through;
"`I was alive without the law once;`" he thought himself a man, a brave man,
a man of understanding, that had profited among the Jews; I was alive,
having respect to that law which should have been my governor;
"`but when the commandment came, sin revived and I died.`"
He had read the law, the commandment, many times,
and had been at the reading of it in the synagogue;
but there was a coming of the commandment which he had not been acquainted with;
there was a writing of the law of God in his heart;
when he came to this inward work upon him, where was then the life he lived?
"`When the commandment came sin revived,
and I died:`" There was a professing life he formerly lived,
but he was slain by the power of the commandment, it laid him in the dust as a slain man;
when he was in a slain condition he found out that
law in him that was the law of sin and death,
and this caused a combat and a war in him; "`I find a law,`" saith he,
"`that when I would do good, evil is present with me;
for I delight in the law of God in the inner man;
but I see another law in my members warring against the law of my mind,
and bringing me into captivity to the law of sin,
which is in my members:`" Now this brought him to a poverty of spirit,
into a sense of his miserable condition, and then he cries out,
"`O wretched man that I am, who shall deliver me from this body of death!`"

Now some people in this day, they are like the apostle,
they have a law in their members warring against the law of their minds;
the good that they would do they do not, and they can go no further:
But the apostle Paul did reach further, though he did not in that state know deliverance,
yet he had a faith that he should be delivered,
and that he should not be miserable all his days.
Thus having led the Romans into the several states through which he passed,
he brings them to a further state,
"`the law of the spirit of life in Christ Jesus hath made me free from the law of sin
and death:`" And now "`there is no condemnation to them that are in Christ Jesus.`"
How shall we know this?
They walk not after the flesh, but after the spirit.
Now Paul was come to that sanctified state,
that state of freedom and liberty which Christ Jesus
will bring all those unto that believe in him.

Holy men, in former days,
did experience and find a great strife and warfare in their own hearts,
they would all do well, and exercise a conscience, void of offence,
towards God and towards man; but there is a law of sin that wars in their members;
if we yield to it it leads to sin and death;
but if we yield ourselves to the law of the spirit of life,
there is a power that is derived from the Mediator,
that will translate the soul out of the kingdom of darkness and sin,
which the devil is the prince of, and bring it into the kingdom of God`'s dear Son.

There must be a real change wrought in us before we can come to God,
and to fellowship and communion with God, which alone can make the soul happy.
Let this be the exercise of everyone of us to adore
and magnify the great mercy and the kindness of God,
that he hath not withdrawn his spirit from you,
but hath placed a monitor in your bosoms that calls upon you to "`cease to do evil,
and learn to do well,`" and to consider that "`the
wages of sin is death:`" Here is a sin,
I may commit it; there is a temptation before me, but I know there is a bait and a hook;
I may swallow it if I will, but if I do, it will be my ruin:
Would I come to eternal death,
and have my portion with liars and wicked persons in the kingdom of darkness,
where the worm dieth not, and the fire is not quenched?
Or would I have my portion with saints and angels?
If I would have my portion with the blessed in the kingdom of God when I die,
I must walk in the way that leads to it; but the gate is strait and the way narrow,
and few there be that find it; labour then to be one of those few.

But what signifies our labour (some may say) if we can do nothing that is good,
not so much as think a good thought?
What signifies our labour?
All the labours and endeavours in the whole world cannot make a man happy.

I now speak to a people to whom God doth vouchsafe
the help and assistance of his grace and Spirit,
and the visitations of his love and power; you must now endeavour to do something;
if a man endeavour, with the help of God he may do a great deal of good,
and shun a great deal of evil: Though all our endeavours,
in our own power and strength can signify nothing, yet they are required by God,
and by joining them with his grace, and laying hold of opportunities,
by divine assistance, we may do what God will accept.
But if a man do anything in his own power and strength, whether prayer, hearing, reading,
meditation, or any other duty, he had as good let it alone.

I would consider you as those that God hath followed
with his grace and the manifestation of his spirit;
this is given to every man "`to profit withal,`"
and every man hath opportunity to work with it;
but he must work "`while it is day, for the night cometh when no man can work.`"

Let everyone of us that are now met together,
labour to be sensible of the love of God to us, and love him above all,
and express our love by a willing and persevering obedience,
that we may have the love of God shed abroad upon our hearts by the Holy Ghost,
and offer up living praises to him through Jesus Christ, who hath loved us,
and washed us from our sins in his own blood,
and hath made us kings and priests unto God and his Father:
"`To him be glory and dominion forever and ever.
Amen.`"
