[short="The Acceptable Sacrifice."]
== Sermon XXIX. The Acceptable Sacrifice.

Preached at Grace-Church-Street, July 3, 1692.

All people that would worship God and meet together for that purpose,
they had need have a great reverence upon their minds,
and a holy fear upon their spirits, that when they enter into the house of the Lord,
and draw nigh to the living God, they might not offer the sacrifice of fools,
but may offer to God that which may be acceptable to him.
For all worship, and all religion,
and all offerings and oblations that ever were offered to God by any people,
they have had a return unto the offerers and worshippers,
either of acceptance or rejection.
Many you know have been rejected though they have offered,
and many have been accepted of God,
and their offerings have been a sweet smelling savour in his nostrils; and, I hope,
we are all of that mind, that we would be glad to have our worship,
and service and offerings to God, accepted in his sight,
and that our present assembling together might be for the better,
and that everyone might have an answer of peace, and of acceptance in their bosoms;
but that can never be unless men be qualified and prepared in their drawing nigh to God,
and in all our offerings and worship that we perform,
our hearts be prepared according to the preparation of the sanctuary,
the preparation of God`'s dwelling and holy place.

The worshippers must be holy; there must be the fear of God,
and a reverence of the great God upon their minds,
before people can offer an acceptable sacrifice unto him, as the holy apostle saith,
Heb. 11:6: "`He that cometh to God, must believe that he is;`" which signifies,
that a preparation ought to be in the minds and hearts
of people that would draw nigh to God;
or perform any service or worship to God,
they must have the knowledge of the God whom they worship,
they must first know "`that he is,
and that he is a rewarder of them that diligently seek him.`"
Here is a qualification for worshippers, for religious persons;
as they expect when they meet together to find the Lord in the midst of them,
they must be qualified accordingly, there must be an awe upon their minds.

I am in the presence of God, I have an expectation from God,
that he will open his abounding treasury, and minister some good unto me,
or else to what purpose do people draw nigh to God?
It is because they would have something of him;
but they must come in an humble petitioning frame; "`he giveth grace to the humble.`"
It is the lofty, the proud, those that exalt themselves, the fat and the full,
that want nothing.
These, saith the prophet, the Lord "`beholdeth afar off.`"
A proud man or woman cannot draw nigh to God, the Lord looks upon them afar off;
nor do they partake of those divine and heavenly comforts and blessings,
and counsels and instructions that the humble mind
hath the promise of and will certainly enjoy,
the humble, God will teach, he will instruct the meek in his way;
but what is this to the lofty mind?
What is this to one that is exalted, and conceited and puffed up,
and reckons himself full and wanting nothing,
while he is swimming in the streams of pleasures of this world,
and savours only the things of the earth, the pleasures of a sensual mind?
These persons are not hungry, and so they are not fed; they are not thirsty,
and so they never obtain that which can satisfy the soul.
Our Lord Jesus Christ pronounced a blessing upon them that hunger and thirst;
but what is that to them that are full and lack nothing?

So my friends, in this and all other religious assemblies,
a great care ought to be upon everyone,
that their coming together to wait upon the Lord may be in that reverence and fear,
and that hope and expectation at the hands of God, that they might be bettered by it,
or else they all lose their labour, as Cain did; he would be an offerer,
he offered sacrifice, but was not accepted;
because his mind and heart was not right before the Lord, his sacrifice was rejected.
It was before he had killed his brother; he had great guilt upon him,
before he had killed his brother; he wanted the qualification of well-doing;
"`if thou dost well, shalt thou not be accepted?
But if thou dost not well, sin lies at thy door.`"
He was got into evil doing, and an evil mind hindered his acceptance with God;
so it doth with all men and women in the world that meddle with religious worship,
and sacrifice to God, if they meddle with evil doing.
There must be a taking off the mind from the evil of sin and corruption,
and the mind must be brought over to something that they
have received from God before ever they can be accepted.

You know the general doctrine of all Protestants is,
that we have no acceptance with God but through Jesus Christ;
we have no way to please God, nor can do anything that shall be acceptable in his sight,
but through one only Mediator.
Now if I should go to worship God,
or perform any religious duty without respect and deference to the sense
and participation of the virtue and power of that only Mediator,
how can I be accepted?
And it hath pleased God out of his infinite love to mankind,
to send this great Mediator into the world,
that every man that comes into the world is made a participant
of something of the life and virtue of that Mediator.
So you read, John 1:4, "`in him was life, and the life was the light of men,
the true light that lighteth every man that cometh into the world;`"
and that with respect to men whether they are good or no,
both good and bad, though all men are bad by nature:
So that though they are children of wrath,
and heirs of eternal damnation in their natural state, by reason of sin,
yet for all that this one Mediator, in whom this light hath shined,
hath sent forth his light among the sons and daughters of men, that is, the light of men,
that enlightens everyone.
So there is an offer made of something that presents
itself to the view of every man that is good;
if he apply his mind to it, he may have that good that comes by Jesus Christ;
he may draw nigh to God; as bad as he is, he hath some good,
that God hath bestowed upon men good and bad.
There is no man such a liar, but he hath some truth in him; there is no man so ungodly,
but he knows that which is pure and holy, that which hath reproved him,
checked and convinced him of his ungodliness.
This presents itself to the view of every man and woman, and calls them to repentance.

Now for men to make a shew and pretence to worship,
and not have regard to the glory of God, how can they draw nigh to God,
or God draw nigh to them?
Our Lord Jesus Christ saith, that "`where two or three are gathered together in my name,
I will be in the midst of them;`" but if people meet together in their sin and wickedness,
if they have a loose and vain mind, and intend to go on in wickedness and sin,
if they meet, they meet not in Christ`'s name, but in the devil`'s name,
and he is in the midst of them,
and he works and "`rules in the hearts of the children of disobedience.`"
So that this hath been the ground and reason why abundance of meetings
upon this account have been fruitless as to the benefit of their souls,
and the expectations of people have been frustrated as to their salvation;
they have not met with that in which the blessing is, and to which the promise is made.
The promise is not made to people that the devil rules;
there is no promise to such but the promise of eternal wrath to be executed upon them,
with the devil and his angels to all eternity; if you can make that a promise.

The promise of life and salvation which is recorded by the prophets and apostles,
it hath always relation to the seed that are in covenant with God.
In this the covenant stands, saith God to Abraham, Gen. 17:7,
"`I will establish my covenant between me and thee,
and thy seed after thee in their generations, for an everlasting covenant,
to be a God unto thee, and to thy seed after thee.`"
The covenant is made to Abraham and his seed, that is, with Christ Jesus the Mediator.
It is he that brings to God, those that trust in him and come to him,
he that cometh to him, he will in no wise cast out; they that do not come to Christ,
are cast off already.
All men, by nature, are cast away already; if any of them will be saved,
it is by coming to Christ, who is able to save, to the uttermost,
and to make peace for them, and of twain to make one new man;
and to make peace between God and the soul.

There is a necessity for all people,
that have any sense of their natural state and condition,
that according to nature have no title to the kingdom of God, to be reconciled to God.
By nature they cannot make a claim to righteousness and life;
they cannot reconcile themselves to God by all their works; saith the prophet Micah,
"`will the Lord be pleased with a thousand rams, or with ten thousand rivers of oil?
Shall I give my first-born for my transgression,
the fruit of my body for the sin of my soul?
He hath shewed thee, O man! what is good: And what doth the Lord require of thee,
but to do justly, and love mercy, and walk humbly with thy God?`"
They that will be saved,
must lay hold of salvation in that way and method
that the Lord God of Heaven and Earth hath prescribed.
He hath prescribed a way for everybody to be saved; he would not have anyone to perish,
but that all should come to repentance, and obtain everlasting life.
God hath made a way that will serve everybody alike; thousands as well as ten;
and all the world as well as one man.
Now the way that God hath made, is turning out of the state into which they are fallen,
and forsaking that governor that rules in the hearts of the children of disobedience,
and closing with Christ, whom God hath appointed to reign in everyones heart.
People in Christendom will say, they have closed with Christ.
Do not you hope to be saved by Christ, on the terms of the covenant?
It is not crying, "`Lord, Lord,`" but doing the will of God; the terms are,
all men must believe in Christ, the eternal Son of God;
and through the power of that faith they have in him, he comes to rule over them,
and they become subject to him.
And if a believer be not subject to Christ, he is all one as if he was an unbeliever;
"`circumcision, or uncircumcision,
avails not anything but a new creature;`" and "`faith which worketh by love.`"

The covenant doth not stand in mere words; if I conform to such articles,
then I am a Christian; if I believe all the articles of the creed, then I am a Christian,
and a child of God.
If a man will say, I believe, his say so is not sufficient.
The condition of the covenant that God hath made, is,
that Christ shall rule and have the government of those souls that he presents to God:
How should it be otherwise, seeing he is not to present any to God that are unclean?
Christ hath no commission to present any to God in their uncleanness and wickedness.
He that believeth, must be cleansed and purified by him: If so, then that cannot be done,
but by ruling over them.
If they had the rule of themselves, they would be polluted, and be like water,
whose current is stopped with dirt and mud, not running in its own proper stream.
People will commit sin, when they have the rule of themselves;
but when Christ presents people to God, and when they come to be led by him,
they are cleansed and purified.

When the apostle describes true faith, he doth it by this quality and property of it,
it purifies the heart.
All other faith is but the hope of the hypocrite; but real faith is the operation of God,
saith the apostle; and that faith worketh in an unclean heart to the cleansing of it,
and in an impure heart to the purifying of it: If the heart comes to be purified,
then it must needs follow that the conversation must be pure also.
No one doth an ill work, or speaks an ill word, but it is from an evil heart.
Now if the axe come to be laid to the root of the tree,
and the word of the Lord operate in the heart powerfully, if ever so much evil be in it,
the axe when laid to the root of the tree will cut it down;
the power of God will execute judgment upon everything that is contrary to him;
Christ is holy, harmless, and undefiled, and separate from sin and sinners;
and though he extend his life and virtue to the life
and soul of the most wicked man in the world,
it never joins with their uncleanness,
but keeps immaculate and undefiled in the heart of the worst of men.

Now this immaculate power that comes from Christ, it will purify the hearts of men,
and preserve them from evil thoughts, words and actions.
This is the manifestation of the one Mediator that they must be governed by,
else they cannot be presented spotless to God the Father.
There is a necessity of coming to a Saviour otherwise than by words and profession;
we must come to him and heartily join with him; we have all joined with the devil,
he hath suggested, moved, and instigated,
and people have followed his instigations and motions;
there is no man but is sensible of a devilish motion, why not then of a divine motion?
Though now it is become a bugbear to say, we are moved by the Spirit of Christ,
why not by that Spirit, as well as by the spirit of the wicked one?
No man doubts but that there are motions of the devil which they are sensible of,
that sometimes they have joined with him, and sometimes they withstand him.
What is the reason that men should join with evil motions?
There is no just reason for it.
The reason why you and I withstand the motions of the devil,
is because we find another motion conveyed into our hearts by the Spirit of God;
if a man hath one motion to commit uncleanness,
he hath another motion to keep himself pure; if he hath a motion to speak a lie,
he hath another motion to speak truth; there are two movers at the same time,
in the same heart, which shall we join with?
Shall I join with the devil`'s motion?
If I find anything of the love of God in my heart,
it will constrain me to mind the good motion, and make me withstand the evil motion;
so that the moving of the Spirit of God is not such a wonder.

There are none who have not had bad motions in them,
and they have also motions of the Spirit of truth; they have met with evil motions,
and they have admired them too much, then it is time to repent;
if there be a distinction between a motion of the Spirit of truth,
and a motion of the spirit of error, then I may boldly say,
it is our duty to join with the Spirit of truth, and not with the spirit of error;
if there be a desire in us to be saved from the wrath to come,
then the way to be saved from God`'s wrath is to be saved from the cause of it;
take away the cause and the effect ceaseth.
The cause of God`'s wrath being kindled against man is sin,
for God had no wrath against man when he first made him;
for he made him after his own image,
and gave him power to continue in that holiness and righteousness,
wherein he created him but he fell, and was cast out of paradise,
and an angel was sent with a flaming sword that turned every way,
to keep the way of the tree of life.
Thus man fell under the wrath of God by his sin;
but how shall I have the wrath of God allayed?
By breaking off from sin, and returning to God again.

This looks like a covenant of works, say some; do you say I must break off from sin,
and so escape the wrath of God?

Yes, I do; but no mortal man can break off from sin but by joining with the Mediator,
he is the author of eternal salvation, he worketh in us to will and to do,
and enableth us to work out our own salvation; it was sin that drove man out of paradise,
and brought upon him the wrath of God.
Sin is the devil`'s work; now that Christ might be a Saviour to us,
he will destroy the devil`'s work; "`for this purpose,`" saith the apostle,
"`the Son of God was manifested, that he might destroy the works of the devil.`"
Now the devil was not the destruction of man simply in himself,
but by tempting him to sin, which is the devil`'s work; and Christ was manifested,
to destroy the devil`'s work; that propensity to sin that is in the nature of man,
which makes him rebel against the mind and will of God.
Christ the eternal Son of God became man; he took the nature of man,
that he might bring man again to his primitive state,
wherein he was created after the image of God.

Now how doth the devil perform his works?
doth he do his works coercively?
No, he useth no irresistible force.
But doth Christ the Mediator work coercively, with an irresistible power and force,
to bring a man again to God?
No, no more than the devil did to beguile man from God.
Man might have stood and continued in his state of innocency if he would;
he might join with evil, and yield to the temptation of the devil, if he had a mind;
he knew if he gave over his mind to evil, he should be ruined; and it proved so.
Man was resolved to try what it was to yield to the devil, and obey him.
He told them that if they did eat of the forbidden fruit they should be as gods,
but they became more like the devil; this they got by being obedient unto him,
not that the devil laid an irresistible force upon them,
you shall eat of the fruit of this tree; but there was only a presentation of it to them,
and with that he prevailed, and so came to the destruction of mankind.

Christ the Mediator, in order that he may present us to God,
comes himself and presents his commands to us, and his command is,
that we must break off from that servitude and subjection
that the devil hath brought man into,
and there must be a subjection unto Christ; we must believe in Christ,
and hearken to the word of God, and break off from sin; but where is the power?
If God would have me holy, let him make me holy; if he would have me pure,
let him make me so, and give me ability to do that which of myself I cannot do;
when it pleaseth God to give me grace and captivate my will,
I shall become a good Christian.
Now here is a great mistake,
that people should think they must wait for an irresistible
power to bring them back to God;
there is a presentation of love and mercy, and earnest invitations,
and the long-suffering and patience and goodness of God`'s long waiting upon sinners.
"`God, who commanded light to shine out of darkness, hath shined into our hearts,
to give the light of the knowledge of the glory of God in the face of Jesus Christ,`" 2 Cor. 4:6.
What shall I do with the light that shines into my heart?
I will shut mine eyes against it; I love darkness rather than light,
and evil more than good; this light will lead me to holiness and righteousness,
I will quarrel with it, it comes to bereave me of my comforts in this world,
of my merry companions, and of all my bravery, I will not hearken to it.
Alas! for these; "`this is the condemnation, that light is come into the world,
and men love darkness rather than light,
because their deeds are evil,`" saith our Saviour.
"`If I had not come and spoken to them, they had no sin,
but now they have no cloak for their sin.`"

Here is the gospel preached by Christ himself;
here is the presentation of an opportunity for every man and woman to return again;
but I must be in the way of returning, that is,
by joining with that which presents to me holiness, righteousness, chastity and humility,
that presents and offers to the soul all the virtues and graces that are in Christ,
and shews it the light and grace that comes from Christ.
Now this light and grace shewing itself to my soul, I have a view of.
Hast thou a view of it?
Hast thou seen purity, humility, sobriety, meekness, and self-denial,
and an heavenly frame of spirit in thyself or somebody else?
How dost thou like it?
I like it not at all; I love to have honour and dignity, power and dominion,
and my elbow-room in the world; I love not this meekness,
humility and strictness of life, that a man must have a care what he speaks,
and set a watch upon his lips, and upon his heart, tongue, and hands,
I do not like this kind of life.

If thou dost not like a good life, somebody will like it, and live in it;
and notwithstanding all thy vapouring, thy hating, and despising it,
when people come to live this kind of life, they will outlive thee; thy proud life,
they reigning life, and thy having elbow-room in the world,
will at last come to be limited; the hand of God is against it,
and it will bring down the pride of man.
When thou comest to lie upon thy dying pillow, expecting every moment to expire,
and breathe thy last, then thou wilt say, O that I had been more serious,
and lived more like a Christian; lived a godly life, and given up my heart to God,
and been more watchful over my thoughts, words and actions!
There is such a friend of mine, that hath lived better than I;
if I had lived such a life as he hath lived, I should have had more comfort;
and they that are despisers of the godly, though they do not like such a life now,
they will like it then.

Friends, you that are lovers of your souls, and meet together that you may become better,
and have expectation and hope,
that you shall receive comfort and benefit by your meeting together, I tell you,
as a servant of God, and a lover of yours, it is but a little while,
and you will wish that you had chosen the most holy, harmless, innocent life,
that ever you saw yourselves, or heard of from anybody else;
and you will wish that you had been more watchful over your thoughts, words and actions.
There is a day, a day approaching,
when we must give an account for everything that we have done,
"`whether good or evil;`" you must give an account for your cursed debauchery;
for your swearing, lying, and inordinate passions;
you must give an account for every vain thought, and every idle word.

If this will certainly come to pass,
how shall I prevent these idle words and evil actions?
"`Wherewith shall a young man cleanse his way,`" saith the Psalmist?
"`By taking heed thereto, according to thy word.`"
I am not as those that say "`lo here and lo there:`" I do not say,
you must come and learn truth of me, but if you find it, you must find it in yourselves:
What if I live in the truth?
That will not serve _thee;_ and if I be a holy man, that will not sanctify _thee;_
thou must hearken to truth`'s speaking in thyself;
thou mayest hear it speaking in thine own heart;
you may hear it call you to righteousness and holiness; and if you hear it,
you may do it too, if you please; for there is a power that goes along with it.

I know enough, thou wilt say, but I cannot do what I know; I have not power.
What ails thee that thou hast not power?
If I had power, then would I abstain from all sin, and break off from my evil ways;
but the devil throws this object and the other object in my way,
and by his temptations he doth ensnare me, I have not power to resist:
Would you have me do more than I can do?
and as long as I have not power I am to be excused.

Now here is a device of the devil to keep people in his net still.
If men would be true to themselves, they would not be long without power:
If thou art convinced of the evil of thy ways,
and that it is thy duty to break off from sin, there is a power offered to thee, that,
if thou joinest with, thou mayest overcome all temptations, and forsake thy sin:
I would have you all prove, and search, and see whether I speak truth or no;
I am persuaded there is not a man or woman here but
they have sometime abstained from an evil work,
which they were tempted to.
How were you restrained; because you knew it was an evil work, you durst not do it;
the devil had not a coercive power to force you to do it; I knew it was an evil thing,
and I joined with that in my mind which dissuaded me from it;
and I prayed to God to give me power to abstain from it.
The devil tempted thee on still, who helped thee against the temptation?
God restrained thee by his grace.
Will not he be a present help unto thee?
he is the same yesterday, today, and forever; depend upon him still,
and he will be always ready to help thee, and support thee, and strengthen thee,
and thou shalt be kept from sin in an hour of temptation:
Consider that all power in Heaven and Earth is given to Christ,
and if he be able to keep thee thou shalt not fall into it; those that come unto me,
saith Christ, none shall pluck them out of my hands, and my Father is greater than all.
If thou comest unto Christ, he will in no wise cast thee out,
and if thou depend upon him, he will preserve thee,
and none shall be able to pluck thee out of his hand.
If thou join with the truth, and with that which is holy,
thou shalt have strength and ability to withstand temptation and overcome it;
and (I may speak with reverence) Christ hath bound himself to those that trust in him;
those that keep the word of my patience, I will keep them in the hour of temptation.
If I keep waiting upon his power, that is ready to help me,
and have a mind to be purified and sanctified,
and to have righteousness brought into my soul, and have mine eyes unto God,
and my expectations from him, he will work in me to will and to do of his good pleasure.

Now here people have a fixed foundation for their faith;
but there is no working at this rate without bearing a daily cross.
There are a great many can receive the truth in words, and receive doctrines, and tenets,
and that with delight;
but there is no practising holiness and righteousness without a daily cross and self-denial.
There are a great many who have come to truth, as far as it stands in words,
but when it comes to something that they must do, to speak the truth,
and live in the truth, they meet with so much of the temptation of the devil,
so much lust and corruption, and ungodliness in themselves;
they meet with such evil things that their souls join with and yield to,
that they cannot go on in the ways of holiness, unless they look up to Jesus,
and have an eye to their Saviour, and take up his cross and follow him.
Whatsoever reproaches, sufferings, and persecutions they endure,
they must have a godly resolution to follow the Lord Christ, and say,
I will obey his commands, he shall have the rule and government of my life,
and be the guide of my way; whatsoever stands in my way,
I will take up my cross and deny myself;
without this there is no good Christianity in the world.

There are a great many that seem to be religious and are professors of the truth:
We all know there are many professors of the truth in notion,
and with some zeal will talk of it;
but they do not know how to live and walk in the truth,
they do not live uprightly and honestly in it; they do not keep their words;
they do not live justly and honestly with all men,
nor do unto others as they would have others do to them:
They can tell how to speak and act; then why do they not do it?
They have got a notion that they are above the cross of Christ,
and self-denial is far below them.
People will not live in the truth.

This is wanting in the whole world:
If we look around we shall find a great many are illuminated;
there is abundance of knowledge and understanding among professors,
abundance of learning, and great numbers of learned men: What is the reason that oaths,
and curses, and all manner of wickedness run down the streets like a river;
there is pride, and wrath, and envy, and revenge, and violence to be found among us,
as if it would draw down vengeance upon us.
They have heard preached in pulpits much of holiness, humility, patience and meekness,
that a meek and quiet spirit is an ornament of great price:
Men have heard much preaching against pride, profaneness, and drunkenness,
and uncleanness, but they have heard it like a tale that is told,
not much concerned about it,
and have given little credit or regard to what they have heard of these things.
Why are people so wicked?
The reason at last results in this,
men are "`lovers of pleasures more than lovers of
God,`" they are not the servants of Christ,
but serve divers lusts, and pleasures, and are led captive by the devil, at his will;
and so they go on in iniquity.
No laws can restrain and curb them,
when the law of Christ is not written in their hearts;
but when men come to see a necessity of self-denial and taking up the cross,
this will produce a reformation.

This is what I labour for, and all good men and women will do it:
It is time to try for reformation.
Vain fashions, and garbs, and pride have been cried up,
why should not we cry for reformation before the
wrath of a provoked God is kindled against us,
and his vengeance poured down upon the nation?
We must reform our lives.
How shall men reform, you will say?
By getting the law of God within their hearts, that is pure, and holy, and heavenly,
that will be as a light to men`'s feet, and a lantern to their paths:
Now till people come to this they will go on in sin and iniquity,
till they be swept away with some overflowing and dreadful judgment.

So that, my friends, in the fear of God, and out of love to you,
I seek that you may be brought to God, through Christ;
that you may live in the love and fear of the Lord, and, when you come to die,
you may have rest and peace for your souls.
There is no rest for those that are evil-doers; "`there is no peace, saith my God,
to the wicked.`"
The ungodly cry, "`peace, peace,`" and talk of peace, but there is no peace for them,
but they shall have for their portion tribulation, and wrath, and anguish;
this shall certainly come upon everyone that doth evil.
It is no matter what religion you are of, if you do not obey the truth,
but live in unrighteousness.

Now, friends, my exhortation to you all is,
that you will return to the truth in your own hearts, and do it while you have time.
I am not persuading people to love my opinion,
but to love God`'s truth in their own hearts, to love it and obey it,
and you cannot do this unless you resolve to take up a daily cross,
and be followers of Christ,
who is gone before to prepare a place for them that are his true disciples;
and then he will present them to God, as holy, harmless, and undefiled,
for these are heirs of that everlasting kingdom,
which God hath prepared for them that love him.
