[short="Christ All in All."]
== Sermon XXXI. Christ All in All.

[.signed-section-context-open]
Preached at Devonshire-House, June 10, 1688.

The Lord Jesus Christ is the light, life and virtue that can only satisfy.
Christ is all in all.

There is nothing can satisfy the souls of the upright,
unless they feel life and virtue to flow from Christ Jesus; and this,
whether it flow instrumentally or immediately, always comforteth;
it always refresheth the upright in heart.

Therefore all they that desire satisfaction to their souls,
that meet together upon that account, they ought to have their eyes turned to the Lord,
that they may be capable to understand the ministration of the spirit,
whether in themselves, or through any other.
For while they are exercised outwardly,
and the dependence of their souls is upon that which is outward,
there remains a veil upon the mind,
that they many times hear excellent things spoken of the kingdom of God,
but they understand them not,
because they are alienated and estranged in their minds from that of God in themselves,
that should give them an understanding.
We never pretend to give people an understanding, we have always said,
that is the work of God.
We have spoken many things of the kingdom of God,
excellent things have been revealed to us by his holy spirit,
and the same spirit hath given us utterance,
to speak of the great things of the law of God; yet many,
that have been constant hearers of these things, remain ignorant, and are insensible,
because they are not exercised in their own measure
of the grace and light of the Lord Jesus Christ,
by which they should receive and understand them.

This hath made me often lament the case of many of the people of this city and nation,
who are daily hearers of the word of God preached, and retain it not in their hearts:
The sowers are gone out to sow, but many receive it in the high-way-ground;
the way that everything can pass in, there they receive the word sown,
and the devil catcheth it away; and though they have heard excellent things,
of the strength, ability and power of God, that he ministereth to his people,
they remain so weak and so feeble,
that they are blown away with every blast of the adversary, with every temptation,
and with every snare and gin that is laid for them, they are caught, and ensnared,
and taken; and so these come to meetings again and again, one year after another:
I might say unto you, wherefore do you come?
It may be you may say, we desire to be satisfied; we desire satisfaction for our souls.
Do you so?
Then I tell you, you may come all the days of your life, and want it,
and lay down your heads in sorrow at last for all that.
For all the words in the world will never communicate that heavenly
life and virtue which brings true satisfaction to the soul,
unto any, except to those that have an exercise in their own mind and spirits,
in that which they have of God;
they must first be brought to know the way they should walk in,
and to believe that is the way: When people believe this is my way,
the light within is my way, the grace of God is my way; that searches and tries my heart,
that is my way I must walk in, speak in, and think in, and do all that I have to do in;
when I believe this is that way,
then this belief obligeth men to take heed to their ways, to their footsteps.
And here they that are thus exercised,
are in a tender care every step they take in their way;
and so perhaps they may receive great benefits by hearing the reports
they do daily hear from those that were in the way before them,
and have travelled further in it, than they ever yet have done.
The experiences of the servants of the Lord, are daily helpful to them,
and they are daily comforted, strengthened, and confirmed, to hear how they have sped,
that have travelled through their condition, and through their present state;
the helps and advantages they have met with, will do thee good, and comfort thee:
But what is this to those that are not in the way, that have not faith in the way?
Though they have a clear belief of the doctrine and way itself,
yet they are not exercising themselves to walk therein;
for they do but as the rest of the world, saying, this good man, and the other good man,
made a good sermon.
Why was it good?
Not for any good they found by it, but because he raised his doctrine well,
and proved it from the scripture, therefore we are obliged to believe it.

But now this good doctrine, if it be ever so good, and ever so firmly proved,
it brings forth no fruit to the amendment of life, saving in them that believe,
saving in them where there is an exercise in the fear of God,
where people are concerned for their soul`'s satisfaction.
For they that look for true satisfaction by this, or that, or the other way of the world,
they spend their days without satisfaction, and so at last they die in sorrow;
and so it will be to the end of this, and all succeeding generations.

And therefore, my friends, though I confess it is not a grief to me, but a joy,
to see people willing to hear the truth, and to come together in great assemblies;
tho I say, this is not a grief, but a joy,
for I am not about to discourage them that do so: Yet I must be plain with you;
I know what I say, and you will know it too one day, that all this meeting together,
and gathering in great assemblies, and hearing what is preached to you,
with ever so great delight to your minds, it will do you no good,
unless you believe in the grace of God,
that hath been ministered to you through Jesus Christ.

And when people come to this foundation, and build on it,
and grow every day more and more diligent in the exercise of their minds towards God,
and examine their way, and examine their footsteps, how they have walked yesterday,
how they have walked this day, and how their minds are exercised at this present time,
whether they have answered the grace of God; when they come to be thus exercised,
they will look upon themselves as bound in duty to give account to God every moment,
for their thoughts, words and actions.
When they are thus exercised, then let them come to meetings in the name of God,
and hear the experiences of them that have gone before them,
and treasured up sayings in their hearts for their encouragement,
and they will find this will be a help to them:
But if people go and build a religion upon the sayings of this and that man; nay,
were it upon the sayings of Christ himself and his apostles,
if they were here to preach to them, and build a religion upon their words, and sayings,
and doctrines, without the operations of the Spirit of God upon their hearts,
inclining them to holiness and righteousness, this religion will do them no good:
By this, to make the best of it, they might make a shift to reach to a form of godliness;
people conforming themselves outwardly, to the outward precept or command from without,
it might amount to a form of godliness; yet it might be supposed and granted,
that the power of God, the power of divine life and virtue, where it comes,
it doth sanctify and season the mind,
and bring men into an awful reverence of the living God, their Maker,
that they might stand in awe, and not sin against him; for here is the life of religion.

This hath a great difference from the manner of building men in religion,
that many have been acquainted withal.
They tell us, our fathers before us were built up in these forms, and modes,
and methods of religion; they received so many doctrines, ordinances,
sacraments and articles; and when these are received, believed and professed,
there`'s a saint for you, there`'s a child of God, and a member of the church.
How came he to be so?
He was instructed in all the principles of the Christian religion,
and subject to all the ordinances of the church, saith one; and saith another,
he could speak excellently concerning the doctrine of our religion;
therefore he is certainly a child of God, and a member of Christ;
but all this acceptation of the principles of the Christian religion, of doctrines,
and ordinances, and sacraments; all this will not amount to the purifying of the heart,
and cleansing and purging of the conscience; nay, it would not come to a far less matter,
to the bridling of the tongue; but they would be in a passion upon the least provocation,
and upon the least disgust and distaste given them,
their tongues would run over into wrath, and into wantonness, and profaneness;
and upon any occasion and provocation given, their corrupted words would prevail,
and lead them into deceit and covetous practices;
and though the fruits and works of the old man remain,
yet they will follow the principle of the regenerate, as far as they consist in words.

If our Lord Jesus Christ say,
"`except a man be born again he cannot enter into the kingdom of God,`"
then this old corrupt birth will preach a sermon upon this text,
and profess it.
How many have taken upon them to preach a sermon, upon some excellent sayings of Christ,
that never knew what regeneration was; for the new birth always hath a new life;
but they have lived the life of carnal corrupt fallen man,
and yet preach a sermon upon regeneration: Thus the minister hath done,
and the people have believed him, and have been gathered into such and such a church;
for most put themselves into one church or other; they have been covenanted Christians,
members of a church; but they have wanted that which makes a Christian, a religious man,
viz. "`the answer of a good conscience.`"

A true Christian, he is bound to be an obedient child unto God,
that begat him of his own will, by the word of truth;
and such a one may be in expectation of an answer of peace from God,
through Jesus Christ, in whom he hath believed, and by whom he is reconciled to God.
If you take away this new birth, and this new nature, and an answer of peace,
from God to the soul, then tell me what the Christian religion is,
more than the religion of Heathens and Pagans, that worship stocks and stones?
All the rest is but talk, and men are never a whit the better for it:
One man may excel another in talk and discourse:
A debauched man many times hath been able to talk at a great rate,
and to speak notable things; and some have been ready to say,
it is a pity a man of such excellent parts should lead a wicked life:
But alas! if such a one can talk of the power of God still,
and the devil hath power over him; or if he speak highly of the wisdom of God,
yet he himself plays the fool abominably; so that by such a kind of life,
and such a kind of religion, people never attain to satisfaction; after forty, or fifty,
or sixty years spent therein, they must after all, lay down their heads in sorrow,
when they have been constant keepers to the church, and sayers of their prayers,
and receivers of the sacrament, and steadfastly believe the articles of the creed,
and make profession of all the parts of the Christian religion; yet after all,
they must lay down their heads in sorrow: Why, what is the matter?
what did they want?
They wanted faith in the power of God, that should enable them to overcome their sin,
and live in obedience to God; and they wanted to their outward profession,
the "`answer of a good conscience,`" and justification through Christ the Mediator.

They talked of redemption through Jesus Christ, but were never redeemed from their sins:
This is so evident and plain, that there is no speaking to the contrary:
If you see a drunkard, or a swearer, or an unclean person, and if he shall preach,
and make an excellent sermon of the redemption that there is in Christ,
and therein tell you, what great benefits they receive by Christ,
that are true believers; and that Christ is a Redeemer,
and redeemeth them from the curse of the law, and from the guilt of sin,
and reconcileth them to God; so that he that was under the curse of the law,
and an heir of wrath, is now a child of God: Now if you come to examine this man,
and ask him, whether he is redeemed, and delivered from sin,
so that sin hath no more dominion over him, he will tell you, no: What, not redeemed,
when thou hast been a believer thus long?
Art thou still under the bondage and captivity of sin?
Then thou art under the government of some other master than Christ;
some other master hath rule over thee, if thou art not redeemed from thy swearing, lying,
drunkenness, and uncleanness; if thou art led to these things,
thou are under the power and government of some other master than Christ.
Now this hath startled people, when they have been thinking,
that they have been baptized persons, and professing Christians,
and they have flattered themselves with a groundless confidence, let me die when I will,
this night, or tomorrow, I shall be saved by Christ; I am an heir of the kingdom of God:
Let me tell thee, thou dishonourest the name of God by thy presumption.

When people come to examine matters, and read over the book of their consciences,
and see what servants they have been to the devil,
how the devil hath led them up and down at his will,
those that were covenanted Christians, followers of Christ;
when the devil hath said to them, follow me, then sayest thou I will;
when the devil saith, follow me to this and the other evil thing, I see I cannot resist;
I cannot withstand the temptation; I was overtaken, and surprised,
and led away by such an allurement, and ensnared by it: I pray thee leave off professing,
for thou disgracest the Lord Jesus Christ; he and his disciples did not so:
He was tempted as thou art, and his disciples were tempted as thou art;
so were Christians of old time;
and Christians that live in the present time do meet with many temptations,
but they are not at the devil`'s beck and call, as thou art.

The apostle Paul, in one passage of his life, we find came to be awakened and startled:
There was a light from Heaven shone about him,
he heard the voice of Christ speaking to him, "`Saul, Saul, why persecutest thou me?`"
and he said, "`who art thou Lord?`"
and the Lord said, "`I am Jesus whom thou persecutest;
it is hard for thee to kick against the pricks;`" and he trembling and astonished said,
"`Lord, what wilt thou have me to do?`" Acts 9:4.
He was brought to this pass after his convincement,
but before that he was overcome and led captive; and when he would do good,
evil was present with him: "`To will,`" saith he, "`is present,
but how to perform I know not;`" but he did not call this a happy state.
He did not say then, I am in a good condition,
when I am led captive by the devil at his will: The good that I would do, I do not,
and I am carnal, and sold under sin: He doth not say, this is a good condition,
I am satisfied with it; see what he calls that condition;
he gives it a more right name than many do now-a-days, that say,
this is the state of God`'s children;
that the best of all God`'s children have not power to live without sin,
and overcome all their corruptions, that they sin in their best duties,
and can do nothing but sin,
and that sin mixeth itself in all their holy duties and performances:
Many of their ministers tell them,
that if they think they can perform any duty without sin, they deceive themselves,
and run the hazard of being accursed.
But they learned not this of Christ, but of some other matter.
Paul gave this state another name;
I would you were as wise when you are in this state and condition.
"`O wretched man that I am, who shall deliver me?`"
I see a wretchedness in this condition; I see, if I be not delivered out of it,
I must perish to all eternity.
This is not a state to live in; who can live at ease in such a condition as this?
Who can but cry out, who shall deliver me from this body of sin and death?

Alas! we hear no such cry now among priests or people, and separate congregations:
I fear this cry is almost lost among us,
unless it be some few that hear the voice of God,
and feel such a stroke of the divine power as Paul did, and answer to the heavenly voice.
I confess that I myself have heard such a cry,
and have been sensible of my woeful captivity and bondage, by reason of sin.
And though I had a mind to do good, I could not do it;
it was my desire that I might sin no more, I would not sin against the Lord,
if I could avoid it; and when I would do good, I found that evil was present with me;
but I was far from sitting down there, and saying,
this is the state and condition of God`'s people;
it is as well with me as it was with the apostle Paul,
therefore I will sit down in this state:
The people of God cannot find satisfaction in such a state as this; though I confess,
that God`'s peculiar people at first came to this state, for their conviction;
and the opening of their minds, and enlightening their understandings,
to see the evil of their ways; but they do not come to this state, as to their rest,
and then persuade themselves that they are in the condition of the children of God;
but they give their state a right name, and cry out,
"`O wretched wan that I am!`" what a miserable condition am I fallen into!
I did not see it before: Now my eyes are opened, now my understanding is illuminated,
now I see that the corruption of my nature prevails against the grace of God;
and when I would join with the grace of God, and the motions of his Holy Spirit,
the enemy is present to lead me away; I am not now in a happy state,
but I am so far advanced that I am convinced of my
miserable and wretched state and condition;
if some way or other be not found for my deliverance,
I shall never see the face of God with comfort.
Then arises that cry, "`who shall deliver me?`"

Thus the apostle Paul (Rom. 7) sets forth the state of his convincement,
and how miserable a condition he was in: Then he goes further,
and tells you how it was with him: "`I thank God, through Jesus Christ our Lord.`"
O! I have cause enough to thank God, I am not a wretched man now, I am not carnal,
sold under sin; I am not led captive by the devil at his will now.
Why how so?
the apostle saith, "`the law of the spirit of life in Christ Jesus,
hath set me free from the law of sin and death.`"
Here is something to glory, and to comfort the soul in:
The law of the Spirit of life triumphed in his soul,
and delivered him from the law of sin and death, and redeemed him from the power of sin,
and made him serve God with freedom and liberty.
"`I thank God, through Jesus Christ our Lord:`" I would have all come to this,
to thank God; not only in words, but in reality, in deed and truth.
For one may teach a _parrot_ to talk over these words;
but it is the law of the spirit of life in Christ Jesus,
that will make you free from the law of sin and death.

This is a hard lesson, therefore you must go home into your own consciences,
before you can make a right judgment of things, and give a right answer to yourselves.
The law of the spirit of life will set thee free from the law of thy passion,
and of thy pride and covetousness, and sensuality,
and the law of thy carnal inclinations.
Art thou set free from these?

Now when people come to examine themselves, they have no way to flee to,
but they must take up a daily cross, and trust to the Lord Jesus for their deliverance;
who hath enlightened them, to see their wretched and woeful state;
and illuminated their understandings, that they might come to him,
in order to their being delivered from the dominion of sin.

The greatest part of the world think this is a thing impossible,
and therefore do not hope to be set free from the bondage of their sins.
Which of these ways is it that thou takest?
I am afraid many of you have taken the wrong way: I judge no one in particular,
but I speak this in faithfulness and love to your souls.

If there be any here, that are sensible of their sins,
and in a captivated state under sin and Satan,
who have despaired of ever being set at liberty, and have said,
it is a vain thing to expect it; for some learned men have told them,
that there is no deliverance from sin in this world,
therefore it is in vain for me to strive,
in vain for me to engage myself in a continual care and conflict,
in a continual warring and watching against sin;
for this deliverance can never be obtained in this life:
It is in vain to seek for a thing that can never be found,
and to strive for that which can never be obtained.
If there be any such here present, I have this to say to them, that the Lord,
in his infinite mercy, hath done two great things for you,
to help you out of this despair,
of obtaining a full deliverance from the bondage of your sins.

First, God hath placed a witness for himself in your bosoms, in your consciences.
Let me ask you, have ye not got victory over many sins and temptations,
that you have been assaulted with, from your childhood to this day?
I might challenge any person in this assembly,
when a temptation hath been presented before you,
hath there not been something within you, to tell you of the danger of complying with it?
Hath not thy conscience warned thee, and called upon thee, O take heed,
do not this evil thing, do not cheat thy neighbour, do not commit this sin;
whether drunkenness, or uncleanness, or whatsoever sin thou wast tempted to: Now,
didst thou join to that voice in thine own conscience?
And did it not help thee over the temptation?
And when thou didst escape the sin, wast thou not glad of it?
and didst thou not rejoice that thou obtainedst victory over it?
Satan laid a snare, and an opportunity before me, to commit such a sin;
but I did not join with it, and now I am glad of it.
It was not only the devil`'s fault, for he came to his own,
but there was an evil inclination in my heart to it:
How came it to pass thou didst not do it?
I knew it was a sin against the Lord.
How didst thou know that?
I knew in my conscience, that if I did it, I must sin against light,
and against conviction, and against grace received;
and that was the reason I did not do it.
Thus thou acknowledgest thine own conscience helped thee against the temptation.

Now I appeal to all your consciences, that hear me this day,
whether God hath not done this kindness for you;
and there is none here but hath been some time helped out of temptation?
I do not believe that ill of any,
that they comply with all the temptations they meet with,
but the light in their consciences hath shewn them the evil of sin,
and they have been kept out of it, and they have been glad of it afterwards.

Now this is one great kindness, which God hath done for everyone of you,
in order to help you out of this despair of being delivered from your sins.

Despair in the common notion of it,
is that which makes a man doubt of his eternal salvation:
"`I shall go to hell when I die; there is no mercy for me.`"
This despair hath so wrought upon people, that many have lost their wits,
and common sense, and at last made away with themselves;
many have been distracted and undone in this world, while they lived in it,
and at last have dispatched themselves out of it.
And there is another despair; a despair of getting victory over their corruptions,
and obtaining a freedom from sin: This latter despair,
this nation is generally fallen into;
though the effects of the other despair is lamentable to behold,
the effects of this will be as bad one day,
if not prevented by rectifying that mistake men lie under.
Why shouldest thou despair of the power of God to help thee, and of the grace of God,
and of the good will of God for thy deliverance?
if thou wilt not join with the grace of God,
and the power of God that is ready to help thee, and give deliverance from thy sins,
the consequence will be dreadful at the last.
Therefore believe in that grace of God, which hath helped thee against some temptations,
and given thee victory over some sins, that it will, if thou faithfully join with it,
give thee victory over all.

Secondly, Consider God hath done another kindness for thee,
he hath sent his light and truth into thy heart, to engage thee in a war against sin:
There are a great many faithful soldiers of Christ,
that have fought this battle before you, and have obtained the victory,
and they will tell you, they never went out to war in their own names,
but in the name of the Lord Jehovah: When they relied upon him,
and in meekness and fear waited upon him, he gave them power to overcome;
and they were made conquerors,
and "`more than conquerors;`" for they have overcome those enemies,
that sometimes overcame them; and Christ hath fixed and settled them in this conquest,
never to be overcome more.
Here is both an outward and an inward evidence: The outward evidence will do you no good,
till you come to lay hold of the inward evidence in your own hearts;
then the outward evidence that God sends, will be serviceable to you.

Therefore, my friends, I tell you (as I said before) nothing will satisfy the soul,
but the virtue and life that flows into it from the fountain of life;
here is the way to it.
If you should hear of a treasury,
and store of bread laid up for all that are willing to come to it;
if you knew not the way to come to it, and were ready to perish with hunger,
what a cry would there be among you!
If a man should come and tell you where there is such a treasury of bread,
when you are ready to perish with hunger,
and tell you the way to it is intricate and narrow, but that he himself hath been there,
and that he can tell you the ready way to it, and that he himself had relief and supply,
and great plenty bestowed upon him, and that he would bring you thither,
O how welcome would such a one be to you!
O that you were as wise in spiritual things, and as much concerned for your souls,
as you are for your bodies, and would take the advice of God`'s ministers!
They would turn you to the light within; the grace of God in your own hearts,
which you are partakers of; and speaking to you in the name of God,
desire you to follow the duties of your own consciences,
and you will come quickly where there is bread enough.
By that light within, you will see your state is not so good as you imagined it was.
This oracle within, is that which you must live with, and dwell with;
you must go home with it, and lie down with it, and you must rise with it,
and follow the dictates of it; if you do so, before the week be out,
you will have experience to tell me, if I should come and ask you,
I have got more victory over my sins,
by following the dictates of the light of the grace of God within my own bosom,
than by all my reading, hearing and praying, and performing other duties.

Make a trial of this, and you will find the presence of God with you,
and that he is a God at hand, and not afar off;
and if you buckle on your spiritual armour,
the captain of your salvation will not be far off, but be present before you.

Therefore keep your eye unto Jesus, the author and finisher of your faith,
and you will be able to do all things through Christ that strengthens you;
and you will be able to conquer those sins and temptations that have conquered you.

May the law of the spirit of life in Christ Jesus, break down the body of sin and death,
and bring you into the glorious liberty which God hath prepared for his children.
